### PR TITLE
Register TwoBasedIndexing

### PR DESCRIPTION
**Pull request by simonster**

### CODE REVIEW

**Comment by quinnj** [comment]
Finally! Woot! +10000000. Been waiting to integrate this into my open-source enterprise-grade software project for financial stuffs.

**Comment by malmaud** [comment]
Sir, I have 1000 teragigavolts of web-scale data distributed across 10^6^6 machines. Most machines are ti-83 graphing calculators, but some are pocket watches. They are each running OS/2 but with a custom 4-bit kernel. How I integrate this package into my workflow?

**Comment by dcjones** [comment]
:+1:  With the longstanding 1-based indexing issue solved we can finally start using this language to implement real software, the kind of software that would make Dijkstra nod his head in solemn approval, and not just silly linear algebra nonsense.

**Comment by one-more-minute** [comment]
What this code do?

**Pull request merged**
