### PR TITLE
Tag SimpleTraits.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [mauro3/SimpleTraits.jl](https://github.com/mauro3/SimpleTraits.jl)
Release: [v0.6.0](https://github.com/mauro3/SimpleTraits.jl/releases/tag/v0.6.0)
Diff: [vs v0.5.1](https://github.com/mauro3/SimpleTraits.jl/compare/e2c5572557a5f4b995ce6c29547e4589a2d4d536...69f71f9c08263f7a97cc38e54703cd88d02e0808)
`requires` vs v0.5.1: 
```diff
--- 0.5.1/requires
+++ 0.6.0/requires
@@ -1,3 +1,3 @@
-julia 0.5
+julia 0.6
+Compat 0.26.0
 MacroTools 0.3.2
-Compat 0.19
```
cc: @mauro3

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by mauro3** [comment]
The failure in JuliaCIBot https://juliarun-ci.s3.amazonaws.com/33336c3d24abaa51de04748d04ee25e34730e5c1/pull_request_of_SimpleTraits_on_julia_0_6.log is because it runs with `--code-coverage=user`.  However, one of the tests checks that the code generated for the traits dispatch is as efficient as without trait dispatch by looking at the numbers of llvm lines produced.  That fails when code-coverage is on, see: https://github.com/mauro3/SimpleTraits.jl/pull/41#issuecomment-296444643.

Can code-coverage be turned off on JuliaCIBot somehow for SimpleTraits?

Alternatively, I should guard the tests in a `if Base.JLOptions().code_coverage!=1...`.

**Comment by mauro3** [comment]
Ok, I added a guard`Base.JLOptions().code_coverage==0....` to the offending test.  Now JuliaCIBot should pass.

**Comment by andreasnoack** [comment]
`ERROR: LoadError: LoadError: The following tags for SimpleTraits have not been pushed to upstream repository: 0.6.0.`

**Comment by mauro3** [comment]
Sorry, I messed it up and based the Julia-0.6 branch off the wrong commit!  Now I re-did the tag.  I hope this time it works...

**Comment by aviks** [comment]
I believe we just run `Pkg.test()`.  How do you run your tests on Travis?

**Comment by mauro3** [comment]
The standard test invocation is (or was at the time I copied the .travis.yml file):
`julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("SimpleTraits"); Pkg.test("SimpleTraits"; coverage=true)'`
see 
https://github.com/mauro3/SimpleTraits.jl/pull/41/files#diff-354f30a63fb0907d4ad57269548329e3L17 . 
Also the [log](https://juliarun-ci.s3.amazonaws.com/33336c3d24abaa51de04748d04ee25e34730e5c1/pull_request_of_SimpleTraits_on_julia_0_6.log) shows that `--code-coverag=user` is set.
So, what I originally did was to remove the `coverage=true` in the .travis.yml file.  

But I think the setup as I have it now is better, where I only run those particular tests when no coverage is enabled.

**Pull request merged**
