### PR TITLE
ArbFloats v0.1.7

### PR DESCRIPTION
**Pull request by JeffreySarnoff**

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
updated (specialized routines for Rationals) by pushing new commits to my copy of metadata-v2

**Comment by tkelman** [comment]
Do you want all of 0.1.3, 0.1.6, and 0.1.7 to be tagged here? Your merges pulled in an unrelated commit from mbauman.

**Comment by tkelman** [comment]
Git tags for 0.1.6 and 0.1.7 aren't pushed to https://github.com/JuliaArbTypes/ArbFloats.jl/releases yet

**Comment by JeffreySarnoff** [comment]
Those later tags have important stuff, I do want them. How do undo my errorful merge? Or otherwise get them pushed right.   (Also -- it is possible that one of the 0.1.3 sha values (in ArbFloats or in METADATA) is not copacetic -- do I care, can I remedy that?

**Comment by JeffreySarnoff** [comment]
@tkelman It seems that the tags 0..1.6, 0.1.7 got lost , but the commits that happened to get to each of those tagged places still exists -- I guess I should make v0.1.6 whatever is current, for safety if nothing else.  UNLESS there is a clever way to reput the tags that does not require my knowing exactly when I thought to increment those tags.

**Comment by JeffreySarnoff** [comment]
@tkelman the after v0.1.5 commits here look like they are all present
[https://github.com/JuliaArbTypes/ArbFloats.jl/compare/v0.1.5...master](https://github.com/JuliaArbTypes/ArbFloats.jl/compare/v0.1.5...master)

**Comment by tkelman** [comment]
I see https://github.com/JuliaArbTypes/ArbFloats.jl/commit/f9167077f8ff87e3dc6733949be31013c8e1b698 for 0.1.7, and https://github.com/JuliaArbTypes/ArbFloats.jl/commit/bd023ebcd26843e27a369473bb1db64f660c965b for both 0.1.3 and 0.1.6 (the same commit).

It would be cleanest to rebase this branch and either force push over it, or push a cleaner version to a new branch and open a new PR. Though I think since the commit here made the same change as mbauman's merged url change, it would be harmless to leave it.

**Comment by tkelman** [comment]
I see what you mean now about 0.1.3. The git tag is https://github.com/JuliaArbTypes/ArbFloats.jl/commit/1d5d779f6cfe09d58d8aeeac490de087c4076ad0, metadata says a different sha. You can fix the latter by editing https://github.com/JeffreySarnoff/METADATA.jl/blob/metadata-v2/ArbFloats/versions/0.1.3/sha1

**Comment by JeffreySarnoff** [comment]
I want to clean it up.

**Pull request closed without merging**
