### PR TITLE
Register DataAssim [https://github.com/Alexander-Barth/DataAssim.jl.g…

### PR DESCRIPTION
**Pull request by Alexander-Barth**
…it]: v0.0.1

I am currently porting some of Matlab/Octave data assimilation code to julia. This initial release implements various Kalman Filter algorithms.

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
I just merged the pull request "test against both 0.4 and 0.5 on travis CI"  (Thanks, Tony for your suggestion!). Do I need to redo a pull request to register DataAssim.jl ?

**Comment by tkelman** [comment]
travis-only changes don't need re-tagging, it won't make a difference to what users will get

**Comment by tkelman** [comment]
What is the license of the code this was ported from?

**Comment by Alexander-Barth** [comment]
The original code had also the license LGPL 3+:

https://sourceforge.net/p/sangoma/code/HEAD/tree/tools/trunk/

**Pull request merged**
