### PR TITLE
Tag StatsModels.jl v0.2.4

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/StatsModels.jl](https://github.com/JuliaStats/StatsModels.jl)
Release: [v0.2.4](https://github.com/JuliaStats/StatsModels.jl/releases/tag/v0.2.4)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/StatsModels.jl/builds/371205664)
Diff: [vs v0.2.3](https://github.com/JuliaStats/StatsModels.jl/compare/9bbc2a7404e75250f37f854d16233f0b0ce9bf15...dc070dc73f2de92e6c9816c3b696388307295031)
`requires` vs v0.2.3: 
```diff
--- 0.2.3/requires
+++ 0.2.4/requires
@@ -2,3 +2,4 @@
 DataFrames 0.11.5
 StatsBase 0.20.1
 Compat 0.63
+ArgCheck
```
cc: @kleinschmidt

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like this is breaking some packages downstream so it would be good to add some upper bounds to the failing packages.

**Comment by kleinschmidt** [comment]
What's the recommended procedure for adding an upper bound when master has diverged from the last release...make a PR against the latest release tag for a patch?

**Comment by andreasnoack** [comment]
They can just be added here in METADATA for now. The package maintainer can then do what they think is right in their package repo, i.e. put an upper bound or fix the package before a new release.

**Comment by andreasnoack** [comment]
Superseded by #14429

**Pull request closed without merging**
