### PR TITLE
Register new package DynamicalSystems.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Datseris/DynamicalSystems.jl](https://github.com/Datseris/DynamicalSystems.jl)
Release: [v0.1.0](https://github.com/Datseris/DynamicalSystems.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/Datseris/DynamicalSystems.jl/builds/268367268)
cc: @Datseris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@Datseris This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by ararslan** [comment]
Since you import StaticArrays and OrdinaryDiffEq in your tests, those should be declared as test dependencies in a test/REQUIRE file.

**Comment by Datseris** [comment]
@ararslan Sorry, I actually had no idea that a second require file could exist in the test folder.

I've added it with the latest commit (I've made it require ForwardDiff to be more general as I may add more tests)

**Comment by ararslan** [comment]
Awesome, thanks!

**Comment by Datseris** [comment]
Hello, if there is something wrong with the package please let me know so I can fix it. (I had it as my summer goal to announce this before September so I would appreciate it if it is possible)

**Comment by tkelman** [comment]
You use StaticArrays without listing it in REQUIRE here, should fix that (including in place in the requires file for this first tag, so Pkg doesn't think there are any versions that don't depend on StaticArrays)

**Comment by Datseris** [comment]
I thought that since I am requiring `ForwardDiff`, and since `ForwardDiff` requires `StaticArrays`, there shouldn't be any issue. I will also add `StaticArrays` as well then, since there is some issue.

**Comment by tkelman** [comment]
StatsBase and RecursiveArrayTools as well.

Not all versions of ForwardDiff (past and future) are always guaranteed to depend on everything you use directly.

**Comment by Datseris** [comment]
@tkelman of course, you are completely right. I was just justifying my (faulty) train of thought.

Attobot cannot tag this again anymore, it gives me error of "Cannot tag a new version "v0.1.0" preceding all existing versions.:".

Should I make a new version 0.1.1 instead or should something else happen?

**Comment by tkelman** [comment]
you can propose a PR that changes just the requires file for the existing tag in metadata, leave the sha and the git tag for this first version alone. change REQUIRE in the package on master before your next tag

**Comment by Datseris** [comment]
I have already deleted and re-did version 0.1.0 (as suggested by attobot), will what you mentioned still work? (unfortunately I do not know about sha). If yes i'll simply do it, it's very straight forward!

**Comment by tkelman** [comment]
those attobot instructions only work for pending pr's, not tags that have already been merged. best to put the git tag back at the sha that was listed here.

requires can be edited at https://github.com/JuliaLang/METADATA.jl/edit/metadata-v2/DynamicalSystems/versions/0.1.0/requires, propose a pr, and it's okay for the metadata copy to be slightly different than the package copy at the tagged sha (metadata takes priority)

**Pull request merged**
