### PR TITLE
Register new package FixedNumbers.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [perrutquist/FixedNumbers.jl](https://github.com/perrutquist/FixedNumbers.jl)
Release: [v0.1.1](https://github.com/perrutquist/FixedNumbers.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/perrutquist/FixedNumbers.jl/builds/419613426)
cc: @perrutquist

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@perrutquist This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by perrutquist** [comment]
Considering if I should name this something else. Please don’t merge yet.

**Comment by rfourquet** [comment]
As you mention it, I also wonder whether a better name could be found. I initially thought it would be a package implementing fixed-precision integers, like `UInt256` etc. I don't have a good suggestion... maybe `TypedNumbers`, or `StaticNumbers` ? FWIW, they are named `integral_constant` in C++ (IIRC).

**Comment by perrutquist** [comment]
Yes, I am strongly leaning towards `StaticNumbers` at the moment. Especially since I’ve added support for ranges with fixed length. They would be `StaticRanges`, and when they are used to create a `view` the size is inferrable from the type, so fits into `StaticArray` nomenclature.

**Comment by perrutquist** [comment]
After renaming the package, attobot decided to open a new PR instead of modifying this one.
Please close this PR and see #18804 instead.

**Pull request closed without merging**
