### PR TITLE
Register and tag Gunrock.jl

### PR DESCRIPTION
**Pull request by ranjanan**
[Gunrock](https://github.com/JuliaComputing/Gunrock.jl) is a package for graph algorithms on GPU.

### CODE REVIEW

**Comment by tkelman** [comment]
Encouraging users to modify a version controlled file means Pkg.update will not work on this package.

**Comment by ranjanan** [comment]
Oh okay. I asked the user to change `path_to_gunrock` in `consts.jl`. Would you suggest I locate it automatically, in the form of an `init()` ?

**Comment by tkelman** [comment]
Or use BinDeps, or make a separate file that sets the location but is in .gitignore.

**Comment by ranjanan** [comment]
Alright, should I tag another release after this fix?

**Comment by tkelman** [comment]
yes you can push an 0.0.2 tag to this same branch

**Pull request closed without merging**
