### PR TITLE
Register LCA.jl Package

### PR DESCRIPTION
**Pull request by fundamental**
LCA.jl provides an implementation of the Locally Competitive Algorithm, a sparse approximation algorithm originally designed for analog implementations.

### CODE REVIEW

**Comment by ararslan** [comment]
Hey @fundamental, looks good overall. I put in a PR to move stuff around a little bit. In particular, the code that uses PyPlot should be separated from the package code, otherwise PyPlot should be declared a dependency of the package.

**Comment by fundamental** [comment]
@ararslan Thanks again for taking the time to make a PR. Let me know if you think I should update the tagged version, though it shouldn't be an issue as the "using PyPlot" in the v0.0.1 tag was within an "if(false)" block.

**Comment by ararslan** [comment]
Yeah, the current tagged version should be fine. I guess the only thing at this point is that we typically discourage acronyms in package names unless they're quite well-known. Is that the case for LCA? I've not heard of it, so I just wanted to check.

**Comment by fundamental** [comment]
Within literature/in-person-interactions discussing/referencing LCA is typically referred to as 'LCA' and not the full 'Locally Competitive Algorithm'. So, at least within the signal processing community LCA should only refer to this algorithm. 

If relevant, (for context) I have worked indirectly with several individuals publishing work specifically on LCA (including a dissertation and one of the original algorithm creators) and several individuals working in the sparse signal processing subfield. While working with said individuals I do not recall any of them mentioning any conflicts with the 'LCA' abbreviation.

**Comment by ararslan** [comment]
Good enough for me!

**Pull request merged**
