### PR TITLE
Tag SingularIntegralEquations.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaApproximation/SingularIntegralEquations.jl](https://github.com/JuliaApproximation/SingularIntegralEquations.jl)
Release: [v0.3.1](https://github.com/JuliaApproximation/SingularIntegralEquations.jl/releases/tag/v0.3.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaApproximation/SingularIntegralEquations.jl/builds/344804345)
Diff: [vs v0.3.0](https://github.com/JuliaApproximation/SingularIntegralEquations.jl/compare/aa6426f512fb826530be862f12ef6ac9aeb91b14...f0f674795e4ac4556e7315c3b813d061cf92a034)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.3.1/requires
@@ -1,5 +1,5 @@
 julia 0.6
-ApproxFun 0.7
+ApproxFun 0.7.1
 BandedMatrices 0.3
 Compat 0.18
 DualNumbers 0.2.3
```
cc: @dlfivefifty

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Is it possible to add upper bounds via attobot?

**Comment by quinnj** [comment]
No, generally upper bounds requires a manual PR from your own fork of METADATA

**Comment by quinnj** [comment]
Would you like to do that before merging this?

**Comment by dlfivefifty** [comment]
Well it’s on an old version so This could be merged and the upper bounds added in a separate PR

**Comment by quinnj** [comment]
sounds good.

**Pull request merged**
