### PR TITLE
Pull request/34a91bd2

### PR DESCRIPTION
**Pull request by brilhana**

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like the package mainly contains general-purpose optimization algorithms. Why not use Optim.jl?

**Comment by brilhana** [comment]
For two reasons: the most efficient algorithm is not implemented by `Optim` and the package is going to include discrete choice models, as well as the solvers, in the foreseeable future.

**Comment by andreasnoack** [comment]
But why not contribute the missing optimization algorithms to Optim.jl (which do you have in mind?) and just focus on the discrete choice models?

**Comment by brilhana** [comment]
Trust region method using the truncated conjugate gradient but you have a valid point. I'll see if they're open to the idea.

**Pull request closed without merging**
