### PR TITLE
Tag InspectDR.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ma-laforge/InspectDR.jl](https://github.com/ma-laforge/InspectDR.jl)
Release: [v0.3.0](https://github.com/ma-laforge/InspectDR.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/ma-laforge/InspectDR.jl/builds/415965768)
Diff: [vs v0.2.4](https://github.com/ma-laforge/InspectDR.jl/compare/cd40fb2ae06c32644ff8abc318659512100161b2...4df10bfd839c1fbf66462c37c4ca6379b90c328f)
`requires` vs v0.2.4: 
```diff
--- 0.2.4/requires
+++ 0.3.0/requires
@@ -1,4 +1,4 @@
-julia 0.6.0
+julia 0.7.0
 Colors
 Gtk
 Graphics
```
cc: @ma-laforge

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ma-laforge** [comment]
Cannot get Travis CI to work despite the fact that the release works on my local computer.

Appears to be the same issue with Gtk.jl... Not sure what needs to be changed.

Probably has something to do with this part of the build log:
```
ERROR: LoadError: error compiling top-level scope: could not load library "libgtk-3"
```

**Comment by andreasnoack** [comment]
If you want this to work well for your users, it might be a good idea to fix the issue before the release. Let me know if you'd like to release this anyway.

**Comment by ma-laforge** [comment]
...This appears to be a testing issue with gtk.  Gtk also fails test.

The InspectDR tests did pass before the transition to Julia 0.7 - and all plots are coming up correctly with these changes.

I would like to make this module available ASAP for people.  I will update the Gtk testing once someone can figure out why Gtk.jl tests fail.

... If it is ok with people: I would like to get it merged nonetheless.

Thanks

**Comment by andreasnoack** [comment]
It might be helpful to join the efforts/discussions related to getting Gtk ready for Julia 1.0. Otherwise, it might be hard for users to use this package.

**Comment by ma-laforge** [comment]
Agreed. Thanks.

**Pull request merged**
