### PR TITLE
Tag AWSS3.jl v0.3.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [samoconnor/AWSS3.jl](https://github.com/samoconnor/AWSS3.jl)
Release: [v0.3.5](https://github.com/samoconnor/AWSS3.jl/releases/tag/v0.3.5)
Travis: [Travis Build Status](https://travis-ci.org/samoconnor/AWSS3.jl/builds/349510369)
Diff: [vs v0.3.4](https://github.com/samoconnor/AWSS3.jl/compare/8cd2f74d660c9d0c01ac1359186cf2fae7ae04d1...d2499b2f799c8dcbff1606e639980c0549413271)
`requires` vs v0.3.4: no changes
cc: @samoconnor

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Is this superseded by #13672?

**Comment by samoconnor** [comment]
Well, v0.3.6 is a newer version, but they are both tagged versions with distinct changes.
It is probable that no one will ever use v0.3.5, but it v0.3.6 has a new bug, maybe they will...

**Comment by samoconnor** [comment]
... if I was the reporter of https://github.com/samoconnor/AWSS3.jl/issues/24, and I was being conservative, I would probably start by trying v0.3.5.

**Comment by samoconnor** [comment]
thankyou!

**Comment by andreasnoack** [comment]
We can merge two. I just ask because usually when this happens, it is not on purpose.

**Pull request merged**
