### PR TITLE
Tag WeakRefStrings.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [quinnj/WeakRefStrings.jl](https://github.com/quinnj/WeakRefStrings.jl)
Release: [v0.3.1](https://github.com/quinnj/WeakRefStrings.jl/releases/tag/v0.3.1)
Travis: [Travis Build Status](https://travis-ci.org/quinnj/WeakRefStrings.jl/builds/275380182)
Diff: [vs v0.3.0](https://github.com/quinnj/WeakRefStrings.jl/compare/152cb5e6698fb183429e9d9cc57c37917b208e5a...98be3ab08d94c2732f40e6f4923c6413e6dbd787)
`requires` vs v0.3.0: no changes
cc: @quinnj

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
CSV and DataTables fail to install on 0.6. Is that expected?

**Comment by quinnj** [comment]
Hmmm, I'll take a look later today.

**Comment by quinnj** [comment]
Not sure why it says that it can't install CSV on 0.6. I just did it from a clean slate w/o any issues. Maybe @ararslan or @tkelman could say better why it had an error?

**Comment by ararslan** [comment]
I... have no idea. I looking at the set of packages required by the various packages in play here, I don't see anything that would be causing a versioning conflict that would keep CSV from installing. @aviks, would it be possible to rerun that build on JuliaCIBot to see whether it's reproducible?

**Pull request merged**
