### PR TITLE
Register new package Case.jl v0.0.1

### PR DESCRIPTION
**Pull request by djsegal**
Repository: [djsegal/Case.jl](https://github.com/djsegal/Case.jl)
Release: [v0.0.1](https://github.com/djsegal/Case.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/djsegal/Case.jl)
cc: @djsegal

### CODE REVIEW

**Comment by djsegal** [comment]
from github description:

> simple string mutation methods for julia

from the docs:

```julia

cur_string = " foo-BAR  bAZ"

camelcase(cur_string) # => "fooBarBaz"

kebabcase(cur_string) # => "foo-bar-baz"

pascalcase(cur_string) # => "FooBarBaz"

snakecase(cur_string) # => "foo_bar_baz"

spacecase(cur_string) # => "foo bar baz"
```

-----

used by: [Fake.jl](https://github.com/JuliaLang/METADATA.jl/pull/12205)

**Comment by KristofferC** [comment]
Why not keep this in Fake? It seems to be very limited in scope and there is no inherent advantage, not shield there be a strive for, to put every single independent utility function in its own package.

**Comment by djsegal** [comment]
I'm cool with putting `underscore` into this package. But I'm definitely not cool with lumping this stuff into Fake.

Fake makes fake data. Case changes the case of strings.

-----

I have thought about make this package before. However I wouldn't use it if I had to load a whole faker gem with it

**Comment by djsegal** [comment]
closing in favor of:

+ [StringManipulations.jl](https://github.com/JuliaLang/METADATA.jl/pull/12226)

**Pull request closed without merging**
