### PR TITLE
Tag SGP4 v0.1.0

### PR DESCRIPTION
**Pull request by crbinz**

### CODE REVIEW

**Comment by tkelman** [comment]
Since the previous tag of the package supports Julia 0.3 but this tag does not, it would be better to use a new minor version and tag this as 0.1.0 of the package.

**Comment by crbinz** [comment]
Makes sense to me... done.

**Comment by tkelman** [comment]
don't forget to push the git tag so it shows under https://github.com/crbinz/SGP4.jl/releases

**Comment by crbinz** [comment]
:+1: good call. Thanks for your help, both here and more generally with all of the METADATA.jl PRs.

**Pull request merged**
