### PR TITLE
Tag FastRounding.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/FastRounding.jl](https://github.com/JeffreySarnoff/FastRounding.jl)
Release: [v0.0.2](https://github.com/JeffreySarnoff/FastRounding.jl/releases/tag/v0.0.2)
Travis: [Travis Build Status](https://travis-ci.org/JeffreySarnoff/FastRounding.jl/builds/223007680)
Diff: [vs v0.0.1](https://github.com/JeffreySarnoff/FastRounding.jl/compare/662d1a03ecb9fe0a9398b256029283d0bb5a8ab4...d07e0eb3d6700b7997b9e65e6d9ad739c95db07d)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.0.2/requires
@@ -1,3 +1,3 @@
 julia 0.5.0
-AdjacentFloats 0.0.1
-ErrorfreeArithmetic 0.0.1
+AdjacentFloats 0.0.2
+ErrorfreeArithmetic 0.0.3
```
cc: @JeffreySarnoff

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
@tkelman  I thought I did as you suggested. What happened?

**Comment by JeffreySarnoff** [comment]
I deleted the version and its tag -- that is what I am used to doing.  In this situation I should have kept the tag.  How can I recover?

**Comment by JeffreySarnoff** [comment]
Or is it easer to minor change (to the tests) and use that to set a next version?

**Comment by tkelman** [comment]
should not change the sha contents or the git tag, just the requires file in metadata - can do a manual pr, rather than via attobot

**Comment by JeffreySarnoff** [comment]
I use attobot because of problems I had with doing manual prs.  I am inclined to do something innocuous to the source and making v0.0.3 from that.  Is that ok?

**Comment by tkelman** [comment]
Put the git tag back to the prior sha for the 0.0.2 tag. Regarding the requirements, https://github.com/JuliaLang/METADATA.jl/pull/8899#issuecomment-294663475 still applies. If the past tag doesn't work with ErrorfreeTransforms 0.0.1 or 0.0.2, then requirements have to be tightened in-place. Just propose an edit via the pencil icon at https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/FastRounding/versions/0.0.2/requires

**Pull request closed without merging**
