### PR TITLE
Tag MbedTLS v0.2.2

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by tkelman** [comment]
please make a more specific version number on the "IO overhaul" condition first

**Comment by malmaud** [comment]
Huh? Not sure I know what you're referring to.

**Comment by tkelman** [comment]
https://github.com/JuliaWeb/MbedTLS.jl/pull/30#discussion_r52682643 otherwise the package will break on earlier 0.5 versions

**Comment by tkelman** [comment]
re-tag this now that master has this sorted?

**Comment by tkelman** [comment]
Another thing to note is the version of the upstream library that you're using has a vulnerability, you should really keep on top of upstream releases as quickly as you can: https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2015-01

**Comment by malmaud** [comment]
OK, superseded by https://github.com/JuliaLang/METADATA.jl/pull/5058. Let's bump the upstream version shortly.

**Comment by tkelman** [comment]
Sounds good. Could you add the appveyor status badge to the readme? The branch status dropdown doesn't work very well on mobile.

Let me know if you want to look into getting mbedtls up on WinRPM so it's a little less manual effort to build new binaries.

**Pull request closed without merging**
