### PR TITLE
Tag Turing.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [yebai/Turing.jl](https://github.com/yebai/Turing.jl)
Release: [v0.3.1](https://github.com/yebai/Turing.jl/releases/tag/v0.3.1)
Travis: [Travis Build Status](https://travis-ci.org/yebai/Turing.jl/builds/303467851)
Diff: [vs v0.3.0](https://github.com/yebai/Turing.jl/compare/f2e4437d8740c960048f1bb0d302579ca4fefde8...63e78b94ba626721198f9685f4329c6635f4c49d)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.3.1/requires
@@ -1,6 +1,8 @@
-julia 0.5
+julia 0.6
 
+Stan
 Distributions 0.11.0
 ForwardDiff
 Mamba
+
 ProgressMeter
```
cc: @yebai

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
`New tag 0.3.1 of package Turing requires julia 0.6.0, but version 0.3.0 of Turing requires julia 0.5.0. Use a new minor package version when support for an old version of Julia is dropped`

**Comment by yebai** [comment]
Alright - we will push a new tagging.

**Comment by xukai92** [comment]
Emmm. What do we suppose to do for this tagging?

**Comment by ChrisRackauckas** [comment]
It needs to be v0.4.0. You cannot do a patch increment (the last number) if the REQUIRE ments change.

**Pull request closed without merging**
