### PR TITLE
tag GLVisualize

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by tkelman** [comment]
What's causing the `LoadError: UndefVarError: renderlist not defined` on GLVisualize? https://travis-ci.org/JuliaGL/GLVisualize.jl/jobs/142031136

**Comment by SimonDanisch** [comment]
not really sure, the build script is a mess, since it never gave me useful information anyways... 
But this should not occur after tagging. I've made sure locally and master looks fine:
https://github.com/JuliaGL/GLAbstraction.jl/blob/master/src/GLCamera.jl#L501
https://github.com/JuliaGL/GLWindow.jl/blob/master/src/screen.jl#L358

**Comment by tkelman** [comment]
If your packages don't work with existing tags then they need to be stricter about lower bounds

**Comment by SimonDanisch** [comment]
This is more about the ancient build script in GLVisualize... I'll update
it tomorrow!

**Comment by SimonDanisch** [comment]
But being more considerate with version numbers doesn't sound like a bad
idea, either...

**Pull request merged**
