### PR TITLE
add upper bounds to lightgraphs versions

### PR DESCRIPTION
**Pull request by sbromberger**
per https://github.com/JuliaGraphs/LightGraphs.jl/issues/573

cc @tkelman

### CODE REVIEW

**Comment by sbromberger** [comment]
Not sure these errors are related to LG.

**Comment by tkelman** [comment]
TrafficAssignment is. It has upper bounds on its LightGraphs dependency, the bounds you're adding here make the intersection empty and infeasible.

**Comment by sbromberger** [comment]
TA v0.5.0 doesn't even require LG but it's in the failure log. How do we resolve this? There should be no gaps in our coverage anywhere.

**Comment by tkelman** [comment]
Ref https://github.com/JuliaLang/METADATA.jl/pull/7613, the artificial dependencies were added there to prevent Pkg from downgrading TrafficAssignment in order to upgrade LightGraphs

**Comment by sbromberger** [comment]
How can I fix this?

**Comment by tkelman** [comment]
Need looser bounds. TrafficAssignment has a LightGraphs 0.7 upper bound, so at least one version of LightGraphs < 0.7 needs to remain installable on all Julia versions that TrafficAssignment supports.

**Comment by sbromberger** [comment]
Not sure I understand. LightGraphs supports all Julia versions between 0.2 and 0.6. Here are the cutoffs:

| LG Version | Lower Bound | Upper Bound |
|---|---|---|
|0.1.0 through 0.3.7|0.3|0.4|
|0.4.0 through 0.6.3|0.4|0.5|
|0.7.0 through 0.7.2|0.5-|0.6|
|0.7.3 through 0.7.5|0.5|0.6|
|0.8.0|0.6-|

With what version of Julia is LG not compatible?

**Comment by tkelman** [comment]
TrafficAssignment's early tags do not have Julia upper bounds, so they claim to support 0.4, 0.5, 0.6, and in the first few, also 0.3. If you upper bound all LG < 0.7, then those TrafficAssignment versions are no longer installable on the versions of julia above your upper bound. Those early versions of TrafficAssignment are the only ones that claim to support julia 0.6, so these LG bounds make that package no longer installable on 0.6 at all.

**Comment by sbromberger** [comment]
Well, I don't think that's a problem LightGraphs should solve. Even if we were to solve it, the early versions of TrafficAssignment won't work in any case, since LightGraphs <= 0.7 won't work in Julia 0.6.

Can we get TrafficAssignment to correctly specify the version of Julia/LightGraphs it requires?

**Comment by tkelman** [comment]
We can do something. Either adding Julia upper bounds to the versions of TrafficAssignment that currently don't have any, which would effectively deprecate the package and make it not installable on 0.6 until a new version of it gets tagged. Or we could loosen some of the bounds on LightGraphs, if the compatibility range is actually wider than what the bounds currently say.

**Comment by sbromberger** [comment]
> Or we could loosen some of its bounds on LightGraphs, if the compatibility range is actually wider than what the bounds currently say.

It's not, as far as I'm aware. We've moved to the minor versions when we've stopped support for a specific version of Julia.

**Comment by sbromberger** [comment]
@tkelman it seems to me that placing artificial constraints on TrafficAssignments may not have been the right way of handling this, as it's now preventing us from putting correct bounds on LightGraphs. What can we do to merge this PR?

**Comment by sbromberger** [comment]
Also: if you look at the `REQUIRE` file in the TrafficAssignment.jl repo, LightGraphs wasn't even required until v0.2.0. It appears they retroactively required LightGraphs for all versions going back to the beginning. This is a problem.

**Comment by tkelman** [comment]
It was necessary to avoid downgrading TrafficAssignment in order to upgrade LightGraphs. Having both installed should prefer keeping LightGraphs back. If there's another way of accomplishing that, we can adjust things to do so.

**Comment by sbromberger** [comment]
> Having both installed should prefer keeping LightGraphs back.

OK, but this is now preventing LightGraphs from tagging appropriate upper bounds, right? Forgive me since many of the subtleties around versioning are still a mystery to me. I still don't know how we resolve the situation, and it appears that it became an issue because TrafficAssignment is specifying bounds for LightGraphs that we know won't work.

**Comment by sbromberger** [comment]
Is it possible to move forward with this? I'd really like to get the upper bounds in on LG prior to v0.9.0. Thanks.

**Comment by tkelman** [comment]
Would need to try alternate solutions to accomplish what TrafficAssignment set the bounds to do, which is avoid letting TrafficAssignment be downgraded to very old versions in order to upgrade LightGraphs.

**Comment by sbromberger** [comment]
I'm not sure what problem we're actually trying to solve here, so closing this out.

**Comment by chkwon** [comment]
Sorry that old versions of TA weren't set properly up. It seems that it would be best to make a new TA version that works with Julia 0.6 and LightGraphs 0.8, without upper bounds?  If you agree,  I will work on it as soon as possible.

**Comment by chkwon** [comment]
@tkelman @sbromberger 

I'll make a new version of TrafficAssignment with the following `REQUIRE`:

```
julia 0.6-
LightGraphs 0.8
Optim 0.7
```

Would this be okay?

**Pull request closed without merging**
