### PR TITLE
register PooledArrays 0.0.1

### PR DESCRIPTION
**Pull request by JeffBezanson**
This implements a compressed representation of arrays with few unique values. It's designed to have the exact same behavior as `Array` except for performance / memory footprint.

### CODE REVIEW

**Comment by ararslan** [comment]
Can you push the tag to the upstream repo so it shows up under Releases? Ref https://travis-ci.org/JuliaLang/METADATA.jl/builds/165389876#L194.

**Comment by JeffBezanson** [comment]
Oops. Done.

**Comment by nalimilan** [comment]
Just FYI, sounds very similar to https://github.com/JuliaArrays/IndirectArrays.jl.

**Comment by JeffBezanson** [comment]
Yes, true. The main extra feature I want here is that the pool is sorted, giving fast `sort` and `sortperm`. Mutation is allowed, and sortedness is maintained when new items are added. Maybe it should be called `SortedPoolArrays`?

**Comment by nalimilan** [comment]
No idea. I guess it depends whether you plan to make it more general at some point.

**Comment by timholy** [comment]
I would definitely call this different enough to merit a different package. I'll add a link to this from IndirectArrays. (Might be good to do the converse, too.)

**Comment by tkelman** [comment]
Turn Travis on here.

**Pull request merged**
