### PR TITLE
Tag Arrow.jl v0.1.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ExpandingMan/Arrow.jl](https://github.com/ExpandingMan/Arrow.jl)
Release: [v0.1.2](https://github.com/ExpandingMan/Arrow.jl/releases/tag/v0.1.2)
Travis: [Travis Build Status](https://travis-ci.org/ExpandingMan/Arrow.jl/builds/415708616)
Diff: [vs v0.1.1](https://github.com/ExpandingMan/Arrow.jl/compare/efa14e9167386cbb544a436a48547d2ffd7ddf62...4692c815fd254a3334c1c7d3da39d754d66ef03d)
`requires` vs v0.1.1: 
```diff
--- 0.1.1/requires
+++ 0.1.2/requires
@@ -1,3 +1,3 @@
 julia 0.6
 CategoricalArrays
-Compat 0.59.0
+Compat 0.66.0
```
cc: @ExpandingMan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Is this obsolete?

**Comment by ExpandingMan** [comment]
This and the other PR were an attempt to fix a series of strange problems I was having with the package manager.

Ultimately I think we need to merge this one, delete the Arrow 0.2.0 one, and then I'll re-tag 0.2.0 at a later date (need to bump Julia version).

Let me consult with @KristofferC some more and get good advice, and then I'll post back here with instructions.  Thanks.

**Comment by ExpandingMan** [comment]
Ok, please delete this one as well.

**Comment by ExpandingMan** [comment]
The new PR should restore this to its original state, as can be seen in the diff.  This PR can still be deleted.

**Pull request closed without merging**
