### PR TITLE
Tag mPulseAPI.jl v1.0.7

### PR DESCRIPTION
**Pull request by attobot**
Repository: [SOASTA/mPulseAPI.jl](https://github.com/SOASTA/mPulseAPI.jl)
Release: [v1.0.7](https://github.com/SOASTA/mPulseAPI.jl/releases/tag/v1.0.7)
Travis: [Travis Build Status](https://travis-ci.org/SOASTA/mPulseAPI.jl/builds/381252299)
Diff: [vs v1.0.6](https://github.com/SOASTA/mPulseAPI.jl/compare/f9ab84e72761a229dc1ea4a8e17a544fe9de3886...2c4aa9dfe1c2e3354038510094069842ac783d78)
`requires` vs v1.0.6: 
```diff
--- 1.0.6/requires
+++ 1.0.7/requires
@@ -4,5 +4,6 @@
 HttpCommon
 HttpParser 0.2.0
 JSON
-DataFrames 0.7.3 0.11.0
+DataFrames 0.7.3
+DataArrays
 Formatting
```
cc: @bluesmoon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by bluesmoon** [comment]
Hi, please note that you will be unable to run tests without an mPulse account. If you'd like to see the test state from our travis account for 1.0.7, it is here: https://travis-ci.org/SOASTA/mPulseAPI.jl/builds/381252299

**Comment by bluesmoon** [comment]
I've also noticed that the `METADATA` merge fails because we work with all version starting with julia 0.4. This is silly. We have a very large number of customers who are on 0.4 and who will continue to be on 0.4 for the foreseeable future. Our code works on 0.4, 0.5 and 0.6. I see no reason why we should be penalised for that.

**Comment by aviks** [comment]
@bluesmoon I'm sure that you'll not be surprised to hear that the Julia open source community do not have the resources to verify packages on older julia versions. This is not just a matter of running the tests, but of fixing compatibility issues as they arise. We restrict this via METADATA tests, since otherwise inadvertent failure are very common --- developers assert compatibility that they do not check. If you are confident of doing that yourself, please ask for an exception for your packages. This can be done by creating a PR against this file. 

https://github.com/JuliaLang/METADATA.jl/blame/metadata-v2/.test/list_3582.jl#L1524

All we need is your explicit acknowledgement that you are aware of the potential issues.

**Comment by bluesmoon** [comment]
Thanks Avik, this makes sense. I'll take care of it.

**Comment by aviks** [comment]
With the other PR merged, this one needs rebasing. The easiest would be to delete your tag, and retag. Hope that is not too much trouble.

**Comment by bluesmoon** [comment]
thanks, I'll take care of it

**Pull request closed without merging**
