### PR TITLE
Add ArcadeLearningEnvironment v0.0.1.

### PR DESCRIPTION
**Pull request by nowozin**

### CODE REVIEW

**Comment by tkelman** [comment]
Cool stuff!

It looks like you created this PR manually? Note that the `REQUIRE` file should be at the top level of the repository, not under deps. https://github.com/nowozin/ArcadeLearningEnvironment.jl/blob/master/deps/REQUIRE

For now since you did the tag manually it doesn't matter, the METADATA requirements are what actually gets used by Pkg. The REQUIRE file within the package is only used for `Pkg.tag`.

**Comment by Evizero** [comment]
This is exciting!

**Comment by tkelman** [comment]
Bump @nowozin your REQUIRE file is still in the wrong place. It is also highly recommended to enable Travis CI.

**Comment by tkelman** [comment]
closing in favor of https://github.com/JuliaLang/METADATA.jl/pull/4290

**Pull request closed without merging**
