### PR TITLE
Tag FinEtools.jl v0.4.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [PetrKryslUCSD/FinEtools.jl](https://github.com/PetrKryslUCSD/FinEtools.jl)
Release: [v0.4.1](https://github.com/PetrKryslUCSD/FinEtools.jl/releases/tag/v0.4.1)
Travis: [Travis Build Status](https://travis-ci.org/PetrKryslUCSD/FinEtools.jl/builds/398823213)
Diff: [vs v0.3.0](https://github.com/PetrKryslUCSD/FinEtools.jl/compare/0cd7123d290e7e29448a5f8a8468d44f8f998c98...f9fb6b797c5d77b5368b558f50a006454a25657d)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.1/requires
@@ -1,3 +1,11 @@
-julia 0.7
+julia-0.7
+
+Arpack
 Compat
+LinearAlgebra
+Printf
+Random
+SparseArrays
 StatsBase
+Statistics
+Unicode
```
cc: @PetrKryslUCSD

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
The Travis CI is failing because of an issue that's been reported as a bug in Julia issues.

**Review by fredrikekre — CHANGES_REQUESTED** [review]
Remove stdlibs from REQUIRE

**Comment by PetrKryslUCSD** [comment]
Done. Stdlibs removed from REQUIRE.

**Comment by PetrKryslUCSD** [comment]
@fredrikekre : Anything else needs to be done?

**Comment by fredrikekre** [comment]
They are still here in the PR; you probably need to remove the tag and make a new release, see https://github.com/attobot/attobot#updatingdeleting-a-release

The format for Julia in require is also wrong; should be `julia 0.7-` or `julia 0.7-beta` maybe.

**Comment by andreasnoack** [comment]
Needs to be a minor version increase when the Julia version is increased so I'll close here

**Pull request closed without merging**
