### PR TITLE
Tag DoubleDouble.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMath/DoubleDouble.jl](https://github.com/JuliaMath/DoubleDouble.jl)
Release: [v0.2.1](https://github.com/JuliaMath/DoubleDouble.jl/releases/tag/v0.2.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMath/DoubleDouble.jl/builds/232447388)
Diff: [vs v0.2.0](https://github.com/JuliaMath/DoubleDouble.jl/compare/cff5b153ff85f1d9246678f3766887e88bb905c1...295941d4a8acef2d0017d1204be885569eed721f)
`requires` vs v0.2.0: no changes
cc: @dpsanders

Please make sure that:
- [ ] CI passes for supported Julia versions (if applicable).
- [ ] Version bounds are up to date.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Thanks for the tag! A maintainer will check for issues and then merge the PR. Alternatively you can reply with `+ready` to do so yourself.

**Comment by tkelman** [comment]
Travis isn't running on Julia 0.4 for this package at the moment

**Comment by tkelman** [comment]
looks like it passes https://travis-ci.org/JuliaMath/DoubleDouble.jl/jobs/232450680 just needed to be enabled

**Comment by dpsanders** [comment]
+ready

**Comment by dpsanders** [comment]
I don't seem to be able to click the check boxes.

**Pull request merged**
