### PR TITLE
Tag LazyJSON v0.0.2 [https://github.com/samoconnor/LazyJSON.jl]

### PR DESCRIPTION
**Pull request by samoconnor**
Diff vs v0.0.1: https://github.com/samoconnor/LazyJSON.jl/compare/28832001c5c8bd78029b7cb548c6bde0105dd904...20989c01048be90df50502527228a3ecc4d6dc5a

### CODE REVIEW

**Comment by andreasnoack** [comment]
`ERROR: LoadError: LoadError: The following tags for LazyJSON have not been pushed to upstream repository: 0.0.2.`

Please consider using https://github.com/attobot/attobot next time you make a release.

**Comment by samoconnor** [comment]
Whoops, I've pushed the tags now.
I will read up on attobot.

**Comment by samoconnor** [comment]
I've installed attobot in my LazyJSON repo. I'll try it out next time I need to tag. Thanks!

**Comment by samoconnor** [comment]
Looks like CI is green now!

**Pull request merged**
