### PR TITLE
Tag Variography.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/Variography.jl](https://github.com/juliohm/Variography.jl)
Release: [v0.3.1](https://github.com/juliohm/Variography.jl/releases/tag/v0.3.1)
Diff: [vs v0.3.0](https://github.com/juliohm/Variography.jl/compare/ec8870c036d1fff06cd45c0fb256c3e11a323c72...349a077abe1235248f7f50ad92b2054b21148010)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.3.1/requires
@@ -1,6 +1,6 @@
 julia 0.7
 GeoStatsBase 0.2.6
-GeoStatsDevTools 0.2.4
+GeoStatsDevTools 0.2.5
 Optim 0.15.0
 Distances 0.5.0
 SpecialFunctions 0.3.8
```
cc: @juliohm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by juliohm** [comment]
Depends on #20231

**Comment by andreasnoack** [comment]
Please trigger a new build here by removing and reapplying the tag.

**Comment by juliohm** [comment]
Done. Just wondering if closing and reopening the PR here would also trigger the build?

**Comment by andreasnoack** [comment]
I asked you to do it because to ensure that it would be automatically merged once tests passed but that only happens when you don't comment on the PR afterward. Please take a look at https://discourse.julialang.org/t/the-current-metadata-release-process/16672

**Pull request merged**
