### PR TITLE
Register StringEncodings 0.1.0

### PR DESCRIPTION
**Pull request by nalimilan**

### CODE REVIEW

**Comment by nalimilan** [comment]
OK to merge?

**Comment by tkelman** [comment]
After leaving open for ~24 hour comment period, so now yes.

**Comment by quinnj** [comment]
+1

**Comment by nalimilan** [comment]
@quinnj (and anybody interested) Feel free to join the discussion on how to handle encodings in general. See in particular https://github.com/nalimilan/StringEncodings.jl/pull/9.

**Pull request merged**
