### PR TITLE
Fixed build on Julia 0.5

### PR DESCRIPTION
**Pull request by aaalexandrov**
Fixed building of DevIL / OpenIL for Julia 0.5.0 and bumped up the package version to 0.4.0

### CODE REVIEW

**Comment by aviks** [comment]
To confirm, version `0.4.0` of `DevIL` will not be installable on `Julia 0.5`?

**Comment by tkelman** [comment]
Can you push the git tag so it shows up at https://github.com/JuliaGL/DevIL.jl/releases ?

**Comment by tkelman** [comment]
@ararslan shouldn't your check have flagged this?

**Comment by aaalexandrov** [comment]
I've pushed the v0.4.0 tag to the DevIL repo, sorry about that.
And to answer the question above - no, I'm not supporting Julia 0.4 in the new release, I've changed the requirements to Julia 0.5-
Does the Julia package manager sync to the latest published package always, or does it try to sync to an earlier package version that corresponds to the actual Julia version?

**Comment by aaalexandrov** [comment]
Is there a way to re-run the checks without submitting changes again?
It should be ok, but it's still showing the result from before me pushing the tags.

**Comment by tkelman** [comment]
julia 0.4 will keep using the last tagged version of the package that supports 0.4 according to its require file. this new tag will be installable on prerelease (the trailing dash) of 0.5 or newer

**Pull request merged**
