### PR TITLE
drop 0.3 support, fix for 0.4rc2 for rened's packages

### PR DESCRIPTION
**Pull request by rened**

### CODE REVIEW

**Comment by rened** [comment]
I somehow lost the ability to merge these myself?

**Comment by ivarne** [comment]
Seems like there was a much needed, but maybe too broad cleanup.

https://groups.google.com/forum/#!topic/julia-dev/RfPkS40mFRo

**Comment by rened** [comment]
Ah, ok, thought something like this. Fine with me ;-) Thanks!

**Comment by tkelman** [comment]
Could you push your tags so they show up under https://github.com/rened/DeclarativePackages.jl/releases etc?

**Comment by rened** [comment]
@tkelman thanks for the input, fixed!

**Pull request merged**
