### PR TITLE
Tag Gadfly v0.6.2 [https://github.com/GiovineItalia/Gadfly.jl]

### PR DESCRIPTION
**Pull request by bjarthur**
Diff vs v0.6.1: https://github.com/GiovineItalia/Gadfly.jl/compare/16018ad198d50d5a951faa46ad5e444a80df5a49...05f4df1d6ac01eacdab415ea20e874be3623f6a4

### CODE REVIEW

**Comment by tkelman** [comment]
Some new issues here, cc @dehann
- exporting `cross` caused Caesar.jl to start failing tests https://github.com/JuliaCI/pkg.julialang.org/blob/fcc6b27399728bfb46782200a382240b78470d6c/logs/Caesar_0.5.log
- messy looking MethodError in RoME.jl https://github.com/JuliaCI/pkg.julialang.org/blob/fcc6b27399728bfb46782200a382240b78470d6c/logs/RoME_0.5.log

**Comment by dehann** [comment]
Thanks, I will have a look.

**Comment by bjarthur** [comment]
`Theme(default_point_size...)` is now `Theme(point_size...)`.  change made for brevity and consistency.  i suppose i should've thought harder about a way to gracefully deprecate.

**Comment by dehann** [comment]
fixed thanks, sorry for slow turnaround on my side.

**Pull request merged**
