### PR TITLE
Tag IntervalArithmetic v0.9.1 [https://github.com/JuliaIntervals/Inte…

### PR DESCRIPTION
**Pull request by lbenet**
…rvalArithmetic.jl]

Diff vs v0.9.0: https://github.com/JuliaIntervals/IntervalArithmetic.jl/compare/28fde2fad77ba513dc4ffa17a7c91be794d995bd...d23a1c9f90ca9699223f1a1cd22e823f9bf064c6

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like this introduces an ambiguity that causes a failure in IntervalRootFinding?

**Comment by lbenet** [comment]
Thanks @tkelman, I'll take a look on this. Incidentally, how do we proceed now?

@dpsanders Any idea? I get in IntervalRootFinding (v0.1.0) some errors in the promotion tests. Could this be related to https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/13

**Comment by dpsanders** [comment]
There is a PR to IntervalRootFinding.jl to remove those tests.

**Comment by tkelman** [comment]
we could add upper bounds on the existing IntervalRootFinding tags' dependency on IntervalArithmetic, so having IntervalRootFinding installed would hold this package back until there's a new working version of IntervalRootFinding available

**Comment by lbenet** [comment]
@tkelman Is there a way to restart the JuliaCIBot checks? We just merged the PR referred by @dpsanders

**Comment by tkelman** [comment]
re-tag

**Comment by lbenet** [comment]
Do you mean a new (patch) version? Sorry for the stupid question...

**Comment by dpsanders** [comment]
He means delete the tag and then create a release with the same tag using Attobot.

**Comment by dpsanders** [comment]
I can do it later when I am at my computer.

**Comment by lbenet** [comment]
Thanks, that would be very helpful!

**Comment by dpsanders** [comment]
Please close in favour of #9406.

**Comment by lbenet** [comment]
Thanks David! Closing...

**Pull request closed without merging**
