### PR TITLE
Tag LinearOperators.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaSmoothOptimizers/LinearOperators.jl](https://github.com/JuliaSmoothOptimizers/LinearOperators.jl)
Release: [v0.4.0](https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/releases/tag/v0.4.0)
Diff: [vs v0.3.1](https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/compare/5a4a9caeb139f2071b0da2315d94e96f45a2636a...2c29006a1da2bb5a256442a714a02ed90644c58a)
`requires` vs v0.3.1: 
```diff
--- 0.3.1/requires
+++ 0.4.0/requires
@@ -1,2 +1,2 @@
-julia 0.4
-Compat 0.17
+julia 0.6
+Compat 0.50
```
cc: @abelsiqueira

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like this breaks `NLPModels`.

**Comment by abelsiqueira** [comment]
The fix for NLPModels is ready

**Comment by abelsiqueira** [comment]
Also, last release supporting the previous version: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/112

**Comment by andreasnoack** [comment]
To avoid breaking code, you'd have to open a PR that adds an upper bound on `LinearOperators` to [all versions of NLPModels](https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/NLPModels/versions) in METADATA.

**Comment by abelsiqueira** [comment]
Clarifying: I go back at tag 0.0.1, add a commit with the change, create a new release 0.0.2, and repeat for 0.1.0-0.3.0. Is that it?

**Comment by abelsiqueira** [comment]
Thanks.

**Pull request merged**
