### PR TITLE
Tag Flux.jl v0.6.8

### PR DESCRIPTION
**Pull request by attobot**
Repository: [FluxML/Flux.jl](https://github.com/FluxML/Flux.jl)
Release: [v0.6.8](https://github.com/FluxML/Flux.jl/releases/tag/v0.6.8)
Travis: [Travis Build Status](https://travis-ci.org/FluxML/Flux.jl/builds/444695810)
Diff: [vs v0.6.7](https://github.com/FluxML/Flux.jl/compare/5e4ee827e9c742f46ad4ceafb388baa40f6c6a9a...cb773e54c0dbb5337bbd3318acb3ae79c1979b01)
`requires` vs v0.6.7: no changes
cc: @MikeInnes

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like this breaks `Omega`. cc @zenna

**Comment by MikeInnes** [comment]
Might be best to go ahead with this anyway, since Flux is currently broken by a CuArrays update; I can try and figure out what happened in Omega in the meantime.

**Comment by MikeInnes** [comment]
Added an upper bound for Flux in Omega.

**Comment by andreasnoack** [comment]
It looks like Turing triggers a similar test failure
```julia
  LoadError: MethodError: no method matching Irrational{:log2π}(::Int64)
  Closest candidates are:
    Irrational{:log2π}(::T<:Number) where T<:Number at boot.jl:725
    Irrational{:log2π}() where sym at irrationals.jl:18
    Irrational{:log2π}(!Matched::Complex) where T<:Real at complex.jl:37
    ...
  Stacktrace:
   [1] convert(::Type{Irrational{:log2π}}, ::Int64) at ./number.jl:7
   [2] oftype(::Irrational{:log2π}, ::Int64) at ./essentials.jl:323
   [3] zero(::Irrational{:log2π}) at ./number.jl:262
   [4] (::getfield(Flux.Tracker, Symbol("##227#230")){Irrational{:log2π}})(::Float64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/scalar.jl:69
   [5] back_(::Flux.Tracker.Grads, ::Flux.Tracker.Call{getfield(Flux.Tracker, Symbol("##227#230")){Irrational{:log2π}},Tuple{Flux.Tracker.Tracked{Float64},Nothing}}, ::Float64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:103
   [6] back(::Flux.Tracker.Grads, ::Flux.Tracker.Tracked{Float64}, ::Float64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:118
   [7] #4 at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:106 [inlined]
   [8] foreach at ./abstractarray.jl:1836 [inlined]
   [9] back_(::Flux.Tracker.Grads, ::Flux.Tracker.Call{getfield(Flux.Tracker, Symbol("##178#179")),Tuple{Flux.Tracker.Tracked{Float64}}}, ::Float64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:106
   [10] back(::Flux.Tracker.Grads, ::Flux.Tracker.Tracked{Float64}, ::Float64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:118
   [11] (::getfield(Flux.Tracker, Symbol("##4#5")){Flux.Tracker.Grads})(::Flux.Tracker.Tracked{Float64}, ::Float64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:106
   [12] foreach at ./abstractarray.jl:1836 [inlined]
   [13] back_(::Flux.Tracker.Grads, ::Flux.Tracker.Call{getfield(Flux.Tracker, Symbol("##203#206")){Int64},Tuple{Flux.Tracker.Tracked{Float64},Nothing}}, ::Int64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:106
   [14] back(::Flux.Tracker.Grads, ::Flux.Tracker.Tracked{Float64}, ::Int64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:118
   [15] #4 at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:106 [inlined]
   ... (the last 4 lines are repeated 2 more times)
   [24] foreach at ./abstractarray.jl:1836 [inlined]
   [25] back_(::Flux.Tracker.Grads, ::Flux.Tracker.Call{getfield(Flux.Tracker, Symbol("##226#229")),Tuple{Flux.Tracker.Tracked{Float64},Flux.Tracker.Tracked{Float64}}}, ::Int64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:106
   [26] back(::Flux.Tracker.Grads, ::Flux.Tracker.Tracked{Float64}, ::Int64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:118
   [27] foreach at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:106 [inlined]
   [28] back_(::Flux.Tracker.Grads, ::Flux.Tracker.Call{getfield(Flux.Tracker, Symbol("##178#179")),Tuple{Flux.Tracker.Tracked{Float64}}}, ::Int64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:106
   [29] back(::Flux.Tracker.Grads, ::Flux.Tracker.Tracked{Float64}, ::Int64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:118
   [30] #6 at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:131 [inlined]
   [31] (::getfield(Flux.Tracker, Symbol("##9#11")){getfield(Flux.Tracker, Symbol("##6#7")){Flux.Tracker.Params,Flux.Tracker.TrackedReal{Float64}}})(::Int64) at /home/jrun/Turing/.julia/packages/Flux/n2qYq/src/tracker/back.jl:140
   [32] gradient_reverse(::Array{Real,1}, ::VarInfo, ::Function, ::Nothing) at /home/jrun/Turing/.julia/packages/Turing/YnwiD/src/core/ad.jl:97
```
Probably related to the call to `zero` in https://github.com/FluxML/Flux.jl/commit/d25e05d9eed5cde043a609bf6aca63bc545ee6b5

**Comment by MikeInnes** [comment]
Yeah ok, sounds right – good catch.
```julia
julia> zero(π)
ERROR: MethodError: no method matching Irrational{:π}(::Int64)
```
I can hack my way around this, but do you know if there's a real fix of any kind?

**Comment by andreasnoack** [comment]
Maybe. Let me try.

**Comment by MikeInnes** [comment]
I pushed/tagged my hackaround in https://github.com/FluxML/Flux.jl/commit/96dbae2d2034b95f10cd356adfcb66be1505c748, but still happy to take any better solution you have.

**Pull request merged**
