### PR TITLE
Tag PowerModels.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lanl-ansi/PowerModels.jl](https://github.com/lanl-ansi/PowerModels.jl)
Release: [v0.5.0](https://github.com/lanl-ansi/PowerModels.jl/releases/tag/v0.5.0)
Diff: [vs v0.4.0](https://github.com/lanl-ansi/PowerModels.jl/compare/115de853fd4103b712d051e902540e7fa2b627be...a1a6f3530d02bbb8b65fb14fac09ba3e04544567)
`requires` vs v0.4.0: no changes
cc: @ccoffrin

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ccoffrin** [comment]
FYI, PowerModelsAnnex will be updated once this version is tagged.

**Comment by ccoffrin** [comment]
Any questions / concerns about this release?

**Comment by KristofferC** [comment]
Looks like PowerModelsAnnex fails with this tag? See e.g. http://juliarun-ci.s3.amazonaws.com/852e49413fd1178b8a67ba2f612509549b3deea5/PowerModelsAnnex_with_pull_request_of_PowerModels_on_julia_0_5.log

**Comment by ccoffrin** [comment]
@KristofferC, yes.  PowerModelsAnnex has a version upper bound on PowerModels and is incompatible with this release of PowerModels.  Once this version is tagged, I will update PowerModelsAnnex to be compatible with this version and update the REQUIRE on that package accordingly.

**Comment by ccoffrin** [comment]
Thanks!

**Pull request merged**
