### PR TITLE
Register SpikingNetworks: v0.0.1, v0.0.2, v0.0.3, v0.0.4

### PR DESCRIPTION
**Pull request by YaoLuCNS**
I have fixed previous errors. I don't know if this one is OK?

### CODE REVIEW

**Comment by tkelman** [comment]
travis didn't run here, will close then reopen to trigger it

**Comment by tkelman** [comment]
It's a good idea to push the git tags to the package repository so they show up under https://github.com/YaoLuCNS/SpikingNetworks.jl/releases. If you enabled Travis CI, would your tests pass there?

**Comment by YaoLuCNS** [comment]
I just use Pkg.generate to create those packages. I don't know what is Travis.

**Comment by tkelman** [comment]
Travis CI (https://travis-ci.org) is a service that automatically runs your tests for you every time you push a commit or get a pull request. See https://docs.travis-ci.com/user/languages/julia

**Comment by tkelman** [comment]
Please do `git push --tags` from the SpikingNetworks.jl package directory.

**Pull request merged**
