### PR TITLE
Tag SingularIntegralEquations v0.2.1

### PR DESCRIPTION
**Pull request by dlfivefifty**
Support for ApproxFun v0.4.1

### CODE REVIEW

**Comment by tkelman** [comment]
Patch releases really shouldn't include breaking changes.

**Comment by dlfivefifty** [comment]
Sorry, I just wanted to update the syntax before dropping 0.4 support (so that the usage is consistence). The syntax of ApproxFun should be stable now and so it shouldn't happen again.

**Comment by dlfivefifty** [comment]
In any case, this package uses internal features of ApproxFun, so will likely continue to need to be limited to specific patch releases.

**Comment by aviks** [comment]
@dlfivefifty did you want to get this merged in it's current form? Sorry, did not understand the result of the above conversation.

**Comment by dlfivefifty** [comment]
@aviks Yes please.  @tkelman's complaint applies to ApproxFun.jl, not SingularIntegralEquations.jl, which has already been tagged and merged.

**Comment by aviks** [comment]
Gottit, thanks. @tkelman thoughts?

**Pull request merged**
