### PR TITLE
Tag SeqMaker v0.1.0

### PR DESCRIPTION
**Pull request by sfchen**
This version of SeqMaker provides complete functions for next generation sequencing simulation

### CODE REVIEW

**Comment by tkelman** [comment]
Is it possible to enable tests on Travis CI?

**Comment by sfchen** [comment]
@tkelman I enabled it. But the test is failing because it takes too long to download a big file.

**Comment by tkelman** [comment]
Ah, that's too bad. Is there a way to run on a smaller subset of the data?

**Comment by sfchen** [comment]
Currently it need human genome reference data to test (~800M), I will consider to pack a tiny genome reference with the package.

**Comment by tkelman** [comment]
This dataset is probably too big for an automated unit test, you're running out of memory on PkgEval. http://pkg.julialang.org/detail/SeqMaker.html

**Comment by tkelman** [comment]
@sfchen any update on getting this to pass its tests again?
At some point I increased the amount of memory on PkgEval so you stopped hitting that problem, now you've been getting
```
INFO: checking SHA1...
ERROR: LoadError: test error in expression: test_ngs()
MethodError: `lowercase` has no method matching lowercase(::Array{UInt8,1})
 in check_sha1 at /home/vagrant/.julia/v0.4/OpenGene/src/Reference/Genome/downloader.jl:7
 in download_assembly at /home/vagrant/.julia/v0.4/OpenGene/src/Reference/Genome/downloader.jl:56
 in load_assembly at /home/vagrant/.julia/v0.4/OpenGene/src/Reference/Genome/reader.jl:11
 in make_seq at /home/vagrant/.julia/v0.4/SeqMaker/src/maker.jl:7
 in ngs at /home/vagrant/.julia/v0.4/SeqMaker/src/SeqMaker.jl:32
 in ngs at /home/vagrant/.julia/v0.4/SeqMaker/src/SeqMaker.jl:26
 in test_ngs at /home/vagrant/.julia/v0.4/SeqMaker/test/runtests.jl:6
```
(same pkg.julialang.org link as above)

**Comment by sfchen** [comment]
@tkelman this issue is caused by SHA1 package not compatible with v0.5.

**Comment by tkelman** [comment]
SHA.jl is compatible with Julia 0.5. It changed from returning a string to returning bytes though.

**Comment by sfchen** [comment]
I will update SeqMaker.

**Comment by tkelman** [comment]
The problem is in OpenGene https://github.com/OpenGene/OpenGene.jl/blob/v0.1.9/src/Reference/Genome/downloader.jl#L7 but only exercised by SeqMaker's tests.

**Comment by sfchen** [comment]
`sha1()` in package `SHA` master switched to return `Array{UInt8,1}`, instead of `String`.  But its latest release in `METADATA` is still returning `String`.

**Comment by tkelman** [comment]
Are you sure about that, or do you have a package installed that applies an upper bound keeping your local copy held back? What version do you see installed?

**Comment by sfchen** [comment]
I am sure. I will add a work around to support both `Array{UInt8,1}` and `String`.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5708 was tagged months ago

**Pull request merged**
