### PR TITLE
DynamoDB.jl

### PR DESCRIPTION
**Pull request by dls**
I've been playing with this for a week now on my own, seems stable enough to send out to the wider community.

Had some trouble doing this the automated way, submitting manually. Sorry if the format is irregular.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Cc @tanmaykm

**Comment by tanmaykm** [comment]
@dls This looks great!

The CI checks have not gone through, probably because of these:
- https://github.com/dls/DynamoDB.jl/issues/1
- https://github.com/dls/DynamoDB.jl/issues/2

Could you fix them and resubmit?

**Comment by dls** [comment]
Okay, I've checked for logs at https://travis-ci.org/JuliaLang/METADATA.jl/pull_requests and found non (weird...), as well as run the command in .travis.yml to verify it should have passed. Closing this and then resubmitting.

**Comment by dls** [comment]
Heh... crazy timing. Okay, not closing this, and no clue what happened.

**Comment by tanmaykm** [comment]
@dls could you please squash the commits?

**Comment by dls** [comment]
Squashed :)

**Comment by tanmaykm** [comment]
thanks!

**Pull request merged**
