### PR TITLE
Tag ResumableFunctions.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BenLauwens/ResumableFunctions.jl](https://github.com/BenLauwens/ResumableFunctions.jl)
Release: [v0.2.0](https://github.com/BenLauwens/ResumableFunctions.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/BenLauwens/ResumableFunctions.jl/builds/346006986)
Diff: [vs v0.1.10](https://github.com/BenLauwens/ResumableFunctions.jl/compare/ec55bcf9bc1cd24ba84b28743e10953795f1d90d...9b025c40e7975758c3f2bf26fcd25c88fba2c233)
`requires` vs v0.1.10: 
```diff
--- 0.1.10/requires
+++ 0.2.0/requires
@@ -1,3 +1,3 @@
-julia 0.6
+julia 0.6 0.7-
 
 MacroTools 0.4
```
cc: @BenLauwens

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Apparently, this breaks https://github.com/pdobacz/PyTest.jl

**Comment by BenLauwens** [comment]
A [pull request](https://github.com/pdobacz/PyTest.jl/pull/6) has been introduced that solves the problem. (Passes the Travis CI build)
PyTest uses a `@resumable function` as an iterator without `for` loop. `done` has to be called before `next` can be called. This modification is inspired by the julep on iterators so that future updates will be transparent.
So I think this can be merged;)

**Comment by andreasnoack** [comment]
Thanks for fixing the issue with PyTest. To avoid breaking installations of PyTest, the PR would have to be merged and a new release of PyTest must be tagged so I think we should wait a day more to give the maintainer a chance to handle this.

**Comment by BenLauwens** [comment]
My PR for PyTest is merged in master but I have not yet seen a new release... is their a general rule how long we have to wait before a package with breaking (but resolved) changes can be merged?

**Comment by andreasnoack** [comment]
The new release has already been merged: https://github.com/JuliaLang/METADATA.jl/pull/13556. Please remove and add the tag for this release. That will update the version of METADATA used for the CIBot tests such that we can confirm that things are working. (In the future, this procedure shouldn't be required but we need to implement a few changes first).

**Comment by BenLauwens** [comment]
Travis CI build stalled after `INFO: Package database updated`

**Comment by andreasnoack** [comment]
Occasionally, the build stalls.

**Pull request merged**
