### PR TITLE
Tag Feather.jl v0.2.4

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/Feather.jl](https://github.com/JuliaStats/Feather.jl)
Release: [v0.2.4](https://github.com/JuliaStats/Feather.jl/releases/tag/v0.2.4)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/Feather.jl/builds/215801785)
Diff: [vs v0.2.3](https://github.com/JuliaStats/Feather.jl/compare/18b7c297c331d6cd960af082d772e4c35834f796...4921ebb83d5f4514467de94d1d8fb5ec3746191b)
`requires` vs v0.2.3: 
```diff
--- 0.2.3/requires
+++ 0.2.4/requires
@@ -1,5 +1,5 @@
 julia 0.5
-FlatBuffers 0.1.1 0.2.0
+FlatBuffers 0.2.0
 NullableArrays 0.0.8
 CategoricalArrays 0.0.6
 DataFrames
```
cc: @quinnj

### CODE REVIEW

**Comment by tkelman** [comment]
there's a test failure on linux 0.5, looks real

**Comment by quinnj** [comment]
Yeah, saw that. Weird because it looks linux-specific; osx & windows tests all passed fine

**Comment by quinnj** [comment]
I forgot that 0.5 still needed the `workspace()` call in the tests.

**Comment by tkelman** [comment]
Ah good, easy fix then.

**Comment by quinnj** [comment]
Yes. And also explains why it was a bit sporadic (I finally realized it when I couldn't reproduce when the docker-python tests didn't run, only when they did, so something in that code must have triggered the need for workspace).

**Pull request closed without merging**
