### PR TITLE
Tag LLVM.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [maleadt/LLVM.jl](https://github.com/maleadt/LLVM.jl)
Release: [v0.3.1](https://github.com/maleadt/LLVM.jl/releases/tag/v0.3.1)
Diff: [vs v0.3.0](https://github.com/maleadt/LLVM.jl/compare/e978d70b04ea82fc62bab149cb1812303db37f9f...e9ae69a21e1758de2ef494f68bdc9d6a9d510213)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.3.1/requires
@@ -1,2 +1,2 @@
 julia 0.5
-Compat 0.9.5
+Compat 0.17.0
```
cc: @maleadt

### CODE REVIEW

**Comment by tkelman** [comment]
should not call `exit` in a build.jl script, that would prevent running build scripts for other packages that get upgraded or installed at the same time

**Comment by maleadt** [comment]
OK, what's the alternative to indicate failure? Throw/error?

**Comment by tkelman** [comment]
yes

**Comment by maleadt** [comment]
Hm, that didn't really apply here. Anyway, replaced the `exit `with a `return`, as that does allow other packages to get built.

**Pull request merged**
