### PR TITLE
Register Slug: v0.1.0

### PR DESCRIPTION
**Pull request by eraviart**

### CODE REVIEW

**Comment by jiahao** [comment]
Slug is not a very descriptive name. Are there other names you could consider?

**Comment by eraviart** [comment]
Do you prefer a name like Slugify or Slugifier?
http://stackoverflow.com/questions/5574042/string-slugification-in-python

**Comment by cbenz** [comment]
Since "slugify" this is a common operation in particular when dealing with URLs in web development, I appreciate the existence of a dedicated package. 

In the Python world I see many packages named "xxx-slugify", so I would vote for Slugify.jl

**Comment by StefanKarpinski** [comment]
+1 for Slugify.jl

**Comment by eraviart** [comment]
Slug has been renamed to Slugify. I close this pull request because it is now replaced with #2593.

**Pull request closed without merging**
