### PR TITLE
Tag ImageTransformations.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaImages/ImageTransformations.jl](https://github.com/JuliaImages/ImageTransformations.jl)
Release: [v0.3.1](https://github.com/JuliaImages/ImageTransformations.jl/releases/tag/v0.3.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaImages/ImageTransformations.jl/builds/233221526)
Diff: [vs v0.3.0](https://github.com/JuliaImages/ImageTransformations.jl/compare/d1388171ba37616d62240664fcd1f4a858defc26...333f9469a94fcbcc224a901ca6ddab1530240e17)
`requires` vs v0.3.0: no changes
cc: @Evizero

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by Evizero** [comment]
(I am mainly curious if this fixes the buildbot errors)

**Comment by Evizero** [comment]
Mhm seems that this time the JuliaBuildBot was not triggered?

**Comment by tkelman** [comment]
the pending status indicator has sometimes been flaky and not shown up properly even though it might be running - we should see if we can make the queue and progress through it visible

**Comment by Evizero** [comment]
Are you asking me to do something? If so I don't quite know what you are hinting at

**Comment by tkelman** [comment]
I'm trying to bump the ci bot and hope it goes through this time

**Pull request merged**
