### PR TITLE
Tag JuliennedArrays.jl v0.0.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bramtayl/JuliennedArrays.jl](https://github.com/bramtayl/JuliennedArrays.jl)
Release: [v0.0.3](https://github.com/bramtayl/JuliennedArrays.jl/releases/tag/v0.0.3)
Travis: [Travis Build Status](https://travis-ci.org/bramtayl/JuliennedArrays.jl/builds/472825305)
Diff: [vs v0.0.2](https://github.com/bramtayl/JuliennedArrays.jl/compare/876c5e934f50607a363ac12176a09996d2504472...12444114d26bd2fc8e4b278649edaa81b520535a)
`requires` vs v0.0.2: 
```diff
--- 0.0.2/requires
+++ 0.0.3/requires
@@ -1,4 +1 @@
-julia 0.6
-RecurUnroll
-TypedBools
-Parts
+julia 1.0
```
cc: @bramtayl

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by bramtayl** [comment]
@andreasnoack I put Julia 1.0 in REQUIRE. Is there a reason JuliaCIBot is testing on 0.6?

**Comment by andreasnoack** [comment]
> Is there a reason JuliaCIBot is testing on 0.6?

It shouldn't be but it doesn't matter except for some wasted energy. The failure on 0.6 is not causing the overall failure. It's the failure on 1.0.

**Comment by bramtayl** [comment]
Ok, cool. I'm confused about the 1.0 "new" failure. It doesn't look like a Julia stacktrace... what is "NoSuchKey" referring to?

**Comment by andreasnoack** [comment]
I see. It looks like something went wrong with that run. I'll restart the tests.

**Pull request merged**
