### PR TITLE
Tag TensorFlow.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [malmaud/TensorFlow.jl](https://github.com/malmaud/TensorFlow.jl)
Release: [v0.6.0](https://github.com/malmaud/TensorFlow.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/malmaud/TensorFlow.jl/builds/236409913)
Diff: [vs v0.5.1](https://github.com/malmaud/TensorFlow.jl/compare/422673021a87646cd73651766792c791a932a000...04f79437d26a7f7ad401462a7e347cdb9c6933ca)
`requires` vs v0.5.1: 
```diff
--- 0.5.1/requires
+++ 0.6.0/requires
@@ -11,3 +11,5 @@
 Media 0.2.2
 Juno 0.2.3
 Compat 0.18
+MacroTools 0.3.6
+AutoHashEquals 0.1.0
```
cc: @malmaud

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by staticfloat** [comment]
JuliaCIBot (neat, is that new?) is failing because the TensorFlow python package isn't installed.

@tkelman should we ignore and merge anyway?

**Comment by ViralBShah** [comment]
Yes we did JuliaCIBot at Julia Computing recently as a service on top of JuliaRun. @tkelman should be writing a blog post. Basically a CI that looks for breaking changes affecting other packages. We probably need a pre-run capability to install stuff like TensorFlow. I guess it is still stabilizing on the basic stuff before new features are added.

**Comment by ViralBShah** [comment]
Cc @nkottary

**Comment by nkottary** [comment]
We considered installing dependencies by looking at the `.travis.yml` file but its hard to tell what is the build part and the test part. If you would like to install such dependencies create a file `.juliarun_ci.sh` in the package root with commands to setup the package. You can use `sudo` in that file. This is WIP and should be fully functional in a couple of days.

**Pull request merged**
