### PR TITLE
Register new package Shearlab.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [arsenal9971/Shearlab.jl](https://github.com/arsenal9971/Shearlab.jl)
Release: [v0.1.1](https://github.com/arsenal9971/Shearlab.jl/releases/tag/v0.1.1)
cc: @arsenal9971

### CODE REVIEW

**Comment by tkelman** [comment]
If you enabled travis ci, would your tests pass there?

**Comment by arsenal9971** [comment]
@tkelman  I thought Travis CI was enabled, I don't know if Attobot does it automatically, what kind of tests do you recommend me? I have no much experience writing tests in Julia.

**Comment by arsenal9971** [comment]
@tkelman I just finished to write down some basic unit (tests)[ https://github.com/arsenal9971/Shearlab.jl/tree/master/test], and also added them to the travis CI, should I create another realese of the project and make another pull request, or should I leave it in this pull request?, how can I know if my package was already registered?

**Comment by tkelman** [comment]
it looks like you haven't enabled travis yet? see https://travis-ci.org/arsenal9971/Shearlab.jl
it may also have issues with tabs in your yml file, not sure.

this wasn't merged yet so your package isn't registered yet. you could replace this tag with latest master and attobot will update this pr, or make a separate release and attobot will make a new pr

**Comment by arsenal9971** [comment]
@tkelman I think Travis is now enabled, but it has build [errors](https://travis-ci.org/arsenal9971/Shearlab.jl/jobs/205482904)

**Comment by tkelman** [comment]
Do `julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall");'` in the same call, environment variable settings from inside Julia don't persist to a separate invocation of julia. Or you could `export PYTHON=""; julia -e ...`

**Comment by arsenal9971** [comment]
@tkelman, I already changed that, and the travis CI test passed successfully in [OSX](https://travis-ci.org/arsenal9971/Shearlab.jl/jobs/205482905) but not in [Linux](https://travis-ci.org/arsenal9971/Shearlab.jl/jobs/205482904), having the same problem with PyCall as before in the later. I'm personally using OSX I thought this should not affect in the structure of the .travis.yaml file

**Comment by arsenal9971** [comment]
@tkelman  I already merged your pull request with the modified .travis.yaml, again the [linux](https://travis-ci.org/arsenal9971/Shearlab.jl/jobs/205519408) version does not pass the test in travis CI with the next error
screen shot 2017-02-26 at 3 39 43 pm
I don't know why it cannot open the file ```Shearlab.jl/src/util/operations.jl````, but I guess it has to be with the warning ```No working GUI backend found for matplotlib````.

Again the [OSX](https://travis-ci.org/arsenal9971/Shearlab.jl/jobs/205519409) build passes the tests.

**Comment by tkelman** [comment]
The problem is that Linux is a case sensitive file system, the folder is named `Util` but you're trying to include files from it as `util`

**Comment by arsenal9971** [comment]
The package passed the [Travis CI](https://travis-ci.org/arsenal9971/Shearlab.jl) test successfully, I will create a new release with Attobot, to do a new pull request to METADATA, thanks for the help.

**Comment by arsenal9971** [comment]
Here the new pull request https://github.com/JuliaLang/METADATA.jl/pull/8132

**Pull request closed without merging**
