### PR TITLE
Tag MathOptInterface.jl v0.4.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaOpt/MathOptInterface.jl](https://github.com/JuliaOpt/MathOptInterface.jl)
Release: [v0.4.1](https://github.com/JuliaOpt/MathOptInterface.jl/releases/tag/v0.4.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaOpt/MathOptInterface.jl/builds/397735419)
Diff: [vs v0.4.0](https://github.com/JuliaOpt/MathOptInterface.jl/compare/9738f62a9ad990aa073edcdde7d193fc3bd16b60...585a9593d9d093d60397de22295899b4d2aef6e1)
`requires` vs v0.4.0: no changes
cc: @blegat

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by blegat** [comment]
cc @odow @mlubin @joaquimg

**Comment by joaquimg** [comment]
We are giving a JuMP tutorial tomorrow, if anyone can merge this (and #15384 ) asap would be of great help :)

**Comment by joaquimg** [comment]
actually its today if we account for the fact the the tutorial is in France at the JuMP-dev workshop ;)

**Comment by KristofferC** [comment]
Hope the merge got in in time. Good luck with the tutorial!

**Comment by blegat** [comment]
Yes, thanks ! The tutorial is in 2h30 :)

**Pull request merged**
