### PR TITLE
Register new package Electron.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidanthoff/Electron.jl](https://github.com/davidanthoff/Electron.jl)
Release: [v0.0.1](https://github.com/davidanthoff/Electron.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/davidanthoff/Electron.jl/builds/339971111)
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@davidanthoff This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by davidanthoff** [comment]
CIBot failure doesn't show a log, I get a message that the key couldn't be found?

**Comment by davidanthoff** [comment]
Still no access to the log...

**Comment by andreasnoack** [comment]
@aviks Do you know what is going on here?

**Comment by davidanthoff** [comment]
Can we just merge for now? The package has full test coverage, so maybe we can just ignore bugs in the METADATA infrastructure?

**Comment by davidanthoff** [comment]
Thanks!

**Pull request merged**
