### PR TITLE
Register LinearOperators: v0.1.0

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by tkelman** [comment]
needs a minimum julia version requirement

**Comment by dpo** [comment]
Seems like something `Pkg.publish()` could tell me before creating the pull request. I can't figure out how to update this pull request cleanly, so I'll just open another.

**Comment by tkelman** [comment]
Good point, perhaps we should make `PkgDev.publish` run a few of the metadata policy checks from https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/.test/METADATA.jl locally.

**Comment by dpo** [comment]
Some sort of package audit would save you some effort down the line. It might even involve running `Lint.jl` on the source files.

**Comment by tkelman** [comment]
I'm absolutely planning on writing something for that. It may be part of Lint.jl, it may be separate.

**Pull request closed without merging**
