### PR TITLE
Tag CpuId.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [m-j-w/CpuId.jl](https://github.com/m-j-w/CpuId.jl)
Release: [v0.1.1](https://github.com/m-j-w/CpuId.jl/releases/tag/v0.1.1)
Diff: [vs v0.1.0](https://github.com/m-j-w/CpuId.jl/compare/5c1eb0f85519749dd9a61bab56d38101f016784e...13d3a0180bacb37833a48afa746f09f2793d9189)
`requires` vs v0.1.0: no changes
cc: @m-j-w

### CODE REVIEW

**Comment by m-j-w** [comment]
@tkelman Don't merge this PR ! I Only need the logfiles of the tests!
(because the CPU on the testing machine is not correctly detected...)

**Comment by tkelman** [comment]
Which tests? You could also just create a testing branch if you want to trigger travis, don't have to tag releases to do that

**Comment by m-j-w** [comment]
Argh, no, wrong machine. I saw in the test logs of Julia Package Listing there used CPU which is not correctly identified. But I now see that METADATA is yet doing those tests...
Newer mind, I'll delete the PR.

**Comment by tkelman** [comment]
That runs from https://github.com/JuliaCI/PackageEvaluator.jl. To run that locally you need vagrant, and to test just your package you can change the wildcards at https://github.com/JuliaCI/PackageEvaluator.jl/blob/6ce0f742f644435403a2df978c68505971267d64/scripts/setup.sh#L150 to instead list just your package, then try `./runvagrant.sh`

**Comment by m-j-w** [comment]
Thanks!

**Comment by tkelman** [comment]
Though http://pkg.julialang.org/logs/CpuId_0.5.log looked fine to me?

**Comment by m-j-w** [comment]
Data cache, level 1:3 : (32,32,6144) kbytes
should be (32, 256, 8194) kbytes

So close, but not exactly.

**Comment by tkelman** [comment]
Ok carry on then. Probably a vagrant thing if I had to guess.

**Pull request closed without merging**
