### PR TITLE
Register new package ImplicitEquations

### PR DESCRIPTION
**Pull request by jverzani**
This package provides a means to graph two dimensional implicit equations and inequalities following a strategy of [Tupper](http://www.dgp.toronto.edu/people/mooncake/papers/SIGGRAPH2001_Tupper.pdf)

### CODE REVIEW

**Comment by tkelman** [comment]
Should this add a `julia 0.3` requirement?

**Comment by jverzani** [comment]
Thanks. Added to master. (Is there an easy way to update this pull request that doesn't involve just tagging a new version? Does editing through Github work?)

**Comment by tkelman** [comment]
push to the same branch. editing through github would likely work, if you're careful that what you push matches what `Pkg.tag` would do

**Comment by jverzani** [comment]
I'm wary of my git skills messing up the METADATA. :(  If all I have to use are the `Pkg.*` commands, I think I'll just tag a new version once this gets added.

**Pull request merged**
