### PR TITLE
Register new package agl_aglfn.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [sambitdash/agl_aglfn.jl](https://github.com/sambitdash/agl_aglfn.jl)
Release: [v0.0.1](https://github.com/sambitdash/agl_aglfn.jl/releases/tag/v0.0.1)
cc: @sambitdash

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@sambitdash This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by sambitdash** [comment]
The JuliaCIBot error is understandable as this is first time registration.

**Comment by tkelman** [comment]
No, https://github.com/sambitdash/agl_aglfn.jl/blob/master/src/agl-aglfn.jl is incorrectly named - it should have the same name as the module, and module names can't have `-` in them. Naming conventions for Julia packages (and modules) would generally begin with a capital letter.

**Comment by sambitdash** [comment]
fixed and retagged.

**Comment by sambitdash** [comment]
all tests passing now.

**Comment by sambitdash** [comment]
Can this be expedited a bit? I have dependencies which are breaking.

**Comment by kmsquire** [comment]
HI @sambitdash, as @tkelman noted, 

> Naming conventions for Julia packages (and modules) would generally begin with a capital letter.

Have you read through the [Package Development docs](https://docs.julialang.org/en/stable/manual/packages/#Package-Development-1), specifically the section on [package naming](https://docs.julialang.org/en/stable/manual/packages/#Guidelines-for-naming-a-package-1)?

If you follow those, it would be best to rename your package to something like `AdobeGlyphs.jl`, to put it in line with the rest of the packages in the repo and make it easy understand the package's purpose.

**Comment by kmsquire** [comment]
Also, can you be more descriptive about how your dependencies that are breaking?  Until the package is registered, you can simply run `Pkg.clone("https://github.com/sambitdash/agl_aglfn.jl.git")` to have it installed locally (and you can instruct other users to do the same, although that's obviously less nice).

**Comment by sambitdash** [comment]
@kmsquire, I can modify the package name to Julia convention of capitalizing but the original package is not owned by me. Adobe's original package is called `agl-aglfn`. Most people may search it that way. I renamed it minimally by adding the underscore `_`. But we have to have the first letter capital, I propose `AdobeGlyphList` as that's what AGL stands for. There are also other glyph related packages Adobe has and it may create confusion. Let me know what works, I will change accordingly.

I have no issues with local builds of cloning the repo. The issue is more with the build failures at GitHub.

**Comment by kmsquire** [comment]
AdobeGlyphLists.jl sounds like a good name. If you include something about agl-aglfn in the description, it still should be quite searchable.  Even more so if one of your files is named `agl-aglfn.jl`.

**Comment by sambitdash** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/11069 created. This can be closed.

**Pull request closed without merging**
