### PR TITLE
Tag Bridge.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [mschauer/Bridge.jl](https://github.com/mschauer/Bridge.jl)
Release: [v0.8.0](https://github.com/mschauer/Bridge.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/mschauer/Bridge.jl/builds/422130977)
Diff: [vs v0.7.0](https://github.com/mschauer/Bridge.jl/compare/ed79aad8c8a54b1aaefe4ac925cf5fe3fb7259b5...d91c600163c3d1624608043e19d2bdbebc5c791c)
`requires` vs v0.7.0: no changes
cc: @mschauer

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by mschauer** [comment]
I did not put an upper bound because older versions do not have that. If needed I could add one with the next version?

**Comment by andreasnoack** [comment]
It would be great to add an upper bound and also open a PR with upper bounds on previous versions.

**Comment by mschauer** [comment]
JuliaCIBot shows a red X but at the same time reports success https://juliarun-ci.s3.amazonaws.com/8aaf6c2384de5116169eb402971f235814802ab9/pull_request_of_Bridge_on_julia_0_6.log
```
...
INFO: Testing Bridge
INFO: Bridge tests passed
...
```

**Comment by andreasnoack** [comment]
cc @nkottary

**Pull request merged**
