### PR TITLE
Register new package Pluck.jl v0.0.2

### PR DESCRIPTION
**Pull request by djsegal**
Repository: [djsegal/Pluck.jl](https://github.com/djsegal/Pluck.jl)
Release: [v0.0.2](https://github.com/djsegal/Pluck.jl/releases/tag/v0.0.2)
Travis: [Travis Build Status](https://travis-ci.org/djsegal/Pluck.jl)
cc: @djsegal

-----

from github description:

> pluck random values from arrays in julia

has two versions of pluck:

+ pluck - nonmutating
+ pluck! - mutating (depletes an array after N calls)

// some languages call this: `sample`

-----

at the moment, can work on arrays and key/value iterators

used by: [Fake.jl](https://github.com/JuliaLang/METADATA.jl/pull/12205)

### CODE REVIEW

**Comment by djsegal** [comment]
from github description:

> pluck random values from arrays in julia

has two versions of pluck:

+ pluck - nonmutating
+ pluck! - mutating (depletes an array after N calls)

some languages call this: `sample`

// i just thought that would be confusing

-----

used by: [Fake.jl](https://github.com/JuliaLang/METADATA.jl/pull/12205)

**Comment by djsegal** [comment]
Note that in `v0.0.2` moving forward, more types will be added to pluck

This started with:

+ https://github.com/djsegal/Pluck.jl/commit/d30098834d4fed7748a22326d0456fb4c7fb7d5e

**Comment by KristofferC** [comment]
This is called sampling (with our without replacement) and is provided by http://juliastats.github.io/StatsBase.jl/latest/sampling.html#Sampling-from-Population-1.

**Comment by djsegal** [comment]
Seems a little like BloatWare to load 8k+ LOC for a sample function?

**Comment by KristofferC** [comment]
Providing a rich, coherent API for dealing with statistics is not bloatware. 

Since you said

> The package probably should be left in the dust.

I think we can close this.

**Comment by djsegal** [comment]
If that gets your rocks off, don't want to get in the way. Loading 15k lines for a sample function is ridiculous though. Maybe you'll realize that in time

Looking forward to the next package, dan

**Pull request closed without merging**
