### PR TITLE
Tag SimpleGraphs.jl v0.2.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [scheinerman/SimpleGraphs.jl](https://github.com/scheinerman/SimpleGraphs.jl)
Release: [v0.2.5](https://github.com/scheinerman/SimpleGraphs.jl/releases/tag/v0.2.5)
Travis: [Travis Build Status](https://travis-ci.org/scheinerman/SimpleGraphs.jl/builds/449475077)
Diff: [vs v0.2.4](https://github.com/scheinerman/SimpleGraphs.jl/compare/a3e705658e6d0657b15b04dff4d61dea8fe63c0c...6633e3e8e807eb56eb1de3fd9f99165c4fb05be4)
`requires` vs v0.2.4: 
```diff
--- 0.2.4/requires
+++ 0.2.5/requires
@@ -7,3 +7,4 @@
 IterTools
 Optim
 LightXML
+AbstractLattices
```
cc: @scheinerman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by scheinerman** [comment]
Is the Julia CI Bot having issues again? Or should I draft a new release? (Everything passes on my computer and on travis.

**Comment by andreasnoack** [comment]
No. CIBot works just as intended. Did you read the logs? It looks like your release breaks `DrawSimpleGraphs`. The error is
```julia
ERROR: LoadError: UndefVarError: get_fill_color not defined
Stacktrace:
 [1] draw_nodes(::SimpleGraph{Int64}) at /home/jrun/DrawSimpleGraphs/.julia/packages/DrawSimpleGraphs/9RJmY/src/DrawSimpleGraphs.jl:29
 [2] draw(::SimpleGraph{Int64}) at /home/jrun/DrawSimpleGraphs/.julia/packages/DrawSimpleGraphs/9RJmY/src/DrawSimpleGraphs.jl:55
 [3] top-level scope at none:0
 [4] include at ./boot.jl:317 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1038
 [6] include(::Module, ::String) at ./sysimg.jl:29
 [7] include(::String) at ./client.jl:388
 [8] top-level scope at none:0
in expression starting at /home/jrun/DrawSimpleGraphs/.julia/packages/DrawSimpleGraphs/9RJmY/test/runtests.jl:4
```

**Comment by scheinerman** [comment]
Thanks so much for writing. I did read the logs and they confused me, but now I think I understand better. What I did was changed the name of a function in `SimpleGraphs`. This function is used by `DrawSimpleGraphs` and I got that ready. I *thought* I should retag `SimpleGraphs` first and, once that was accepted, then retag `DrawSimpleGraphs` (since `DrawSimpleGraphs` requires `SimpleGraphs`, and not vice versa). So I have a chicken-and-egg problem. What's the best way for me to proceed? I appreciate your help!

**Comment by andreasnoack** [comment]
One solution would be to deprecate the old functions instead of just removing it. Then it would just give a warning instead of an error in `DrawSimpleGraphs`. Another option would be to add an upper bound on `SimpleGraphs` in the existing releases of `DrawSimpleGraphs`. Finally, since it's your own package, we could also merge this PR as is with the understanding that you tag a release of `DrawSimpleGraphs` right away.

The deprecation solution is probably the preferred but can occasionally feel overly complicated if all downstream packages can easily be updated at the same time. If you prefer just to update `DrawSimpleGraphs` then it's okay to open the PR to METADATA alongside the PR to `SimpleGraphs` and leave a comment that it depends on another PR. That's a good way to signal this dependency. Then you can update the tag as soon as the first PR has been merged to trigger the tests again and have the second PR merged.

**Comment by scheinerman** [comment]
Thanks. I decided to go the "easy" route and tag a release for `DrawSimpleGraphs`.  I'll make a comment there too. The `DrawSimpleGraphs` might fail on travis because of the change (because `SimpleGraphs` is in its dependency).

**Pull request merged**
