### PR TITLE
Tag GLPK.jl v0.4.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaOpt/GLPK.jl](https://github.com/JuliaOpt/GLPK.jl)
Release: [v0.4.2](https://github.com/JuliaOpt/GLPK.jl/releases/tag/v0.4.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaOpt/GLPK.jl/builds/212990250)
Diff: [vs v0.4.1](https://github.com/JuliaOpt/GLPK.jl/compare/835726b1abf25a50e55d132152449306e58128d8...d3d3bf632346824c22cf1f7fca6983fdf6c18cc8)
`requires` vs v0.4.1: no changes
cc: @mlubin

### CODE REVIEW

**Comment by tkelman** [comment]
This caused one of JuMPeR's tests to start failing, compare
https://github.com/JuliaCI/pkg.julialang.org/blob/d0380638f8b61f6a191b5eff43b9ff1eb75fd225/logs/JuMPeR_0.5.log
to https://github.com/JuliaCI/pkg.julialang.org/blob/d0380638f8b61f6a191b5eff43b9ff1eb75fd225~/logs/JuMPeR_0.5.log

**Comment by mlubin** [comment]
CC @yeesian, de facto maintainer of JuMPeR

**Comment by yeesian** [comment]
Yeah, it's the same error as in [this PR](https://github.com/IainNZ/JuMPeR.jl/pull/74): https://travis-ci.org/IainNZ/JuMPeR.jl/builds/219071505.

I can't reproduce it locally though, and don't have the time to look into it.

**Comment by tkelman** [comment]
I can reproduce if I run in a clean JULIA_PKGDIR

**Comment by mlubin** [comment]
@yeesian, I don't think the homebrew binaries were updated, so if the issue is due to the version bump you won't see it on OS X.

**Pull request merged**
