### PR TITLE
Face tracking packages: support for Julia 0.4

### PR DESCRIPTION
**Pull request by dfdx**
This PR contains new tags for several packages for image transformation and face tracking. These new tags introduce support for Julia v0.4.

### CODE REVIEW

**Comment by timholy** [comment]
Cool stuff!

**Comment by dfdx** [comment]
@timholy Thanks. If fact, if you take a look at requirements of these packages, you will find that all of them are largely based on one or more of your own packages. So kudos to you and all the team working on great image ecosystem in Julia!

**Comment by tkelman** [comment]
FaceDatasets and ActiveAppearanceModels should add `julia` lines to their `REQUIRE` files to reflect the lowest version of Julia they are tested on.

**Comment by dfdx** [comment]
Good point. I added requirements in #3324

**Pull request merged**
