### PR TITLE
Register GraphPlot

### PR DESCRIPTION
**Pull request by sbromberger**
GraphPlot has moved under JuliaGraphs and it's time we registered it :)

### CODE REVIEW

**Comment by tkelman** [comment]
see comments at https://github.com/JuliaLang/METADATA.jl/pull/6375

**Comment by sbromberger** [comment]
Thanks. I've fixed everything, and now I'm getting

```
julia> Pkg.tag("GraphPlot", v"0.1.0")
INFO: Tagging GraphPlot v0.1.0

julia> Pkg.register("GraphPlot")
INFO: Registering GraphPlot at git://github.com/JuliaGraphs/GraphPlot.jl.git
INFO: Tagging GraphPlot v0.1.0
INFO: Committing METADATA for GraphPlot

julia> Pkg.publish()
INFO: Validating METADATA
ERROR: KeyError: GraphPlot not found
 in getindex at dict.jl:738
 in undirected_dependencies_subset at pkg/query.jl:366
 in sanity_check at pkg/resolve.jl:54
 in check_metadata at pkg/entry.jl:629
 in publish at pkg/entry.jl:372
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61
```

Any ideas?

**Comment by tkelman** [comment]
do register and tag the other way around

**Comment by sbromberger** [comment]
Nope, unless I'm doing something really stupid:

```
julia> Pkg.register("GraphPlot")
INFO: Registering GraphPlot at git://github.com/JuliaGraphs/GraphPlot.jl.git
INFO: Committing METADATA for GraphPlot

julia> Pkg.tag("GraphPlot", v"0.1.0")
INFO: Tagging GraphPlot v0.1.0
INFO: Committing METADATA for GraphPlot

julia> Pkg.publish()
INFO: Validating METADATA
ERROR: KeyError: GraphPlot not found
 in getindex at dict.jl:738
 in undirected_dependencies_subset at pkg/query.jl:366
 in sanity_check at pkg/resolve.jl:54
 in check_metadata at pkg/entry.jl:629
 in publish at pkg/entry.jl:372
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61
```

**Comment by tkelman** [comment]
what's `git status` and `git log -3` in your METADATA?

**Comment by sbromberger** [comment]
I made sure to do a `git reset HEAD~` and `git pull` in METADATA prior to this, but:

```
phasebang:METADATA bromberger1$ git status
On branch metadata-v2
Your branch is ahead of 'origin/metadata-v2' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

commit ac6d0643997d8692235aa5d21b22a55c8ca2764c
Author: Seth Bromberger <github@bromberger.com>
Date:   Mon Sep 19 13:02:58 2016 -0700

    Tag GraphPlot v0.1.0

commit 071bd659873817ee04c159e3c3f121b7a9ae7c94
Author: Seth Bromberger <github@bromberger.com>
Date:   Mon Sep 19 13:02:34 2016 -0700

    Register GraphPlot

commit d60b28156491dcb96a4aee702b469920183e0e64
Merge: c2c31fd 9dd5c4b
Author: Tony Kelman <tony@kelman.net>
Date:   Mon Sep 19 11:23:18 2016 -0700

    Merge pull request #6410 from andreasnoack/anj/ijulia

    Tag IJulia v1.3.1 [https://github.com/JuliaLang/IJulia.jl]
```

**Comment by tkelman** [comment]
what do `git show HEAD` and `git show HEAD~` look like then?

**Comment by sbromberger** [comment]
after the `git reset HEAD~`:

```
METADATA $ git reset HEAD~
METADATA $ git status
On branch metadata-v2
Your branch is up-to-date with 'origin/metadata-v2'.
nothing to commit, working tree clean
METADATA $ git show HEAD
commit d60b28156491dcb96a4aee702b469920183e0e64
Merge: c2c31fd 9dd5c4b
Author: Tony Kelman <tony@kelman.net>
Date:   Mon Sep 19 11:23:18 2016 -0700

    Merge pull request #6410 from andreasnoack/anj/ijulia

    Tag IJulia v1.3.1 [https://github.com/JuliaLang/IJulia.jl]

phasebang:METADATA bromberger1$ git show HEAD~
commit c2c31fdc9d63c7c934998178cde603758f488d0c
Merge: bc37270 099b744
Author: Tony Kelman <tony@kelman.net>
Date:   Mon Sep 19 11:21:14 2016 -0700

    Merge pull request #6409 from JeffBezanson/metadata-v2

    update URL for FixedPointNumbers for the move to JuliaMath
```

**Comment by tkelman** [comment]
I meant for the register and tag commits

**Comment by sbromberger** [comment]
Well, crud. ok. one sec.

**Comment by sbromberger** [comment]
```
METADATA $ git show HEAD~
commit 65b88c0d4cee9c0757ecce5d1f3f41a07ed8907b
Author: Seth Bromberger <github@bromberger.com>
Date:   Mon Sep 19 17:09:20 2016 -0700

    Register GraphPlot

diff --git a/GraphPlot/url b/GraphPlot/url
new file mode 100644
index 0000000..b8ca1af
--- /dev/null
+++ b/GraphPlot/url
@@ -0,0 +1 @@
+git://github.com/JuliaGraphs/GraphPlot.jl.git
METADATA $ git show HEAD
commit 77205375640eda57be3fa981f639743cc2a109df
Author: Seth Bromberger <github@bromberger.com>
Date:   Mon Sep 19 17:09:30 2016 -0700

    Tag GraphPlot v0.1.0

diff --git a/GraphPlot/versions/0.1.0/requires b/GraphPlot/versions/0.1.0/requires
new file mode 100644
index 0000000..1113c9a
--- /dev/null
+++ b/GraphPlot/versions/0.1.0/requires
@@ -0,0 +1,6 @@
+julia 0.5-
+Colors
+ColorTypes
+Compose
+Graphs
+LightGraphs
diff --git a/GraphPlot/versions/0.1.0/sha1 b/GraphPlot/versions/0.1.0/sha1
new file mode 100644
index 0000000..ad5954b
--- /dev/null
+++ b/GraphPlot/versions/0.1.0/sha1
@@ -0,0 +1 @@
+b2fd3e142a0335f0241801c14b5a152de37e75ec
```

**Comment by tkelman** [comment]
You're using 0.4 there? Just do http://docs.julialang.org/en/release-0.4/manual/packages/#man-manual-publish, and don't forget to `git push --tags` the release tag to the package as well.

**Comment by sbromberger** [comment]
Closing in favor of #6452.

**Pull request closed without merging**
