### PR TITLE
Tag TikzPictures v0.3.4

### PR DESCRIPTION
**Pull request by mykelk**
Remove 0.5 deprecation by using Compat.

### CODE REVIEW

**Comment by tkelman** [comment]
Note that due to missing lualatex this has been failing on PackageEvaluator: http://pkg.julialang.org/detail/TikzPictures.html

Are there still tests you could do as a fallback when lualatex isn't available? It's a test-only dependency, right?

**Comment by mykelk** [comment]
Yep, it's a test-only dependency. There are some tests we could do (it can output raw tex files), but for the most part TikzPictures is pretty useless without latex installed because it uses latex to generate pictures (e.g., SVG or PDF).

**Comment by tkelman** [comment]
So there are things under src that users would want to do that won't work without a latex installation present? sounds like maybe the package should check if that's the case and install one locally if it can't find an existing install?

**Comment by mykelk** [comment]
I thought about doing that. The problem is that a latex distribution is pretty huge. Perhaps there should be a texlive.jl package that handles this.

**Comment by tkelman** [comment]
Having a specific package for it sounds like it would be a good idea.

**Comment by mykelk** [comment]
I just tagged a new release that skips some tests if lualatex is not found.

**Pull request merged**
