### PR TITLE
Tag OdsIO.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [sylvaticus/OdsIO.jl](https://github.com/sylvaticus/OdsIO.jl)
Release: [v0.4.0](https://github.com/sylvaticus/OdsIO.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/sylvaticus/OdsIO.jl/builds/419067023)
Diff: [vs v0.3.0](https://github.com/sylvaticus/OdsIO.jl/compare/1323c3a8b03e926501fd627910eccf70de500e28...5edb57f7721fc6d53ea43898b923d351558a32ce)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -1,4 +1,5 @@
-julia 0.6
+julia 0.7
 PyCall 1.7
 DataFrames 0.11.3
 DataStructures 0.7.4
+Missings 0.2.10
```
cc: @sylvaticus

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like tests are failing. Please also adjust your .travis.yml to reflect the new requirements, i.e. drop 0.6 and add 0.7 and 1.0.

**Comment by sylvaticus** [comment]
Thank you. My test is actually failing also in Julia 0.7/1.0.

The problem seems that the build script (/deps/build.jl) seems it's not executed.
The build script installs a necessary python module ("ezodf"), eventually installing pip:

```
using PyCall

println("Running build.jl for the OdsIO package.")

# Change that to whatever packages you need.
const PACKAGES = ["ezodf","lxml"]

# Use eventual proxy info
proxy_arg=String[]
if haskey(ENV, "http_proxy")
    push!(proxy_arg, "--proxy")
    push!(proxy_arg, ENV["http_proxy"])
end

# Import pip
try
    @pyimport pip
catch
    # If it is not found, install it
    println("Pip not found on your sytstem. Downloading it.")
    get_pip = joinpath(dirname(@__FILE__), "get-pip.py")
    download("https://bootstrap.pypa.io/get-pip.py", get_pip)
    run(`$(PyCall.python) $(proxy_arg) $get_pip --user`)
end

println("Installing required python packages using pip")
run(`$(PyCall.python) $(proxy_arg) -m pip install --user --upgrade pip setuptools`)
run(`$(PyCall.python) $(proxy_arg) -m pip install --user $(PACKAGES)`)
```

How do I enforce its execution at install time in Julia 0.7/1.0 ?

**Comment by andreasnoack** [comment]
See https://travis-ci.org/sylvaticus/OdsIO.jl/jobs/419067026#L543-L553. The build script is run but it looks like there is a bug in PyCall.

**Comment by sylvaticus** [comment]
Thank you very much for your help and time.
I am  bit lost, as the version of PyCall travis is using in that failing test is v1.18.1, but going to the PyCall.jl site it seems that such version is passing the test:
https://travis-ci.org/JuliaPy/PyCall.jl/jobs/418995724

Also, in my local installation (both 0.7 and 1.0), OdsIO works (but I had to manually install the python module), so this means PyCall works in Julia 0.7/1.0.

**Comment by andreasnoack** [comment]
It's the combination of `@pyimport` and the `try`/`catch` block that is causing the trouble here. I think you can work around the issue by simply changing
```julia
try
    @pyimport pip
```
to 
```julia
try
    pyimport("pip")
```
since the latter won't try to create the `const` variable.

**Comment by sylvaticus** [comment]
@andreasnoack Thank you, you was right. That was enough to get the build script working.

**Pull request merged**
