### PR TITLE
Tag JSON v0.6.0

### PR DESCRIPTION
**Pull request by kmsquire**
v0.5.2 should probably have been a minor version bump (cf: https://github.com/JuliaLang/METADATA.jl/pull/5380#issuecomment-225941996).

This sets v0.5.3 to the previous commit, and bumps master to v0.6.0

### CODE REVIEW

**Comment by tkelman** [comment]
this appears to have broken Plotly.jl, cc @malmaud http://pkg.julialang.org/logs/Plotly_0.4.log

**Comment by malmaud** [comment]
It breaks Plotly by virtue of breaking PlotlyJS, so CC @spencerlyon2

**Comment by spencerlyon2** [comment]
Thanks for the heads up. I merged a fix for this on PlotlyJS master.

I'm adding a couple new things to that branch before tagging here. Should be tagged in the next couple of hours.

**Comment by TotalVerb** [comment]
All breaking changes are downstream issues: see https://github.com/JuliaLang/METADATA.jl/pull/5398#issuecomment-226655603. No further action is needed here.

**Pull request merged**
