### PR TITLE
Tag Phylo.jl v0.3.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [richardreeve/Phylo.jl](https://github.com/richardreeve/Phylo.jl)
Release: [v0.3.2](https://github.com/richardreeve/Phylo.jl/releases/tag/v0.3.2)
Travis: [Travis Build Status](https://travis-ci.org/richardreeve/Phylo.jl/builds/416788272)
Diff: [vs v0.3.1](https://github.com/richardreeve/Phylo.jl/compare/e7ab2b7ed20c1ffbbd917b5a4a3b96607d9b0833...fb94e95885d4168ba475d8c0c78d5b9b4dac7b78)
`requires` vs v0.3.1: no changes
cc: @richardreeve

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by richardreeve** [comment]
As with v0.3.1, this seems to be a false negative - my CI tests work, but there's a problem with the testing here.

**Comment by andreasnoack** [comment]
Yes. I'm currently working on upgrading our tests to the new release so this failure is related to a bug in the test code. I'll restart the tests once the bug is fixed.

**Comment by richardreeve** [comment]
If you could merge this anyway that would be great, as I'm now fixing Diversity.jl, which depends on this functioning...

**Comment by andreasnoack** [comment]
I'll only be able to merge this once it passes our tests so you'd have to wait a little longer.

**Comment by richardreeve** [comment]
Okay.

**Comment by andreasnoack** [comment]
I think the tests work again now so I'll restart and merge if they pass.

**Pull request merged**
