### PR TITLE
Register new package ModernRoboticsBook.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ferrolho/ModernRoboticsBook.jl](https://github.com/ferrolho/ModernRoboticsBook.jl)
Release: [v0.1.1](https://github.com/ferrolho/ModernRoboticsBook.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/ferrolho/ModernRoboticsBook.jl/builds/497905754)
cc: @ferrolho

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ferrolho This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by ferrolho** [comment]
@andreasnoack, my apologies in advance if you are not the right person to tag for this: I think @attobot mistakenly closed this PR.

I forgot to update the UUID after renaming this package. After having updated the correct UUID, I deleted the release and the tag and re-released the repos including the UUID change commit. I think this triggered @attobot to close this PR, but not to re-open it.

**Comment by andreasnoack** [comment]
@simonbyrne Do you know why Atto did this?

**Comment by ferrolho** [comment]
Ok, I deleted the tag once again, waited ~5 mins and re-released it again. It seems to have worked: https://github.com/JuliaLang/METADATA.jl/pull/21709. Maybe I just did the delete and re-release actions too quickly that Atto triggered the delete/update actions with the wrong timings?

**Comment by simonbyrne** [comment]
I'm not sure exactly what happened here. I didn't think attobot could close PRs...

**Pull request closed without merging**
