### PR TITLE
Tag DifferentialEquations.jl v4.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DifferentialEquations.jl](https://github.com/JuliaDiffEq/DifferentialEquations.jl)
Release: [v4.0.0](https://github.com/JuliaDiffEq/DifferentialEquations.jl/releases/tag/v4.0.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/DifferentialEquations.jl/builds/333911905)
Diff: [vs v3.1.0](https://github.com/JuliaDiffEq/DifferentialEquations.jl/compare/3db2976b60ebc59b7469b8998ef7ba16d9d9c9e3...6ce0ba44ba844b5b4ec5ec5393297ed3ceb9a6cf)
`requires` vs v3.1.0: 
```diff
--- 3.1.0/requires
+++ 4.0.0/requires
@@ -1,27 +1,25 @@
 julia 0.6
 Reexport 0.0.3
-DiffEqBase 1.0.0 3.0.0
-StochasticDiffEq 2.11.1
-FiniteElementDiffEq 0.3.0
-BoundaryValueDiffEq
-DiffEqDevTools 0.8.0
-OrdinaryDiffEq 2.11.0 3.0.0
-AlgebraicDiffEq 0.1.0
-DiffEqParamEstim 0.3.0
-DiffEqSensitivity 0.2.1
-Sundials 0.11.0
-ParameterizedFunctions 2.0.0
-DiffEqPDEBase 0.3.0
-DelayDiffEq 0.3.0
-DiffEqCallbacks 0.0.2
-DiffEqMonteCarlo 0.3.0
-DiffEqJump 0.3.0
-DiffEqFinancial 0.2.0
-DiffEqBiological 0.0.1
-MultiScaleArrays 0.1.0
+DiffEqBase 3.0.0
+StochasticDiffEq 3.0.0
+BoundaryValueDiffEq 1.0.0
+DiffEqDevTools 1.0.0
+OrdinaryDiffEq 3.0.0
+DiffEqParamEstim 1.0.0
+DiffEqSensitivity 1.0.0
+Sundials 1.0.0
+ParameterizedFunctions 3.0.0
+DiffEqPDEBase 0.4.0
+DelayDiffEq 2.0.0
+DiffEqCallbacks 1.0.0
+DiffEqMonteCarlo 0.10.0
+DiffEqJump 1.0.0
+DiffEqFinancial 1.0.0
+DiffEqBiological 1.0.0
+MultiScaleArrays 0.5.0
 DimensionalPlotRecipes 0.0.2
-RecursiveArrayTools 0.4.1
-DiffEqNoiseProcess 0.0.1
-SteadyStateDiffEq 0.0.1
-DiffEqUncertainty
-DiffEqPhysics
+RecursiveArrayTools 0.14.0
+DiffEqNoiseProcess 1.0.0
+SteadyStateDiffEq 0.2.0
+DiffEqUncertainty 0.1.0
+DiffEqPhysics 1.0.0
```
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
The Travis error seems to be a resolver issue, but it's in every test. But this is a huge change where nothing from before is compatible. I double checked that I put the right minimum bounds so I don't know what it could be.

**Comment by ChrisRackauckas** [comment]
@ararslan @aviks I've checked with higher accuracy

```
julia> ENV["JULIA_PKGRESOLVE_ACCURACY"]=10000
10000

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating DifferentialEquations master...
INFO: Computing changes...
ERROR: resolve is unable to satisfy package requirements.
  The problem was detected when trying to find a feasible version
  for package RecursiveArrayTools.
  However, this only means that package RecursiveArrayTools is involv
ed in an
  unsatisfiable or difficult dependency relation, and the root of
  the problem may be elsewhere.
```

and I have no idea what's going on (yes, that accuracy is absurd, I know 👍 )

**Comment by ChrisRackauckas** [comment]
I found it by adding the packages one by one...

**Comment by ararslan** [comment]
Looks like it's happening in your package's Travis tests as well

**Comment by ChrisRackauckas** [comment]
Should be fixed by https://github.com/JuliaLang/METADATA.jl/pull/13114 . Fingers crossed.

**Comment by ChrisRackauckas** [comment]
Finally! JuliaCIBot didn't run but the repo's Travis tests are passing, so I'm going for it. Thanks for the help and sorry for the troubles with this one!

**Comment by ararslan** [comment]
Sorry, race condition. I closed and reopened right as you said that.

**Comment by ChrisRackauckas** [comment]
Nevermind then 👍 

JuliaCIBot will be expected to fail on BioEnergeticFoodWebs.jl though, so it won't be very interesting.

**Pull request merged**
