### PR TITLE
Tag DrakeVisualizer.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rdeits/DrakeVisualizer.jl](https://github.com/rdeits/DrakeVisualizer.jl)
Release: [v0.1.0](https://github.com/rdeits/DrakeVisualizer.jl/releases/tag/v0.1.0)
Diff: [vs v0.0.1](https://github.com/rdeits/DrakeVisualizer.jl/compare/516c69e5f2e0c8cc2fd5baf12aa2bbb733740454...00387b454ba28d1ec44ce11e597f73fe5810b18d)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.1.0/requires
@@ -1,6 +1,5 @@
 julia 0.5
-PyLCM 0.0.3
-PyCall 1.4.0
+LCMCore 0.0.2
 BinDeps 0.4.0
 GeometryTypes 0.1.6
 ColorTypes 0.2.0
@@ -8,3 +7,5 @@
 Rotations 0.2.0
 CoordinateTransformations 0.2.0
 StaticArrays 0.0.4
+DataStructures 0.4
+JSON 0.8
```
cc: @rdeits

### CODE REVIEW

**Comment by tkelman** [comment]
you should use `dirname(@__FILE__)`, not `Pkg.dir`, to be correct if the package gets installed elsewhere on LOAD_PATH

**Comment by tkelman** [comment]
since your demo notebook does `using Reactive` and you NBinclude that notebook in a test, should add Reactive explicitly to `test/REQUIRE`

**Comment by rdeits** [comment]
Thanks @tkelman. I keep forgetting about the Pkg.dir() thing; I've added it to my checklist, so hopefully this will be the last time. I'll update the release.

**Comment by rdeits** [comment]
@tkelman can you please hold off on merging this for a moment? There's a change from upstream at https://github.com/RobotLocomotion/director that I'd like to integrate before this gets merged. Should be done within the hour.

**Comment by rdeits** [comment]
Ok, good to go.

**Pull request merged**
