### PR TITLE
New OnlineStats release + upper bounds for OnlineStatsBase

### PR DESCRIPTION
**Pull request by joshday**
This PR adds upper bounds for OnlineStatsBase in the requires of OnlineStats.

Subsumes:
- https://github.com/JuliaLang/METADATA.jl/pull/14024
- https://github.com/JuliaLang/METADATA.jl/pull/14003

Requires https://github.com/JuliaLang/METADATA.jl/pull/14002 first

### CODE REVIEW

**Comment by andreasnoack** [comment]
@shashi Is this fine with you?

**Comment by andreasnoack** [comment]
There is a problem here though
```
ERROR: LoadError: packages with unsatisfiable requirements found:
    OnlineStats v0.17.0 – no valid versions exist for package 
```

**Comment by andreasnoack** [comment]
Never mind. I forgot that the OnlineStatsBase PR was needed for this one

**Comment by andreasnoack** [comment]
@joshday It looks like there is a test failure here.

**Comment by joshday** [comment]
Nothing's broken...just a bad test.  I'll change the commit.

**Pull request merged**
