### PR TITLE
Register new package Multisets.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [scheinerman/Multisets.jl](https://github.com/scheinerman/Multisets.jl)
Release: [v0.0.1](https://github.com/scheinerman/Multisets.jl/releases/tag/v0.0.1)
cc: @scheinerman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@scheinerman This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
It's highly recommended to add a few unit tests.

**Comment by scheinerman** [comment]
Agreed. I just need to get some time to work on that.

**Comment by scheinerman** [comment]
OK. Added some basic tests.

**Comment by PallHaraldsson** [comment]
```
The following can be used for testing subset and superset:

    A <= B
    A < B
    A >= B
    A > B
```
This might be ok, or not.. I just know about the proper Unicode symbol for "in set" (and `in` operator); not sure about one for e.g. superset.

**Comment by MikeInnes** [comment]
seems to be superceded by #11037

**Pull request closed without merging**
