### PR TITLE
Add Ensemble.jl (Ensemble MCMC and other Stochastic Samplers) to package list

### PR DESCRIPTION
**Pull request by farr**
This package implements the algorithm from the [`emcee`](https://github.com/dfm/emcee) sampler, several other stochastic sampling algorithms based on the same fundamental "stretch move," and provides some useful library functions for performing stochastic sampling in Julia.

### CODE REVIEW

**Comment by tkelman** [comment]
what's the minimum supported version of julia?

**Comment by farr** [comment]
Oops.  I suspect anything would do, but I have used it since Julia 0.4, so I have added this to the REQUIRE file in the Ensemble.jl.git repo and my fork of METADATA.jl

**Comment by farr** [comment]
Just pushed the tag to the upstream repo (Ensemble.jl.git).  Sorry for being such a newb.

**Comment by tkelman** [comment]
If you enabled Travis CI, would your tests pass there?

**Comment by farr** [comment]
Thanks!

**Pull request merged**
