### PR TITLE
Register new package graphmol.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [mojaie/graphmol.jl](https://github.com/mojaie/graphmol.jl)
Release: [v0.1.1](https://github.com/mojaie/graphmol.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/mojaie/graphmol.jl/builds/475157461)
cc: @mojaie

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@mojaie This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please make the package name more explicit, eg. GraphMolecularModeling.jl

**Comment by mojaie** [comment]
Sure. I will rename it to MolecularGraph.jl. Is this all right?

**Comment by dpsanders** [comment]
You will need to delete the release and the tag and make a new release so that attobot picks up the new name.

**Comment by mojaie** [comment]
Renamed #20396

**Pull request closed without merging**
