### PR TITLE
Pyamg test fix

### PR DESCRIPTION
**Pull request by cortner**

### CODE REVIEW

**Comment by tkelman** [comment]
It looks like the changes here work with IterativeSolvers 0.3 but not 0.2.x, and since IterativeSolvers 0.3 is only available for julia 0.5, then this PyAMG change fails tests on julia 0.4. Probably best to make this julia 0.5 only (and set an IterativeSolvers 0.3 minimum version in test/REQUIRE)

**Comment by cortner** [comment]
first time I've done it this way - I hope this is as intended?

**Comment by tkelman** [comment]
mostly, though it'll need to use a new package minor version, 0.1.0

**Comment by cortner** [comment]
Can you explain?

**Comment by tkelman** [comment]
dropping support for a julia version requires using at least a new package minor version

**Comment by cortner** [comment]
ok now?

**Comment by tkelman** [comment]
the IterativeSolvers requirement in test/REQUIRE should have an 0.3 lower bound, but otherwise yes

**Comment by cortner** [comment]
done. hopefully at some point I will understand this system . . .

**Comment by tkelman** [comment]
forgot to push the 0.1.1 git tag? next time around, take a look at https://github.com/attobot/attobot

**Comment by cortner** [comment]
ok, will set this up now

**Pull request merged**
