### PR TITLE
Tag RCall.jl v0.10.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaInterop/RCall.jl](https://github.com/JuliaInterop/RCall.jl)
Release: [v0.10.0](https://github.com/JuliaInterop/RCall.jl/releases/tag/v0.10.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaInterop/RCall.jl/builds/328313799)
Diff: [vs v0.9.0](https://github.com/JuliaInterop/RCall.jl/compare/3d279bd52053a40f777724e2a3acd7275f504c02...0dabc9bf05a21444efabdf96b320c17df8055e09)
`requires` vs v0.9.0: no changes
cc: @randy3k

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by randy3k** [comment]
Ready to be merged now.

**Comment by aviks** [comment]
Tests failed with 

```
macros: Error During Test
  Test threw an exception of type RCall.RParseError
  Expression: (RCall.render("x = 1\nβ = \$a"))[1] == "x = 1\nβ = `#JL`\$`a`"
  RParseError: Error: unexpected '<'
```

Is this expected?

**Comment by randy3k** [comment]
It must be a bug of earlier version of R. RCall repo’s one tests had no issues https://travis-ci.org/JuliaInterop/RCall.jl

**Comment by nkottary** [comment]
Its `3.4.3`

**Comment by randy3k** [comment]
That’s weird. I do anticipate that 3.4.3 should work. Additionally, I don’t understand why there is an unexpected '<' while there is no '<' in the line.

**Comment by richardreeve** [comment]
Any idea what's going on / can we merge this so I can use missing more pervasively in my code?

**Comment by randy3k** [comment]
I have no idea about the oddity of juliabot. The tests were successful on Travis. Perhaps we could merge it as is!?

**Comment by richardreeve** [comment]
@aviks Can we merge this then?

**Comment by randy3k** [comment]
I noticed that juliabot uses Julia v0.6.0 and thought that it may be the reason. However, a local macOS version of Julia v0.6.0 did pass the tests. I don't really have any clues now.

**Comment by aviks** [comment]
I've merged it. However, JuliaCIBot uses a reasonably standard ubuntu environment, so this is something you may see in the wild with your users. So would be good to get to the bottom of this at some point.

**Comment by randy3k** [comment]
Thanks. I will try to resolve it down the road. It may have something to do with unicode support.

**Pull request merged**
