### PR TITLE
Tag BeaData.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [stephenbnicar/BeaData.jl](https://github.com/stephenbnicar/BeaData.jl)
Release: [v0.3.0](https://github.com/stephenbnicar/BeaData.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/stephenbnicar/BeaData.jl/builds/430204927)
Diff: [vs v0.2.1](https://github.com/stephenbnicar/BeaData.jl/compare/4e4587b0e69f8ae4eded47a90bcd5ddfb66cc7fd...3caa49fb2a433dffe247fb771d067685d3670347)
`requires` vs v0.2.1: 
```diff
--- 0.2.1/requires
+++ 0.3.0/requires
@@ -1,6 +1,7 @@
-julia 0.6
+julia 0.7
 HTTP
 JSON
+Dates
 DataFrames
 DataStructures
 DocStringExtensions
```
cc: @stephenbnicar

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please remove stdlibs from your REQUIRE file

**Comment by stephenbnicar** [comment]
@andreasnoack I made the requested changes 2 weeks ago and updated the PR.  Is there something else that I need to do for this to get merged?

**Comment by andreasnoack** [comment]
If tests don't pass then the PR isn't merged automatically. Please leave a comment explaining why the tests are failing and why it would be okay to merge anyway.

**Comment by stephenbnicar** [comment]
Ok, I didn't know that.  I don't remember it ever being raised as an issue before.  

The JuliaCI tests don't pass because the package requires a proprietary key (personal to the user) and there's no straightforward way to provide one securely for the JuliCI tests.  For the Travis tests there's an encrypted version of my key that is used for the tests and they all pass.

**Comment by andreasnoack** [comment]
> Ok, I didn't know that. I don't remember it ever being raised as an issue before.

Things evolve and we are trying to make the process a little less labor intensive.

Thanks for the explanation. I'll mark the package as untestable for now. Eventually, we might get a system where it will be possible to register a key but we currently don't have any specific plans for supporting it.

**Pull request merged**
