### PR TITLE
Tag StochasticSearch v0.1.2

### PR DESCRIPTION
**Pull request by phrb**

### CODE REVIEW

**Comment by tkelman** [comment]
Raising the minimum julia version requirement from 0.3 to 0.4 would usually qualify as a breaking change, so would justify increasing the minor version number (or major if post-1.0). If there's ever a bug that needs to be fixed for julia 0.3, would have to adjust the julia requirement on the existing 0.1.0 tag to be 0.4-only then tag a new 0.0.6 version of StochasticSearch.

**Comment by phrb** [comment]
Should I close this, re-tag, and make the pull request again?

**Comment by tkelman** [comment]
That could also work, you could tag this as 0.2.0 instead.

**Comment by phrb** [comment]
Ok. Will do, thank you!

**Pull request closed without merging**
