### PR TITLE
Tag Mimi v0.1.1

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by tkelman** [comment]
Are the test failures expected here?

**Comment by davidanthoff** [comment]
They were a false alarm. The Distributions updates caused a model that uses Mimi to fail, and since we started running that model in Mimi's CI tests, we saw those bugs. All fixed now in the model, so the Mimi tests pass again.

**Comment by tkelman** [comment]
Oh, you're still cloning master of your test code. Thought you said you'd switch to a fixed sha?

**Comment by davidanthoff** [comment]
We will, but not yet :) Way behind plan on all of this...

**Pull request merged**
