### PR TITLE
Register new package PowerDynBase.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaEnergy/PowerDynBase.jl](https://github.com/JuliaEnergy/PowerDynBase.jl)
Release: [v0.2.1](https://github.com/JuliaEnergy/PowerDynBase.jl/releases/tag/v0.2.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaEnergy/PowerDynBase.jl/builds/439117804)
cc: @timkittel

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@timkittel This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by timziebart** [comment]
Hm, I am not sure what is happening here. It says explicitly in the `REQUIRE` ([see here](https://github.com/JuliaEnergy/PowerDynBase.jl/blob/master/REQUIRE#L1)) and `Project.toml` ([see here](https://github.com/JuliaEnergy/PowerDynBase.jl/blob/master/Project.toml#L13)) that the package is written for Julia 1.0 only. But for some reason, it tests the other Julia version as well. Furthermore, for Julia 1.0 it says `no julia entry (>= 0.6.0 needed)` ([see here](https://travis-ci.org/JuliaLang/METADATA.jl/jobs/439117875#L524)).
Also, the repo travis is passing the tests, [see here](https://travis-ci.org/JuliaEnergy/PowerDynBase.jl/branches).

**Comment by andreasnoack** [comment]
I think the issue is that you've capitalized `J` in the REQUIRE file. It should be `julia` not `Julia`.

**Comment by andreasnoack** [comment]
Notice that you can just update this PR. See https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by andreasnoack** [comment]
I think you might have ended up attaching the tag to the same old commit instead of your latest commit.

**Comment by timziebart** [comment]
@andreasnoack thanks for your help and yes I did. But it seems like it's working now (:

PS: You are super fast (:

**Comment by andreasnoack** [comment]
You are welcome. We have a system that will automatically merge PRs after three days unless somebody has commented after the latest Attobot comment. Hence, it would be great if you could remove and reapply the tag again since it will trigger an Attobot comment. Otherwise, I might forget to merge this.

**Pull request merged**
