### PR TITLE
Tag DiffEqBase.jl v1.17.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DiffEqBase.jl](https://github.com/JuliaDiffEq/DiffEqBase.jl)
Release: [v1.17.0](https://github.com/JuliaDiffEq/DiffEqBase.jl/releases/tag/v1.17.0)
Diff: [vs v1.16.0](https://github.com/JuliaDiffEq/DiffEqBase.jl/compare/80df0f6fe831a819fa6f549d72a3f251ba96ac32...f7fc25b5ac3a0851b4f6971e57069cf9c66ffc4d)
`requires` vs v1.16.0: no changes
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
JuliaCIBot didn't catch this one, looks like this caused a MethodError in SteadyStateDiffEq https://github.com/JuliaCI/pkg.julialang.org/blob/09b938da085c16417609c82b8832d6ec26e888f6/logs/SteadyStateDiffEq_0.6.log

**Comment by tkelman** [comment]
SteadyStateDiffEq should probably have upper bounds of 0.17 on DiffEqBase added

**Comment by ChrisRackauckas** [comment]
I'll look into this right now. Sorry, was going through a list of requests.

**Comment by ChrisRackauckas** [comment]
No, this was just a bug in DiffEqBase, not an incompatibility. Hotfix incoming.

**Pull request merged**
