### PR TITLE
Tag SVMLightLoader v0.2.1

### PR DESCRIPTION
**Pull request by IshitaTakeshi**

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like the tagged commit is not present on the master branch? https://github.com/IshitaTakeshi/SVMLightLoader.jl/commit/2234bbe8fbd37892084fd46be3e91644d15c13fc

**Comment by IshitaTakeshi** [comment]
Pushed.
https://github.com/IshitaTakeshi/SVMLightLoader.jl/commit/2234bbe8fbd37892084fd46be3e91644d15c13fc

**Comment by IshitaTakeshi** [comment]
I think it exists?

**Comment by tkelman** [comment]
Looks good now.

**Pull request merged**
