### PR TITLE
Tag FourierFlows.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [FourierFlows/FourierFlows.jl](https://github.com/FourierFlows/FourierFlows.jl)
Release: [v0.3.0](https://github.com/FourierFlows/FourierFlows.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/FourierFlows/FourierFlows.jl/builds/469504534)
Diff: [vs v0.2.2](https://github.com/FourierFlows/FourierFlows.jl/compare/5cb5d3ffbca9cafdebb34f3e5eea4f0937593b6e...5897e83f40696c759d1dfb0268c568e338644d05)
`requires` vs v0.2.2: 
```diff
--- 0.2.2/requires
+++ 0.3.0/requires
@@ -1,7 +1,4 @@
 julia 0.7
 FFTW 0.2.3
 JLD2 0.0.4
-SpecialFunctions 0.3.6
 Interpolations 0.8
-Requires 0.5.2
-ComputationalResources 0.2.0
```
cc: @navidcy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by navidcy** [comment]
Why is JuliaCIBot failing?

**Comment by andreasnoack** [comment]
You can read the logs by clicking the "Details" link next to "JuliaCIBot". It looks like this release is breaking.

**Comment by navidcy** [comment]
I'm not sure how I can resolve this. The newer version of FourierFlows `v0.3.0` I'm trying to release seems to be breaking JuliaCIBot when running `GeophysicalFlows`.

Indeed, The newer version of FourierFlows introduces breaking changes for GeophysicalFlows. There is a new upcoming release of GeophysicalFlows #20269 which is currently _also_ breaking...

What would be the best way to resolve this?
I'd expect that FourierFlows should be able to be upgraded since it does not depend on GeophysicalFlows. Then I'd be able to add FourierFlows v0.3.0 in GeophysicalFlows upcoming release and everything should be fine, no?

cheers

**Comment by andreasnoack** [comment]
The right, but slightly tedious way of handling this is to add upper bounds on the affected packages directly in METADATA. See e.g. https://github.com/JuliaLang/METADATA.jl/pull/20147. Alternatively, we can merge this knowing that it will break `GeophysicalFlows` until #20269 has been merged. It's not good to break code when you can avoid it but we sometimes do this for packages with few reverse dependencies.

**Comment by navidcy** [comment]
Thanks @andreasnoack. I’ll submit a GeophysicalFlows v0.1.1 with upper bounds on FourierFlows. Do I do that in Project.toml through [Compat] or should I also add upper bounds in the REQUIRE file?

**Comment by andreasnoack** [comment]
Please check the link above. You shouldn't make a new release with upper bounds. Instead, you should add upper bounds on existing releases directly in METADATA.

**Comment by navidcy** [comment]
I pinned FourierFlows 0.2.2 in GeophysicalFlows 0.1.0 (PR #20284). 

I’ll create the v0.3.0 tag for FourierFlows and resubmit the release shortly after the pin is merged.

**Comment by navidcy** [comment]
@andreasnoack when tests pass you can merge it

**Pull request merged**
