### PR TITLE
Register new package CardinalDicts.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/CardinalDicts.jl](https://github.com/JeffreySarnoff/CardinalDicts.jl)
Release: [v0.0.1](https://github.com/JeffreySarnoff/CardinalDicts.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/JeffreySarnoff/CardinalDicts.jl/builds/259563494)
cc: @JeffreySarnoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@JeffreySarnoff This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
fixing up .yml files

**Comment by JeffreySarnoff** [comment]
fixed -- ready

**Comment by JeffreySarnoff** [comment]
trying to bump travis-ci

**Comment by JeffreySarnoff** [comment]
admin: what can I do so travis starts?

**Comment by tkelman** [comment]
just wait a few hours, the queue for base is very long

**Comment by tkelman** [comment]
@JeffreySarnoff please rename the repository back to its registered name CardinalDicts.jl - the package fails to install at all because you seem to have done a rename by deleting and replacing a new separate repository instead of renaming via the transferring in the github settings.

**Comment by JeffreySarnoff** [comment]
I think I just did -- let me know if there is more to do.

**Comment by tkelman** [comment]
Looks good now I believe, thanks

**Pull request merged**
