### PR TITLE
Tag RCall.jl v0.11.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaInterop/RCall.jl](https://github.com/JuliaInterop/RCall.jl)
Release: [v0.11.0](https://github.com/JuliaInterop/RCall.jl/releases/tag/v0.11.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaInterop/RCall.jl/builds/414775078)
Diff: [vs v0.10.6](https://github.com/JuliaInterop/RCall.jl/compare/0b95207c775bd8018216155577f8ca8d01f4891c...eb4035801061944237b61d47e71e5631f5f838c8)
`requires` vs v0.10.6: 
```diff
--- 0.10.6/requires
+++ 0.11.0/requires
@@ -1,11 +1,9 @@
-julia 0.6
+julia 0.7.0-beta2
 Missings 0.2.0
 DataStructures 0.5.0
 DataFrames 0.11.0
-DataArrays 0.7.0
 CategoricalArrays 0.3.0
 AxisArrays 0.0.6
-Compat 0.34.0
 StatsModels 0.2.4
 Conda
 @windows WinReg 0.2.0
```
cc: @randy3k

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like test are failing on 1.0 (nightly). Please enable tests for 1.0 explicitly.

**Comment by randy3k** [comment]
this is unfortunately an issue of upstream AxisArrays. There is no fix required by RCall

**Comment by andreasnoack** [comment]
Are you sure you want a new release of RCall before either the AxisArrays issue has been fixed or the dependency removed?

**Comment by randy3k** [comment]
at least it is now working with julia v0.7 and the latest release doesn’t. It will allow users migrating to v0.7.

**Comment by randy3k** [comment]
do you think it make sense to put an upper bound for julia v1.0?

**Comment by andreasnoack** [comment]
Could you try just to remove https://github.com/JuliaInterop/RCall.jl/blob/master/.travis.yml#L29-L31 from the script and see what happens on Julia 1.0?

**Comment by randy3k** [comment]
here you are

<details>

```
51.28s$ julia --check-bounds=yes --color=yes -e "VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; Pkg.test(\"${JL_PKG}\", coverage=true)"
   Testing RCall
 Resolving package versions...
    Status `/tmp/tmpTOa2Cf/Manifest.toml`
  [39de3d68] AxisArrays v0.2.1
  [b99e7846] BinaryProvider v0.4.0
  [324d7699] CategoricalArrays v0.3.13
  [944b1d66] CodecZlib v0.4.3
  [34da2185] Compat v1.0.1
  [8f4d0f93] Conda v1.0.1
  [a93c6f00] DataFrames v0.13.0
  [9a8bc11e] DataStreams v0.4.0
  [864edb3b] DataStructures v0.11.0
  [8197267c] IntervalSets v0.2.0
  [c8e1da08] IterTools v1.0.0
  [682c06a0] JSON v0.19.0
  [e1d29d7a] Missings v0.3.0
  [6f49c342] RCall v0.10.6+ [`~/build/JuliaInterop/RCall.jl`]
  [b3c3ace0] RangeArrays v0.3.1
  [189a3867] Reexport v0.2.0
  [a2af1166] SortingAlgorithms v0.3.1
  [2913bbd2] StatsBase v0.25.0
  [3eaba693] StatsModels v0.3.0
  [3bb67fe8] TranscodingStreams v0.6.1
  [81def892] VersionParsing v1.1.1
  [ea10d353] WeakRefStrings v0.5.1
  [1b915085] WinReg v0.3.1
  [2a0f44e3] Base64  [`~/julia/bin/../share/julia/stdlib/v1.0/Base64`]
  [ade2ca70] Dates  [`~/julia/bin/../share/julia/stdlib/v1.0/Dates`]
  [8bb1440f] DelimitedFiles  [`~/julia/bin/../share/julia/stdlib/v1.0/DelimitedFiles`]
  [8ba89e20] Distributed  [`~/julia/bin/../share/julia/stdlib/v1.0/Distributed`]
  [9fa8497b] Future  [`~/julia/bin/../share/julia/stdlib/v1.0/Future`]
  [b77e0a4c] InteractiveUtils  [`~/julia/bin/../share/julia/stdlib/v1.0/InteractiveUtils`]
  [76f85450] LibGit2  [`~/julia/bin/../share/julia/stdlib/v1.0/LibGit2`]
  [8f399da3] Libdl  [`~/julia/bin/../share/julia/stdlib/v1.0/Libdl`]
  [37e2e46d] LinearAlgebra  [`~/julia/bin/../share/julia/stdlib/v1.0/LinearAlgebra`]
  [56ddb016] Logging  [`~/julia/bin/../share/julia/stdlib/v1.0/Logging`]
  [d6f4376e] Markdown  [`~/julia/bin/../share/julia/stdlib/v1.0/Markdown`]
  [a63ad114] Mmap  [`~/julia/bin/../share/julia/stdlib/v1.0/Mmap`]
  [44cfe95a] Pkg  [`~/julia/bin/../share/julia/stdlib/v1.0/Pkg`]
  [de0858da] Printf  [`~/julia/bin/../share/julia/stdlib/v1.0/Printf`]
  [3fa0cd96] REPL  [`~/julia/bin/../share/julia/stdlib/v1.0/REPL`]
  [9a3f8284] Random  [`~/julia/bin/../share/julia/stdlib/v1.0/Random`]
  [ea8e919c] SHA  [`~/julia/bin/../share/julia/stdlib/v1.0/SHA`]
  [9e88b42a] Serialization  [`~/julia/bin/../share/julia/stdlib/v1.0/Serialization`]
  [1a1011a3] SharedArrays  [`~/julia/bin/../share/julia/stdlib/v1.0/SharedArrays`]
  [6462fe0b] Sockets  [`~/julia/bin/../share/julia/stdlib/v1.0/Sockets`]
  [2f01184e] SparseArrays  [`~/julia/bin/../share/julia/stdlib/v1.0/SparseArrays`]
  [10745b16] Statistics  [`~/julia/bin/../share/julia/stdlib/v1.0/Statistics`]
  [8dfed614] Test  [`~/julia/bin/../share/julia/stdlib/v1.0/Test`]
  [cf7118a7] UUIDs  [`~/julia/bin/../share/julia/stdlib/v1.0/UUIDs`]
  [4ec0a83e] Unicode  [`~/julia/bin/../share/julia/stdlib/v1.0/Unicode`]
ERROR: LoadError: LoadError: UndefVarError: endof not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include at ./sysimg.jl:29 [inlined]
 [6] include(::String) at /home/travis/.julia/packages/AxisArrays/uZ7JS/src/AxisArrays.jl:3
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/travis/.julia/packages/AxisArrays/uZ7JS/src/core.jl:59
in expression starting at /home/travis/.julia/packages/AxisArrays/uZ7JS/src/AxisArrays.jl:18
```
</details>

**Comment by randy3k** [comment]
I finally have decided to put an upper bound on julia 1.0. Will release later when AxisArrays.jl becomes 1.0 ready.

BTW, JuliaCIBot has been pending for 5-6 hours. Is it normal?

**Comment by andreasnoack** [comment]
At JuliaCon, there were some AxisArrays discussions. I think people might consider deprecating it but we should ask @mbauman and @iamed2 what the current thinking is.

**Comment by iamed2** [comment]
@mbauman was working on it before he left, I'm not sure where he left off. We want to release it in the current version as 1.0-compatible, then replace it eventually with a modern design. I was working on the latter but at this point I'd like to upgrading the current package quickly, but I don't know how much Matt got done and I haven't heard from him since he left.

**Pull request merged**
