### PR TITLE
Pull request/f1efb605 jmor

### PR DESCRIPTION
**Pull request by valerdi**

### CODE REVIEW

**Comment by tkelman** [comment]
Hi @valerdi. Your package looks completely empty at this point. Maybe develop it further before registering?

When this is further along, also do take a look at http://docs.julialang.org/en/release-0.5/manual/packages/#guidelines-for-naming-a-package.

**Comment by valerdi** [comment]
Hi @tkelman, I'm new in github and julia package development, I updated the main source of the package but how do i update this pull request? thanks

**Comment by tkelman** [comment]
You'd need to update the git tag then update the sha1 file contents in this branch of your metadata fork. It would probably be easer if you used https://github.com/attobot/attobot though.

You'll need to declare your package dependencies in your REQUIRE file. It's also recommended to write some tests and documentation for your package, and enable a continuous integration testing service like Travis CI. A more descriptive package name would be encouraged. By MOR do you mean model order reduction?

**Comment by valerdi** [comment]
yes, i mean model order reduction. Well, with all that you said, it'll take a while but i'll try

**Comment by aviks** [comment]
Closing this. @valerdi Please ask on discourse if you are uncertain about how to register packages.

**Pull request closed without merging**
