### PR TITLE
Update tikzpictures to 0.2.0

### PR DESCRIPTION
**Pull request by mykelk**

### CODE REVIEW

**Comment by IainNZ** [comment]
Please don't merge PRs like this with 20 merge commit and two actual commits.

**Comment by mykelk** [comment]
Not sure where all the merges came from, but the Pkg.tag("TikzPictures") and Pkg.publish() failed a number of times before it went through.

**Comment by IainNZ** [comment]
You tagged v0.0.2 in August by the looks of it, and then ran Pkg.update 20 times between now and when you just tagged v0.2.0

**Comment by johnmyleswhite** [comment]
We should maybe revert these changes.

**Comment by mykelk** [comment]
@johnmyleswhite That's fine with me. But we still want TikzPictures to go to v0.2.0. What is the cleanest way to do this?

**Comment by johnmyleswhite** [comment]
If it's not too late, we need to do a proper revert. One thing we need is to stop having new commits going in from other packages. So let's hold off on anything else you've been working on. After that, it's probably easiest to do the revert for you.

**Comment by mykelk** [comment]
It's not too late. I made the PGFPlots.jl tag after this one, but Pkg.publish() went through without all those merges. You can go ahead with the revert. Sorry for messing this one up.

**Comment by johnmyleswhite** [comment]
Looks like Iain (or someone else) may have fixed this already.

Don't worry about the problems with this one. I'd just try to keep in mind that you need to read through exactly what changes are being made before hitting the merge button.

**Pull request merged**
