### PR TITLE
Tag Gaston v0.5.6 [https://github.com/mbaz/Gaston.jl]

### PR DESCRIPTION
**Pull request by mbaz**

### CODE REVIEW

**Comment by tkelman** [comment]
Would it be possible to enable Travis CI here?

**Comment by mbaz** [comment]
@tkelman I haven't enabled it because my tests require gnuplot to be installed, and I assume travis does not support that use case. However, let me look into it and try to find a way to make it work.

**Comment by tkelman** [comment]
try
```
addons:
  apt:
    packages:
    - gnuplot
```
for linux

**Comment by mbaz** [comment]
@tkelman Thanks for the tip. I'm testing things out now.

**Comment by mbaz** [comment]
@tkelman OK, Travis seems to be working. I'll tag a new release and do another pull request.

**Pull request closed without merging**
