### PR TITLE
Register Extern: v0.0.1

### PR DESCRIPTION
**Pull request by ararslan**
I made a thing and I think it works, maybe other people will use it. 🎷🐴

### CODE REVIEW

**Comment by ararslan** [comment]
Closed by #5567. 🔐

**Comment by tkelman** [comment]
Looks like you don't have Travis CI enabled? Otherwise this looks fine, though note it has a lot in common with Requires.jl - particularly that it will interact poorly with precompilation, if the state of which packages are present changes between precompilation and usage.

**Comment by ararslan** [comment]
Not sure what you mean about Travis... I have the badge on the repo and things look okay [here](https://travis-ci.org/ararslan/Extern.jl).

I wasn't aware of Requires! It appears to serve precisely the same purpose. I had thought about the issue you mentioned but wasn't sure how to get around it. Should I just ditch this then?

**Comment by tkelman** [comment]
Whoops, was looking at the branch status page and didn't realize that you had done [ci skip] on your most recent commit, that's why it looked like it wasn't enabled.

Your package is a bit safer and doesn't do the same hacking of internals, so it's less bad than Requires. No harm registering this, but if anyone wants to start using it they should be aware of the precompilation issue. Something like an `extern` keyword (that would properly tie into the precompilation machinery) is planned, so maybe your package can be a proving ground for how to go about it.

**Pull request merged**
