### PR TITLE
Tag Clipper.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGeometry/Clipper.jl](https://github.com/JuliaGeometry/Clipper.jl)
Release: [v0.4.0](https://github.com/JuliaGeometry/Clipper.jl/releases/tag/v0.4.0)
Diff: [vs v0.3.0](https://github.com/JuliaGeometry/Clipper.jl/compare/f02c3beec3b009fc84738ddd992d59d91340d1f6...71aa1b61c52a9d05c763266b6d23f81753060b14)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -1,2 +1,2 @@
-@windows WinRPM
-julia 0.5
+julia 0.6
+BinaryProvider
```
cc: @SimonDanisch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Did the JuliaCIBot just leave?! :D

**Comment by andreasnoack** [comment]
Let's try again

**Comment by andreasnoack** [comment]
@nkottary Any idea what is going on for CIBot?

@SimonDanisch Please adjust the path to the Travis badge in the README.

**Comment by SimonDanisch** [comment]
updated the badges! :)

**Comment by nkottary** [comment]
I see this error: 

```
ERROR: while scanning a simple key at line 17, column 0: could not find expected ':' at line 18, column 0
 in stale_possible_simple_keys(::YAML.TokenStream) at /home/jrun/.julia/v0.5/YAML/src/scanner.jl:268
 in need_more_tokens(::YAML.TokenStream) at /home/jrun/.julia/v0.5/YAML/src/scanner.jl:149
 in peek(::YAML.TokenStream) at /home/jrun/.julia/v0.5/YAML/src/scanner.jl:155
 in parse_block_mapping_key(::YAML.EventStream) at /home/jrun/.julia/v0.5/YAML/src/parser.jl:402
 in peek(::YAML.EventStream) at /home/jrun/.julia/v0.5/YAML/src/parser.jl:54
 in compose_mapping_node(::YAML.Composer, ::Void) at /home/jrun/.julia/v0.5/YAML/src/composer.jl:152
 in compose_node(::YAML.Composer, ::Void, ::Void) at /home/jrun/.julia/v0.5/YAML/src/composer.jl:86
 in compose_document(::YAML.Composer) at /home/jrun/.julia/v0.5/YAML/src/composer.jl:50
 in compose(::YAML.EventStream) at /home/jrun/.julia/v0.5/YAML/src/composer.jl:38
 in load(::YAML.TokenStream, ::Void) at /home/jrun/.julia/v0.5/YAML/src/YAML.jl:20
 in open(::JuliaRunCI.##39#43, ::String) at ./iostream.jl:113
 in run_test_commands(::Array{Base.AbstractCmd,1}, ::String, ::Tuple{Pair{String,String},Pair{String,String},Pair{String,String},Pair{String,String}}, ::JuliaRunCI.CloneRevDepEnv, ::String, ::SubString{String}, ::String) at /mnt/juliarun/JuliaRunCI/src/ci.jl:56
 in #run_revdep_ci#51(::Bool, ::Function, ::JuliaRunCI.CIEnv, ::GitHub.OAuth2, ::JuliaRun.KuberClusters.KuberCluster, ::JuliaRunCI.CloneRevDepEnv) at /mnt/juliarun/JuliaRunCI/src/ci.jl:410
 in run_revdep_ci(::JuliaRunCI.CIEnv, ::GitHub.OAuth2, ::JuliaRun.KuberClusters.KuberCluster, ::JuliaRunCI.CloneRevDepEnv) at /mnt/juliarun/JuliaRunCI/src/ci.jl:365
 in run_ci() at /mnt/juliarun/JuliaRunCI/src/ci.jl:302
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321```

**Comment by nkottary** [comment]
YAML.jl was unable to parse the `.travis.yaml` for this package.

**Pull request merged**
