### PR TITLE
Register new package Transpiler.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [SimonDanisch/Transpiler.jl](https://github.com/SimonDanisch/Transpiler.jl)
Release: [v0.0.1](https://github.com/SimonDanisch/Transpiler.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/SimonDanisch/Transpiler.jl/builds/215708403)
cc: @SimonDanisch

### CODE REVIEW

**Comment by tkelman** [comment]
requires #8520 and #8521 first, not appropriate to be cloning master as in https://github.com/SimonDanisch/Transpiler.jl/pull/1/commits/e7b5bc3a7ea65919a18c7b5a181c9ba7d1780dd9

**Comment by tkelman** [comment]
tests aren't actually running here, and the test-only dependencies aren't listed in `test/REQUIRE`

**Comment by SimonDanisch** [comment]
>the test-only dependencies

Which ones are those?

**Comment by tkelman** [comment]
https://github.com/SimonDanisch/Transpiler.jl/blob/master/test/opengl_funcs.jl uses several packages (FileIO, ModernGL, Reactive, GLFW, GLAbstraction, Colors) but isn't currently run. I must've opened an older copy of runtests.jl that still had the autogenerated `@test 1 == 2`, wasn't clear if the other test files were going to be included. If `opengl_funcs.jl` isn't for now then you're fine.

**Comment by ararslan** [comment]
As a heads up, you have several 0.6 depwarns in this tag.

**Comment by SimonDanisch** [comment]
I know... Priorization under limited time -.-

**Comment by tkelman** [comment]
need to retag without the checkout code in the tests, and preserve license attribution for copied code

**Comment by ararslan** [comment]
Prepare to be transpiled

**Pull request merged**
