### PR TITLE
Register new package MultiResolutionIterators.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [oxinabox/MultiResolutionIterators.jl](https://github.com/oxinabox/MultiResolutionIterators.jl)
Release: [v0.4.0](https://github.com/oxinabox/MultiResolutionIterators.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/oxinabox/MultiResolutionIterators.jl/builds/389070368)
cc: @oxinabox

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@oxinabox This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by oxinabox** [comment]
(I thought I registered this ages ago. The fact that I didn't would explain why my other things are not building)

**Comment by oxinabox** [comment]
This error does not seem to be on me:

```
fatal: error thrown and no exception handler available.
InitError(mod=:LibGit2, error=ErrorException("could not load library "libgit2"
libssl.so.10: cannot open shared object file: No such file or directory"))
```


https://travis-ci.org/JuliaLang/METADATA.jl/builds/389070386#L506

**Comment by andreasnoack** [comment]
Could you please try to remove and reapply the tag?

**Comment by oxinabox** [comment]
Thanks

**Pull request merged**
