### PR TITLE
Tag PlotThemes.jl v0.1.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPlots/PlotThemes.jl](https://github.com/JuliaPlots/PlotThemes.jl)
Release: [v0.1.2](https://github.com/JuliaPlots/PlotThemes.jl/releases/tag/v0.1.2)
Diff: [vs v0.1.1](https://github.com/JuliaPlots/PlotThemes.jl/compare/953b2a27121594febd532c624c70d577a80de1c7...d7c274324365861becccd10c991d6bc9f15f100e)
`requires` vs v0.1.1: no changes
cc: @mkborregaard

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like this is relying on a method that doesn't exist prior to PlotUtils 0.4

**Comment by mkborregaard** [comment]
That's right - they belong together. Do I need to put a minimum version tag on PlotUtils?

**Comment by tkelman** [comment]
yes, if there's no way for this version of PlotThemes to work at all with any earlier versions of PlotUtils

**Comment by mkborregaard** [comment]
OK.

**Comment by mkborregaard** [comment]
Hold on a second, I will up minor version numbers throughout.

**Comment by tkelman** [comment]
which of these should be closed then?

**Comment by mkborregaard** [comment]
The current versions are PlotThemes 0.1.3, PlotUtils 0.4.1 and Plots 0.11.1. Anything before that should be closed. Do you prefer me to do it?

**Comment by tkelman** [comment]
One of the downsides of attobot is I don't think submitters can directly close their own generated PR's.

**Pull request closed without merging**
