### PR TITLE
Tag Equations v0.2.0

### PR DESCRIPTION
**Pull request by jhlq**
Updated for 0.4

### CODE REVIEW

**Comment by tkelman** [comment]
see https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/README.md, you need to add a REQUIRE file indicating the minimum version of julia supported by the package

**Comment by jhlq** [comment]
Done, do I tag a patch and republish or is there a smoother way?

**Comment by jhlq** [comment]
Instinctively feel like updating the hash in the metadata clone, however the document you linked does say we "are strongly discouraged from editing METADATA.jl directly"

**Comment by tkelman** [comment]
you can modify your fork to get changes into this pr. you can manually create the lower case `requires` file here which Pkg.tag would normally copy.

**Comment by jhlq** [comment]
Added for the most recent version, should there be for the previous ones as well?

**Comment by jhlq** [comment]
Sorry about the messy PR and wasting your time, should have looked properly at the format of other packages... Maybe a prompt for the REQUIRE file at Pkg.tag could be beneficial. Also since this gets mailed to all watchers: Love you all!

**Comment by tkelman** [comment]
We automatically  populate the REQUIRE in recent Pkg.generate. Thanks for fixing.

**Pull request merged**
