### PR TITLE
Register new package StringManipulations.jl v0.0.1

### PR DESCRIPTION
**Pull request by djsegal**
Repository: [djsegal/StringManipulations.jl](https://github.com/djsegal/StringManipulations.jl)
Release: [v0.0.1](https://github.com/djsegal/StringManipulations.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/djsegal/StringManipulations.jl)
cc: @djsegal

-----

Replacement for:
+ [Case.jl](https://github.com/JuliaLang/METADATA.jl/pull/12138)
+ [Underscore.jl](https://github.com/JuliaLang/METADATA.jl/pull/12158)

### CODE REVIEW

**Comment by djsegal** [comment]
@aviks, I'm getting the following error from JuliaCIBot. Is it something broken with my code?

```xml
This XML file does not appear to have any style information associated with it. 
The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
d798aed7799e48989270c48b15443952eb02c233/StringManipulations_julia_0_6.log
</Key>
<RequestId>2503553C33707E0F</RequestId>
<HostId>
4toLhpG0CjvFY2QiLYc1ReW5A3iZQvpNtbaYUZaq5mlq7TkfqPeNOb5uEozxcufiiFx3ztFc4CA=
</HostId>
</Error>
```

**Comment by ararslan** [comment]
"String manipulations" seems far too broad a term for the scope of this package.

**Comment by KristofferC** [comment]
The naming of this package is way too broad for what the package provides. Base defines a lot of String manipulation functions and this doesn't extend that, it only add functions that are specialized on certain values (`-`, `_``) , i.e. the generalization of these functions gives you back `replace`.

**Comment by djsegal** [comment]
@ararslan, ok. i'll try to brainstorm some names that are larger in scope than `case`, but smaller in scope than `string manipulations`

-----

@KristofferC, no this is not going into Fake.jl. This has utility outside of generating fake data.

one area i think it has a lot of usefulness is in making websites (where css, js, and julia have different naming conventions). why do you think transforming strings has such a narrow scope?

**Comment by ararslan** [comment]
> i'll try to brainstorm some names that are larger in scope than case, but smaller in scope than string manipulations

Isn't the scope of this package exactly changing between cases?

**Comment by djsegal** [comment]
@ararslan, maybe?

To me, 

+ Case kind of implies simple replace calls
+ `underscore`, `dasherize`, etc are more compiler oriented with a lexer and parser step?

// see: https://en.wiktionary.org/wiki/lower_case

**Comment by djsegal** [comment]
closed in favor of: 

+ https://github.com/JuliaLang/METADATA.jl/pull/12253

**Pull request closed without merging**
