### PR TITLE
Tag NLOptControl.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMPC/NLOptControl.jl](https://github.com/JuliaMPC/NLOptControl.jl)
Release: [v0.2.1](https://github.com/JuliaMPC/NLOptControl.jl/releases/tag/v0.2.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMPC/NLOptControl.jl/builds/455782003)
Diff: [vs v0.1.6](https://github.com/JuliaMPC/NLOptControl.jl/compare/0269a566dc7b4c0e108dbb185d061a3ca99fea0d...24fb4f29ffa7ea6a31812d232db9e0be7582384d)
`requires` vs v0.1.6: 
```diff
--- 0.1.6/requires
+++ 0.2.1/requires
@@ -1,11 +1,15 @@
-julia 0.6
-FastGaussQuadrature
-JuMP
+julia 0.6-
+FastGaussQuadrature 0.3.2
+JuMP 0.18.4
 DataFrames 0.11
-Ipopt
-KNITRO
-Interpolations
-MathProgBase
+Ipopt 0.4.3
+KNITRO 0.4
+Interpolations 0.8.0
+MathProgBase 0.7.7
 CSV 0.2.4
-OrdinaryDiffEq
-DiffEqBase
+OrdinaryDiffEq 3.21.0
+DiffEqBase 3.13.3
+Colors 0.8.2
+Plots 17.4
+GR 0.35
+Hiccup 0.1.1
```
cc: @huckl3b3rry87

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by huckl3b3rry87** [comment]
I am sorry, delete this one as well. I will make sure it is good next time.

Thanks

**Comment by andreasnoack** [comment]
Please just update the existing PRs instead of making new ones.

**Comment by huckl3b3rry87** [comment]
@andreasnoack OK, I will do that next time. Also, not sure how to go about this, but can you please delete two of my packages? VehicleModels.jl and PrettyPlots.jl from the metadata? They are now in other packages. Or is there another way that I should go about that?

Thank you

**Comment by andreasnoack** [comment]
You can prepare a PR to METADATA that upper bounds the Julia versions in REQUIRE such that the packages become uninstallable.

**Comment by huckl3b3rry87** [comment]
OK, thank you!

**Comment by huckl3b3rry87** [comment]
like require
```
julia 200
```
?

**Comment by andreasnoack** [comment]
No by setting an upper bound sufficiently low.

**Comment by huckl3b3rry87** [comment]
Ah, OK. I got it, so someone can still use it if they have an old version? I was hoping that it could actually be deleted to avoid confusion

**Comment by andreasnoack** [comment]
You can set it so low that nobody can install it. E.g. the interval `0.5 0.5` is empty because the right end point is excluded.

**Comment by huckl3b3rry87** [comment]
Thank you for explaining that to me:)

**Comment by huckl3b3rry87** [comment]
> Please just update the existing PRs instead of making new ones.

I am trying to do this for this PR
https://github.com/JuliaLang/METADATA.jl/pull/19563
but I am not sure how to do it since the PR was made automatically from an attobot branch not mine. Is there any documentation on this? A [google search](https://www.google.com/search?ei=fPXuW8TtFpGgjwT8voiAAQ&q=update+an+existing+PR+with+auttobot&oq=update+an+existing+PR+with+auttobot&gs_l=psy-ab.3..35i304i39.2402.2402..2693...0.0..0.75.75.1......0....1..gws-wiz.......0i71.U1gWJLLkPfQ) did not yield anything for me

**Pull request closed without merging**
