### PR TITLE
RudeOil, a crude attempt a playing with Julia and Docker

### PR DESCRIPTION
**Pull request by mdavezac**

### CODE REVIEW

**Comment by jiahao** [comment]
How much overlap is there with https://github.com/Keno/Docker.jl?

@Keno

**Comment by mdavezac** [comment]
Frankly, I'm not sure. There is no documentation, no test, no usage example in Keno/Docker.jl yet. So I'm not sure which way end to grab it from. That's why RudeOil exists.

**Comment by Keno** [comment]
Docker.jl is currently unmaintained, as I do not currently have a use case that would require Docker any more. I'm happy to give up the name if you actually have a use case and want to maintain the package.

**Comment by tkelman** [comment]
FWIW I think RudeOil is a clever, funny, awesome package name. Maybe not the most discoverable name in the world, but at least Docker's in the sub-description.

**Comment by ViralBShah** [comment]
It's a funny name - but if this is going to be a maintained package, it does make sense to call it Docker.jl.

**Comment by mdavezac** [comment]
For what it's worth, I would rather keep the name. Julia seems to have a tradition of names that are not quite on topic, e.g. Julia itself, then Winston, Gadfly...

**Comment by IainNZ** [comment]
@mdavezac we do have a naming guide in the docs, that prefers literal names if possible. Something like plotting as no one right way to do it, hence the galaxy of names... would have been good to re-purpose the Docker.jl name for something useful, but oh well.

**Comment by milktrader** [comment]
+1 for clever names

**Pull request merged**
