### PR TITLE
Register new package ArrayACAutomatons.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [hack1nt0/ArrayACAutomatons.jl](https://github.com/hack1nt0/ArrayACAutomatons.jl)
Release: [v0.1.0](https://github.com/hack1nt0/ArrayACAutomatons.jl/releases/tag/v0.1.0)
cc: @hack1nt0

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@hack1nt0 This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use abbreviations in package names.

**Comment by hack1nt0** [comment]
Hi @dpsanders , need I change the package name, and how? `AC` abbreviates Aho–Corasick, two author names of the algorithm. I thought it too verbose, and `AC自动机`, i.e., `AC Automaton` is so common in my language.

**Comment by andreasnoack** [comment]
I also think something like `AhoCorasickAutomaton` would be better. If you decide to change the name,  then you just make the change in the repo and then delete this release and make it again. In any case, please let us know what you decide.

**Comment by hack1nt0** [comment]
Ok, I decide to change the name to `AhoCorasickAutomaton`. Despite the prefix `Array` makes a lot of sense, I will put this implementation detail to the doc.

**Comment by hack1nt0** [comment]
Please delete this PR, I had done a new PR named `AhoCorasickAutomatons`, and had removed this repo accidentally.

**Pull request closed without merging**
