### PR TITLE
Tag VoronoiDelaunay v0.0.4 [https://github.com/JuliaGeometry/VoronoiD…

### PR DESCRIPTION
**Pull request by robertdj**
…elaunay.jl]

### CODE REVIEW

**Comment by robertdj** [comment]
From Travis:
> Use a new minor package version when support for an old version of Julia is dropped. Re-tag the package as 0.1.0 using `Pkg.tag("VoronoiDelaunay", :minor)`

Is it okay to edit the tag directly on GH from v0.0.4 to v0.1.0 ?

**Comment by tkelman** [comment]
sure

**Comment by robertdj** [comment]
Great. It's changed in the [VD repo](https://github.com/JuliaGeometry/VoronoiDelaunay.jl/releases). But I can't see a way to change the [filenames in this PR](https://github.com/JuliaLang/METADATA.jl/pull/6828/files).
Should I `PkgDev.publish()` again?

**Comment by tkelman** [comment]
you can rename the files but that usually requires going via the command line

**Comment by robertdj** [comment]
I don't mind the command line; I would just like to finish this up :-) 
It seems to me that the thing missing is to let METADATA know that this PR is for v0.1.0 instead of v0.0.4. Is there an easy way about this?

**Comment by tkelman** [comment]
the two files that are under 0.0.4, move them under a 0.1.0 folder instead

**Comment by robertdj** [comment]
I'm not sure what to do after moving the files under 0.0.4. Adding those would give me a new commit, right?
Isn't it just as easy with

```
PkgDev.tag("VoronoiDelaunay",` :minor)
PkgDev.publish()
```

and then close this PR?

**Comment by tkelman** [comment]
that would probably work

**Comment by robertdj** [comment]
I'm running into all kinds of Git problems that I would rather not spend time on. 
Would it mess things up with this commit if I delete <https://github.com/robertdj/METADATA.jl> and fork the official METADATA again? I think that makes it easier for me to push a new v0.1.0 commit.

**Comment by tkelman** [comment]
we'd have to close this pr but otherwise I don't think that would break anything

**Comment by robertdj** [comment]
Cool. I'll get on with the tagging, then.

**Comment by tkelman** [comment]
replaced by https://github.com/JuliaLang/METADATA.jl/pull/6891

**Pull request closed without merging**
