### PR TITLE
Tag IPNets.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaWeb/IPNets.jl](https://github.com/JuliaWeb/IPNets.jl)
Release: [v0.4.0](https://github.com/JuliaWeb/IPNets.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaWeb/IPNets.jl/builds/258951537)
Diff: [vs v0.3.0](https://github.com/JuliaWeb/IPNets.jl/compare/88966d5609593df77c2ec055e9679d0209e98aad...de9785a21d50a6814259bf2f394166d0debf99ad)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -1 +1 @@
-julia 0.5
+julia 0.6
```
cc: @sbromberger

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by sbromberger** [comment]
Looks like JuliaCIBot is stuck somewhere.

**Comment by sbromberger** [comment]
What's going on with this?

**Comment by tkelman** [comment]
One of the reverse-dependency tests seems to be freezing.

**Comment by sbromberger** [comment]
Thanks!

**Pull request merged**
