### PR TITLE
Tag IntervalTrees.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BioJulia/IntervalTrees.jl](https://github.com/BioJulia/IntervalTrees.jl)
Release: [v0.3.0](https://github.com/BioJulia/IntervalTrees.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/BioJulia/IntervalTrees.jl/builds/246303187)
Diff: [vs v0.2.1](https://github.com/BioJulia/IntervalTrees.jl/compare/ddaa8cd512e5eed969d3e7c467aa42f1de403011...9bcb231b70bd961839c773f8fcdfc9213f020b4b)
`requires` vs v0.2.1: no changes
cc: @bicycle1885

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like this may have caused a failure in GenomicFeatures? https://github.com/JuliaCI/pkg.julialang.org/blob/e2a1041bc079390ee9bda36122a00afaa316fac5/logs/GenomicFeatures_0.5.log

cc @Ward9250

**Comment by bicycle1885** [comment]
Possibly. But I think it is already fixed by https://github.com/BioJulia/GenomicFeatures.jl/pull/3.

**Comment by tkelman** [comment]
Most users will be on releases of packages, that hasn't been tagged yet.

**Comment by bicycle1885** [comment]
I'm tagging a new release.

**Comment by bicycle1885** [comment]
Here it is: https://github.com/JuliaLang/METADATA.jl/pull/9964.

**Pull request merged**
