### PR TITLE
Register new package GraphRecipes.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPlots/GraphRecipes.jl](https://github.com/JuliaPlots/GraphRecipes.jl)
Release: [v0.4.0](https://github.com/JuliaPlots/GraphRecipes.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPlots/GraphRecipes.jl/builds/462468902)
cc: @mkborregaard

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@mkborregaard This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by mkborregaard** [comment]
This is a rename of the existing package PlotRecipes.jl which has been refactored to only focus on graph-related recipes. PlotRecipes.jl has never worked on 1.0 so the name change should be relatively painless.

**Comment by diegozea** [comment]
JuliaCIBot shows the following error:
```
ERROR: LoadError: ArgumentError: Package GraphRecipes [158f301c-6656-5673-b341-1dd6f9668561] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```
Do you have any hint about how can that be solved?

**Comment by mkborregaard** [comment]
Does it need a modern project.toml and manifest.toml file? I'll add those and update the release.

**Comment by mkborregaard** [comment]
No it was just that I'd forgotten to rename the src/PlotRecipes.jl file :flushed:

**Pull request merged**
