### PR TITLE
Tag ColorBrewer v0.3.1 [https://github.com/timothyrenner/ColorBrewer.jl]

### PR DESCRIPTION
**Pull request by timothyrenner**
Diff vs v0.3.0: https://github.com/timothyrenner/ColorBrewer.jl/compare/519d0fd18068e2cd24c952696501580e54ce7be7...220b57b558b1086da747e5b8cd1c5b7c628b365a

Patch for finding resource file in non-standard package configurations.

### CODE REVIEW

**Comment by tkelman** [comment]
If you enabled Travis CI, would your tests pass?

**Comment by timothyrenner** [comment]
@tkelman There's a `.travis.yml` file in the package and it looks like the above tests did pass - was there something additional I need to enable?

**Comment by tkelman** [comment]
the travis tests here are for consistency of your tag, they don't run your package's tests or do anything about master of your package (only releases you choose to tag)

see https://travis-ci.org/timothyrenner/ColorBrewer.jl

**Comment by timothyrenner** [comment]
Tests are good: https://travis-ci.org/timothyrenner/ColorBrewer.jl

Appreciate the assist setting this up.

**Pull request merged**
