### PR TITLE
Register new package Matcha.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [SimonDanisch/Matcha.jl](https://github.com/SimonDanisch/Matcha.jl)
Release: [v0.0.1](https://github.com/SimonDanisch/Matcha.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/SimonDanisch/Matcha.jl/builds/215703541)
cc: @SimonDanisch

### CODE REVIEW

**Comment by SimonDanisch** [comment]
This should be ready to go now!

**Comment by tkelman** [comment]
Should have some minimal documentation.

**Comment by SimonDanisch** [comment]
Done: https://github.com/SimonDanisch/Matcha.jl/blob/master/README.md

**Comment by SimonDanisch** [comment]
bump

**Comment by tkelman** [comment]
new package registrations stay open at least 24 hours for initial feedback

**Comment by SimonDanisch** [comment]
Thanks a lot!

**Comment by tkelman** [comment]
occurs to me that this is a bit unfortunately closely named to kmsquire/Match.jl

**Comment by SimonDanisch** [comment]
That's actually a reason for the name, since it's very similar, but sounds and meaning are completely different! It was kinda hard to come up with a name, that isn't taken but still represents the purpose in an at least slightly meaningful way!

**Pull request merged**
