### PR TITLE
Tag RCall.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaInterop/RCall.jl](https://github.com/JuliaInterop/RCall.jl)
Release: [v0.8.0](https://github.com/JuliaInterop/RCall.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaInterop/RCall.jl/builds/297300277)
Diff: [vs v0.7.5](https://github.com/JuliaInterop/RCall.jl/compare/9c795a58219aa653709643f46e5cfe311fd6419f...5bc3e4e115f4aa0872bd8818163cf1afa1adcb85)
`requires` vs v0.7.5: 
```diff
--- 0.7.5/requires
+++ 0.8.0/requires
@@ -1,9 +1,11 @@
-julia 0.5
+julia 0.6
+Nulls 0.1.0
 DataStructures 0.5.0
-DataFrames 0.9
+DataFrames 0.10
+DataArrays 0.5.0
+CategoricalArrays 0.1.0
 NullableArrays 0.1.0
-CategoricalArrays 0.1.0
 AxisArrays 0.0.6
 NamedArrays 0.5.3
-Compat 0.17.0
+Compat 0.34.0
 @windows WinReg 0.2.0
```
cc: @randy3k

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
Is this good to go now=

**Comment by randy3k** [comment]
Yes, it is. Thanks.

**Comment by KristofferC** [comment]
The JuiaCIBot errors about too old R version, means that R on the JuliaCIBot-nodes should be upgraded?

**Comment by randy3k** [comment]
it seems to be the reason of failure.

**Comment by KristofferC** [comment]
CC @aviks about upgrading R on the JuliaCIBot nodes.

**Pull request merged**
