### PR TITLE
Tag WinReg v0.1.1

### PR DESCRIPTION
**Pull request by simonbyrne**
Updated for 0.5

### CODE REVIEW

**Comment by tkelman** [comment]
and push this commit to master, it only exists as the tag https://github.com/simonbyrne/WinReg.jl/commit/674ffea0978ab8e694941ed0e5dbb0affae58142

**Comment by simonbyrne** [comment]
Ah, I didn't realise I'd tagged a version on a branch: unfortunately that's already been squashed into master. I'll tag a new release on master (with the above fix).

**Comment by tkelman** [comment]
could you do a merge commit so the tagged commit here is in the commit history of master?

**Comment by simonbyrne** [comment]
Done.

**Pull request merged**
