### PR TITLE
Tag Signals.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [TsurHerman/Signals.jl](https://github.com/TsurHerman/Signals.jl)
Release: [v1.0.0](https://github.com/TsurHerman/Signals.jl/releases/tag/v1.0.0)
Travis: [Travis Build Status](https://travis-ci.org/TsurHerman/Signals.jl/builds/420598246)
Diff: [vs v0.2.2](https://github.com/TsurHerman/Signals.jl/compare/3849d7f84d475dc92fc85db22e73655f2e6cad27...8f9824e16365cb0f890b327570c1b29bd3f6e0ab)
`requires` vs v0.2.2: 
```diff
--- 0.2.2/requires
+++ 1.0.0/requires
@@ -1 +1,4 @@
-julia 0.6
+julia 1.0
+DataStructures
+Compat
+Distributed
```
cc: @TsurHerman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by quinnj** [comment]
Made several comments on the commit for 1.0 support; in particular, need to resolve the broken Project.toml in order to get travis tests passing. Please respond back here once those issues are sorted out.

**Comment by TsurHerman** [comment]
I am struggling with understanding what needs to be in the project.toml 
Isn’t REQUIRE sufficient ?

**Comment by andreasnoack** [comment]
For now, I'd recommend that you don't include project and manifest files in your package since they are not yet required.

**Comment by andreasnoack** [comment]
Please also don't include stdlibs in your require file (Distributed).

**Comment by TsurHerman** [comment]
I fixed it according to @quinnj remarks. I accidentally re-submitted the package this time in 
versio 1.0.1 , so this PR(merging of 1.0.0) can be removed

**Pull request closed without merging**
