### PR TITLE
Tag ImageCore.jl v0.1.2 [https://github.com/JuliaImages/ImageCore.jl/…

### PR DESCRIPTION
**Pull request by tkelman**
…releases/tag/v0.1.2]

plus some version bounds on ~~FixedPointNumbers for~~ very early versions of Color.jl and Gadfly, which helps with the resolution issues seen in (closes #7947), at least locally for me on julia 0.6-dev. Let's see what it does on other Julia versions. cc @timholy

### CODE REVIEW

**Comment by tkelman** [comment]
Had to push some tags to Color.jl (I thought I fixed the travis check to only be picky about git tags if you're adding new sha1 files, but apparently it didn't work correctly), but looks like I fixed 0.6-dev compared to #7947. Now will see how to fix Mads on 0.5.

**Comment by tkelman** [comment]
By faking VERSION, I've learned that JuliaLang/julia#20319 fixes the remaining issue. I will see if that's backportable, but in the meantime I'll also want to see what bounds tweaks I could make the get things happy without needing to modify JULIA_PKGRESOLVE_ACCURACY.

**Comment by tkelman** [comment]
Well that felt a lot like shuffling around the deck chairs. Anyway, good enough for now I think.

**Comment by timholy** [comment]
Thanks a bunch, @tkelman! And of course @carlobaldassi.

**Comment by timholy** [comment]
Should say, this now gives the whole Images suite a fighting chance of getting through CI on 0.6, so it should have quite a cascade.

**Comment by tkelman** [comment]
I'm glad we isolated the odd resolver behavior and uninformative failure messages enough to improve them for 0.6 - should make future debugging of this kind of situation much easier.

**Comment by timholy** [comment]
Yes. And while you know of my skepticism about adding upper bounds (based on early attempts at doing similar things locally), as usual the right answer is not to avoid it, but to fix it. So, here's a new picture of me:
image

**Pull request merged**
