### PR TITLE
Tag TrafficAssignment.jl v0.3.1

### PR DESCRIPTION
**Pull request by chkwon**
fixed a bug

### CODE REVIEW

**Comment by tkelman** [comment]
Upper bounds aren't generally going to achieve what you want unless you apply them to all past versions, otherwise Pkg can just downgrade your package and install the last version that doesn't have an upper bound

**Comment by chkwon** [comment]
@tkelman Ah.. you are right. So what is the best way?

**Comment by tkelman** [comment]
We can modify the requires files of the older versions to add bounds as well: https://github.com/chkwon/METADATA.jl/tree/pull-request/a071afc6/TrafficAssignment/versions

**Comment by chkwon** [comment]
Thanks. Always learning new things. 

Except for the last working versions (v0.2.3 and v0.3.1), can I delete older versions?

**Comment by chkwon** [comment]
Oh it seems like I can fix easily. Never mind.

**Comment by tkelman** [comment]
> can I delete older versions?

No! Old versions need to remain in metadata for reproducibility's sake.

**Comment by chkwon** [comment]
I've updated upper bounds.

**Comment by tkelman** [comment]
Cool, that's good so far. One thing to note is that since old versions depended on Graphs but not LightGraphs, one feasible resolution would be to downgrade to the most recent version of TrafficAssignment that didn't depend on LightGraphs in order to use the latest LightGraphs. While that's valid, you probably want to avoid it?

You can add "artificial" dependencies `LightGraphs 0.0 0.8` (or maybe 0.7?) on the very early versions and it'll avoid that. Though you will probably want to fix your code to be compatible with the latest lightgraphs reasonably soon, otherwise anyone with your package installed will stay held back to non-latest lightgraphs.

**Comment by chkwon** [comment]
Great suggestion. I added artificial dependencies `LightGraphs 0.0 0.7` on very early versions.

**Comment by tkelman** [comment]
Travis is complaining about some missing tags. Easiest would be to recreate and push those, or we can figure out how to make an exception.

**Comment by tkelman** [comment]
When Julia 0.6 comes out it'll downgrade to v0.2.1, unless you put out a newer release with an upper bound higher than 0.6 by then. You've got some time.

**Comment by chkwon** [comment]
@tkelman Thanks! I'll prepare for v0.6.

**Comment by tkelman** [comment]
Bump, be aware that with your current bounds, when 0.6.0 final gets released, users of this package will get downgraded to 0.2.1 of it.

**Comment by sbromberger** [comment]
Why is LightGraphs now being required for TrafficAssignment < 0.2.0 ? It wasn't used by the package until version 0.2.0. (before that, it was Graphs.)

**Pull request merged**
