### PR TITLE
Register new package PPrint.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rbt-lang/PPrint.jl](https://github.com/rbt-lang/PPrint.jl)
Release: [v0.1.0](https://github.com/rbt-lang/PPrint.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/rbt-lang/PPrint.jl/builds/495002863)
cc: @xitology

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@xitology This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use abbreviations in package names. Can you make the name more explicit? E.g. `FixedWidthPrinting.jl` or similar.

**Comment by xitology** [comment]
`pprint` seems to be the standard name for this kind of a package. For example, both Python and Racket have `pprint` in their standard libraries ([1], [2]).

1: https://docs.python.org/3/library/pprint.html
2: https://docs.racket-lang.org/pprint/index.html

**Comment by dpsanders** [comment]
We prefer explicit package names in Julia, e.g. `PrettyPrinter.jl`

**Comment by xitology** [comment]
I will rename the package. Still:

1. For REPL usage, having a shorter name to import is a benefit.
2. Having the package name match the name of the exported function is nice.

**Comment by xitology** [comment]
No objections against `PrettyPrinting.jl`?

**Comment by dpsanders** [comment]
For REPL usage tab completion means that there is no / less problem with longer names.

`PrettyPrinting.jl` seems reasonable to me.

**Comment by xitology** [comment]
Awesome, thank you!

**Pull request closed without merging**
