### PR TITLE
Pull request/027d0ae8

### PR DESCRIPTION
**Pull request by Kelvyn88**
Minor reviews for ODEs Package

### CODE REVIEW

**Comment by jiahao** [comment]
In general, we strongly encourage new developers to contribute to an existing package rather than contribute a new package whose domain overlaps strongly with the existing one. In this case there is a fairly developed [ODE.jl](https://github.com/JuliaLang/ODE.jl) package. Why is there a need for a second one?

**Comment by jiahao** [comment]
Also, I don't think you meant to open so many pull requests.

**Comment by Kelvyn88** [comment]
Ok, I understand. Please close this pull request. I'll make a pull request to the ODE package later, oce I get the newest method. Thanks.

**Comment by jiahao** [comment]
I'm sure ODE.jl could use more attention. Thanks!

**Comment by Kelvyn88** [comment]
Thanks for your comments!

**Pull request closed without merging**
