### PR TITLE
Tag Pandas.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPy/Pandas.jl](https://github.com/JuliaPy/Pandas.jl)
Release: [v0.6.0](https://github.com/JuliaPy/Pandas.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPy/Pandas.jl/builds/275587364)
Diff: [vs v0.5.4](https://github.com/JuliaPy/Pandas.jl/compare/bd14f25236fdcfe5cf3433b69ca346297c9707fa...12dc2dcd6b4ae79b98f5a33c9a83286af332fb53)
`requires` vs v0.5.4: 
```diff
--- 0.5.4/requires
+++ 0.6.0/requires
@@ -1,5 +1,8 @@
-julia 0.5
+julia 0.6
 PyCall 1.7.2
 PyPlot 2.2.4
 Lazy 0.11.4
 Compat 0.17
+TableTraits 0.0.1
+TableTraitsUtils 0.0.1
+DataValues 0.0.1
```
cc: @malmaud

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
since https://github.com/JuliaLang/METADATA.jl/pull/11165 got merged, this should put the git tag back to what the metadata-v2 sha1 file says, but can modify the metadata requires file to fix the missing requirement

**Comment by aviks** [comment]
`ERROR: LoadError: LoadError: Do not modify existing published tag sha1 files (policy 8).
Ask for an exception if absolutely necessary, but tag commits
should be immutable once published for reproducibility.`

**Comment by malmaud** [comment]
Is there an action item for me here?

**Comment by aviks** [comment]
Did you intend to change the existing tag? Not sure what is intended here. Can't you just tag a different version?

**Comment by tkelman** [comment]
>  this should put the git tag back to what the metadata-v2 sha1 file says, but can modify the metadata requires file to fix the missing requirement

**Comment by KristofferC** [comment]
Should this be merged then @tkelman, @malmaud

**Comment by malmaud** [comment]
Oh, I see - I didn't realize the the earlier PR for for v0.6 was accepted. So I think the easiest thing is to just close this and then tag a v0.6.1.

**Comment by malmaud** [comment]
And I put back the v0.6 tag on Pandas to the SHA currently in metadata

**Comment by tkelman** [comment]
0.6.0 is still missing a requirement though. Pkg could choose to downgrade to it in order to remove DataValues. Best to add the missing dependency to 0.6.0's metadata requires file

**Comment by malmaud** [comment]
OK, but at least that can just be done as a PR to Metadata, conserving the immutabilty of SHAs already committed to METADATA.

**Pull request closed without merging**
