### PR TITLE
Tag WriteVTK v0.2.2

### PR DESCRIPTION
**Pull request by jipolanco**

### CODE REVIEW

**Comment by tkelman** [comment]
You should have a `julia 0.3` dependency here if you aren't testing on 0.2 or earlier. Will send across a PR.

**Comment by tkelman** [comment]
Also doesn't look like your git tags are getting pushed to the repository? That's technically optional but it can be nice for users browsing the package on github to easily see which commit corresponds to which release.

**Comment by jipolanco** [comment]
You mean to my own repo? I believe the tags are being pushed, as you can see [here](https://github.com/jipolanco/WriteVTK.jl/tags). It's just that I decided to delete the last tag (v0.2.2) and to re-tag it to the newest commit, where I merged your PR.

**Comment by jipolanco** [comment]
I just sent a separate PR (#3072), which includes your PR.

**Comment by tkelman** [comment]
Oh I see on the tags, nevermind, carry on.

**Pull request closed without merging**
