### PR TITLE
Register and tag 'MultipleTesting'

### PR DESCRIPTION
**Pull request by julian-gehring**

### CODE REVIEW

**Comment by tkelman** [comment]
This is referring to statistical hypothesis testing, right? Not software unit testing?

**Comment by julian-gehring** [comment]
Yes, multiple testing is an established term in the context of statistical hypothesis testing.

**Comment by tkelman** [comment]
For non-statisticians it's not a very obvious name.

**Comment by julian-gehring** [comment]
Could you elaborate what you mean with an obvious name?

**Comment by julian-gehring** [comment]
@nignatiadis

**Comment by Smaug123** [comment]
I agree that MultipleTesting is unclear to non-statisticians like me, and non-statisticians probably make up quite a lot of the Julia userbase!

**Comment by tkelman** [comment]
It looks like googling "Multiple testing" does return primarily statistics references, so maybe this is fine. I'd just get a very wrong impression of what the package is for from the name and short description alone.

**Comment by nignatiadis** [comment]
I also think the name is appropriate. The term multiple testing should be obvious not only to statisticians, but also to most scientists that work with p-values (biologists, psychologists, etc.). I am quite confident that most people looking for this functionality are going to google "multiple testing Julia". 

Would a description like "p-value adjustment and estimation of the proportion of true null hypotheses" be more informative?

**Comment by Smaug123** [comment]
That description would be completely unambiguous, I think, yes.

**Comment by julian-gehring** [comment]
@Smaug123 @nignatiadis I just changed the description to
"Statistical p-value adjustment and estimation of the proportion of true null hypotheses", thanks for the suggestion!

**Comment by diegozea** [comment]
Hi @julian-gehring! There is a package called [PValueAdjust](https://github.com/dirkschumacher/PValueAdjust.jl)  on METADATA created by @dirkschumacher. Could you explain (maybe in `README.md`) what are the differences between the two packages?

**Comment by julian-gehring** [comment]
We are aiming for a broad range of methods in the context of multiple testing in statistics. At the moment, this includes a) adjustment of p-values, b) estimating the fraction of tests under the null hypothesis, and c) FDR estimators and d) more to come. (a) is indeed related to Dirk's great package, which originally inspired our MultipleTesting package. Thanks for pointing out that it would be good to document how our package relates to others out there. It has been on my todo list, and I'll try to add this information soon.

**Comment by tbreloff** [comment]
+1 to PValueAdjustmentAndEstimationOfTheProportionOfTrueNullHypotheses.jl  It's catchy and easy to remember.  Excellent bikeshedding guys!

**Comment by tkelman** [comment]
@tbreloff your sarcasm isn't helpful. Given tab completion, there isn't really much cost to long package names anyway.

**Pull request merged**
