### PR TITLE
Register new package JWT.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [felipenoris/JWT.jl](https://github.com/felipenoris/JWT.jl)
Release: [v0.0.1](https://github.com/felipenoris/JWT.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/felipenoris/JWT.jl/builds/404484683)
cc: @felipenoris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@felipenoris This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider renaming the package to something `JSONWebTokens` cf https://docs.julialang.org/en/v0.6.2/manual/packages/#Guidelines-for-naming-a-package-1

**Comment by felipenoris** [comment]
I'll do that.

**Comment by felipenoris** [comment]
Done! How do I update this PR? (https://github.com/felipenoris/JSONWebTokens.jl)

**Comment by andreasnoack** [comment]
Sounds good. The easiest is probably to delete the release and tag and reapply it. That will open a new PR so I'll close this one.

**Pull request closed without merging**
