### PR TITLE
Tag Conda v0.2.1 [git://github.com/Luthaf/Conda.jl.git]

### PR DESCRIPTION
**Pull request by Luthaf**
See https://github.com/Luthaf/Conda.jl/issues/34 for the solved issue.

I had to submit this by hand, because `PkgDev.publish()` segfaulted for me.

### CODE REVIEW

**Comment by tkelman** [comment]
> `PkgDev.publish()` segfaulted for me.

Yikes. Thanks!

**Comment by Luthaf** [comment]
If someone is interested, I got this backtrace:

```
julia> PkgDev.publish()
WARNING: Base.ByteString is deprecated, use String instead.
[... other warnings]
INFO: Validating METADATA
INFO: Pushing Conda permanent tags: v0.2.1

signal (11): Erreur de segmentation
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f642dad1a77)
unknown function (ip: 0x7f61f6f71369)
git_remote_connect at ~/src/julia/bin/../lib/julia/libgit2.so (unknown line)
git_remote_push at ~/src/julia/bin/../lib/julia/libgit2.so (unknown line)
[inline] at ./pointer.jl:17
push at ./libgit2/remote.jl:84
unknown function (ip: 0x7f6222539666)
push at ./libgit2.jl:181
unknown function (ip: 0x7f622253869b)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:76
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1561
unknown function (ip: 0x7f62222c9e3b)
#6 at ~/.julia/v0.5/PkgDev/src/entry.jl:99
with at ./libgit2/types.jl:565
publish at ~/.julia/v0.5/PkgDev/src/entry.jl:84
publish at ~/.julia/v0.5/PkgDev/src/PkgDev.jl:55
unknown function (ip: 0x7f62222c107f)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:76
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1561
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:58
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:181
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:535
jl_toplevel_eval_in_warn at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:547
eval at ./boot.jl:230
unknown function (ip: 0x7f642434e300)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:76
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1561
[inline] at ./REPL.jl:3
eval_user_input at ./REPL.jl:62
unknown function (ip: 0x7f622265b586)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:76
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1561
[inline] at ./REPL.jl:92
#1 at ./event.jl:46
unknown function (ip: 0x7f622268b50f)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:76
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1561
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1382
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 695950028 (Pool: 695867877; Big: 82151); GC: 1767
```

**Comment by wildart** [comment]
@Luthaf what is the transport protocol in your local repo?

**Comment by wildart** [comment]
@Luthaf What is the julia version you use? Please post `versioninfo()` results.

**Comment by Luthaf** [comment]
I use a bit outdated nightly, so this might be fixed on the more recent ones.

```
julia> versioninfo()
Julia Version 0.5.0-dev+4011
Commit 89487db (2016-05-10 04:13 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

Concerning the transport protocol, using SSH (git@github.com:Luthaf/Conda.jl.git) I get an error from PkgDev.publish, and using HTTPS (https://github.com/Luthaf/Conda.jl) I get a segfault.

**Comment by wildart** [comment]
Yes, try recent master. Old versions had incorrect push parameters. See [PkgDev.jl/#35](https://github.com/JuliaLang/PkgDev.jl/issues/35).

**Pull request merged**
