### PR TITLE
Tag Lazy v0.9.0

### PR DESCRIPTION
**Pull request by one-more-minute**

### CODE REVIEW

**Comment by tkelman** [comment]
Should put `julia 0.3` in require if you aren't testing against anything earlier

**Comment by one-more-minute** [comment]
Sure, PRs are welcome.

**Comment by milktrader** [comment]
@tkelman I wonder if we could get a list of registered packages that either don't have `julia` in the REQUIRE or have dash cruft. @IainNZ probably knows how to do this.

**Comment by tkelman** [comment]
Ref #2800 and #2777 - the consensus is towards enforcing a higher standard automatically as we go on. Merging without addressing valid review is somewhat poor form.

**Pull request merged**
