### PR TITLE
Tag PairwiseListMatrices.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [diegozea/PairwiseListMatrices.jl](https://github.com/diegozea/PairwiseListMatrices.jl)
Release: [v0.5.0](https://github.com/diegozea/PairwiseListMatrices.jl/releases/tag/v0.5.0)
Diff: [vs v0.4.0](https://github.com/diegozea/PairwiseListMatrices.jl/compare/b77f0bb65628d4e818984e5e1191bb9b042ce47a...61af18aa4cc54e31ae4cd63ac9c302465dba4bf3)
`requires` vs v0.4.0: 
```diff
--- 0.4.0/requires
+++ 0.5.0/requires
@@ -1,3 +1,3 @@
 julia 0.5
-IndexedArrays
-Requires
+NamedArrays
+RecipesBase
```
cc: @diegozea

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
Conditionally loading packages depending on `Pkg.installed` is not going to interact correctly with precompilation. Should either unconditionally depend on everything you use / import, or disable precompilation, or split the conditional pieces out to separate packages.

**Comment by diegozea** [comment]
Is It OK to use `Requires.jl`?

**Comment by tkelman** [comment]
Yes, though the parts that you put under a requires macro won't typically get precompiled, it's at least a little less fragile than using Pkg.installed

**Comment by diegozea** [comment]
@tkelman It should be fixed now. Thanks!

**Pull request merged**
