### PR TITLE
Re-tag Compose and Gadfly as 0.4.0

### PR DESCRIPTION
**Pull request by timholy**
CC @tkelman. See #4051.

### CODE REVIEW

**Comment by tkelman** [comment]
You can leave the existing tags in place for 0.3.19. It's mostly important to leave the door open for a possible 0.3.20 for 0.3-specific bugfixes.

**Comment by timholy** [comment]
Is there any disadvantage to deleting those tags?

**Comment by tkelman** [comment]
I'm not sure what would happen for anyone who has already updated to them. They should be able to just update smoothly to the new tag, but I'm not positive if that'll work correctly.

**Comment by timholy** [comment]
I don't think there's going to be a problem, and it would be far less confusing to not have a 0.3.19 that requires julia 0.4 followed by a 0.3.20 that requires julia 0.3.

**Comment by tkelman** [comment]
The tag was merged a day ago so I think that's a bit beyond the window of "no one has downloaded this yet," but generally tags should be immutable. Julia 0.3 will never use the 0.3.19 tag, and Julia 0.4 will see and prefer the 0.4.x tags, so having 0.3.x tags be out of order isn't really an issue.

**Comment by timholy** [comment]
The tags are already deleted from the Compose and Gadfly repos. I imagine I can figure out how to put them back if necessary, but since the experiment was already underway:
```jl
$ JULIA_PKGDIR=/tmp/pkgs julia -q
julia> Pkg.init()
INFO: Initializing package repository /tmp/pkgs/v0.4                                                                                                                                                                                                                           
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
julia> Pkg.add("Gadfly")
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git                                                                                                                                                                                            
# lots skipped here
INFO: Installing ArrayViews v0.6.4
# skipped
INFO: Installing Compose v0.3.19
# skipped
INFO: Installing Gadfly v0.3.19
# skipped

julia> cd(Pkg.dir())

shell> cd METADATA
/tmp/pkgs/v0.4/METADATA

shell> git remote add th https://github.com/timholy/METADATA.jl.git

shell> git fetch th
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 24 (delta 5), reused 2 (delta 2), pack-reused 6
Unpacking objects: 100% (24/24), done.
From https://github.com/timholy/METADATA.jl
 * [new branch]      devel      -> th/devel
 * [new branch]      master     -> th/master
 * [new branch]      metadata-v2 -> th/metadata-v2
 * [new branch]      pull-request/0879264b -> th/pull-request/0879264b
 * [new branch]      pull-request/4178e915 -> th/pull-request/4178e915
 * [new branch]      pull-request/5b38edb5 -> th/pull-request/5b38edb5
 * [new branch]      pull-request/6a37f6d9 -> th/pull-request/6a37f6d9
 * [new branch]      pull-request/df7b2e7d -> th/pull-request/df7b2e7d
 * [new branch]      pull-request/e00d8526 -> th/pull-request/e00d8526
 * [new branch]      pull-request/e72a9f05 -> th/pull-request/e72a9f05

shell> git merge th/pull-request/0879264b
Updating ac291dc..0879264
Fast-forward
 Compose/versions/{0.3.19 => 0.4.0}/requires | 0
 Compose/versions/{0.3.19 => 0.4.0}/sha1     | 0
 Gadfly/versions/{0.3.19 => 0.4.0}/requires  | 0
 Gadfly/versions/{0.3.19 => 0.4.0}/sha1      | 0
 Immerse/versions/0.0.9/requires             | 2 +-
 5 files changed, 1 insertion(+), 1 deletion(-)
 rename Compose/versions/{0.3.19 => 0.4.0}/requires (100%)
 rename Compose/versions/{0.3.19 => 0.4.0}/sha1 (100%)
 rename Gadfly/versions/{0.3.19 => 0.4.0}/requires (100%)
 rename Gadfly/versions/{0.3.19 => 0.4.0}/sha1 (100%)

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove
```
No problems.

**Comment by tkelman** [comment]
good enough then.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
