### PR TITLE
Tag VegaLite.jl v0.0.4

### PR DESCRIPTION
**Pull request by attobot**
Repository: [fredo-dedup/VegaLite.jl](https://github.com/fredo-dedup/VegaLite.jl)
Release: [v0.0.4](https://github.com/fredo-dedup/VegaLite.jl/releases/tag/v0.0.4)
Travis: [Travis Build Status](https://travis-ci.org/fredo-dedup/VegaLite.jl/builds/243164369)
Diff: [vs v0.0.3](https://github.com/fredo-dedup/VegaLite.jl/compare/05e1f11eb4a01873f17d66baa9d3f3e20e66452d...7716c41c9bc6222229ab9a7672dcacfab82e5aef)
`requires` vs v0.0.3: 
```diff
--- 0.0.3/requires
+++ 0.0.4/requires
@@ -1,4 +1,7 @@
 julia 0.4
-Compat 0.8
+Compat 0.9.1
 JSON
 Requires
+NodeJS
+Cairo
+Rsvg
```
cc: @fredo-dedup

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
Look like there's a syntax error on 0.4, should this be dropping 0.4 support? https://travis-ci.org/fredo-dedup/VegaLite.jl/jobs/243164370

**Comment by davidanthoff** [comment]
I'm prepping a PR that fixes this on julia 0.4.

**Comment by fredo-dedup** [comment]
With Julia 0.4 support dropped. We'll see later if it can be brought back.

**Comment by fredo-dedup** [comment]
I need to use a higher minor version number since Julia v0.4 support is dropped. Will make a new tag v0.1.0 and remove this one.

**Pull request closed without merging**
