### PR TITLE
Register new package FWF.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bkamins/FWF.jl](https://github.com/bkamins/FWF.jl)
Release: [v0.1.0](https://github.com/bkamins/FWF.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/bkamins/FWF.jl/builds/338231552)
cc: @bkamins

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@bkamins This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by bkamins** [comment]
No changes needed you can merge if it is OK with you.

**Comment by andreasnoack** [comment]
How does this relate to https://github.com/JuliaLang/METADATA.jl/pull/13268?

**Comment by RandomString123** [comment]
LOL.  Apparently we were both working on the same project but separately.

@bkamins  your code looks better than mine but I think I have a few more features.  We should figure out how to merge these two into a single project.  

I needed the functionality for some files I wanted to work worth but other than that I am not attached to the project.  I am fine giving you contribute to my repository or trying to merge into yours.   Let me know your thoughts on how you think we should move forward.

**Comment by bkamins** [comment]
😲 What a coincidence. This is completely unrelated.
I have written my package because people were asking questions about how to read FWF files recently.

@RandomString123: I like your design and if you intend to maintain FWF.jl in the long term there is no need to duplicate the efforts and my package does not have to be registered.

However, you might have a look at what I have implemented. Largely it is a much lighter approach but you could consider:
* in your implementation you use byte indexing and I use character indexing - I recommend my approach - as I guess your will badly fail on UTF-8 encoded data;
* adding something similar to `keep` keyword argument I have if field widths are passed (to allow for simple dropping of unwanted columns which often happen in FWF files - this is not needed with ranges version);
* I guess I have a bit different handling of malformed data;
* I have implemented auto detection of column widths which is handy in many situations.

Anyway - please let me know what you think how we could proceed as I think joining the efforts is the best approach!

**Comment by bkamins** [comment]
And LOL again - we were writing the replies in parallel :). Anyway - I have pointed out my thoughts above.

I am OK to go forward with your package and I can help implementing the points I have raised above.

**Comment by RandomString123** [comment]
@bkamins I added you as a collaborator to the repository and created an issue where we can discuss merging so we aren't doing it in this PR.  I think if you agree this is a good path forward let @andreasnoack know and he can get the PRs sorted out.

**Comment by andreasnoack** [comment]
Great. Thanks for resolving this so fast.

**Pull request closed without merging**
