### PR TITLE
Tag Mustache v0.0.8

### PR DESCRIPTION
**Pull request by jverzani**

### CODE REVIEW

**Comment by tkelman** [comment]
Could you hold off on merging your next PR until Travis has a chance to run on it? Don't want to accidentally cause master to start failing tests, which could lead to confusing failures in unrelated separate PR's.

**Comment by jverzani** [comment]
Sure, sorry didn't realize this was something to worry about. Thanks for letting me know.

**Comment by tkelman** [comment]
Failures aren't too likely, but better to let things verify as clean just in case. Should usually only take a few minutes for Travis to run. Thanks.

**Comment by tkelman** [comment]
Oh and judging by https://travis-ci.org/jverzani/Mustache.jl it looks like you need to put `using Compat` inside `module Mustache` for things to work correctly on 0.3

**Comment by jverzani** [comment]
Double thanks!

On Mon, Apr 20, 2015 at 10:07 AM, Tony Kelman <notifications@github.com>
wrote:

> Oh and judging by https://travis-ci.org/jverzani/Mustache.jl it looks
> like you need to put using Compat inside module Mustache for things to
> work correctly on 0.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/METADATA.jl/pull/2467#issuecomment-94461891>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Pull request merged**
