### PR TITLE
Tag SpatialEcology.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [EcoJulia/SpatialEcology.jl](https://github.com/EcoJulia/SpatialEcology.jl)
Release: [v0.5.0](https://github.com/EcoJulia/SpatialEcology.jl/releases/tag/v0.5.0)
Diff: [vs v0.4.3](https://github.com/EcoJulia/SpatialEcology.jl/compare/574e2a5eec107014996363cfbe9f6db2a565115b...1ae9e1f58aa07de89054d7a90dc84fb3c70ba5fd)
`requires` vs v0.4.3: 
```diff
--- 0.4.3/requires
+++ 0.5.0/requires
@@ -3,4 +3,5 @@
 RecipesBase
 DataFrames
 StatsBase
+#EcoBase
 #Phylogeny
```
cc: @mkborregaard

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Tests will fail as this depends on the newly released package EcoBase https://github.com/JuliaLang/METADATA.jl/pull/18175.

**Comment by andreasnoack** [comment]
It looks like there is some kind of error. Any idea what it is?

**Comment by mkborregaard** [comment]
Looks like an interaction between local toml/manifest file and require file. Let me try sth.

**Comment by mkborregaard** [comment]
Wait, it's totally mysterious - the line that errors is `using CSV`, and the error is 
```
ERROR: Base.Meta.ParseError("missing comma or ) in argument list")
Stacktrace:
 [1] #parse#1(::Bool, ::Bool, ::Bool, ::Function, ::String, ::Int64) at ./meta.jl:129
 [2] #parse at ./none:0 [inlined]
 [3] #parse#4(::Bool, ::Bool, ::Function, ::String) at ./meta.jl:164
 [4] parse(::String) at ./meta.jl:164
 [5] top-level scope at ./none:3
ERROR: LoadError: LoadError: Failed to precompile CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b] to /home/travis/.julia/compiled/v1.0/CSV/HHBkp.ji.
```
but CSV 0.3.1 (which is the version installed by the test) loads fine.
(I've updated the manifest/project in the release).

**Comment by mkborregaard** [comment]
You can mark this as "waiting for author" I guess. EDIT: please don't, it's fixed now.

**Comment by mkborregaard** [comment]
Wait, it's solved now. @fredrikekre found the fix, and I have to say that it surpasses the wit of mortals. 
In short, these lines in SpatialEcology
```
const GroupedAssemblage = Vector{T} where T<:EcoBase.AbstractAssemblage

function show(io::IO, com::GroupedAssemblage)
    println(io, "GroupedAssemblage with $(length(com)) assemblages")
end
```
made any attempt to `using CSV` after `using SpatialEcology` fail with `ERROR: Base.Meta.ParseError("missing comma or ) in argument list")`

Yeah I don't get it either, but modifying the line made the tests pass.

**Comment by mkborregaard** [comment]
@andreasnoack Did you forget about this completely? :-O
It's ready to merge :-)

**Comment by andreasnoack** [comment]
Based on your latest comment, I expected an update. It also looks like this breaks `Microbiome`.

**Comment by mkborregaard** [comment]
Oh, my comment must have been unclear. I meant it to state that I've found a fix and that tests should pass. 
@kescobo do you know what's going at microbiome?

**Comment by mkborregaard** [comment]
Never mind, that's a bug in the tagged EcoBase package that slipped through my tests. Sorry :flushed:

**Comment by mkborregaard** [comment]
Alright, fixed. I've tagged a hotfix release of EcoBase that works (https://github.com/JuliaLang/METADATA.jl/pull/18771) and with that the Microbiome tests passes as well. 
So this and the EcoBase tag should definitely be ready to merge now :-)

**Comment by mkborregaard** [comment]
Thank you :heart:

**Pull request merged**
