### PR TITLE
Tag OpenEphysLoader.jl v0.2.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [galenlynch/OpenEphysLoader.jl](https://github.com/galenlynch/OpenEphysLoader.jl)
Release: [v0.2.2](https://github.com/galenlynch/OpenEphysLoader.jl/releases/tag/v0.2.2)
Travis: [Travis Build Status](https://travis-ci.org/galenlynch/OpenEphysLoader.jl/builds/415145046)
Diff: [vs v0.2.1](https://github.com/galenlynch/OpenEphysLoader.jl/compare/8e5cb1f17c5adef0f10ef0b749ccc659a433c15d...b529c164a1931da2eb4273e9dbb9864547e2bf3c)
`requires` vs v0.2.1: no changes
cc: @galenlynch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Is this obsolete?

**Comment by galenlynch** [comment]
I suppose, it has all the same features as 0.2.3 but does not have the compatibility changes. Should I not include it as a tagged version?

**Comment by andreasnoack** [comment]
It's up to you but it seems that there isn't much reason to do it now that 0.2.3 is in.

**Comment by galenlynch** [comment]
Ok, I don't know how to close an attobot PR, so could you please close this PR?

Thanks!

**Pull request closed without merging**
