### PR TITLE
Tag IterativeSolvers.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMath/IterativeSolvers.jl](https://github.com/JuliaMath/IterativeSolvers.jl)
Release: [v0.5.0](https://github.com/JuliaMath/IterativeSolvers.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMath/IterativeSolvers.jl/builds/332968507)
Diff: [vs v0.4.2](https://github.com/JuliaMath/IterativeSolvers.jl/compare/46b05250aa1c7dd1d399d64b8a323d7db37f26ea...756edef2b6a58a65b41f87127fbec1f8c62150c7)
`requires` vs v0.4.2: 
```diff
--- 0.4.2/requires
+++ 0.5.0/requires
@@ -1,6 +1,3 @@
 julia 0.6
 
-UnicodePlots
 RecipesBase
-SugarBLAS
-LinearMaps
```
cc: @haampie

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
JuliaCIBot regression looks unrelated. Can you confirm @montyvesselinov ?

**Comment by haampie** [comment]
Regression for GeostatInversion.jl has an easy fix: https://github.com/madsjulia/GeostatInversion.jl/pull/2

**Comment by aviks** [comment]
Should we merge this now, or wait for `GeostatInversion` to be ready to tag?

**Comment by haampie** [comment]
Maybe best to ping @montyvesselinov to be sure. I'm fine with merging this.

**Comment by ChrisRackauckas** [comment]
You made the PR and everything but the author of the dependency hasn't responded, so I'm just gonna merge it since there's no reason to wait when the dependency has free code.

**Comment by montyvesselinov** [comment]
The PR Merged; sorry for the delay

**Comment by montyvesselinov** [comment]
madsjulia/GeostatInversion.jl#2 merged sorry for the delay

**Comment by aviks** [comment]
No problems @montyvesselinov, just wanted to ensure that you are aware of this issue.

**Pull request merged**
