### PR TITLE
Tag Variography.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/Variography.jl](https://github.com/juliohm/Variography.jl)
Release: [v0.0.2](https://github.com/juliohm/Variography.jl/releases/tag/v0.0.2)
Travis: [Travis Build Status](https://travis-ci.org/juliohm/Variography.jl/builds/363585310)
Diff: [vs v0.0.1](https://github.com/juliohm/Variography.jl/compare/a6da828ac0d3ea982f7cccac571a7bce2bdd0086...6602482141bc3bac10e09ec1c1c811abe1583f49)
`requires` vs v0.0.1: no changes
cc: @juliohm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by juliohm** [comment]
The errors in the build are because this package itself wasn't tagged yet.

**Comment by juliohm** [comment]
I appreciate if someone can merge this, the error on Travis is because of KrigingEstimators.jl which is also pending merge: https://github.com/JuliaLang/METADATA.jl/pull/14181

This should be the last disruptive change in this port. Refactoring and renaming classes led to this. Hopefully won't happen again anytime soon.

**Comment by juliohm** [comment]
@andreasnoack sorry for pinging you again, but this is hopefully the last breaking change on that GeoStats.jl refactoring we've been tagging here. Both `Variography.jl` and `KrigingEstimators.jl` would need to be merged simultaneously to avoid errors in the Travis build.

I am planning to use some new features of GeoStats.jl this weekend on a Hackaton on campus, and it would be great if people could try them out as well.

**Comment by juliohm** [comment]
I am depending on this PR (and related PRs) to release a new version of GeoStats.jl. There are lots of improvements that I would like to release before Julia v0.7 comes out. If anyone can double check that the build errors are caused by package splitting, that would be great.

**Comment by andreasnoack** [comment]
Sorry for the delay here.

**Pull request merged**
