### PR TITLE
Register (and tag) PiecewiseLinear.jl

### PR DESCRIPTION
**Pull request by joehuchette**

### CODE REVIEW

**Comment by tkelman** [comment]
Is this JuMP (optimization) specific? The name should probably reflect that, otherwise it sounds much more general than it is.

**Comment by joehuchette** [comment]
That's how I intend to use it, but it could be useful otherwise. I'm open to name suggestions that aren't ridiculously long.

**Comment by tkelman** [comment]
PiecewiseLinearOpt? PiecewiseLinearJuMP? PiecewiseLinearProg?

**Comment by joehuchette** [comment]
I think I can live with PiecewiseLinearOpt

**Pull request closed without merging**
