### PR TITLE
Tag HeatTransfer.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaFEM/HeatTransfer.jl](https://github.com/JuliaFEM/HeatTransfer.jl)
Release: [v0.2.0](https://github.com/JuliaFEM/HeatTransfer.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaFEM/HeatTransfer.jl/builds/421263447)
Diff: [vs v0.1.0](https://github.com/JuliaFEM/HeatTransfer.jl/compare/5654632fe884014fa37a8e7879dbc8bf3fbbfb37...58f32812eaefe8940a6646a6825ffba4415457c9)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,2 +1,2 @@
-julia 0.6
+julia 0.7 1.0-
 FEMBase
```
cc: @ahojukka5

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like this breaks HeatTransfer on 0.7

**Comment by andreasnoack** [comment]
Doh. This *is* HeatTransfer. The issue here is that Literate.jl includes a project file. We can ask @fredrikekre if he'd be okay with deleting it for the time being. Otherwise, it will only be possible to test the reverse dependencies once CIBot is upgraded to the new package manager.

**Comment by andreasnoack** [comment]
I noticed a lot of warnings in the JuliaFEM tests in CIBot similar to
```julia
WARNING: eval from module Calculus to FEMBasis:    
Expr(:call, :*, 0.25, 0)
  ** incremental compilation may be broken for this module **
```
Do you also see them when running the tests locally?

**Comment by ahojukka5** [comment]
Yes, I can see them and have seen them for a long time. I don't know the cause of these warnings. I have opened issues about them in both FEMBasis.jl and Calculus.jl:

- https://github.com/JuliaFEM/FEMBasis.jl/issues/9
- https://github.com/JuliaMath/Calculus.jl/issues/128

**Comment by andreasnoack** [comment]
Okay. I'll merge here despite CIBot not being able to verify that things work such that things won't get more delayed.

**Pull request merged**
