### PR TITLE
Tag NFFT.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [tknopp/NFFT.jl](https://github.com/tknopp/NFFT.jl)
Release: [v0.2.0](https://github.com/tknopp/NFFT.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/tknopp/NFFT.jl/builds/194275586)
Diff: [vs v0.1.4](https://github.com/tknopp/NFFT.jl/compare/3310762229a1a0ba68dc02caccf43e6f045847b2...2ee5cb86a5fed6d228edb27e3246e576f72ef429)
`requires` vs v0.1.4: no changes
cc: @tknopp

### CODE REVIEW

**Comment by tknopp** [comment]
don't understand why this now has Julia 0.4 in its requires.

https://github.com/tknopp/NFFT.jl/blob/master/REQUIRE

**Comment by tkelman** [comment]
tagged the wrong commit maybe?

**Comment by tknopp** [comment]
this was attobot from master.
But now #7664 looks better (apparently had to skip 0.2.0)

**Comment by tkelman** [comment]
maybe an attobot bug? cc @simonbyrne

**Comment by simonbyrne** [comment]
When you created the release, it used the preexisting tag (created from #7642). In future, you should [delete the release & tag](https://github.com/attobot/attobot#updatingdeleting-a-release) before retagging.

**Comment by tknopp** [comment]
A thanks for clarifying!

**Pull request closed without merging**
