### PR TITLE
Tag ForwardDiff v0.1.0

### PR DESCRIPTION
**Pull request by jrevels**
My JSoC project finally bears fruit!

### CODE REVIEW

**Comment by mlubin** [comment]
:100:

**Comment by jrevels** [comment]
I also made an [announcement post](https://groups.google.com/forum/#!topic/julia-users/-Kg7Wwt-wjU). 

It feels *really* good to finally release this.

**Comment by KristofferC** [comment]
I can understand that. Looks like a lot of hard work, but a very nice result!

**Comment by gragusa** [comment]
💯

**Pull request merged**
