### PR TITLE
Migrate AWSCore.jl to JuliaCloud github account

### PR DESCRIPTION
**Pull request by samoconnor**
Migrate AWSCore.jl from samoconnor account to JuliaCloud account

### CODE REVIEW

**Comment by tkelman** [comment]
This should really be using a github transfer, not a duplicate copy at a separate URL. Otherwise anyone who has the package already installed will no longer receive any updates since their remotes will still point at your personal copy.

**Comment by samoconnor** [comment]
Hi Tony,
I'm not familiar with Gitub's transfer feature.
My `.git/config` is set so that both remotes are kept up to date:
```
[remote "origin"]
	url = https://github.com/JuliaCloud/AWSCore.jl.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = git@github.com:samoconnor/AWSCore.jl.git
	pushurl = git@github.com:JuliaCloud/AWSCore.jl.git
```
My intention was to leave this in place for a while to give people a chance to catch up.
But, if there's a "right way" to do it, I'm happy to learn about it.

**Comment by tkelman** [comment]
I'm not worried about you, I'm worried about every other computer that has ever run `Pkg.add("AWSCore")` or one of its dependents.

1. Delete the current https://github.com/JuliaCloud/AWSCore.jl.
2. Go to the settings of https://github.com/samoconnor/AWSCore.jl, go to transfer repository and move it to JuliaCloud
3. Try to avoid ever creating a personal fork at https://github.com/samoconnor/AWSCore.jl again, as anyone who ever did Pkg.add before this PR that changes the URL gets merged won't have their remotes redirected. Github will redirect things automatically if you do a repo transfer, but if you create a new separate repo or fork at the old location the redirect will no longer work and anyone with an old copy won't be able to pull updates from the right place since Pkg doesn't fix the remotes of existing clones.

**Comment by samoconnor** [comment]
Well, I'm glad for your experience with this stuff.
I had assumed that `Pkg.update()` would do `git remote rm|add origin` when the `METADATA.jl` url changed.

**Comment by samoconnor** [comment]
Hi @vikjam, @leeper,
I noticed that you had starred JuliaCloud/AWSCore.jl.
Please note that it is about to be deleted and replaced by a repo of the same name (transferred from samoconnor/AWSCore.jl).

**Comment by samoconnor** [comment]
@tkelman I've transferred the repo per your instructions.
```
$ curl -v https://github.com/samoconnor/AWSCore.jl
...
HTTP/1.1 301 Moved Permanently
...
Location: https://github.com/JuliaCloud/AWSCore.jl 
```

**Comment by samoconnor** [comment]
@tkelman, @tanmaykm, @quinnj, @s2maki

AWSCore.jl has moved to JuliaCloud, but there are a few dependancies to take care of.

The motivation for moving AWSCore.jl was to ensure that other people could make patches if needed in the event that I am unavailable for periods of time. To this end, it seems like a good idea to move the following dependancies to an suitable "organisaiton" account (or accounts):

 - Retry.jl -- @quinnj and I have [recently discussed](https://github.com/JuliaWeb/HTTP.jl/pull/77#discussion_r134917630) merging some of his new retry macros into Retry.jl. Perhaps it makes sense for Retry.jl to live at [JuliaWeb](https://github.com/JuliaWeb) ?
- XMLDict.jl -- Maybe this should live next to LightXML.j in [JuliaIO](https://github.com/JuliaIO)?
- SymDict.jl -- To my knowledge, this is only used by `AWS*`. I could move it to [JuliaCloud](https://github.com/JuliaCloud), or I could just absorb it into AWSCore if it not seen as being more widely useful.

What do you all think?

(To move things to JuliaWeb or JuliaIO I would need someone to set me up with appropriate access permission)

**Pull request merged**
