### PR TITLE
Register AWSSDK.jl

### PR DESCRIPTION
**Pull request by samoconnor**
https://github.com/JuliaCloud/AWSSDK.jl

### CODE REVIEW

**Comment by samoconnor** [comment]
https://github.com/JuliaCloud/AWSSDK.jl/commit/28d8302e1a145ead37cef5578763de761b9a20c3

**Comment by samoconnor** [comment]
CIBot passes for 0.5 and 0.6.
But fails for 0.7 http://juliarun-ci.s3.amazonaws.com/a2598a51a1c33eccc114f7da2637908a62999be6/AWSSDK_julia_0_7.log

**Comment by samoconnor** [comment]
Fix for 0.7 string escaping problem: https://github.com/JuliaCloud/AWSSDK.jl/commit/e16e4a025ab421cef19a63c46de5629b66273f43 

https://github.com/JuliaLang/julia/issues/21284

https://github.com/domchristie/to-markdown/issues/181

**Comment by samoconnor** [comment]
More string escaping fixes for 0.7
https://github.com/JuliaCloud/AWSSDK.jl/commit/6c1a2d1a51b352cb47d42d37020b504b67948bd3
https://github.com/JuliaCloud/AWSCore.jl/commit/0afbf0890284b1e2fb36b2daedea86b05e120311

**Comment by ararslan** [comment]
Did you mean to include the commits you're reference in this tag? If so, looks like you'll have to retag and update the SHA here.

**Comment by samoconnor** [comment]
Hi @ararslan, No, I don't intent to include those commits.
I referenced them here just as a follow up to the 0.7 CI bot fail.
I don't intend to "officially" support 0.7 yet. Some of my dependancies do not yet have tagged versions with 0.7 support.

I would like to get the package registered as-is, then follow up with a v0.0.2.
I have recently added support for a few new AWS services:  https://github.com/JuliaCloud/AWSSDK.jl/commit/41da8d7fbfb791ce2758eb086fcb7a42cbb09f05

**Comment by ararslan** [comment]
Okay great, thanks for the clarification.

**Pull request merged**
