### PR TITLE
Tag ColorSchemes.jl v2.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphics/ColorSchemes.jl](https://github.com/JuliaGraphics/ColorSchemes.jl)
Release: [v2.0.0](https://github.com/JuliaGraphics/ColorSchemes.jl/releases/tag/v2.0.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphics/ColorSchemes.jl/builds/421994193)
Diff: [vs v1.5.1](https://github.com/JuliaGraphics/ColorSchemes.jl/compare/f0acf187b04f846e4508be3901b9fc58a035da7b...0fc1715625660a7f41953c916fa27c3970ae095a)
`requires` vs v1.5.1: 
```diff
--- 1.5.1/requires
+++ 2.0.0/requires
@@ -1,8 +1,7 @@
-julia 0.6
-Images 0.9.1
-Colors 0.7.0
+julia 0.7
+Images
+Colors
 Clustering
 FileIO
-@windows ImageMagick
-@linux ImageMagick
-@osx QuartzImageIO
+ImageMagick
+QuartzImageIO
```
cc: @cormullion

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
The CIBot tests fails because NearestNeighbors has a project file checked in.

**Comment by cormullion** [comment]
OK, is there anything I have to do? Otherwise I'm happy to wait... :)

**Comment by andreasnoack** [comment]
> OK, is there anything I have to do?

No. I just wanted to let you know why the reverse dependency testing failed. The reason I didn't merge when I wrote the last comment was that the Travis tests hadn't finished yet.

**Comment by cormullion** [comment]
Oh, OK. Thanks Andreas!

**Pull request merged**
