### PR TITLE
Upper bound TypeSortedCollections for RigidBodyDynamics.

### PR DESCRIPTION
**Pull request by tkoolen**
Fixes https://github.com/tkoolen/RigidBodyDynamics.jl/issues/332.

### CODE REVIEW

**Comment by tkelman** [comment]
Not necessarily. Pkg could choose to downgrade RigidBodyDynamics to a previous version that doesn't depend on TypeSortedCollections in order to upgrade to the latest TypeSortedCollections version.

**Comment by tkoolen** [comment]
> Pkg could choose to downgrade RigidBodyDynamics to a previous version that doesn't depend on TypeSortedCollections in order to upgrade to the latest TypeSortedCollections version.

That would be better than the current situation. And if users want to avoid that situation, they can set a lower bound on RigidBodyDynamics in their REQUIRE file (either the one for a dependent package, or the global one).

**Comment by tkoolen** [comment]
Any update on this?

**Comment by tkoolen** [comment]
See also https://github.com/JuliaLang/METADATA.jl/pull/11281.

**Comment by KristofferC** [comment]
Should this still be merged?

**Comment by tkoolen** [comment]
In my opinion, yes. It's just a fact that version 0.3.0 of RigidBodyDynamics doesn't work with version 0.1.1 of TypeSortedCollections, so I think that should be modeled. I believe that the scenario from https://github.com/JuliaLang/METADATA.jl/pull/11158#issuecomment-328945323 can't happen anymore because of the new RigidBodyDynamics tag. And again, even that scenario would have been better than the situation before this PR and the release of RigidBodyDynamics 0.4.0, so I don't understand the holdup.

**Pull request merged**
