### PR TITLE
Tag Flux.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [MikeInnes/Flux.jl](https://github.com/MikeInnes/Flux.jl)
Release: [v0.2.1](https://github.com/MikeInnes/Flux.jl/releases/tag/v0.2.1)
Diff: [vs v0.2.0](https://github.com/MikeInnes/Flux.jl/compare/efcb9650da31c183b94b839f66aa3467d007c33f...7a85eff370b7c68d587b49699fa3f71e44993397)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.2.1/requires
@@ -1,5 +1,5 @@
-julia 00.6-
+julia 0.6-
 Iterators
 DataFlow
 Juno
-MacroTools  0.3.3
+MacroTools 0.3.3
```
cc: @MikeInnes

### CODE REVIEW

**Comment by tkelman** [comment]
Still modifying base functions on base types. https://github.com/MikeInnes/Flux.jl/pull/24

**Comment by tkelman** [comment]
Hey. Slow your roll and stop ignoring review.

**Comment by MikeInnes** [comment]
Not ignoring, it just doesn't need to block

**Comment by tkelman** [comment]
When you click merge without saying a word, it comes across as ignoring. A simple response to the effect of "Will address that later, would like to get this tagged ASAP" would go a long way.

**Pull request merged**
