### PR TITLE
Tag Distances v0.3.1

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by tkelman** [comment]
likewise, please push git tag to https://github.com/JuliaStats/Distances.jl/releases

**Comment by KristofferC** [comment]
Why am I so bad :(

**Comment by KristofferC** [comment]
https://github.com/JuliaStats/Distances.jl/releases/tag/v0.3.1

did it from github ui

**Comment by tkelman** [comment]
That works, thanks. Mostly helps with later bookkeeping.

**Pull request merged**
