### PR TITLE
Tag Distributions v0.10.3

### PR DESCRIPTION
**Pull request by ararslan**
Got a SecureTransport error on OS X using `PkgDev.publish()`, so I'm doing it manually. Bummers.

### CODE REVIEW

**Comment by tkelman** [comment]
> 100 changed files with 8,663 additions and 7,324 deletions. 

Is this really a patch update?

**Comment by tkelman** [comment]
Oh right, remember https://github.com/JuliaLang/METADATA.jl/pull/5876
> creating a branch from right before the major rewrite, re-applying the deprecation fixes and tagging that as 0.10.2?

Any reason to believe it'll break fewer packages this time around than it did in August? Major rewrites should use at least a new minor version numbers, probably major - though maybe you don't want to tag something that's likely very broken as 1.0.0.

**Comment by ararslan** [comment]
> Any reason to believe it'll break fewer packages this time around than it did in August?

Nope. Now I remember the whole branch thing we did with 0.10.2...

**Comment by tkelman** [comment]
Probably safer to backport some of https://github.com/JuliaStats/Distributions.jl/compare/v0.10.1...v0.10.3 to a branch starting from https://github.com/JuliaStats/Distributions.jl/tree/release-0.10.2, if https://github.com/JuliaStats/Distributions.jl/pull/532#issuecomment-246552504 is still the case

**Pull request closed without merging**
