### PR TITLE
Tag Gumbo v0.1.3

### PR DESCRIPTION
**Pull request by porterjamesj**

### CODE REVIEW

**Comment by porterjamesj** [comment]
cc @aviks

**Comment by tkelman** [comment]
Since this version drops support for Julia 0.3, you'll need to tag it as a new minor version via `Pkg.tag("Gumbo", :minor)`. Leave out the v0.1.3 tag.

**Comment by porterjamesj** [comment]
aha, this might also explain why `Pkg.tag` wouldn't let me tag a patch version. will fix.

**Comment by porterjamesj** [comment]
oh I see what happened, I somehow managed to tag 0.2.0 on here but end up without a tag in my git repo. 0.2.0 dropped support for 0.3, so I will tag this as 0.2.1.

**Comment by porterjamesj** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5781

**Pull request closed without merging**
