### PR TITLE
Register and tag PlotlyJS.jl

### PR DESCRIPTION
**Pull request by spencerlyon2**
Purely offline interface to plotly.js visualization library.

[docs](http://spencerlyon.com/PlotlyJS.jl/)
[tests](https://travis-ci.org/spencerlyon2/PlotlyJS.jl)

Will be a dependency to Plotly/Plotly.jl. This package will be responsible for constructing visualizations and integrating with display front ends (electron, Jupyter, etc.). Plotly/Plotly.jl will be used to interface with the plotly REST api

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
:tada:

**Comment by johnmyleswhite** [comment]
Gave it a few hours; merging now.

**Comment by spencerlyon2** [comment]
Thank you!

**Comment by tkelman** [comment]
Preferable to leave at least 24hrs, given time zones.

**Comment by tkelman** [comment]
@spencerlyon2 can you push the git tags so they show up under https://github.com/spencerlyon2/PlotlyJS.jl/releases ?

**Comment by spencerlyon2** [comment]
Sure thing. Done

**Pull request merged**
