### PR TITLE
Tag SimpleTasks v0.0.11

### PR DESCRIPTION
**Pull request by wongwill86**

### CODE REVIEW

**Comment by tkelman** [comment]
please do a rebase, you're accumulating merge commits that make your PR's look larger than they really are

**Comment by wongwill86** [comment]
ah forgot to do that. sorry, it's caught up now.

**Comment by tkelman** [comment]
No, that just added another merge commit. Don't use the github interface to update your fork of METADATA, since that adds merge commits that don't exist upstream. Use the command line, or just check out the upstream copy of metadata-v2 and create new branches from that for pull requests.

**Comment by tkelman** [comment]
Much better, thank you.

**Pull request merged**
