### PR TITLE
Tag BinaryBuilder.jl v0.0.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPackaging/BinaryBuilder.jl](https://github.com/JuliaPackaging/BinaryBuilder.jl)
Release: [v0.0.3](https://github.com/JuliaPackaging/BinaryBuilder.jl/releases/tag/v0.0.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPackaging/BinaryBuilder.jl/builds/369907476)
Diff: [vs v0.0.2](https://github.com/JuliaPackaging/BinaryBuilder.jl/compare/819b085e57e405b7f845f4d81e68e771f3382cb9...3b438983dda37d9a30cdb728b309f378b84f3aa6)
`requires` vs v0.0.2: no changes
cc: @staticfloat

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Is it expected that it fails
1. on CIBot?
2. [three out of four 0.6 targets on Travis](https://travis-ci.org/JuliaPackaging/BinaryBuilder.jl)?

**Comment by staticfloat** [comment]
It is expected that it fails on CIBot (it's running inside of `docker`, and we don't have the right permissions setup on CIBot to allow its user namespace stuff to work)

It is not expected that it would fail on Travis.  I can't reproduce the failure locally, so I'm just going to run those jobs again and see if they magically start working.

**Comment by staticfloat** [comment]
I just realized what's going on.  You're seeing a feature branch fail.  That's expected.

This PR is for the v0.0.3 tag, which is here; https://travis-ci.org/JuliaPackaging/BinaryBuilder.jl/builds/369907476

**Comment by andreasnoack** [comment]
Thanks for clarifying.

**Pull request merged**
