### PR TITLE
New ShowSet package and updated Permutations package

### PR DESCRIPTION
**Pull request by scheinerman**
Added a new package called `ShowSet` that provides for nicer printing of `Set` and `IntSet` objects. Also updated version number of my `Permutations` module.

### CODE REVIEW

**Comment by IainNZ** [comment]
Can you rebase this?

**Comment by scheinerman** [comment]
I'd be glad to, but I don't know what "rebase" means or how to do it! Can you please send or point me to instructions. (I had a lot of trouble as I don't really understand git or julia package work.) Thanks.

**Comment by IainNZ** [comment]
So the easiest way would to:
1) `git clone` your METADATA fork somewhere convenient
2) run something like `git rebase git rebase -i HEAD~61`. An editor will appear with instructions, you want to "squash" all these merge commits into one, which just involves putting `s` at the start of the line for each commit.
3) Once thats done, run `git log` to see if it looks ok, then force push it back to github: `git push -f origin metadata-v2`
4) This pull request should automatically update

**Comment by IainNZ** [comment]
I think this is caused by tagging something and not publishing immediately - everytime you run package update, a new merge commit has to be made until you publish your new tags.

**Comment by kmsquire** [comment]
Simply rebasing against `origin/metadata-v2` in the `METADATA` directory often gets rid of the merge commits.

```
cd ~/.julia/v0.3/METADATA
rebase origin/metadata-v2
git log # as in Iain's #3 above
```

(If there are conflicts, I usually abort the rebase and do something more severe, as Iain suggested.)

**Comment by scheinerman** [comment]
I’m sort of doubtful that I did this correctly. Here’s what I got at the end:

$ git push -f origin metadata-v2
Username for 'https://github.com': scheinerman
Password for 'https://scheinerman@github.com': 
Everything up-to-date

I may need more “idiot proof” instructions.  Sorry!!

**Comment by IainNZ** [comment]
A more nuclear option is

1. Give up on this PR
2. Delete your METADATA fork on Github
3. Go to your julia package folder (`~/.julia/v0.3/`), nuke the METADATA folder there
4. git clone a fresh METADATA
5. Do your tagging, registering
6. Pkg.publish it

**Comment by scheinerman** [comment]
OK. I *think* I understand what all this means and will give this a try, but probably not 'til the weekend.

**Comment by scheinerman** [comment]
@IainNZ I tried your steps, but Julia just hangs at #6.

**Comment by scheinerman** [comment]
Tried once again. Got this:

```julia
julia> Pkg.publish()
Username for 'https://github.com': scheinerman
Password for 'https://scheinerman@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/scheinerman/METADATA.jl.git/' not found
ERROR: failed process: Process(`git --work-tree=/home/ers/.julia/v0.3/METADATA --git-dir=/home/ers/.julia/v0.3/METADATA/.git fetch -q`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:502
 in run at pkg/git.jl:22
 in publish at pkg/entry.jl:310
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in __cd#227__ at ./pkg/dir.jl:28
 in publish at pkg.jl:57
```
Ready to give up :-)

**Comment by jakebolewski** [comment]
@scheinerman if you go to https://github.com/JuliaLang/METADATA.jl and click the fork button in the upper right hand corner, it should clone METADATA to `https://github.com/scheinerman/METADATA.jl`.  If you try `Pkg.publish()` again from the REPL it hopefully should work.

**Comment by scheinerman** [comment]
Hi all: I must be skipping a key step to fail so many times ... I hope this is all easier in Julia 0.4 and I think I might wait for that. But after forking METADATA, cloning it in ~/.julia/v0.3, changing its name from METADATA.jl to METATDATA, I did this:
```julia

$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.5 (2015-01-08 22:33 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  x86_64-linux-gnu

julia> Pkg.register("ShowSet")
INFO: Registering ShowSet at git://github.com/scheinerman/ShowSet.jl.git
INFO: Tagging ShowSet v0.0.1
INFO: Committing METADATA for ShowSet

julia> Pkg.publish()
INFO: Validating METADATA
INFO: Pushing ShowSet permanent tags: v0.0.1
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: failed process: Process(`git --work-tree=/home/ers/.julia/v0.3/ShowSet --git-dir=/home/ers/.julia/v0.3/ShowSet/.git push -q origin refs/tags/v0.0.1:refs/tags/v0.0.1`, ProcessExited(128)) [128]
 in wait at ./task.jl:284
 in wait at ./task.jl:194
 in wait at task.jl:48
 in sync_end at ./task.jl:311
 in publish at pkg/entry.jl:319
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in __cd#227__ at ./pkg/dir.jl:28
 in publish at pkg.jl:57
```

**Comment by scheinerman** [comment]
I *think* I may have had some success this morning :-).

**Pull request closed without merging**
