### PR TITLE
Tag GMT.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [GenericMappingTools/GMT.jl](https://github.com/GenericMappingTools/GMT.jl)
Release: [v0.2.0](https://github.com/GenericMappingTools/GMT.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/GenericMappingTools/GMT.jl/builds/296928084)
Diff: [vs v0.1.0](https://github.com/GenericMappingTools/GMT.jl/compare/e8535e792e9487527d079ec5d8773a035e9a41a8...afc3a155f7adf58fc263424d26ae13fc6bb8c9c6)
`requires` vs v0.1.0: no changes
cc: @joa-quim

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
0.5.2 Tests seem to fail with a syntax error.

**Comment by joa-quim** [comment]
No. They fail because the GMT package itself it's not installed. You can see that when it is
https://travis-ci.org/GenericMappingTools/GMT.jl
the tests pass.

**Comment by aviks** [comment]
On Travis, you seem to be testing `v0.6`. On the METADATA tests, 0.6 tests fail due to installing GMT, but tests on `v0.5.2` are failing with the following error. If your package does not work on 0.5, you should change your `REQUIRE`

```
ERROR: LoadError: LoadError: syntax: extra token "T" after end of expression
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /mnt/pkgevalempty/bff772fd18c13fe0d294c6426eafc7f4dcb447dc/GMT/.julia/v0.5/GMT/src/common_options.jl, in expression starting on line 864
while loading /mnt/pkgevalempty/bff772fd18c13fe0d294c6426eafc7f4dcb447dc/GMT/.julia/v0.5/GMT/src/GMT.jl, in expression starting on line 58
ERROR: LoadError: Failed to precompile GMT to /mnt/pkgevalempty/bff772fd18c13fe0d294c6426eafc7f4dcb447dc/GMT/.julia/lib/v0.5/GMT.ji.

```

**Comment by joa-quim** [comment]
I now require 0.6, why is JuliaCIBot still doing 0.5.2 also? I would like this merged.

**Pull request merged**
