### PR TITLE
Register AbstractTrees

### PR DESCRIPTION
**Pull request by Keno**
A small package with various algorithms for working with tree-like data structures (and provides hooks for packages that contain such data structures).

### CODE REVIEW

**Comment by tkelman** [comment]
the filename in metadata is `requires` not `REQUIRE`

**Comment by tkelman** [comment]
Push git tags to https://github.com/Keno/AbstractTrees.jl/releases.

Conventional protocol has been to leave new package registrations open for 24 hours. If there's a strong need to rush this, do say so.

**Comment by Keno** [comment]
Yes, I'd like to merge this sooner. I'm getting ready to register a bunch of packages (and bumps to existing packages) which depend on this.

**Comment by tkelman** [comment]
Turn Travis on, add something non-empty to the readme?

**Pull request merged**
