### PR TITLE
Register new package DimArrays.jl

### PR DESCRIPTION
**Pull request by mcabbott**
Register new package

### CODE REVIEW

**Comment by andreasnoack** [comment]
Thanks for providing this package. Please enable Travis testing for the package. Please also consider using https://github.com/attobot/attobot when registering or releasing packages.

**Comment by mcabbott** [comment]
Done, I think I have both Travis and attobot turned on now.

**Comment by mcabbott** [comment]
Should I change something to make JuliaCIBot happy? Have not yet upgraded to 0.7, edited `.travis.yml` to allow failures on nightly.

**Comment by mcabbott** [comment]
Closing in favour of  https://github.com/JuliaLang/METADATA.jl/pull/16001 made via attobot

**Pull request closed without merging**
