### PR TITLE
Register new package SimpleGraphs.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [scheinerman/SimpleGraphs.jl](https://github.com/scheinerman/SimpleGraphs.jl)
Release: [v0.1.0](https://github.com/scheinerman/SimpleGraphs.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/scheinerman/SimpleGraphs.jl/builds/417715394)
cc: @scheinerman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@scheinerman This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Error log says
```julia
ERROR: LoadError: package SimpleGraphs v0.1.0 requires a non-registered package: SimpleRandom
```

**Comment by scheinerman** [comment]
`SimpleRandom` is now registered so can we please try again to register `SimpleGraphs`?

**Comment by andreasnoack** [comment]
The easiest way to try this out is for you to remove and reapply the tag here. It will automatically update this PR and the tests will run again. If they pass then the PR will be merged automatically.

**Comment by scheinerman** [comment]
Thanks! I didn't see how to delete and reinstate a tag, so I just put a new number on it.

**Comment by andreasnoack** [comment]
Please don't. It makes out job harder and errors are more likely. The upgrading process is described in the documentation for Attobot, see https://github.com/attobot/attobot#updatingdeleting-a-release.

**Comment by scheinerman** [comment]
OK. Deleted 0.1.2 and 0.1.1, and then reinstated 0.1.1.  I hope that works! Sorry 'bout that.

**Comment by andreasnoack** [comment]
You are welcome. Almost there. This PR is 0.1.0 though.

**Comment by scheinerman** [comment]
This is really strange. Version 0.1.0 passes checks but Travis is looking for 0.1.2 and that's why it's failing. Should I just tag an 0.1.2 release and hope for the best?

**Comment by andreasnoack** [comment]
You should, within GitHub, delete these two releases *and* tags, and then make a new v0.1.0 release.

**Comment by scheinerman** [comment]
Thanks. I think I did what I was supposed to :-)  ... Let me know if I messed up. I appreciate your help.

**Pull request merged**
