### PR TITLE
Pull request/939cf3f3

### PR DESCRIPTION
**Pull request by tinybike**

### CODE REVIEW

**Comment by IainNZ** [comment]
Hi @tinybike. All Julia packages are in the same namespace, so `Simulator` is way too general a name to add into METADATA. `AugurSimulator` would be a good idea.

**Comment by dpsanders** [comment]
Or perhaps `AugurSimulation.jl` or even maybe just `Augur.jl`?

**Comment by tinybike** [comment]
Oh, I see your point!  Yeah, `Augur.jl` would probably be easiest -- `AugurSimulator` makes sense but is a bit long.

**Comment by dpsanders** [comment]
Actually in my opinion, longer is better -- for a non-expert, `Augur` does not mean anything. In any case in the REPL or IJulia etc. you can use tab completion.

**Pull request closed without merging**
