### PR TITLE
Tag RCall v0.10.6 [https://github.com/JuliaInterop/RCall.jl]

### PR DESCRIPTION
**Pull request by randy3k**
Diff vs v0.10.5: https://github.com/JuliaInterop/RCall.jl/compare/e43868ffad9c34b7e9144882a0fc80a7c0bb054e...fb00c408fcb7e2741dc9484449283d877b3689aa

@simonbyrne For some reasons, attobot didn't automatically create the PR, so I have to push it manually.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like this is breaking. Is that expected? If so, some bounds should probably be added.

**Comment by randy3k** [comment]
The dependencies failures are not because of RCall, it seems JuliaCIBot has some issues.

**Comment by randy3k** [comment]
JuliaCIBot still stops at `Cloning METADATA from https://github.com/randy3k/METADATA.jl`.

**Comment by andreasnoack** [comment]
cc: @nkottary

**Comment by randy3k** [comment]
let me retag and try again.

**Pull request closed without merging**
