### PR TITLE
Tag Vega v0.3.4

### PR DESCRIPTION
**Pull request by randyzwitch**
Now that I've lost push ability on METADATA, I'm almost assuredly doing this wrong. Not sure why I have 963 commits to my request, when I'm only changing Vega.jl

### CODE REVIEW

**Comment by tkelman** [comment]
There's a merge conflict here. You need to rebase this branch so it only includes the one commit.

**Comment by randyzwitch** [comment]
Any hints? This is just going to be one big monkey-banging-on-keyboard operation for me, because I've got no idea why I have 250 of other people's commits anyway.

**Comment by tkelman** [comment]
Something like the following, assuming you start out with this branch checked out locally:
```
git remote add JuliaLang https://github.com/JuliaLang/METADATA.jl
git remote add randyzwitch https://github.com/randyzwitch/METADATA.jl
git fetch JuliaLang
git rebase -i JuliaLang/metadata-v2
# set "pick" for the commit "Tag Vega v0.3.4"
# and delete any other lines
# check "git log", "git diff HEAD~ HEAD" to be sure it looks right
git push --force randyzwitch metadata-v2
```
then refresh the page here.

**Comment by randyzwitch** [comment]
Starting over

**Pull request closed without merging**
