### PR TITLE
Update DoubleDouble URL to JuliaMath org

### PR DESCRIPTION
**Pull request by dpsanders**
DoubleDouble moved to JuliaMath.

cc @simonbyrne

### CODE REVIEW

**Comment by simonbyrne** [comment]
I believe @tkelman has a script to handle this?

**Comment by simonbyrne** [comment]
Ah, it's so you can use AttoBot (https://github.com/JuliaMath/DoubleDouble.jl/issues/24).

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/.test/update-redirects.jl but doesn't hurt to do manually

lgtm

**Comment by tkelman** [comment]
(as long as it's done via a repo transfer, so github redirects work on existing remotes, which this was)

be sure to double check that CI services are still running okay with the new repo location

**Pull request merged**
