### PR TITLE
Tag PowerModels.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lanl-ansi/PowerModels.jl](https://github.com/lanl-ansi/PowerModels.jl)
Release: [v0.4.0](https://github.com/lanl-ansi/PowerModels.jl/releases/tag/v0.4.0)
Diff: [vs v0.3.4](https://github.com/lanl-ansi/PowerModels.jl/compare/0171f8baba821f27196a566365164fa5ab8c98a5...115de853fd4103b712d051e902540e7fa2b627be)
`requires` vs v0.3.4: 
```diff
--- 0.3.4/requires
+++ 0.4.0/requires
@@ -1,5 +1,5 @@
 julia 0.5
 JSON 0.6.0
 MathProgBase 0.5.4
-JuMP 0.17 0.18-
+JuMP 0.17 0.19-
 Compat 0.17
```
cc: @ccoffrin

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like the existing versions of PowerModelsAnnex won't be compatible with this?

**Comment by ccoffrin** [comment]
This correct.  There are so many breaking changes in this release there will need to be a new version of the annex to address them.  

As I understand it, `PowerModels 0.3 0.4-` in the [Annex REQUIRE](https://github.com/lanl-ansi/PowerModelsAnnex.jl/blob/master/REQUIRE) should prevent it from using this version of PowerModels until I have a chance to update the Annex package.

**Comment by ccoffrin** [comment]
@tkelman does anything else need to be done here?

**Comment by ccoffrin** [comment]
Thanks!

**Pull request merged**
