### PR TITLE
Tag PrettyPlots.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMPC/PrettyPlots.jl](https://github.com/JuliaMPC/PrettyPlots.jl)
Release: [v0.0.2](https://github.com/JuliaMPC/PrettyPlots.jl/releases/tag/v0.0.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMPC/PrettyPlots.jl/builds/389794930)
Diff: [vs v0.0.1](https://github.com/JuliaMPC/PrettyPlots.jl/compare/2eeb96d22d37f302a6df4faa348b181f52f1afff...598c21153a170aa14068fccc053ecc1c6ef39b65)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.0.2/requires
@@ -1,7 +1,7 @@
 julia 0.6
 Colors
-DataFrames 0.0.0 0.11.0
+DataFrames 0.11
 Plots
-GR
-VehicleModels 0.1.3
-NLOptControl 0.1.3
+PyPlot
+VehicleModels 0.1.4
+NLOptControl 0.1.6
```
cc: @huckl3b3rry87

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
From the log
```julia
ERROR: LoadError: packages with unsatisfiable requirements found:
    PrettyPlots v0.0.2 – no valid versions exist for package

**Comment by andreasnoack** [comment]
From the log
```julia
ERROR: LoadError: packages with unsatisfiable requirements found:
    PrettyPlots v0.0.2 – no valid versions exist for package

**Comment by huckl3b3rry87** [comment]
please close this

**Comment by huckl3b3rry87** [comment]
sorry, please delete this as well

**Comment by andreasnoack** [comment]
Your call but it's fine to keep the PR open while you fix the package. You can just move the tag when you are ready and the PR will be updated. Let me know if you still prefer that the PR is closed.

**Comment by huckl3b3rry87** [comment]
@andreasnoack thank you for the explanation, I just made a new tag, so please delete this one

**Pull request closed without merging**
