### PR TITLE
Tag NCDatasets.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Alexander-Barth/NCDatasets.jl](https://github.com/Alexander-Barth/NCDatasets.jl)
Release: [v0.2.0](https://github.com/Alexander-Barth/NCDatasets.jl/releases/tag/v0.2.0)
Diff: [vs v0.1.0](https://github.com/Alexander-Barth/NCDatasets.jl/compare/9a484d59b0f2e6180d891329637476825a4c065a...aa5f896cc90102cf169a18852e0a7661229b9810)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,4 +1,5 @@
 julia 0.6
-DataArrays 0.7
 BinDeps 0.4
 Conda 0.3
+Missings
+Compat
```
cc: @Alexander-Barth

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
Sorry for the noise, this issue should be closed without merging. I will make a new attempt later.

**Comment by andreasnoack** [comment]
Looks like this causes a segfault in `DIVAnd`

**Comment by Alexander-Barth** [comment]
This is really strange. I can reproduce this error in Julia 0.6.2 but not in Julia 0.6.3:
```
$ ~/opt/julia-0.6.3/bin/julia -e 'using NCDatasets; function fun(); ds = Dataset("juliaYLTJUL.nc"); tmp = nomissing(ds["obstime"][1:3]); @show tmp; end; fun()'
tmp = DateTime[2001-09-09T00:00:00, 2008-05-04T00:00:00, 2000-04-24T00:00:00]
master2:~  
$ ~/opt/julia-0.6.2/bin/julia -e 'using NCDatasets; function fun(); ds = Dataset("juliaYLTJUL.nc"); tmp = nomissing(ds["obstime"][1:3]); @show tmp; end; fun()'

signal (4): Illegal instruction
while loading no file, in expression starting on line 0
fun at ./none:1
unknown function (ip: 0x2aaac2b06c9f)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:75
eval at /buildworker/worker/package_linux64/build/src/interpreter.c:242
jl_interpret_toplevel_expr at /buildworker/worker/package_linux64/build/src/interpreter.c:34
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:577
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:551
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:496
eval at ./boot.jl:235
[...]
```
The error occurs at the function `nomissing` defined as:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/v0.2.0/src/NCDatasets.jl#L1289

Could it be a bug in Julia 0.6.2 ?

**Comment by andreasnoack** [comment]
> Could it be a bug in Julia 0.6.2 ?

Yes it could very likely be the case. I wasn't aware that we didn't use 0.6.3 for CIBot.

**Pull request merged**
