### PR TITLE
Tag LazyQuery.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bramtayl/LazyQuery.jl](https://github.com/bramtayl/LazyQuery.jl)
Release: [v0.0.2](https://github.com/bramtayl/LazyQuery.jl/releases/tag/v0.0.2)
Diff: [vs v0.0.1](https://github.com/bramtayl/LazyQuery.jl/compare/e58692ea8e53e660ec67d18eb0f3d17feb780c1a...545ba98a747f9140789f66085b238bf452c353f0)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.0.2/requires
@@ -1,4 +1,4 @@
-julia 0.5
+julia 0.5 0.7
 DataFrames
 MacroTools
-LazyContext
+LazyContext 0.0.1 0.1.0
```
cc: @bramtayl

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
Tightening bounds needs to be done in place on the existing releases. I'd also avoid adding a julia upper bound.

**Comment by bramtayl** [comment]
I'm not sure how to do that? I wasn't aware you could edit already released versions.

**Comment by tkelman** [comment]
only the metadata requires files, don't touch the sha or git tag

**Comment by bramtayl** [comment]
The most recently published version worked on master at the time, and but I don't think it works on master now, even with an older LazyContext (still works on 0.5 and 0.6). So I can leave out the julia upper bound but CI will still fail, I think

**Comment by tkelman** [comment]
closing this since https://github.com/JuliaLang/METADATA.jl/pull/10013 makes it unnecessary

**Pull request closed without merging**
