### PR TITLE
Register MNISTDataset: v0.0.1 and Update IDXParser v0.1.1

### PR DESCRIPTION
**Pull request by Elzair**

### CODE REVIEW

**Comment by rened** [comment]
Hi, there is already an MNIST package - perhaps it would be better not to duplicate this functionality?

**Comment by IainNZ** [comment]
CC @johnmyleswhite

**Comment by IainNZ** [comment]
@Elzair maybe your package should be "the" MNIST package, can you contrast them?

**Comment by Elzair** [comment]
I will try that. Thanks.

**Pull request closed without merging**
