### PR TITLE
Register new package GCMFaces.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [gaelforget/GCMFaces.jl](https://github.com/gaelforget/GCMFaces.jl)
Release: [v0.1.1](https://github.com/gaelforget/GCMFaces.jl/releases/tag/v0.1.1)
cc: @gaelforget

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@gaelforget This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
What is GCM? Please spell out domain-specific abbreviations in package names.

**Comment by gaelforget** [comment]
Thanks @dpsanders for your comment. I spelled out the acronym in the package's README.md (see exert below). However, since `GCMFaces` is the name of the Matlab / Octave toolbox that inspired this package and is already familiar to a wide user community, I would really prefer not expanding to `GeneralCirculationModelFaces.jl` and stick with `GCMFaces.jl`. I hope this is agreeable.

### Package Name

GCM is an acronym that stands for General Circulation Model, or Global Climate Model, as discussed in [this wikipedia entry](https://en.wikipedia.org/wiki/General_circulation_model). The name for `GCMFaces.jl` derives from the `Matlab / Octave` package introduced in [Forget et al., 2015](http://www.geosci-model-dev.net/8/3071/2015/), `doi:10.5194/gmd-8-3071-2015` which inspired this `Julia` package.

**Comment by dpsanders** [comment]
In my opinion, `GeneralCirculationModelFaces.jl` is a much better name.

**Comment by dpsanders** [comment]
(Actually, I'm not sure what "faces" means here, either.)

**Comment by gaelforget** [comment]
I guess `face` is jargon for `array` or `mesh`. Thanks for making me rethink this package's name. I am going to take it in a different direction, if that's ok, and use `MeshArrays` as a name. This new name better reflects what the package does, and what it is intended to do in more general fashion later on, rather than where it came from. 

Could you please provide guidance w.r.t. how I should proceed with the package name change? I am new to this and confused about the "attobot" part in particular. If I just rename the repo in `GitHub` and then change the name in `Project.toml` does that propagate through the system? Or maybe I need to regenerate tests & coverage badges and then a new tag?

**Comment by dpsanders** [comment]
Don't use Project.toml yet, just REQUIRE.
You will need to rename the repo and then make a new release for Attobot to pick up.
Just leave a comment here asking for this one to be closed.

**Comment by gaelforget** [comment]
ok. Please close this PR. I will rename the package and generate another one. Thanks

**Pull request closed without merging**
