### PR TITLE
Tag IterableTables.jl v0.5.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidanthoff/IterableTables.jl](https://github.com/davidanthoff/IterableTables.jl)
Release: [v0.5.1](https://github.com/davidanthoff/IterableTables.jl/releases/tag/v0.5.1)
Travis: [Travis Build Status](https://travis-ci.org/davidanthoff/IterableTables.jl/builds/270274252)
Diff: [vs v0.5.0](https://github.com/davidanthoff/IterableTables.jl/compare/5dd87776d4f3629692579fe49e9fe76b9809d2ea...301dd32654993f707268bd5b8abf45403845883b)
`requires` vs v0.5.0: no changes
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by davidanthoff** [comment]
@shashi Here we go, would be great if you could tag an IndexedTables.jl version as well.

**Comment by shashi** [comment]
#10997 I was hoping I could change the base branch of that PR to this one...

**Comment by shashi** [comment]
@simonbyrne

**Comment by shashi** [comment]
If attobot merges this https://github.com/attobot/METADATA.jl/pull/1 then it will work.

**Comment by tkelman** [comment]
Why do they need to be simultaneous?

**Comment by davidanthoff** [comment]
We moved the iterable tables integration code for IndexedTables.jl from behind a ``@require`` block in IterableTables.jl into IndexedTables.jl (without a dependency on Requires.jl and no more type-piracy). We can't make sure that the pre-move versions of IterableTables.jl and IndexedTables.jl and the post-move versions end up in pairs on a user machine because we can't enforce any versions bounds on things that are handled via Requires.jl. So it would be nice if those two packages simply had a release roughly at the same time, and then things should be fairly smooth for users.

**Comment by tkelman** [comment]
so https://github.com/attobot/METADATA.jl/pull/1 isn't strictly necessary as long as they're merged roughly around the same time?

**Comment by davidanthoff** [comment]
Yeah, I think roughly merging at the same time would be fine.

**Comment by davidanthoff** [comment]
Bump, can we get this and the corresponding IndexedTables.jl thing merged?

**Comment by tkelman** [comment]
There's an odd CIBot failure on IndexedTables, and one with FeatherFiles here, that should be looked into

**Comment by davidanthoff** [comment]
I think we should just merge this. I looked through the JuliaCIBot failures and they seem all unrelated or actually caused by the chicken-egg problem that we need to tag this here and the corresponding IndexedTables.jl version at the same time.

**Comment by tkelman** [comment]
Did you look at FeatherFiles? That's not in the most recent run.

**Comment by davidanthoff** [comment]
Everything Feather related seems to pass locally and on travis and appveyor, so I'd say we can ignore that for now, and if it shows up in the wild again we'll fix it then.

**Pull request merged**
