### PR TITLE
Tag Missings.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaData/Missings.jl](https://github.com/JuliaData/Missings.jl)
Release: [v0.3.0](https://github.com/JuliaData/Missings.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaData/Missings.jl/builds/413002359)
Diff: [vs v0.2.10](https://github.com/JuliaData/Missings.jl/compare/408d238873f41e73239310f88f40e303bb0cb46b...a496e12109aa7cd7686230ef999c9479e08e66b4)
`requires` vs v0.2.10: 
```diff
--- 0.2.10/requires
+++ 0.3.0/requires
@@ -1,2 +1 @@
-julia 0.6
-Compat 0.59.0
+julia 1.0-
```
cc: @quinnj

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Can't this be made to work on 0.7?

**Comment by quinnj** [comment]
It's been working fine on 0.7. This just bumps it to 1.0.

**Comment by andreasnoack** [comment]
Why not just set the requirement to 0.7-rc2?

**Comment by quinnj** [comment]
There's already a valid release for 0.7-rc2; this is just signaling that the package has been tested and works on 1.0.

**Comment by andreasnoack** [comment]
I don't really see why you'd want to do that but it's your call.

**Comment by cstjean** [comment]
> There's already a valid release for 0.7-rc2; this is just signaling that the package has been tested and works on 1.0.

I would have appreciated to have a single Manifest for my project that works on both 0.7 and 1.0. It would make the transition easier. 

EDIT: I see that many other packages have done the same; nevermind.

**Pull request merged**
