### PR TITLE
Register new package OMGP.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [theogf/OMGP.jl](https://github.com/theogf/OMGP.jl)
Release: [v0.3.1](https://github.com/theogf/OMGP.jl/releases/tag/v0.3.1)
Travis: [Travis Build Status](https://travis-ci.org/theogf/OMGP.jl/builds/446184724)
cc: @theogf

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@theogf This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use acronyms in package names.

**Comment by theogf** [comment]
Ok, I will change it to AugmentedGaussianProcesses.jl, do you recommend that I create a completely new Github repository or change the name of the actual one?

**Comment by andreasnoack** [comment]
Just change the name of the current repo and update the names in the source files.

**Comment by theogf** [comment]
I already took the initiative to do so. Can you manage the change for the PR?

**Comment by andreasnoack** [comment]
Just delete the tag and reapply it. That should open a new PR (because of the name change). I'll close this one.

**Pull request closed without merging**
