### PR TITLE
Tag WebSockets.jl v0.3.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaWeb/WebSockets.jl](https://github.com/JuliaWeb/WebSockets.jl)
Release: [v0.3.2](https://github.com/JuliaWeb/WebSockets.jl/releases/tag/v0.3.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaWeb/WebSockets.jl/builds/303959494)
Diff: [vs v0.3.0](https://github.com/JuliaWeb/WebSockets.jl/compare/78987bdcc58950b2a314ffff9e93da9f041e1bc8...e69a981c50273ab0aa5890e177b628db81f2fb65)
`requires` vs v0.3.0: no changes
cc: @hustf

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Do you really want to continue supporting 0.4? We've frozen the METADATA for 0.4

**Comment by hustf** [comment]
Thank you for going throughthis.
No changes have been made to the actual package here (just the tests), and
0.7 is not supported because HttpCommon did not build on 0.7.
When the upstream packages starts supporting 0.7, it's time for a new
revision, which will exclude 0.4. If metadata 0.4 is frozen, I suggest you
do not update.
Best regards,
Frøystein Hustadnes

**Comment by hustf** [comment]
P.S. Tests will not work on 0.4. That's another reason for not updating 0.4
metadata with this.

**Comment by aviks** [comment]
> P.S. Tests will not work on 0.4

Yes, that is true for most packages, and that is the reason for freezing 0.4 tags. Closing this, please let us know if anything changes.

**Pull request closed without merging**
