### PR TITLE
Tag RobotOS v0.3.1

### PR DESCRIPTION
**Pull request by phobon**

### CODE REVIEW

**Comment by tkelman** [comment]
Did you do `git push --tags`? Helps to have the tags visible in the releases tab on github

**Comment by phobon** [comment]
That must have been because I didn't run `Pkg.publish()` this time (it
generally ends up failing for me). It's there now.

**Comment by tkelman** [comment]
Ah, cool. What's the failure? Or if you're running it from 0.3, it's known to be really slow. It's much better on 0.4.

**Comment by phobon** [comment]
I'm pretty sure it was on 0.4 but I don't remember the error at all. I'll
make sure to take note of it next time I try.

**Pull request merged**
