### PR TITLE
Tag ASTInterpreter2.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Keno/ASTInterpreter2.jl](https://github.com/Keno/ASTInterpreter2.jl)
Release: [v0.1.1](https://github.com/Keno/ASTInterpreter2.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/Keno/ASTInterpreter2.jl/builds/305008622)
Diff: [vs v0.1.0](https://github.com/Keno/ASTInterpreter2.jl/compare/ee2e55fe8ef28240490c222f050b0699f573858a...cc05800c0948ff653849042f5f68e11634e7f002)
`requires` vs v0.1.0: no changes
cc: @Keno

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by kshyatt** [comment]
Closed/reopened to get CI to rerun

**Comment by aviks** [comment]
`ASTInterpreter2` tests fail with

```
Stacktrace:
 [1] _compare(::Array{UInt8,1}, ::Array{UInt8,1}) at /mnt/pkgevalempty/7ca93ecc14b11ca33e2735ee11d0cc2cfda3f312/ASTInterpreter2/.julia/v0.6/VT100/test/TerminalRegressionTests.jl:119
 [2] compare(::VT100.ScreenEmulator, ::String, ::String) at /mnt/pkgevalempty/7ca93ecc14b11ca33e2735ee11d0cc2cfda3f312/ASTInterpreter2/.julia/v0.6/VT100/test/TerminalRegressionTests.jl:132
 [3] macro expansion at /mnt/pkgevalempty/7ca93ecc14b11ca33e2735ee11d0cc2cfda3f312/ASTInterpreter2/.julia/v0.6/VT100/test/TerminalRegressionTests.jl:165 [inlined]
 [4] (::TerminalRegressionTests.##10#13{Array{String,1},TerminalRegressionTests.EmulatedTerminal,Array{String,1},Array{String,1},Condition})() at ./task.jl:335ERROR: LoadError: LoadError: 
Stacktrace:
 [1] try_yieldto(::Base.##296#297{Task}, ::Task) at ./event.jl:189
 [2] wait() at ./event.jl:234
 [3] wait(::Condition) at ./event.jl:27
 [4] #automated_test#7(::Bool, ::Function, ::##3#5, ::String, ::Array{String,1}) at /mnt/pkgevalempty/7ca93ecc14b11ca33e2735ee11d0cc2cfda3f312/ASTInterpreter2/.julia/v0.6/VT100/test/TerminalRegressionTests.jl:174
 [5] automated_test(::Function, ::String, ::Array{String,1}) at /mnt/pkgevalempty/7ca93ecc14b11ca33e2735ee11d0cc2cfda3f312/ASTInterpreter2/.julia/v0.6/VT100/test/TerminalRegressionTests.jl:136
 [6] include_from_node1(::String) at ./loading.jl:569
 [7] include(::String) at ./sysimg.jl:14
 [8] include_from_node1(::String) at ./loading.jl:569
 [9] include(::String) at ./sysimg.jl:14
 [10] process_options(::Base.JLOptions) at ./client.jl:305
 [11] _start() at ./client.jl:371
while loading /mnt/pkgevalempty/7ca93ecc14b11ca33e2735ee11d0cc2cfda3f312/ASTInterpreter2/.julia/v0.6/ASTInterpreter2/test/ui.jl, in expression starting on line 29
while loading /mnt/pkgevalempty/7ca93ecc14b11ca33e2735ee11d0cc2cfda3f312/ASTInterpreter2/.julia/v0.6/ASTInterpreter2/test/runtests.jl, in expression starting on line 7
```

**Comment by Keno** [comment]
terminal tests are hard. I should probably tag a new VT100, which is a bit better at making sure to globble up all output from the kernel buffers.

**Comment by KristofferC** [comment]
> oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"

Let's try again...

**Pull request merged**
