### PR TITLE
Tag ImageQuilting v0.2.4 [git://github.com/juliohm/ImageQuilting.jl.git]

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by tkelman** [comment]
Combinatorics 0.3.1 is julia 0.5-only.

**Comment by juliohm** [comment]
@tkelman what should I do to REQUIRE it only for v0.5-? I did the check in the code, but it seems I also have to insert a condition in the REQUIRE file itself.

**Comment by juliohm** [comment]
@tkelman removing the 0.3.1 in the Combinatorics 0.3.1 would solve the problem?

**Comment by tkelman** [comment]
yes that would be fine

**Comment by juliohm** [comment]
@tkelman done. Could you please merge this one?

**Comment by tkelman** [comment]
Sure. You may want to put release back in https://github.com/juliohm/ImageQuilting.jl/blob/master/.travis.yml now that release is 0.4.

**Comment by juliohm** [comment]
Thank you @tkelman, I'm saving the bot to build the latest master only. The build for the 0.4 is indirectly checked by Julia tests: http://pkg.julialang.org/?pkg=ImageQuilting&ver=0.4#ImageQuilting

**Comment by tkelman** [comment]
I *really* wouldn't worry about "saving the bot." Julia 0.4 and 0.5-dev are growing increasingly different, and passing tests on one is no guarantee of passing tests on the other. Travis, unlike PackageEvaluator, runs your tests on the development master branch of your package *before* you tag versions and potentially expose users to accidentally updating to code that may not work.

**Comment by juliohm** [comment]
That is true, I'll add `release` to Travis in future commits. Thanks.

**Pull request merged**
