### PR TITLE
Tag JLD v0.6.10 [https://github.com/JuliaIO/JLD.jl]

### PR DESCRIPTION
**Pull request by jrevels**
ref https://github.com/JuliaIO/JLD.jl/pull/142

@StefanKarpinski Is there a reason why you were waiting on me to tag this as opposed to doing so yourself (it seems that you, @JeffBezanson, and @tkelman all have commit access to JLD)?

### CODE REVIEW

**Comment by tkelman** [comment]
looks like the test failure on 32 bit is real here, hold on

**Comment by tkelman** [comment]
we could probably backport the simple renaming to a branch based off the last tag, to avoid releasing a version with test failures

**Comment by ararslan** [comment]
I made a branch `backport-rename` based on the v0.6.9 tag with Stefan's commit cherry-picked.

**Comment by tkelman** [comment]
Shall we delete this version of the 0.6.10 tag and make a new one from backport-rename instead then? Is attobot on for JLD?

**Comment by ararslan** [comment]
That sounds like a good plan to me. And yes, it appears Attobot is enabled for all of JuliaIO.

**Comment by jrevels** [comment]
I deleted the v0.6.10 tag in https://github.com/JuliaIO/JLD.jl. I'll let somebody who's more involved with this endeavor do whatever other tagging/releasing is required.

**Pull request closed without merging**
