### PR TITLE
MolecularDataType.jl

### PR DESCRIPTION
**Pull request by yuhangwang**
I would like to register a new Julia package: MolecularDataType.jl. Thanks.

### CODE REVIEW

**Comment by tkelman** [comment]
Please rebase and squash this to remove all unnecessary commits.

Would your tests pass on Travis CI if you enabled it?

**Comment by yuhangwang** [comment]
Travis CI showed all checks passed for my fork of METATA.jl. I have also done the rebase and squash as you suggested. I also added second package "MolecularPDB" which depends on "MolecularDataType". Do I need to add the second one after the pull request of the first one is accepted?

**Comment by yuhangwang** [comment]
I have also added a Travis CI build status link to MolecularDataType.jl repository.

**Comment by tkelman** [comment]
It would be preferable to do one package registration at a time, and one commit per package registration (at most 2).

**Comment by yuhangwang** [comment]
Sorry about the "closed" status. Somehow github automatically closed the pull request when I did "git reset --hard origin/metadata-v2" which force my fork to loose the all commits I made. I have initiated another pull request to simplify everything (with only one new commit that added my package". Please discard this pull request. Thanks.

**Pull request closed without merging**
