### PR TITLE
Register EzXML [https://github.com/bicycle1885/EzXML.jl.git]: v0.0.1

### PR DESCRIPTION
**Pull request by bicycle1885**
Another libxml2-based package with consistent APIs, automatic memory management, XPath support, etc.

https://github.com/bicycle1885/EzXML.jl

### CODE REVIEW

**Comment by nalimilan** [comment]
Just curious, what's the difference with LightXML.jl? Could these packages be merged at some point, or should one replace the other?

**Comment by bicycle1885** [comment]
There are many differences:
* Documents and XML trees will be garbage collected.
* Simpler types: `Document` and `Node` only.
* Attribute values can be accessed like a dictionary.
* Namespace support.
* XPath support.

Not sure whether people love EzXML.jl but I believe EzXML.jl will supersede LightXML.jl.

**Comment by nalimilan** [comment]
OK, thanks. Then why not call it LibXML2.jl?

**Comment by bicycle1885** [comment]
Because there is no reason to do so; EzXML.jl is not a legitimate successor of LightXML.jl and there is no shared code between them.

**Comment by nalimilan** [comment]
Note I said LibXML2.jl, not LightXML2.jl. Using the name of the wrapped library is classic for Julia packages.

**Comment by bicycle1885** [comment]
Ah, sorry. My eyes are slippy because it's already 7 p.m. here.
LibXML2 is okay, but I'm not willing to wrap all features of libxml2.

**Comment by bicycle1885** [comment]
Ping. Is there any reason not to merge?

**Comment by tkelman** [comment]
There is a pre-existing C library also called ezxml http://ezxml.sourceforge.net, might be a bit confusing that this is based on a different library?

**Comment by bicycle1885** [comment]
Oh, no. I didn't realize it. Maybe I need to rename my package HardXML.jl or something. But the C library is not so common and looks almost abandoned (no updates for 5 years).

**Comment by tkelman** [comment]
nevermind, should have checked the dates there

**Comment by bicycle1885** [comment]
Thank you!

**Pull request merged**
