### PR TITLE
Tag BIGUQ.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [madsjulia/BIGUQ.jl](https://github.com/madsjulia/BIGUQ.jl)
Release: [v0.5.0](https://github.com/madsjulia/BIGUQ.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/madsjulia/BIGUQ.jl/builds/432280659)
Diff: [vs v0.4.0](https://github.com/madsjulia/BIGUQ.jl/compare/781f3d414179f5901021351e03b43710f66fb19c...84c14c0a72611de34be815fed14dfe793f01a4ce)
`requires` vs v0.4.0: no changes
cc: @montyvesselinov

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by montyvesselinov** [comment]
0.7 has passed

**Comment by andreasnoack** [comment]
According to your REQUIRE, it should work on Julia 1.0.

**Comment by montyvesselinov** [comment]
oops. i will fix it.

**Comment by montyvesselinov** [comment]
Actually, all the past BIGUQ tagged versions in METADATA.jl are committed without upper bound 1.0.

So even if this version REQUIRES

```
julia 0.6 1.0
```

this is not going to help. A much older version will get in 1.0. So I do not think we can do anything here.

**Comment by andreasnoack** [comment]
Continuing having the wrong bound isn't a good solution. You can add bounds on the previously released versions to improve the situation.

In addition, not adding bounds require me to manually merge this PR instead of this being automatic. Please try to help to make the process of maintaining METADATA as simple as possible.

**Comment by andreasnoack** [comment]
Actually, the conversion script to the registry now adds the bound for the older versions so just adding it here might be sufficient.

**Pull request merged**
