### PR TITLE
Register new package OpenStreetMap2.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliusgeo/OpenStreetMap2.jl](https://github.com/juliusgeo/OpenStreetMap2.jl)
Release: [v0.0.1](https://github.com/juliusgeo/OpenStreetMap2.jl/releases/tag/v0.0.1)
cc: @juliusgeo

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@juliusgeo This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by juliusgeo** [comment]
I tried to fix my REQUIRE file so that the JuliaCI will pass now.

**Comment by andreasnoack** [comment]
According to the project file the name is `OpenStreetMapParser2`. I suspect that is the reason why it fails.

**Comment by visr** [comment]
Love all the OpenStreetMap interest, and I understand you started afresh since the original https://github.com/tedsteiner/OpenStreetMap.jl has not seen a commit in years.

But there are also two newer packages, both not registered yet though:
- https://github.com/yeesian/OpenStreetMap2.jl
- https://github.com/pszufe/OpenStreetMapX.jl

The latter is the newest and is actively being developed, it was mentioned here as well:
https://discourse.julialang.org/t/package-for-map-visualizations/1875/28

Would it make sense to join forces? Also tagging @yeesian since I'm not sure if he still planned on registering OpenStreetMap2.jl. And then I might as well tag @pszufe :)

**Comment by yeesian** [comment]
Thanks visr! Personally, I do not have plans to register yeesian/OpenStreetMap2 anytime soon, and will be happy to contribute to other packages if that might make more sense.

**Comment by yeesian** [comment]
Taking a broader view, I think the surface area of OpenStreetMap (io,plots,routing,etc) is so wide, that there is scope for a lot of packages to each be overlapping in some functionality, yet providing other unique features that their maintainers deem of importance (while disregarding the rest).

It is a little unfortunate that there is no common base of data structures for us to collectively build on top of yet, but their design might also be made easier if we have a better sense of the tasks people are using OSM for, so it might make for a richer ecosystem to encourage experimentation for now, and have a more concerted attempt at unifying them when there's a real need/demand for it.

**Comment by pszufe** [comment]
https://github.com/pszufe/OpenStreetMapX.jl  is a Julia 1.0 + more modern dependencies rewrite of https://github.com/tedsteiner/OpenStreetMap.jl where all original functionality is working (if it does not raise a github issue)

Regarding differences between juliusgeo/OpenStreetMap2.jl vs the original tedsteiner/OpenStreetMap.jl - it seems that @juliusgeo package is oriented towards nice plotting while tedsteiner/OpenStreetMap.jl and yeesian/OpenStreetMap2.jl are oriented towards processing map data and routing. And the medium term development goal of OpenStreetMapX.jl is to provide multi-agent simulation framework for modelling of smart cities (and we have research grants for that so it *will be* created). Joining the forces is always welcome.

Honestly, while any new Julia project is welcome, OpenStreetMap2.jl name for @juliusgeo package will be just confusing. When I was starting OpenStreetMapX my first idea for the name was OpenStreetMap2 but than I found @yeesian project so and I simply changed the name.

**Comment by juliusgeo** [comment]
@yeesian I did not see your package, otherwise I would not have taken the same name haha. 
@pszufe You are right my package is more oriented towards nice plotting (and also geojson export of map data). Do you think that a package name of OpenStreetMapPlotter.jl would be sufficiently distinct to avoid confusion? 

I think that it might make sense for my package to stay distinct because it has different focuses that may not be needed by other projects, and because mine uses Winston.jl which has a whole host of dependencies with it.

**Comment by pszufe** [comment]
@juliusgeo , actually one of many functions that we rewrite OpenStreetMap.jl was using Winston.jl for plotting. At the time we did it Winston.jl did not work in Julia 0.7. Perhaps now it works :-)
We have rewritten the former OpenStreetMap.jl functionality to https://github.com/pszufe/OpenStreetMapXPlot.jl  We used Plots.jl for easy change of backends - however those plots are not as beautiful as  yours (probably worse choice of colors and we did not buildings etc). Talking about "combining forces" in the area of plotting - the feature I would love to see is some form of integration of Julia with QGIS https://qgis.org/en/site/

**Comment by juliusgeo** [comment]
@pszufe I believe that Winston.jl has only recently begun to support Julia 1.0--I actually had to wait a little bit for it to be supported before starting my project. Now that I am looking at it, I think that Plots.jl might have better code for supporting drawing polygons, which is the main issue that I had with Winston.jl. There are some artifacts that are created in exported .svg images using my code at certain render distances that I think are caused by me having to use Winston.jl's FillBetween function because there is no proper FillPolygon function that I could find.

I think that integration with QGIS would be super cool--one of the reasons why I wrote code to export to GeoJSON format was so that then I could open up map files in QGIS. However, I'm sure there is some way to do this more directly.

**Comment by pszufe** [comment]
QGIS uses Python for scripting, however I found it hard to configure QGIS with Anaconda (and PyCall.jl uses Anaconda). It would be really worth looking into that.

**Comment by juliusgeo** [comment]
@pszufe @visr @yeesian 
I think I will rename my package to OpenStreetMapPlotter.jl and I will focus on creating pretty graphs using Winston and also on exporting the map files to QGIS, and then there will be minimal overlap of features. In addition, I think it might be useful to have one central OpenStreetMap plotting package that then other packages can use as a backend for plotting rather than having to reinvent the plotting wheel each time. Thoughts?

**Comment by yeesian** [comment]
I'll like that very much :)

If you're interested in some pointers, I had envisioned a future where we might be able to take in a style spec like
* [CartoCSS](https://github.com/mapbox/carto) (some words on it [here](https://macwright.org/2012/11/02/css-for-maps.html) and [here](https://blog.mapbox.com/the-end-of-cartocss-da2d7427cf1)), or
* [Mapbox GL Style](https://openmaptiles.org/styles/) with an opensource editor in [Maputnik](https://github.com/maputnik/editor). (For a free basemap style, you might also be interested in [OSM Liberty](https://github.com/maputnik/osm-liberty). There is [a few more](https://openmaptiles.org/styles/) by OpenMapTiles.)

and produce themes in [PlotThemes.jl](https://github.com/JuliaPlots/PlotThemes.jl) and/or [MakieThemes.jl](https://github.com/JuliaPlots/MakieThemes.jl)

There was an project that offers freely downloadable OSM vector tiles, and a set of open-source tools for use and generating of the maps called [OSM2VectorTiles](https://openmaptiles.org/osm2vectortiles/). It has been succeeded by [OpenMapTiles](https://openmaptiles.org/).

I had taken a very small stab at reading vectortiles in https://github.com/yeesian/MapTiles.jl but have not had time to work on it since.

**Comment by yeesian** [comment]
Since we're on the topic of openstreetmap, I might as well also mention that there's been a rich and growing area of activity in building [stable, non-proprietary IDs and data standards for streets](https://github.com/sharedstreets/sharedstreets-ref-system). It's unclear how it should fit in with everything, but it's going to be helpful (for simulations/analysis/routing/etc) to have ways of ingesting and working with real-world data on road speeds in the future (rather than [hardcoding some values](https://github.com/pszufe/OpenStreetMapX.jl/blob/adcec98e289222b013ccc15d9fc73b09c99328fd/src/speeds.jl#L5-L24)).

**Comment by juliusgeo** [comment]
@yeesian I like the idea of being able to use theme files from CartoCSS or Mapbox GL Style. I will look into seeing if that can fit into how Winston.jl plots things. I will also take a look at using Plot.jl--It looks like it might be a little bit more flexible than Winston.jl.

I am not sure if it would be possible to use them to create themes that would be compatible with PlotThemes.jl as it doesn't seem like there is a good way to distinguish between different types of lines in those themes -- right now I just have a massive dictionary that stores the different styles I have selected for every different type of way. However, I think it would definitely be valuable to have some way to define maybe a few "key" colors and then have the rest of the colors made based on a formulation of those so it doesn't take as much work to customize the styling.

**Comment by pszufe** [comment]
To give a full picture. I use currently for map visualization the following tools:

- Leaflet: https://leafletjs.com/  I access it via R https://github.com/rstudio/leaflet   Works like a charm. I use Julia and OpenStreetMapX.jl for data processing and then vitalize in R. 
- QGIS - no good automated integration (Python issues) but this is very powerful tool if the amount of graphics is huge
- Plots.jl (via OpenStreetMapXPlot.jl) - "time to first graph" is killing me. I am waiting for Julia to include natively compiled versions of plotting packages. Last but not least Plots.jl does not support scaling of graphics in a nice way such as Leaftlet or QGIS do

Here is the list of things I would love to have:
- Leaflet.jl  (@yeesian seems you were working on it. does it work?)
- QGIS.jl   - maybe could be developed with PyCall?
- nice vector scalable Julia-native graphics

**Comment by visr** [comment]
Sounds like a good plan @juliusgeo. Happy to see good discussion here, even up to making roadmaps for the future. Perhaps we should continue the discussion at https://discourse.julialang.org/c/domain/geo?

**Comment by andreasnoack** [comment]
Great that you coordinate the packages. It sounds right to continue the discussion on Discourse. I'll close this PR. You can just open new ones when you have settled on the names and content.

**Pull request closed without merging**
