### PR TITLE
Tag PtFEM.jl v0.1.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [PtFEM/PtFEM.jl](https://github.com/PtFEM/PtFEM.jl)
Release: [v0.1.3](https://github.com/PtFEM/PtFEM.jl/releases/tag/v0.1.3)
Travis: [Travis Build Status](https://travis-ci.org/PtFEM/PtFEM.jl/builds/393056816)
Diff: [vs v0.1.1](https://github.com/PtFEM/PtFEM.jl/compare/bcd1a0d044869c42d6ad9f809b321e5d1949ca62...30ed78b62888e1583acdd077346dcd5ff48acab8)
`requires` vs v0.1.1: 
```diff
--- 0.1.1/requires
+++ 0.1.3/requires
@@ -1,5 +1,5 @@
 julia 0.7-
-Compat 0.17
+Compat 0.68.0
 Documenter
 Interpolations
 OffsetArrays
@@ -7,3 +7,4 @@
 DataFrames
 Plots
 GR
+CustomUnitRanges
```
cc: @goedman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Does this supersede #15197?

**Comment by goedman** [comment]
Yes, I have never figured out how to update an existing request in attobot.

**Comment by andreasnoack** [comment]
> Yes, I have never figured out how to update an existing request in attobot.

You remove the old release and tag and make a new release with the same version. It looks like you managed to do it in https://github.com/JuliaLang/METADATA.jl/pull/15197#issuecomment-397808665.

**Comment by andreasnoack** [comment]
Is this one still relevant now that v0.1.2 has been merged?

**Comment by goedman** [comment]
I will delete the release and the tag. An interesting test once I’ll attempt the next release.

0.1.2 solved my problem with Pkg(3) as BHAtp.jl (using and re-exporting PtFEM) now builds on Travis and Appveyor. It kept on referring to versions in my local registry that were not present in Travis and Appveyor.

Right now specifying Julia 0.7 as a lower bound seems to be accepted on Julia 0.7-. Which was the only change in 0.1.3.

Thanks again for your help.

**Comment by andreasnoack** [comment]
You are welcome. I think the reason 0.7 in the REQUIRE is not a problem is that Pkg3 doesn't use REQUIRE anymore.

**Pull request closed without merging**
