### PR TITLE
Tag PolynomialFactors.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jverzani/PolynomialFactors.jl](https://github.com/jverzani/PolynomialFactors.jl)
Release: [v0.2.0](https://github.com/jverzani/PolynomialFactors.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/jverzani/PolynomialFactors.jl/builds/414942520)
Diff: [vs v0.1.0](https://github.com/jverzani/PolynomialFactors.jl/compare/1c3e0d5da6c7dae7f621b1722feae36baec0c269...4f9a17222196c4f54de7dc46f9b29b53a0308e88)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,5 +1,5 @@
-julia 0.6
-Polynomials 0.1.1
-Compat 0.17.0
+julia 0.7
+AbstractAlgebra 0.0.6
 Combinatorics 0.4.1
 Primes 0.1.1
+Compat 0.62.0
```
cc: @jverzani

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like tests are failing on Julia 1

**Comment by jverzani** [comment]
Yes, that's due to AbstractAlgebra not having cleared up its deprecations. Should I change the CI until that gets taken care of?

**Comment by andreasnoack** [comment]
It depends on how urgent it is to get the release out. I'd recommend waiting for the dependencies to get ready first before making the new release. People will mostly be using Julia 1.0 now so a new release won't work before all dependencies are ready anyway.

**Comment by jverzani** [comment]
There is no urgency. Is it better to cancel this then or just let it sit in the queue? I would think easier for you to cancel.

**Comment by andreasnoack** [comment]
I think it is fine to keep this open. Once the dependencies are ready, you can update the REQUIRE, remove the existing tag and reapply it. Then this PR will automatically get updated.

**Comment by andreasnoack** [comment]
Bump. It looks like AbstractAlgebra has been updated.

**Pull request merged**
