### PR TITLE
Tag SPH.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rkat/SPH.jl](https://github.com/rkat/SPH.jl)
Release: [v1.0.0](https://github.com/rkat/SPH.jl/releases/tag/v1.0.0)
Diff: [vs v0.0.1](https://github.com/rkat/SPH.jl/compare/eeb3a883e02c5634513c2bed108ed8fc23dc45a1...ad9941f850634fcf301413619984595ca56e15ec)
`requires` vs v0.0.1: no changes
cc: @rkat

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please enable travis testing for your package and add the test badge to your README such that it is easy to check the test status for your package. Thanks.

**Comment by rjkat** [comment]
Done! I have updated the v1.0.0 tag in the repository. Is this the correct thing to do or should I make a 1.0.1 release?

**Comment by andreasnoack** [comment]
I'd recommend that you remove the project and manifest files from your repository. They are not yet needed and they currently break our reverse dependency testing.

**Comment by andreasnoack** [comment]
You'd need to bump the julia requirement in REQUIRE if this only targets Julia 1.0

**Comment by rjkat** [comment]
That’s a bit sad. Do you need a hand to fix the tests? 

Also it’s pretty difficult to find information on how best to upgrade packages to Julia 1.0. If there is a page I couldn’t find it. I'd be happy to help write some documentation. 

In the meantime I’ll remove the files.

**Comment by rjkat** [comment]
Wait so REQUIRE is still used by Julia 1? That’s surprising.

**Comment by andreasnoack** [comment]
Yes. The REQUIRE file is still the foundation for METADATA. Once we migrate away from METADATA, it will no longer be needed.

**Comment by rjkat** [comment]
@andreasnoack let me know if there’s anything else I need to do on this one

**Pull request merged**
