### PR TITLE
Pull request/19845a6e

### PR DESCRIPTION
**Pull request by fairbrot**

### CODE REVIEW

**Comment by IainNZ** [comment]
Hi @fairbrot,
Looks like a neat package. Two things:
* The name. There is a preference to [err on the side of clarity](http://docs.julialang.org/en/latest/manual/packages/#guidelines-for-naming-a-package), so `GaussianProcesses.jl` would be a really great choice for a name.
* Tagging. You actually need to tag a version to be able to `Pkg.add` a package. This can be done after registration or at the same time.

**Comment by kmsquire** [comment]
Is this meant to be the canonical Gaussian Process package?  If not necessarily, then it might not be good to take that name.

**Comment by kmsquire** [comment]
It might also be fine.  There are many possible ways to implement decision trees, and one of them happens to be implemented in the DecisionTrees.jl package.

**Comment by ViralBShah** [comment]
I think the generic name is ok here.

**Comment by ViralBShah** [comment]
I mean `GaussianProcesses` is ok.

**Comment by johnmyleswhite** [comment]
I think names like `GaussianProcesses` are fine if we develop some community standards that reflect who owns what. If we allow some kind of eminent domain rulings on names like `DataFrames` or `Stats`, then the names are safe to use.

**Comment by fairbrot** [comment]
Hi everyone, thanks for the feedback. We're happy to change the name of the package to GaussianProcesses. We'll update this over the next few days,

**Comment by fairbrot** [comment]
Pull request has been recreated at #2561

**Pull request closed without merging**
