### PR TITLE
Tag Mixers.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rafaqz/Mixers.jl](https://github.com/rafaqz/Mixers.jl)
Release: [v0.1.0](https://github.com/rafaqz/Mixers.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/rafaqz/Mixers.jl/builds/423911052)
Diff: [vs v0.0.2](https://github.com/rafaqz/Mixers.jl/compare/6651d74b31f76f7f49d9d141f44104dd71d6fa54...067a2edc758559907aa7c9243a29e3a8072de5aa)
`requires` vs v0.0.2: 
```diff
--- 0.0.2/requires
+++ 0.1.0/requires
@@ -1,2 +1,2 @@
-julia 0.6
-MacroTools 0.4.0
+julia 0.7
+MacroTools
```
cc: @rafaqz

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please remove the stdlib `Test` from your `test/REQUIRE` file.

**Comment by rafaqz** [comment]
Oops.

Test removed, tag commit updated.

**Comment by andreasnoack** [comment]
The PR doesn't seem to have been updated. Did you completely remove the release and tag before reapplying the tag?

**Comment by rafaqz** [comment]
I did it on the command line but not github... apologies I'm still a bit vague on this process and what triggers attotbot.

**Pull request merged**
