### PR TITLE
Bump CSV

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by tkelman** [comment]
Git tag (https://github.com/JuliaDB/CSV.jl/releases) doesn't match the sha here? And just as a matter of safety, could you push PR branches to your fork and make PR's from there?

**Comment by quinnj** [comment]
What are the ramifications for not matching (they're off by just a commit)? And what should I do about it? It doesn't seem like I can edit the github release. Just bump another version?

**Comment by tkelman** [comment]
Not a big deal, but I think it should be possible to clean up by replacing the tag.

**Comment by quinnj** [comment]
Cool. I feel like it was a good walk around the block on updating packages again and I'm refreshed on all the ins and outs to keep in sync. I'll just my own fork next time too.

**Pull request merged**
