### PR TITLE
New Pkg GeoEfficiency

### PR DESCRIPTION
**Pull request by DrKrar**

### CODE REVIEW

**Comment by DrKrar** [comment]
This package represent a good addition to help researcher in the radiation field to calculate geometrical efficiency fast and accurate.

**Comment by tkelman** [comment]
That's an interesting version number to start with! Looks okay, though note your readme appveyor badge link points to https://ci.appveyor.com/project/wildart/pkgdev-jl/branch/master. Do your tests pass if you enable Travis CI?

**Comment by DrKrar** [comment]
sorry, can i fix this later or should I begin a new pull request.

**Comment by tkelman** [comment]
You can fix this later. This PR is good as is I think, let's just leave this open for a while longer in case anyone else has any comments.

**Comment by DrKrar** [comment]
the version number come with the program from python where i had started developing the package.

**Pull request merged**
