### PR TITLE
Register ODEInterface: v0.0.1

### PR DESCRIPTION
**Pull request by luchr**

### CODE REVIEW

**Comment by tkelman** [comment]
Hiya. Your repository name should end in `.jl` to fit the established convention. Note that if you're redistributing source code written by other authors, your package's license file needs to mention the license statement of the existing code: http://www.unige.ch/~hairer/prog/licence.txt

**Comment by luchr** [comment]
I am very sorry for using the wrong naming scheme. I've created a new repository and I've added the additional license informations in LICENSE.md. 
Here is the new pull request: https://github.com/JuliaLang/METADATA.jl/pull/3827

**Comment by tkelman** [comment]
It's quite alright, no harm done. Closing this in favor of #3827. Many of these routines have been translated to Julia in the ODE.jl package, and there's an existing wrapper package for the Dopri solvers at https://github.com/helgee/Dopri.jl, but it looks like you also have support for some additional routines that have not previously been translated or wrapped.

**Comment by dpsanders** [comment]
There is already a registered package Dopri.jl that wraps the dopri routines. Could you coordinate to decide how to proceed? I guess there should only be a single interface package.

**Pull request closed without merging**
