### PR TITLE
Register ConicIP One more time!

### PR DESCRIPTION
**Pull request by gabgoh**
https://github.com/JuliaLang/METADATA.jl/pull/8582

### CODE REVIEW

**Comment by ararslan** [comment]
A couple notes:

* Looks like you're still testing on 0.4 but not supporting it, so 0.4 should be dropped from the Travis and AppVeyor YAML files.

* The Travis badge in the README links to the badge image rather than to Travis.

* The tests aren't passing on Julia 0.6, and there are a large number of deprecation warnings.

**Comment by mlubin** [comment]
I'm going to merge this because it's literally the sixth attempt at registering the package, and I trust @gabgoh to address these points in a future release.

https://github.com/JuliaLang/METADATA.jl/pull/8582
https://github.com/JuliaLang/METADATA.jl/pull/8572
https://github.com/JuliaLang/METADATA.jl/pull/5981
https://github.com/JuliaLang/METADATA.jl/pull/5839
https://github.com/JuliaLang/METADATA.jl/pull/5837

**Comment by tkelman** [comment]
there are still 2 mentions of `using Compat` that need to be removed if it's not in REQUIRE

**Comment by gabgoh** [comment]
THANK YOU so much. Will fix these bugs and retag soon!

**Comment by tkelman** [comment]
consider using https://github.com/attobot/attobot

**Pull request merged**
