### PR TITLE
Tag JuLIP.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [libAtoms/JuLIP.jl](https://github.com/libAtoms/JuLIP.jl)
Release: [v0.4.0](https://github.com/libAtoms/JuLIP.jl/releases/tag/v0.4.0)
Diff: [vs v0.2.2](https://github.com/libAtoms/JuLIP.jl/compare/3dca3a8c29f223111e2e51b3fce807cd96c506f5...227e818b676e715bf355c41559deeab8c0c866a4)
`requires` vs v0.2.2: 
```diff
--- 0.2.2/requires
+++ 0.4.0/requires
@@ -1,13 +1,13 @@
 julia 0.6 0.7-
-PyCall
 StaticArrays
-Optim 0.10 0.11-
-LineSearches
+Optim 0.14
 Calculus
-PyAMG
+AMG
 JSON
 Reexport
 FunctionWrappers
-Dierckx 0.2.1
+Dierckx 0.3 0.4-
 ForwardDiff 0.4
-PositiveFactorizations
+Parameters
+NeighbourLists 0.2
+MacroTools
```
cc: @cortner

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by cortner** [comment]
this jumps a minor version since it is a fairly significant change to the library, therefore leaving the option to have a v0.3 that still builds on v0.2

**Comment by andreasnoack** [comment]
There seems to be an issue with the version bounds
```julia
ERROR: LoadError: packages with unsatisfiable requirements found:
    JuLIP v0.4.0 – no valid versions exist for package 
```

**Comment by cortner** [comment]
you just merged it :)

**Comment by cortner** [comment]
I am very confused right now. 

* I have tagged version 0.2.0, 0.2.1 and 0.2.2 of JuLIP
* why should travis care about older version of JuLIP to begin with?

Any idea how to fix this?

**Comment by andreasnoack** [comment]
I don't see an obvious conflict. @martinholters Are you able to see what is causing the problem here?

**Comment by martinholters** [comment]
I think CI ran before #13950 was merged, so `NeighbourLists 0.2` wasn't available. I'll rerun...

**Comment by cortner** [comment]
Ok - My mistake then, should I wait next time for the first PR to be merged?

**Comment by andreasnoack** [comment]
Not necessarily, but it would be great to mention in a comment if there are dependencies between PRs.

**Comment by cortner** [comment]
Ok - will do.

Sent from my iPhone

On 23 Mar 2018, at 09:42, Andreas Noack <notifications@github.com<mailto:notifications@github.com>> wrote:


Not necessarily, but it would be great to mention in a comment if there are dependencies between PRs.

**Comment by martinholters** [comment]
Ok, CI is green now. I haven't looked at this otherwise, though, so I'll leave merging to you, @andreasnoack.

**Pull request merged**
