### PR TITLE
Tag Deldir.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [robertdj/Deldir.jl](https://github.com/robertdj/Deldir.jl)
Release: [v1.0.0](https://github.com/robertdj/Deldir.jl/releases/tag/v1.0.0)
Travis: [Travis Build Status](https://travis-ci.org/robertdj/Deldir.jl/builds/255185970)
Diff: [vs v0.0.3](https://github.com/robertdj/Deldir.jl/compare/f647423eb36e29f077d12727290b64f97a4ead9a...4147cc5886d478922075b94cbd18b8e879a9ffd7)
`requires` vs v0.0.3: 
```diff
--- 0.0.3/requires
+++ 1.0.0/requires
@@ -1,2 +1,2 @@
-julia 0.4
-DataFrames
+julia 0.6
+DataFrames 0.9.0
```
cc: @robertdj

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by robertdj** [comment]
Before trying attobot I made a pull request the manual way for the wrong commit:
https://github.com/JuliaLang/METADATA.jl/compare/metadata-v2...robertdj:pull-request/179f178f
Can you delete this PR?

Thanks!

**Comment by tkelman** [comment]
if you remove and replace the tag, attobot will update this pr in place

**Comment by robertdj** [comment]
The (correct) tag for this release is made with attobot. As far as I can tell the previous pull request can just be deleted, but I can't seem to find a "delete PR" button.

**Comment by tkelman** [comment]
I don't see any non attobot PRs for this package, where are you looking?

**Comment by robertdj** [comment]
In the link I wrote above: 
https://github.com/JuliaLang/METADATA.jl/compare/metadata-v2...robertdj:pull-request/179f178f
The `requires` are different than the attobot PR.

**Comment by tkelman** [comment]
okay but there's no PR open from that branch, so it doesn't matter

**Comment by robertdj** [comment]
Okay, great! Is this PR acceptable?

**Comment by tkelman** [comment]
Looks like this caused a test failure in VoronoiCells.jl? https://github.com/JuliaCI/pkg.julialang.org/blob/140f9750e737330dae1dbc4adce0a7a77d3a4081/logs/VoronoiCells_0.6.log

**Comment by robertdj** [comment]
True. I'm fixing my packages one at a time these days. I'll get to VoronoiCells soon.

**Pull request merged**
