### PR TITLE
Register MPEC v0.0.3

### PR DESCRIPTION
**Pull request by chkwon**
For solving mathematical programs with equilibrium constraints (MPEC), this package provides an extension to JuMP.jl by providing a macro that accepts complementarity conditions as constraints. Then it reformulates the complementarity conditions as a set of equality and inequality constraints so that a nonlinear optimization solver such as Ipopt.jl can solve the problem.

The main objective of this package is to provide the complements keyword (macro in this Julia package) that is available in other modeling languages such as GAMS, Pyomo, and AMPL.

### CODE REVIEW

**Comment by tkelman** [comment]
I know what MPEC's are, and this is pretty neat (what you call the "smooth nonlinear transformation" is also known as Fischer-Burmeister, right?), but I will leave a link here to http://docs.julialang.org/en/release-0.4/manual/packages/#guidelines-for-naming-a-package

**Comment by chkwon** [comment]
@tkelman I didn't know about the name Fischer-Burmeister. Thanks for letting me know :)

Naming is always an issue. Would TransformMPEC.jl work? Well, maybe I should make this part of Complementarity.jl. Let me think about it.

**Comment by mlubin** [comment]
:+1: to the package, will leave naming up to you

**Comment by chkwon** [comment]
Decided to go with Complementarity.jl #6168

**Pull request closed without merging**
