### PR TITLE
Tag SampledSignals v0.2.0 [https://github.com/JuliaAudio/SampledSignals.jl]

### PR DESCRIPTION
**Pull request by ssfrr**

### CODE REVIEW

**Comment by tkelman** [comment]
push the git tag to https://github.com/JuliaAudio/SampledSignals.jl/releases

**Comment by ssfrr** [comment]
tags pushed. thanks.

**Comment by ssfrr** [comment]
actually, please hold off on merging this. I'm rethinking some of the API changes that are going into this release. I'll update the PR when I've nailed it down.

**Comment by ssfrr** [comment]
OK. I made the tweaks, moved the tag in my repo, and pushed a new version of this PR with the hash updated, so it should be good to merge. Hopefully I didn't mess anything up with my gittery.

**Comment by tkelman** [comment]
gittery is a term that I might need to start incorporating in my vocabulary

**Pull request merged**
