### PR TITLE
Tag IJulia v1.2.0

### PR DESCRIPTION
**Pull request by stevengj**
This mostly fixes IJulia to work with Julia 0.5.  (There are still some glitches, especially with the Interact package — cc @shashi — but the situation is much improved compared to IJulia 1.1.)

### CODE REVIEW

**Comment by tkelman** [comment]
may want to update your ci to test against 0.5 and not 0.3.

is that workaround on appveyor still needed?

**Comment by stevengj** [comment]
Thanks, fixed CI... I'll have to look into the AppVeyor hack when I get more time.

**Comment by wookay** [comment]
do you know when ZMQ.jl will tag their version up? (related `bytestring` deprecation)
maybe it's better to write an issue for ZMQ.jl.

**Comment by wookay** [comment]
oh, there's not any warning for `bytestring` in IJulia now,
it seems to be all right.

**Comment by wookay** [comment]
nope. someone found it. I'm so sorry.

**Comment by wookay** [comment]
created a PR to fix the workaround on appveyor, at Conda.jl
https://github.com/Luthaf/Conda.jl/pull/41

**Pull request merged**
