### PR TITLE
Tag ImageQuilting.jl v0.4.7

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/ImageQuilting.jl](https://github.com/juliohm/ImageQuilting.jl)
Release: [v0.4.7](https://github.com/juliohm/ImageQuilting.jl/releases/tag/v0.4.7)
Travis: [Travis Build Status](https://travis-ci.org/juliohm/ImageQuilting.jl/builds/249716523)
Diff: [vs v0.4.6](https://github.com/juliohm/ImageQuilting.jl/compare/299f72614c88ea771b3163495206ad4580a0da38...262c8693797c93c4d87af19ec577cb3834914eea)
`requires` vs v0.4.6: 
```diff
--- 0.4.6/requires
+++ 0.4.7/requires
@@ -1,4 +1,4 @@
-julia 0.5
+julia 0.6
 Combinatorics
 StatsBase
 Primes
```
cc: @juliohm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
Need to use a new package minor version when dropping support for julia 0.5.

**Comment by juliohm** [comment]
Indeed, sorry, I thought I had bumped the minor already. What is the most straightforward way to fix the tag with attobot?

**Comment by tkelman** [comment]
since it needs to use a new version, just open a new one

**Comment by juliohm** [comment]
Can I just rename the v0.4.7 to v0.5.0 and it will trigger the build again?

**Comment by juliohm** [comment]
I will just delete the release and create a new one, just found the button on GitHub.

**Comment by juliohm** [comment]
Can you please close this PR? Thank you and sorry again for the confusion.

**Pull request closed without merging**
