### PR TITLE
Register BenchmarkProfiles [https://github.com/JuliaSmoothOptimizers/…

### PR DESCRIPTION
**Pull request by dpo**
…BenchmarkProfiles.jl.git]: v0.0.1

### CODE REVIEW

**Comment by dpo** [comment]
See #6604. The name has been revised. The original Matlab code comes without a license.

**Comment by dpo** [comment]
Tags updated but I can't re-run the Travis build.

**Comment by tkelman** [comment]
> The original Matlab code comes without a license.

Do you have permission to distribute a direct translation under the MIT license then?

**Comment by ararslan** [comment]
For reference, a relevant question from Stack Exchange: [Open source code with no license… can I fork it?](http://programmers.stackexchange.com/q/148146) The consensus seems to be "no."

**Comment by ViralBShah** [comment]
Yes, this is a bit of a bummer. By default, material created is copyrighted by the person and is their exclusive right. A license is used to dilute the default protections, which allows for redistribution, reuse, modifications, etc. Thus, without a license - we really can't do much. This is essentially what the Stack Exchange thread says.

The best thing is to ask the upstream author to publish the code under an open source license.

**Comment by dpo** [comment]
Thanks for raising those points.

> Thus, without a license - we really can't do much. This is essentially what the Stack Exchange thread says.

My understanding of the SO discussion is that written approval is sufficient, though I agree a license would make things easier.

I do have written consent from Stefan Wild to distribute the data profile part. He asked me to link to his page from my README (which I have now done) and said he'll link to BenchmarkProfiles.jl from his DFO page. I suggested he license his code.

The performance profile part is the first version of them by Dolan and Moré. I'm waiting for Moré's written approval. I'll confirm here when I have it.

**Comment by lobingera** [comment]
(i ran into a case like this sometime before and it took some weeks until the code was put under a license).
Just for curiosity: Are there know cases in any reseach field in which the original author claimed copyright voilations, when her/his SW was reused? Because obviously the author wanted to publish research and wasn't interested in keeping the SW closed...

**Comment by ViralBShah** [comment]
I personally do not know of such a case, but netlib is full of codes without license and people have been discussing it for years.

**Comment by dpo** [comment]
Optimizers are good people:

> From: Jorge Moré <more@anl.gov>
Subject: Re: Performance profiles
Date: October 11, 2016 at 23:02:10 GMT-4
To: Orban Dominique <dominique.orban@gerad.ca>

> Hi Dominique,

> By all means distribute the Julia version.

**Comment by tkelman** [comment]
Great. Should note that somewhere in the repo.

**Comment by dpo** [comment]
Thanks. See https://github.com/JuliaSmoothOptimizers/BenchmarkProfiles.jl/pull/7.

**Comment by dpo** [comment]
ps: on Travis, it seems Julia release is still 0.4.7

**Comment by tkelman** [comment]
better to use actual version numbers for release testing

**Comment by dpo** [comment]
Yes I suppose version numbers are a sure shot, but I thought "release" and "0.5" were currently the same.

**Pull request merged**
