### PR TITLE
Register new package DirectConvolution.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [vincent-picaud/DirectConvolution.jl](https://github.com/vincent-picaud/DirectConvolution.jl)
Release: [v0.0.1](https://github.com/vincent-picaud/DirectConvolution.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/vincent-picaud/DirectConvolution.jl/builds/366826611)
cc: @vincent-picaud

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@vincent-picaud This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by vincent-picaud** [comment]
@andreasnoack that the first Julia package I release and feedbacks are welcomed. Thanks.
As you suggested, I cleaned my .travis file and added test/REQUIRE. I hope it is the right way to do now.

**Comment by andreasnoack** [comment]
You are welcome. You can remove the tag and add it again to the commit that includes your changes. That will automatically update this PR.

**Comment by vincent-picaud** [comment]
@andreasnoack done. thanks.

**Comment by andreasnoack** [comment]
Great. The PR will remain open a little longer to allow people to comment on it.

**Pull request merged**
