### PR TITLE
Tag Plots.jl v0.10.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [tbreloff/Plots.jl](https://github.com/tbreloff/Plots.jl)
Release: [v0.10.3](https://github.com/tbreloff/Plots.jl/releases/tag/v0.10.3)
Travis: [Travis Build Status](https://travis-ci.org/tbreloff/Plots.jl/builds/190998629)
Diff: [vs v0.10.2](https://github.com/tbreloff/Plots.jl/compare/c092d3cab48d784dc75e999efb5090bf00057c92...199a3306db73c29bce2dd8e96d2e1762ed38d776)
`requires` vs v0.10.2: no changes
cc: @tbreloff

### CODE REVIEW

**Comment by ararslan** [comment]
This includes new features so, if I correctly understand The Laws of Semantic Versioning, this probably should be a minor release rather than a patch release, @tbreloff. Dunno how much it matters. @tkelman, thoughts?

**Comment by tbreloff** [comment]
Every single tag has had new features, so....

If you don't merge, that's fine. I'm always on the dev branch anyways.

**Comment by ararslan** [comment]
> Every single tag has had new features

That's good to know. Like I said, I don't know how strict we usually are about adherence to semver. I just noticed in the diff versus the previous tag that this version implements the big fancy thing you mentioned on Discourse so I figured I'd just point it out.

**Comment by tkelman** [comment]
Semver is a recommendation, not exactly a requirement right now. Technically while in v0.x.y you can do whatever you want, but I think it's worth still using patch for bugfixes and minor for features and larger changes. Pkg3 may or may not change the way dependency resolution works such that failure to follow semver would have more negative consequences for anyone trying to depend on your package.

**Pull request merged**
