### PR TITLE
adding test GreatCircle.jl v0.1.0

### PR DESCRIPTION
**Pull request by acrosby**
Let me know if there are any issues, I have to do this manually usually.

### CODE REVIEW

**Comment by tkelman** [comment]
missing the `requires` file

**Comment by acrosby** [comment]
Thanks, is this just supposed to look like "REQUIRE" in the root of the package repo?

**Comment by tkelman** [comment]
same content, but named `requires` for some reason that isn't written down anywhere I can find

**Comment by acrosby** [comment]
yeah, I tried to find an explanation for the METADATA.jl layout, but couldn't.

**Pull request merged**
