### PR TITLE
Tag VoronoiCells v0.1.1

### PR DESCRIPTION
**Pull request by robertdj**
Tests pass and there is no manual work to get the package working.

### CODE REVIEW

**Comment by tkelman** [comment]
Ref https://github.com/robertdj/VoronoiCells.jl/commit/e973f31cbb15e9efd0b9be149f72f11349a1a9a7#commitcomment-18118856, you should not be doing Pkg operations in a `deps/build.jl`. Tag them first and declare the minimum version dependencies in your `REQUIRE` file.

**Comment by robertdj** [comment]
I see. Unfortunately I don't have permissions to tag the required packages -- I have filed an [issue](https://github.com/JuliaGeometry/VoronoiDelaunay.jl/issues/18) so hopefully it'll be possible soon.
Is there another solution until then?

**Comment by tkelman** [comment]
You can temporarily do the checkout in `.travis.yml` rather than in `deps/build.jl`

**Comment by robertdj** [comment]
Sorry about my long absence. I'll keep my responsive rate socially acceptable. 

I'd rather not mess up too much, so one question: I've pushed a fixed version. Should I tag this fixed version and `Pkg.publish` again?

**Comment by tkelman** [comment]
@SimonDanisch what would you think about inviting @robertdj to be a member of JuliaGeometry? This package sounds like it would be a good fit there.

**Comment by SimonDanisch** [comment]
Sounds good to me :)

**Comment by robertdj** [comment]
I'll replace the sha file contents -- it looks like GeometricalPredicates and VoronoiDelaunay might be updated soon and then I'll make a new tag.

**Comment by robertdj** [comment]
It appears that my previous commit/tag was from a different computer. I'll make a 0.1.2 tag instead.

**Comment by robertdj** [comment]
This seems to be difficult... I'll fix it when I get a hold of the computer I initially used for the commit. Wont be for another 8 hours or so.

**Comment by robertdj** [comment]
Okay, I ended up making a 0.1.2 tag. It is ready to be made into a PR:
https://github.com/JuliaLang/METADATA.jl/compare/metadata-v2...robertdj:pull-request/c7a806db
Should I create the PR and close this or ...?

**Comment by tkelman** [comment]
yeah that's probably easiest

**Pull request closed without merging**
