### PR TITLE
Tag AndersonMoore.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [es335mathwiz/AndersonMoore.jl](https://github.com/es335mathwiz/AndersonMoore.jl)
Release: [v0.0.2](https://github.com/es335mathwiz/AndersonMoore.jl/releases/tag/v0.0.2)
Diff: [vs v0.0.1](https://github.com/es335mathwiz/AndersonMoore.jl/compare/5a057f36760e01116f3d5118a69bff6e7347c1ac...18bb0c100b746d63ffaea17fcbd0510a5f9655d6)
`requires` vs v0.0.1: no changes
cc: @gtunell

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like the package doesn't work on Julia 0.7 so it would be a good idea to upper bound Julia at 0.7 and allow failure on Travis.

**Comment by gtunell** [comment]
It currently only works on Julia 0.6. How would I add this upper bound? I have removed 0.7 from the Travis file completely.

**Comment by andreasnoack** [comment]
In https://github.com/es335mathwiz/AndersonMoore.jl/blob/617f4798a0cef02e95c753e8d9f43078289241f4/REQUIRE#L1 you change
```
julia 0.6
```
to
```
julia 0.6 0.7
```

**Comment by gtunell** [comment]
I have changed the REQUIRE file to have the upper bound of Julia v0.7. Also the Travis file allows failures for 0.7.

**Comment by andreasnoack** [comment]
It looks like tests are failing on CIBot. Please don't restrict testing on Travis to the develop branch, cf https://github.com/es335mathwiz/AndersonMoore.jl/blob/master/.travis.yml#L24. Otherwise, it is difficult to know if the release actually works.

**Comment by andreasnoack** [comment]
I'll close here https://github.com/JuliaLang/METADATA.jl/pull/17282. Please retag if you still would like a 0.0.2 release.

**Pull request closed without merging**
