### PR TITLE
Register SymWoodburymatrices and BlockMatrices (IntPoint Dependencies)

### PR DESCRIPTION
**Pull request by gabgoh**
SymWoodbury.jl (Package for Symmetric Woodbury Matrices) and BlockMatrices.jl (Package for Block Diagonal Matrices)

### CODE REVIEW

**Comment by tkelman** [comment]
Need to tag a version for these. Would it be possible to contribute SymWoodburyMatrices to the existing WoodburyMatrices package instead? How does your BlockMatrices package differ from github.com/KristofferC/BlockArrays.jl?

**Comment by KristofferC** [comment]
If the package is only for block diagonal matrices shouldn't the word diagonal be in the package name?

**Comment by gabgoh** [comment]
thanks for the input. yes, my package is for block diagonal matrices while blockarrays is more generic. I'm having second thoughts about releasing it as a standalone package, perhaps it should be just part of IntPoint, perhaps that would reduce the clutter? what do you think?

SymWoodburyMatrices however can be combined with WoodburyMatrices (they both perform the same function for the most part, but the latter is optimized for symmtric matrices). I'll put aside a few hours to doing that.

**Comment by timholy** [comment]
This can be closed, right? (I will tag a new version of WoodburyMatrices.)

**Comment by aviks** [comment]
@gabgoh are you happy closing this PR?

**Comment by gabgoh** [comment]
closing this PR, all dependency issues have been resolved.

**Pull request closed without merging**
