### PR TITLE
Tag Rebugger.jl v0.1.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [timholy/Rebugger.jl](https://github.com/timholy/Rebugger.jl)
Release: [v0.1.2](https://github.com/timholy/Rebugger.jl/releases/tag/v0.1.2)
Travis: [Travis Build Status](https://travis-ci.org/timholy/Rebugger.jl/builds/418866531)
Diff: [vs v0.1.1](https://github.com/timholy/Rebugger.jl/compare/3efc2bb5fb066f8c4daef3e030ef091dd770df7b...d40f8bd9faaaf753022a1fac94001f6862db05c1)
`requires` vs v0.1.1: no changes
cc: @timholy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by timholy** [comment]
I am hoping that this, in conjunction with #17169, will fix the installation problems described in https://discourse.julialang.org/t/ann-rebugger-interactive-debugging-for-julia-0-7-1-0/13843

**Comment by KristofferC** [comment]
The problem is that you have stdlibs in REQUIRE files. This means that this REQUIRE file is unsatisfiable and is therefore filtered out in the conversion process. Simply remove the stdlibs from the tagged versions and everything should work again.

Sorry about this, ideally a test in METADATA should have caught this. (and ideally we would have the new registry system fully in place...)

**Review by KristofferC — APPROVED** [review]

**Comment by timholy** [comment]
xref https://github.com/JuliaLang/METADATA.jl/pull/17173 for the two older versions.

**Comment by KristofferC** [comment]
https://github.com/JuliaRegistries/General/commit/c9cf4b4e64fe18466b7f0f5cceae29b9733235a8 :)

**Pull request merged**
