### PR TITLE
Register BayesianDataFusion: v0.1.0, v0.2.0, v0.3.0, v0.3.1, v0.3.2, …

### PR DESCRIPTION
**Pull request by jaak-s**
Package for doing Bayesian matrix factorization.
Features include tensor factorization, co-factorization, factorization with side information.

### CODE REVIEW

**Comment by tkelman** [comment]
What is the minimum Julia version this package is expected to work with?

**Comment by jaak-s** [comment]
Versions v0.3.10+ and v0.4.0+ are fine. The nightly branch is not supported.

**Comment by tkelman** [comment]
then you should add `julia 0.3` to your REQUIRE file, and the tag here

**Comment by jaak-s** [comment]
Thanks, added.

**Pull request merged**
