### PR TITLE
Pull request/5a31489f

### PR DESCRIPTION
**Pull request by reesepathak**
Introducing PSPlot.jl, a package will allows you to access psfrag plotting functionality in Julia, with the convenience of plotting in PyPlot. 

Currently only supports OS X due to a binary dependency (Inkscape). Hope to add additional unix support and then windows support in the future.

### CODE REVIEW

**Comment by reesepathak** [comment]
Importantly, note that JuliaCIBot fails because of non-osx systems. Currently this package only supports OS X, as mentioned in the original pull request.

**Comment by andreasnoack** [comment]
In the future, please consider using https://github.com/attobot/attobot when releasing new versions of this package or registering another one.

**Comment by reesepathak** [comment]
Yes, I will have to look into that. Thanks!

**Comment by reesepathak** [comment]
@andreasnoack What else do I need to do for this package to be accepted?

**Comment by andreasnoack** [comment]
From my side, it is good to go but we usually let package registration PRs stay open a couple of days to allow people to comment.

**Pull request merged**
