### PR TITLE
Register new package NLSolversBase.jl v1.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/NLSolversBase.jl](https://github.com/JuliaNLSolvers/NLSolversBase.jl)
Release: [v1.0.2](https://github.com/JuliaNLSolvers/NLSolversBase.jl/releases/tag/v1.0.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaNLSolvers/NLSolversBase.jl/builds/212552701)
cc: @pkofod

### CODE REVIEW

**Comment by tkelman** [comment]
good to see tests, but without a readme or description, is anyone supposed to use this?

**Comment by pkofod** [comment]
No end users, but we need to register it to use it in Optim, LineSearches and NLsolve. I'll throw together a short description tomorrow.

**Comment by pkofod** [comment]
Made a short description in the README.md. Close and re-tag?

**Comment by tkelman** [comment]
No need if there weren't any code changes. By description I meant the "No description, website, or topics provided." under the repo name.

**Comment by pkofod** [comment]
Oh yeah, I forgot that was a thing.

**Comment by tkelman** [comment]
pkg.julialang.org gets populated based on the description field. it doesn't do anything with the github labels, those are new and I don't know if there's an API to get them

**Pull request merged**
