### PR TITLE
Pull request/92e068ac

### PR DESCRIPTION
**Pull request by montyvesselinov**
Various fixes and improvements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please bump the minor version when you change the Julia version requirement.

**Comment by montyvesselinov** [comment]
We are planning for major changes; can you commit now. We will bump the
minor version on the next commit. Thank you very much!

-monty

**Comment by andreasnoack** [comment]
I'm sorry. Changing the minor version when changing the Julia version requirement is a prerequisite for a new METADATA release.

**Comment by montyvesselinov** [comment]
Pushed separately.

**Pull request closed without merging**
