### PR TITLE
Register new package EasyPhys.jl v0.1.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [julian-wolf/EasyPhys.jl](https://github.com/julian-wolf/EasyPhys.jl)
Release: [v0.1.3](https://github.com/julian-wolf/EasyPhys.jl/releases/tag/v0.1.3)
Travis: [Travis Build Status](https://travis-ci.org/julian-wolf/EasyPhys.jl/builds/184345122)
cc: @julian-wolf

### CODE REVIEW

**Comment by julian-wolf** [comment]
Thanks, attobot!

**Comment by aviks** [comment]
Would EasyPhysics be a better name? Just a suggestion.

**Comment by julian-wolf** [comment]
I like EasyPhys. If there's a policy of only allowing maximally-descriptive names / discouraging abbreviations in registered packages (sorta like what Mathematica has going, which would actually be pretty awesome) then I'd be happy to change it, but otherwise I think I'll leave it as is. Anyway, thanks for the input!

**Comment by kmsquire** [comment]
Official guidelines are here: http://docs.julialang.org/en/release-0.5/manual/packages/#guidelines-for-naming-a-package

Generally, more descriptive names with full names are encouraged, although not mandated.  Given that this has sat for almost a week with no more comments, I'll merge tomorrow if no one says anything.

**Comment by tkelman** [comment]
It's good practice to list all dependencies explicitly in REQUIRE, rather than assuming they will be present as transitive dependencies. Though with PyCall and PyPlot that's a pretty safe assumption.

**Comment by julian-wolf** [comment]
Thanks for the info! So would this just amount to explicitly requiring PyCall, or would I also list matplotlib, etc.? (I'm pretty new to this.)

**Comment by ViralBShah** [comment]
You should depend on PyCall and PyPlot (which will use matplotlib), if that is what your code needs.

**Comment by julian-wolf** [comment]
Okay, great. I'm new to tags and releases and all that—is there any way that I can update the version tagged v0.1.3 with a single commit adding this to the REQUIRE file? The master branch has been updated considerably since this tag and isn't fully tested, so I would rather not publish a new release yet. (Rolling back and tagging v0.1.4 is also an option, but tagging a new release just for a single line change seems weird.)

**Comment by tkelman** [comment]
See https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by julian-wolf** [comment]
Thanks. So, just to be sure, this will amount to deleting the tag v0.1.3, creating a new branch from the commit that was previously tagged v0.1.3, committing the change to that branch, and then re-tagging it v0.1.3?

**Comment by tkelman** [comment]
Has master diverged much since you tagged v0.1.3? You can re-tag the replacement version from master if there haven't been many significant changes.

**Comment by julian-wolf** [comment]
Master has diverged a fair amount, and, since it is not currently fully-tested, I would prefer not to tag / release master as-is.

**Comment by tkelman** [comment]
okay, then yes it would be a good idea to create a branch

**Pull request merged**
