### PR TITLE
Tag Clipper.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGeometry/Clipper.jl](https://github.com/JuliaGeometry/Clipper.jl)
Release: [v0.5.0](https://github.com/JuliaGeometry/Clipper.jl/releases/tag/v0.5.0)
Diff: [vs v0.4.0](https://github.com/JuliaGeometry/Clipper.jl/compare/71aa1b61c52a9d05c763266b6d23f81753060b14...d19595e4d05f894321dffd4c4107aeba1077160a)
`requires` vs v0.4.0: 
```diff
--- 0.4.0/requires
+++ 0.5.0/requires
@@ -1,2 +1,2 @@
-julia 0.6
+julia 0.7
 BinaryProvider
```
cc: @SimonDanisch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ajkeller34** [comment]
Is this waiting on the JuliaCIBot test to pass?

**Comment by SimonDanisch** [comment]
1.0 failure seems due to a pkg bug, or at least i'm not sure how this can happen with only one dependency - can we merge this?

**Comment by andreasnoack** [comment]
> Is this waiting on the JuliaCIBot test to pass?

Yes. The tests don't pass on 1.0. You have to change `Base.Test`->`Test` in https://github.com/JuliaGeometry/Clipper.jl/blob/master/test/runtests.jl#L2. (Please read the log such that I don't have to)

**Comment by andreasnoack** [comment]
Please also adjust `.travis.yml` to reflect the currently supported versions. Sorry for being grumpy here but these should really be easy to handle before a release. Any time a PR to METADATA fails tests, a METADATA maintainer will have to spend time on it and, in this case, it seems like it could easily have been avoided.

**Comment by SimonDanisch** [comment]
I'm sorry andreas! Happens when I tag packages I don't use - and read the wrong logs -.-
@ajkeller34, I added you as a collaborator, would you be able to fix this?

**Comment by SimonDanisch** [comment]
Checks pass :)

**Pull request merged**
