### PR TITLE
Pull request/7798b8e4

### PR DESCRIPTION
**Pull request by sbromberger**
Sorry for the multiple changes here - I had to back out 0.3.7 and inadvertently created 0.3.8. This should fix things.

### CODE REVIEW

**Comment by tkelman** [comment]
probably cleanest to squash these

**Comment by sbromberger** [comment]
I don't know how. I used `Pkg.tag()` and `Pkg.publish()`....

**Comment by tkelman** [comment]
Or, actually, since everything is contained in that last commit, can just rebase out the others.
```
cd ~/.julia/v0.4/METADATA
git remote add sbromberger https://github.com/sbromberger/METADATA.jl
get fetch --all
git checkout pull-request/7798b8e4
git rebase -i origin/metadata-v2
# delete everything except the last commit
# check git log, git show, that it looks correct
git push sbromberger +pull-request/7798b8e4
git checkout metadata-v2
```

**Comment by sbromberger** [comment]
damn. Auth is failing on that git push. Dunno why.

**Comment by sbromberger** [comment]
Thanks for all the help!

**Pull request merged**
