### PR TITLE
Pull request/1fb03976

### PR DESCRIPTION
**Pull request by charlesll**
Registration of Spectra.jl

Created a new branch to avoid any trouble with the old pull request.

### CODE REVIEW

**Comment by tkelman** [comment]
Depending on both pyplot and gadfly seems a bit unusual.

**Comment by tkelman** [comment]
What is the license status of https://github.com/charlesll/Spectra.jl/blob/master/Dependencies/gcvspl.f?

**Comment by charlesll** [comment]
gcvspl is available on the netlib website: http://www.netlib.org/gcv/gcvspl. There is nothing in the headerlines regarding a licence, so I guess it can be considered as public domain?

I will make a commit to remove dependency to gadfly, as my examples run with pyplot.

**Comment by charlesll** [comment]
I found details on the gcvspl.f licence, and updated the headerlines of the gcvspl.f file accordingly.

**Comment by tkelman** [comment]
Great! Spectra's a pretty generic name, but unless someone has strong objections to it I think we can register this in a few hours.

**Comment by charlesll** [comment]
Great, thanks!

**Comment by tkelman** [comment]
(p.s. would be a good idea to add some tests to https://github.com/charlesll/Spectra.jl/blob/master/test/runtests.jl over time so you can check that the package continues working correctly)

**Comment by charlesll** [comment]
Yes, I will add them very soon. I am currently adding further functionality and examples, so I will create the tests accordingly!

**Pull request merged**
