### PR TITLE
Tag PortAudio v0.3.0 [https://github.com/JuliaAudio/PortAudio.jl]

### PR DESCRIPTION
**Pull request by ssfrr**

### CODE REVIEW

**Comment by tkelman** [comment]
I guess you haven't attempted to run this on Travis recently?

**Comment by ssfrr** [comment]
currently passing:
https://travis-ci.org/JuliaAudio/PortAudio.jl

Though I can't access audio devices on the travis machines, so it only tests that it's installable and I can run "using PortAudio" without error

**Comment by tkelman** [comment]
Oh right you don't have a badge, and I was looking for the status at https://github.com/JuliaAudio/PortAudio.jl/branches but your latest commit was [ci skip]ed

**Comment by ssfrr** [comment]
Yeah, it seemed disingenuous to put a CI badge when I'm not really testing the package's functionality, though I guess it would make it more visible if I broke the install, so maybe it makes sense anyways.

thanks for the review and merge.

**Pull request merged**
