### PR TITLE
Register new package HigherPrecision.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [saschatimme/HigherPrecision.jl](https://github.com/saschatimme/HigherPrecision.jl)
Release: [v0.1.0](https://github.com/saschatimme/HigherPrecision.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/saschatimme/HigherPrecision.jl/builds/297593844)
cc: @saschatimme

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@saschatimme This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This library looks fantastic. I'm going to go try it out with DiffEq right now!

**Comment by ChrisRackauckas** [comment]
I may have merged a little quickly after checking out the repo. Everything checks out fine, but the naming is a little odd. Is there a reason why it's HigherPrecision.jl instead of DoubleFloat64.jl if that's the only type from the package?

**Comment by saschatimme** [comment]
I plan to also add Quad-Double precision and felt that two separate packages would have been rather odd.

**Comment by ChrisRackauckas** [comment]
Sounds good to me. I'm excited to follow your developments.

**Pull request merged**
