### PR TITLE
Register new package GSW-Julia.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ax1ine/GSW-Julia.jl](https://github.com/ax1ine/GSW-Julia.jl)
Release: [v0.1.0](https://github.com/ax1ine/GSW-Julia.jl/releases/tag/v0.1.0)
cc: @ax1ine

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ax1ine This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use abbreviations in package names, and don't put julia in the package name itself (that's taken account of by .jl). Also please add some description of the purpose of the package and usage examples in the readme.

**Comment by ax1ine** [comment]
I'm sorry, I've messed up with the packages (I'm very new with Julia) and accidently opened a new pull request (https://github.com/JuliaLang/METADATA.jl/pull/20898). Please, disregard it.

I have updated the description and restructured the package.

I would kindly ask to be allowed to keep the GSW abbreviation as it's well-known to the dedicated community. This package is a wrapper on the original C version of the Gibbs-SeaWater (GSW) Oceanographic Toolbox for the Thermodynamic Equation of Seawater 2010 (TEOS-10). The toolbox has many implementations (https://github.com/TEOS-10) and all of them are named in a similar way (e.g. Python package is also names GSW). The developers have decided to use the C version for the further development to simplify maintenance so I build this wrapper around it.

**Comment by andreasnoack** [comment]
Regarding this name then the "-Julia" part is redundant because we have the ".jl" extensions. Also, you are free to keep the GSW name but it's strongly discouraged since it's a completely uninformative name. There are probably also several GSWs across the disciplines.

Notice also that the tests are failing. Please read the log to figure out what is going wrong.

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
