### PR TITLE
Register new package IEEEMinMax

### PR DESCRIPTION
**Pull request by ararslan**
This package provides the pre-0.6, IEEE 754-2008 compliant behavior of `min` and `max` as `minnum` and `maxnum` (named as per IEEE). Pretty lightweight, useful for Graphics and Winston.

### CODE REVIEW

**Comment by ararslan** [comment]
@tkelman If you think this should be part of NaNMath that's fine--just close this and I'll open a PR there instead.

**Comment by ararslan** [comment]
Should also ask @mlubin what he thinks of having it in NaNMath.

**Comment by tkelman** [comment]
ref https://github.com/mlubin/NaNMath.jl/issues/2

**Comment by ararslan** [comment]
Ah yeah.

**Pull request closed without merging**
