### PR TITLE
Register new package Jive.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [wookay/Jive.jl](https://github.com/wookay/Jive.jl)
Release: [v0.1.0](https://github.com/wookay/Jive.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/wookay/Jive.jl/builds/465445420)
cc: @wookay

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@wookay This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please add info about what the purpose of the package is, and change the name to make that purpose clear from the name.

**Comment by wookay** [comment]
this package providing macros and functions to help the writing tests. 
maybe `TestUtils.jl` is a better name for this package, but I've got inspired and choosed the name from
> Jive - perform the jive or a similar dance to popular music

actually this doesn't have any related with music though.

when I writing some Julia tests and many modules, I need to make some macros for the modules.
`@mockup`, `@onlyonce`, `@skip`, `@If` are used for it.
and `runtests` function could specify the directory of the test files to run. you could see the example in the term (click to animate)


I prefer the name `Jive` but I would appreciate suggesting another name.
thanks.

**Comment by aviks** [comment]
It is fine to have a "funky" name for a package, so long as it is not misleading. In this case however, Jive is the name of a well known collaboration software. (https://www.jivesoftware.com/)

**Comment by wookay** [comment]
hmm. JuliaCIBot. I couldn't test with it for Julia 1.0.2.

@aviks I don't heard about the Jive Collaboration Software.. I think that it's possible to distinguish the name between `Jive.jl` and Jive Software. thanks for the comment.

**Comment by andreasnoack** [comment]
It's unclear to me why this is failing on CIBot. Might be an issue with Julia 1.0.0. I'll try to upgrade to Julia 1.0.2 tomorrow. However, the `mockup` macro might not be sound. Usually, you are warned against `eval`ing inside a macro.

**Comment by wookay** [comment]
@andreasnoack  I added the option to warn the replacing modules for usual cases, by something like
`Jive.config[:warn_replacing_mock] = true`
thanks for the comment and much appreciated for the upgrading!

**Comment by andreasnoack** [comment]
@wookay I'm not sure how your last comment relates to my comment. Would you be able to elaborate?

**Comment by wookay** [comment]
@andreasnoack  I took it the wrong way. I understood that the `@mockup` macro may not be right. _warned_ it for usual.
I didn't know exactly, but it seemed like that.

but It just meant that `eval` inside a macro carefully.

**Comment by andreasnoack** [comment]
@aviks Are you suggesting that the current name is an issue because of https://www.jivesoftware.com/?

**Comment by aviks** [comment]
> @aviks Are you suggesting that the current name is an issue because of https://www.jivesoftware.com/?

Yes.

**Comment by ssfrr** [comment]
I've never heard of Jive software, and I'd say they certainly don't have a monopoly on the word "jive".

**Comment by andreasnoack** [comment]
The policy has been to point out possible issues and then let the package author decide. So @wookay please let us know if you'd like to keep the name or if you'd like to change it.

**Comment by wookay** [comment]
thanks for all of your opinions.
I still like to keep the name if it doesn't have any other problem.
Happy new year!

**Pull request merged**
