### PR TITLE
Tag Vega v0.8.0

### PR DESCRIPTION
**Pull request by randyzwitch**

### CODE REVIEW

**Comment by aviks** [comment]
Tests fail on 0.6 with 
```
ERROR: LoadError: type StepRangeLen has no field divisor
Stacktrace:
 [1] #histogram#121(::Array{Float64,1}, ::Bool, ::Bool, ::Int64, ::Float64, ::Function) at /mnt/pkgevalempty/133ca9c82826bb530c9db3d5da0df1ecde3551d4/Vega/.julia/v0.6/Vega/src/derived/histogram.jl:12
 [2] (::Vega.#kw##histogram)(::Array{Any,1}, ::Vega.#histogram) at ./<missing>:0
```

**Comment by randyzwitch** [comment]
Thanks, I'll fix that in the coming days

**Comment by randyzwitch** [comment]
By keeping the REQUIRE in sync with the Vega repo, I fail the tests because you're not allowed to modify files. But the CIBot tests pass.

Should I close this PR and start a new one? Not sure how to proceed.

**Comment by randyzwitch** [comment]
@aviks, please see comment above

**Pull request merged**
