### PR TITLE
Tag MLDataPattern.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaML/MLDataPattern.jl](https://github.com/JuliaML/MLDataPattern.jl)
Release: [v0.5.0](https://github.com/JuliaML/MLDataPattern.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaML/MLDataPattern.jl/builds/420864676)
Diff: [vs v0.4.0](https://github.com/JuliaML/MLDataPattern.jl/compare/90911ca8829773cbf98d95ed3739e1c62cf0ce9b...f03b0c182a6d89948096f7244a163b2a258c57c4)
`requires` vs v0.4.0: 
```diff
--- 0.4.0/requires
+++ 0.5.0/requires
@@ -1,6 +1,4 @@
-julia 0.6
-StatsBase 0.13
-LearnBase 0.1.5 0.2.0
-MLLabelUtils 0.0.3
-ShowItLikeYouBuildIt
-Compat 0.19
+julia 0.7
+StatsBase 0.24.0
+LearnBase 0.2.0 0.3.0
+MLLabelUtils 0.4.0
```
cc: @Evizero

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
A version of Colors without a project file has just been merged into METADATA so I'll restart tests here

**Comment by Evizero** [comment]
still pending. did it die maybe?

**Comment by andreasnoack** [comment]
Probably. Let's try again.

**Comment by Evizero** [comment]
👍

**Comment by andreasnoack** [comment]
Success

**Pull request merged**
