### PR TITLE
Tag DataArrays v0.2.12, Compat v0.3.4

### PR DESCRIPTION
**Pull request by garborg**

### CODE REVIEW

**Comment by tkelman** [comment]
Can you push the tags to the package repos? Makes it much easier to track what versions correspond to which sha's if it's visible within the same repo.

**Comment by tkelman** [comment]
Oh nevermind, do you not have commit access to Compat.jl? We should fix that.

**Comment by StefanKarpinski** [comment]
@tkelman, I believe you have the power to do that, right? Let me know otherwise.

**Comment by garborg** [comment]
Yeah, that's the rub -- I used to put up notes for others to tag versions, but it only seemed to work when one person owned the repo.

**Comment by tkelman** [comment]
No, I can't add Sean to the JuliaLang/Contributors team. I oddly have the rights to revoke either the Contributors team or the Admin team's access to Compat.jl, but I can't add people to teams.

**Comment by StefanKarpinski** [comment]
Done.

**Pull request merged**
