### PR TITLE
Tag OpenGene v0.1.6 and Regisger SeqMaker

### PR DESCRIPTION
**Pull request by sfchen**
This new revision of OpenGene provides some small new features and a bug fix

SeqMaker: Next Generation Sequencing simulation with SNP, Variation and Sequencing Error Integrated

Features:
* support sequencing error simulation
* support SNV simulation

### CODE REVIEW

**Comment by sfchen** [comment]
@tkelman 
Hi Tony, can you review this PR?

**Comment by tkelman** [comment]
SeqMaker could use some tests.

I'd rather not be personally pinged on these, I'll check them one way or another. I leave new package registrations open for a 24 hour initial feedback period.

**Comment by sfchen** [comment]
@tkelman ok, I didn't add tests because the test need to download big reference genome assembly (~1G), I will add one.

**Comment by tkelman** [comment]
That is very large. There's no way to test on a smaller subset?

**Pull request merged**
