### PR TITLE
Tag RigidBodyDynamics.jl v0.2.0 (properly this time)

### PR DESCRIPTION
**Pull request by tkoolen**
Repository: [tkoolen/RigidBodyDynamics.jl](https://github.com/tkoolen/RigidBodyDynamics.jl)
Release: [v0.2.0](https://github.com/tkoolen/RigidBodyDynamics.jl/releases/tag/v0.2.0)
Travis: [Build Status](https://travis-ci.org/tkoolen/RigidBodyDynamics.jl)
Diff [vs v0.1.0](https://github.com/tkoolen/RigidBodyDynamics.jl/compare/dfbf7aac31875c69ea8def33400baaa387822bbb...2a136f2cebfcd05fa042861e608e553a91f63b0a)

No changes in requires.

### CODE REVIEW

**Comment by tkoolen** [comment]
Should I set 0.6.0-pre as the upper bound for all RigidBodyDynamics versions before 0.2.0?

**Comment by tkelman** [comment]
To what end?

**Comment by tkoolen** [comment]
Versions before 0.2.0 don't work on 0.6 because of (among other things) a generated function that caused world-age issues.

**Comment by tkelman** [comment]
Do they load and partially work at all? Pkg auto-upgrades, so it shouldn't usually be necessary to force those versions to not be installable if there's a newer version that works.

**Comment by tkoolen** [comment]
Just tested 0.0.1 through 0.1.0 on 0.6-rc3. All versions except 0.0.5 load. All versions fail basic tests, e.g. due to method ambiguity errors in `convert` methods for essential types such as `SpatialInertia`.

**Comment by tkoolen** [comment]
BTW, the JuliaCIBot failures for RigidBodyDynamics are due to
```
 LoadError: InitError: Failed to import required Python module sympy.
  
  For automated sympy installation, try configuring PyCall to use the Conda.jl package's Python "Miniconda" distribution within Julia. Relaunch Julia and run:
      ENV["PYTHON"]=""
      Pkg.build("PyCall")
  before trying again.
```
For Travis, [I clear the `PYTHON` environment variable before running `Pkg.test()`](https://github.com/tkoolen/RigidBodyDynamics.jl/blob/2a136f2cebfcd05fa042861e608e553a91f63b0a/.travis.yml#L17). Any advice on how to get this to work on JuliaCIBot? I'm assuming it just runs `Pkg.test("RigidBodyDynamics")`, correct? I don't think I should set the environment variable and call `Pkg.build("PyCall")` inside my `runtests.jl`, because that would be bad for users running the tests locally, right? I guess [SymPy itself had the same issue and just ignored it](https://github.com/JuliaLang/METADATA.jl/pull/9404).

For RigidBodyTreeInspector, @rdeits and I are planning to release a version based on RigidBodyDynamics 0.2.0 soon. Should this PR add upper bounds on the RigidBodyDynamics versions that are compatible with RigidBodyTreeInspector?

**Comment by tkelman** [comment]
If this tag of RigidBodyDynamics breaks all existing tags of RigidBodyTreeInspector, then yes it would be good to add upper bounds

**Pull request merged**
