### PR TITLE
Register GroupSlices

### PR DESCRIPTION
**Pull request by AndyGreenwell**
Moving JuliaLang [PR #15503](https://github.com/JuliaLang/julia/pull/15503) into a package.

### CODE REVIEW

**Comment by tkelman** [comment]
You'll need to tag a version

**Comment by AndyGreenwell** [comment]
If the `Pkg.tag` operation needs to occur before the `Pkg.publish` operation, then we should change the order in which these items are discussed in the [docs](http://docs.julialang.org/en/release-0.4/manual/packages/#tagging-and-publishing-your-package)

**Comment by tkelman** [comment]
Yes.

**Comment by AndyGreenwell** [comment]
Closing this PR.  Will open anew with a tag.

**Pull request closed without merging**
