### PR TITLE
Tag POMDPModelTools.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPOMDP/POMDPModelTools.jl](https://github.com/JuliaPOMDP/POMDPModelTools.jl)
Release: [v0.1.1](https://github.com/JuliaPOMDP/POMDPModelTools.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPOMDP/POMDPModelTools.jl/builds/426955465)
Diff: [vs v0.1.0](https://github.com/JuliaPOMDP/POMDPModelTools.jl/compare/7d769ed22b75040d0f4b30250c7468b755945fa5...794178b848b087e522cc539a5ea31c20ee87e50b)
`requires` vs v0.1.0: no changes
cc: @rejuvyesh

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like this breaks POMDPModels

**Comment by rejuvyesh** [comment]
@andreasnoack Will be fixed once we merge https://github.com/JuliaPOMDP/POMDPModels.jl/pull/42 and tag it.

**Comment by andreasnoack** [comment]
Do you want to wait for that or would you like this PR to be merged now?

**Comment by rejuvyesh** [comment]
It would be great if it can be merged soon!

**Pull request merged**
