### PR TITLE
Tag Gadfly.jl 0.6.6, Compose.jl 0.5.6

### PR DESCRIPTION
**Pull request by bjarthur**

### CODE REVIEW

**Comment by bjarthur** [comment]
@andreasnoack

**Comment by andreasnoack** [comment]
From the log
```julia
ERROR: LoadError: METADATA/Gadfly/versions/0.6.6/requires: oldest allowed julia version 0.5.0 too old (>= 0.6.0 needed)
```
Remeber that when bumping the Julia version in REQUIRE, you'd have to make it a minor release.

**Comment by bjarthur** [comment]
last time we bumped the julia version in either Gadfly or Compose was on 2 feb 2017:

```
arthurb-lm4:Gadfly arthurb$ git blame REQUIRE 
81a141d85 (Tamas Nagy       2017-02-02 11:16:56 -0800  1) julia 0.5
5a3a777f1 (Tim Holy         2015-08-23 18:28:14 -0500  2) Colors 0.3.4
9f8832972 (Ben Arthur       2017-04-23 07:57:20 -0400  3) Compat 0.18.0
0f7c59034 (Ben Arthur       2017-05-21 20:01:29 -0400  4) Compose 0.5.2
1461f8041 (Tomas Lycken     2016-08-11 12:18:15 +0200  5) Contour 0.1.1
72a970a12 (Mattriks         2017-04-26 21:55:39 +1000  6) CoupledFields
67ca8bc73 (Ben Arthur       2018-02-12 07:44:23 -0500  7) DataFrames 0.4.2 0.11.0
b0bfa4be3 (Tony Kelman      2017-05-17 08:10:10 -0400  8) DataArrays
e5ff532eb (Daniel Jones     2014-04-27 18:38:31 -0700  9) DataStructures
09221588c (Daniel Jones     2013-10-25 23:30:11 -0700 10) Distributions
43844a680 (Daniel Jones     2013-12-30 17:04:00 -0800 11) Hexagons
d4222bef2 (Eric Davies      2017-06-22 18:52:55 -0700 12) IterTools
3fc201fdb (Daniel Jones     2013-01-06 20:42:10 -0800 13) JSON
f8651caae (Daniel Jones     2014-07-19 17:17:04 -0700 14) KernelDensity
8e38bfa66 (Stefan Karpinski 2013-10-26 00:38:07 -0400 15) Loess
1dfebccde (Daniel Jones     2014-12-30 12:21:29 -0800 16) Showoff 0.0.3
cf73ba6e0 (Daniel Jones     2014-01-20 19:02:25 -0800 17) StatsBase
ffe269b69 (Mike J Innes     2016-09-21 17:54:55 +0100 18) Juno

arthurb-lm4:Gadfly arthurb$ cd ../Compose

arthurb-lm4:Compose arthurb$ git blame REQUIRE 
3c75ec4a (Tamas Nagy   2017-02-22 18:10:49 -0800 1) julia 0.5
ded1a0db (Tim Holy     2015-08-23 17:17:10 -0500 2) Colors
ccafd67d (Tony Kelman  2017-04-12 14:15:15 -0700 3) Compat 0.18.0
060fcf0e (Daniel Jones 2014-07-25 20:39:17 -0700 4) DataStructures
d750a270 (Eric Davies  2017-06-22 18:07:00 -0700 5) IterTools
9b72a8a5 (Daniel Jones 2014-06-12 08:26:58 -0700 6) JSON
5e61f92e (Daniel Jones 2015-10-22 22:39:47 -0700 7) Measures
```

this error sounds more to me like METADATA's having dropped support for 0.5.

i suppose i'll just merge your DataFrames PR and will tag a new release when ready.

**Comment by bjarthur** [comment]
@nalimilan does the above see right to you?

**Comment by nalimilan** [comment]
I'd say you indeed need to drop support for Julia 0.5, which requires bumping the minor version (second digit). So it makes sense to include the DataFrames 0.11 port in that release too.

**Comment by bjarthur** [comment]
closed in favor of https://github.com/JuliaLang/METADATA.jl/pull/14044

**Pull request closed without merging**
