### PR TITLE
ArbFloats v0.1.8 (newbranch)

### PR DESCRIPTION
**Pull request by JeffreySarnoff**

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
LoadError: ArgumentError: invalid version string: v0,1,7
how do I kill that bad version string?

**Comment by ararslan** [comment]
You have a version tagged on your repo using commas instead of periods, which you can remove like
```
git tag -d v0,1,7
git push :refs/tags/v0,1,7
```

**Comment by tkelman** [comment]
Okay the cherry-pick worked here, but you started from a branch that had bad commits on it. Try this
```
git remote add JeffreySarnoff https://github.com/JeffreySarnoff/METADATA.jl
git remote add JuliaLang https://github.com/JuliaLang/METADATA.jl
git fetch JeffreySarnoff
git fetch JuliaLang
git checkout JuliaLang/metadata-v2
git log -1 # should match https://github.com/JuliaLang/METADATA.jl/commits/metadata-v2
git checkout -b arbfloats-new2
git cherry-pick c140513
git push JeffreySarnoff arbfloats-new2
```

**Comment by JeffreySarnoff** [comment]
sequence worked -- closing this to open pull from the newly pushed branch

**Pull request closed without merging**
