### PR TITLE
Tag SHA v0.2.0

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
Closing while we merge a few more PR's before making this release.

**Comment by tkelman** [comment]
will any existing users need upper bounds to avoid api change breakage?

**Comment by staticfloat** [comment]
Yes, but the only effected package I could find was BinDeps, and I added the compatibility fix [a while back](https://github.com/JuliaLang/BinDeps.jl/commit/64c591da0cabafc2e319b2ef0dedc18a42d34c95).

**Comment by staticfloat** [comment]
New PR here: https://github.com/JuliaLang/METADATA.jl/pull/5708

**Pull request closed without merging**
