### PR TITLE
Register GeographicLibPy

### PR DESCRIPTION
**Pull request by kshramt**

### CODE REVIEW

**Comment by tkelman** [comment]
Hi, looks good, though you'll need to tag a version in order for anyone to be able to install the package with `Pkg.add("GeographicLibPy")`.

**Comment by kshramt** [comment]
Thank you for taking a look at this.
I tagged `v0.0.1` and force-`push`ed.

**Comment by stevengj** [comment]
(Would be good if the README file had some basic notes on how to use the package.)

**Comment by tkelman** [comment]
Not absolutely required for registration, but would of course be useful to add documentation and a description field for usability and discoverability going forward.

**Comment by kshramt** [comment]
OK, thanks!

**Pull request merged**
