### PR TITLE
Register new package APITools.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaString/APITools.jl](https://github.com/JuliaString/APITools.jl)
Release: [v0.1.0](https://github.com/JuliaString/APITools.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaString/APITools.jl/builds/379058713)
cc: @ScottPJones

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ScottPJones This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
This seems like rather a generic name for a package, that gives no information about what it is for. I wonder if there could be a more informative name?

**Comment by ViralBShah** [comment]
@andreasnoack I believe you may be in conversation with Scott about this. I believe we do not register packages with such generic names, and perhaps this needs to be resubmitted with a better name. If you are ok with that, we can go ahead and close this one.

**Comment by oxinabox** [comment]
Cross-ref to brainstorming/discussion on discourse 
https://discourse.julialang.org/t/name-of-apitools-jl-package/11042/4

**Comment by andreasnoack** [comment]
Superseded by #14779

**Pull request closed without merging**
