### PR TITLE
Tag NIDAQ.jl v0.3.0

### PR DESCRIPTION
**Pull request by bjarthur**
support julia 0.6 and NI-DAQmx 17.1.0

### CODE REVIEW

**Comment by tkelman** [comment]
Compat needs to be listed in REQUIRE if it's used in your source. Though other than the `using Compat` doesn't look like you're using it for anything?

**Comment by bjarthur** [comment]
oi.  my bad.  fixed now.  probably not kosher though to try and move the git tag to point to this new commit.  will i just have to tag and publish 0.3.1?

**Comment by tkelman** [comment]
Either way, since it hasn't been published to metadata yet it's fine to modify if you want to change it.

**Comment by bjarthur** [comment]
fixed here https://github.com/JuliaLang/METADATA.jl/pull/10556

**Pull request closed without merging**
