### PR TITLE
Pull request/902ed354

### PR DESCRIPTION
**Pull request by emmt**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Thanks for the package! Is this what this library is usually called? A slightly more descriptive name would be nice, but I am not sure what it should be looking at the package.

**Comment by IainNZ** [comment]
Well I guess we already have FITSIO, so makes sense to have OIFITS too :D
https://github.com/JuliaAstro/FITSIO.jl

@emmt make sure to tag a version too, otherwise users won't be able to Pkg.add them!

**Comment by ViralBShah** [comment]
I was wondering if the two were related.

**Comment by IainNZ** [comment]
OIFITS.jl depends on FITSIO.jl

**Comment by emmt** [comment]
Hi,

Well, OI-FITS is the name of this specific data format. It is intended 
for Optical Interferometry data and is based on FITS which is a widely 
used file format in astronmy. FITS is an acronym for Flexible Image 
Transport System. So I think that OIFITS is fine.

On the GitHub page of the package the description is:

"Support for OI-FITS (optical interferometry data format) in Julia."

is it clear enough?

Thanks!

	Eric.

**Comment by emmt** [comment]
Le 03/03/2015 20:35, Viral B. Shah a écrit :
> I was wondering if the two were related.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/METADATA.jl/pull/2237#issuecomment-77017436>.
>
Yes OIFITS is based on FITSIO.

Eric.

**Comment by IainNZ** [comment]
@emmt can you please tag a version? I'll merge after that

**Comment by emmt** [comment]
OK that should be done now!

**Comment by emmt** [comment]
> Merged #2237 <https://github.com/JuliaLang/METADATA.jl/pull/2237>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/METADATA.jl/pull/2237#event-245636787>.
>

thanks again!

**Pull request merged**
