### PR TITLE
Set a maximum version of StatsFuns for Distributions

### PR DESCRIPTION
**Pull request by ararslan**
StatsFuns 0.3.0 introduces breaking changes to all current Distributions versions.

### CODE REVIEW

**Comment by tkelman** [comment]
I think we may need to add an artificial `StatsFuns 0.0.0 0.3.0` dependency to even earlier Distributions.jl version that supports `julia 0.3` or newer, otherwise the conflict may result in downgrading Distributions.jl to something from before it depended on StatsFuns.

**Comment by ararslan** [comment]
Ah right, should have remembered that from last time. Will do.

**Comment by tkelman** [comment]
I'm a little hesitant on what to do about any versions of Distributions that don't have a minimum Julia version, or have one that's pre-0.3.0. We should probably test this and see whether Distributions could ever get downgraded to anything REALLY old. Hopefully not, but we probably want to wait until after a Distributions tag that *does* support the new StatsFuns version before merging this.

**Comment by ararslan** [comment]
A Distributions tag is in the works, ref https://github.com/JuliaStats/Distributions.jl/pull/512.

**Comment by tkelman** [comment]
If that's going to take a while, we should maybe raise the julia minimum for statsfuns 0.3.0 temporarily to 0.5-.

For the very old Distributions versions with no julia dependency or before 0.3.0 so adding an extra statsfuns dependency would not work, we should add a julia 0.3 upper bound.

**Comment by ararslan** [comment]
I'm hoping it won't be long. If someone says it's okay to merge my current Distributions PR then I'll go ahead and do that, tag a version, and update this. Hoping to get this done ASAP today.

**Comment by ararslan** [comment]
Ref #5624.

**Comment by andreasnoack** [comment]
What is required to resolve the `StatsFuns` situation?

**Comment by tkelman** [comment]
we could either do fixes that say they're 0.5-only at first until distributions and this change are ready, or we could do the new tags in the same pr that loosens the statsfuns julia requirement back to allowing 0.4

**Comment by ararslan** [comment]
We might have to upper bounds for StatsBase too.

**Comment by ararslan** [comment]
Distributions versions 0.2.2-0.3.0 had no Julia version requirement but 0.2.1 requires Julia 0.2-, so I set 0.3 as an upper bound on Julia for those versions.

Distributions versions with no dependency on StatsFuns got a line that sets bounds at 0.0.0, 0.3.0. Existing StatsFuns dependencies got 0.3.0 as an upper bound if none existed, or were left as-is otherwise.

Is this what you had in mind, @tkelman?

**Comment by ararslan** [comment]
I won't have much time to help 🔥💧🚒  for the next several hours but I'll try to check in occasionally if I can.

**Comment by ararslan** [comment]
In the meantime I've added you two (@tkelman and @andreasnoack) as collaborators on my METADATA fork, you can make any changes to this PR if need be.

**Comment by tkelman** [comment]
ok I'll adjust this when I get in front of a desk then

**Comment by ararslan** [comment]
Thanks @tkelman!

**Pull request merged**
