### PR TITLE
Tag CombineML.jl v1.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ppalmes/CombineML.jl](https://github.com/ppalmes/CombineML.jl)
Release: [v1.1.0](https://github.com/ppalmes/CombineML.jl/releases/tag/v1.1.0)
Travis: [Travis Build Status](https://travis-ci.org/ppalmes/CombineML.jl/builds/428099879)
Diff: [vs v1.0.0](https://github.com/ppalmes/CombineML.jl/compare/8cbda38057145d314ccee6a7e3529ae63b570dd8...a209cd4083c406b6efde60c4960643facd7f4325)
`requires` vs v1.0.0: 
```diff
--- 1.0.0/requires
+++ 1.1.0/requires
@@ -1,8 +1,8 @@
-julia 0.6
+julia 0.7
 DecisionTree 0.7
 MLBase 0.6
 StatsBase 0.15
 PyCall 1.10
-MultivariateStats 0.3
-Iterators 0.3
+MultivariateStats 0.6.0
+IterTools 1.0.0
 ArrayViews 0.6
```
cc: @ppalmes

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
I can reproduce the error locally on the current release of CombineML.

**Comment by ppalmes** [comment]
it might be because JuliaCIBot is using python3 while Travis build is using python2.7

**Comment by ppalmes** [comment]
should i transition to python3 or is there a config to use python2.7?

**Comment by andreasnoack** [comment]
It might be related to Python2/3 but the problem seems to be unrelated to this package. I think it's a PyCall issue.

**Pull request merged**
