### PR TITLE
Tag RCall.jl v0.10.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaInterop/RCall.jl](https://github.com/JuliaInterop/RCall.jl)
Release: [v0.10.1](https://github.com/JuliaInterop/RCall.jl/releases/tag/v0.10.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaInterop/RCall.jl/builds/330447848)
Diff: [vs v0.10.0](https://github.com/JuliaInterop/RCall.jl/compare/737b5eae453b589e2ce9f9583816a22936522617...cd1ca1538a70684161a8ae0981e7cfeb16f72fda)
`requires` vs v0.10.0: no changes
cc: @randy3k

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by randy3k** [comment]
Do NOT merge, trying to fix the juliacibot issue discussed at https://github.com/JuliaLang/METADATA.jl/pull/12848

**Comment by randy3k** [comment]
@aviks I have determined the problem, it was because the `locale` of JuliaCIBot was set as `C` and doesn't support unicode. The relevent code is now updated in case a platform doesn't support unicode. It is now ready to be merged (the traivs macOS builds are very slow as they are a lot of [backlogs](https://www.traviscistatus.com))

**Comment by richardreeve** [comment]
@randy3k The backlogs aren't being resolved as far as I can see (at least for the time-being) - the travis notes just say they're cancelling old jobs, but it doesn't seem to be helping - or at least none of my macOS tests are being done. I've just set allow_failures to include osx for now, and set fast_finish to true. I figure I'll switch it back when they get it fixed.

**Comment by randy3k** [comment]
@aviks Do you have any ideas why METADATA travis build failed?

**Pull request merged**
