### PR TITLE
A few compat issues and drop 0.5 since it doesn't work anymore

### PR DESCRIPTION
**Pull request by quinnj**
cc: @aviks 

As far as I can tell, no METADATA travis checks are passing while we continue to try and check w/ 0.5, so this PR drops it.

### CODE REVIEW

**Comment by omus** [comment]
Would be nice to enforce that new tags require Julia 0.6 or above as we aren't running tests on 0.5 anymore.

**Comment by quinnj** [comment]
Yeah, we could do that. I wonder if attobot could help in enforcing this at all (i.e. fail to even PR if 0.5 is still the minimum), @simonbyrne, does attobot do checks like that?

**Comment by andreasnoack** [comment]
@ararslan Isn't there some more steps required here if we are dropping 0.5 support?

**Comment by quinnj** [comment]
Just pushed a commit to to require 0.6 as the minimum julia version.

**Comment by simonbyrne** [comment]
It's not completely trivial, but we could add it to AttoBot: essentially just need a way to parse the REQUIRE file.

**Comment by quinnj** [comment]
I think we should merge this as-is and figure out proper dropping of 0.5 later. Holding up the entire package ecosystem is not ok, IMO.

**Comment by ararslan** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/12729. @aviks did not want to require 0.6 at a minimum in METADATA yet.

**Comment by aviks** [comment]
Yes, I had disagreed with  that then, but our hands are forced now, I
suppose.

**Comment by ararslan** [comment]
Okay. I've reopened https://github.com/JuliaLang/METADATA.jl/pull/12729, which will need some updating.

**Pull request merged**
