### PR TITLE
Register GenericSVD

### PR DESCRIPTION
**Pull request by simonbyrne**
https://github.com/simonbyrne/GenericSVD.jl

### CODE REVIEW

**Comment by tkelman** [comment]
Travis should have failed here, this needs a tagged version.

**Comment by simonbyrne** [comment]
I wasn't sure how it worked: the [docs](http://docs.julialang.org/en/release-0.4/manual/packages/) seem to imply that I should tag after being registered with METADATA.

**Comment by tkelman** [comment]
We should fix the docs then, because registering without tagging isn't very useful and travis explicitly fails for that. Travis did not run here, don't know why.

**Comment by tkelman** [comment]
Closing and reopening as an experiment to try to get Travis to run.

**Pull request merged**
