### PR TITLE
Tag KernelDensity.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/KernelDensity.jl](https://github.com/JuliaStats/KernelDensity.jl)
Release: [v0.5.0](https://github.com/JuliaStats/KernelDensity.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/KernelDensity.jl/builds/414860439)
Diff: [vs v0.4.1](https://github.com/JuliaStats/KernelDensity.jl/compare/bf4191d3eeada071d308b058c922b2aba6aa4003...a58dda2608df2aa7be79619ad050b61d48170637)
`requires` vs v0.4.1: 
```diff
--- 0.4.1/requires
+++ 0.5.0/requires
@@ -1,6 +1,6 @@
-julia 0.6
-Compat 0.17
+julia 0.7
 StatsBase
 Distributions
 Optim
 Interpolations
+FFTW
```
cc: @awllee

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by awllee** [comment]
It seems that JuliaCIBot does not run Julia v0.7

**Comment by andreasnoack** [comment]
We are working on fixing CIBot so just ignore for now.

Why not fix the package for Julia 1.0 before release?

**Comment by awllee** [comment]
It should hopefully be fixed --- failures are due to Optim.jl --- unless other packages 0.7/1.0 changes break it.

**Comment by andreasnoack** [comment]
I've just merged the Optim PR so could you add a new lower bound for Optim, delete this tag and reapply it on a commit which includes the new bound?

**Comment by andreasnoack** [comment]
As mentioned in #16634, we might as well handle this with upper bounds for older versions of Optim instead.

**Comment by awllee** [comment]
I don't understand; in any case it seems to me that more precise requirement specifications will be required fairly generally in the future once the package ecosystem settles down a bit.

Requested change is in the pull request above, which can still be merged, but tagging a new release is probably unnecessary.

**Pull request merged**
