### PR TITLE
Tag ROCAnalysis v0.1.0 [https://github.com/davidavdav/ROCAnalysis.jl]

### PR DESCRIPTION
**Pull request by davidavdav**
Dropping support for julia-0.3

### CODE REVIEW

**Comment by tkelman** [comment]
cc @diegozea looks like this caused a test failure in MiToS.jl  http://pkg.julialang.org/logs/MIToS_0.4.log

**Comment by davidavdav** [comment]
Two packages declaring `AUC()`.  `ROCAnalysis.AUC()` is a courtesy for people thinking in terms of positive metrics, higher is better.  Personally I believe in error metrics, lower is better.

**Comment by diegozea** [comment]
Thanks!

**Comment by diegozea** [comment]
I import `AUC` from `ROCAnalysis` now.

**Pull request merged**
