### PR TITLE
Tag StatPlots.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPlots/StatPlots.jl](https://github.com/JuliaPlots/StatPlots.jl)
Release: [v0.8.0](https://github.com/JuliaPlots/StatPlots.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPlots/StatPlots.jl/builds/414872433)
Diff: [vs v0.7.3](https://github.com/JuliaPlots/StatPlots.jl/compare/4ec9c0ae312476c3619f2735e03123c735dc013b...48b9d506e4e9496f8eb6eb48a5ec5bdf63a398f3)
`requires` vs v0.7.3: 
```diff
--- 0.7.3/requires
+++ 0.8.0/requires
@@ -1,4 +1,4 @@
-julia 0.6
+julia 0.7
 
 Reexport
 Plots 0.14
```
cc: @piever

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like tests are failing on Julia 1.0 (nightly) and testing isn't enabled on 0.7 and 1.0.

**Comment by piever** [comment]
Now tests are enabled. It works on Julia 0.7, I think it's updated also for Julia 1.0 but tests fail there due to some dependencies.

**Comment by andreasnoack** [comment]
It looks like the issue is Plots.jl. Do you know what the status is for Plots.jl wrt Julia 1.0 updates?

**Comment by mkborregaard** [comment]
There are errors, but they come from failing dependencies Optim and KernelDensity. Plots works.

**Comment by andreasnoack** [comment]
Looks like this would need to wait for Optim, https://travis-ci.org/JuliaPlots/StatPlots.jl/jobs/415054295#L726

**Comment by andreasnoack** [comment]
Just merged Optim so this probably just needs new bounds on Optim

**Comment by mkborregaard** [comment]
Shouldn't that be taken care of by the shared julia 0.7 lower bound of both this and Optim?

**Comment by andreasnoack** [comment]
I believe the resolver could still decide to install this together with Optim 0.15.x which would fail. However, the proper fix might be to add upper bounds on Optim < 0.16. Could you try to restart the Travis tests such that we can verify that tests pass?

**Comment by mkborregaard** [comment]
The resolver handles Optim correctly, failure is due to https://github.com/JuliaLang/METADATA.jl/pull/16625 not being merged.

**Comment by andreasnoack** [comment]
I've just merged it

**Comment by mkborregaard** [comment]
It should run now. Would you still like me to lower-bound the dep on Optim and KernelDensity? Not sure what's preferred for clarity.

**Comment by andreasnoack** [comment]
If you are not using any API changes in Optim and that StatPlots has only been failing because Optim failed then it is probably more correct to set an upper bound on Optim only.

**Comment by andreasnoack** [comment]
Looks like there is another issue. This time in Interpolations https://travis-ci.org/JuliaPlots/StatPlots.jl/jobs/415054295#L742

**Comment by mkborregaard** [comment]
All right, it appears that the Interpolation people are not quite ready to tag yet, though there is a 1.0 PR. We'll have to wait for them it seems.

**Comment by mkborregaard** [comment]
@andreasnoack our CI tests pass now. WRT Interpolations I believe we only depend on that via KernelDensity, which has been merged, so this should be good to merge too. Let me know if you need any adjustments on dep bounds here.

**Pull request merged**
