### PR TITLE
Tag AverageShiftedHistograms v0.3.0

### PR DESCRIPTION
**Pull request by joshday**

### CODE REVIEW

**Comment by tkelman** [comment]
Can you remove the 0.2 tags from the pr?

**Comment by joshday** [comment]
That just makes it look like a mess...let me try this again tomorrow.  I tried deleting the tags and now julia is giving me: 
```
julia> Pkg.publish()
ERROR: AverageShiftedHistograms v0.2.3 is incorrectly tagged
...
```

**Comment by tkelman** [comment]
It looked okay, you can just squash what's here.

**Comment by joshday** [comment]
Any advice on getting julia back on the same page as git?

**Comment by tkelman** [comment]
Do you have the deletion commits present in your checked out local copy of metadata?

**Pull request closed without merging**
