### PR TITLE
Tag Cairo.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphics/Cairo.jl](https://github.com/JuliaGraphics/Cairo.jl)
Release: [v0.5.0](https://github.com/JuliaGraphics/Cairo.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphics/Cairo.jl/builds/336975837)
Diff: [vs v0.4.0](https://github.com/JuliaGraphics/Cairo.jl/compare/10913a18895481fd49ec661ff6c7a5730814e962...c599c15ff07694d7f318a614d204d0e4edc6249e)
`requires` vs v0.4.0: 
```diff
--- 0.4.0/requires
+++ 0.5.0/requires
@@ -1,5 +1,5 @@
-julia 0.5
-Compat 0.39.0
+julia 0.6
+Compat 0.50.0
 Colors
 BinDeps 0.3.21
 Graphics 0.1
```
cc: @lobingera

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Luxor tests failed with the new Cairo tag

```
animation (Unix only): Error During Test
  Test threw an exception of type UndefVarError
  Expression: animate(demomovie, [Scene(demomovie, backdrop), Scene(demomovie, frame, 0:359, easingfunction=easeinoutquad)], creategif=false) == true
  UndefVarError: circle not defined
  Stacktrace:
   [1] circle at /home/jrun/Luxor/.julia/v0.6/Luxor/src/curves.jl:15 [inlined]
   [2] circle at /home/jrun/Luxor/.julia/v0.6/Luxor/src/curves.jl:24 [inlined]
   [3] frame(::Luxor.Scene, ::Int64) at /home/jrun/Luxor/.julia/v0.6/Luxor/test/animation-test.jl:21
   [4] #animate#91(::Bool, ::Int64, ::String, ::Function, ::Luxor.Movie, ::Array{Luxor.Scene,1}) at /home/jrun/Luxor/.julia/v0.6/Luxor/src/animate.jl:119
   [5] (::Luxor.#kw##animate)(::Array{Any,1}, ::Luxor.#animate, ::Luxor.Movie, ::Array{Luxor.Scene,1}) at ./<missing>:0
   [6] (::##5#6)(::String) at /home/jrun/Luxor/.julia/v0.6/Luxor/test/animation-test.jl:26
```

cc: @cormullion

**Comment by cormullion** [comment]
Yes, I call `Cairo.circle(currentdrawing.cr, x, y, r)`. Have you taken it away? :(

**Comment by lobingera** [comment]
Not intentionally

**Comment by lobingera** [comment]
@aviks Still something missing?

**Comment by andreasnoack** [comment]
I noticed that Gadfly was also relying on the imported `Graphics.circle` so maybe we should hold off a little longer and check all downstream packages.

**Comment by lobingera** [comment]
I included circle in the meanwhile.

**Comment by andreasnoack** [comment]
Wouldn't it be better if packages explicitly used the circle from `Graphics`?

**Comment by lobingera** [comment]
Maybe, maybe not. What are you thinking of?

**Comment by andreasnoack** [comment]
> Maybe, maybe not. What are you thinking of?

That it's weird that Cairo pretends to provide a function that it is actually implemented somewhere else.

**Pull request merged**
