### PR TITLE
Tag Gtk.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphics/Gtk.jl](https://github.com/JuliaGraphics/Gtk.jl)
Release: [v0.2.0](https://github.com/JuliaGraphics/Gtk.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphics/Gtk.jl/builds/414008142)
Diff: [vs v0.1.0](https://github.com/JuliaGraphics/Gtk.jl/compare/99a53d598c6c405e1b9420992e442f5fb79ff50b...6f76db1308057eda56a8a8343027e588f29a3226)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,2 +1,7 @@
-Cairo 0.0.1
-julia 0.2-
+julia 0.7
+Cairo 0.2.2
+Graphics 0.1
+BinDeps
+@windows WinRPM
+@osx Homebrew
+Compat 0.66.0
```
cc: @tknopp

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tknopp** [comment]
Deprecation warnings not fully resolved, but its important to get this out, so that depending packages will work under julia 0.7.

**Comment by tknopp** [comment]
@andreasnoack  what does `waiting for author` mean? I don't understand what the travis message means.

**Comment by andreasnoack** [comment]
skaermbillede 2018-08-09 kl 19 19 53
😉

**Comment by tknopp** [comment]
Hm wrong version number, this can be closed

**Pull request closed without merging**
