### PR TITLE
Tag ValidatedNumerics.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [dpsanders/ValidatedNumerics.jl](https://github.com/dpsanders/ValidatedNumerics.jl)
Release: [v0.8.0](https://github.com/dpsanders/ValidatedNumerics.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/dpsanders/ValidatedNumerics.jl/builds/211883403)
Diff: [vs v0.7.0](https://github.com/dpsanders/ValidatedNumerics.jl/compare/45843133bd2e074be228e702a9a7c9b55e031efe...1c0b48fda03132b02ef0550cd637785935d80eca)
`requires` vs v0.7.0: 
```diff
--- 0.7.0/requires
+++ 0.8.0/requires
@@ -1,6 +1,6 @@
-julia 0.4
+julia 0.5
 CRlibm 0.5
 Compat 0.7.11
-FixedSizeArrays 0.1.2
-ForwardDiff 0.2.0
+StaticArrays 0.3
+ForwardDiff 0.2
 RecipesBase
```
cc: @dpsanders

### CODE REVIEW

**Comment by tkelman** [comment]
I don't remember where the issue was, but IntervalConstraintProgramming has been hitting an illegal instruction crash ever since this was tagged. It's working now on 0.6, but not on 0.5. Should we maybe make this version of ValidatedNumerics 0.6-only?

**Comment by dpsanders** [comment]
On 4 May 2017 7:25 a.m., "Tony Kelman" <notifications@github.com> wrote:

> I don't remember where the issue was, but IntervalConstraintProgramming
> has been hitting an illegal instruction crash ever since this was tagged.
> It's working now on 0.6, but not on 0.5. Should we maybe make this version
> of ValidatedNumerics 0.6-only?
>

It works fine on 0.5; it's just when it's inside `@testset` that something
bizarre happens.

**Comment by tkelman** [comment]
Ah right. Maybe make an 0.5-only tag that doesn't use testsets just to get things passing?

**Comment by dpsanders** [comment]
Good idea, I'll try something along those lines.

**Pull request merged**
