### PR TITLE
Tag GLWindow.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGL/GLWindow.jl](https://github.com/JuliaGL/GLWindow.jl)
Release: [v0.3.0](https://github.com/JuliaGL/GLWindow.jl/releases/tag/v0.3.0)
Diff: [vs v0.2.1](https://github.com/JuliaGL/GLWindow.jl/compare/acc648923bb9b044d3e75e85de5802f9f44aef3e...f18fee9c2c76eb228d962747b2d9da83092e8ea3)
`requires` vs v0.2.1: 
```diff
--- 0.2.1/requires
+++ 0.3.0/requires
@@ -1,4 +1,5 @@
-julia 0.4
+julia 0.5
+
 ModernGL
 GLAbstraction
 GLFW
@@ -8,4 +9,4 @@
 ColorTypes
 FixedPointNumbers
 FixedSizeArrays
-FileIO
+FileIO
```
cc: @SimonDanisch

### CODE REVIEW

**Comment by SimonDanisch** [comment]
@tkelman can we merge this and https://github.com/JuliaLang/METADATA.jl/pull/7675, https://github.com/JuliaLang/METADATA.jl/pull/7626
Now that GLVisualize is already tagged but not these, GLVisualize's tagged version doesn't work currently!

**Comment by tkelman** [comment]
Okay will look over them. Should add upper bounds when you introduce breaking changes like that.

**Comment by SimonDanisch** [comment]
Okay, that does make sense... thanks a lot!

**Comment by SimonDanisch** [comment]
will do with the next tag, which needs to happen very soon! ;)

**Pull request merged**
