### PR TITLE
Register SVMLightLoader: v0.1.0, v0.2.0

### PR DESCRIPTION
**Pull request by IshitaTakeshi**
The Loader of svmlight / liblinear format files.

### CODE REVIEW

**Comment by kshyatt** [comment]
Does this really only work with `julia 0.3.2-` and pre-releases of 0.3? You might want to update `REQUIRE`.

**Comment by tkelman** [comment]
`0.3.2-` means anything newer than `0.3.1`, so that's fine. It's `0.3-` that we're trying to get rid of.

**Comment by kshyatt** [comment]
Ah, ok. Awesome :).

**Comment by IshitaTakeshi** [comment]
Thanks!

**Pull request merged**
