### PR TITLE
Register QRupdate: v1.0.0

### PR DESCRIPTION
**Pull request by mpf**

### CODE REVIEW

**Comment by tkelman** [comment]
This is great. FactCheck is a test only dependency, right? If so it can be moved to `test/REQUIRE`

**Comment by tkelman** [comment]
could you rebase out that merge commit? it's not necessary and clutters up the history with a bunch of unrelated changes

**Comment by mpf** [comment]
Tony: I hit the limits of my git knowledge. Would you prefer me to close to close the pull request and start from scratch with the suggested changes to test/REQUIRE?

**Comment by mpf** [comment]
Thanks for the suggestion. The FactCheck dependency is now in `test/REQUIRE`.

**Pull request merged**
