### PR TITLE
Tag SoftConfidenceWeighted v0.1.4 [https://github.com/IshitaTakeshi/S…

### PR DESCRIPTION
**Pull request by IshitaTakeshi**
…oftConfidenceWeighted.jl]

### CODE REVIEW

**Comment by tkelman** [comment]
Can you push the git tag so it's visible under https://github.com/IshitaTakeshi/SoftConfidenceWeighted.jl/releases ?

**Comment by IshitaTakeshi** [comment]
pushed

**Comment by tkelman** [comment]
Do you want this to still work on Julia 0.4? If so it needs to use `Compat` version 0.8.4 or newer for `view`.

**Comment by IshitaTakeshi** [comment]
But tests passed on Julia 0.4?

**Comment by IshitaTakeshi** [comment]
No I don't want to support Julia 0.4

**Comment by IshitaTakeshi** [comment]
Should I rewrite REQUIRE and push again?

**Comment by tkelman** [comment]
Yes, though if you're dropping 0.4 support then it should use a new package minor version number.

**Comment by IshitaTakeshi** [comment]
You mean that I should write `julia 0.5` in REQUIRE?

**Comment by tkelman** [comment]
Yes, if you want to drop support for Julia 0.4 with future versions.

**Pull request closed without merging**
