### PR TITLE
Register new package Dolang.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [EconForge/Dolang.jl](https://github.com/EconForge/Dolang.jl)
Release: [v0.1.0](https://github.com/EconForge/Dolang.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/EconForge/Dolang.jl/builds/243459624)
cc: @sglyon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@sglyon This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
Importing an optional dependency in a try-catch is not compatible with precompilation, since the state of whether the dependency is available won't be tracked correctly.

**Comment by sglyon** [comment]
Is the only issue that users who install the optional dependency after this package has been precompiled won't see the optional dependency until after another precompile happens?

If so, I know about that issue and am totally happy to live with it.

**Comment by tkelman** [comment]
and the reverse, if someone removes the dependency after your package has been precompiled. Having to manually manage the cache defeats the purpose of automatic precompilation.

**Comment by sglyon** [comment]
Last I checked the optional dependency (SymEngine) is difficult to install behind a corporate firewall. That's the only reason we have it as conditional. 

Is there any other way I can do this that would work with Precompilation

If not, unfortunately, I don't see a way around what I'm doing.

**Comment by tkelman** [comment]
Disable precompilation if you do what you're doing.

**Comment by sglyon** [comment]
OK, I could do that as a last resort.

Do you know of any other alternatives. I'd love to keep pre-compilation _and_ the optional dependency

**Comment by tkelman** [comment]
Without https://github.com/JuliaLang/julia/pull/21743, nothing nice and fully precompilation-compatible. Could make a separate package that depends on both. Or maybe refactor so all references to the optional package happen only at runtime, assuming it's been loaded into Main.

**Comment by sglyon** [comment]
That's helpful, thanks.

I think for now I'll just do `__precompile__(false)`

**Pull request merged**
