### PR TITLE
Register FMIndexes: v0.0.1

### PR DESCRIPTION
**Pull request by bicycle1885**
https://github.com/BioJulia/FMIndices.jl

### CODE REVIEW

**Comment by bicycle1885** [comment]
Wait a moment! FMIndexes.jl may be a better name.

**Comment by dcjones** [comment]
Great work, Kenta!

"Indexes" and "indices" are both valid and about equally used (e.g. "indexes" occurs on github 13.6e6 times, and "indices" 14e6 times). So I think either would be fine.

**Comment by bicycle1885** [comment]
Thank you :smile: 
Papers referencing to this data structure seem to prefer FM-Indexes to FM-Indices.
So now I'm feeling like to rename it.
I'm going to rename the name if either is fine.

**Comment by bicycle1885** [comment]
Renamed the package and fixed the URL (it was wrong!).
I think this is ready to be merged.

**Pull request merged**
