### PR TITLE
Tag SignedDistanceFields v0.0.1

### PR DESCRIPTION
**Pull request by yurivish**

### CODE REVIEW

**Comment by tkelman** [comment]
Could use a REQUIRE file reflecting the minimum julia version the package gets tested with.

**Comment by SimonDanisch** [comment]
Okay uhm... How to do this.
@yurivish transfered the repo to JuliaGraphics and now I tried to tag it locally. 
Register says `repo already exists` and tagging says `tag v0.0.1 already exists` but also doesn't allow me to create a newer tag...

**Comment by tkelman** [comment]
Are you on julia master or 0.4?

**Comment by SimonDanisch** [comment]
0.4 RC3

**Comment by tkelman** [comment]
Let's close this PR, you can delete the tag at the new repo from both github and your local checkout, see if that fixes things? Or just try `Pkg.tag("SignedDistanceFields", :minor)` and start from 0.1.0.

**Comment by SimonDanisch** [comment]
Okay way too easy :D feel free to close this, I can't ...
I added it to my GLVisualize tagging PR!

**Pull request closed without merging**
