### PR TITLE
Tag ImageInTerminal.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaImages/ImageInTerminal.jl](https://github.com/JuliaImages/ImageInTerminal.jl)
Release: [v0.3.0](https://github.com/JuliaImages/ImageInTerminal.jl/releases/tag/v0.3.0)
Diff: [vs v0.2.1](https://github.com/JuliaImages/ImageInTerminal.jl/compare/bc696f5238273c08b46a13fd1655e900550c1fef...4e3bdae7bcab004d93d3199046e7f5fe6b60e86c)
`requires` vs v0.2.1: 
```diff
--- 0.2.1/requires
+++ 0.3.0/requires
@@ -1,6 +1,5 @@
-julia 0.5
+julia 0.7
 Crayons 0.1.0
 ColorTypes 0.3.2
-ImageCore 0.1.1
-ImageTransformations 0.2.1
-Compat 0.17
+ImageCore 0.7
+ImageTransformations 0.3.0
```
cc: @Evizero

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please adjust the Travis tests to the new Julia requirements. It also looks like tests are failing on Julia 1.0 (nightly).

**Comment by Evizero** [comment]
Oh, I somehow forgot to update the CI scripts. Thanks for pointing that out.

I updated the CI scripts, so now it should also test on 1.0 (which should already work).

~~nightly seems broken because of dependencies that are broken there. For now nightly/latest is an accepted test failure to me, since I still have to update packages to 1.0 and I need a working  version of ReferenceTests for this (which depends on ImageInTerminal)~~ edit: nightly works as well

**Comment by Evizero** [comment]
mhm It looks like OSX is somehow broken. ~~It will take me a bit before I can look into that~~

EDIT: was an easy enough fix. it was only a problem in the tests (using QuartzImageIO on OSX resulted in different pixel values than ImageMagick, which broke the reference tests)

**Comment by Evizero** [comment]
sorry for all the noise. I am not usually so negligent. Thanks for being patient

**Comment by Evizero** [comment]
this should be ready now. the tests all pass.

Not sure what JuliaCIBot is complaining about. does it want a Project.toml or something?

**Comment by andreasnoack** [comment]
No, it is actually the Project.toml file in Colors that is problem. See https://github.com/JuliaGraphics/Colors.jl/issues/322.

**Pull request merged**
