### PR TITLE
Tag ElasticFDA.jl v0.5.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jdtuck/ElasticFDA.jl](https://github.com/jdtuck/ElasticFDA.jl)
Release: [v0.5.1](https://github.com/jdtuck/ElasticFDA.jl/releases/tag/v0.5.1)
Travis: [Travis Build Status](https://travis-ci.org/jdtuck/ElasticFDA.jl/builds/426123106)
Diff: [vs v0.5.0](https://github.com/jdtuck/ElasticFDA.jl/compare/f854d711554f553445d6229ff9424388b41068b8...683b0f795e7e876acf1ac0e7362353c1a9d6f324)
`requires` vs v0.5.0: 
```diff
--- 0.5.0/requires
+++ 0.5.1/requires
@@ -4,3 +4,4 @@
 NLopt
 ProgressMeter
 Distributions
+RecipesBase
```
cc: @jdtuck

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Errors with
```julia
ERROR: LoadError: MethodError: no method matching exp(::Array{Float64,1})
Closest candidates are:
  exp(!Matched::Float16) at math.jl:1004
  exp(!Matched::Complex{Float16}) at math.jl:1005
  exp(!Matched::Missing) at math.jl:1056
  ...
Stacktrace:
 [1] phi(::Array{Float64,1}) at /home/jrun/ElasticFDA/.julia/v0.7/ElasticFDA/src/regression_funcs.jl:92
 [2] #elastic_prediction#39(::Array{Float64,1}, ::Bool, ::Function, ::Array{Float64,2}, ::Array{Float64,1}, ::Dict{String,Any}) at /home/jrun/ElasticFDA/.julia/v0.7/ElasticFDA/src/regression.jl:463
 [3] (::getfield(ElasticFDA, Symbol("#kw##elastic_prediction")))(::NamedTuple{(:y,),Tuple{Array{Float64,1}}}, ::typeof(elastic_prediction), ::Array{Float64,2}, ::Array{Float64,1}, ::Dict{String,Any}) at ./none:0
 [4] top-level scope at none:0
```
 on 0.7.

**Comment by jdtuck** [comment]
Why is this not an error on 1.0, this makes no sense


---
Derek


On September 8, 2018 at 14:32:27 MDT, Andreas Noack <notifications@github.com> wrote:

Error with

ERROR: LoadError: MethodError: no method matching exp(::Array{Float64,1})
Closest candidates are:
  exp(!Matched::Float16) at math.jl:1004
  exp(!Matched::Complex{Float16}) at math.jl:1005
  exp(!Matched::Missing) at math.jl:1056
  ...
Stacktrace:
 [1] phi(::Array{Float64,1}) at /home/jrun/ElasticFDA/.julia/v0.7/ElasticFDA/src/regression_funcs.jl:92
 [2] #elastic_prediction#39(::Array{Float64,1}, ::Bool, ::Function, ::Array{Float64,2}, ::Array{Float64,1}, ::Dict{String,Any}) at /home/jrun/ElasticFDA/.julia/v0.7/ElasticFDA/src/regression.jl:463
 [3] (::getfield(ElasticFDA, Symbol("#kw##elastic_prediction")))(::NamedTuple{(:y,),Tuple{Array{Float64,1}}}, ::typeof(elastic_prediction), ::Array{Float64,2}, ::Array{Float64,1}, ::Dict{String,Any}) at ./none:0
 [4] top-level scope at none:0

on 0.7.

**Comment by jdtuck** [comment]
And this file didn’t change between the two versions


---
Derek


On September 8, 2018 at 15:06:43 MDT, Tucker, James Derek <jdtuck@sandia.gov> wrote:
Why is this not an error on 1.0, this makes no sense


---
Derek


On September 8, 2018 at 14:32:27 MDT, Andreas Noack <notifications@github.com> wrote:

Error with

ERROR: LoadError: MethodError: no method matching exp(::Array{Float64,1})
Closest candidates are:
  exp(!Matched::Float16) at math.jl:1004
  exp(!Matched::Complex{Float16}) at math.jl:1005
  exp(!Matched::Missing) at math.jl:1056
  ...
Stacktrace:
 [1] phi(::Array{Float64,1}) at /home/jrun/ElasticFDA/.julia/v0.7/ElasticFDA/src/regression_funcs.jl:92
 [2] #elastic_prediction#39(::Array{Float64,1}, ::Bool, ::Function, ::Array{Float64,2}, ::Array{Float64,1}, ::Dict{String,Any}) at /home/jrun/ElasticFDA/.julia/v0.7/ElasticFDA/src/regression.jl:463
 [3] (::getfield(ElasticFDA, Symbol("#kw##elastic_prediction")))(::NamedTuple{(:y,),Tuple{Array{Float64,1}}}, ::typeof(elastic_prediction), ::Array{Float64,2}, ::Array{Float64,1}, ::Dict{String,Any}) at ./none:0
 [4] top-level scope at none:0

on 0.7.

**Comment by jdtuck** [comment]
Second it passed my travis on 0.7, I am not seeing the load error

**Comment by jdtuck** [comment]
Wonder why it passed 1.0.... fixing it now

**Pull request merged**
