### PR TITLE
Tag Benchmark v0.1.1

### PR DESCRIPTION
**Pull request by Rory-Finnegan**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Thanks for submitting this. Looks like needs a Julia version.

**Comment by Rory-Finnegan** [comment]
I'm guessing that should be added to Benchmark.jl and then the METADATA version should be updated accordingly? Also, I just checked and it seems to work on a relatively recent version of 0.5, so are you okay with `julia 0.5-`?

**Comment by tkelman** [comment]
if you only provide one number then it's a lower bound. should use the lowest version of julia for which tests are regularly being run (is travis on?)

**Comment by tkelman** [comment]
if you only provide one number then it's a lower bound. should use the lowest version of julia for which tests are regularly being run (is travis on?)

**Comment by Rory-Finnegan** [comment]
@tkelman No, travis is not set up for this package.

**Comment by KristofferC** [comment]
This can be closed?

**Comment by Rory-Finnegan** [comment]
Sure, I forgot this PR was still open and I'm pretty sure the pkg is abandoned now.

**Pull request closed without merging**
