### PR TITLE
Tag Libz.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BioJulia/Libz.jl](https://github.com/BioJulia/Libz.jl)
Release: [v0.3.0](https://github.com/BioJulia/Libz.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/BioJulia/Libz.jl/builds/402829437)
Diff: [vs v0.2.4](https://github.com/BioJulia/Libz.jl/compare/2911ad2a26ec711833afad04278f7ea219b98d58...89698ec6995c76be1a7fe4a0d0dd367f2d5db935)
`requires` vs v0.2.4: 
```diff
--- 0.2.4/requires
+++ 0.3.0/requires
@@ -1,3 +1,3 @@
-julia 0.4
-Compat 0.17.0
+julia 0.6
+Compat 0.27.0
 BufferedStreams 0.2.1
```
cc: @BenJWard

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like this is breaking `Whippet`

**Comment by GunnarFarneback** [comment]
Ongoing discussion in https://github.com/BioJulia/Libz.jl/pull/61#issuecomment-404962127.

**Comment by GunnarFarneback** [comment]
Superseded by #16104.

**Comment by GunnarFarneback** [comment]
#16104 has been merged. This one can be closed and forgotten.

**Pull request closed without merging**
