### PR TITLE
Tag MIToS.jl v2.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [diegozea/MIToS.jl](https://github.com/diegozea/MIToS.jl)
Release: [v2.2.0](https://github.com/diegozea/MIToS.jl/releases/tag/v2.2.0)
Travis: [Travis Build Status](https://travis-ci.org/diegozea/MIToS.jl/builds/422594282)
Diff: [vs v2.1.2](https://github.com/diegozea/MIToS.jl/compare/0594833e98d2e782d3b7d3ee12babb84ce285bc4...20e527b0c37a65db6a80da91e3d147bab877aded)
`requires` vs v2.1.2: 
```diff
--- 2.1.2/requires
+++ 2.2.0/requires
@@ -4,16 +4,14 @@
 TranscodingStreams
 AutoHashEquals
 DataStructures
-Formatting 0.3.1
+Format
 PairwiseListMatrices
 ArgParse
-ROCAnalysis
 Clustering
 StaticArrays
 FastaIO
-FTPClient
-Requests
-PkgBenchmark
+HTTP
 NamedArrays
 RecipesBase
 ProgressMeter
+Requires
```
cc: @diegozea

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider adding upper bounds on Julia if the package doesn't work with 0.7/10 yet

**Comment by diegozea** [comment]
Yeap, it doesn't work in Julia 0.7 yet.
Is `julia 0.6 0.7` the correct REQUIRE line to make this version only support 0.6?

**Comment by andreasnoack** [comment]
Yes. That should do it.

**Comment by diegozea** [comment]
Thanks! :)

**Comment by andreasnoack** [comment]
It looks like this fails on 0.6 with
```
ERROR: LoadError: ArgumentError: Module ROCAnalysis not found in current path.
Run `Pkg.add("ROCAnalysis")` to install the ROCAnalysis package.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:435
 [2] require(::Symbol) at ./loading.jl:405
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /home/jrun/MIToS/.julia/v0.6/MIToS/test/runtests.jl, in expression starting on line 7
INFO: Testing MIToS
```

**Comment by diegozea** [comment]
`ROCAnalysis` was missing in `test/REQUIRE`
It should work now :)

**Comment by diegozea** [comment]
I think it's good now.

**Pull request merged**
