### PR TITLE
Register Xpress: v0.0.1

### PR DESCRIPTION
**Pull request by joaquimg**
Submitting Xpress.jl a wrapper for the C API of the mathematical programming solver Xpress by FICO

### CODE REVIEW

**Comment by tkelman** [comment]
Do you know if there would be any way to download a temporary evaluation copy of the solver/license for testing purposes?

**Comment by joaquimg** [comment]
On windows there is a student version at: https://community.fico.com/download.jspa
This is the easiest way by far of getting a working version.

The other options are to request an evaluation copy or an academic license, this could take a few days, @mlubin got one of those. 
If you go for the latter options tell me when you email them so that I might help if it takes too long.

**Comment by mlubin** [comment]
:+1:

**Comment by tkelman** [comment]
The package looks good. Just wondering whether it's possible to download some restricted copy and test the bindings in an automatic way on Travis CI / PackageEvaluator and the like. Probably not, that's fine if it's the case.

**Comment by joaquimg** [comment]
I would say that the answer is no...

**Comment by mlubin** [comment]
Based on my interactions with Xpress, I doubt it would be easy

**Comment by tkelman** [comment]
@aviks new package registrations should generally wait 24 hours before merging

**Pull request merged**
