### PR TITLE
Register Luxor 

### PR DESCRIPTION
**Pull request by cormullion**
Register [Luxor](https://github.com/cormullion/Luxor.jl.git).

### CODE REVIEW

**Comment by tkelman** [comment]
You should declare the dependency on `Compat` explicitly in your `REQUIRE` file, ideally with a minimum version dependency that implements the features you need

**Comment by tkelman** [comment]
You should also generally not use `Pkg.dir` to refer to the package's location, as it might be installed elsewhere - ref https://github.com/JuliaLang/julia/issues/12120 (use `dirname(@__FILE__)`, or `@__DIR__` if you declare a dependency on Compat 0.9.1).

**Comment by cormullion** [comment]
Hi Tony, yes I remember about Pkg.dir, now you mention it...

**Comment by cormullion** [comment]
@tkelman I hope I've fixed these with [this commit]( https://github.com/cormullion/Luxor.jl/commit/f87b2c822c38ed02da3f040f94e6e8cff41013d6).

**Comment by tkelman** [comment]
Looks good, though you should add the Compat lines to the requires files of the tags in this branch of your metadata fork: https://github.com/cormullion/METADATA.jl/tree/pull-request/76440969/Luxor/versions

**Comment by cormullion** [comment]
Thanks @tkelman !

**Pull request merged**
