### PR TITLE
Tag ProtoBuf v0.1.4

### PR DESCRIPTION
**Pull request by sbchisholm**

### CODE REVIEW

**Comment by tkelman** [comment]
Have you tested that this is still working on julia 0.3? If not, it should change the minimum version in require to 0.4 and use a new minor package version

**Comment by sbchisholm** [comment]
@tkelman would you like to see the changes in your PR included in this tag?

**Comment by tkelman** [comment]
not necessary to adjust a tag for travis only changes. looks like it still works fine on 0.3.

**Comment by sbchisholm** [comment]
Thanks

**Pull request merged**
