### PR TITLE
New package Factors.jl

### PR DESCRIPTION
**Pull request by hamzaelsaawy**

### CODE REVIEW

**Comment by timholy** [comment]
Is the name "Factors" a bit too generic for something specifically targeted at Bayesian and Markov networks? I was expecting it to be about polynomials or matrices.

**Comment by quinnj** [comment]
I thought it was another `CategoricalArrays`/`PooledDataArray` type of implementation (since they're called factors in R)

**Comment by hamzaelsaawy** [comment]
Would renaming to `PGMFactors` be more appropriate?

**Comment by tkelman** [comment]
That would be an improvement, though the PGM acronym isn't necessarily common knowledge.

**Comment by MikeInnes** [comment]
@hamzaelsaawy the choice of name is yours; if you want to stick with this, let me know and I can merge.

**Pull request closed without merging**
