### PR TITLE
PyAMG.jl minor update

### PR DESCRIPTION
**Pull request by cortner**
this tags a new version with a requested enhancement (iteration residuals).

### CODE REVIEW

**Comment by KristofferC** [comment]
Build is failing on 0.4. Do you still intend to support it?

**Comment by cortner** [comment]
Hadn't planned to, but there is no reason it should fail. I will check what happened.

**Comment by cortner** [comment]
ok, tests pass on v0.4. Are there instructions somewhere that I can follow on how to update this PR?

**Comment by cortner** [comment]
hm - I pushed an updated METADATA, but it doesn't show here?

**Comment by KristofferC** [comment]
Did you push to the correct branch (the one you made the PR from)?

**Comment by cortner** [comment]
I think this is now correct?

**Comment by ararslan** [comment]
Looks like you still need to push the v0.0.9 tag to the PyAMG.jl repository.

**Comment by cortner** [comment]
I tried `git push --tags cortner +metadata-v2:PyAMG`, but it just tells me that `Everything up-to-date` . What now?

**Comment by cortner** [comment]
ok, done.

**Comment by ararslan** [comment]
Awesome. Now you'll want to close and reopen this PR to retrigger the Travis build.

**Comment by ararslan** [comment]
Okay cool, Travis is happy now.

As an aside, I noticed that your tests do pass but they aren't actually using the `Base.Test` framework. In general it's preferable to use `@test` rather than `@assert` for package tests.

**Comment by cortner** [comment]
I can fix that - do you care for this v?

**Comment by cortner** [comment]
dont merge this yet, I'll quickly fix the `runtests.jl` and submit.

**Comment by cortner** [comment]
I hope this is now ok.

**Comment by cortner** [comment]
out of curiosity: to delete the tag and tag again, I actually go to `METADATA/PyAMG/versions` and `rm` the `0.0.9` directory, comma, delete the tag in the `PyAMG` repository, then do `PkgDev.tag("PyAMG")`, then finally push both PyAMG and METADATA again. Is this actually the most efficient way right now?

**Comment by kmsquire** [comment]
@cortner If you're working manually, that's probably the most efficient.  But check out [attobot](https://github.com/attobot/attobot) if you get the chance.  It still requires some minor effort if you screw up a tag, but it's well described how to do this on the web page, and it's all done through github.

**Comment by tkelman** [comment]
@kmsquire messy pr's like this one should be squash merged

**Comment by kmsquire** [comment]
Whoops!  I did that with the other ones, but somehow missed this one.

**Comment by cortner** [comment]
thank you.

**Pull request merged**
