### PR TITLE
Register ForecastEval package

### PR DESCRIPTION
**Pull request by colintbowers**
Register new package FoecastEval

### CODE REVIEW

**Comment by tkelman** [comment]
Would Travis CI pass if you enabled it?

**Comment by colintbowers** [comment]
I'm not 100% sure how Travis CI works. I've got a full set of tests in runtests.jl, and `Pkg.test("ForecastEval")` passes them all on my local machine. Getting Travis CI running is next on my list of tasks for my both packages (ForecastEval and DependentBootstrap), but unfortunately I've got a fair bit of other work to get through before I can look at it again. I thought I'd get the package registered in the meantime...

**Comment by tkelman** [comment]
go to https://travis-ci.org/colintbowers/ForecastEval.jl, click enable, that should be all you need to start

**Comment by colintbowers** [comment]
Done. I hadn't bothered much with Travis for this package because I kept getting "build unknown" when I attempted to activate it for my DependentBootstrap package, even though I thought I'd followed instructions to the letter. But I just noticed that sometime in the last few days I'm now getting "tests passed" for my DependentBootstrap package. Obviously I wasn't patient enough...

Thanks for your help. I'm not familiar with most of these tools.

**Comment by tkelman** [comment]
It would be worthwhile to add a package description other than "No description, website, or topics provided." That will be populated into the listing at pkg.julialang.org

**Comment by colintbowers** [comment]
Done!

Cheers,

Colin

**Pull request merged**
