### PR TITLE
Tag SimpleWeightedGraphs.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphs/SimpleWeightedGraphs.jl](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl)
Release: [v0.1.0](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/releases/tag/v0.1.0)
Diff: [vs v0.0.1](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/compare/37b219bd8c2a794dae931a7877b40adeb600286d...b8036815b5a5e0ee310430a309d870c272cdb506)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.1.0/requires
@@ -1,2 +1,2 @@
 julia 0.6
-LightGraphs 0.9.1
+LightGraphs 0.10.1
```
cc: @sbromberger

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by sbromberger** [comment]
@tkelman welcome back. Did you close/reopen to kickstart Travis again?

**Comment by tkelman** [comment]
Travis was fine I believe, kicking the CIBot

**Comment by sbromberger** [comment]
Possible to get this merged, please?

**Comment by sbromberger** [comment]
Thanks, as always, @tkelman !

**Pull request merged**
