### PR TITLE
Tag Random123.jl v1.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [sunoru/Random123.jl](https://github.com/sunoru/Random123.jl)
Release: [v1.2.0](https://github.com/sunoru/Random123.jl/releases/tag/v1.2.0)
Diff: [vs v1.1.0](https://github.com/sunoru/Random123.jl/compare/ec1624bc7e3546d2da0cb74cd20dfcf6d89b923f...234208c4cbbc1fb961dcd1087fd86bfe5b282684)
`requires` vs v1.1.0: 
```diff
--- 1.1.0/requires
+++ 1.2.0/requires
@@ -1 +1,2 @@
 julia 0.7
+RandomNumbers
```
cc: @sunoru

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by sunoru** [comment]
Why is the CI status still not reported... https://travis-ci.org/JuliaLang/METADATA.jl/builds/495152307

**Comment by GregPlowman** [comment]
How can we prod this PR?
Would closing and reopening help?

**Comment by GregPlowman** [comment]
CI has magically gone green. I think we're good to go!

**Comment by sunoru** [comment]
Can you help merge this? @ChrisRackauckas

**Comment by GregPlowman** [comment]
Thanks!

**Pull request merged**
