### PR TITLE
Tag Distances v0.3.2 [https://github.com/JuliaStats/Distances.jl]

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaStats/Distances.jl/issues/50

### CODE REVIEW

**Comment by KristofferC** [comment]
cc @davidavdav

**Comment by davidavdav** [comment]
thx

**Comment by tkelman** [comment]
You're using Compat without putting it in your REQUIRE file.

**Comment by ararslan** [comment]
Ah yeah, it's in the test/REQUIRE but not in the main REQUIRE.

**Pull request closed without merging**
