### PR TITLE
Tag TypedTables v0.0.6

### PR DESCRIPTION
**Pull request by andyferris**
bugfix

### CODE REVIEW

**Comment by tkelman** [comment]
be sure to push the commit https://github.com/FugroRoames/TypedTables.jl/commit/899016651079e50c56b54db6e090427212ed88d5 to master, right now it only exists as the tag

**Comment by andyferris** [comment]
Haha I just realized that one. Pushed.

I wonder if we should make `PkgDev.publish()` perform a check for this one?

**Comment by tkelman** [comment]
That would not be a bad idea.

**Comment by nalimilan** [comment]
Indeed, it's very common to forget pushing a tag, commits, or both, and this makes your life harder @tkelman!

**Comment by tkelman** [comment]
I'll write a metadata auto-review bot sooner or later.

**Pull request merged**
