### PR TITLE
Tag Playground v0.0.3

### PR DESCRIPTION
**Pull request by Rory-Finnegan**
Moved the test requirements for DeclarativePackages.jl and Lint.jl from `.travis.yml` into `test/REQUIRE`.

### CODE REVIEW

**Comment by milktrader** [comment]
This looks like a cool package. I'm working on a similar project with the meme of Pantry.

**Comment by Rory-Finnegan** [comment]
@milktrader Cool, if your code is online somewhere I'd be interested in seeing how you're doing things.

**Comment by milktrader** [comment]
Here is a screen shot, but I'm still a bit away from isolating each Julia session to see only a specified package directory. I noticed you're using @rened DeclarativePackages so I'm looking into using that in some way.

screen shot 2015-10-07 at 8 33 43 am

**Comment by milktrader** [comment]
Here is some more API spit balling

screen shot 2015-10-07 at 9 12 19 am

**Pull request merged**
