### PR TITLE
tag v0.4.3 of DataStructures

### PR DESCRIPTION
**Pull request by rawls238**
@kmsquire @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
be sure to push the git tag so it shows up at https://github.com/JuliaLang/DataStructures.jl/releases

**Comment by rawls238** [comment]
:+1: will add that manually. Next time I'll use `PkgDev` for that, sorry about that :)

**Comment by tkelman** [comment]
Whatever works. PkgDev might still be a little rough around the edges.

**Comment by rawls238** [comment]
@tkelman added a tag on the repo

**Comment by tkelman** [comment]
Great! Really glad to see you joining in on maintainership here. I'll merge when green if @kmsquire or anyone else who's more familiar with this package doesn't beat me to it.

**Pull request merged**
