### PR TITLE
Tag DataFrames.jl v0.15.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaData/DataFrames.jl](https://github.com/JuliaData/DataFrames.jl)
Release: [v0.15.1](https://github.com/JuliaData/DataFrames.jl/releases/tag/v0.15.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaData/DataFrames.jl/builds/463204590)
Diff: [vs v0.15.0](https://github.com/JuliaData/DataFrames.jl/compare/dcac4bc383231388629f25877e7b1304cffe0632...f0efb17128c052c3532e6a1211f1419e937c01fd)
`requires` vs v0.15.0: no changes
cc: @nalimilan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Shouldn't this be 0.16 since 0.15.0 will be broken on Julia 1.1?

**Comment by nalimilan** [comment]
I don't really see the link between 1.1 support and version change.

**Comment by fredrikekre** [comment]
Version 0.15.0 doesn't work on Julia 1.1, so it should be upper bounded, and it seems weird to set such bounds between 0.15.0 and 0.15.1. On Julia 1.1 this release will be the only one working, and shouldn't that start on a a new minor number?

**Comment by nalimilan** [comment]
I wouldn't think so, as I don't see the advantage. We've just tagged 0.15 with major API changes, bumping immediately to 0.16 would just create confusion IMHO.

**Comment by fredrikekre** [comment]
Ok.

**Pull request merged**
