### PR TITLE
Tag Optim.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/Optim.jl](https://github.com/JuliaNLSolvers/Optim.jl)
Release: [v0.8.0](https://github.com/JuliaNLSolvers/Optim.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaNLSolvers/Optim.jl/builds/237184606)
Diff: [vs v0.7.8](https://github.com/JuliaNLSolvers/Optim.jl/compare/250b50ab5f9bb87576c623fa20fdafb981ce40a1...0eee33607a19320851a9ce51333e005ffd324262)
`requires` vs v0.7.8: 
```diff
--- 0.7.8/requires
+++ 0.8.0/requires
@@ -1,6 +1,8 @@
-julia 0.4
-Calculus
-ForwardDiff 0.3.0 0.5.0
+julia 0.5
 PositiveFactorizations
 Compat 0.18.0
-LineSearches 0.1.2 1.0.0-
+LineSearches 2.1.0
+Calculus
+NLSolversBase
+ForwardDiff 0.3.0 0.5.0
+ReverseDiff 0.0.3
```
cc: @pkofod

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by pkofod** [comment]
Does the travis message mean that Optim is causing problems for those packages with this tag?

**Comment by tkelman** [comment]
JuliaCIBot sort of says that, but it looks like mostly a resolver issue, something is inconsistent about the bounds here. Will have to look into it in more detail.

**Comment by pkofod** [comment]
Ah, this is very likely a clash with NLsolve because we are using the new LineSearches.

**Comment by pkofod** [comment]
For what it's worth, ReverseDiff is part of this clash of packages https://github.com/JuliaDiff/ReverseDiff.jl/blob/master/REQUIRE#L3

**Comment by pkofod** [comment]
This won't work yet. but I'll just reuse this PR by deleting the tag at the Optim repo, and creating a new v0.8.0 tag once it's ready.

**Comment by pkofod** [comment]
ref https://github.com/JuliaNLSolvers/Optim.jl/pull/421 for the PR that will form the "new" v0.8.0

**Comment by tkelman** [comment]
Actually since you're not only dropping 0.4 support but also 0.5 support at the same time, it may be prudent to bump the minor version number by 2. Just in case there's a need to backport some bug fix to an 0.5-only release, could leave space for that to be 0.8.x and make this 0.6-only series 0.9.x.

**Comment by pkofod** [comment]
Fine by me.

**Pull request closed without merging**
