### PR TITLE
Temporal + Indicators (one more time...)

### PR DESCRIPTION
**Pull request by dysonance**
Okay third pull request, sorry for the noobish spamming of the pull requests as I'm learning Git, but all prior recommendations should be taken care of at this point. Any chance today's my lucky day?

For reference, the prior two PR's are linked below:
[First one](https://github.com/JuliaLang/METADATA.jl/pull/4995)
[Second one](https://github.com/JuliaLang/METADATA.jl/pull/5052)

Let me know if any further concerns and I will try to address them ASAP.

### CODE REVIEW

**Comment by tkelman** [comment]
Everything looks right here. No worries at all about the git learning curve, gotta learn somehow.

**Comment by dysonance** [comment]
**You are a saint.**

Thanks for all the help. So is this the day that my first ever open source development package goes public? Or are there other steps left to take care of?

**Comment by dysonance** [comment]
@tkelman I've noticed neither package isn't listed in the Julia package listing. I'm curious if there's any further steps I need to take? My assumption was that if merged into the METADATA repo, the packages would be publicly listed. I tried doing Pkg.add on JuliaBox, and indeed they can be added, but I guess I'm curious why they wouldn't be autopopulated into the package listing?

**Comment by tkelman** [comment]
The only person who has commit access to update pkg.julialang.org is defending his thesis in about a week.

**Comment by dysonance** [comment]
Lol, nuf said... Thanks for the quick answer. Best of luck to him then!

**Comment by dysonance** [comment]
@tkelman Sorry to bug you again, just wanted to make sure I'm understanding the documentation correctly. For reference on future development, I will need to create new pull requests for each new version I want to publish? (i.e. it's not enough to make the changes, re-tag, and push the commits to my github repos?)

In summary, if I'm using Git, the process is:
- Edit code
- `git tag <v0.0.x>`
- `git push origin master`
- `cd ../METADATA`
- `git push dysonance <metadata-new> --force`
- Go to my METADATA fork and create a pull request

And if I can figure out how to let Julia do it on its own:
- Edit code
- `Pkg.tag(...)`
- `Pkg.publish()`
- Go to my METADATA fork and create a pull request

**Comment by tkelman** [comment]
You're missing a "create new `versions/0.0.x/requires` and `versions/0.0.x/sha1` files" between `cd ../METADATA` and `git push ...`, but otherwise yes everything there is correct.

**Comment by dysonance** [comment]
Excellent, I'm learning! What commands would I use to accomplish those two steps? Particularly the new sha1 files, which I don't know the first thing about.

**Comment by tkelman** [comment]
Inside `Pkg.dir("MyPackage")`, run `git log -1` and copy-paste the sha into the `METADATA/MyPackage/versions/x.y.z/sha1` file. The `METADATA/MyPackage/versions/x.y.z/requires` file is just a copy of the package's `REQUIRE` file (yeah it's a bit confusing that they have different file names...). Once you've populated those files in METADATA, do
```
git checkout -b newtag
git add MyPackage/versions/x.y.z/*
git commit -m "Tag MyPackage version x.y.z"
git push dysonance newtag
```

**Comment by dysonance** [comment]
So:
- Edit code
- `git tag <v0.0.x>`
- `git commit -a -m "message" && git push origin master`
- `mkdir ../METADATA/<MyPackage>/0.0.x`
- `git rev-list -n 1 HEAD > ../METADATA/<MyPackage>/0.0.x/sha1`
- `cp REQUIRE ../METADATA/<MyPackage>/0.0.x/requires`
- `cd ../METADATA/<package>`
- `git push dysonance <metadata-new> --force`
- Go to my METADATA fork and create a pull request

**Comment by tkelman** [comment]
You'll need to add and commit the new METADATA files too.

**Comment by dysonance** [comment]
- Edit code
- `git tag <v0.0.x>`
- `git commit -a -m "message" && git push origin master`
- `mkdir ../METADATA/<MyPackage>/0.0.x`
- `git rev-list -n 1 HEAD > ../METADATA/<MyPackage>/0.0.x/sha1`
- `cp REQUIRE ../METADATA/<MyPackage>/0.0.x/requires`
- `cd ../METADATA`
- `git add -A && git commit -a -m "new MyPackage version"`
- `git push dysonance <metadata-new> --force`
- Go to my METADATA fork and create a pull request

**Comment by tkelman** [comment]
Yep. If there's anything that needs clarifying at http://docs.julialang.org/en/release-0.4/manual/packages/#tagging-and-publishing-your-package, a doc PR would be welcome.

**Comment by dysonance** [comment]
Yeah absolutely. I wanna make sure I have this process under my belt and learn how to deal with anything weird that might pop up first. But after that, I'm happy to help contribute to the docs :smile:

**Pull request merged**
