### PR TITLE
Various updates including Julia v0.5

### PR DESCRIPTION
**Pull request by EricForgy**
- Add PlotlyJS example
- Add support for IJulia (experimental)
- Updates for Julia v0.5

### CODE REVIEW

**Comment by tkelman** [comment]
If you use Compat, it needs to be listed explicitly in your REQUIRE file, with a minimum version number that implements the features you need.

**Comment by EricForgy** [comment]
Ok. Thanks. Do I need to tag a new version to make this minor change? Is there a way to revise and keep the same tag? If so, how? Thank you.

**Comment by EricForgy** [comment]
I tried rebase, but looks like I made a mess:

image

**Comment by tkelman** [comment]
Yes, you could have modified the `requires` file of the 0.0.5 tag in-place in this branch of your METADATA fork.

**Comment by EricForgy** [comment]
Ok. Since I went ahead and tagged a new version, is it ok to merge as is?

**Pull request merged**
