### PR TITLE
Register new package StaticLint.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ZacLN/StaticLint.jl](https://github.com/ZacLN/StaticLint.jl)
Release: [v0.0.1](https://github.com/ZacLN/StaticLint.jl/releases/tag/v0.0.1)
cc: @ZacLN

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ZacLN This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please enable travis testing and make sure that tests pass on the relevant versions of Julia.

**Comment by ZacLN** [comment]
Sorry for slowness, travis enabled

**Comment by andreasnoack** [comment]
It looks like https://travis-ci.org/ZacLN/StaticLint.jl is still inactive

**Comment by ZacLN** [comment]
But it says travis has passed here? I'm confused

**Comment by andreasnoack** [comment]
That METADATA's Travis tests which check if the release metadata seems right not Travis testing for your package.

**Comment by ZacLN** [comment]
OK but [this](https://github.com/ZacLN/StaticLint.jl/runs/16565759) seems to have run travis?

**Comment by andreasnoack** [comment]
Ah. That one is running on https://travis-ci.com and not org. Please update the link in your README.

**Pull request merged**
