### PR TITLE
Tag ClimateTools.jl v0.9.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Balinus/ClimateTools.jl](https://github.com/Balinus/ClimateTools.jl)
Release: [v0.9.0](https://github.com/Balinus/ClimateTools.jl/releases/tag/v0.9.0)
Diff: [vs v0.8.0](https://github.com/Balinus/ClimateTools.jl/compare/d59380e37f169819906839cb55cec00c3ed76a7b...5a1989e97a01d89c0389365ae72dc095d5a543db)
`requires` vs v0.8.0: 
```diff
--- 0.8.0/requires
+++ 0.9.0/requires
@@ -1,11 +1,14 @@
-julia 0.6
-NetCDF 0.4.1
-Shapefile 0.2.0
-AxisArrays 0.1.3
-PyCall 1.11.1
-PyPlot 2.3.2
-ArgCheck 0.1.0
-Interpolations 0.7.0
-ProgressMeter 0.5.5
-NCDatasets 0.0.9
-Polynomials 0.3.0
+julia 0.7
+NetCDF 0.7.1
+Shapefile 0.4.0
+AxisArrays 0.3.0
+PyCall 1.18.5
+PyPlot 2.6.3
+ArgCheck 1.0.0
+Interpolations 0.8.0
+ProgressMeter 0.6.0
+NCDatasets 0.3.2
+Polynomials 0.5.1
+Reexport 0.2.0
+IterTools 1.1.0
+
```
cc: @Balinus

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider if you can make your test setup install the necessary Python packages on CI. See https://discourse.julialang.org/t/the-current-metadata-release-process/16672

**Comment by Balinus** [comment]
Thanks! I will read how to do that. The Python packages are somewhat of a pain though. Basemap only works with specific python version (sadly not the Conda.jl's default). For TravisCI, I had to specify 

```
env:
   - CONDA_JL_VERSION=2
```

in my [.travis.yml](https://github.com/Balinus/ClimateTools.jl/blob/master/.travis.yml) file. Hopefully, this workaround is possible with JuliaCIBot.

**Comment by andreasnoack** [comment]
Unfortunately, it currently isn't possible to specify the Python version. Quite unfortunate that some packages still haven't been updated to Python 3.

**Comment by Balinus** [comment]
Well, it has been updated to Python 3. But now it's gonna be deprecated. Hence, it's simple to install on Python < 3.5, but not 3.6 or 3.7 (or something like that). 

My plan is to switch from Basemap to Cartopy asap (but I need to find time!).

**Pull request merged**
