### PR TITLE
Register new package BOSSArrays.jl v0.2.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [seung-lab/BOSSArrays.jl](https://github.com/seung-lab/BOSSArrays.jl)
Release: [v0.2.2](https://github.com/seung-lab/BOSSArrays.jl/releases/tag/v0.2.2)
cc: @jingpengwu

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@jingpengwu This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
You should avoid extending Base functions on Base types, like in `Base.UnitRange( idx::Int )`, as that can change the behavior of unrelated code

**Comment by tkelman** [comment]
Blosc is missing from REQUIRE, and HttpCommon from test/REQUIRE

**Comment by tkelman** [comment]
Can this be made to pass tests on Travis CI?

**Comment by jingpengwu** [comment]
@tkelman thanks for the advices. I have added the package REQUIRE, and travis CI support.
BTW, the HttpCommon was not required for test.
The extention of the Base function won't affect other packages since it only functions on my own types.

**Comment by tkelman** [comment]
> it only functions on my own types

That would be fine if it were the case - but you don't have your own package-local `Int` do you?

**Comment by jingpengwu** [comment]
oh, right, I have fixed this. Can we merge if I tag a new release?

**Comment by tkelman** [comment]
can also amend and replace the tag since it hasn't been published yet, see https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by tkelman** [comment]
still missing Blosc from require, the tag didn't include https://github.com/seung-lab/BOSSArrays.jl/commit/060cc802effa2329e078f8074cd076a1fa25b55c ?

**Comment by tkelman** [comment]
you keep re-tagging 3dd9250b8db7832dbbf6982c58635f86689b360e over and over again. you need to delete both the release and the git tag to re-create the git tag at a newer commit

**Comment by jingpengwu** [comment]
thanks, I just updated. I should completely delete the old tag, otherwise the code was not updated!

**Comment by tkelman** [comment]
5th time's the charm

**Pull request merged**
