### PR TITLE
Tag Compat v0.8.1

### PR DESCRIPTION
**Pull request by nalimilan**
For `allunique` addition.

### CODE REVIEW

**Comment by tkelman** [comment]
push the git tag so it shows up at https://github.com/JuliaLang/Compat.jl/releases

**Comment by KristofferC** [comment]
Maybe the test script should be altered to look if the tag exists. I make this mistake all the time...

**Comment by tkelman** [comment]
That's one of several things I've been meaning to code up but haven't done yet.

**Comment by nalimilan** [comment]
Always the same mistake! Done.

**Comment by timholy** [comment]
`Pkg/PkgDev.publish()` does this automatically for you. But `PkgDev.publish()` still doesn't work for me, so I often tag & publish from julia-0.4.

**Pull request merged**
