### PR TITLE
Tag LibExpat.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIO/LibExpat.jl](https://github.com/JuliaIO/LibExpat.jl)
Release: [v0.5.0](https://github.com/JuliaIO/LibExpat.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIO/LibExpat.jl/builds/413286116)
Diff: [vs v0.4.2](https://github.com/JuliaIO/LibExpat.jl/compare/4d37b81ab9461e2384a265ff49fd237e611f6eb0...c27b8304227aec2c8b55a33b6cc1d8a992789745)
`requires` vs v0.4.2: 
```diff
--- 0.4.2/requires
+++ 0.5.0/requires
@@ -1,2 +1,2 @@
-julia 0.6
+julia 0.7-alpha2
 Compat 0.41.0
```
cc: @Keno

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by Keno** [comment]
Hold off on this, there's more work to be done.

**Comment by ssfrr** [comment]
What's the status with this? I'm getting an appveyor failure on 1.0 because it looks like the current tagged version (0.4.2) is still using `Void`.

**Comment by lobingera** [comment]
@Keno @andreasnoack I somehow have the same question as above...

**Comment by musm** [comment]
should be good to go after CI run

**Pull request merged**
