### PR TITLE
Tag AutoGrad.jl v1.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [denizyuret/AutoGrad.jl](https://github.com/denizyuret/AutoGrad.jl)
Release: [v1.0.1](https://github.com/denizyuret/AutoGrad.jl/releases/tag/v1.0.1)
Travis: [Travis Build Status](https://travis-ci.org/denizyuret/AutoGrad.jl/builds/419950439)
Diff: [vs v1.0.0](https://github.com/denizyuret/AutoGrad.jl/compare/bb5e356e159259b09711945e1fe537065ba1c11d...bfc19976e781ab462f057bf317b5fcc0bc7268ec)
`requires` vs v1.0.0: no changes
cc: @denizyuret

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider deleting the project file from the repo since it currently isn't needed and it breaks the reverse dependency testing in CIBot.

**Comment by denizyuret** [comment]
So deleted.

**Comment by denizyuret** [comment]
I checked the CI, only small numerical errors in Float32 tests. They pass on my machine 9/10 times :)
I think this is ready to go.

**Comment by denizyuret** [comment]
ok, fixed CI and requirements.

**Pull request merged**
