### PR TITLE
Register new package OhMyREPL.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [KristofferC/OhMyREPL.jl](https://github.com/KristofferC/OhMyREPL.jl)
Release: [v0.1.0](https://github.com/KristofferC/OhMyREPL.jl/releases/tag/v0.1.0)
cc: @KristofferC

### CODE REVIEW

**Comment by tkelman** [comment]
Does the change in error printing here interfere with any other packages' tests?

**Comment by KristofferC** [comment]
I don't know. `Pkg.test` runs in its own process so probably not.

**Comment by KristofferC** [comment]
Bump

**Comment by tkelman** [comment]
Looks like Pkg.test doesn't set `--startup-file` though, so if it's put there as you recommend it could. Maybe worth restricting the output overrides to when `isinteractive()` is true

**Comment by KristofferC** [comment]
`isinteractive()` is false when OhMyREPL.jl gets loaded (REPL hasn't started yet).

**Comment by tkelman** [comment]
but it should be true by the time the functions execute?

**Comment by KristofferC** [comment]
OhMyREPL loads a REPL by itself. Maybe this approach would work: https://github.com/KristofferC/OhMyREPL.jl/issues/68

**Pull request merged**
