### PR TITLE
Tag JuMP v0.10.0

### PR DESCRIPTION
**Pull request by joehuchette**
@mlubin @IainNZ

### CODE REVIEW

**Comment by mlubin** [comment]
:+1: 
Hold up a bit for some doc fixes.

**Comment by IainNZ** [comment]
https://www.youtube.com/watch?v=M11SvDtPBhA

**Comment by IainNZ** [comment]
https://www.youtube.com/watch?v=iP6XpLQM2Cs

**Comment by mlubin** [comment]
Guess we're stuck, readthedocs won't build docs for ``release-0.10``

**Comment by joehuchette** [comment]
Any ideas how to fix that?

**Comment by mlubin** [comment]
https://github.com/rtfd/readthedocs.org/issues/1617

**Comment by mlubin** [comment]
Let's just merge this, RTD isn't very useful.

**Comment by mlubin** [comment]
Oh, needs to be retagged

**Comment by joehuchette** [comment]
Retagged, good to merge once CI passes.

**Comment by mlubin** [comment]
I don't see a 0.10.0 tag at https://github.com/JuliaOpt/JuMP.jl/releases

**Comment by IainNZ** [comment]
:dancers:

**Pull request merged**
