### PR TITLE
Tag DifferentialEquations.jl v1.10.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DifferentialEquations.jl](https://github.com/JuliaDiffEq/DifferentialEquations.jl)
Release: [v1.10.0](https://github.com/JuliaDiffEq/DifferentialEquations.jl/releases/tag/v1.10.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/DifferentialEquations.jl/builds/221587044)
Diff: [vs v1.9.1](https://github.com/JuliaDiffEq/DifferentialEquations.jl/compare/52a2768fcb065c20153df64eb77bcb32568fe529...057c4922abd08b410ac4b8e0782684ffcc68eaa4)
`requires` vs v1.9.1: 
```diff
--- 1.9.1/requires
+++ 1.10.0/requires
@@ -1,6 +1,6 @@
 julia 0.5
 Reexport 0.0.3
-DiffEqBase 0.8.0 0.15.0
+DiffEqBase 0.15.0
 StochasticDiffEq 1.0.0
 FiniteElementDiffEq 0.0.5
 DiffEqDevTools 0.2.0
```
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
huh, this one worked. DASSL and DASPK are not dependencies of DifferentialEquations, so they won't hold it back. I am curious why they didn't work...

**Comment by tkelman** [comment]
ODETestProblem not defined in https://travis-ci.org/JuliaDiffEq/DifferentialEquations.jl/jobs/221587045
where should that be coming from?

**Comment by ChrisRackauckas** [comment]
That's one of the things which was removed from DiffEqBase.jl (which killed all of the tests). I missed this one. It won't be disruptive to users that this is there, but I'll put a patch in right now.

**Comment by ChrisRackauckas** [comment]
BTW, thanks so much for helping out with all of this!

**Pull request merged**
