### PR TITLE
Register LegacyStrings: v0.1.0

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by tkelman** [comment]
This should retain the Base contributor attribution, at the very least the license.

**Comment by tkelman** [comment]
AppVeyor's not running yet?

**Comment by StefanKarpinski** [comment]
As soon as this is registered, I can add the appropriate deprecation messages to https://github.com/JuliaLang/julia/pull/16590 and we can merge that PR finally, bringing the 0.5 edition of Stringapalooza to a close.

**Comment by StefanKarpinski** [comment]
License file updated: https://github.com/JuliaArchive/LegacyStrings.jl/commit/92add93a91e5ddd81f30. I'm going to leave this PR as for version 0.1 as-is so that we can get a move on with this.

**Comment by StefanKarpinski** [comment]
None of the CI seems to be running. @tkelman, any idea what's going on?

**Comment by tkelman** [comment]
Most likely due to https://www.traviscistatus.com/incidents/rqb906yypnk0, causing pending osx builds to fill our entire queue. I cancelled a bunch of them in base, we can restart them when the Travis issue is resolved.

**Comment by tkelman** [comment]
This also needs the docs to be copied into the readme.

**Comment by tkelman** [comment]
todo's captured as issues

**Pull request merged**
