### PR TITLE
Tag BigArrays.jl v0.7.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [seung-lab/BigArrays.jl](https://github.com/seung-lab/BigArrays.jl)
Release: [v0.7.0](https://github.com/seung-lab/BigArrays.jl/releases/tag/v0.7.0)
Travis: [Travis Build Status](https://travis-ci.org/seung-lab/BigArrays.jl/builds/434352407)
Diff: [vs v0.6.1](https://github.com/seung-lab/BigArrays.jl/compare/a6344ebf578c27f29946af1581c0bd2a71f77b98...0d8b5951dbe27b802ac1ca3b33a08472f2ed2422)
`requires` vs v0.6.1: 
```diff
--- 0.6.1/requires
+++ 0.7.0/requires
@@ -1,8 +1,15 @@
-julia 0.6
+julia 0.7
 JSON
-#HDF5
 Memoize
-#ImageMagick
 Blosc
-Libz
-EMIRT
+TranscodingStreams
+CodecZlib
+CodecZstd
+OffsetArrays
+JSON
+
+
+#GoogleCloud
+#AWSCore
+#AWSSDK
+
```
cc: @jingpengw

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by xiuliren** [comment]
can we merge?

**Comment by andreasnoack** [comment]
Tests don't pass. See the CIBot details.

**Comment by xiuliren** [comment]
The CIBot is not required?
The error is 
```
ERROR: The following package names could not be resolved:
 * BigArrays (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```
Does it means this package was not registered in Julia 0.7? This is the first time I am tagging it for Julia 0.7

**Comment by andreasnoack** [comment]
For some reason, your package doesn't show up in https://github.com/JuliaRegistries/General/tree/master/B. @KristofferC any idea why that would be?

**Comment by xiuliren** [comment]
The repo was private for about a year, maybe that makes the trouble.

**Comment by StefanKarpinski** [comment]
The fact that it was made private after being registered broke the syncing script, so it was explicitly blacklisted from the general registry. It should start syncing now.

**Comment by StefanKarpinski** [comment]
Synced now: https://github.com/JuliaRegistries/General/commit/d8983d968acb91ba24cb8f86caa711c22b188acd

**Comment by andreasnoack** [comment]
Things are now working here. Thank you for the patience

**Pull request merged**
