### PR TITLE
Register new package PretrainedEmbeddings.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaText/PretrainedEmbeddings.jl](https://github.com/JuliaText/PretrainedEmbeddings.jl)
Release: [v0.1.0](https://github.com/JuliaText/PretrainedEmbeddings.jl/releases/tag/v0.1.0)
cc: @oxinabox

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@oxinabox This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by oxinabox** [comment]
Oops, I must have missed that once.

**Comment by oxinabox** [comment]
@MikeInnes  and @ninjin  have convinced me that Embeddings.jl is a better name.
Also I'll need to add a new release to make the CI get the test changes I have made to stop it from using up all the disk-space on travis.

So this can be closed

**Comment by aviks** [comment]
Hi Lyndon, looks like you did not do a new METADATA Pr after the renaming?

**Comment by oxinabox** [comment]
huh, I'll get on that

**Pull request closed without merging**
