### PR TITLE
Register MolecularDataType: v0.0.1

### PR DESCRIPTION
**Pull request by yuhangwang**
I discarded my previous commits and reset my branch to be the same as the JuliaLang/METADATA.jl. Then I added my package "MolecularDataType" again. This time there is only one commit.

### CODE REVIEW

**Comment by tkelman** [comment]
It's a good idea to push the git tags (`git push --tags`) to the package repo so they show up under https://github.com/UMOL/MolecularDataType.jl/releases

**Comment by yuhangwang** [comment]
Ok. Thank you for taking care of this pull request and thanks for the suggestion.

**Comment by yuhangwang** [comment]
I just tagged and pushed my changes to MolecularDataType.jl. Thanks!

**Comment by tkelman** [comment]
The git tag should match the metadata tag, c8a07f5f9789cf24dcb0d02df55fe2e4054fcd9e - did you use `Pkg.tag` to do this?

**Comment by yuhangwang** [comment]
No. I used `git tag -a v0.0.1 -m "version 0.0.1"`

**Comment by yuhangwang** [comment]
I have to go now and I will try to fix it later today.

**Comment by yuhangwang** [comment]
I accidentally deleted the version installed at ~/.julia/v0.4. What is the best way to proceed? Should I reinstall MolecularDataType and use Pkg.tag to create another tag for it and push it to GitHub?

**Pull request merged**
