### PR TITLE
Register new package BeliefUpdaters.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPOMDP/BeliefUpdaters.jl](https://github.com/JuliaPOMDP/BeliefUpdaters.jl)
Release: [v0.1.0](https://github.com/JuliaPOMDP/BeliefUpdaters.jl/releases/tag/v0.1.0)
cc: @MaximeBouton

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@MaximeBouton This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by MaximeBouton** [comment]
This package depends on [POMDPModelTools](https://gtihub.com/JuliaPOMDP/POMDPModelTools.jl) 
Please restart the build after JuliaLang/METADATA.jl#17464 is merged

**Comment by zsunberg** [comment]
@andreasnoack Since you were helping us with #17464, could you restart this build for us? Thanks! :)

**Comment by andreasnoack** [comment]
Yes, I can do that. However, you can always trigger the tests by removing and reapplying the tag.

**Comment by zsunberg** [comment]
@andreasnoack Thanks! Ok, will re-apply the tag in the future. We have enabled travis as you suggested on slack https://travis-ci.org/JuliaPOMDP/BeliefUpdaters.jl?utm_source=email&utm_medium=notification. (cc: @MaximeBouton in the future we should restart the builds by re-applying the tag)

**Comment by MaximeBouton** [comment]
@andreasnoack thanks for the help, the build restarted and it looks all good now.

**Pull request merged**
