### PR TITLE
Register new package BulkSMS.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [scls19fr/BulkSMS.jl](https://github.com/scls19fr/BulkSMS.jl)
Release: [v0.0.1](https://github.com/scls19fr/BulkSMS.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/scls19fr/BulkSMS.jl/builds/445841280)
cc: @scls19fr

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@scls19fr This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
This would need some kind of documentation and/or readme.

**Comment by s-celles** [comment]
I don't understand what is wrong with my Documenter.jl settings https://travis-ci.org/scls19fr/BulkSMS.jl
I really hope that @mortenpi or someone else from https://github.com/JuliaDocs/ can help.
SSH public key is set on Travis (with read/write access) and DOCUMENTER_KEY is also set on Travis side. I really don't understand what is wrong here.
Any idea?

**Comment by fredrikekre** [comment]
> I don't understand what is wrong with my Documenter.jl settings

Remove https://github.com/scls19fr/BulkSMS.jl/blob/dc74fd5c5d64b9c6083eb98152ebe4ced43dfa05/docs/make.jl#L15-L19

**Comment by s-celles** [comment]
Thanks @fredrikekre

**Pull request merged**
