### PR TITLE
Register and tag TimeSeriesIO

### PR DESCRIPTION
**Pull request by femtotrader**

### CODE REVIEW

**Comment by tbreloff** [comment]
I've gotta say... these seem like very tiny and specific packages to be registered (and to get such generic names).  Is there some other package that depends on them?

**Comment by femtotrader** [comment]
DataReaders.jl depends on 
https://github.com/femtotrader/DataReaders.jl

You can have a look at discussion here
https://github.com/JuliaStats/TimeSeries.jl/issues/290

TALib.jl should also quickly depends on
https://github.com/femtotrader/TALib.jl

**Comment by femtotrader** [comment]
DukascopyTicksReader.jl will also
https://github.com/femtotrader/DukascopyTicksReader.jl

**Comment by tkelman** [comment]
included in #6997, closing this copy

**Pull request closed without merging**
