### PR TITLE
Tag Mads.jl v0.6.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [madsjulia/Mads.jl](https://github.com/madsjulia/Mads.jl)
Release: [v0.6.1](https://github.com/madsjulia/Mads.jl/releases/tag/v0.6.1)
Travis: [Travis Build Status](https://travis-ci.org/madsjulia/Mads.jl/builds/454210395)
Diff: [vs v0.6.0](https://github.com/madsjulia/Mads.jl/compare/d752186a55d3ccab5fc92e79809140a834abb270...d1ead054a62d80bdd4d6415f0edd056f59a47117)
`requires` vs v0.6.0: no changes
cc: @montyvesselinov

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by montyvesselinov** [comment]
I just made changes. Not sure why PyPlot fails.

**Comment by montyvesselinov** [comment]
it works on Travis

**Comment by andreasnoack** [comment]
1. You'd have to call `before_script.jl` in `test/runtests.jl`. See https://github.com/tkf/IPython.jl/blob/master/test/runtests.jl#L3-L20

2. The METADATA Travis tests also fail on Julia 0.7. The package requirements you have set makes the package uninstallable on Julia 0.7.

**Comment by montyvesselinov** [comment]
Sorry about that. Very interesting. Another attempt.

**Comment by montyvesselinov** [comment]
According to the log it does seem the test is on the latest version?!

**Comment by andreasnoack** [comment]
Why do you have these lines, https://github.com/madsjulia/Mads.jl/blob/master/ci/before_script.jl#L30-L34, in the script.

**Comment by montyvesselinov** [comment]
I removed these lines. But Julia CI still fails. 

Travis CI is working. I still do not understand why PyCall/PyPlot fails. Note that the script is supposed to detect these failures and set ENV variables to prevent their use in Mads.  PyCall/PyPlot are optional but a part of the testing if available.

https://github.com/madsjulia/Mads.jl/blob/master/ci/before_script.jl#L3-L28

**Comment by montyvesselinov** [comment]
I dropped all python pre installation stuff (https://github.com/madsjulia/Mads.jl/blob/master/.travis.yml) and it now passes on travis again.

**Comment by montyvesselinov** [comment]
The build did not fail. it was just terminated earlier. not sure why?!

**Comment by andreasnoack** [comment]
We had an issue with CIBot but it looks like things now are working.

**Pull request merged**
