### PR TITLE
Pull request/90886eab

### PR DESCRIPTION
**Pull request by arsenal9971**
Shearlab is a Julia Library with toolbox for two- and threedimensional data processing using the Shearlet system as basis functions which generates an sparse representation of cartoon-like functions. It is based in the Matlab Library Shearlab3D, developed by the Applied Functional Analysis Research Group in the Technical University of Berlin lead by Professor Gita Kutyniok, for further information of the Matlab Implementation you can visit the link http://www.shearlab.org/. It uses the other library that I developed FWT.jl

### CODE REVIEW

**Comment by kmsquire** [comment]
(You probably saw my [comment in #7763](https://github.com/JuliaLang/METADATA.jl/pull/7763#issuecomment-276487533).)

**Comment by tkelman** [comment]
If your code is based on an existing Matlab toolbox, then it's almost certainly a derived work and should account for that in the licensing. It looks like the Matlab toolbox is GPL3 licensed?

**Comment by dpsanders** [comment]
Maybe the name should be `ShearLab.jl`, or just `Shearlets.jl`.

**Comment by arsenal9971** [comment]
@tkelman Here I give you the content of the License file in the Matlab package that my advisor's group developed 
"
%  ShearLab3Dv11 Toolbox Copying Permissions

%  This program is free software: you can redistribute it and/or modify
%  it under the terms of the GNU General Public License as published by
%  the Free Software Foundation, either version 3 of the License, or
%  (at your option) any later version.

%  This program is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  GNU General Public License for more details.


%  This package was written by 
%	Rafael Reisenhofer, Technische Universität Berlin
%
%  Contributors to this effort include
%   Wang-Q Lim, Technische Universität Berlin
%   Gitta Kutyniok, Technische Universität Berlin 
%
% Copyright 2014, Rafael Reisenhofer, Technische Universität Berlin.
% 
%                         All Rights Reserved
"

Which License should I give, how can I change the license with PkgDev?

**Comment by arsenal9971** [comment]
I also need the other library, FWT.jl for this one, or you recommend me to make them separately ??

**Comment by tkelman** [comment]
Would be better to do them separately, and ref the naming guidelines linked to https://github.com/JuliaLang/METADATA.jl/pull/7763#issuecomment-276487533

Changing the license doesn't have to go through PkgDev, you can just replace the LICENSE.md file.

**Comment by arsenal9971** [comment]
Thanks @tkelman, I will do it now, after changing and doing the commit should I ask again for a pull request. I wanted to do it together to not repeat the functions in both libraries. I still having problems in the Travis that is saying "Package Shearlab has no tagged versions". But I actually tagged it since the beginning.

**Comment by dpsanders** [comment]
Is there a reason to have the other package be separate? It could be part of this one if that's easier.

**Comment by arsenal9971** [comment]
@dpsanders You are right, it happened just historically, I wrote the FWT way before Shearlab, and it came out that lots of the functions in FWT where actually really useful in Shearlab, by the similarity of the transforms. I will work.

**Comment by arsenal9971** [comment]
@dpsanders  and @tkelman  I already changed the License, I will incorporate FWT in Shearlab, and change the names of the functions as you asked, and then will do pull request again

**Comment by tkelman** [comment]
closing this in favor of https://github.com/JuliaLang/METADATA.jl/pull/8086

**Pull request closed without merging**
