### PR TITLE
Tag Digits v0.1.2

### PR DESCRIPTION
**Pull request by greenflash1357**
New version of Digits with new functions and updated Readme.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
That's a lot of merges. Could you rebase them out?

**Comment by tkelman** [comment]
Additionally, you don't need to depend on `julia 0.3-` any more, that means "prereleases of 0.3 or newer." Since 0.3 has been out for almost a year, you can safely change that to `julia 0.3` now, which means "releases of 0.3 or newer."

**Comment by greenflash1357** [comment]
rebased.

@tkelman: thanks. I've merged your PR. Your changes will be part of the next release.

**Comment by tkelman** [comment]
Looks good.

**Pull request merged**
