### PR TITLE
Register new package FEniCS.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/FEniCS.jl](https://github.com/JuliaDiffEq/FEniCS.jl)
Release: [v0.0.1](https://github.com/JuliaDiffEq/FEniCS.jl/releases/tag/v0.0.1)
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ChrisRackauckas This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
If this supports Julia 0.5, it should be tested there on Travis

**Comment by ChrisRackauckas** [comment]
That's a mistake. Sorry. I just updated the repo, but will probably wait for some more updates to release it.

**Comment by tkelman** [comment]
Do you want this to be available on Julia 0.5?

**Comment by ChrisRackauckas** [comment]
No. I think it might still work but the install process can be difficult to maintain so I'd rather not try to support multiple versions.

**Comment by tkelman** [comment]
Then best to retroactively change the metadata requires file for this tag before it's out there too long.

**Pull request merged**
