### PR TITLE
Pull request/e4086519

### PR DESCRIPTION
**Pull request by arbenson**

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider using https://github.com/attobot/attobot when tagging packages

**Comment by arbenson** [comment]
Thanks for the suggestion. I will use attobot on future releases.

**Comment by andreasnoack** [comment]
Is it on purpose that you've tagged three versions of `HigherOrderClustering` in this PR?

**Comment by arbenson** [comment]
No. I had some trouble with the PkgDev workflow and did not see an easy way to revert tags.

https://github.com/JuliaLang/julia/issues/8289
https://github.com/JuliaLang/PkgDev.jl/issues/76

Is there an easy fix?

**Comment by andreasnoack** [comment]
Attobot makes this much simpler. You can delete the existing tags directly on Github if you go to [the "releases" section](https://github.com/arbenson/HigherOrderClustering.jl/releases). Then enable Attobot and make a new tag. That will create a new PR automatically.

**Comment by arbenson** [comment]
Ah, I see. I used the attobot release to delete the tags v0.0.{2,3} and release v0.0.1. 

screen shot 2018-02-20 at 8 46 55 am

According to the README, "AttoBot will then update the existing pull request and make a comment that it has been updated".  This does not appear to have occurred (maybe there is a delay?)

**Comment by andreasnoack** [comment]
Have you enabled Attobot for your repo at https://github.com/integration/attobot?

**Comment by arbenson** [comment]
I had not, but now I have.

After registering, I updated the release:
screen shot 2018-02-20 at 8 58 04 am

This has not yet created a commit to this PR.

**Comment by andreasnoack** [comment]
I don't think that will work. Try removing and adding both release and tag and then make a new release.

**Comment by arbenson** [comment]
Alright, this seems to have created a new PR:
https://github.com/JuliaLang/METADATA.jl/pull/13449

Perhaps it is best to close this PR and then I will also release ScHoLP with AttoBot under another PR.

**Comment by arbenson** [comment]
Thanks for the help!

**Comment by arbenson** [comment]
And the other one is here:
https://github.com/JuliaLang/METADATA.jl/pull/13450

**Pull request closed without merging**
