### PR TITLE
Tag Bio.jl v0.4.6

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BioJulia/Bio.jl](https://github.com/BioJulia/Bio.jl)
Release: [v0.4.6](https://github.com/BioJulia/Bio.jl/releases/tag/v0.4.6)
Travis: [Travis Build Status](https://travis-ci.org/BioJulia/Bio.jl/builds/204992230)
Diff: [vs v0.4.5](https://github.com/BioJulia/Bio.jl/compare/7f5e7afd8ad7c2fab70b812f6596e9163b9eca70...a57bfb5bb31b4cabbef802edecf619606eb1619b)
`requires` vs v0.4.5: 
```diff
--- 0.4.5/requires
+++ 0.4.6/requires
@@ -4,7 +4,7 @@
 Colors
 Distributions
 IndexableBitVectors 0.1.1
-IntervalTrees 0.1 0.1.1
+IntervalTrees 0.1
 Iterators
 Libz 0.2
 LightGraphs
```
cc: @Ward9250

### CODE REVIEW

**Comment by Ward9250** [comment]
Please *Cancel* this

**Comment by tkelman** [comment]
looks like this still fails with IntervalTrees 0.1.1? https://travis-ci.org/BioJulia/Bio.jl/jobs/204992231

**Comment by Ward9250** [comment]
Indeed! I forgot to update the REQURE for our release0.4 branch!, I've just fixed that with an append commit, but because the shas have changed this needs to be closed so I can do it again.

**Comment by tkelman** [comment]
attobot will update the pr if you replace the release

**Comment by kmsquire** [comment]
@ward9250, I believe you can just retag it, and this pull request will be updated.

**Comment by Ward9250** [comment]
Ok now this is retagged and correct.

**Comment by Ward9250** [comment]
@kmsquire That's really cool attobot does that!

**Pull request merged**
