### PR TITLE
Tag ImageCore.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaImages/ImageCore.jl](https://github.com/JuliaImages/ImageCore.jl)
Release: [v0.6.0](https://github.com/JuliaImages/ImageCore.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaImages/ImageCore.jl/builds/384646568)
Diff: [vs v0.5.0](https://github.com/JuliaImages/ImageCore.jl/compare/a278c6d92cb195ea153bbb5f57ee27592bdb82d0...ab016468457d59e5c5144487ae8e4dabc5fcfc00)
`requires` vs v0.5.0: 
```diff
--- 0.5.0/requires
+++ 0.6.0/requires
@@ -1,4 +1,4 @@
-julia 0.6.0
+julia 0.6
 FixedPointNumbers 0.3.0
 ColorTypes 0.4
 Colors
```
cc: @Evizero

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by Evizero** [comment]
uh, the `REQUIRE` change was an oversight. Does it make a difference to have `0.6` vs `0.6.0` ?

**Comment by Evizero** [comment]
it may be interesting to not here that development on `ImageCore` already diverged for 0.6 and 0.7 (see https://github.com/JuliaImages/ImageCore.jl/pull/54#issuecomment-354175036), with the footnote that 0.7 support is still WIP. 

This is why this tag shows CI for 0.7 removed, because I am tagging the `release-0.6` branch until `master` is actually working for 0.7.

**Comment by andreasnoack** [comment]
Looks like it breaks `Augmentor`.

**Comment by Evizero** [comment]
Ok, well. This should **not** be merged, but closed instead. Its good that Augmentor caught this because in one way or another this broke `permutedims` for `Colorant` `OffsetArray` in a strange way

**Comment by andreasnoack** [comment]
We can just leave it open. When you move the tag to a working commit, the PR will be updated automatically.

**Pull request merged**
