### PR TITLE
Tag KNITRO.jl v0.3.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaOpt/KNITRO.jl](https://github.com/JuliaOpt/KNITRO.jl)
Release: [v0.3.2](https://github.com/JuliaOpt/KNITRO.jl/releases/tag/v0.3.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaOpt/KNITRO.jl/builds/352415845)
Diff: [vs v0.3.1](https://github.com/JuliaOpt/KNITRO.jl/compare/09b996a7e8ac8c05e07465568273cc963afafefd...816106679b4763723161865cad389ae6e7e6f175)
`requires` vs v0.3.1: no changes
cc: @sylvainmouret

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
From the log:
```julia
ERROR: LoadError: METADATA/KNITRO/versions/0.3.2/requires: oldest allowed julia version 0.5.0 too old (>= 0.6.0 needed)
```

**Comment by sylvainmouret** [comment]
Hi Andreas,
What is the problem here?
The version requirement for Julia are the same as in the previous release of the KNITRO package. Nothing has changed on this matter.
Can you update to Julia 0.6?

**Comment by andreasnoack** [comment]
You need to require at least `julia 0.6` in your REQUIRE file before a new version can be released since we have dropped support for Julia 0.5.

**Comment by andreasnoack** [comment]
This tag still requires only `julia 0.5`. Try to delete the tag and add it again.

**Comment by sylvainmouret** [comment]
I tried it but the last commit include requirement to Julia 0.6 was not taken into account.
Anyway, I made a v0.3.3 release which should be OK hopefully.

**Pull request closed without merging**
