### PR TITLE
Tag GLM.jl v0.10.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/GLM.jl](https://github.com/JuliaStats/GLM.jl)
Release: [v0.10.0](https://github.com/JuliaStats/GLM.jl/releases/tag/v0.10.0)
Diff: [vs v0.9.0](https://github.com/JuliaStats/GLM.jl/compare/a71c0b7754fb3e8a9e5a11c085cff331af0c091e...83f1e4c5540774109ee4f75008a6db3739028916)
`requires` vs v0.9.0: no changes
cc: @dmbates

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Tests for Lasso fail with the new version of GLM

```
ERROR: LoadError: LoadError: Base.LinAlg.RankDeficientException(0)
Stacktrace:
 [1] chkfullrank at ./linalg/cholesky.jl:548 [inlined]
 [2] A_ldiv_B!(::Base.LinAlg.CholeskyPivoted{Float64,Array{Float64,2}}, ::Array{Float64,1}) at ./linalg/cholesky.jl:458
 [3] delbeta!(::GLM.DensePredChol{Float64,Base.LinAlg.CholeskyPivoted{Float64,Array{Float64,2}}}, ::Array{Float64,1}, ::Array{Float64,1}) at /mnt/pkgevalempty/1c820d52714cb2faf82b093dbfd6a96d7640ad03/Lasso/.julia/v0.6/GLM/src/linpred.jl:167
 [4] _fit!(::GLM.GeneralizedLinearModel{GLM.GlmResp{Array{Float64,1},Distributions.Binomial{Float64},GLM.LogitLink},GLM.DensePredChol{Float64,Base.LinAlg.CholeskyPivoted{Float64,Array{Float64,2}}}}, ::Bool, ::Int64, ::Float64, ::Float64, ::Void) at /mnt/pkgevalempty/1c820d52714cb2faf82b093dbfd6a96d7640ad03/Lasso/.julia/v0.6/GLM/src/glmfit.jl:172
```

**Comment by dmbates** [comment]
Hmm - I'm not really sure how this worked in the past.  The relevant section of the `Lasso` code is
```julia
    nullmodel = fit(GeneralizedLinearModel, ones(T, length(y), ifelse(intercept, 1, 0)), y, d, l;
                    wts=wts, offset=offset, convTol=irls_tol)
    nulldev = deviance(nullmodel)
```
so, in the case that the model does not have an intercept it tries to fit a `GeneralizedLinearModel` to a model matrix of size `(n, 0)`.  I'm not sure if it is better to special-case this use in `Lasso::build_model` or in `GLM`.  I'll see what I can do in `GLM` or create a PR for @simonster for `Lasso`.  Another alternative is to come up with a more sensible check in `chkfullrank`.  Technically, a symmetric 0 by 0 matrix is positive definite.

**Comment by dmbates** [comment]
I tracked it down to a default argument in the `GLM.cholpred` being `true` when it should be `false`.  I can make the change in the GLM package master branch.  Is the simplest approach after that to release a v0.10.1 of GLM with this change?

**Comment by dmbates** [comment]
@aviks Please close this PR in favor of #12694

**Comment by dmbates** [comment]
@aviks I think you merged the wrong PR.  The way I planned it this one should be closed and #12964 should be merged.  Am I missing something here?

**Pull request merged**
