### PR TITLE
Register new package Circuitscape.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ranjanan/Circuitscape.jl](https://github.com/ranjanan/Circuitscape.jl)
Release: [v0.0.1](https://github.com/ranjanan/Circuitscape.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/ranjanan/Circuitscape.jl/builds/260104498)
cc: @ranjanan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ranjanan This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
Is this derived from existing Circuitscape code?

**Comment by ranjanan** [comment]
This is a rewrite of the Circuitscape project in Julia. However, it still uses the PyAMG solver through PyCall for now, but that will change in the next few releases.

**Comment by tkelman** [comment]
Rewrite can mean many things. Is it a direct translation or a clean-room reimplementation? Did you refer to existing source code or only academic papers or mathematical descriptions? The existing Circuitscape project says it has a Creative Commons license here http://www.circuitscape.org/downloads but I'm not seeing which variant. If this is a derived work of that copyrighted code then it should be respecting the original project's license terms.

**Comment by StefanKarpinski** [comment]
> I think the Python package at https://pypi.python.org/pypi/Circuitscape/ has a CC-BY 3.0 license https://creativecommons.org/licenses/by/3.0/legalcode but I'm not absolutely positive.

@ViralBShah owns the copyright to CircuitScape, so he can give permission to use the code.

**Comment by ranjanan** [comment]
@tkelman I've modified the copyright accordingly and sent a new request to register.

**Pull request merged**
