### PR TITLE
Register BeaData.jl

### PR DESCRIPTION
**Pull request by sbnicar**
Requesting publish for package BeaData.jl

### CODE REVIEW

**Comment by kmsquire** [comment]
BureauOfEconomicAnalysisData.jl is a bit too long, but I wonder if, e.g., BEA_Data.jl would be a better name?  

AKAIK, there aren't any other packages which have underscores, but then, there also aren't many packages which begin with an acronym and end with a word...

Anyway, unless this is a clear win, don't let this comment prevent registering.

**Comment by sbnicar** [comment]
The name was modeled after BlsData and FredData, both registered packages that query economic data APIs and start with acronyms.

**Comment by sbnicar** [comment]
I should add that I don't really have any objection to changing the name, but iI thought an underscore or "BEAData" would be bad style, given the examples provided in the documentation.

**Comment by kmsquire** [comment]
Okay, thanks for the explanation.  The name should be fine then.

**Comment by milktrader** [comment]
FWIW, I don't mind BeaData.

**Comment by tkelman** [comment]
If your tests are all in a try, any failures wouldn't be very visible.

**Pull request merged**
