### PR TITLE
Tag FiniteElementDiffEq.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/FiniteElementDiffEq.jl](https://github.com/JuliaDiffEq/FiniteElementDiffEq.jl)
Release: [v0.4.0](https://github.com/JuliaDiffEq/FiniteElementDiffEq.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/FiniteElementDiffEq.jl/builds/235922151)
Diff: [vs v0.3.0](https://github.com/JuliaDiffEq/FiniteElementDiffEq.jl/compare/46d3e29b40aa9e6a021768516edd66d018218767...f844cabaccf61b487f8e469014ed3f722a879d02)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -4,7 +4,6 @@
 IterativeSolvers 0.2.2
 Parameters 0.5.0
 GenericSVD 0.0.2
-ForwardDiff 0.2.4 0.5.0
 NLsolve 0.7.3
 ChunkedArrays 0.1.0
 VectorizedRoutines 0.0.2
```
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Note that the CIBot incorrectly flagged this as an issue with ForwardDiff v0.5.0. In reality, this hasn't actually used ForwardDiff since a refactor a while back. What it found was an issue with NLsolve:

https://github.com/JuliaNLSolvers/NLsolve.jl/issues/103

**Comment by tkelman** [comment]
Oh great, should we remove the upper bounds on the past versions then?

**Comment by ChrisRackauckas** [comment]
Yes.

**Comment by tkelman** [comment]
Does the same apply to StochasticDiffEq from https://github.com/JuliaLang/METADATA.jl/pull/9437?

**Comment by ChrisRackauckas** [comment]
>Does the same apply to StochasticDiffEq from #9437?

Yes. While I think there is one part that actually hits changed code, that stuff isn't released and I don't think it's even tested yet (it might actually only be on a private branch right now?). So yeah, it's not needed there either. But the bound is definitely needed on OrdinaryDiffEq.

**Comment by tkelman** [comment]
Were you going to partially revert the change from https://github.com/JuliaLang/METADATA.jl/pull/9437 then?

**Comment by ChrisRackauckas** [comment]
does it matter? The next version doesn't have a version bound.

**Comment by tkelman** [comment]
If they're unnecessary, then they're pointlessly preventing installation of version combinations that would work together.

**Pull request merged**
