### PR TITLE
Register AmplNLWriter: v0.0.1

### PR DESCRIPTION
**Pull request by JackDunnNZ**

### CODE REVIEW

**Comment by mlubin** [comment]
LGTM, barring any objections over the name. This will soon be a JuliaOpt project.
@IainNZ @dpo @vitaut

**Comment by tkelman** [comment]
Great! Would be good to REQUIRE `julia 0.3` and `MathProgBase` and `Compat`, add FactCheck to `test/REQUIRE`, and set up Travis sooner or later.

**Comment by JackDunnNZ** [comment]
@tkelman Done, except for Travis!

**Comment by mlubin** [comment]
(Will be pushed soon)

**Comment by tkelman** [comment]
No objections to the name so far, I'll call that good enough to merge then.

**Pull request merged**
