### PR TITLE
Tag D3Trees.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [sisl/D3Trees.jl](https://github.com/sisl/D3Trees.jl)
Release: [v0.3.0](https://github.com/sisl/D3Trees.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/sisl/D3Trees.jl/builds/416557964)
Diff: [vs v0.2.0](https://github.com/sisl/D3Trees.jl/compare/024de934e9a55d19fcb2c7d5e8b92d4b96435847...c0158772e3ca74b5d3f0a7107b5e8a3dd52468cd)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.3.0/requires
@@ -1,4 +1,3 @@
-julia 0.6
+julia 0.6 0.7
 JSON
-Blink
 AbstractTrees 0.1
```
cc: @zsunberg

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Could you please enable testing on Julia 0.6 since it is supported according to your REQUIRE. It looks like tests are passing on Julia 0.7 and 1.0 so why have you added an upper bound to Julia?

**Comment by KristofferC** [comment]
Should previous version also have an upper bound?

**Comment by zsunberg** [comment]
Yeah, I messed this up. Sorry for using your time!! The easiest way to fix is to just close this and do another PR with attobot, right?

**Comment by zsunberg** [comment]
oh, I guess that re-tagging just updates this PR. Ok, now everything should be correct in REQUIRE. Sorry for the confusion!

**Pull request merged**
