### PR TITLE
Register SplNDimsFiltering [https://github.com/Yorick/SplNDimsFilteri…

### PR DESCRIPTION
**Pull request by QuelqunQui**
…ng.jl.git]

### CODE REVIEW

**Comment by tkelman** [comment]
Hi @QualqunQui. This repository URL is a 404, is the repository public? You'll also need to tag a version.

**Comment by QuelqunQui** [comment]
Well, I think I've tagged it but not sure if its public yet ^^, I must say I'm a first timer but I'll check that :)

**Comment by QuelqunQui** [comment]
Well I believe I had missed some steps, sorry for bothering, there were stills things I didn't understood

**Comment by MikeInnes** [comment]
@QuelqunQui ping us if we can help you with this.

**Pull request closed without merging**
