### PR TITLE
Disable policy 8 check

### PR DESCRIPTION
**Pull request by ararslan**
cc @aviks and @omus

### CODE REVIEW

**Comment by tkelman** [comment]
Your changes may have made it worse, but the failures on CI were a race condition. Not a good idea.

**Comment by aviks** [comment]
cc: @KristofferC I'm on board with this. Not ideal, but at this point it will make things better.

**Comment by aviks** [comment]
Things were pretty bad before Alex's changes. We'd discussed turning it off then as well.

**Comment by ararslan** [comment]
It seemed to be working correctly after my changes, but @omus noted that they were incorrect for private instances of METADATA, and I think https://github.com/JuliaLang/METADATA.jl/pull/13011 reintroduced the failures.

**Comment by tkelman** [comment]
Don't disable it entirely, make it retry on failure to verify. Outright deletion of a tag also needs to be flagged. And people merging to a repo that's pulled from by hundreds or thousands of people a day need to pay closer attention, avoid merging multiple pr's related to the same tag where CI will be inaccurate. You're going to need to make the pkg3 registries more automated and prevent user/maintainer mistakes, not require more things to be verified manually.

**Comment by tkelman** [comment]
You also *really* need to be running the consistency checks on all versions of julia that tags are accepted for, which you shut off for no reason and have completely ignored.

**Comment by aviks** [comment]
At this point we have a bit of crisis at the moment, we need to get things fixed in the short term, so that metadata can continue to function. In this case, no tests are better than bad tests, as the current situation demonstrates, since bad tests directly lead to human mistakes.

**Comment by omus** [comment]
I have a simple fix I think will address the problem and not disable the tests. I wasn't done validating it but I'll push it right away.

**Comment by omus** [comment]
Potential fix I mentioned: https://github.com/JuliaLang/METADATA.jl/pull/13107

**Comment by omus** [comment]
> At this point we have a bit of crisis at the moment

My preference is we try my potential fix first. If that doesn't resolve the issues then we should consider rolling back some changes then.

**Comment by aviks** [comment]
Closed in favour of #13107

**Pull request closed without merging**
