### PR TITLE
Register new package Modia3D.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ModiaSim/Modia3D.jl](https://github.com/ModiaSim/Modia3D.jl)
Release: [v0.2.0](https://github.com/ModiaSim/Modia3D.jl/releases/tag/v0.2.0)
cc: @crlaugh

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@crlaugh This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by MartinOtter** [comment]
> CI passes for supported Julia versions (if applicable).

The CI failed, because Modia3D depends on ModiaMath and ModiaMath was not yet registered (a pull request was made for ModiaMath at the same time as for Modia3D). Since ModiaMath is registered now, the CI of Modia3D should be successful.

> Version bounds reflect minimum requirements.

I checked the REQUIRE file and all seems o.k. to me (most likely, the issue was that ModiaMath is present in the REQUIRE file, but was not yet registered when the CL of Modia3D run)

**Comment by MartinOtter** [comment]
Since ModiaMath is now registered, the checks on Modia3D should run now successfully.

**Comment by andreasnoack** [comment]
It looks like Travis testing for this hasn't run yet. Could you please also put the Travis badge in the README such that it becomes easier to check the test status?

**Comment by andreasnoack** [comment]
It looks like there are test failures on Julia 0.7/1.0 so please add an upper bound if these versions aren't supported yet.

**Comment by MartinOtter** [comment]
Sorry about the trouble above: We are new to the registration process and needed to learn some fine details.

In the meantime we have adapted Modia3D to Julia 0.7 (is already running without warnings) and by the end of the week we will have a good version both for Julia 0.7 and 1.0. We will make a new release (0.2.1) probably beginning of next week.

It is then probably best to reject the pull request above and we will make a new pull request (for the next version) next week.

**Comment by andreasnoack** [comment]
Sounds good. Thanks for the update.

**Pull request closed without merging**
