### PR TITLE
Tag NLPModelsJuMP.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaSmoothOptimizers/NLPModelsJuMP.jl](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl)
Release: [v0.2.0](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaSmoothOptimizers/NLPModelsJuMP.jl/builds/496222502)
Diff: [vs v0.1.1](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/compare/6c016657ee13f8ca442b0c4c17d1013719aef5c6...f0707124c7af772f3e4cadb2ff04b2f88abd7647)
`requires` vs v0.1.1: 
```diff
--- 0.1.1/requires
+++ 0.2.0/requires
@@ -1,5 +1,4 @@
-julia 0.6 2.0
-NLPModels 0.5.0
-JuMP 0.15 0.19
+julia 1.0 2.0
+NLPModels 0.7.0 0.8.0
+JuMP 0.18.5 0.19
 MathProgBase 0.7.6
-Compat
```
cc: @abelsiqueira

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
I'm guessing something happened related to https://github.com/JuliaLang/METADATA.jl/pull/21780. Is there anything I should do?

**Comment by dpo** [comment]
Bump.

**Comment by andreasnoack** [comment]
Please try to delete the release and create it again. That should effectively rebase the PR.

**Comment by abelsiqueira** [comment]
Thanks

**Pull request merged**
