### PR TITLE
Tag StaticArrays.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArrays/StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl)
Release: [v0.2.0](https://github.com/JuliaArrays/StaticArrays.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArrays/StaticArrays.jl/builds/201023228)
Diff: [vs v0.1.5](https://github.com/JuliaArrays/StaticArrays.jl/compare/cc229220a72ee33cc2d1cd3c5a57d04f755a99ad...7f610e0c4249b53ecc0ea06cf4c44c48038463e6)
`requires` vs v0.1.5: no changes
cc: @andyferris

### CODE REVIEW

**Comment by andyferris** [comment]
This resolves https://github.com/JuliaArrays/StaticArrays.jl/issues/101

cc @tkelman

**Comment by tkelman** [comment]
thanks. were any downstream packages using this?

**Comment by andyferris** [comment]
None that any of us are aware of. I guess it is difficult to truly know?

**Comment by tkelman** [comment]
pkgeval should do a decent job of finding any that break

**Pull request merged**
