### PR TITLE
Tag StatPlots.jl v0.8.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPlots/StatPlots.jl](https://github.com/JuliaPlots/StatPlots.jl)
Release: [v0.8.2](https://github.com/JuliaPlots/StatPlots.jl/releases/tag/v0.8.2)
Diff: [vs v0.8.1](https://github.com/JuliaPlots/StatPlots.jl/compare/05c7cc3c1f88de334c0eac0e7cf9f57ea082fa3f...5544052836b5028d5757093eeba0657a5bb09484)
`requires` vs v0.8.1: no changes
cc: @mkborregaard

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Comment by mkborregaard** [comment]
Why not merge it?

**Comment by mkborregaard** [comment]
I thought this was merged ages ago. Do we need to push a new release, and if so, why?

**Comment by andreasnoack** [comment]
It wasn't merged because the CIBot tests didn't pass. You can just delete the tag and release and then make the release again for a commit you find appropriate.

**Comment by mkborregaard** [comment]
OK, will do

**Pull request closed without merging**
