### PR TITLE
Register SimpleStructs.jl

### PR DESCRIPTION
**Pull request by pluskid**
Register [SimpleStructs.jl](github.com/pluskid/SimpleStructs.jl).

Reference: dmlc/MXNet.jl#40

### CODE REVIEW

**Comment by tkelman** [comment]
Neat. This looks a bit similar to @mauro3's https://github.com/mauro3/Parameters.jl, had you compared to that?

**Comment by pluskid** [comment]
@tkelman Thanks! I was not aware of that package. It seems the two packages are targeting (slightly) different use cases. Parameters.jl seem to be mostly useful for dealing with numerical parameters. After a brief looking at the readme, it seems the `pack` and `unpack` macros quite neat.

However, SimpleStructs.jl is more targeted to be used to handle specifications or more general hyperparameters. The design here is to allow
* default or required field values
* complicated value constraints 
* strongly typed fields

**Comment by mauro3** [comment]
Great minds think alike :smile: Yes, it does look quite similar.  I think Parameters.jl is more widely applicable than just numerical parameters, but that was the itch I was scratching, thus the somewhat unfortunate name.  I think the only place in type construction where the two packages differ is the explicit syntax for adding constraints and the implicit call to `convert`.  Note that constraints can be used in Parameters.jl too, but need to  be included in the constructor. So:
```julia
@defstruct StructName (
  field_name :: field_type,
  (fname2    :: ftype2 = default_val2, fname2 > 0 && fname2 < 5),
  (fname3    :: ftype3 = default_val3, fname3 <= fname2),
)
```
would read
```julia
@with_kw type StructName
  field_name::field_type
  fname2::ftype2 = default_val2
  fname3::ftype3 = default_val3
  function StructName(field_name, fname2, fname3)
    @assert fname2 > 0 && fname2 < 5
    @assert fname3 <= fname2
    new(field_name, fname2, fname3)
  end
end
```
the keyword constructor then calls the above constructor and thus constraints are checked.

Given the overlap, I think a merge would make sense.  I would be happy with adding constraints but not so much with adding the implicit call to `convert` (that deviates too much from the expected behavior for my taste).

**Comment by pluskid** [comment]
@mauro3 Thanks for the clarification! Now I see that they are more similar under the hood except the syntax. I also don't mind do a merging, but as I said above, I believe the targeting is slightly different.

SimpleStructs.jl is targeting the end user (instead of the developer) and heavily rely on the auto-call to `convert`. This is primarily as a workaround that Julia types are not covariant. For example, for a field of type `Vector{AbstractString}`, I want to allow the user to call with `field=["foo", "bar"]` as well as `field=["foo", "unicode-😀"]`.

Another example, for example (see the real code [here](https://github.com/dmlc/MXNet.jl/blob/master/src/callback.jl#L11-L25)), I have types
```julia
abstract AbstractT
abstract subT1
type T1 <: subT1
end
type T1_bar <: subT1
end

struct = Struct(..., field=[T1(), T1_bar()], ...)
```
I do not want the user to worry about the underlying type hierarchy a lot and do not want to force the user to have to call type conversion explicitly to vector of `AbstractT`. Things get much more complicated when other composite types (like `Dict` or `Vector` of `Vector`, etc.) are needed.

For my case, there will always be only one constructor (and for many cases, the constructor is hidden from the end user, because it gets wrapped in a function call with `kwargs...`, e.g. see [this](https://github.com/dmlc/MXNet.jl/blob/master/src/model.jl#L322)), and no parameter based dispatching is needed.

**Comment by mauro3** [comment]
Just to clarify: your user does not actually use the `@defstruct` macro, right?

Hmm, the `convert` seems to be implicitly done by julia:
```
julia> type A
       a::Vector{AbstractString}
       end

julia> A(["foo", "unicode-α"])
A(AbstractString["foo","unicode-α"])
```
When does this fail?

Anyway, maybe Parameters.jl could add the macro `@with_kw_autoconvert` (or some such) to allow for the conversion variant?

**Comment by pluskid** [comment]
@mauro3 No the users will not use `@defstruct` directly.

Thanks! That's a nice catch. It seems Julia constructors are doing something special, seems like auto-convert already called. Calling function
```
function test(x :: Vector{AbstractString})
```
fails but calling constructor for
```
type Test
  x :: Vector{AbstractString}
end
```
will work. If the scenario works perfectly fine with Parameters.jl, I would be happy to close this PR and add a link in SimpleStructs.jl README to Parameters.jl.

**Comment by eschnett** [comment]
@mauro3 "I would be happy with adding constraints [...]": Yes, please!

**Comment by mauro3** [comment]
@pluskid I need to look up when conversion is implicit.  Maybe there are cases when defining inner constructors when this fails.

@eschnett issue created.

**Comment by Evizero** [comment]
The appealing thing about the `@defstruct` macro to me is the `convert` and the nice sugar for constraints. The convert because I would like the field to be strongly typed (as `Float64` for example), but the user to be able to specify that kw-arg (in the constructor) as an Int

**Comment by mauro3** [comment]
Ok, so I had a look at when constructors do automatic conversion:  https://gist.github.com/mauro3/dfd68bbaaa5f8c76761c . The answer is "always" (as it says in the docs), but it doesn't always work.

An example where it doesn't work is:
```julia
type D1{I}
    b::Vector{Integer}
    c::I
end
D1(Int[2,3],"A") # fails.
# This falls back to convert(D1, Int[2,3],"A") which of course fails.

# custom outer constructor fixes this:
type D2{I}
    b::Vector{Integer}
    c::I
end
D2{I}(b,c::I) = D2{I}(b,c)
D2(Int[2,3],"A") # works
```
Note that this case isn't handled by SimpleStructs nor Parameters.

@Evizero: would the constraints as proposed in https://github.com/mauro3/Parameters.jl/issues/6 work for you?

**Comment by Evizero** [comment]
Any news on this @mauro3 ?

**Comment by Evizero** [comment]
Because this package works now as it is, and there are serious time-budgets associated with having this functionality in Parameters.jl, I vote to merge SimpleStructs.jl

I do see the point of merging efforts to reduce redundancy. But if the manpower is lacking to actually do it (which is very understandable), such a plan to join forces might just be in the way of making any progress in the near future

**Comment by mauro3** [comment]
Is using `Pkg.clone("git@github.com:pluskid/SimpleStructs.jl.git")` not an option until this matter settles?

**Comment by Evizero** [comment]
Well. I would like to refactor my code to use this (and also base new code that I am currently writing on this) but I can't really write the clone statement into the REQUIRE file. Also I rather not refactor it again in a few months.

I don't see the harm in having this package in METADATA. It's not like the package name "SimpleStructs" would likely be useful in a different context.

At the end of the day, it's not my decision. I'm ok with that. I'm just stating my opinion on this. It is depressing in some sense that a minimalistic but useful package is blocked because something similar - that doesn't have the core functionality of the new thing - already exists in some form. It almost seems like once someone got his/her package into METADATA that he/she has earned the claim on the topic. Of course the opposite extreme of having 100 packages for the same thing would also suck, but somewhat of a compromise could mitigate code-base stagnation

Probably what's going to happen is that I'll end up copying the SimpleStructs macro (and including the license) to move on from this stalemate. It's the worst of all solutions, but at some point convenience takes over.

**Comment by mauro3** [comment]
FYI: constraints are now implemented in Parameters.jl

**Pull request merged**
