### PR TITLE
Register and tag Dtree

### PR DESCRIPTION
**Pull request by kpamnany**
Used by Celeste.

### CODE REVIEW

**Comment by tkelman** [comment]
If you enabled Travis CI would the package work there? Could you run the bench file you've written as part of runtests.jl?

**Comment by dpsanders** [comment]
Searching for `dtree` on Google does not seem to find the package that this is a wrapper for. Is there a better option for the package name?

**Comment by dpsanders** [comment]
In fact, there seems to be no information about the original package in the repository, nor in the LICENSE file.

**Comment by kpamnany** [comment]
@tkelman: The microbenchmark is essentially an MPI application and has to be started with ``mpiexec`` on a few nodes/cores. I wasn't able to work out how to do that. I'll play with it some more when I get a chance, but this code is pretty well tested already.

@dpsanders: The ``README.md`` file in the repository cites the paper that describes this implementation. If you search for ``dtree`` together with my name on Google Scholar, this paper comes up.

**Comment by tkelman** [comment]
> this code is pretty well tested already.

Would be good to hook that up into a standard unit test suite so that's easy to verify. You should be able to get one or multiple of the open-source mpi implementations running on Travis.

**Pull request merged**
