### PR TITLE
Pull request/6e1c59ed

### PR DESCRIPTION
**Pull request by tpoisot**
OK, so version `1.2.1`, with `Colors` instead of `Color`.

### CODE REVIEW

**Comment by tkelman** [comment]
If you're dropping support for julia 0.3 with 1.2.1, it should use a new minor version.

**Comment by tpoisot** [comment]
Support for Julia was actually dropped at 1.2.0

**Comment by tkelman** [comment]
The require file needs to be adjusted for that to be the case.

**Comment by tpoisot** [comment]
Wouldn't that be re-writing history? What's the simplest way to proceed?

**Comment by tkelman** [comment]
You can modify the requires file in your fork of metadata... which you appear to have deleted.

**Comment by tkelman** [comment]
We can try these tags again, but don't delete your fork until after a PR is merged, otherwise there's no way to make modifications.

**Pull request closed without merging**
