### PR TITLE
Tag CSTParser.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ZacLN/CSTParser.jl](https://github.com/ZacLN/CSTParser.jl)
Release: [v0.4.0](https://github.com/ZacLN/CSTParser.jl/releases/tag/v0.4.0)
Diff: [vs v0.3.5](https://github.com/ZacLN/CSTParser.jl/compare/57a60fbb7cfe2dd049c914929d4dbc0d58c81d35...7e893c3441176199c8bcaa417625571fd68585a0)
`requires` vs v0.3.5: 
```diff
--- 0.3.5/requires
+++ 0.4.0/requires
@@ -1,3 +1,2 @@
-julia 0.6.0
-Tokenize 0.4.0
-AbstractTrees
+julia 0.7.0
+Tokenize 0.5.2
```
cc: @ZacLN

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
There is already a 0.4.0 in METADATA but with a different sha. What happened?

**Comment by ZacLN** [comment]
Arg! I deleted the release, waiting for a response on the previous pull. Then I think you merged it before I reset the tag and made a new release- how can I fix this?

**Comment by andreasnoack** [comment]
I'm not sure. My guess is that the best thing to do would be to delete the current v0.4.0 in your repo, make a v0.4.1 release, merge it into METDATA, and then delete v0.4.0 here in METADATA.

**Comment by ZacLN** [comment]
OK done :crossed_fingers:

**Pull request closed without merging**
