### PR TITLE
Tag DoubleDouble v0.2.0

### PR DESCRIPTION
**Pull request by dpsanders**
Updates for v0.4; Travis is enabled.
Minor tag since the public API for the constructor changed `double -> Double`

cc @simonbyrne @ivanslapnicar

### CODE REVIEW

**Comment by tkelman** [comment]
Will existing versions of ArrowHead.jl need an upper bound?

**Comment by dpsanders** [comment]
I guess so, yes, good point.

**Comment by dpsanders** [comment]
The `Arrowhead.jl` tests passed so we (with @tkelman) merged this. Let me know if there are any problems @ivanslapnicar

**Comment by ivanslapnicar** [comment]
@dpsanders thanks. Everything works fine.

**Pull request merged**
