### PR TITLE
Register Immerse

### PR DESCRIPTION
**Pull request by timholy**
Immerse sits on top of Gadfly and adds some new forms of interactivity. Documentation is nonexistent at the current time, but I plan to fix that by the time I release the next tutorial video.

Let the name bikeshedding begin.

### CODE REVIEW

**Comment by tkelman** [comment]
Shouldn't it depend on everything it imports? https://github.com/JuliaGraphics/Immerse.jl/blob/dee2115d8e0a2274610142c56c97b5f796442018/src/Immerse.jl#L3

**Comment by timholy** [comment]
Good catch. Will fix.

**Comment by IainNZ** [comment]
This is a many-approachs-to-a-big-problem type package, so name is fine with me as-is.

**Comment by quinnj** [comment]
+1

**Comment by milktrader** [comment]
I want to use this name for a method in a Liquid State Machine package :smile:

**Comment by tbreloff** [comment]
Don't worry... You can always name it Drown.jl

**Comment by timholy** [comment]
> I want to use this name for a method in a Liquid State Machine package 

Thank goodness for lowercase, then :smile:.

**Pull request merged**
