### PR TITLE
Register Slugify: v0.1.0

### PR DESCRIPTION
**Pull request by eraviart**

### CODE REVIEW

**Comment by milktrader** [comment]
Curious why this is licensed under Apache License Version 2.0

**Comment by eraviart** [comment]
No special reason: For small projects like this one, I use Apache
License 2.0 by default, but it could be any non-copyleft license. Is
this license a problem for you?

**Comment by StefanKarpinski** [comment]
Apache 2.0 may not be compatible with GPLv2: http://www.apache.org/licenses/GPL-compatibility.

**Comment by milktrader** [comment]
The standard license for Julia packages is the MIT license.

**Comment by kmsquire** [comment]
(Which doesn't mean new projects are required to be MIT licensed, just encouraged.)

**Comment by eraviart** [comment]
License changed to MIT in Slugify 0.1.1 https://github.com/eraviart/Slugify.jl/commit/a8191225799beaace0355bc97eca0c0cd1e9abef

**Pull request merged**
