### PR TITLE
Tag ZippedArrays.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bramtayl/ZippedArrays.jl](https://github.com/bramtayl/ZippedArrays.jl)
Release: [v0.0.2](https://github.com/bramtayl/ZippedArrays.jl/releases/tag/v0.0.2)
Travis: [Travis Build Status](https://travis-ci.org/bramtayl/ZippedArrays.jl/builds/364308584)
Diff: [vs v0.0.1](https://github.com/bramtayl/ZippedArrays.jl/compare/e0441f10ebbb8b989ee85bfbc6801fdb34164b2e...9895cbe713d92ab12c0d4aa3695f9e0038facb97)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.0.2/requires
@@ -1 +1,2 @@
-julia 0.6+julia 0.6
+Compat
```
cc: @bramtayl

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by bramtayl** [comment]
Nevermind hold off on this one I want to get an inference free collect up and running.

**Comment by aviks** [comment]
Good to go?

**Comment by andreasnoack** [comment]
Good to go now?

**Comment by bramtayl** [comment]
Sorry for the slow response. Yes this is good to go.

**Pull request merged**
