### PR TITLE
Tag Polyhedra and CDDLib

### PR DESCRIPTION
**Pull request by blegat**
* Tag Polyhedra v0.1.0 [https://github.com/blegat/Polyhedra.jl]
* Tag CDDLib v0.1.0 [https://github.com/blegat/CDDLib.jl]

### CODE REVIEW

**Comment by joehuchette** [comment]
Travis is failing with:
```
ERROR: LoadError: New tag 0.0.2 of package Polyhedra requires julia 0.5.0, but version 0.0.1 of Polyhedra requires julia 0.4.0. Use a new minor package version when support for an old version of Julia is dropped. Re-tag the package as 0.1.0 using `Pkg.tag("Polyhedra", :minor)`.
```

**Comment by blegat** [comment]
Thanks, I have updated the tags :)

**Comment by joehuchette** [comment]
Now this:
> ERROR: LoadError: LoadError: The following tags for CDDLib have not been pushed to upstream repository: 0.1.0.

**Comment by blegat** [comment]
It is pushed now :) Can someone with right access trigger a rebuild on travis ?

**Pull request merged**
