### PR TITLE
Register new package StaticPolynomials.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaAlgebra/StaticPolynomials.jl](https://github.com/JuliaAlgebra/StaticPolynomials.jl)
Release: [v0.1.0](https://github.com/JuliaAlgebra/StaticPolynomials.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaAlgebra/StaticPolynomials.jl/builds/372622194)
cc: @saschatimme

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@saschatimme This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by saschatimme** [comment]
JuliaCIBot failed since I use for my Tests a non-registered package. This package just contains a couple of test systems which I use to for a couple of packages. What is the recommended way to deal with such a situation?

**Comment by andreasnoack** [comment]
If it is used by several packages then I'd just register the helper package. Otherwise, I'd copy the code to the relevant package(s).

**Comment by saschatimme** [comment]
Everything should now be fine @andreasnoack, sorry for the noise.

**Comment by andreasnoack** [comment]
Great. I'll keep the PR open for a little longer to allow people to comment on name and content.

**Comment by saschatimme** [comment]
Just added a small bugfix to this release to avoid an immediate point update.

**Pull request merged**
