### PR TITLE
Register Julia package VarianceComponentTest

### PR DESCRIPTION
**Pull request by Tao-Hu**

### CODE REVIEW

**Comment by tkelman** [comment]
It would be best if you can tag a release, otherwise the package can't be added via `Pkg.add`

**Comment by tkelman** [comment]
Thanks. It's also best practice to be explicit about your minimum Julia requirement by adding a line like `julia 0.3` to your `REQUIRE` file, assuming you aren't testing with versions older than 0.3.

**Comment by milktrader** [comment]
@tkelman I guess the docs just need to be updated to reflect these important details. I'm evaluating my time commitments to see if I will assign it to myself.

**Comment by milktrader** [comment]
ok, I'll do it. I'll _find_ the time :smile:

**Comment by Tao-Hu** [comment]
@tkelm I have already add a line about Julia version requirement to the `REQUIRE` file. Should I tag another release?

**Comment by tkelman** [comment]
Either that or you can add it to the `VarianceComponentTest/versions/0.0.1/requires` file in this branch.

**Comment by Tao-Hu** [comment]
@tkelman Adding done.

**Pull request merged**
