### PR TITLE
Register new package IOLogging.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Seelengrab/IOLogging.jl](https://github.com/Seelengrab/IOLogging.jl)
Release: [v0.1.0](https://github.com/Seelengrab/IOLogging.jl/releases/tag/v0.1.0)
cc: @Seelengrab

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@Seelengrab This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by Seelengrab** [comment]
That JuliaCIBot failure seems unrelated to my package - right?

**Comment by andreasnoack** [comment]
Well, I wouldn't call it *unrelated* as your package somehow manages to trigger a bug in Pkg. Unfortunately, we probably have to wait with merging this PR until we understand the bug since there is a risk that it would break the resolver.

Ref https://github.com/JuliaLang/Pkg.jl/issues/750

**Comment by andreasnoack** [comment]
This is caused by
```julia
julia> Pkg.Types.semver_spec(">=0.7, ^1")
ERROR: type VersionBound has no field lo
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
 [2] isjoinable(::Pkg.Types.VersionBound, ::Pkg.Types.VersionBound) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/versions.jl:69
 [3] union!(::Array{Pkg.Types.VersionRange,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/versions.jl:159
 [4] Type at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/versions.jl:183 [inlined]
 [5] semver_spec(::String) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/versions.jl:268
 [6] top-level scope at none:0
```
cc: @KristofferC

**Comment by Seelengrab** [comment]
Oh boy! Just FYI, I added this spec to make sure it wouldn't be installed on anything after 1.x, since the logging interface could [change a bit](https://github.com/JuliaLang/julia/blob/7d6bc6bd1eb12d08113efb1995717ae6b2bccdcd/stdlib/Logging/src/Logging.jl#L5-L9).

**Comment by Seelengrab** [comment]
I think this is indicative of more than just that - shouldn't this:

```
julia> Pkg.Types.semver_spec(">=0.7, ^0")
VersionSpec("0.0.0-*")
```

give `VersionSpec("0.7.0-0.*")`? And the original spec should give `VersionSpec("0.7.0-1.*")`, if I understand correctly (Ref. [this](https://discourse.julialang.org/t/specify-version-range-with-specific-versions-in-compat-on-0-7-1-0/15018) discussion on discourse).

**Comment by andreasnoack** [comment]
Yes. That doesn't look right. Would be great if you could report that as a separate issue at https://github.com/JuliaLang/Pkg.jl/issues

**Comment by Seelengrab** [comment]
Done! 

I guess I can change the version spec to `julia = "0.7"` for now? Not ideal though.

**Comment by fredrikekre** [comment]
The project file won't be used in the conversion anyways, so what matters is what you have in REQUIRE

**Comment by andreasnoack** [comment]
I'll recommend that you just set `julia = ">=0.7` for now and then adjust this once `Pkg` has been updated.

**Comment by Seelengrab** [comment]
I've changed both REQUIRE and Project.toml to no longer specify an upperbound for the package. ~Is it possible to rerun JuliaCIBot and your travis to confirm this?~ Nevermind, I remembered about the functionality of attobot.

**Pull request merged**
