### PR TITLE
Register new package Planets.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [dcarrera/Planets.jl](https://github.com/dcarrera/Planets.jl)
Release: [v0.2.0](https://github.com/dcarrera/Planets.jl/releases/tag/v0.2.0)
cc: @dcarrera

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@dcarrera This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
The name of this package seems too generic and does not specify the content. Maybe you could change the name to be more specific?

**Comment by dcarrera** [comment]
Sorry for the late resposne.

I have tried and failed to come up with a better name. The problem is that I plan to have several different things that are tied to either planet formation or their evolution. The things I want to slowly add include:

1) Computing the size of a planet.
2) Opacity of a protoplanetary disk.
3) Internal structure of a protoplanetary disk.
4) Changes in the planet's orbit due to interactions with a protoplanetary disk (needs [2] and [3]).
5) Accretion of gas onto a planet to make its atmosphere (needs [4]).
6) Loss of planet atmospheres due to collisions or stellar irradiation.

So... maybe "PlanetFormation" is better, but that sounds a bit long and some bits (like [1]) are not strictly about formation.

**Comment by andreasnoack** [comment]
It looks like it's your lucky day. GitHub has had major issues today and it looks like the issues have caused the webhook information to be wrong in a way that triggered the automatic merge for this PR.

**Comment by dcarrera** [comment]
I haven't decided whether I like `PlanetFormation` better (it's slightly inaccurate), but in principle, is there a procedure for renaming modules?

**Comment by andreasnoack** [comment]
Not now but eventually there should be a way to do this.

**Pull request merged**
