### PR TITLE
Tag Quaternions v0.1.0

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by tkelman** [comment]
I'd remove the 0.0.5 tag if we aren't going to test it on 0.2. Also remove the trailing `-` on `julia 0.3-` for 0.1.0.

**Comment by SimonDanisch** [comment]
Okay! Should I rebase?

**Comment by tkelman** [comment]
Yeah, if it's not too much trouble.

**Comment by SimonDanisch** [comment]
Okay, not sure why `rebase -i HEAD~4` is not working, but `reset --sof HEAD~4t` seems to have done the right thing :D

**Pull request merged**
