### PR TITLE
Pull request/23f87e97

### PR DESCRIPTION
**Pull request by aaronstanton**
adding a tagged version

### CODE REVIEW

**Comment by aaronstanton** [comment]
Hi Tony,

I'm having a problem that I believe is related to the fact that this
package has two modules: Seismic.jl and SeismicPlotting.jl

When I add the package: *>Pkg.add("Seismic") * followed by *>using
Seismic* everything
is fine, but the second module *>using SeismicPlotting *isn't found. Should
this module be put into another package, or is there special syntax to load
it in this case?

Cheers,

Aaron

**Comment by tkelman** [comment]
Top-level `using SeismicPlotting` will only work if that's a separate package, yes.

**Comment by dpsanders** [comment]
Maybe a solution (as Tony hinted) is to make a submodule so that you could write
using Seismic.SeismicPlotting?

**Comment by dpsanders** [comment]
Or just using Seismic.Plotting?

**Comment by aaronstanton** [comment]
That is a good solution, I will make two submodules Seismic.Processing and
Seismic.Plotting

**Pull request merged**
