### PR TITLE
Add WeakRefStrings package

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by tkelman** [comment]
New package registrations should remain open for 24 hours...

**Comment by tkelman** [comment]
The package doesn't pass tests on 0.4. Does it support 0.4?

**Comment by quinnj** [comment]
Sorry about the 24 hour thing. Got 0.4 compat done and a new PR for it. https://github.com/JuliaLang/METADATA.jl/pull/5438

**Comment by dpsanders** [comment]
I actually think it should be a policy (enforceable in github?)  that nobody should merge the registration if their own package.

**Pull request merged**
