### PR TITLE
Register new package Case.jl v0.0.1

### PR DESCRIPTION
**Pull request by djsegal**
Repository: [djsegal/Case.jl](https://github.com/djsegal/Case.jl)
Release: [v0.0.1](https://github.com/djsegal/Case.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/djsegal/Case.jl)
cc: @djsegal

### CODE REVIEW

**Comment by djsegal** [comment]
Would this be approved if I change the name to:

+ `StringCasing.jl`

?

**Comment by omus** [comment]
I think StringCasing.jl would be a better name (sorry, for going through another rename)

**Comment by omus** [comment]
@KristofferC what name would you prefer?

**Comment by djsegal** [comment]
closing in favor of: #12428

**Pull request closed without merging**
