### PR TITLE
Tag PGFPlotsX.jl v0.3.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [KristofferC/PGFPlotsX.jl](https://github.com/KristofferC/PGFPlotsX.jl)
Release: [v0.3.3](https://github.com/KristofferC/PGFPlotsX.jl/releases/tag/v0.3.3)
Travis: [Travis Build Status](https://travis-ci.org/KristofferC/PGFPlotsX.jl/builds/458333228)
Diff: [vs v0.3.2](https://github.com/KristofferC/PGFPlotsX.jl/compare/dc92689ae57b96acfb1fe10916cf7f543f9be1dc...d568a44505874688d81274d3a7c6f08cce82d00c)
`requires` vs v0.3.2: no changes
cc: @tpapp

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Tests are still failing

**Comment by tpapp** [comment]
My guess is that the `pdftoppm` to binaries are not available in the environment, but I am not a 100% sure.

1. I would like to debug this in a branch, is that possible? Ie invoke JuliaCIBot without tagging, or somehow reproduce its build environment.
2. Is it possible to check that `pdftoppm` is available when using JuliaCIBot?

**Comment by andreasnoack** [comment]
`pdftoppm` is not available on CIBot. Unfortunately, we don't have an easy way to provide access to a CIBot environment. Should I just merge for now?

**Comment by tpapp** [comment]
I am working on making these tests conditional, will modify the release. Please don't merge yet.

**Pull request merged**
