### PR TITLE
Tag TimeZones v0.3.0 [https://github.com/JuliaTime/TimeZones.jl]

### PR DESCRIPTION
**Pull request by omus**
Now supports Julia 0.6 via the nightly

### CODE REVIEW

**Comment by tkelman** [comment]
If the content of the windows xml file ever changes due to a download, it'll make the package dirty and prevent it from upgrading

**Comment by omus** [comment]
Interesting point. I guess the solution is to avoid overriding the committed file.

**Comment by omus** [comment]
Fixed the issue with the windows xml file making the package dirty. Updated the SHA1 and pushed an updated tagged version.

**Comment by tkelman** [comment]
Can you fix the issue where this downloads that file repeatedly and never cleans up after itself?

**Comment by omus** [comment]
I'll make a patch release for that.

**Pull request merged**
