### PR TITLE
Register new package GenomicVectors.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [phaverty/GenomicVectors.jl](https://github.com/phaverty/GenomicVectors.jl)
Release: [v0.0.1](https://github.com/phaverty/GenomicVectors.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/phaverty/GenomicVectors.jl/builds/221152304)
cc: @phaverty

### CODE REVIEW

**Comment by tkelman** [comment]
Since you have `import DataStructures: OrderedDict` in `src/GenomicVectors.jl`, should add `DataStructures` directly to `REQUIRE` - currently you're relying on it being installed as a transitive dependency, which might not always be the case

**Comment by phaverty** [comment]
Oh, I actually switched from OrderedDict to AxisArrays for this. I have
fixed REQUIRE and src/GenomicVectors.jl.  I'm somewhat surprised that this
didn't break things.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by tkelman** [comment]
That's usually a sign that test coverage could be improved :)

Looks good with https://github.com/phaverty/GenomicVectors.jl/commit/1aaa77e267ebf0b51aa4eb21656567215494429d, should probably amend or replace the tag for that?

**Comment by phaverty** [comment]
I have amended the tag.  Thanks for the careful review.  I'll get to work
on those tests ... :-)

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Pull request merged**
