### PR TITLE
Tag QDates.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [antimon2/QDates.jl](https://github.com/antimon2/QDates.jl)
Release: [v0.3.0](https://github.com/antimon2/QDates.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/antimon2/QDates.jl/builds/491450492)
Diff: [vs v0.2.0](https://github.com/antimon2/QDates.jl/compare/5a038bad95734ec506309f5d915a1b1a4b929da5...18654bd0d933e5bcbb1da074e60dc5128caf731a)
`requires` vs v0.2.0: no changes
cc: @antimon2

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dpsanders** [comment]
Maybe the package name could be more explicit about the package purpose? "Q" is not very informative. Eg. JapaneseKurekiDates.jl

**Comment by antimon2** [comment]
@dpsanders 
I'm sorry for my late response.

"Q" comes from Chinese Character "旧",  That is almost the same pronunciation as "Q" in Japanese (like [kjuː]), and means "old" or "traditional".
"QDate", "旧日付" in Japanese, means "Japanese Kyūreki Date".
And the package name "QDates" means "A package that handles a type `QDate`.

I see that this is not intuitive for those non-Japanese.
If it is preferable to (or I SHOULD, or I MUST) change the package name, should I delete all the past versions from METADATA.jl?

**Comment by andreasnoack** [comment]
@dpsanders I don't think we should discuss package names then tagging releases. The right place for name discussions is when a package is being registered.

**Comment by dpsanders** [comment]
@andreasnoack Yes, I totally agree -- sorry, for some reason I thought this was a package registration.

**Pull request merged**
