### PR TITLE
Register Julia PDK (Botched)

### PR DESCRIPTION
**Pull request by wildart**
A wonderful package that could publish itself.

### CODE REVIEW

**Comment by jakebolewski** [comment]
I think all the docstrings that got removed should be added to the package.

**Comment by wildart** [comment]
I moved docstring from `helpdb.jl` to `PkgDev.jl` for related functions.

**Comment by hayd** [comment]
Note the error:
```
ERROR: LoadError: AssertionError: Invalid url scheme https for package PkgDev. Should be 'git' 
```
Presumably the docs for package development are going remain in the main julia lang docs?

**Comment by wildart** [comment]
For the new package manager all packages would be registered with `https` protocol, `git`+`ssh` will be dropped. Because the nightly version is shipped with `libgit2` library that is built without support of `ssh` protocol.

**Comment by wildart** [comment]
Messed it up. See #3628

**Pull request closed without merging**
