### PR TITLE
Tag LanguageServer.jl v0.2.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaEditorSupport/LanguageServer.jl](https://github.com/JuliaEditorSupport/LanguageServer.jl)
Release: [v0.2.3](https://github.com/JuliaEditorSupport/LanguageServer.jl/releases/tag/v0.2.3)
Diff: [vs v0.2.2](https://github.com/JuliaEditorSupport/LanguageServer.jl/compare/f40bf8741fe0fbebdc6e1d1a2578a652b5d0088b...b0dff964d7e3d454b8eb756d06bb9e3601f3c595)
`requires` vs v0.2.2: no changes
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
> ERROR: LoadError: METADATA/LanguageServer/versions/0.2.3/requires: prerelease 0.6.0-rc1 not allowed (>= 0.6.0 needed)

**Comment by davidanthoff** [comment]
Could we make an exception to this policy here, only one time? This is the commit that shipped in the VS Code extension, and I'd like the release tags to correspond to the versions that we shipped. I've updated REQUIRE on ``master``, so this should be solved for the next release.

**Comment by KristofferC** [comment]
You should be able to just manually change the REQUIRE file in this PR. It won't correspond to the REQUIRE in the repo but that is the same situation when adding upper bounds to previous releases.

**Comment by aviks** [comment]
Not sure how to do that.  A new PR would be best, I think.

**Pull request closed without merging**
