### PR TITLE
Register ProgressiveAligner: v0.3.0

### PR DESCRIPTION
**Pull request by latticetower**

### CODE REVIEW

**Comment by tkelman** [comment]
Hi, thanks for the package submission. It needs a requirements file indicating the minimum supported version of julia, and any other package dependencies.

**Comment by latticetower** [comment]
Hi, I fixed that.

**Comment by tkelman** [comment]
Great, thanks. Note that the tagged commit here is from october, do you want to update that? https://github.com/latticetower/ProgressiveAligner.jl/commits/master

**Comment by latticetower** [comment]
I realized that I forget to tag new code version. Sorry. I'll fix that and make new pull request.

**Pull request closed without merging**
