### PR TITLE
Register NBInclude: v1.0.0

### PR DESCRIPTION
**Pull request by stevengj**
[NBInclude](https://github.com/stevengj/NBInclude.jl) is a package that exports a single function: `nbinclude(path)`.   It is pretty much a drop-in replacement for `include`, except that `path` is an IJulia notebook instead of a `.jl` file.

I've had a couple of people asking for this, so that they could re-use code in notebooks without copying it to a `.jl` file, and to provide a mechanism for [literate programming](https://en.wikipedia.org/wiki/Literate_programming) in Julia.

The analogue in IPython is `%run 'my_notebook.ipynb'`

Closes JuliaLang/IJulia.jl#334.

### CODE REVIEW

**Comment by tkelman** [comment]
Seems there's a remotecall failure on 0.3?

**Comment by stevengj** [comment]
That's weird, I just tried `Pkg.test("NBInclude")` on 0.3.11 on my machine and it passed.

**Comment by stevengj** [comment]
Changed from `https` to `git` URL and did a force-push, let's see if Travis passes now.

**Comment by tkelman** [comment]
It might be windows-only https://ci.appveyor.com/project/StevenGJohnson/nbinclude-jl/build/1.0.1/job/3ibm5kl75g7udi1r, I'm not seeing a Travis status. Not turned on yet?

**Comment by stevengj** [comment]
I turned on Travis this morning (it took a while for NBInclude to show up on my travis page), but haven't triggered a build yet.

**Comment by stevengj** [comment]
Looks like I was missing `using Compat` in the test script.  Not sure why it still worked on my machine.

**Comment by stevengj** [comment]
Ah, the reason it still doesn't work is that it needs a new version of Compat that hasn't been tagged yet (for JuliaLang/Compat.jl@941ff2405bc44e67a6c1a8e6c6f95d718dd183f2).  It works on my machine because I checked out compat.

**Comment by stevengj** [comment]
Okay, fixed the requires now that Compat 0.7.6 has been tagged (thanks @andreasnoack).

**Comment by stevengj** [comment]
Hooray, Appveyor is passing now.

Now that I have a package that actually works as advertised (I hope!), is there any objection to merging this?

**Comment by tkelman** [comment]
Will take that as a no.

**Pull request merged**
