### PR TITLE
Pull request/1e508fd2

### PR DESCRIPTION
**Pull request by sonVishal**
Numerical solution of nonlinear (NL) equations (EQ) especially designed for numerically sensitive problems.

Based on the Fortran solvers [NewtonLib](http://elib.zib.de/pub/elib/codelib/NewtonLib/index.html).

Currently the following two solvers are implemented:
- NLEQ1: Damped Newton-algorithm for systems of highly nonlinear equations - damping strategy due to Ref. (1).
- NLEQ2: Damped Newton-algorithm with rank strategy for systems of highly nonlinear equations - damping strategy due to Ref.(1).

### CODE REVIEW

**Comment by tkelman** [comment]
If this is derived from code with the ZIB license, then I don't think that grants you permission to redistribute under the MIT license.

**Comment by kmsquire** [comment]
Bump

**Comment by sonVishal** [comment]
This is what my supervisor at TUM, Dr Christian Ludwig, emailed me after talking to the people at ZIB:

> Hallo Vishal Sontakke,
> 
> here is my translation of the email of Mr. Weiser:
> 
> =====
> 
> the algorithms are public available anyway. The copyright of the ZIB
> covers only the concrete realisation with the Fortran-Codes.
> 
> Provided that the implementation in Julia is not a one-to-one transfer
> of this Fortran-Codes (which is also not appropriate for the language),
> there is nothing to be said against the publication under/using the MIT
> license. Depending on the "degree of similarity" it is advisable to give
> a reference to the publications of Deuflhard and if applicable to the
> original codes.
> 
> I wish (you) much success incorporating (your code) to the Julia library.
> 
> Kind regards
> Martin Weiser
> 
> =====
> 
> Lieber Herr Dr. Ludwig,
> 
> die Algorithmen als solche sind ohnehin frei verfügbar. Das Urheberrecht
> des ZIB erstreckt sich also nur auf die konkrete Realisierung der
> Fortran-Codes.
> 
> Sofern die Julia-Implementierung keine Eins-zu-eins-Übertragung der
> Fortran-Quellen ist (was der Sprache ja auch gar nicht angemessen wäre),
> spricht nichts gegen eine Veröffentlichung unter MIT-Lizenz. Je nach
> "Ähnlichkeitsgrad" empfiehlt sich dabei ein Hinweis auf die
> Publikationen von Deuflhard und ggf. auf die Original-Codes.
> 
> Ich wünsche viel Erfolg beim Einbringen in die Julia-Bibliothek.
> 
> Schöne Grüße
> Martin Weiser
> 
> =====
> 
> I hope this helps.
> 
> Bye
> C. Ludwig

**Comment by aviks** [comment]
@sonVishal do you still want to register this package?

**Comment by KristofferC** [comment]
Closing due to inactivity.

**Pull request closed without merging**
