### PR TITLE
Make LevelDB compatible with Julia 0.5 and release it as v1.0.2

### PR DESCRIPTION
**Pull request by jerryzhenleicai**

### CODE REVIEW

**Comment by tkelman** [comment]
Few things: METADATA is frozen for package versions that support Julia 0.3. Change the minimum Julia version in your REQUIRE file to 0.4 or 0.5 and re-tag as package 1.1.0. The git tag should match the METADATA tag.

**Comment by tkelman** [comment]
You're also missing Compat in your `REQUIRE` file, and it's recommended to enable Travis CI if possible.

**Comment by aviks** [comment]
Hi @jerryzhenleicai Do you still want to tag this? Can you fix the errors please?

**Comment by KristofferC** [comment]
Closing due to inactivity.

**Pull request closed without merging**
