### PR TITLE
Tag Currencies.jl v0.12.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaFinance/Currencies.jl](https://github.com/JuliaFinance/Currencies.jl)
Release: [v0.12.0](https://github.com/JuliaFinance/Currencies.jl/releases/tag/v0.12.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaFinance/Currencies.jl/builds/499691453)
Diff: [vs v0.11.0](https://github.com/JuliaFinance/Currencies.jl/compare/7d28ee8f60e9c78cf1a2e671033334866eb47f54...b21a74c9c18680400995e86ca4d53df92753ae1c)
`requires` vs v0.11.0: no changes
cc: @EricForgy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Was this release also a mistake then?

**Comment by EricForgy** [comment]
Hi @fredrikekre ,

This is my attempt at fixing things, but I think I'm still doing something wrong 😔 

This package should only depend on DelimitedFiles, but when I add it, it is still pulling dependencies from an earlier tag and I don't understand what is going on 😔 

Any ideas? 🙏

**Comment by EricForgy** [comment]
If I look here

https://github.com/JuliaRegistries/General/blob/master/C/Currencies/Deps.toml#L15-L16

I see the correct dependencies.

The Manifest.toml looks ok to me.

https://github.com/JuliaFinance/Currencies.jl/blob/master/Manifest.toml

🤔 

Nevertheless, when I add it, it pulls a bunch of extra dependencies that v0.10.0 depended on

image

Any ideas? 🙏

**Comment by EricForgy** [comment]
Hi @fredrikekre 

I noticed 

https://github.com/JuliaLang/METADATA.jl/pull/21780

Thank you for helping 🙏 

I think I see what's going on.

https://github.com/JuliaRegistries/General/commit/609034d773a25aae1af6ebe04ff066d7cda7cdb2

That is showing v0.12.0 depends on Test, but v0.12.0 doesn't have a dependency on Test. That is why it is pulling in the extra dependencies. How to fix that? 🤔 

https://github.com/JuliaFinance/Currencies.jl/blob/master/Project.toml

**Comment by fredrikekre** [comment]
> This is my attempt at fixing things

Fix what?

> That is showing v0.12.0 depends on Test, but v0.12.0 doesn't have a dependency on Test. That is why it is pulling in the extra dependencies. How to fix that?

Wait for the new registration process.

Again, did you intend to tag 0.12 of Currencies in METADATA?

**Comment by EricForgy** [comment]
> Fix what?

Fix the fact that v0.11.0 doesn't exist anymore on my repo. I tried to add it back by tagging a new v0.11.0, but the sha1 was different. 

When I 

```
pkg> add Currencies#master
```

it was showing v0.11.0 and pulling in extra dependencies. I didn't know why. So thought if I tag a new version v0.12.0 that actually works as desired, then I could forget about any issues with v0.11.0.

> Again, did you intend to tag 0.12 of Currencies in METADATA?

Yes.

> Wait for the new registration process.

This https://github.com/JuliaRegistries/General/blob/master/C/Currencies/Deps.toml#L15-L16

```julia
["0.10-0.12"]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

should be

```julia
["0.10-0.11"]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

or maybe even

```julia
["0.10"]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

Is waiting the only way possible to make that change?

Thank you again 🙏

**Comment by fredrikekre** [comment]
> Is waiting the only way possible to make that change?

Yes, stdlib dependencies like that does not really matter anyway since they are always available.

**Comment by EricForgy** [comment]
Great! Everything seems fine now. When I saw the extra dependencies going into my Manifest.toml, I assumed it grabbed the wrong version, but everything is working. Thank you again. I'm looking forward to the new registration process, but I bet not as much as you are. Good luck and thanks for your efforts 🙌

**Pull request merged**
