### PR TITLE
Register new package Checkers.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [pkalikman/Checkers.jl](https://github.com/pkalikman/Checkers.jl)
Release: [v0.0.1](https://github.com/pkalikman/Checkers.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/pkalikman/Checkers.jl/builds/252482458)
cc: @pkalikman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@pkalikman This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by quinnj** [comment]
Great looking package! Thanks for registering! The docs look great. The JuliaCIBot failure just indicates that there's a failure on latest master (0.7-DEV), but that's not a blocker for registering this package.

**Comment by pkalikman** [comment]
Hi @quinnj; thanks. Any suggestions on how I can identify the failing tests? When I click details I just see a blank page that says

Julia Version | Test status
-- | --
0.5.2 |  
0.6.0-rc1 |  
0.7.0-dev

**Comment by tkelman** [comment]
There should be an icon you can click on to get to the log, a green checkmark for a pass or a red cross for a failure. Are you using some uncommon browser or font configuration?

**Comment by pkalikman** [comment]
@tkelman Just Chrome, but with its built-in "unsafe script" blocking active. When I disabled that the image-links loaded; thanks. (I'm guessing you'll see more people have this issue as they tend towards tighter browser security; if there's another way to serve those status links might be worth implementing.) Thanks! Best

**Pull request merged**
