### PR TITLE
Tag QNaNs.jl v0.1.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/QNaNs.jl](https://github.com/JeffreySarnoff/QNaNs.jl)
Release: [v0.1.2](https://github.com/JeffreySarnoff/QNaNs.jl/releases/tag/v0.1.2)
Travis: [Travis Build Status](https://travis-ci.org/JeffreySarnoff/QNaNs.jl/builds/194545770)
Diff: [vs v0.1.1](https://github.com/JeffreySarnoff/QNaNs.jl/compare/5e71d04e04d9045983f4dc602905fa3a4d3e6b2c...0be93bcacccde748dc64d20b06982279f298873e)
`requires` vs v0.1.1: no changes
cc: @JeffreySarnoff

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
I am not sure how to squash the changes into one when the master branch is on github.

**Comment by tkelman** [comment]
What do you mean? What are you trying to do?

**Comment by JeffreySarnoff** [comment]
my mistake -- this has only 1 commit, my question was:
if it had more than one commit -- how do I squash the multiple commits into one when the master version is on github (and locally I have Pkg.checkout(..)).

**Comment by tkelman** [comment]
Do you mean multiple metadata commits, or multiple package commits? Squashing commits on a pre-existing branch requires force-pushing over that branch, so it's a history-rewriting operation and not recommended to do on master or release branches that anyone other than you might have checked out. You can do squashing on work-in-progress temporary branches without any issues though.

**Comment by JeffreySarnoff** [comment]
ok

**Comment by tkelman** [comment]
Was `signbit` not already defined in Base for Int16, Int32, Int64?

**Comment by JeffreySarnoff** [comment]
thanks, fixed

**Pull request merged**
