### PR TITLE
Tag SurrealNumbers.jl v0.0.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [mroughan/SurrealNumbers.jl](https://github.com/mroughan/SurrealNumbers.jl)
Release: [v0.0.5](https://github.com/mroughan/SurrealNumbers.jl/releases/tag/v0.0.5)
Travis: [Travis Build Status](https://travis-ci.org/mroughan/SurrealNumbers.jl/builds/425544001)
Diff: [vs v0.0.4](https://github.com/mroughan/SurrealNumbers.jl/compare/9dcee6433533400f35b34ee88e5fdf6239942259...237f98c79b6708ab8ea2131b0d71a5a4d7c2c4fc)
`requires` vs v0.0.4: 
```diff
--- 0.0.4/requires
+++ 0.0.5/requires
@@ -1 +1 @@
-julia 0.6
+julia 0.6-
```
cc: @mroughan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Tests failed so please check the logs.

**Comment by mroughan** [comment]
Sorry about that. Thought I had checked, but may have been a step out of 
alignment. Have pushed a new version and release, and double checked.

**Comment by andreasnoack** [comment]
The error message says that you'd have to make it a minor release, i.e. 0.1.0, when changing the Julia version required. Hence, I'll close the two existing PRs.

**Comment by mroughan** [comment]
I understand now. Will do. Its about time for that anyway.

**Pull request closed without merging**
