### PR TITLE
Register ClusterUtils

### PR DESCRIPTION
**Pull request by pearcemc**
This is a package to assist with map-reduce and multiprocessing on HPC systems.

### CODE REVIEW

**Comment by tkelman** [comment]
You'll need to tag a version for anyone to be able to install it with `Pkg.add`

**Comment by tkelman** [comment]
Also a good idea to enable Travis CI and write some tests.

**Comment by kshyatt** [comment]
@pearcemc I'm bumping this as a reminder to tag a version.

**Comment by pearcemc** [comment]
I've tagged a version and pushed to my fork of METADATA, do I need to open a new pull request?

**Comment by kshyatt** [comment]
When I look at your repo, I don't see any tags. I think you need to push the tag to the ClusterUtils repo itself.

**Comment by pearcemc** [comment]
I've pushed a tagged version.

Also, do you know if Travis-CI is likely to kick up a fuss if I use `addprocs()`? As more meaningful tests would need it.

**Comment by tkelman** [comment]
Should be fine as long as you don't go too crazy. Note that the first 2 tags here, since they're missing a julia version in `REQUIRE`, are technically allowed to be installed on old releases like Julia 0.3. If that's not expected to work, then the best thing to do would be either not register those first 2 tags, or add a minimum julia version requirement to them in metadata.

**Comment by pearcemc** [comment]
@tkelman thanks for getting back to me. I wasn't clear from the Pkg docs how to accomplish this. Is it set out anywhere, or do I need to edit METADATA manually? Cheers

**Comment by tkelman** [comment]
Easiest to manually edit this branch of your metadata fork. Which do you want to do, remove those tags or add a version floor?

**Comment by pearcemc** [comment]
I'd remove the tags as they don't serve much purpose.

On Wed, May 11, 2016 at 5:33 AM, Tony Kelman <notifications@github.com>
wrote:

> Easiest to manually edit this branch of your metadata fork. Which do you
> want to do, remove those tags or add a version floor?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/METADATA.jl/pull/4989#issuecomment-218359390>
>



-- 
Matthew Pearce
T: 07881832138
@pearce_

**Comment by tkelman** [comment]
You can delete the files from the github web interface. https://github.com/pearcemc/METADATA.jl/tree/metadata-v2/ClusterUtils/versions

It'll be one commit per deleted file, but we can squash them on merge.

**Comment by pearcemc** [comment]
Thanks Tony. I deleted the relevant version folders on the command line before seeing your message and pushed to my fork, hope this works out.

**Comment by tkelman** [comment]
whoops, forgot to merge this yesterday. maybe i was waiting on travis to finish.

**Pull request merged**
