### PR TITLE
Tag Microbiome.jl v0.1.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BioJulia/Microbiome.jl](https://github.com/BioJulia/Microbiome.jl)
Release: [v0.1.2](https://github.com/BioJulia/Microbiome.jl/releases/tag/v0.1.2)
Travis: [Travis Build Status](https://travis-ci.org/BioJulia/Microbiome.jl/builds/336254892)
Diff: [vs v0.1.0](https://github.com/BioJulia/Microbiome.jl/compare/eb8947946cafeda7cad50a5d97295ba34c11ed3b...e29ae1879d9dd31f4b44a5935a4b2899618ba196)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.1.2/requires
@@ -1,6 +1,6 @@
 julia 0.6-
 RecipesBase
 Distances
-DataFrames 0.0.0 0.11.0
+DataFrames
 Clustering
 Colors
```
cc: @kescobo

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Test error should be fixed by https://github.com/JuliaLang/METADATA.jl/pull/13367. Will restart tests here when the PR has been merged.

**Comment by andreasnoack** [comment]
I didn't read the log correctly. You'll have to change the required Julia version to 0.6 instead of 0.6-.

**Comment by kescobo** [comment]
Ahh, thanks. Once I've made that fix, should I delete this tag and re-tag, or is there a better way to amend a release?

**Comment by andreasnoack** [comment]
If you delete the release and tag on GitHub and add a new with the version fixed then this PR will be updated automatically.

**Pull request merged**
