### PR TITLE
Tag LightGraphs.jl v0.9.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphs/LightGraphs.jl](https://github.com/JuliaGraphs/LightGraphs.jl)
Release: [v0.9.0](https://github.com/JuliaGraphs/LightGraphs.jl/releases/tag/v0.9.0)
Diff: [vs v0.8.0](https://github.com/JuliaGraphs/LightGraphs.jl/compare/107c2eade4907a77ce9d9c602d58ed726c578465...72ff259bd32eed646623d17905bb3d4851f19ea4)
`requires` vs v0.8.0: 
```diff
--- 0.8.0/requires
+++ 0.9.0/requires
@@ -1,9 +1,5 @@
 julia 0.6-
 GZip 0.2.20
-EzXML 0.3.0
-ParserCombinator 1.7.11
-JLD 0.6.3
-Distributions 0.10.2
 StatsBase 0.9.0
 DataStructures 0.5.0
 SimpleTraits 0.4.0
```
cc: @sbromberger

### CODE REVIEW

**Comment by tkelman** [comment]
Just a warning that some of your reverse-dependencies will most likely hit https://github.com/JuliaLang/julia/issues/21266 here. Hopefully we'll get a fully stable version of the fix ready in time to get backported for 0.5.2.

**Comment by sbromberger** [comment]
Does it matter that this version only works on 0.6?

**Comment by tkelman** [comment]
Oh, sweet, didn't see that. That does help.

**Comment by sbromberger** [comment]
Nice. Thanks for looking out.

**Pull request merged**
