### PR TITLE
Tag PkgDev.jl v0.1.7

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaLang/PkgDev.jl](https://github.com/JuliaLang/PkgDev.jl)
Release: [v0.1.7](https://github.com/JuliaLang/PkgDev.jl/releases/tag/v0.1.7)
Travis: [Travis Build Status](https://travis-ci.org/JuliaLang/PkgDev.jl/builds/367816136)
Diff: [vs v0.1.6](https://github.com/JuliaLang/PkgDev.jl/compare/62b1beb4fb246fdcba8a000f270f555297551600...1d694018324fc7f9bb01b423a663bb54e689cb2d)
`requires` vs v0.1.6: no changes
cc: @ararslan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ararslan** [comment]
JuliaCIBot seems to be hitting weird Git errors. Any idea what that's about, @aviks?

**Comment by aviks** [comment]
Yikes! c: @nkottary

**Comment by andreasnoack** [comment]
Which error are you talking about?

Note that
```julia
ERROR: LoadError: METADATA/PkgDev/versions/0.1.7/requires: oldest allowed julia version 0.5.0 too old (>= 0.6.0 needed)
```

**Comment by ararslan** [comment]
From PackageGenerator, 0.5:
> ERROR: GitError(Code:ERROR, Class:Net, SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)

0.6:
> ERROR: Cannot clone PackageGenerator from `https://github.com/bramtayl/PackageGenerator.jl.git`. No errors

**Comment by andreasnoack** [comment]
That is the reason we no longer support 0.5. It's the GitHub crypto upgrade issue described in https://discourse.julialang.org/t/errors-for-git-pkg/9351. You'll have to bump it to 0.6.

**Comment by andreasnoack** [comment]
Closing here since you'll have to use a minor version.

**Comment by ararslan** [comment]
Okay, sounds good, thanks.

**Pull request closed without merging**
