### PR TITLE
Register new package FMMTrees.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [krcools/FMMTrees.jl](https://github.com/krcools/FMMTrees.jl)
Release: [v0.1.0](https://github.com/krcools/FMMTrees.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/krcools/FMMTrees.jl/builds/492218662)
cc: @krcools

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@krcools This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use abbreviations in package names.

**Comment by krcools** [comment]
How can I fix this? Updating this PR probably doesn't work, correct?

**Comment by dpsanders** [comment]
You change the name of the repo, delete the release and the tag, and re-release.

**Comment by cortner** [comment]
Isn't FMM a widely understood term? Can it be anything other than Fast Multipole Method? For me FMM is almost as recognisable as FFT, but you won't rename FFTW.jl to FastestFourierTransformInTheWest.jl.

**Comment by krcools** [comment]
The package has been registered  now under ClusterTrees

**Pull request closed without merging**
