### PR TITLE
Pull request/ac9e2d27

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by tkelman** [comment]
You should not be calling Pkg.checkout in https://github.com/thofma/Hecke.jl/blob/master/deps/build.jl. That changes state in a different package on the user's machine in a way they didn't ask for.

**Comment by thofma** [comment]
How can I specify in the REQUIRE file that I need the master branch of a specific package?

**Comment by tkelman** [comment]
You can't. You can only depend on registered versions. Encourage the Nemo maintainer to tag a new version if you require a feature not yet available in an existing release.

**Comment by wbhart** [comment]
I tried to tag a new release, but it doesn't seem to work.

On one machine I get the following:

julia> Pkg.publish()
INFO: Validating METADATA
INFO: Pushing Nemo permanent tags: v0.4.1
Enter passphrase for key '/home/wbhart/.ssh/id_rsa':
INFO: Submitting METADATA changes
INFO: Forking JuliaLang/METADATA.jl to wbhart
INFO: Could not authenticate with existing token. Deleting token and trying again.
Enter host password for user 'wbhart':
INFO: Retrieving existing GitHub token. (You may have to re-enter your password.)
Enter host password for user 'wbhart':
ERROR: forking JuliaLang/METADATA.jl failed: Bad credentials
 in error at ./error.jl:21
 in fork at pkg/github.jl:144
 in pull_request at pkg/entry.jl:327
 in publish at pkg/entry.jl:394
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61

On my other machine I get:

julia> Pkg.publish()
ERROR: There are no METADATA changes to publish
 in publish at pkg/entry.jl:348
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61

It does seem to know about the new tag, it just doesn't know it needs to be published.

I have no idea how to resolve this at present.

**Comment by thofma** [comment]
Thanks for the effort. Looks like some git authentication problem. You could try push the changes in .julia/../METADATA to your wbhart/METADATA.jl repository without invoking julia. Then make a pull request on github. (Pkg.publish() does exactly this).

**Comment by wbhart** [comment]
I've created the pull request manually now.

Bill.

**Comment by thofma** [comment]
Thanks.

**Comment by tkelman** [comment]
Nemo 0.4.1 tag merged.

**Comment by thofma** [comment]
I updated the build.jl and tagged a new version.

**Pull request merged**
