### PR TITLE
Tag TextParse.jl v0.1.9

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaComputing/TextParse.jl](https://github.com/JuliaComputing/TextParse.jl)
Release: [v0.1.9](https://github.com/JuliaComputing/TextParse.jl/releases/tag/v0.1.9)
Travis: [Travis Build Status](https://travis-ci.org/JuliaComputing/TextParse.jl/builds/270293731)
Diff: [vs v0.1.8](https://github.com/JuliaComputing/TextParse.jl/compare/13e5fd9e224fdbbd27303f10b8b23bac704a49da...d2aaf6d793709035b8c1e7654cef0b5e973d9db9)
`requires` vs v0.1.8: 
```diff
--- 0.1.8/requires
+++ 0.1.9/requires
@@ -2,4 +2,4 @@
 Compat 0.17
 NullableArrays
 PooledArrays 0.0.2
-WeakRefStrings 0.1.0 0.3.0
+WeakRefStrings
```
cc: @shashi

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
@quinnj did TextParse need WeakRefStrings upper bounds? Was it broken by 0.3.0 or not?

**Comment by quinnj** [comment]
yes, it needs 0.3.0

**Comment by tkelman** [comment]
But https://travis-ci.org/JuliaComputing/TextParse.jl/builds/270293731?utm_source=github_status&utm_medium=notification ran since WeakRefStrings 0.3.0 was tagged, didn't have an upper bound, seems to have passed, and it doesn't look like any of the changes between TextParse 0.1.8 and 0.1.9 are related to WeakRefStrings. https://pkg.julialang.org/detail/TextParse.html also ran against 0.3.0 and had no breakage, so where were you seeing that?

**Comment by quinnj** [comment]
I guess I'd have to look more closely at how they're using it; either it was wrong or by some chance, they're not using the pieces that broke? If tests all pass and everything, then I guess maybe not?

**Comment by shashi** [comment]
https://github.com/JuliaComputing/TextParse.jl/search?utf8=%E2%9C%93&q=WeakRefString&type=

I can add the upper bounds if it's safer. I don't really use anything fancy

**Comment by tkelman** [comment]
If tests pass and the older TextParse versions can work fine against either the old or the new WeakRefStrings API's, probably best to remove the upper bounds we added to the older TextParse tags.

**Pull request merged**
