### PR TITLE
Register new package CreateMacrosFrom.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bramtayl/CreateMacrosFrom.jl](https://github.com/bramtayl/CreateMacrosFrom.jl)
Release: [v0.0.1](https://github.com/bramtayl/CreateMacrosFrom.jl/releases/tag/v0.0.1)
cc: @bramtayl

### CODE REVIEW

**Comment by ararslan** [comment]
It appears this package doesn't have any tests; the code in test/runtests.jl is actually the Documenter command to create the docs.

**Comment by bramtayl** [comment]
There's doctests

**Comment by ararslan** [comment]
Michael Hatherly, the author of Documenter, has said that doctests are intended to ensure that examples in documentation are kept up to date, not as a stand-in for unit tests.

**Comment by dpsanders** [comment]
There are also no docs so it's not possible to find out what the package actually does. So how would somebody find out whether it's of interest to them?

The name of the package with `From` at the end seems strange.

**Comment by bramtayl** [comment]
There are docs here: 

https://bramtayl.github.io/CreateMacrosFrom.jl/latest/

linked in the readme.

There is only one exported macro, @create_macros_from, so I thought it was a fitting name.

**Comment by dpsanders** [comment]
OK, there wasn't a link to the docs when I first looked.

**Comment by bramtayl** [comment]
Also, I think Michael Hatherly's issue with doctests was that they are "string based not value based." That could be a problem in some cases but I don't think it's a problem in my tests.

**Comment by MichaelHatherly** [comment]
> Also, I think Michael Hatherly's issue with doctests was that they are "string based not value based." That could be a problem in some cases but I don't think it's a problem in my tests.

Yes, probably not much of a problem with a small package like this that doesn't have much to test. The remark in https://github.com/JuliaLang/PkgDev.jl/pull/92#issuecomment-273456597 was just a general comment rather than specific to any particular package. I've expanded on it in https://github.com/JuliaLang/PkgDev.jl/pull/92#issuecomment-273699125.

**Comment by bramtayl** [comment]
Well now I have blessings from

> *Michael Hatherly, the author of Documenter*

himself!

**Comment by tkelman** [comment]
You should fill in
> No description or website provided. 

and put at least some brief description on the readme as an indication of what the package does.

**Comment by bramtayl** [comment]
Ok, I added a github description

**Pull request merged**
