### PR TITLE
Register new package CharAnalysis.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rsonthal/CharAnalysis.jl](https://github.com/rsonthal/CharAnalysis.jl)
Release: [v0.0.1](https://github.com/rsonthal/CharAnalysis.jl/releases/tag/v0.0.1)
cc: @rsonthal

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@rsonthal This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by quinnj** [comment]
@rsonthal, can you change the name of the module in `CharAnalysis.jl` file from `Bigram` to `CharAnalysis`? Otherwise, I don't think the package will work once installed for users.

**Comment by rsonthal** [comment]
Yes I will make the change!

**Comment by andreasnoack** [comment]
When you have made that change then please remove and reapply the tag. It will automatically update this PR. Also, could you please add the Travis badge to your README.md such that it is easier to check that status of the Travis tests for your package?

**Comment by rsonthal** [comment]
Thank you for the help. I will do that once I have made the change

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
