### PR TITLE
- rename Lisp to LispSyntax

### PR DESCRIPTION
**Pull request by swadey**

### CODE REVIEW

**Comment by kmsquire** [comment]
Unfortunately, deleting `Lisp.jl` will currently cause problems for anyone who has installed it, so we can't do that.

(This needs to be documented somewhere.)

**Comment by kmsquire** [comment]
(Closed so this isn't accidentally merged.)

**Comment by kmsquire** [comment]
See, e.g., https://github.com/JuliaStats/Distance.jl/issues/25, for how to do this.

**Comment by kmsquire** [comment]
See also, https://groups.google.com/d/msg/julia-users/NHeaVWMfRfo/G4C31JzWN0kJ, for a discussion of some problems when `Stats` was renamed to `StatsBase`.

(Of course, `Lisp.jl` won't have been installed by many people, and probably isn't depended on by any packages, so many of those issues might not be relevant.)

**Comment by kmsquire** [comment]
Also relevant:

* https://github.com/JuliaLang/METADATA.jl/issues/347#issuecomment-35015012
* https://github.com/JuliaLang/PkgDev.jl/issues/21

**Comment by swadey** [comment]
yeah, this was in response to jeff's request (here: #4367).  I figured it would be better to rename now rather than waiting until people install it.

**Pull request closed without merging**
