### PR TITLE
Tag Feather.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaData/Feather.jl](https://github.com/JuliaData/Feather.jl)
Release: [v0.4.0](https://github.com/JuliaData/Feather.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaData/Feather.jl/builds/417451038)
Diff: [vs v0.3.1](https://github.com/JuliaData/Feather.jl/compare/9c96901e0e09a490a94badfdc432de1302a93bac...c682c365657eb0fa09684e7c2276ebbf8894ba88)
`requires` vs v0.3.1: 
```diff
--- 0.3.1/requires
+++ 0.4.0/requires
@@ -1,6 +1,7 @@
 julia 0.6
+Arrow 0.1.1
 FlatBuffers 0.3.0
 CategoricalArrays 0.3.0
 DataFrames 0.11.0
 DataStreams 0.3.0
-WeakRefStrings 0.4.0
+Compat 0.63.0
```
cc: @ExpandingMan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by vchuravy** [comment]
@ExpandingMan AppVeyor is consistently failing https://ci.appveyor.com/project/quinnj/feather-jl-xxi09/build/1.0.44/job/vp7iwkpr9fawk2qf

**Comment by ExpandingMan** [comment]
This appears to be a bug in `DataFrames` in which it makes an improper type assertion on 32-bit machines [here](https://github.com/JuliaData/DataFrames.jl/blob/v0.11.7/src/dataframe/dataframe.jl#L228).  I think the proper solution is a `DataFrames` patch.  Will consult.

**Comment by ExpandingMan** [comment]
Ok, there is still the problem on 32-bit Windows which I think is being caused by DataFrames.  Most of the tests are passing on 64-bit windows, but it ends in some sort of IO error.

I simply don't have the ability to maintain this on Windows.  @quinnj , do you have an opinion on this?  Had the appveyor tests been passing?  Unfortunately if we want this to consistently pass on Windows, that would be up to you as I don't have a windows environment in which to do any development.

**Comment by quinnj** [comment]
I've tagged a new DataFrames release w/ the fix; so once that gets merged in METADATA, let's kick off the Feather tests again.

**Comment by ExpandingMan** [comment]
Sounds good, but note that there is another failure on 0.7 and 1.0 in windows that I don't know how to fix.

**Comment by quinnj** [comment]
@ExpandingMan, the latest failure (https://ci.appveyor.com/project/quinnj/feather-jl-xxi09/build/1.0.47/job/j824mmjnaoo2x25j) seems like a Arrow.jl bug for 32-bit dealing w/ pointers & alignment. On 64-bit, it looks like there's just a "delete file" operation that isn't working. For windows, you have to completely gc the file handle before trying to `rm` it, which often comes up when mmapping. There's probably a place where we generate a feather file, open it up to test, then try to `rm`, and we just need to do `file = nothing; GC.gc(); GC.gc()` to ensure that `file` is totally closed before trying to `rm`.

**Comment by ExpandingMan** [comment]
The 64-bit finally passes, but I have absolutely no idea what is causing the alignment problem on 32-bit.  Thing is, it's actually having that problem on arrays of 8-byte objects, so I don't see how it could possibly throw such an error, it's almost as if they array were being created in a misaligned location (that's not possible is it?).  Any ideas?  I'm not sure how I'd even troubleshoot this.

**Pull request merged**
