### PR TITLE
Tag Permutations.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [scheinerman/Permutations.jl](https://github.com/scheinerman/Permutations.jl)
Release: [v0.1.0](https://github.com/scheinerman/Permutations.jl/releases/tag/v0.1.0)
Diff: [vs v0.0.1](https://github.com/scheinerman/Permutations.jl/compare/f937a0f9d2c90a6243e9ab69db877b066bfba55a...e58f98be0ee63118f27bc191defed9c360a381ff)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.1.0/requires
@@ -0,0 +1 @@
+julia 0.5
```
cc: @scheinerman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by bramtayl** [comment]
Tada!

**Comment by rdeits** [comment]
@scheinerman I think you'll need to update this release so that it includes the `Combinatorics.jl` dependency. Since you've already fixed your `REQUIRE` file, you just need to follow the instructions here: https://github.com/attobot/attobot#updatingdeleting-a-release

(sorry for not adding Combinatorics in my original PR)

**Comment by scheinerman** [comment]
Thanks. I think I have it fixed.

On Aug 25, 2017, at 12:36, Robin Deits <notifications@github.com<mailto:notifications@github.com>> wrote:


@scheinerman<https://github.com/scheinerman> I think you'll need to update this release so that it includes the Combinatorics.jl dependency. Since you've already fixed your REQUIRE file, you just need to follow the instructions here: https://github.com/attobot/attobot#updatingdeleting-a-release

(sorry for not adding Combinatorics in my original PR)

**Comment by tkelman** [comment]
closing this in favor of https://github.com/JuliaLang/METADATA.jl/pull/10919

**Pull request closed without merging**
