### PR TITLE
Tag MultiJuMP.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [anriseth/MultiJuMP.jl](https://github.com/anriseth/MultiJuMP.jl)
Release: [v0.4.0](https://github.com/anriseth/MultiJuMP.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/anriseth/MultiJuMP.jl/builds/479068506)
Diff: [vs v0.3.0](https://github.com/anriseth/MultiJuMP.jl/compare/f5f65e7ed815a872f0fa2e93c4ace42a257c1273...5c19b523d6d38fc3e99968b2c7202d051a68058f)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -1,6 +1,6 @@
 julia 0.7
 JuMP 0.18
-Combinatorics
-RecipesBase
-LaTeXStrings
-MathProgBase
+Combinatorics 0.7
+RecipesBase 0.6
+LaTeXStrings 1.0
+MathProgBase 0.7
```
cc: @matbesancon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by martinholters** [comment]
```
ERROR: LoadError: LoadError: Tagged version 0.4.0 of MultiJuMP lists version 0.1.1 in its Project file.
The versions must match.
```

**Comment by matbesancon** [comment]
woops, gonna fix that

**Comment by matbesancon** [comment]
I don't think releases can be edited, I just tagged v0.4.1 fixing the issue. Should this PR be closed?

**Comment by martinholters** [comment]
I think you can use git to push an updated tag which will result in an updated release, but just tagging  the patch release is also ok.

**Pull request closed without merging**
