### PR TITLE
Tag Compat v0.8.5

### PR DESCRIPTION
**Pull request by spencerlyon2**
cc @tkelman 

Ref https://github.com/JuliaLang/Compat.jl/pull/245

### CODE REVIEW

**Comment by tkelman** [comment]
be sure to push the git tag to https://github.com/JuliaLang/Compat.jl/releases

**Comment by spencerlyon2** [comment]
Ahh sorry, I don't think have commit access over there.

**Comment by tkelman** [comment]
Strange. You do now.

**Comment by spencerlyon2** [comment]
Ok thanks -- pushed the tag

**Pull request merged**
