### PR TITLE
Tag BasisMatrices.jl v0.3.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [QuantEcon/BasisMatrices.jl](https://github.com/QuantEcon/BasisMatrices.jl)
Release: [v0.3.2](https://github.com/QuantEcon/BasisMatrices.jl/releases/tag/v0.3.2)
Travis: [Travis Build Status](https://travis-ci.org/QuantEcon/BasisMatrices.jl/builds/244795358)
Diff: [vs v0.3.1](https://github.com/QuantEcon/BasisMatrices.jl/compare/33326fc195c5b3b14f6b5cb9d9062fe955752bae...5d3b2219b41bf99b563e5f17dbaaa71c6b11feba)
`requires` vs v0.3.1: no changes
cc: @sglyon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by sglyon** [comment]
Fixed so now we specifically run on 0.6 with travis instead of just 0.5 and nightly

**Comment by tkelman** [comment]
Are the failures in https://travis-ci.org/QuantEcon/BasisMatrices.jl/builds/244796691 expected?

**Comment by sglyon** [comment]
No -- totally a mistake. Sorry for the noise. 

I guess this isn't quite ready.

**Comment by sglyon** [comment]
Hey @tkelman -- I fixed the bug in the package and tests should pass now. This is ready to merge once travis reports success on the tag.

**Pull request merged**
