### PR TITLE
Pull request/2e6aa657

### PR DESCRIPTION
**Pull request by wolfiex**
Added Reload.jl

### CODE REVIEW

**Comment by KristofferC** [comment]
Have you seen https://github.com/timholy/Revise.jl? It seems you package does exactly what `Revise.track(file)` does?

**Comment by wolfiex** [comment]
Thanks, I though there must be something similar!

 Having just tried it Revise does update variables correctly, however it does not tell you if you have introduced an error in your code (and thus fails to update the data when this happens). 

Additionally it does not seem to rerun print commands when needed.  The idea of this was to help with constantly having to click on the interpreter window to see a variable result, whilst still being able to play with the data when needed (you know RSI and all). 

I guess i should postpone the pull request and see if i can adapt the code form Revise to suit my needs.

**Comment by KristofferC** [comment]
Note that including a file at arbitrary times is quite dangerous. What if the user is in process of writing `rm("somefile...")` and the include fires before the filename is complete? Then you could delete a file that was not intended to be deleted.

**Comment by aviks** [comment]
Closing this PR (to prevent slipped fingers). Please let us know if you need this reopened.

**Pull request closed without merging**
