### PR TITLE
Register new package AMA.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [gtunell/AMA.jl](https://github.com/gtunell/AMA.jl)
Release: [v0.0.1](https://github.com/gtunell/AMA.jl/releases/tag/v0.0.1)
cc: @gtunell

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@gtunell This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by simonbyrne** [comment]
We generally discourage acronyms unless they are fairly universal, see https://docs.julialang.org/en/v0.6.4/manual/packages/#Guidelines-for-naming-a-package-1

Maybe AndersonMoore.jl?

**Comment by simonbyrne** [comment]
Also, which fork are you registering?

**Comment by gtunell** [comment]
I released under my account initially but Gary will be taking over in the near future. We would like to register under es335mathwiz.

**Comment by es335mathwiz** [comment]
We have deleted the earlier fork.  We'd like to use the remaining fork at commit f7fd241.  I was worried about using the first as my colleague will be leaving the project soon.  Also using the name AndersonMoore.jl should be fine.

**Comment by es335mathwiz** [comment]
Will we need to or should we change our repository name at github in order to use the AndersonMoore.jl  name?

**Comment by simonbyrne** [comment]
Yes, you will need to change the name of the repository, rename the main file (`src/AMA.jl` should become `src/AndersonMoore.jl`) and rename any references (e.g. `module AMA` to `module AndersonMoore`, and look in the tests and the CI config files as well).

**Comment by es335mathwiz** [comment]
Sounds great, but just to make sure I understand.  We should reconfigure the repository as you describe and then make a new pull request from a new commit that reflects those changes.

**Comment by simonbyrne** [comment]
Yes: just delete the old release (see [here](https://github.com/attobot/attobot)), and create a new one. That should trigger a new pull request here.

**Pull request closed without merging**
