### PR TITLE
Register new package FCS.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [tlnagy/FCS.jl](https://github.com/tlnagy/FCS.jl)
Release: [v0.0.1](https://github.com/tlnagy/FCS.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/tlnagy/FCS.jl/builds/303310626)
cc: @tlnagy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@tlnagy This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tlnagy** [comment]
I didn't realize that I broke 0.5 compat with this update. Please close this and I'll retag and release the package.

**Comment by aviks** [comment]
We generally tend to dislike acronyms as package name (with only a few exceptions). Is there a chance you could rename the package to be more descriptive?

**Comment by aviks** [comment]
Bump.. thoughts?

**Comment by tlnagy** [comment]
Please close in favor of https://github.com/JuliaLang/METADATA.jl/pull/12251

**Pull request closed without merging**
