### PR TITLE
Tag CxxWrap.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaInterop/CxxWrap.jl](https://github.com/JuliaInterop/CxxWrap.jl)
Release: [v0.8.0](https://github.com/JuliaInterop/CxxWrap.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaInterop/CxxWrap.jl/builds/441090348)
Diff: [vs v0.7.4](https://github.com/JuliaInterop/CxxWrap.jl/compare/7afcb4431d9ef4f45c061425e5d6d28a0d55baf1...d3fd4ce0fe8e360f47504086e769d446acc568b6)
`requires` vs v0.7.4: 
```diff
--- 0.7.4/requires
+++ 0.8.0/requires
@@ -1,2 +1,2 @@
-julia 0.7.0-beta
-BinaryProvider 0.4 0.5
+julia 1.0
+BinaryProvider 0.5 0.6
```
cc: @barche

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by barche** [comment]
The JuliaCIBot error is:
```
/opt/julia-1.0.0/bin/julia: symbol lookup error: /home/jrun/LCIO/.julia/packages/LCIO/epGT5/deps/usr/lib/liblciowrap.so: undefined symbol: get_any_type
```

This function is removed in this release, so the problem should be easily fixed by just rebuilding the LCIO wrapper library. It would also be safest te set an upper bound for CxxWrap to the next 0.x version.

CC @jstrube

**Comment by jstrube** [comment]
LCIO is a bit of a mess right now...
It depends on Zlib, which doesn't have a binary that's compatible with cxx14, which is needed for libxccwrap...
Trying to find a workaround for this dependency hell...

**Comment by andreasnoack** [comment]
I'll merge. @jstrube Please add upper bounds to LCIO if necessary.

**Comment by jstrube** [comment]
Will start adding with the next release. Thanks.

**Pull request merged**
