### PR TITLE
Tag ArbFloats.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArbTypes/ArbFloats.jl](https://github.com/JuliaArbTypes/ArbFloats.jl)
Release: [v0.2.0](https://github.com/JuliaArbTypes/ArbFloats.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArbTypes/ArbFloats.jl/builds/259692370)
Diff: [vs v0.1.17](https://github.com/JuliaArbTypes/ArbFloats.jl/compare/8e24be91f923aa6087fbee34e47e4b4905b0dbda...beea7f7f61c1ea3d2f63b7fd68af7d0f174e5013)
`requires` vs v0.1.17: 
```diff
--- 0.1.17/requires
+++ 0.2.0/requires
@@ -1,5 +1,5 @@
-julia 0.5.0
+julia 0.6.0
 BinDeps 0.4.5
 Compat 0.9.5
 Nemo 0.6.0
-ReadableNumbers 0.0.3
+ReadableNumbers 0.0.4
```
cc: @JeffreySarnoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
I do not see the problem.

**Comment by tkelman** [comment]
seems it can't find one of your test files? odd

**Comment by JeffreySarnoff** [comment]
thanks -- that is it, I fixed that (though I have no idea how it got wrong .. and that is worrisome).

**Comment by JeffreySarnoff** [comment]
admin: I have no idea what JuliaCIBot wants.

**Pull request merged**
