### PR TITLE
Tag VT100.jl v0.0.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Keno/VT100.jl](https://github.com/Keno/VT100.jl)
Release: [v0.0.3](https://github.com/Keno/VT100.jl/releases/tag/v0.0.3)
Travis: [Travis Build Status](https://travis-ci.org/Keno/VT100.jl/builds/201637243)
Diff: [vs v0.0.2](https://github.com/Keno/VT100.jl/compare/f7a02f318e70343671e901fc248e834f11610b47...f68a69d21ddb15bdf208065650264b026089e5d1)
`requires` vs v0.0.2: 
```diff
--- 0.0.2/requires
+++ 0.0.3/requires
@@ -1,4 +1,4 @@
-julia 0.4
-Colors
-Compat 0.7.15
-FixedPointNumbers
+julia 0.5
+ColorTypes 0.3.4
+Compat 0.17.0
+FixedPointNumbers 0.3.0
```
cc: @Keno

### CODE REVIEW

**Comment by Keno** [comment]
I guess I dropped 0.4 support. Will retag as 0.1

**Comment by Keno** [comment]
@simonbyrne Will attobot pick up that I edited the release?

**Comment by Keno** [comment]
Doesn't matter, I'll fix up with PR manually.

**Comment by Keno** [comment]
@simonbyrne Does attobot not allow maintainer edits :/? Oh well, a new PR it is.

**Comment by tkelman** [comment]
the branch name that attobot creates is specific to a given version number

**Pull request closed without merging**
