### PR TITLE
Tag Turing.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [yebai/Turing.jl](https://github.com/yebai/Turing.jl)
Release: [v0.2.0](https://github.com/yebai/Turing.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/yebai/Turing.jl/builds/224386810)
Diff: [vs v0.1.0](https://github.com/yebai/Turing.jl/compare/0fe926e429176f2417ac37d749358c24d69c4442...94581c7cef5b0f1471a71948d284b6f25a478c1d)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,4 +1,8 @@
 julia 0.5
+
 Distributions 0.11.0
 PDMats 0.5.1
 ForwardDiff
+Mamba
+Stats
+ProgressMeter
```
cc: @yebai

### CODE REVIEW

**Comment by tkelman** [comment]
> Any code that has been copied from other projects (e.g. ASCIIPlots) needs to follow the terms of those projects' licenses.

This is not being done yet. See the text of the MIT license, https://github.com/johnmyleswhite/ASCIIPlots.jl/blob/master/LICENSE.md specifically

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by yebai** [comment]
We've removed the ASCIIPlot code and add a dependence on it in the main repo. This PR has been opened on the wrong commit. We're still experimenting with `attobot`..

**Comment by tkelman** [comment]
Ah okay I see https://github.com/yebai/Turing.jl/pull/190 now. It is usually recommended to tag commits from master (or a permanent release branch, if you do separate bugfix backports).

**Comment by tkelman** [comment]
Looks like there's also code adapted from Mamba that should acknowledge its license.

**Pull request merged**
