### PR TITLE
Tag ElectronDisplay.jl v0.7.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [queryverse/ElectronDisplay.jl](https://github.com/queryverse/ElectronDisplay.jl)
Release: [v0.7.0](https://github.com/queryverse/ElectronDisplay.jl/releases/tag/v0.7.0)
Travis: [Travis Build Status](https://travis-ci.org/queryverse/ElectronDisplay.jl/builds/491337441)
Diff: [vs v0.6.0](https://github.com/queryverse/ElectronDisplay.jl/compare/4b086f2639090c23e802930944f2f8d27eb26b9c...27340d5ebca4b4825b8019182a9d92998d68ea49)
`requires` vs v0.6.0: 
```diff
--- 0.6.0/requires
+++ 0.7.0/requires
@@ -1,2 +1,5 @@
 julia 0.7
 Electron 0.2.0
+TableTraits 0.4.1
+TableShowUtils 0.2.3
+IteratorInterfaceExtensions 0.1.1
```
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by davidanthoff** [comment]
It seems that this tag doesn't show up over in https://github.com/JuliaRegistries/General/blob/master/E/ElectronDisplay/Versions.toml, even though the migration script has run in the meantime.

I'm not even sure whom to ping, so I'm just going to ping the two folks under who's names the automatic scripts seem to run: @StefanKarpinski and @andreasnoack.

**Comment by StefanKarpinski** [comment]
I’ve been made aware that something is wrong but haven’t had a chance to investigate. Will do so tonight or tomorrow morning.

**Comment by davidanthoff** [comment]
Great, thanks!

**Comment by StefanKarpinski** [comment]
See https://github.com/JuliaRegistries/General/issues/29.

**Comment by davidanthoff** [comment]
Great, thanks!

**Pull request merged**
