### PR TITLE
Register new package Geodesics.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [anowacki/Geodesics.jl](https://github.com/anowacki/Geodesics.jl)
Release: [v0.2.0](https://github.com/anowacki/Geodesics.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/anowacki/Geodesics.jl/builds/466010879)
cc: @anowacki

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@anowacki This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
The package name seems too general for the specific application. A more specific package name would seem more appropriate.

**Comment by anowacki** [comment]
I was asked to register the package and would be prepared to consider other names if people feel strongly on this.

(The word after all comes from 'geodesy', meaning the measurement of the Earth.  'Geodetic' is now used for the adjective relating to geodesy, leaving 'geodesics' to mean a narrow aspect of this—shortest paths thereon.  I wasn't aware of it subsequently being taken up in other fields for the generalised version of this.)

**Comment by dpsanders** [comment]
Exactly, I was expecting a package for calculating geodesics on general surfaces, which is why I suggested that a more specific name would be appropriate.

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
