### PR TITLE
Bugfix release for Feather

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by tkelman** [comment]
This is going to interact poorly with precompilation. Can you make the dependency unconditional until the NullableArrays version of DataFrames is released and you can depend on it?

**Comment by quinnj** [comment]
Huh? What dependency are you referring to exactly?

**Comment by tkelman** [comment]
DataArrays

**Comment by quinnj** [comment]
Feather actually isn't precompiled, so it should be ok, right?

**Comment by tkelman** [comment]
If you mark it with `__precompile__(false)` so no one tries to import it in their own packages that are precompiled, then sure. DataArrays is pure Julia right? So just adding it to REQUIRE until the rewritten DataFrames is ready doesn't seem like it would be that problematic?

**Comment by quinnj** [comment]
Ok, updated with an explicit requirement for DataArrays.

**Comment by tkelman** [comment]
Not in https://github.com/quinnj/METADATA.jl/blob/16dea3f44b6e28ea4cbd49e59658db1d93b7f860/Feather/versions/0.2.1/requires - you should really be using PkgDev if it works at all, have you at least tried using `PkgDev.tag` then manually pushing, if publish isn't working?

**Comment by quinnj** [comment]
Just re-pushed. Does PkgDev have functionality to delete tags and retag? It seems like a situation where I'd need to do things manually anyway.

**Comment by tkelman** [comment]
No one has implemented PkgDev.untag yet (the issue has been opened at least 3 times by now), it's the manual creation of tags I'd like to discourage.

**Pull request merged**
