### PR TITLE
Tag LPVSpectral.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [baggepinnen/LPVSpectral.jl](https://github.com/baggepinnen/LPVSpectral.jl)
Release: [v0.1.0](https://github.com/baggepinnen/LPVSpectral.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/baggepinnen/LPVSpectral.jl/builds/396055795)
Diff: [vs v0.0.4](https://github.com/baggepinnen/LPVSpectral.jl/compare/3a2d546564db5d2e34c87cffa3a6b36f050dfc1e...4eb7fee3688b75a45bc6c8fbd3f498f32b50014f)
`requires` vs v0.0.4: 
```diff
--- 0.0.4/requires
+++ 0.1.0/requires
@@ -1,3 +1,5 @@
-julia 0.5
+julia 0.7-alpha
 Plots
 DSP
+RecipesBase 0.2.3
+ProximalOperators
```
cc: @baggepinnen

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by baggepinnen** [comment]
Yes, there is some issue with building `Plots.jl`. I can't seem to figure out how to specify that travis should use julia0.7 branch in the Plots repo :/

**Comment by andreasnoack** [comment]
>  I can't seem to figure out how to specify that travis should use julia0.7 branch in the Plots repo :/

Ideally, you should only make a 0.7 release of your package when all your dependencies are ready for it.

**Comment by dpsanders** [comment]
It is unclear (even from the README) what LPV is / means / refers to. 
Maybe the acronym could be spelled out in the package name?

**Comment by baggepinnen** [comment]
I agree that the name is slightly unfortunate, but I deemed `LinearParameterVaryingSpectralEstimation.jl` to be too long. LPV is a well used abbreviation in its field, so someone looking for an LPV spectral estimation method will find it, and it's referenced in the article describing the method so I would like to keep the url intact.

**Comment by andreasnoack** [comment]
Closing because of no activity for a month.

**Pull request closed without merging**
