### PR TITLE
Register new package OnlineStatsBase.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [joshday/OnlineStatsBase.jl](https://github.com/joshday/OnlineStatsBase.jl)
Release: [v0.0.1](https://github.com/joshday/OnlineStatsBase.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/joshday/OnlineStatsBase.jl/builds/246677669)
cc: @joshday

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@joshday This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
@shashi 

> This PR will remain open for 24 hours for feedback

**Comment by shashi** [comment]
> (which is optional)

**Comment by tkelman** [comment]
The feedback is optional. Not the 24 hours.

**Comment by shashi** [comment]
Ah okay! Well.

**Pull request merged**
