### PR TITLE
Tag NLPModels.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaSmoothOptimizers/NLPModels.jl](https://github.com/JuliaSmoothOptimizers/NLPModels.jl)
Release: [v0.5.0](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/releases/tag/v0.5.0)
Diff: [vs v0.4.3](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/compare/b0e2a2975577e1ca0b70e80bddbc04a1dd554a32...27d948f714b9443d161e7afb21fb61e9c9d1cf19)
`requires` vs v0.4.3: 
```diff
--- 0.4.3/requires
+++ 0.5.0/requires
@@ -1,2 +1,3 @@
 julia 0.6
 LinearOperators 0.4.0
+ForwardDiff 0.6.0
```
cc: @abelsiqueira

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider adding an upper bound if Julia 1.0 isn't supported yet.

**Comment by abelsiqueira** [comment]
Yes, sure. I delete the tag and create another for the new commit, right?

**Comment by andreasnoack** [comment]
Yes. That is the way to do it. See also https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by abelsiqueira** [comment]
This is updated now.

**Comment by dpo** [comment]
Just wondering why the JuliaCIBot isn't kicking in.

**Comment by andreasnoack** [comment]
It should work now. Sorry for the delay here.

**Comment by andreasnoack** [comment]
It looks like this breaks AmplNLReader on Julia 0.6

**Comment by abelsiqueira** [comment]
`AmplNLReader` is currently not passing on 0.6, and after some [investigation and discussion](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/pull/48), we decided to leave it not passing. On 0.7 it seems to work, so we'll drop 0.6 support for `AmplNLReader`.

Can we merge this without `AmplNLReader` passing? Even if we make a release for `AmplNLReader` limiting `NLPModels` it won't pass.
Also, we need `NLPModels` on 0.7 to update `AmplNLReader` to 0.7.

**Comment by andreasnoack** [comment]
Then the best thing to do is first to add upper bounds at `0.5` on NLPModels for all published versions of AmplNLReader. See https://github.com/JuliaLang/METADATA.jl/pull/17104/files. That should avoid breaking anything on 0.6.

**Comment by abelsiqueira** [comment]
AmplNLReader PR: #18099

**Pull request merged**
