### PR TITLE
Tag SingularIntegralEquations v0.1.6 [https://github.com/ApproxFun/Si…

### PR DESCRIPTION
**Pull request by dlfivefifty**
…ngularIntegralEquations.jl]

Updated for ApproxFun v0.4.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
You need to change this to a minor tag since it drops support for Julia v0.4

**Comment by dlfivefifty** [comment]
What's the easiest way to retag?  I usually

1.  Delete the tag in github
2.  Delete .julia/v0.5 to reset METADATA
3. Pkg.checkout and PkgDev.tag

This is a bit tedious though.

**Comment by ChrisRackauckas** [comment]
You can just:

1. Delete the tag locally. [Push the deleted tag change.](https://www.abeautifulsite.net/how-to-delete-a-tag-on-github)
2. Go to the branch for this PR. Delete the v0.1.6 folder in your package folder. Commit the change.
3. Tag minor, push tag.
4. Close then re-open this PR to restart Travis.

**Comment by dlfivefifty** [comment]
I did steps 1-3.  It looks like travis restarted automatically.  Should I still close and reopen?

**Comment by ChrisRackauckas** [comment]
>I did steps 1-3. It looks like travis restarted automatically. Should I still close and reopen?

Nah you're good (see the edit). I forgot commits will restart. (If you forget to push a tag, then you push the tag to your repo and just open/close to restart travis.)

**Pull request merged**
