### PR TITLE
Tag MarketData v0.3.7

### PR DESCRIPTION
**Pull request by milktrader**

### CODE REVIEW

**Comment by milktrader** [comment]
I fixed the travis error, how do I fix this PR?

**Comment by tkelman** [comment]
Looks like it's saying you should have used a new minor version?

**Comment by milktrader** [comment]
Will the test only fail if the last tag fails? (i.e., a new tag will submit two tagged versions to METADATA if I understand correctly)

If I document this tag version as a mistake and tag a new one with the fix, will METADATA stop when it sees this tag version is failing?

**Comment by tkelman** [comment]
I think this minor version check should only look at the minor version series of the newest tag for any given package.

**Comment by milktrader** [comment]
Ok, lets give it a try ...

The issue here btw is requiring a dependency for a package version that conflicts with its bounds.

**Pull request closed without merging**
