### PR TITLE
UMOL v0.0.1

### PR DESCRIPTION
**Pull request by yuhangwang**
v0.0.1

### CODE REVIEW

**Comment by tkelman** [comment]
This is a completely empty package. https://github.com/UMOL/UMOL.jl/blob/master/src/UMOL.jl What is the intended purpose supposed to be?

**Comment by yuhangwang** [comment]
UMOL v0.0.3

**Comment by yuhangwang** [comment]
Hi Tony (tkelman),

UMOL is designed to be a package for molecular data processing. Right now I am just registering for a place in the Julia package catalog. The code will be committed later.

**Comment by yuhangwang** [comment]
The package is empty right just to make it easier to debug the julia package publishing process.

**Comment by tkelman** [comment]
We generally encourage development into a working package before registering. And see the package naming guidelines: http://docs.julialang.org/en/release-0.4/manual/packages/#guidelines-for-naming-a-package - specifically, acronym names are discouraged if something more descriptive can be used instead.

**Comment by yuhangwang** [comment]
Thank you for forwarding the naming guidelines. "UMOL" is planned to be have multiple versions written in different languages. The Julia version will eventually become a wrapper for the base library written in C. The name "UMOL" is following Julia package naming guideline #6.

**Comment by tkelman** [comment]
Registering a package that doesn't do anything yet just to save a spot and occupy a name is not something that has been done yet intentionally, AFAIK. I'd be happy to accept this once you have some bare minimun nonzero amount of functionality in the package and push a new tag for that.

**Comment by yuhangwang** [comment]
Ok. I will close this pull request for now and open another one once I have added my code. Thanks.

**Pull request closed without merging**
