### PR TITLE
Register Plotly

### PR DESCRIPTION
**Pull request by bpostlethwaite**

### CODE REVIEW

**Comment by milktrader** [comment]
Julia packages are named with a `.jl` extension, so this would best be renamed as Plotly.jl

**Comment by milktrader** [comment]
Once that's done, a version has to be tagged so users can add the package with the `Package.add()` method. To do this:

````julia
julia> Pkg.update()
# get some update info here
julia> Pkg.tag("Plotly", :patch)  # this will start versioning at 0.0.1
````

**Comment by bpostlethwaite** [comment]
okay, repo name has changed to Plotly.jl and I have added a tag.

**Comment by milktrader** [comment]
Great, now we just need to update the PR. It still shows the old url and no tags.

**Comment by ViralBShah** [comment]
It's exciting to have a plotly interface.

**Comment by bpostlethwaite** [comment]
Okay I think I made a mess of this PR. I attempted to put control of the METADATA fork under the Plotly organization and got confused what Pkg.publish() was doing under the hood. I think I will make the PRs manually from now on.

The new PR is at: JuliaLang/METADATA.jl/pull/2054

**Pull request closed without merging**
