### PR TITLE
Tag TrafficAssignment.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [chkwon/TrafficAssignment.jl](https://github.com/chkwon/TrafficAssignment.jl)
Release: [v0.5.0](https://github.com/chkwon/TrafficAssignment.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/chkwon/TrafficAssignment.jl/builds/414484688)
Diff: [vs v0.4.1](https://github.com/chkwon/TrafficAssignment.jl/compare/f58385b5c53cd3e52c6617c0cdcf4c1f254809e5...68d17d118b3400f86ad1796ee98ffc6dd056f8de)
`requires` vs v0.4.1: 
```diff
--- 0.4.1/requires
+++ 0.5.0/requires
@@ -1,4 +1,4 @@
-julia 0.6.0-pre
+julia 0.7
 LightGraphs 0.8
 Optim 0.7
-BinDeps
+BinDeps 0.8
```
cc: @chkwon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Is it on purpose that you allow failures on 1.0?

**Comment by chkwon** [comment]
Yes.  This package rely on some other packages that are not quite 1.0 ready yet.

**Comment by andreasnoack** [comment]
Are you sure you'd like to release a new version before these issues have been fixed? Please also notice that you have some warnings left caused by your own package, https://travis-ci.org/chkwon/TrafficAssignment.jl/jobs/414484689#L1099-L1100, so they will cause failure on 1.0 even when Optim has been fixed for 1.0.

**Comment by chkwon** [comment]
Those particular issues are also from Optim.  I expect my package will go through well as soon as Optim is updated.  If you want me to wait, no problem. No rush.

```julia
WARNING: importing deprecated binding Base.STDOUT into Optim.
WARNING: Base.STDOUT is deprecated, use stdout instead.
  likely near /home/travis/build/chkwon/TrafficAssignment.jl/test/runtests.jl:16
in update! at /home/travis/.julia/packages/Optim/5JqO8/src/utilities/update.jl
```

**Comment by andreasnoack** [comment]
If it isn't urgent then I'll recommend waiting until the dependencies are ready and then adjust the versions in `REQUIRE` before release.

**Comment by chkwon** [comment]
No problem. I'll submit an updated PR later. You may close this PR.

**Comment by andreasnoack** [comment]
We can just keep this one open such that this discussion is easy to find. Once the dependencies are ready, you can update your REQUIRE file, delete this tag and reapply the same tag on the new commit. Then this PR will be updated automatically.

**Comment by chkwon** [comment]
What's going on here?  JuliaCIBot check is still pending...

**Comment by andreasnoack** [comment]
CIBot isn't realiable for the time being. I hadn't noticed that you'd updated the PR. Another time, it would be great if you could leave a comment that the PR is ready.

**Comment by chkwon** [comment]
Thanks!  I wanted to let you know when all checks have passed.  :)

**Pull request merged**
