### PR TITLE
Tag Clustering v0.7.0 [https://github.com/JuliaStats/Clustering.jl]

### PR DESCRIPTION
**Pull request by ararslan**
Fixes https://github.com/JuliaStats/Clustering.jl/issues/76

### CODE REVIEW

**Comment by tkelman** [comment]
https://github.com/JuliaStats/Clustering.jl/pull/65 is kind of a feature, isn't it?

**Comment by ararslan** [comment]
Whoopies.

**Comment by tkelman** [comment]
Restarted Travis, the tag check functioned as intended.

**Comment by ararslan** [comment]
Hey, what do you know, the code failed appropriately this time. I had forgotten to push the remote tag. Said tag has now been pushed.

**Comment by tkelman** [comment]
Maybe we should suggest "close then reopen the pull request to get travis to restart after pushing the tags" ? Hopefully people won't end up triggering excessively many builds that way.

**Comment by ararslan** [comment]
> If your build fails, be sure to ping @tkelman several times in a row to ensure your build gets restarted in a timely manner

:trollface:

Yeah that sounds like a good suggestion. I can't imagine people would just spam open and close since it's pretty easy to verify that the tags have indeed been pushed after the first time the check says they haven't been.

**Pull request merged**
