### PR TITLE
Tag DiffEqBase.jl v1.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DiffEqBase.jl](https://github.com/JuliaDiffEq/DiffEqBase.jl)
Release: [v1.6.0](https://github.com/JuliaDiffEq/DiffEqBase.jl/releases/tag/v1.6.0)
Diff: [vs v1.5.1](https://github.com/JuliaDiffEq/DiffEqBase.jl/compare/dcfc2a38b2eca7e75726ce8346ef21471c9c59d2...249114216a1f0a5e470cdc0579761f3b19090642)
`requires` vs v1.5.1: no changes
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should not be merged until after https://github.com/JuliaLang/METADATA.jl/pull/9293

**Comment by tkelman** [comment]
only 4 reverse dependencies? seems like there should be more than that

**Comment by ChrisRackauckas** [comment]
```julia
length(Pkg.dependents("DiffEqBase"))
29
```

**Comment by tkelman** [comment]
@nkottary any ideas why http://juliarun-ci.s3.amazonaws.com/d0bba038e7fec8b5577018a3d65592c0e81daafb/DiffEqBase_reverse_dependency_tests.html is so short? maybe most of the others are upper bounded so they couldn't install this new version?

**Comment by ChrisRackauckas** [comment]
>maybe most of the others are upper bounded so they couldn't install this new version?

DiffEqMonteCarlo has the only upper bound on this, and it's a leaf package only depended on by DifferentialEquations.

**Comment by nkottary** [comment]
@tkelman I had set a limit for the number of tests. I will increase it now.

**Comment by tkelman** [comment]
ah okay, makes sense!

**Pull request merged**
