### PR TITLE
First wave for finally registering all new packages for GLVisualize

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by IainNZ** [comment]
Whats the difference between ColorTypes and Colors?

**Comment by IainNZ** [comment]
(also, is really worth registering packages when they look so new? Will other packages use them?)

**Comment by SimonDanisch** [comment]
I'm using them for GLPlot and GLVisualize.
ColorTypes is really lightweight and uses FixedSizeArrays for arithmetic
and convenience constructors. Which makes it a lot faster to load, and a
lot easier to treat them inside GLAbstraction ( setting up OpenGL buffers
for a lot of different types is really troubling. Giving them all the same
interface via FixedSizeArrays made my code a lot cleaner)
Also, things become more consistent for the user, as Points, Vectors and
Colors work all similarly. (e.g. Vector3(1) --> Vector3(1,1,1), RGB(1) -->
RGB(1,1,1))
I Hope that Color will use ColorTypes at some point. But so far I didn't
have time to rewrite it and create a PR and no one else had the time ;)
GeometryTypes is already used by quite a few people and will soon be the
foundation for JuliaGeometry. It's basically the successor of
ImmutableArrays and will soon allow for types like Point{T,3}, when I
integrate the tuple changes into FixedSizeArrays.

2015-06-08 0:49 GMT+02:00 Iain Dunning <notifications@github.com>:

**Comment by IainNZ** [comment]
I think I understand. Not an ideal situation with the Color/ColorTypes thing, but whatever. Do the Colors.jl people know about ColorTypes at least?

**Pull request merged**
