### PR TITLE
Register VLFeat and tag 0.0.2

### PR DESCRIPTION
**Pull request by stemann**

### CODE REVIEW

**Comment by IainNZ** [comment]
Hi @stemann, just making sure you do mean the `julia` version dependency you have there? It means "at least 0.3, but not the release version of 0.4 (but prerelease 0.4 ok)". Is that correct?

**Comment by IainNZ** [comment]
(it isn't harmful, as long as you release another version before 0.4 comes out)

**Comment by stemann** [comment]
Yes, I know.

**Comment by stemann** [comment]
Hold on for a bit - need to transfer repo from @kmsquire.

**Comment by stemann** [comment]
OK to proceed.

**Pull request merged**
