### PR TITLE
Tag DiffEqProblemLibrary.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DiffEqProblemLibrary.jl](https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl)
Release: [v0.5.0](https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/DiffEqProblemLibrary.jl/builds/221423395)
Diff: [vs v0.4.0](https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl/compare/fe37c4b3f2fb4d808f5b681d3cf1fbd079fb7f67...0930b72b2f6abdcdc96fedb7d128d7da4f664954)
`requires` vs v0.4.0: 
```diff
--- 0.4.0/requires
+++ 0.5.0/requires
@@ -1,6 +1,6 @@
 julia 0.5
 ParameterizedFunctions 0.5.0
-DiffEqBase 0.2.0
+DiffEqBase 0.15.0
 FiniteElementDiffEq 0.0.5
 JLD 0.6.5
 DiffEqPDEBase
```
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/8769#issuecomment-293639490

**Comment by ChrisRackauckas** [comment]
This had an extra package in REQUIRE which caused the test to fail since it was doing the downgrading of DiffEqBase.jl. That's all fixed up now. Tests should pass here.

**Comment by ChrisRackauckas** [comment]
Actually, this will need DiffEqPDEBase to go first.

**Comment by ChrisRackauckas** [comment]
Since DiffEqPDEBase has gone through, tests are passing everywhere. The only one which hasn't passed yet is v0.5 Mac, but that's because Travis is taking its time starting it. This is safe to merge.

**Comment by tkelman** [comment]
Not while it fails the metadata tests.

**Comment by ChrisRackauckas** [comment]
How is it failing the METADATA tests while Travis and AppVeyor are passing?

**Comment by tkelman** [comment]
`PkgDev.check_metadata()` is failing.

**Comment by ChrisRackauckas** [comment]
```julia
julia> using PkgDev

julia> PkgDev.check_metadata()
ERROR: UndefVarError: check_metadata not defined
```

**Comment by ChrisRackauckas** [comment]
What do I do to investigate this?

**Comment by tkelman** [comment]
I think it's under PkgDev.Entry, sorry. Should be reproducible locally.

**Comment by ChrisRackauckas** [comment]
```julia
julia> PkgDev.Entry.check_metadata()
ERROR: packages with unsatisfiable requirements found:
    BioEnergeticFoodWebs v0.3.0 – no valid versions exist for package PolynomialFactors
    BioEnergeticFoodWebs v0.3.1 – no valid versions exist for package PolynomialFactors
```

Looks like it's trying to downgrade BioEnergeticFoodWebs to v0.2.0 (pre DifferentialEquations)? I'm not sure why that would be an issue though.

**Comment by ChrisRackauckas** [comment]
This looks to be fixed locally by minimum version requirements on BioEnergeticFoodWebs. I'll PR that.

**Comment by ChrisRackauckas** [comment]
Is there a way to force attobot to rebase after https://github.com/JuliaLang/METADATA.jl/pull/8815 ?

**Comment by tkelman** [comment]
Travis runs on the merge commit, so restarting should be enough.

**Comment by ChrisRackauckas** [comment]
Looks like this one is good now.

**Pull request merged**
