### PR TITLE
upper bound Tokenize for OhMyREPL 0.5

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/KristofferC/OhMyREPL.jl/issues/93

Is this correct @tkelman?

### CODE REVIEW

**Comment by tkelman** [comment]
I would leave off the v prefixes. Can this be fixed in Tokenize? If not, may want to start using a new minor there to reflect the API break.

**Comment by KristofferC** [comment]
Yeah, I didn't realize that would be an API break. If this fixes it, I would like to go with this simple fix since it is technically for a version of OMR that is not supported anymore.

**Comment by tkelman** [comment]
Right but I'd request that you start using 0.2.x numbering in Tokenize ASAP, maybe even making a duplicate of your latest tag as 0.2.0. People are still using OhMyREPL on 0.5 and it would be good to leave versioning room for possible backport bug fixes just in case.

**Comment by tkelman** [comment]
actually which version caused the problem, 0.1.8 or 0.1.9? upper bounds are exclusive

**Comment by KristofferC** [comment]
The 0.1.9 version has problems. I tagged a 2.0 Tokenize

**Comment by tkelman** [comment]
so if 0.1.8 worked fine, the upper bound should be 0.1.9

**Comment by KristofferC** [comment]
Fixed

**Comment by KristofferC** [comment]
Seems like attobot didnt pick up the new tag, perhaps because it is on the same commit as the previous one.

**Comment by tkelman** [comment]
Maybe it assumes that was unintentional? Hm, could manually propose copying the 0.1.10 metadata files to a new 0.2.0 then

**Pull request merged**
