### PR TITLE
Tag LogParser v0.3.0

### PR DESCRIPTION
**Pull request by randyzwitch**
I intentionally made this `julia 0.5` instead of `julia 0.5-`, as I don't want to have to do another PR just to switch it in a few weeks.

### CODE REVIEW

**Comment by tkelman** [comment]
you could make it `0.5.0-rc0` and it will be installable now, otherwise this version won't be installable yet

**Comment by randyzwitch** [comment]
If I put  0.5.0-rc0, it will also allow for 0.5 when it comes out?

**Comment by tkelman** [comment]
yes, the first version is an inclusive lower bound, the second version (if present) is an exclusive upper bound

**Comment by tkelman** [comment]
You're running Travis and AppVeyor against 0.4 still, are you intending for this to be 0.5-only?

**Comment by tkelman** [comment]
And looks like Gzip is a test-only dependency so could go in `test/REQUIRE`, and you aren't using Compat at all at the moment, but better to have more dependencies listed than you need than the other way around.

**Comment by randyzwitch** [comment]
Thanks for the careful eyes Tony, I'll clean this up and keep in mind for next submissions

**Pull request merged**
