### PR TITLE
Register new package SDL2.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jonathanBieler/SDL2.jl](https://github.com/jonathanBieler/SDL2.jl)
Release: [v0.0.1](https://github.com/jonathanBieler/SDL2.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/jonathanBieler/SDL2.jl/builds/355852053)
cc: @jonathanBieler

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@jonathanBieler This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like tests are failing

**Comment by stevengj** [comment]
Why SDL2 rather than SDL (or something more verbose like SimpleDirectMediaLayer)?

**Comment by jonathanBieler** [comment]
Mainly because there was already a SDL.jl package, I wouldn't mind renaming it, but I also still have some build issues.

**Comment by stevengj** [comment]
Where is the other SDL.jl package?  I can't seem to find it.

**Comment by jonathanBieler** [comment]
It got removed I think, it wasn't working anymore:

https://github.com/JuliaLang/METADATA.jl/blob/5873ff972e7947a3fc93ebc22fac4c071ee6fc7a/SDL/url

https://github.com/JuliaPackageMirrors/SDL.jl

**Comment by andreasnoack** [comment]
bump

**Comment by jonathanBieler** [comment]
Sorry, I renamed the package recently to SimpleDirectMediaLayer.jl, there's some issues with the linux build but it seems solved in v0.7. I guess I need to do a new pull request ?

**Pull request closed without merging**
