### PR TITLE
Tag DataFrames v0.6.11

### PR DESCRIPTION
**Pull request by tshort**

### CODE REVIEW

**Comment by tkelman** [comment]
Please re-tag this as 0.7.0, since it's the first version to drop support for Julia 0.3.

**Comment by tshort** [comment]
I know how to add a tag, but are you suggesting I should remove the 0.6.11 tag? If so, how?

**Comment by tkelman** [comment]
We can leave the 0.6.11 tag as is, but if the need arises in the future to tag a new bugfix release that still support 0.3 off of a branch of DataFrames, we should leave room for it to be 0.6.12. The versions wouldn't be monotonic but that's not too big a deal.

**Comment by tkelman** [comment]
Please do `Pkg.tag("DataFrames", :minor)`. It's better for someone with commit access to do it, but otherwise I'll make the change here.

**Comment by nalimilan** [comment]
@tshort Tagged 0.7.0, but should we also publish it?

**Comment by tkelman** [comment]
Yes, I meant metadata tag more than git tag.

**Comment by nalimilan** [comment]
OK. See https://github.com/JuliaLang/METADATA.jl/pull/4855.

**Pull request merged**
