### PR TITLE
Register new package LTVModelsBase.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [baggepinnen/LTVModelsBase.jl](https://github.com/baggepinnen/LTVModelsBase.jl)
Release: [v0.1.0](https://github.com/baggepinnen/LTVModelsBase.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/baggepinnen/LTVModelsBase.jl/builds/441239238)
cc: @baggepinnen

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@baggepinnen This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use acronyms like LTV in package names.

**Comment by baggepinnen** [comment]
Is `LinearTimeVaryingModelsBase` a better name? I didn't think so considering it's length and that this is not a user facing package, but I could change it if necessary.

**Comment by andreasnoack** [comment]
> Is LinearTimeVaryingModelsBase a better name?

I'd say so

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
