### PR TITLE
DictFiles v0.0.2, FunctionalDataUtils v0.0.5, FunctionalData v0.0.10, ShapeModels v0.0.3, ExtremelyRandomizedTrees v0.0.5, InformedDifferentialEvolution v0.0.4

### PR DESCRIPTION
**Pull request by rened**

### CODE REVIEW

**Comment by IainNZ** [comment]
Haha such industriousness, I love it. Looking forward to trying the ExtremelyRandom Trees on some problems of mine.

**Comment by rened** [comment]
;-)

**Comment by rened** [comment]
ah, hm, squashing would probably have been a good idea. next time.

**Comment by tkelman** [comment]
squashing is no big deal, but at least being patient enough to let travis finish would be good, so we don't accidentally break travis on master and hence any other innocent pr's

**Comment by rened** [comment]
sure, good point. (the failure here was just to do travis having problems talking to the github api - i retriggered the build and it is ok)

**Comment by tkelman** [comment]
generally "fatal: Couldn't find remote ref refs/pull/2438/merge" means you merged the pull request before travis even started

**Comment by rened** [comment]
hm, ic :-( sorry about  that, will be more patient next time.

**Comment by tkelman** [comment]
no harm done here (and the travis queue can get really annoying sometimes), but better to be a little bit conservative imo

**Pull request merged**
