### PR TITLE
Register AffineInvariantMCMC [https://github.com/madsjulia/AffineInva…

### PR DESCRIPTION
**Pull request by montyvesselinov**
…riantMCMC.jl.git]: v0.1.0, v0.1.1

### CODE REVIEW

**Comment by montyvesselinov** [comment]
Please register. We are in a middle of Mads changes.

**Comment by nalimilan** [comment]
Looks like a very well documented and test package! Though Travis tests are failing on master, and I can't see them run for the version you register here. Could you make them pass? Also, is there a minimum version requirement for RobustPmap?

Finally, I wonder what's the advantage of putting these two functions in a separate package, since the README and the docs all refer to MADS rather than specifically to this package. Since it doesn't have any non-Julia dependencies, it should be pretty lightweight to merge into a bigger package. Anyway, that's your call, not mine.

**Comment by montyvesselinov** [comment]
https://travis-ci.org/madsjulia/AffineInvariantMCMC.jl

i see it passing.

We use this module from Mads and BIGUQ.jl so we need it is a separate.

Thank you very much!

**Comment by nalimilan** [comment]
OK. So it's just the link in README.md which is incorrect.

Could you also move COPYING.md to LICENSE.md? That also allows GitHub to detect the license automatically.

What about the minimum RobustPmap version?

**Comment by montyvesselinov** [comment]
LICENSE.md added.

Any version of RobustPmap will work; we support RobustPmap. Thank you very much!

**Comment by nalimilan** [comment]
Can you update the PR with the new version then?

**Comment by montyvesselinov** [comment]
I cannot update it; can you do it for me. Thank you very much!

**Comment by montyvesselinov** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/7215

**Comment by tkelman** [comment]
closing as superseded by 7215

**Pull request closed without merging**
