### PR TITLE
Tag Reactive.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGizmos/Reactive.jl](https://github.com/JuliaGizmos/Reactive.jl)
Release: [v0.4.0](https://github.com/JuliaGizmos/Reactive.jl/releases/tag/v0.4.0)
Diff: [vs v0.3.7](https://github.com/JuliaGizmos/Reactive.jl/compare/1b4e2c050ffa65238a6082117a99732d7a437ea0...45cd55214f02be4f41e5df64a5628cecab913f82)
`requires` vs v0.3.7: 
```diff
--- 0.3.7/requires
+++ 0.4.0/requires
@@ -1,2 +1,2 @@
-julia 0.4
+julia 0.5
 DataStructures
```
cc: @timholy

### CODE REVIEW

**Comment by tkelman** [comment]
Not super surprising, this caused the tests to fail for Interact https://github.com/JuliaCI/pkg.julialang.org/blob/c868b6c9a62315ab23df2331ffd159c23cb29f2e/logs/Interact_0.5.log
and GtkReactive https://github.com/JuliaCI/pkg.julialang.org/blob/c868b6c9a62315ab23df2331ffd159c23cb29f2e/logs/GtkReactive_0.5.log

**Comment by tkelman** [comment]
ping @shashi on the Interact failure

**Comment by tkelman** [comment]
also ping @jobjob

**Comment by JobJob** [comment]
Cheers @tkelman, yep, the Interact test for the name of the slider's signal is now wrong, not a big deal in practice, but will fix it after we merge https://github.com/JuliaGizmos/Reactive.jl/pull/129

**Pull request merged**
