### PR TITLE
Register new package OpenTrick.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [zhanglix/OpenTrick.jl](https://github.com/zhanglix/OpenTrick.jl)
Release: [v0.1.0](https://github.com/zhanglix/OpenTrick.jl/releases/tag/v0.1.0)
cc: @zhanglix

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@zhanglix This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by zhanglix** [comment]
Will this PR be merged automatically three days later or manually by someone? Could it be merged as soon as possible? 

thank you.

**Comment by zhanglix** [comment]
@andreasnoack  could you help me to  merge this PR? Thank you.

**Comment by andreasnoack** [comment]
Please avoid commenting on PRs unless it is necessary. Your PR would have been merged automatically if you hadn't commented on it.

**Comment by zhanglix** [comment]
@andreasnoack Sorry, I didn't known the rule. Maybe add this to the automatically generated PR description is helpful to newbies like me .

**Comment by andreasnoack** [comment]
No problem. You couldn't know that. Things are still a bit in transition. Once things have settled, we'll update the descriptions.

**Pull request merged**
