### PR TITLE
Tag Knet.jl v0.8.6

### PR DESCRIPTION
**Pull request by attobot**
Repository: [denizyuret/Knet.jl](https://github.com/denizyuret/Knet.jl)
Release: [v0.8.6](https://github.com/denizyuret/Knet.jl/releases/tag/v0.8.6)
Travis: [Travis Build Status](https://travis-ci.org/denizyuret/Knet.jl/builds/316952393)
Diff: [vs v0.8.5](https://github.com/denizyuret/Knet.jl/compare/8ea130e8403f2bed37101da2834442c4a4846a3d...7d14a44fe2ae69f581336a95be03f4ad2dd334be)
`requires` vs v0.8.5: 
```diff
--- 0.8.5/requires
+++ 0.8.6/requires
@@ -1,10 +1,9 @@
-julia 0.4
+julia 0.6
 AutoGrad 0.0.9
+Compat 0.33.0
 
-# We need these for some examples. They get automatically installed when needed.
-# ArgParse
-# JLD
-# GZip    # for mnist
-# Images  # for vgg
-# MAT     # for vgg
-# Compat  # for mnist,vgg,charlm
+# The following are used by the build script if installed.
+# CUDAapi, CUDAdrv, Documenter
+
+# We need the following for some examples. They get automatically installed when needed.
+# ArgParse, JLD, JLD2, Images, GZip, MAT, PyCall, JSON, IJulia, BenchmarkTools, Distributions
```
cc: @denizyuret

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Do you mind deleting the tag, and re-tagging? Attobot should update this PR. The tests fails due to the Autograd issue from earlier, and re-tagging should fix this.

**Comment by denizyuret** [comment]
Avik, what exactly is the issue?  Do I need to change anything?  Or can I
just resubmit the code as is?

**Comment by aviks** [comment]
No, you do not need to change anything. Just delete the tag, and re-tag (at the same commit). We essentially need to rebase the PR to the latest HEAD of METADATA -- attobot will do that automatically if you re-tag.

**Comment by denizyuret** [comment]
In particular, do I need to support julia 0.4 or change the tag number to Knet 0.9?  If I have to choose between the two I will try to re-support 0.4 because I reserve Knet 0.9 for the next big change in the user interface.

**Comment by denizyuret** [comment]
Ok, understood.  I may add a commit or two from the latest bug fixes if
that is ok.

**Comment by aviks** [comment]
No, everything can stay the same -- Knet v0.8.6

**Comment by aviks** [comment]
Yes, sure.

**Comment by aviks** [comment]
Actually, hold, on, I misspoke, sorry. The Autograd issue from earlier has been fixed automatically. I did not see the new test results, and that fails, due to changing the patch version while dropping julia version support. So your options are, as you say: support 0.4, or tag 0.9.

**Comment by denizyuret** [comment]
OK, you can close this request, I will retag and open a new one.

**Comment by aviks** [comment]
Sorry for the trouble!

**Pull request closed without merging**
