### PR TITLE
Tag IntervalConstraintProgramming.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIntervals/IntervalConstraintProgramming.jl](https://github.com/JuliaIntervals/IntervalConstraintProgramming.jl)
Release: [v0.6.0](https://github.com/JuliaIntervals/IntervalConstraintProgramming.jl/releases/tag/v0.6.0)
Diff: [vs v0.5.0](https://github.com/JuliaIntervals/IntervalConstraintProgramming.jl/compare/edc8e17404ee85704868e15ff2847c14c445763e...45b4d99a485f2ae93722663c8280dc6ce33e1f8a)
`requires` vs v0.5.0: 
```diff
--- 0.5.0/requires
+++ 0.6.0/requires
@@ -1,4 +1,5 @@
-julia 0.4
-ValidatedNumerics 0.7
+julia 0.5
+IntervalArithmetic 0.9
+IntervalRootFinding 0.1
 MacroTools 0.3
-Compat 0.7.14
+
```
cc: @dpsanders

### CODE REVIEW

**Comment by tkelman** [comment]
Should this be 0.6-only, if it fails tests on 0.5?

**Comment by dpsanders** [comment]
The package works fine on 0.5. The failure seems to occur *only* when inside a testset! 

Once 0.6 is released and packages are updated, it can be 0.6 only. For now let's leave it as 0.5 installable.

**Comment by tkelman** [comment]
May want to be more targeted about the testing exception, to be sure other regressions don't slip through

**Comment by dpsanders** [comment]
Thanks.

**Pull request merged**
