### PR TITLE
Tag Optim v0.6.1 [https://github.com/JuliaOpt/Optim.jl] 

### PR DESCRIPTION
**Pull request by pkofod**
Better deprecations, ref #5943 
changes: https://github.com/JuliaOpt/Optim.jl/blob/276c98d3a61432a14fad388debce91d056653b88/src/nelder_mead.jl#L47

might be a weird way to do it, but it works :)

### CODE REVIEW

**Comment by tkelman** [comment]
Travis says
```
ERROR: LoadError: LoadError: syntax: missing comma or ) in argument list
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/travis/.julia/v0.4/Optim/src/nelder_mead.jl, in expression starting on line 49
while loading /home/travis/.julia/v0.4/Optim/src/Optim.jl, in expression starting on line 88
```

**Comment by pkofod** [comment]
Ah, that's a mistake, I didn't test it on v0.4, and I'm using generators... I'm fixing it.

**Comment by pkofod** [comment]
https://travis-ci.org/JuliaOpt/Optim.jl

**Comment by tkelman** [comment]
tag 0.6.2 with the fix then?

**Pull request closed without merging**
