### PR TITLE
Tag Match.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [kmsquire/Match.jl](https://github.com/kmsquire/Match.jl)
Release: [v1.0.0](https://github.com/kmsquire/Match.jl/releases/tag/v1.0.0)
Diff: [vs v0.4.0](https://github.com/kmsquire/Match.jl/compare/1c980a4299a04d2fc0d0ac5041ef122c38c6b736...e3111ed561c6889fecf4e79c5fbe5b5e2d1356c8)
`requires` vs v0.4.0: 
```diff
--- 0.4.0/requires
+++ 1.0.0/requires
@@ -1 +1 @@
-julia 0.6
+julia 0.7
```
cc: @kmsquire

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by kmsquire** [comment]
Looks like JuliaCIBot is using the previously tagged version of Match.jl, not the one tagged here.

**Comment by kmsquire** [comment]
> Looks like JuliaCIBot is using the previously tagged version of Match.jl, not the one tagged here.

Still true after rerunning.

**Comment by kmsquire** [comment]
Okay, ignore my last comments--I was looking at the "old" tests (which should be failing).

The packages being tested (Languages and FirstOrderLogic) are failing for their own reasons on v0.7 and on v1.0

The error for Match.jl isn't clear to me:

```julia
[ Info: Cloning cache of Match from https://github.com/kmsquire/Match.jl.git
[ Info: Installing Match v1.0.0
[ Info: Package database updated
[ Info: Computing test dependencies for Match...
ERROR: KeyError: key "Test" not found
Stacktrace:
 [1] getindex at ./dict.jl:478 [inlined]
 [2] resolve(::Dict{String,OldPkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,OldPkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,OldPkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/OldPkg/src/entry.jl:493
 [3] resolve at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/OldPkg/src/entry.jl:485 [inlined] (repeats 4 times)
 [4] macro expansion at ./logging.jl:307 [inlined]
 [5] #test!#57(::Bool, ::Function, ::String, ::Array{AbstractString,1}, ::Array{AbstractString,1}, ::Array{AbstractString,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/OldPkg/src/entry.jl:699
 [6] (::getfield(OldPkg.Entry, Symbol("#kw##test!")))(::NamedTuple{(:coverage,),Tuple{Bool}}, ::typeof(OldPkg.Entry.test!), ::String, ::Array{AbstractString,1}, ::Array{AbstractString,1}, ::Array{AbstractString,1}) at ./none:0
 [7] #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/OldPkg/src/entry.jl:749
 [8] #test at ./none:0 [inlined]
 [9] #4 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/OldPkg/src/dir.jl:36 [inlined]
 [10] cd(::getfield(OldPkg.Dir, Symbol("##4#7")){Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:coverage,),Tuple{Bool}}},typeof(OldPkg.Entry.test),Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:96
 [11] #cd#1(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:coverage,),Tuple{Bool}}}, ::Function, ::Function, ::Array{AbstractString,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/OldPkg/src/dir.jl:36
 [12] #cd at ./none:0 [inlined]
 [13] #test#3(::Bool, ::Function, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/OldPkg/src/OldPkg.jl:269
 [14] (::getfield(OldPkg, Symbol("#kw##test")))(::NamedTuple{(:coverage,),Tuple{Bool}}, ::typeof(OldPkg.test), ::String) at ./none:0
 [15] top-level scope at none:0
```

See 
* https://juliarun-ci.s3.amazonaws.com/82bd55ae77d750c89cecdfb47e5f5ed20314ff90/pull_request_of_Match_on_julia_0_7.log
* https://juliarun-ci.s3.amazonaws.com/82bd55ae77d750c89cecdfb47e5f5ed20314ff90/pull_request_of_Match_on_julia_1_0.log

**Comment by kmsquire** [comment]
Perhaps this is because `using Base.Test` was changed to `using Test`, but `OldPkg` doesn't understand this?  Cc: @StefanKarpinski

**Comment by fredrikekre** [comment]
Just remove your `test/REQUIRE` file.

**Comment by aviks** [comment]
@kmsquire  https://github.com/kmsquire/Match.jl/pull/50

It may be best to merge that and re-tag.

**Comment by kmsquire** [comment]
@fredrikekre and @aviks, thanks for the help!

**Pull request merged**
