### PR TITLE
Tag ActuarialScience v0.0.3

### PR DESCRIPTION
**Pull request by alecloudenback**
update Actuarial Science Package

Let me know if this isn't the standard way to update packages! first time updating public package.

### CODE REVIEW

**Comment by tkelman** [comment]
Should rebase out the merge commit. The sha is the same for 0.0.3 and 0.0.4 here, did you intend that?

**Comment by alecloudenback** [comment]
The duplicate tag is really the fault of my trying to get my package to publish and issuing the commands multiple times. This is a continuation of my first contribution to open source, so please let me know if I understand what you're suggesting:

I should un-merge my commit to `metadata-v2`, and refresh `metadata-v2` to latest version. Take my branch ('rebase'?) back to `2dbd77f`. Then tag and publish with the PkgDev tool?

**Comment by ararslan** [comment]
To remote the duplicate tag, `cd` to the directory for ActuarialScience.jl, then do
```bash
git tag -d v0.0.4
git push origin :refs/tags/v0.0.4
```

Now, to remove the unnecessary commits from this PR, `cd` to the METADATA directory and do
```bash
git checkout -b tag-as-0.0.3
git rebase -i HEAD~10
# Delete all lines except for Tag ActuarialScience 0.0.3
git push alecloudenback tag-as-0.0.3:pull-request/60310c60 --force
```

I also recommend cleaning up your local METADATA clone after doing the above:
```
git checkout metadata-v2
git reset --hard origin/metadata-v2
```

**Comment by alecloudenback** [comment]
@ararslan Really appreciate the direction. I think that all worked great, though I did need to add an `alecloudenback` remote.

**Comment by ararslan** [comment]
Glad it worked for you! This looks great to me now.

**Pull request merged**
