### PR TITLE
Tagging GLVisualize and friends

### PR DESCRIPTION
**Pull request by SimonDanisch**
Making GLVisualize master easily installable before merging next2.

@sjkelly Sorry, but you took too long ;) We can tag again whenever you get your PR's ready.

@ViralBShah, @shashi, only Reactive should be missing after this

### CODE REVIEW

**Comment by SimonDanisch** [comment]
and FreeType: #4434

**Comment by sjkelly** [comment]
GeometryTypes is supposed to be v0.2.0 since we added deprecations.

**Comment by SimonDanisch** [comment]
uh... did loose track of your semver scheme... Do it with your next tag (that you planned instead of this anyways?)

**Comment by sjkelly** [comment]
No worries. The GL ecosystem is the only packages that use it and we made
the appropriate patches already!

**Comment by tkelman** [comment]
GLAbstraction should move to 0.1.x since you have past tags that support julia 0.3.

**Pull request merged**
