### PR TITLE
Tag KrylovMethods v0.2.0

### PR DESCRIPTION
**Pull request by lruthotto**

### CODE REVIEW

**Comment by tkelman** [comment]
Your test-only dependencies should be given in `test/REQUIRE`, not added on Travis. Your tests depend on an unregistered package, so it's not possible for them to pass when someone just does `Pkg.add("KrylovMethods"); Pkg.test("KrylovMethods")`.

**Comment by lruthotto** [comment]
This is not a test-only requirement. Our code actually does break without this new version of KrylovMethods that features block iterative methods.

**Comment by lruthotto** [comment]
I see what you mean now. Sorry. No problem adding MatrixDepot, but how to go about Linear Operators (not an official package)?

**Comment by tkelman** [comment]
Either it should be registered or the tests of a registered package shouldn't depend on it (or those that do could be made optional).

**Comment by ViralBShah** [comment]
Best to register LinearOperators.jl.

Cc @dpo as well.

**Comment by dpo** [comment]
Let me make a few updates to LinearOperators and I'll submit it here.

**Comment by dpo** [comment]
See #5766.

**Pull request merged**
