### PR TITLE
Tag TOML v0.3.0

### PR DESCRIPTION
**Pull request by pygy**

### CODE REVIEW

**Comment by milktrader** [comment]
This will probably fail on travis since it was merged before travis could complete the testing. Sometimes travis takes a while to run so it can be aggravating waiting for it.

**Comment by pygy** [comment]
Le Fu....

Any corrective manoeuvre on my hand?

**Comment by IainNZ** [comment]
No, don't worry about this one. Just don't do it next time ;-)

**Comment by pygy** [comment]
Cool.

Sorry for the noise, I wasn't aware of the issue. It may be the first  time I merge an update by myself (or, the previous times, I didn't do it immediately).

I'll be more careful next time.

I relaunched Travis manually, and it succeeded, but it hasn't been reflected here.

**Comment by milktrader** [comment]
Thanks @pygy !

**Pull request merged**
