### PR TITLE
Tag Compat v0.8.0 [git://github.com/JuliaLang/Compat.jl.git]

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by nalimilan** [comment]
Would you include https://github.com/JuliaLang/Compat.jl/pull/227 in the release? I think it should be uncontroversial.

**Comment by malmaud** [comment]
Why not just tag a patch once it's merged?

**Comment by tkelman** [comment]
the commit that you tagged doesn't exist on master. please don't tag from a branch.

**Comment by malmaud** [comment]
Sorry about that.

**Pull request closed without merging**
