### PR TITLE
Tag ArbFloats v0.1.9 [https://github.com/JuliaArbTypes/ArbFloats.jl]

### PR DESCRIPTION
**Pull request by JeffreySarnoff**
low level speedups, speed comparison to BigFloat in PERFORMANCE.md

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like you still have to push the tag to your repo so that it shows up under https://github.com/JuliaArbTypes/ArbFloats.jl/releases.

**Comment by JeffreySarnoff** [comment]
@ararslan Thank you. The new tag is now pushed.

**Comment by ararslan** [comment]
Great! Could you close and reopen the PR to trigger a rebuild on Travis?

**Comment by JeffreySarnoff** [comment]
Closing and reopening to trigger a rebuild.

**Comment by ararslan** [comment]
Just to be clear, you can click "reopen" here rather than opening a new pull request.

**Comment by JeffreySarnoff** [comment]
giving that a try -- I deleted and recloned my remote METADATA before seeing your note .. I have set my remote METADATA as I did the first time.

**Comment by tkelman** [comment]
Now there are commits from other packages in here. When you delete your repository that means the PR then says "unknown repository" and can't be fixed without opening a new one. Deleting your repository is never really necessary.

**Comment by JeffreySarnoff** [comment]
OK, my mistake.  When I clone the METADATA and time goes by my copy gets
very out of sync.  What is the way to make it  update itself?

**Comment by ararslan** [comment]
Run `Pkg.update()` regularly

**Comment by JeffreySarnoff** [comment]
nevermind -- thanks.

**Pull request closed without merging**
