### PR TITLE
Tag IterableTables.jl v0.8.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidanthoff/IterableTables.jl](https://github.com/davidanthoff/IterableTables.jl)
Release: [v0.8.1](https://github.com/davidanthoff/IterableTables.jl/releases/tag/v0.8.1)
Travis: [Travis Build Status](https://travis-ci.org/davidanthoff/IterableTables.jl/builds/405737537)
Diff: [vs v0.8.0](https://github.com/davidanthoff/IterableTables.jl/compare/73066dd57703674066386a3a3de5c786f9ce01cb...626530d7680039528471f9f72fb75f2f42c25653)
`requires` vs v0.8.0: no changes
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Not sure why the JuliaCIBot fails, things seem to work on the travis and appveyor builds?

**Comment by andreasnoack** [comment]
We have had to make a couple of adjustments of the script to make 0.7 testing work. I've restarted the tests so let's see how it goes.

**Comment by davidanthoff** [comment]
Hm, this looks to me like some error with JuliaCIBot?

**Comment by davidanthoff** [comment]
Could we just merge this? The failure seems entirely unrelated to the package, there just must be something wrong in the test script?

**Pull request merged**
