### PR TITLE
Register new package VehicleModels.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMPC/VehicleModels.jl](https://github.com/JuliaMPC/VehicleModels.jl)
Release: [v0.1.1](https://github.com/JuliaMPC/VehicleModels.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMPC/VehicleModels.jl/builds/245931971)
cc: @huckl3b3rry87

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@huckl3b3rry87 This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
Similarly here, if NLOptControl is used here, then it should be listed in REQUIRE

**Comment by tkelman** [comment]
Still missing a dependency on NLOptControl

**Comment by tkelman** [comment]
assuming this is replaced by #10032

**Comment by huckl3b3rry87** [comment]
@tkelman yes, sorry about that

**Pull request closed without merging**
