### PR TITLE
Lint.jl v0.6.0

### LINKED ISSUE #254: Unable to run `Pkg.add("Lint")`
Good afternoon. I'm trying to install the linter package by running:

```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.1 (2018-09-29)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Pkg
```

But when I run the following command, I get an `Unsatisfiable requirements` error (complete stacktrace attached)

`julia> Pkg.add("Lint")`
[Stacktrace.txt](https://github.com/tonyhffong/Lint.jl/files/2440382/Stacktrace.txt)

I'm following the [installation guide here](https://github.com/tonyhffong/Lint.jl), and am running Julia 1.0 on a Mac OS X, Version 10.13.6 if that helps at all. 
Thanks in advance!

### PR DESCRIPTION
**Pull request by FelipeLema**
Should fix https://github.com/tonyhffong/Lint.jl/issues/254
Done thanks to https://github.com/tonyhffong/Lint.jl/issues/254#issuecomment-473524335

### CODE REVIEW

**Comment by just-cameron** [comment]
Whats up with this PR? I'd like to see it go through.

**Comment by fredrikekre** [comment]
METADATA is EOL, you should use https://github.com/JuliaRegistries/Registrator.jl and register to the new registry.

**Comment by jayvdb** [comment]
@fredrikekre , would it be possible for this one to be updated in the old registry.  It was unmaintained for a while, so it doesnt have any recent/working releases in the old registry, making it difficult to use it in older Julia configurations.  See https://github.com/tonyhffong/Lint.jl/issues/254

**Comment by fredrikekre** [comment]
It looks like the package has moved on to require Julia 1.0 though?

**Comment by jayvdb** [comment]
Ah true.  Disregard.

**Pull request closed without merging**
