### PR TITLE
Tag MLLabelUtils.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaML/MLLabelUtils.jl](https://github.com/JuliaML/MLLabelUtils.jl)
Release: [v0.0.2](https://github.com/JuliaML/MLLabelUtils.jl/releases/tag/v0.0.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaML/MLLabelUtils.jl/builds/219457957)
Diff: [vs v0.1.1](https://github.com/JuliaML/MLLabelUtils.jl/compare/8f7a7f206fc9bb931dca55c3c8861fd16204e3e2...a486084590937764f1db4ec5217c5ccaf283d33a)
`requires` vs v0.1.1: 
```diff
--- 0.1.1/requires
+++ 0.0.2/requires
@@ -1,4 +1,4 @@
-julia 0.6-
-StatsBase 0.13
+julia 0.5
+StatsBase
 LearnBase 0.1.5 0.2.0
-MappedArrays 0.0.6
+MappedArrays
```
cc: @Evizero

### CODE REVIEW

**Comment by Evizero** [comment]
Unsure if I am using attobot correctly here. I am trying to backport a commit to a 0.5 branch (since master is already 0.6-).

**Comment by Evizero** [comment]
It should be correct based on what I am seeing with git. I am unsure why attobot compares to 0.1.1. Maybe that is just a default assumption?

**Comment by Evizero** [comment]
This should be the right diff against `v0.0.1`: https://github.com/JuliaML/MLLabelUtils.jl/compare/272c7...a486084590937764f1db4ec5217c5ccaf283d33a

**Comment by tkelman** [comment]
> Maybe that is just a default assumption?

Yeah, believe so. Maybe worth an issue over in the attobot repo to compare to the most recent patch release for the same minor series, when that exists.

**Pull request merged**
