### PR TITLE
Tag FastClosures.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [c42f/FastClosures.jl](https://github.com/c42f/FastClosures.jl)
Release: [v0.1.1](https://github.com/c42f/FastClosures.jl/releases/tag/v0.1.1)
Diff: [vs v0.1.0](https://github.com/c42f/FastClosures.jl/compare/e2b851582d9fe9384a6e49bec3b78febf54ae10c...170cad9e26326d6f6f664912e46b918b2f83c5ea)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.1.1/requires
@@ -1,2 +1,2 @@
-julia 0.5
+julia 0.6
 Compat 0.26.0
```
cc: @c42f

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
superseded by #11038

**Comment by c42f** [comment]
Thanks Tony.  I deleted the v0.1.1 release but I wasn't sure how I could get attobot to close this for me.

**Comment by tkelman** [comment]
currently these can only be closed by members of julialang. ref https://github.com/attobot/attobot/issues/30

**Comment by c42f** [comment]
Ah right, no problems.

**Pull request closed without merging**
