### PR TITLE
Register ClimateTools.jl

### PR DESCRIPTION
**Pull request by Balinus**
First commit of ClimateTools package.

### CODE REVIEW

**Comment by aviks** [comment]
Hi Balinus, did you not want to register this package any more?

**Comment by Balinus** [comment]
Well, I think it might be best to register a new version 0.0.2 which will be available in some days. I hope I have not wasted your time on this? :/

**Comment by aviks** [comment]
No, certainly not. We keep new package registrations open for a day or two before merging in case there are any comments on the package name (which is a global resource, and difficult to change later).

**Comment by Balinus** [comment]
ok, thanks for the clarification. I'll do a pull request in the next couples of days. The package will be more advanced.

I was unsure about the package name. It's meant to be a diverse set of tools for people working in the climate fields, hence the name ClimateTools.

**Comment by Balinus** [comment]
Well, it went faster than expected. I've submitted another pull request with version 0.0.2. Thanks!

**Pull request closed without merging**
