### PR TITLE
Register new package WordTokenizers.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaText/WordTokenizers.jl](https://github.com/JuliaText/WordTokenizers.jl)
Release: [v0.1.0](https://github.com/JuliaText/WordTokenizers.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaText/WordTokenizers.jl/builds/371530664)
cc: @oxinabox

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@oxinabox This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by oxinabox** [comment]
Time for some good ol' bike shedding over package names.
Problem with WordTokenizers.jl is that this also includes sentence splitters.
Which are notionally tokenizers. (NLTK calls them such).

Other possible names

 - **Tokenizers.jl** -- but this is very close to the julia only Tokenize.jl
 - **NaturalLanguageTokenizers.jl** -- which is a bit to long
 - **NaturalTokenizers.jl** -- Seems additionally unclear

**Comment by oxinabox** [comment]
- *Segmenters.jl** -- segmenting what?
 - **NaturalLanguageSegmenters.jl** -- better

**Comment by aviks** [comment]
I think `WordTokenizers`, though not technically correct, describes the essence of the package best. The other options are either confusing, or very awkward. Just add `(we also do sentences)` as a tagline to the package.

**Comment by ninjin** [comment]
I don’t think the name is a big deal, but it is worth pointing out that there is not a single researcher I know that has not been stumped by NLTK referring to sentence splitting as tokenisation. Things that flow through my mind, text segmentation, text preprocessing, etc. Work tokenisation sounds weird, since word and token are distinct things.

**Comment by oxinabox** [comment]
Word to Token as Character is the Letter.
They are not strictly the same thing, but they are closely linked and have a casual usage sense that is the same.
Consider also the usage: Morpheme tokenizer,  and Subword Tokenizer.

Text Preprocessing might work if the package also had Stop Word Removal.
Which might be a good things to include

**Comment by oxinabox** [comment]
If no one really objects to the name, I think WordTokenizers.jl will do fine.
I'ld like to merge this as it is blocking me on having CI for other packages

**Pull request merged**
