### PR TITLE
Register new package PackageCompiler.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [SimonDanisch/PackageCompiler.jl](https://github.com/SimonDanisch/PackageCompiler.jl)
Release: [v0.1.0](https://github.com/SimonDanisch/PackageCompiler.jl/releases/tag/v0.1.0)
cc: @SimonDanisch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@SimonDanisch This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Guess I can't open files on the JuliaCIBot?

**Comment by fredrikekre** [comment]
http://juliarun-ci.s3.amazonaws.com/60743df839a878d3c419b7a770b911da8eed0388/PackageCompiler_julia_0_6.log

**Comment by SimonDanisch** [comment]
Yeah exactly? `permission denied (EACCES)`  - this doesn't happen on travis

**Comment by fredrikekre** [comment]
Oh sorry, thought you meant you could not see the log...

**Comment by aviks** [comment]
Not sure why. what file are you trying to read?

**Pull request merged**
