### PR TITLE
Tag NamedTuples v0.0.3

### PR DESCRIPTION
**Pull request by mdcfrancis**
removes warnings for julia 0.4

### CODE REVIEW

**Comment by mdcfrancis** [comment]
Added the v0.0.4 tag which fixes a few other issues

**Comment by tkelman** [comment]
What's the minimum supported Julia version?

**Comment by mdcfrancis** [comment]
I have tagged v0.0.5 which removes 0.3 compat and specifies that this is only supported on 0.4

**Comment by tkelman** [comment]
Can you rebase out the unrelated commits (rather than merge) and force push over this branch? thanks

**Comment by tkelman** [comment]
And did the past tags support 0.3? If so it may be best to use a new 0.1.0 minor version for the first explicitly 0.4-only version.

**Comment by mdcfrancis** [comment]
I am closing this in favor of a squash commit on the following pull request

https://github.com/JuliaLang/METADATA.jl/pull/4364

**Comment by tkelman** [comment]
That works, thanks

**Pull request closed without merging**
