### PR TITLE
Register new package SetOps.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [scheinerman/SetOps.jl](https://github.com/scheinerman/SetOps.jl)
Release: [v0.1.0](https://github.com/scheinerman/SetOps.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/scheinerman/SetOps.jl/builds/416857059)
cc: @scheinerman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@scheinerman This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
This seems to be "type piracy": https://docs.julialang.org/en/stable/manual/style-guide/#Avoid-type-piracy-1

**Comment by scheinerman** [comment]
I'm not sure I understand your comment, but this module is not particularly important to me. I didn't think that tagging a package with a version number had any bearing on registering it as an "official" Julia package. Was not my intent.

**Comment by quinnj** [comment]
@scheinerman, did you not intend to register this package then? On the comment about type piracy.......I'd say this is lower-risk type piracy. I'm not sure how surprised anyone would be if `Set([1,2,3]) - Set([1,)` produced `Set([2,3])`. Anytime it's arguable that the definitions should themselves be in Base, I'd say it's not that terrible. But we'll wait to hear if @scheinerman actually wants to register this package or not.

**Comment by sbromberger** [comment]
Also note that `powerset` exists in `Combinatorics.jl`: https://github.com/JuliaMath/Combinatorics.jl/blob/60a2343af0dfc54ab01af6bb2f21d0b5a51fb729/src/combinations.jl#L268-L280

**Comment by scheinerman** [comment]
Let's not register. I don't think there's much of a call for this and mostly this was written for myself as a learning exercise.  The functionality exists in Julia. I would recommend that (-) be included as `setdiff`, but that's a minor matter.

**Pull request closed without merging**
