### PR TITLE
Register new package BanditOpt.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [v-i-s-h/BanditOpt.jl](https://github.com/v-i-s-h/BanditOpt.jl)
Release: [v0.0.1](https://github.com/v-i-s-h/BanditOpt.jl/releases/tag/v0.0.1)
cc: @v-i-s-h

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@v-i-s-h This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Did you intend to make this release? Your package doesn't contain anything.

**Comment by v-i-s-h** [comment]
I'm registering this package as a placeholder for name 'BanditOpt', so that I can use the name once I code the stuff.

**Comment by simonbyrne** [comment]
Although not formally written any where, we typically expect the package to do something before it can be registered.

**Comment by v-i-s-h** [comment]
Oh..Ok. Now I understand.
I will publish the code soon with a new release.
I think you can reject this PR.

Thanks @andreasnoack and @simonbyrne for the clarification.

**Pull request closed without merging**
