### PR TITLE
Tag TimeSeries.jl v0.14.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/TimeSeries.jl](https://github.com/JuliaStats/TimeSeries.jl)
Release: [v0.14.0](https://github.com/JuliaStats/TimeSeries.jl/releases/tag/v0.14.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/TimeSeries.jl/builds/445450733)
Diff: [vs v0.13.0](https://github.com/JuliaStats/TimeSeries.jl/compare/93d1890820ddfe1abc30c997aa437707ffa15efc...b98c9681c6281770c86b58da14b2c1aa49798410)
`requires` vs v0.13.0: no changes
cc: @iblis17

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by iblislin** [comment]
Quoted from the [log](https://juliarun-ci.s3.amazonaws.com/b0d3d4aed22596340d204c64dcd91b7d99b1a945/MarketData_with_pull_request_of_TimeSeries_on_julia_1_0.log)  
```
[9e3dc215] + TimeSeries v0.14.0
```

:thinking: this confused me.

**Comment by iblislin** [comment]
Do we need to rebase this PR?

**Comment by andreasnoack** [comment]
I think it might be because the registry hadn't been updated yet when I restarted the tests. Let's try again.

**Comment by andreasnoack** [comment]
It looks like the `TimeSeries` tests are failing.

**Comment by iblislin** [comment]
I cannot reproduce the failures.
but I guess it's caused by the upper bound of MarketData at TimeSeries.
(since I `grep` the log, 
found there are both `  [9e3dc215] + TimeSeries v0.14.0` and `  [9e3dc215] TimeSeries v0.13.0`)

I can send another PR against this PR, to remove the upper bound of latest MarketData.
And let's try the JuliaCIBot again.

**Comment by iblislin** [comment]
I decide to make a new tag for MarketData.
It is compatible for both TimeSeries v0.13.0 and v0.14.0.
Ref: https://github.com/JuliaLang/METADATA.jl/pull/19184

**Comment by iblislin** [comment]
(I don't have the permission to re-open this PR)

**Comment by andreasnoack** [comment]
You can just remove the tag and reapply it. That will trigger the tests.

**Pull request merged**
