### PR TITLE
Adding ParSpMatVec with tagged version 0.0.1.

### PR DESCRIPTION
**Pull request by lruthotto**
I hope this is what you meant, @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
Yes. You can push additional commits to the same branch as an open PR and it will update, rather than opening a new PR for every modification.

**Comment by tkelman** [comment]
You need to list BinDeps in REQUIRE, not manually add it on travis.

**Comment by lruthotto** [comment]
Thanks, Tony. Added BinDeps as requirement now. It's quite elegant.

BTW: Is there a similar way to add a Fortran compiler as well? Right now, this seems to be an issue when using Travis on Linux OS's.

**Comment by tkelman** [comment]
Yep: https://github.com/JuliaOpt/Ipopt.jl/blob/cc7aee5256bbafb16c74e80b9b03cd29ee12088a/.travis.yml#L11-L13

**Comment by tkelman** [comment]
Travis is being flaky so I'm going to close and reopen this just to force it to run, pardon the noise.

**Comment by lruthotto** [comment]
Well, I don't think I could complain about the noise here. thanks for the hint and your patience. 

seems like travis testing now works on linux, too.

**Comment by tkelman** [comment]
No problem. I am still curious how this compares to @madeleineudell's similar package.

**Comment by timholy** [comment]
I wondered about that too. https://github.com/madeleineudell/ParallelSparseMatMul.jl

**Comment by lruthotto** [comment]
I didn't do a lot of comparison to ParallelSparseMatMul to be honest. My goal here was to have something that can replace julia's default routines without changing our codes too much. For example, the methods here don't need the user to distribute the matrix or even add processors. This is purely a convenience argument. However, the code here is faster than the one in Base (even with nproc =1 on my machine).

**Comment by lruthotto** [comment]
removed mumps. hope that's it!

**Comment by tkelman** [comment]
No, that new commit is completely deleting the package, that's not right either. Can you rebase out the mumps-related commits?

**Comment by lruthotto** [comment]
No, I don't know how to do that. Where can I learn that?

**Comment by lruthotto** [comment]
OK, I think I rebased it now. Will this PR change automatically?

**Comment by tkelman** [comment]
Ah sorry, had to give a lecture. Yeah this looks right now.

**Pull request merged**
