### PR TITLE
Tag NLSolversBase.jl v3.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/NLSolversBase.jl](https://github.com/JuliaNLSolvers/NLSolversBase.jl)
Release: [v3.0.0](https://github.com/JuliaNLSolvers/NLSolversBase.jl/releases/tag/v3.0.0)
Diff: [vs v2.1.3](https://github.com/JuliaNLSolvers/NLSolversBase.jl/compare/bce3ec37684d503ba077ff57a41dd1a49510ce7f...ddd6847e84116ad1fad258bbb066e5a298265c49)
`requires` vs v2.1.3: 
```diff
--- 2.1.3/requires
+++ 3.0.0/requires
@@ -1,2 +1,2 @@
-julia 0.5
+julia 0.6
 Compat 0.17.0
```
cc: @pkofod

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by pkofod** [comment]
(will update this with femtocleaner cleaning and remove compat so don't merge just yet)

**Comment by pkofod** [comment]
Ah well... This is because the argument order check is removed, so the objective and gradient counts are reduced. Version limits on LineSearches and Optim I guess.

**Comment by aviks** [comment]
@pkofod Let us know when this is ready to go.

**Comment by MikeInnes** [comment]
Closing as I'm not sure if this should go through. @pkofod let me know if I should merge this instead.

**Comment by pkofod** [comment]
I'll fix the remaining problems with anriseth and create a new pr

**Pull request closed without merging**
