### PR TITLE
Pull request/0ad53647

### PR DESCRIPTION
**Pull request by montyvesselinov**
new version of deps/build.jl using pip

please initiate a build test.

Thank you very much!

### CODE REVIEW

**Comment by montyvesselinov** [comment]
I checked the build status. It failed. However, yesterday's build was based
on version 0.1.4 which I knew is not going to work. I am confused why. The
latest build was 0.1.6.

-monty

**Comment by tkelman** [comment]
If you mean on pkg.julialang.org, that doesn't run as often as it should, Iain Dunning has still been triggering those manually.

**Comment by montyvesselinov** [comment]
On Wed, Mar 2, 2016 at 8:08 AM, Tony Kelman <notifications@github.com>
wrote:

> pkg.julialang.org


Yes. I meant for pkg.julialang.org.

I will be curious to see was it all fixed now. If we can initiate one it
will be great. Thank you very much!


-monty

**Comment by montyvesselinov** [comment]
Tony-

I think you already merged our pull request to add Mads.jl version 0.1.6.
Is this correct. I do not understand why http://pkg.julialang.org/ is still
testing version 0.1.4.

Thank you very much!

-monty

**Comment by tkelman** [comment]
The most recent run of PackageEvaluator must have started just before this got merged. Should get included in the next run, whenever that will be. Ideally it would be nightly but I don't think Iain ever wired up the whole thing to a cron job.

**Comment by montyvesselinov** [comment]
Could be. The web site this was done 3 days ago (see below). Version 0.1.6
was pushed more than a week ago.

Mads <http://github.com/madsjulia/Mads.jl>Model Analysis & Decision Support
GPL v3
<http://github.com/madsjulia/Mads.jl/blob/90760f55f08a253c7a05cdf9086d418c1c24b21e/LICENSE>
license
/ Owner: madsjulia <http://github.com/madsjulia>
2 ★ / 70 ↧ / 2 ↥
Julia v0.4: 0.1.4
<http://github.com/madsjulia/Mads.jl/tree/90760f55f08a253c7a05cdf9086d418c1c24b21e>
(3
days ago) /  Tests fail. <http://pkg.julialang.org/detail/Mads.html>
Julia v0.5: 0.1.4
<http://github.com/madsjulia/Mads.jl/tree/90760f55f08a253c7a05cdf9086d418c1c24b21e>
(3
days ago) /  Tests fail. <http://pkg.julialang.org/detail/Mads.html>


-monty

**Comment by tkelman** [comment]
The last entry under test details says 3-01 though, so it may have been a few days between running and uploading the website.

**Pull request merged**
