### PR TITLE
Register new package Tokenize.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Tokenize.jl](https://github.com/KristofferC/Tokenize.jl)
Release: [v0.1.0](https://github.com/KristofferC/Tokenize.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/KristofferC/Tokenize.jl/builds/184068692)
cc: @KristofferC

### CODE REVIEW

**Comment by simonbyrne** [comment]
Glad that worked!

**Comment by KristofferC** [comment]
I'm the one who is glad. No mucking around with metadata branch, ups wrong commit, reset metadata, delete tag, retag, push new tag, update PR, wups no lower bound on compat, delete tag, retag, push tag etc. etc.

**Comment by simonbyrne** [comment]
You seem to have an issue with the mac buildbot

**Comment by KristofferC** [comment]
"The command "curl -A "$CURL_USER_AGENT" -s -L -o julia.dmg 'https://s3.amazonaws.com/julialang/bin/osx/x64/0.5/julia-0.5-latest-osx10.7+.dmg'" failed and exited with 56 during ."

Tests passes on the other mac worker. Don't think  it is related to the package.

**Comment by KristofferC** [comment]
Restated and passed.

**Pull request merged**
