### PR TITLE
Tag CUBLAS.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGPU/CUBLAS.jl](https://github.com/JuliaGPU/CUBLAS.jl)
Release: [v0.2.0](https://github.com/JuliaGPU/CUBLAS.jl/releases/tag/v0.2.0)
Diff: [vs v0.1.0](https://github.com/JuliaGPU/CUBLAS.jl/compare/0f19aac8e811b446539992ac66e505a86856a735...c053b1d81e2e57330d6e5b7a7e6cd744678f73d1)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,2 +1,2 @@
 julia 0.5
-CUDArt 0.3.0
+CUDAdrv 0.5.1
```
cc: @MikeInnes

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
Is this failing on 0.5 on @maleadt's CI? http://ci.maleadt.net:8010/#builders/17/builds/6

**Comment by MikeInnes** [comment]
Ok, updated to be 0.6-only.

**Comment by tkelman** [comment]
Do so on master as well please. Does this actually require CUDAdrv 0.5.1 or would 0.5 suffice?

**Comment by MikeInnes** [comment]
0.5.1 is fine with me, but you're welcome to check that

**Pull request merged**
