### PR TITLE
mPulseAPI does not currently work with julia 0.7

### PR DESCRIPTION
**Pull request by bluesmoon**
Updating requires files for all versions since our current tests show that we don't work with julia 0.7.

### CODE REVIEW

**Comment by tkelman** [comment]
Are you sure you want to make Pkg.add an error? This is effectively deprecating the package.

**Comment by bluesmoon** [comment]
How would you suggest I specify that the package only works with 0.4, 0.5 and 0.6?  At the moment I can't even test on 0.7 because it complains about my documentation being in the wrong format.

**Comment by tkelman** [comment]
It's fine for the package not to work there yet (a note in the readme maybe), the question is whether you want to disallow installing it there altogether.

**Comment by bluesmoon** [comment]
nvm, I've made it work with 0.7.

**Pull request closed without merging**
