### PR TITLE
Tag UnitfulAngles.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [yakir12/UnitfulAngles.jl](https://github.com/yakir12/UnitfulAngles.jl)
Release: [v0.5.0](https://github.com/yakir12/UnitfulAngles.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/yakir12/UnitfulAngles.jl/builds/419828776)
Diff: [vs v0.3.0](https://github.com/yakir12/UnitfulAngles.jl/compare/b639c07434c5f69b12f694652c0db463c91f5439...9f27e0fb9c35b59f4106a1150f14547288c0ce25)
`requires` vs v0.3.0: no changes
cc: @yakir12

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please just update https://github.com/JuliaLang/METADATA.jl/pull/17188

**Comment by yakir12** [comment]
@andreasnoack, I appreciate your supervision here, God knows I need it, but I have no idea how to "just update #17188". To be honest, I was hoping to bring this package to a working state for version 0.7/1.0 but nothing more. The idea being that it would be better to have packages work for 1.0 now rather than have them both work for 1.0 AND in perfect order *later*. For instance, there are a few silly issues in there that I should fix and clean up (other than the ones you found). They are ugly, but they are not crucial. I don't have much time right now, and I'm a total git when it comes to git, so that's why it's the way it is...

So, again, tons of thanks for the help!! But, is removing the REQUIRE file for the tests super important? Or can we just go with the new tagged version (although I know I've been basically using the tags as a crude push, sorry about that)? Or could you explain how I can update a tag without push new changes and thus creating a new tag (again, I'm bad at gitting)?

**Comment by andreasnoack** [comment]
> So, again, tons of thanks for the help!! But, is removing the REQUIRE file for the tests super important?

Yes. Having stdlibs in your REQUIRE files can break things.

Please see https://github.com/attobot/attobot#updatingdeleting-a-release for how to update the other PR. It is really simple.

**Comment by yakir12** [comment]
> It is really simple.

Indeed it was! Hope it's all good now :|

**Pull request closed without merging**
