### PR TITLE
New package PrettyNumber

### PR DESCRIPTION
**Pull request by RedPointyJackson**
Basically, prettifies numbers using Unicode, like in 

````
julia> "0.42924042 ± 0.420e-20" |> prettify
"0.429 ± 4.2⋅10⁻²¹"
````

I would merge it with [Humanize.jl](https://github.com/IainNZ/Humanize.jl), but I have received
no response to a pull request.

### CODE REVIEW

**Comment by tkelman** [comment]
You'll need to push the git tag here.

**Comment by RedPointyJackson** [comment]
@tkelman done!

**Comment by tkelman** [comment]
Would Travis CI pass on the package if you enabled it at https://travis-ci.org/redpointyjackson/PrettyNumber.jl? Is much/any of the code copied from Humanize or is it a from-scratch rewrite?

**Comment by RedPointyJackson** [comment]
Yes, it should pass. I had it enabled and passing a while ago, but after renaming the repo with a `.jl` at the end I guess I have "broken" it. The code isn't based on Humanize at all, I wasn't even aware of it existing when I wrote the package.

**Pull request merged**
