### PR TITLE
Register VSL

### PR DESCRIPTION
**Pull request by sunoru**

### CODE REVIEW

**Comment by tkelman** [comment]
Is VSL always a part of MKL? I guess we have the precedent of acronyms with VML.jl already.

**Comment by sunoru** [comment]
Yeah. VSL and VML are both common libraries in MKL for different use...

**Comment by tkelman** [comment]
Oh, could you please push the git tag to the package so it shows up under https://github.com/sunoru/VSL.jl/releases? Thanks!

**Comment by sunoru** [comment]
Ah I forgot. Done.

**Pull request merged**
