### PR TITLE
Update requires to guard against CxxWrap API change

### PR DESCRIPTION
**Pull request by jstrube**

### CODE REVIEW

**Comment by tkelman** [comment]
could you do these all in a single PR so it's possible to look at the changes all at once? just make multiple edits within a single branch

**Comment by jstrube** [comment]
Wasn't sure what level of granularity was preferred.
I've edited all versions requiring julia 0.5 in this request and closed the others.

**Comment by tkelman** [comment]
Thanks, this is preferable for requires changes. Ref

> be aware that for upper bounds to be effective, they'll likely need to be retroactively added to past versions' require files in metadata - otherwise Pkg could choose to downgrade LCIO in order to upgrade CxxWrap

this also applies to the earlier tags

**Comment by jstrube** [comment]
OK. I was mis-interpreting the `julia 0.4` req as `julia 0.4 0.5-`, and CxxWrap 0.1.5 was the last one compatible with julia 0.4, so I thought that was safe, but of course I was wrong.
"Fixed" now.
What's good practice for removing outdated releases?

**Comment by tkelman** [comment]
I'd avoid the trailing dash on the upper bounds, since upper bounds are exclusive and that would rule out the very first prerelease after 0.4 branched.

**Comment by jstrube** [comment]
ok. makes sense.
Thanks for the careful checking. It's reassuring to know how much quality checking the julia packages go through.

**Pull request merged**
