### PR TITLE
Tag IntervalRootFinding.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIntervals/IntervalRootFinding.jl](https://github.com/JuliaIntervals/IntervalRootFinding.jl)
Release: [v0.2.0](https://github.com/JuliaIntervals/IntervalRootFinding.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIntervals/IntervalRootFinding.jl/builds/348715949)
Diff: [vs v0.1.1](https://github.com/JuliaIntervals/IntervalRootFinding.jl/compare/60813ab471ebdb423106d6cea1d825bbefdabc06...99cfcd15ed24c767627d382100f8872d5231382c)
`requires` vs v0.1.1: 
```diff
--- 0.1.1/requires
+++ 0.2.0/requires
@@ -1,3 +1,5 @@
-julia 0.5
-IntervalArithmetic 0.9
+julia 0.6
+IntervalArithmetic 0.12
 ForwardDiff 0.3
+StaticArrays 0.5
+Polynomials
```
cc: @dpsanders

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please merge this. We will update ValidatedNumerics.jl in due course.

**Comment by andreasnoack** [comment]
This breaks `ValidatedNumerics`

**Comment by andreasnoack** [comment]
Sorry. Missed your comment.

**Comment by dpsanders** [comment]
Thanks!

**Pull request merged**
