### PR TITLE
Tag Homebrew v0.4.0

### PR DESCRIPTION
**Pull request by staticfloat**
Just for you, @IainNZ ;)

Fixes "`xz` operation already underway" issues.

### CODE REVIEW

**Comment by tkelman** [comment]
metadata is frozen for julia 0.3, so best to drop julia 0.3 support and tag this as 0.4.0

**Comment by staticfloat** [comment]
Done

**Comment by tkelman** [comment]
needs to be a new package minor version

**Comment by tkelman** [comment]
and should make the require (and ci matrix) changes in the repo itself so they get included in future tags

**Comment by staticfloat** [comment]
Ah, I thought you meant "tag this for 0.4.0".  I see what you meant now.

**Pull request merged**
