### PR TITLE
Register Suppressor [https://github.com/Ismael-VC/Suppressor.jl.git]

### PR DESCRIPTION
**Pull request by Ismael-VC**
Continuation of: https://github.com/JuliaLang/METADATA.jl/pull/6635

Sorry @tkelman

### CODE REVIEW

**Comment by Ismael-VC** [comment]
@tkelman I think I've got the hang of this, sadly PkgDev is unusable on Windows at the moment but I learned how to do everything manually.

Please let me know if there is something else that I need to do in order for this to be merged.

Thanks for everything!

**Comment by tkelman** [comment]
probably best to remove all but the most recent tag here

**Comment by Ismael-VC** [comment]
Thanks for you input I will certainly do that.

**Comment by Ismael-VC** [comment]
@tkelman I've just updated the PR, finally everything seems to be in order, I'll be paying attention to any further notice, thanks again.

**Pull request merged**
