### PR TITLE
Register Jute [https://github.com/fjarri/Jute.jl.git]

### PR DESCRIPTION
**Pull request by fjarri**

### CODE REVIEW

**Comment by tkelman** [comment]
You'll need to tag a version.

**Comment by fjarri** [comment]
My bad, done that right after I saw the error. The Julia manual tells you to first register and then tag, it got me confused.

**Comment by fjarri** [comment]
So, do I need to create a new PR? Or you can re-run the checks on this one?

**Comment by tkelman** [comment]
you need to push a new commit to this one that includes the tag, or make a new pr that does. I recommend using https://github.com/attobot/attobot

**Comment by fjarri** [comment]
Ok, thanks, let me recreate it then.

**Pull request closed without merging**
