### PR TITLE
Update url

### PR DESCRIPTION
**Pull request by jbrea**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Was this discussed with the author at all? Is there any background to know on this? It looks like you just forked the package and then decided to take it, but the original author might be unresponsive?

**Comment by jbrea** [comment]
Yes, @nowozin did not respond (see [here](https://github.com/nowozin/ArcadeLearningEnvironment.jl/issues/8)), which is why I decided to fork it. What is the preferred approach to deal with such situations?

**Comment by nowozin** [comment]
Hi,

Sorry for being unresponsive.
I am happy to give you ownership of the repository if you want to maintain
it.

Sebastian

**Comment by jbrea** [comment]
Thanks a lot!

**Pull request merged**
