### PR TITLE
Tag Logging v0.3.0

### PR DESCRIPTION
**Pull request by kmsquire**
* Drop v0.3 support
* Add support for logging to syslog
* Enable precompilation

https://github.com/kmsquire/Logging.jl

### CODE REVIEW

**Comment by ararslan** [comment]
Dropping 0.3 support requires bumping the minor version rather than the patch; that's why Travis is failing.

**Comment by kmsquire** [comment]
Thanks, forgot that. Will fix tomorrow.

**Comment by kmsquire** [comment]
Fixed, thanks for the heads up @ararslan!

**Comment by tkelman** [comment]
This probably shouldn't export `log` ? Looks like it broke RobustLeastSquares, cc @andyferris http://pkg.julialang.org/logs/RobustLeastSquares_0.4.log

**Comment by andyferris** [comment]
Yes `log` for "logarithm", please :)

**Comment by kmsquire** [comment]
#6726

**Comment by kmsquire** [comment]
(Thanks for the heads up!)

**Pull request merged**
