### PR TITLE
Register new package Eirene.jl v0.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Eetion/Eirene.jl](https://github.com/Eetion/Eirene.jl)
Release: [v0.0.0](https://github.com/Eetion/Eirene.jl/releases/tag/v0.0.0)
Travis: [Travis Build Status](https://travis-ci.org/Eetion/Eirene.jl/builds/367348921)
cc: @Eetion

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@Eetion This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
From the log
```julia
ERROR: LoadError: Eirene: version 0.0.0 no longer allowed (>= 0.0.1 needed)
```

**Comment by Eetion** [comment]
Thanks for the note - I thought I had fixed this issue by creating a new release with tag v0.0.1.  That seems to have opened a new pull request (you can see both on https://github.com/JuliaLang/METADATA.jl/pulls).  What might be the best way to proceed?

**Comment by andreasnoack** [comment]
That's fine. I'll just close this one.

**Comment by Eetion** [comment]
Thanks!

**Pull request closed without merging**
