### PR TITLE
Ignore upstream tags that don't start with v

### PR DESCRIPTION
**Pull request by ararslan**
This should address the issue noted in #6636.

### CODE REVIEW

**Comment by tkelman** [comment]
could go in the regex, couldn't it?

**Comment by ararslan** [comment]
I'd have to reproduce `Base.VERSION_REGEX` but change `v?` to `v`... This is the approach that PkgDev uses, which is why I chose it. I can do whatever's best though.

**Comment by tkelman** [comment]
I meant the `r"^\w+\trefs/tags/([^\^]+)(\^{})?$"` regex

**Comment by ararslan** [comment]
Oh, that's a good idea. I'll do that.

**Pull request merged**
