### PR TITLE
Tag StaticArrays.jl v0.10.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArrays/StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl)
Release: [v0.10.0](https://github.com/JuliaArrays/StaticArrays.jl/releases/tag/v0.10.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArrays/StaticArrays.jl/builds/453305584)
Diff: [vs v0.9.2](https://github.com/JuliaArrays/StaticArrays.jl/compare/1683f798e0dcb8725768407053a45ae48434fed7...a46d711c568e4a42b755947267b6297c5ea8913c)
`requires` vs v0.9.2: no changes
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by timholy** [comment]
The JuliaCIBot run seems to be borked.

**Comment by andreasnoack** [comment]
The BEAST regression looks genuine. The rest seems spurious.

**Comment by andreasnoack** [comment]
@krcools Notice that it looks like this release affects BEAST so you might want to add an upper bound on StaticArrays on the existing releases here in METADATA.

**Comment by timholy** [comment]
xref #19688

**Pull request merged**
