### PR TITLE
Tag ApproxFun v0.7.1 [https://github.com/JuliaApproximation/ApproxFun…

### PR DESCRIPTION
**Pull request by dlfivefifty**
….jl]

Diff vs v0.7.0: https://github.com/JuliaApproximation/ApproxFun.jl/compare/a4141f6562eec07ec85752af355e744bf1a3a5f7...e33dceb4dd7dd4b4bcbd6b62014c5c46e030b5ba

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like this will break `SingularIntegralEquations`. Is that okay? Also, please consider using https://github.com/attobot/attobot next time you make a release.

**Comment by dlfivefifty** [comment]
I'll tag SingularIntegralEquations.jl as soon as the tests pass.

I'm happy to use attobot (I didn't realize it was preferable to PkgDev)

**Comment by dlfivefifty** [comment]
(This is because SingularIntegralEquations.jl uses unexported behaviour of ApproxFun, so it always breaks.)

**Comment by ChrisRackauckas** [comment]
Merging since @dlfivefifty said that failure is okay.

**Pull request merged**
