### PR TITLE
Tag Planets.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [dcarrera/Planets.jl](https://github.com/dcarrera/Planets.jl)
Release: [v0.4.0](https://github.com/dcarrera/Planets.jl/releases/tag/v0.4.0)
Diff: [vs v0.2.0](https://github.com/dcarrera/Planets.jl/compare/2f29426688374b96708a7b734123abb0944fa756...00cd4ae5a2522a5531b530d67aae2371b1083d12)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.4.0/requires
@@ -1,4 +1,4 @@
-julia 0.7
+julia 1.0
 DataFrames
 Missings
-CSV
+CSV 0.4.2
```
cc: @dcarrera

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dcarrera** [comment]
JuliaCIBot seems to be stuck. What do I do?

**Comment by dcarrera** [comment]
Ok, so JuliaCIBot just said that the tests failed. But the test for Julia 1.0 doesn't have any error messages, and the test for Julia 0.7 has an error for some other package:

```
----------STDERR----------
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /home/jrun/Planets/.julia/packages/StatsBase/56Djy/src/statmodels.jl:227.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/StatsBase/56Djy/src/statmodels.jl:227
```

Furthermore, why did JuliaCIBot even try to test against Julia 0.7 when the requirements explicitly say Julia 1.0 or above? I don't want to support Julia 0.7.

Help?

**Comment by dcarrera** [comment]
I can't figure out what's happening. I can't even seen an error message. When I click on "Details" next to JuliaCIBot, under "Julia 1.0.0 > New" there is a link that says "Fail". When I click on that, all I see is an XML file some JavaScript and some random-looking IDs, but no error message. Help?

**Comment by andreasnoack** [comment]
It looks like you don't have enabled Travis testing. Please enable that as the first thing to see if tests pass on Travis.

**Comment by dcarrera** [comment]
How do I enable Travis testing? I'm not 100% familiar with the process of making Julia packages.

**Comment by andreasnoack** [comment]
See https://docs.travis-ci.com/user/languages/julia/ and the references there.

**Comment by dcarrera** [comment]
Thanks. I think I've done everything I need to do to enable Travis. I signed up to Travis-ci.com with my GitHub account, I activated / selected the Planets.jl repository, and I added a .travis.yml file with the following contents:

```
language: julia
julia:
  - 1.0
```

I have not setup codecov or coveralls since those seem to be optional. Right now I just want to get something working. So I think I'm set. Do I need to make a new release now?

**Comment by andreasnoack** [comment]
You'd have to go through all the steps in https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci and please also add the test badge to your README.md. I might be useful to look at how other Julia packages do this.

**Comment by dcarrera** [comment]
Ok. I think that I **now** got everything working and followed all the steps. All the tests pass on Travis, and I've added a test badge to the README.md file. I've gone ahead and made a new release. I'm hopeful that that one will pass.

**Pull request closed without merging**
