### PR TITLE
Register new package POD.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lanl-ansi/POD.jl](https://github.com/lanl-ansi/POD.jl)
Release: [v0.1.0](https://github.com/lanl-ansi/POD.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/lanl-ansi/POD.jl/builds/466639879)
cc: @kaarthiksundar

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@kaarthiksundar This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by ccoffrin** [comment]
@andreasnoack, can we get a CI restart on this one?

**Comment by andreasnoack** [comment]
It looks like Travis is currently having issues, see https://www.traviscistatus.com, so I'll wait a bit before restarting.

**Comment by dpsanders** [comment]
Could the package name be more self explanatory, and preferably avoid abbreviations?

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
