### PR TITLE
Tag HierarchicalMatrices.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMatrices/HierarchicalMatrices.jl](https://github.com/JuliaMatrices/HierarchicalMatrices.jl)
Release: [v0.1.1](https://github.com/JuliaMatrices/HierarchicalMatrices.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMatrices/HierarchicalMatrices.jl/builds/370688021)
Diff: [vs v0.1.0](https://github.com/JuliaMatrices/HierarchicalMatrices.jl/compare/a1c493292f9228df0118b5ac991be83af38d01a1...1d47682700a748c58251ee29422d04b7c4d5c42f)
`requires` vs v0.1.0: no changes
cc: @MikaelSlevinsky

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
That's an interesting new feature of JuliaCIBot to forward-test package dependencies.

I'm working on a tag for FastTransforms, too, but I may have tagged this prematurely.

**Comment by MikaelSlevinsky** [comment]
Tag deleted.

**Comment by MikaelSlevinsky** [comment]
I hope this tag and the two version tags of `FastTransforms.jl` can be deciphered:

https://github.com/JuliaLang/METADATA.jl/pull/14399, `FastTransforms.jl` v0.3.1 only works with `HierarchicalMatrices.jl` v0.1, excluding v0.1.1
https://github.com/JuliaLang/METADATA.jl/pull/14400, `FastTransforms.jl` v0.3.2 only works with `HierarchicalMatrices.jl` v0.1.1

**Comment by andreasnoack** [comment]
To avoid breakage, you'd have to put an upper bound on `HierarchicalMatrices` for all previous versions of `FastTransforms` in METADATA. Otherwise, the package manager will just pick, say version 0.3.0 which isn't compatible with `FastTransforms`. See https://github.com/JuliaLang/METADATA.jl/pull/14123/files for an example of how this is done.

**Comment by MikaelSlevinsky** [comment]
How do we get the JuliaCIBot to run again? It should pass now that FastTransforms has upper bounded HierarchicalMatrices in #14929.

**Comment by andreasnoack** [comment]
Please try to remove the tag and reapply it again. That can also be used as a way to rerun the tests in case we forget to close and reopen.

**Pull request merged**
