### PR TITLE
Register new package DataFitting.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [gcalderone/DataFitting.jl](https://github.com/gcalderone/DataFitting.jl)
Release: [v0.1.0](https://github.com/gcalderone/DataFitting.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/gcalderone/DataFitting.jl/builds/423085562)
cc: @gcalderone

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@gcalderone This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider deleting the project file for the time being as it breaks CIBot.

**Comment by gcalderone** [comment]
If I delete the project.toml how can I specify the v1.0 dependencies (such as `Printf` and `Statistics`)?

**Comment by andreasnoack** [comment]
You don't have to specify them.

**Comment by gcalderone** [comment]
Will other users be able to use my package if I delete Project.toml? 
i.e. will Julia automatically download the dependencies even if they are not specified at all?
If so, how will julia find the exact version I'm relying on?

**Comment by andreasnoack** [comment]
> Will other users be able to use my package if I delete Project.toml?

Yes. Of course. I wouldn't ask you to do this if it wouldn't work. The basis of the Registry is still the REQUIRE file. Eventually, this will change but it is still the case so what matters is what you have in your REQUIRE file.

**Comment by gcalderone** [comment]
Sorry, I'm rather new to Pkg3 stuff...
Are you saying that I should insert the v1.0 dependencies in `REQUIRE` ?

My package is supposed to work both with julia v0.6 and 0.7/1.0. What will happen if a user is still using Julia v0.6?

**Comment by andreasnoack** [comment]
The stdlib dependencies `Test`, `Printf`, and `Statistics` don't have to be specified in the REQUIRE file. You should be able to just delete the `Project.toml` file and nothing more. CI should tell you if that is not the case.

**Comment by gcalderone** [comment]
Ok, thank you very much for your explanations.
I will delete the release and recreate it, then attobot should do the rest....

**Pull request merged**
