### PR TITLE
Tag Currencies.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaFinance/Currencies.jl](https://github.com/JuliaFinance/Currencies.jl)
Release: [v0.6.0](https://github.com/JuliaFinance/Currencies.jl/releases/tag/v0.6.0)
Diff: [vs v0.5.1](https://github.com/JuliaFinance/Currencies.jl/compare/a41d231d8d3db068e195df5d2cee71b4de9979b7...cd71b1586c3456c450efee00879664625fe28acd)
`requires` vs v0.5.1: no changes
cc: @TotalVerb

### CODE REVIEW

**Comment by TotalVerb** [comment]
This release does not introduce any new features; it is mostly a change to internals. However there is one breaking change:

## Breaking User-Visible Changes

- The `.val` field of `Monetary` has changed in type. Accessing this field is not recommended.

**Comment by tkelman** [comment]
Was there a travis failure here that someone restarted?

**Comment by TotalVerb** [comment]
Do you mean on the repository, or here on METADATA.jl?

**Comment by tkelman** [comment]
on metadata

**Pull request merged**
