### PR TITLE
Tag Hecke.jl v0.4.4

### PR DESCRIPTION
**Pull request by attobot**
Repository: [thofma/Hecke.jl](https://github.com/thofma/Hecke.jl)
Release: [v0.4.4](https://github.com/thofma/Hecke.jl/releases/tag/v0.4.4)
Travis: [Travis Build Status](https://travis-ci.org/thofma/Hecke.jl/builds/359405127)
Diff: [vs v0.4.3](https://github.com/thofma/Hecke.jl/compare/97c7babdcfbe01ed6275f0c210de1e837d5d726a...0e6f364f0831ce4e3057e0bb329540f213b68e43)
`requires` vs v0.4.3: 
```diff
--- 0.4.3/requires
+++ 0.4.4/requires
@@ -1,2 +1,2 @@
 julia 0.6
-Nemo 0.7.5 0.8.2
+Nemo 0.8.2
```
cc: @thofma

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by thofma** [comment]
I cannot reproduce this error locally. With a clean package directory I did (in the METADATA repository)
```
git fetch origin pull/14016/head:Hecke/v0.4.4
git checkout Hecke/v0.4.4 
```
and then
```
Pkg.add("Hecke"); Pkg.test("Hecke");
```
Is the JuliaCIBot doing something else?

**Comment by andreasnoack** [comment]
I'm wondering if https://github.com/wbhart/Nemo.jl/blob/718193c2888dc50582e2aa2e32507c070b735e3e/src/flint/FlintTypes.jl#L2302-L2308 is really safe. Passing `struct` with mutable struct fields to C isn't described in the documentation to my knowledge and the error could be explained by the `base_ring` field not being appropriately populated.

**Comment by thofma** [comment]
The C code does not touch the `base_ring` field. Could you close/open this PR?

**Comment by simonbyrne** [comment]
What was the problem?

**Comment by andreasnoack** [comment]
I don't know how it happened but see https://travis-ci.org/JuliaLang/METADATA.jl/builds/359783997 and https://travis-ci.org/JuliaLang/METADATA.jl/builds/359732152

**Comment by simonbyrne** [comment]
Hmm, no idea what happened.

**Comment by thofma** [comment]
Don't know.

**Pull request closed without merging**
