### PR TITLE
Pull request/dc1feea3

### PR DESCRIPTION
**Pull request by joshday**
Adding package for Average Shifted Histograms.

### CODE REVIEW

**Comment by IainNZ** [comment]
Please see [the guidelines for package names](http://docs.julialang.org/en/latest/manual/packages/#guidelines-for-naming-a-package)

**Comment by milktrader** [comment]
R has a package named ash, but I would put my vote for naming it `AverageShiftedHistograms`

**Comment by joshday** [comment]
Agreed.  I'm changing the name to AverageShiftedHIstograms.

**Comment by milktrader** [comment]
Great!

**Pull request closed without merging**
