### PR TITLE
SerialLib

### PR DESCRIPTION
**Pull request by windcoon**
I created a quick SerialLib, to communicate with an AVR or Arduino. It is based on rennis250 ones.

### CODE REVIEW

**Comment by milktrader** [comment]
Is Arduino.jl abandoned?

**Comment by ViralBShah** [comment]
Would be nice to merge efforts with the arduino.jl package eventually.

**Comment by windcoon** [comment]
I have created a pull request for Arduino.jl from my fork branch, I changed the function names to the original ones back.

**Comment by milktrader** [comment]
Correct me if I'm wrong but this appears to be a fork of Arduino.jl and simply renamed SerialLib.jl. Did you add functionality to Arduino.jl that was not supported or is it a more substantial redo of the package?

**Comment by IainNZ** [comment]
It looks like just a fork with some weird tweaks, like adding the TravisCI badge for METADATA.jl to the README...

**Comment by IainNZ** [comment]
Hah also, amazingly, took @rennis250 out of the license and put himself in instead

**Comment by milktrader** [comment]
Hmmm perhaps we revert this and discuss it a bit more.

**Pull request merged**
