### PR TITLE
Tag NamedArrays.jl v0.9.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidavdav/NamedArrays.jl](https://github.com/davidavdav/NamedArrays.jl)
Release: [v0.9.2](https://github.com/davidavdav/NamedArrays.jl/releases/tag/v0.9.2)
Travis: [Travis Build Status](https://travis-ci.org/davidavdav/NamedArrays.jl/builds/444202026)
Diff: [vs v0.9.1](https://github.com/davidavdav/NamedArrays.jl/compare/162aa3df705ec4bf841ac0a35e66a704f6d934d1...8ab1e80135b64ef96cb5e83a375700b300957d8a)
`requires` vs v0.9.1: no changes
cc: @davidavdav

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Comment by diegozea** [comment]
@andreasnoack I guess this has not been merged because of the fails in JuliaCIBot:
https://s3.ap-south-1.amazonaws.com/juliarun-ci/9b943bc8543a958681295ca85eba6775683631d7/NamedArrays_reverse_dependency_tests.html
Could it be a problem in the JuliaCIBot? Because this NamedArrays version works well with my PairwiseListMatrices package that it's failing there. Also, this tag solves an error in MIToS master (I'm preparing it for Julia 1.0)
cc: @davidavdav 
Best regards,

**Comment by andreasnoack** [comment]
It does indeed look like a network issue. @davidavdav Could you please remove the tag and make release again? Please also verify that CIBot tests pass.

**Comment by davidavdav** [comment]
Hi, I really appreciate all the automatic release features, but I don't really understand them yet that well.  I released the v0.9.2 again, but I have no control over CIbot.

**Comment by andreasnoack** [comment]
There a links to the docs in the PR and you can trigger a new run be removing creating the release again.

**Pull request closed without merging**
