### PR TITLE
Tag BeaData v0.0.3

### PR DESCRIPTION
**Pull request by stephenbnicar**
Updated documentation.

### CODE REVIEW

**Comment by tkelman** [comment]
push the git tag so it shows up at https://github.com/stephenbnicar/BeaData.jl/releases

**Comment by stephenbnicar** [comment]
Done.

**Comment by tkelman** [comment]
readstring will error on 0.4 unless you use Compat or similar

**Comment by stephenbnicar** [comment]
I added `Compat 0.7.9` to my REQUIRE

**Comment by tkelman** [comment]
just `using Compat` is enough for readstring, it's a renamed function not a syntax rewrite

**Comment by stephenbnicar** [comment]
Ok got it.  Thanks a lot for your help. I pushed the changes to the package and moved the git v0.0.3 tag to the most recent commit.  I made the appropriate changes to the METADATA `requires` and `sha1` files and pushed a new commit to the PR.

**Comment by tkelman** [comment]
Should probably warn or something when the tests fail in a try catch and nothing actually runs.

**Pull request merged**
