### PR TITLE
Register new package Dispatcher.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [invenia/Dispatcher.jl](https://github.com/invenia/Dispatcher.jl)
Release: [v0.1.0](https://github.com/invenia/Dispatcher.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/invenia/Dispatcher.jl/builds/223341495)
cc: @iamed2

### CODE REVIEW

**Comment by quinnj** [comment]
Looks cool!

**Comment by iamed2** [comment]
Thanks!

**Comment by sbromberger** [comment]
Very neat - and thanks for using LightGraphs. If you need anything or run into issues, please let us know. (We've got some major changes in v0.8 and the upcoming v0.9.)

**Comment by iamed2** [comment]
Sure thing! Already using LightGraphs 0.8 for Julia 0.6 :) I think you have plans that might obsolete some of the NodeSet code in DIspatcher, which is nice.

**Comment by sbromberger** [comment]
@iamed2 what functionality is that, specifically? We can chat about it on gitter or over at LG issues.

**Pull request merged**
