### PR TITLE
Register new package MichiganAutonomousVehicles.jl v0.0.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMPC/MichiganAutonomousVehicles.jl](https://github.com/JuliaMPC/MichiganAutonomousVehicles.jl)
Release: [v0.0.5](https://github.com/JuliaMPC/MichiganAutonomousVehicles.jl/releases/tag/v0.0.5)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMPC/MichiganAutonomousVehicles.jl/builds/391504448)
cc: @huckl3b3rry87

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@huckl3b3rry87 This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by huckl3b3rry87** [comment]
This one should be good to go!

Thanks!

**Comment by huckl3b3rry87** [comment]
@andreasnoack thanks for the feedback. I fixed it now

**Comment by andreasnoack** [comment]
Great. I'll suggest that you remove the v0.0.5 and v0.0.5.1 commits and reapply v0.0.5. Then there'll be a Travis build that corresponds to the release in a representative setting. However, I still see Ipopt in your .travis.yml. Why is that needed?

**Comment by huckl3b3rry87** [comment]
@andreasnoack since the package needs to use Ipopt to do the tests and unless something changed, it needs to build it first. This is how I do it in NLOptControl as well https://github.com/JuliaMPC/NLOptControl.jl/blob/master/.travis.yml

**Comment by huckl3b3rry87** [comment]
Hmm. I thought that moving the tag would take care of that. I will just draft another release if that is ok. So, please close this

**Comment by andreasnoack** [comment]
You should add a `test/REQUIRE` file to specify test dependencies. Then it will be installed and built automatically regardless of the testing platform.

**Comment by huckl3b3rry87** [comment]
@andreasnoack I was actually able to remove the dependency on Ipopt since NLOptControl.jl already has it. Previously I still had to build Ipopt but this is no longer the case.

I moved the tag to a new version 0.1.1 and there is a .traivs build https://travis-ci.org/JuliaMPC/MichiganAutonomousVehicles.jl corresponding to this. Is there anything else that you would like me to do? Thanks

**Comment by huckl3b3rry87** [comment]
Ok, to make things simple I just made another release
https://github.com/JuliaLang/METADATA.jl/pull/15186

So, hopefully, we can just close this and merge the pull request from the above link.

Thanks!

**Pull request closed without merging**
