### PR TITLE
ArbFloats v0.1.8

### PR DESCRIPTION
**Pull request by JeffreySarnoff**

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
I tried your suggestion -- and missed something. This has the last tag only, by force.

**Comment by JeffreySarnoff** [comment]
.... arrgh

**Comment by tkelman** [comment]
Do not delete the existing tags that are present in JuliaLang/METADATA, those have already been published! This went wrong because it was opened from your metadata-v2 branch.

**Comment by JeffreySarnoff** [comment]
jas@jas ~/.julia/v0.5/ArbFloats $ git checkout -b arbfloats-newbranch
Switched to a new branch 'arbfloats-newbranch'
jas@jas ~/.julia/v0.5/ArbFloats $ git cherry-pick c140513de6a29d074677513235dd2ccb929d0eb3
fatal: bad object c140513de6a29d074677513235dd2ccb929d0eb3
jas@jas ~/.julia/v0.5/ArbFloats $ git status
On branch arbfloats-newbranch

**Comment by JeffreySarnoff** [comment]
c140513de6a29d074677513235dd2ccb929d0eb3

**Comment by JeffreySarnoff** [comment]
I did not expect the "bad object" message -- what happened

**Comment by tkelman** [comment]
need add a remote for your github fork and fetch from it
```
git remote add JeffreySarnoff https://github.com/JeffreySarnoff/METADATA.jl
git fetch JeffreySarnoff
git checkout -b arbfloats-newbranch || git checkout arbfloats-newbranch
git cherry-pick c140513
git push JeffreySarnoff arbfloats-newbranch
```

**Comment by JeffreySarnoff** [comment]
that seemed to work -- closing this opening from the newbranch

**Comment by JeffreySarnoff** [comment]
LoadError: ArgumentError: invalid version string: v0,1,7
how do I kill that bad version string?

**Pull request closed without merging**
