### PR TITLE
Tag OptimTestProblems.jl v1.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/OptimTestProblems.jl](https://github.com/JuliaNLSolvers/OptimTestProblems.jl)
Release: [v1.2.0](https://github.com/JuliaNLSolvers/OptimTestProblems.jl/releases/tag/v1.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaNLSolvers/OptimTestProblems.jl/builds/342214558)
Diff: [vs v1.1.0](https://github.com/JuliaNLSolvers/OptimTestProblems.jl/compare/3024c558c0d1b3f2fa448928a14ae446133bb2a9...a0d046486a53cd84c49e6810169b50b992203dcb)
`requires` vs v1.1.0: no changes
cc: @anriseth

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by anriseth** [comment]
> ERROR: LoadError: packages with unsatisfiable requirements found:
>    BioEnergeticFoodWebs v0.3.0 – no valid versions exist for package DiffEqUncertainty
>    BioEnergeticFoodWebs v0.3.1 – no valid versions exist for package DiffEqUncertainty

Hmm. What's wrong with Travis here? OptimTestProblems shouldn't have anything to do with either of these packages.

**Comment by andreasnoack** [comment]
I think one of the DiffEq PRs has broken METADATA. cc @ChrisRackauckas

**Comment by anriseth** [comment]
Can you give this another try now, please?

**Comment by anriseth** [comment]
Thanks :)

**Pull request merged**
