### PR TITLE
Register new package BoxCoxTrans.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [tk3369/BoxCoxTrans.jl](https://github.com/tk3369/BoxCoxTrans.jl)
Release: [v1.0.0](https://github.com/tk3369/BoxCoxTrans.jl/releases/tag/v1.0.0)
cc: @tk3369

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@tk3369 This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by ararslan** [comment]
I would recommend spelling out the word "transformations" in the package title.

**Comment by dpsanders** [comment]
Maybe this package can be combined with the YeoJohnson package in a statistical transformations package?

**Comment by tk3369** [comment]
Decent suggestions.... let me think about how to combine them this coming weekend.

**Comment by tk3369** [comment]
@dpsanders what other statistical transformations can you think of?  Just wondering what else can be added.

**Comment by andreasnoack** [comment]
Closing since the PR has had no activity for a month and we'll now switch to using https://github.com/JuliaComputing/Registrator.jl for package registrations. Please reopen with Registrator if you still want to make this release.

**Pull request closed without merging**
