### PR TITLE
NormalizeQuantiles: major update for julia 0.4: dropped DataArrays in favor of Nullables

### PR DESCRIPTION
**Pull request by oheil**

### CODE REVIEW

**Comment by tkelman** [comment]
Is something wrong with travis ci on your repository? Do you maybe need to re enable it?

**Comment by oheil** [comment]
It just took long to start, don't know why, maybe high load there?

**Comment by oheil** [comment]
Ah, sorry ,I now see what you mean, I check...

**Comment by oheil** [comment]
Running now.

**Pull request merged**
