### PR TITLE
Tag ImageFeatures.jl v0.0.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaImages/ImageFeatures.jl](https://github.com/JuliaImages/ImageFeatures.jl)
Release: [v0.0.3](https://github.com/JuliaImages/ImageFeatures.jl/releases/tag/v0.0.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaImages/ImageFeatures.jl/builds/424330109)
Diff: [vs v0.0.2](https://github.com/JuliaImages/ImageFeatures.jl/compare/e3e08c88bafd911744a53f3ca76793ee126e9f89...0e2ffc4c7755823db17713bf8aa9363741c88b94)
`requires` vs v0.0.2: no changes
cc: @timholy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider adding upper bounds if the package doesn't support Julia 0.7 yet.

**Comment by timholy** [comment]
It does in #17685, this is just a "last release" for 0.6 users. Still want the upper bounds?

Or I can just close this, it doesn't seem anyone was screaming for it.

**Comment by andreasnoack** [comment]
I see. In the future, it would be great if you could add the bound anyway since it will allow CIBot to pass and I'm trying to automate the merge process and that only works when tests pass.

**Comment by timholy** [comment]
:100: for automating the merge process.

**Pull request merged**
