### PR TITLE
Register RobustShortestPath, TrafficAssignment

### PR DESCRIPTION
**Pull request by chkwon**

### CODE REVIEW

**Comment by jiahao** [comment]
The URL for RobustShortestPath should be updated.

**Comment by chkwon** [comment]
jiahao: Could you tell me what is wrong with the URL for RobustShortestPath? This is my first time publishing packages. So please help.

**Comment by IainNZ** [comment]
Neat packages @chkwon - I think you should also tag a version of RobustShortestPath so people can do `Pkg.add("RobustShortestPath")` (btw, Bertsimas is my supervisor, I'll tell him that one of his papers is a Julia package :D)

**Comment by chkwon** [comment]
Thanks, @IainNZ  Please say hello to him. I've once met him when I was a student several years ago.

My Julia system was somehow messed up for tagging. I think I should open a new request. I'll close this one.

**Pull request closed without merging**
