### PR TITLE
Register new package HistogramThresholding.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [zygmuntszpak/HistogramThresholding.jl](https://github.com/zygmuntszpak/HistogramThresholding.jl)
Release: [v0.1.0](https://github.com/zygmuntszpak/HistogramThresholding.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/zygmuntszpak/HistogramThresholding.jl/builds/480681013)
cc: @zygmuntszpak

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@zygmuntszpak This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by fredrikekre** [comment]
You need to remove LinearAlgebra from REQUIRE.

**Comment by zygmuntszpak** [comment]
I've removed LinearAlgebra from REQUIRE as requested.

**Comment by fredrikekre** [comment]
Please have a look at the logs:
```
ERROR: LoadError: LoadError: Tagged version 0.1.0 of HistogramThresholding declares the package UUID to be "8e3ecc80-03f2-11e9-1267-a1d11a9abb87" in its Project file, which does not match the package's METADATA-compatible UUID "2c695a8d-9458-5d45-9878-1b8a99cf7853".
To fix this error, change the UUID to be "2c695a8d-9458-5d45-9878-1b8a99cf7853" and retag.
```

**Comment by zygmuntszpak** [comment]
We can close this issue because a newer tagged version got merged (https://github.com/JuliaLang/METADATA.jl/pull/20790).

**Pull request closed without merging**
