### PR TITLE
Register CUDD [https://github.com/sisl/CUDD.jl.git]

### PR DESCRIPTION
**Pull request by wenting-zhao**

### CODE REVIEW

**Comment by tkelman** [comment]
You'll need to tag a version

**Comment by aviks** [comment]
@wenting-zhao Could you please tag a version? This cannot be merged in its current state. Let us know if you need help with that.

**Comment by wenting-zhao** [comment]
Sorry for not getting to this soon enough.  I've just run PkgDev.tag("CUDD"), but I'm not sure how to update things on your side.  Would this be all I need to do, or do I need to create a new pull request?

**Comment by aviks** [comment]
I've restarted the build (and the queue is long, it'll take a while) so let's see. Have you tagged the same version and hash as what's on this PR? 

If that does not work, try closing this, and creating a new tag via attobot. The easiest way now to register packages these days is attobot: https://github.com/attobot/attobot

**Comment by wenting-zhao** [comment]
Did it work?  If not, I'll close this and publish the package via attobot.  Sorry for any inconvenience this may cause.

**Comment by aviks** [comment]
You can see the test results by clicking the `Details` link on the _Travis_ line. The tests still failed with `Package CUDD has no tagged versions`

Best to redo with attobot... that will be easier.

**Pull request closed without merging**
