### PR TITLE
Compatibility for v0.5

### PR DESCRIPTION
**Pull request by cormullion**

### CODE REVIEW

**Comment by tkelman** [comment]
If you enabled Travis CI, would your tests pass there?

**Comment by cormullion** [comment]
@tkelman  I'll read up about that... (I think your video at JuliaCon  might be a place to start...)

**Comment by tkelman** [comment]
Try https://travis-ci.org/cormullion/ColorSchemes.jl, the default yml file template that was already pre-generated should be good enough to start with

**Comment by cormullion** [comment]
@tkelman thanks Tony. It wasn't as painful as I thought:)

**Pull request merged**
