### PR TITLE
Pull request/0e85c955

### PR DESCRIPTION
**Pull request by krisztiankosi**

### CODE REVIEW

**Comment by tkelman** [comment]
I'd encourage converting some of your examples into tests.

**Comment by krisztiankosi** [comment]
The examples shows not just the usage of the toolbox. I want to explain with examples, how the methods working. I writing many more examples.

What do you mean on test? 
It can be mean many things:

- writing a function, which check the working of the ToolBox

**Comment by tkelman** [comment]
Mostly tests that ensure it is functioning correctly. Documentation would also be good of course.

**Comment by krisztiankosi** [comment]
thank you, I will write a short manual, but detailed  in pdf, I will add the usage type manual into Readme.md, and I will link the original article link to Readme.md (it is OA article, so anyone can read that), maybe I will create a .bib file with important articles.

**Pull request merged**
