### PR TITLE
Register new package Web3.jl v0.2.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lambda-mechanics/Web3.jl](https://github.com/lambda-mechanics/Web3.jl)
Release: [v0.2.2](https://github.com/lambda-mechanics/Web3.jl/releases/tag/v0.2.2)
cc: @zot

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@zot This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by zot** [comment]
OK, so I can't seem to get this right at the start -- after I make a change, which one am I supposed to do?

1. Move the tag
2. Edit the current release to use a new tag
3. Make a new release

???

**Comment by fredrikekre** [comment]
https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by zot** [comment]
> https://github.com/attobot/attobot#updatingdeleting-a-release

Thanks!

**Comment by zot** [comment]
See #21194 for a discussion of the name of this package

**Comment by zot** [comment]
Is this being merged?

EDIT: Not that I'm in a massive hurry, I'm just not sure how automatic/manual the process is for new projects...

**Comment by zot** [comment]
@fredrikekre is someone waiting for something from me before you merge this?

**Comment by zot** [comment]
Forgot to also tag @andreasnoack

**Comment by andreasnoack** [comment]
The trick is not to comment on the PR after you've updated it, see https://discourse.julialang.org/t/the-current-metadata-release-process/16672.

**Comment by zot** [comment]
Thanks!

**Pull request merged**
