### PR TITLE
Tag GeoStats.jl v0.1.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/GeoStats.jl](https://github.com/juliohm/GeoStats.jl)
Release: [v0.1.2](https://github.com/juliohm/GeoStats.jl/releases/tag/v0.1.2)
Diff: [vs v0.1.1](https://github.com/juliohm/GeoStats.jl/compare/fe323fbb8cb1a102be5cbcc779089299d5806ef7...7e3e98a8ef27405e64fc1959a08640f4cea27663)
`requires` vs v0.1.1: no changes
cc: @juliohm

### CODE REVIEW

**Comment by visr** [comment]
Cool new release. Not really a patch though, since it removes/renames some key functions:
https://github.com/juliohm/GeoStats.jl/compare/fe323fbb8cb1a102be5cbcc779089299d5806ef7...7e3e98a8ef27405e64fc1959a08640f4cea27663#diff-d793f98e71fbc7bb0368200bd8bf2e7bL27

**Comment by juliohm** [comment]
Thank you Martjin, I'm planning a minor release for Julia v0.6, that is
why :)

**Comment by visr** [comment]
Ok, but the METADATA version numbers should follow [semver.org](http://semver.org/), which says that a patch is backwards-compatible. So this should've been 0.2.0, then for julia v0.6 you can make 0.3.0. Version numbers are cheap ;)

**Comment by juliohm** [comment]
Thank you, I'll keep that in mind.

**Pull request merged**
