### PR TITLE
Register new package ModernRobotics.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ferrolho/ModernRobotics.jl](https://github.com/ferrolho/ModernRobotics.jl)
Release: [v0.1.0](https://github.com/ferrolho/ModernRobotics.jl/releases/tag/v0.1.0)
cc: @ferrolho

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ferrolho This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Perhaps the package name should make explicit that this for a book called "Modern Robotics"; otherwise it sounds like you are implying that other Julia robotics packages are not "modern" (which is clearly not the case; rather the opposite!)

**Comment by dpsanders** [comment]
e.g. `ModernRoboticsBook.jl`

**Comment by ferrolho** [comment]
Certainly, @dpsanders! I didn't put much effort into the naming of the package; I just went with the same name as the original library:
- https://github.com/NxRLab/ModernRobotics
- https://github.com/Le0nX/ModernRoboticsCpp

I will change it to `ModernRoboticsBook.jl`.

Question: Should I just create a new tag and let `attobot` take care of it? Will that not create a new and separate PR?

Thanks for the feedback! :+1:

**Comment by dpsanders** [comment]
Yes it will be a separate PR. This one will then be closed by a human.

**Comment by ferrolho** [comment]
New release: [ModernRoboticsBook.jl/releases/tag/v0.1.1](https://github.com/ferrolho/ModernRoboticsBook.jl/releases/tag/v0.1.1)

This PR can now be closed. Thank you, @dpsanders.

Link to the new automated PR: https://github.com/JuliaLang/METADATA.jl/pull/21700

**Pull request closed without merging**
