### PR TITLE
Register GeoStatsImages

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by juliohm** [comment]
@kmsquire could you please take care of this pull request? I renamed the package as you suggested.

**Comment by IainNZ** [comment]
@juliohm you know that without tagging a version `Pkg.add("GeoStatsImages")` won't work, as you have in your README?

**Comment by juliohm** [comment]
@IainNZ, yes, I was planning to add the tag after the package is registered, I can add it right away...

**Comment by juliohm** [comment]
@IainNZ, I tagged it. Everything else is ok?

**Comment by IainNZ** [comment]
You've managed to get a PyCall tagging commit in there somehow

**Comment by juliohm** [comment]
Ok, will close this pull request and open a new one from scratch.

**Pull request closed without merging**
