### PR TITLE
Register new package MonteCarloObservable.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [crstnbr/MonteCarloObservable.jl](https://github.com/crstnbr/MonteCarloObservable.jl)
Release: [v0.1.0](https://github.com/crstnbr/MonteCarloObservable.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/crstnbr/MonteCarloObservable.jl/builds/455207561)
cc: @crstnbr

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@crstnbr This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by carstenbauer** [comment]
Is there something left for me to do here?

**Comment by carstenbauer** [comment]
@andreasnoack: I hope it's not rude to ping you on this. This is my first attempt to register a package. I just want to know wether there is something left for me to do here.

The JuliaCIBot Tests fail, but this is due to a missing matplotlib.

**Comment by andreasnoack** [comment]
It's okay. Please consider adding something like https://github.com/tkf/IPython.jl/blob/master/test/runtests.jl#L3-L20 to handle the Python dependencies in CIBot.

**Comment by carstenbauer** [comment]
Will do, thanks for merging this!

**Pull request merged**
