### PR TITLE
Tag PlotlyJS.jl v0.8.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [sglyon/PlotlyJS.jl](https://github.com/sglyon/PlotlyJS.jl)
Release: [v0.8.3](https://github.com/sglyon/PlotlyJS.jl/releases/tag/v0.8.3)
Travis: [Travis Build Status](https://travis-ci.org/sglyon/PlotlyJS.jl/builds/327525545)
Diff: [vs v0.8.2](https://github.com/sglyon/PlotlyJS.jl/compare/7263071a248722c766ddf8d5310f30794da6ec4d...d6787523e19da447c4e9f90e49762e9aefbc33ac)
`requires` vs v0.8.2: 
```diff
--- 0.8.2/requires
+++ 0.8.3/requires
@@ -1,6 +1,6 @@
 julia 0.6
 JSON 0.7
-Blink 0.3.3
+Blink 0.3.3 0.6-
 Colors
 LaTeXStrings
 DocStringExtensions
```
cc: @sglyon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by sglyon** [comment]
ref https://github.com/sglyon/PlotlyJS.jl/releases/tag/v0.8.3 and https://github.com/sglyon/PlotlyJS.jl/issues/162

**Comment by sglyon** [comment]
Please don't merge this quite yet

I might have found a fix... I will comment here again when this should be merged (either b/c I found a fix and updated the tag, or I give up because I don't have the time right now)

**Comment by sglyon** [comment]
Ok, I did a better fix for this. Ready for review/merge

**Comment by sglyon** [comment]
Ok, I did a better fix for this. Ready for review/merge

**Comment by ChrisRackauckas** [comment]
You need to also METADATA PR to bound previous versions as well. Otherwise it may just push the version of PlotlyJS back to keep the newest Electron, which breaks your fix.

**Comment by sglyon** [comment]
I actually found a fix that doesn't require an upper bound on anything -- this should work with any version of Blink/electron

**Pull request merged**
