### PR TITLE
WavefrontOBJs package

### PR DESCRIPTION
**Pull request by ericjang**

### CODE REVIEW

**Comment by ericjang** [comment]
Oops, sorry - still trying to figure out package management. need to get rid of old commit

**Comment by timholy** [comment]
Comparison to https://github.com/JuliaIO/WavefrontObj.jl?

**Comment by ericjang** [comment]
Ah, I didn't know that package existed. It looks like that one has all the
code commented out though? I'm hesitant to provide a patch that re-writes
everything.

- Eric

**Comment by timholy** [comment]
You just might want to post an issue in that package. Assuming it's registered with FileIO, you'd also want to change the registration.

**Comment by sjkelly** [comment]
There is also: https://github.com/JuliaIO/MeshIO.jl/blob/master/src/io/obj.jl Which works for me, minus 'MTL' files, which I do not use yet. Maybe @SimonDanisch can comment? Regardless, I think merging with MeshIO would be the best way forward here!

**Comment by ericjang** [comment]
That's cool - I'm more confident in my MTL parser implementation than my OBJ parser. Let me know what I can do to help.

**Pull request closed without merging**
