### PR TITLE
Bumping Images, ImageView, Grid, Compat, Interpolations, CUDArt

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by jiahao** [comment]
Sorry @timholy, I'm trying to excise `julia 0.3-` from newly tagged versions of packages...

**Comment by timholy** [comment]
Good idea, thanks for checking. Will close and start fresh.

**Comment by jiahao** [comment]
Grazie

**Comment by IainNZ** [comment]
https://www.youtube.com/watch?v=krtnt191Drg

**Comment by timholy** [comment]
:smile:

**Pull request closed without merging**
