### PR TITLE
Pull request/aab2af0e

### PR DESCRIPTION
**Pull request by felipenoris**
Hello, I would like to contribute with this package I'm working on. You can get more details on the Readme file. Thanks.

### CODE REVIEW

**Comment by IainNZ** [comment]
Hah thats pretty neat. Looks good to merge once the light goes green.

**Comment by quinnj** [comment]
Cool stuff.

**Comment by felipenoris** [comment]
Thanks guys

**Comment by milktrader** [comment]
Nice!

**Pull request merged**
