### PR TITLE
Tag AutoGrad.jl v0.0.10

### PR DESCRIPTION
**Pull request by attobot**
Repository: [denizyuret/AutoGrad.jl](https://github.com/denizyuret/AutoGrad.jl)
Release: [v0.0.10](https://github.com/denizyuret/AutoGrad.jl/releases/tag/v0.0.10)
Travis: [Travis Build Status](https://travis-ci.org/denizyuret/AutoGrad.jl/builds/316491980)
Diff: [vs v0.0.9](https://github.com/denizyuret/AutoGrad.jl/compare/0c27dd85875a8c0cdbc9a4dd11ffbf72493ecbc2...823ea162c829402b0aaf7a7d9e4145f170fdd79b)
`requires` vs v0.0.9: 
```diff
--- 0.0.9/requires
+++ 0.0.10/requires
@@ -1,2 +1 @@
 julia 0.4
-Compat 0.8.1 # allunique
```
cc: @denizyuret

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Do you really test and support `0.4` for Autograd?

**Comment by denizyuret** [comment]
Yes.

**Comment by aviks** [comment]
Thanks @vchuravy

**Comment by omus** [comment]
Since this package requires a Julia version below the minimum Julia version it needs to be added to this list: https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/.test/list_3582.jl

**Comment by denizyuret** [comment]
It does not require it. It handles 0.4 but works fine with 0.5 and 0.6. I
can get rid of 0.4 and 0.5 if this will cause issues.

**Comment by omus** [comment]
I would consider dropping for the next minor release but the PR I made should address the issue.

**Pull request merged**
