### PR TITLE
Tag GaussianMixtureTest v0.0.4

### PR DESCRIPTION
**Pull request by panlanfeng**
Fix a bug due to typing error.

### CODE REVIEW

**Comment by aviks** [comment]
Paging @ararslan : can you figure out why the tests failed in this case please?

**Comment by ararslan** [comment]
@aviks I looked into it and I have absolutely no idea. Could you close and reopen the PR to retrigger Travis? I'm inclined to believe it was just a fluke.

**Comment by ararslan** [comment]
Yep, looks like a fluke. ¯\\\_(ツ)\_/¯

**Comment by aviks** [comment]
Yes, thanks for looking at it!

**Pull request merged**
