### PR TITLE
DevIL v0.3

### PR DESCRIPTION
**Pull request by aaalexandrov**
Fixed Julia 0.4 compatibility issues.

### CODE REVIEW

**Comment by tkelman** [comment]
If this is the first tagged version to drop support for Julia 0.3, it should change the minor package version to 0.3.0.

**Comment by aaalexandrov** [comment]
Minor version updated to 0.3

**Comment by tkelman** [comment]
can you rebase this instead of merging in unrelated commits?

**Comment by aaalexandrov** [comment]
Will close this request and create a clean one that's based properly.

**Pull request closed without merging**
