### PR TITLE
Register Celeste: v0.0.1, v0.0.2

### PR DESCRIPTION
**Pull request by jeff-regier**

### CODE REVIEW

**Comment by tkelman** [comment]
what version of julia does celeste 0.0.1 require?

**Comment by jeff-regier** [comment]
Julia 0.4, exactly (It won't work with 0.3 or 0.5). Thanks.

**Comment by tkelman** [comment]
can you add `julia 0.4` to https://github.com/jeff-regier/METADATA.jl/blob/pull-request/b0875cf6/Celeste/versions/0.0.1/requires then?

**Comment by jeff-regier** [comment]
I see. I think instead I'll just remove those tags, and open a new PR.

**Pull request closed without merging**
