### PR TITLE
Tag RoME.jl v0.1.7

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaRobotics/RoME.jl](https://github.com/JuliaRobotics/RoME.jl)
Release: [v0.1.7](https://github.com/JuliaRobotics/RoME.jl/releases/tag/v0.1.7)
Diff: [vs v0.1.6](https://github.com/JuliaRobotics/RoME.jl/compare/6113ced94a7245bec9749ce1394a28f8430dbeb5...8428bc1439e9c5074435f43f3b900863a1e198f2)
`requires` vs v0.1.6: 
```diff
--- 0.1.6/requires
+++ 0.1.7/requires
@@ -1,5 +1,5 @@
 julia 0.6
-IncrementalInference 0.3.6
+IncrementalInference 0.3.8 0.3.10
 Graphs 0.9.0
 TransformUtils 0.0.6
 CoordinateTransformations 0.5.0
```
cc: @dehann

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dehann** [comment]
Should resolve issue found in #18355.

**Comment by andreasnoack** [comment]
Does this require #18355?

**Comment by dehann** [comment]
Nope, this new RoME v0.1.7 tag "pre-emptively" fixes the issue introduced by IIF v0.3.9 in #18355.  This RoME v0.1.7 tag is a "stand-alone" tag as if it were normal development.  If you could merge this RoME v0.1.7, and then restart tests on #18355 please -- I would then expect tests to pass on #18355.  

Aside:  I'm in the process of bring Graphs, KDE, IIF, RoME, Caesar up to Julia 0.7 and 1.0.  There will likely be another few tags from these packages in the next couple of days.

Thanks for the help and double checking!

**Comment by dehann** [comment]
Oh wait -- I see now the JuliaCIBot found a different bug on the new RoME.  Let me clear that error first and then we could check to merge this PR please. Will be back here soon...

**Comment by dehann** [comment]
HI @andreasnoack , I think this should be good to go.  If you could please merge this and then restart tests on #18355 ?

**Pull request merged**
