### PR TITLE
Bump HDF5 and AxisAlgorithms

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by tkelman** [comment]
No Travis? Odd.

**Comment by timholy** [comment]
I just assumed it was a little slow to start, but more likely something odd happened.

Unless I hear otherwise, I'll just hit merge on this in the next few hours.

**Comment by tkelman** [comment]
looks fine to me, I guess we can pay attention on the off chance other unrelated PR's start mysteriously failing

**Comment by tkelman** [comment]
There was apparently an outage today on Travis' end - https://www.traviscistatus.com/

Plus it was a busy day with PR's to base, people back from the 4th I suppose

**Pull request merged**
