### PR TITLE
Tag GR v0.9.9

### PR DESCRIPTION
**Pull request by jheinen**
I tried the commands in milktrader's mail:

    Pkg.update()                # get latest METADATA
    Pkg.tag("GR", :patch)       # :patch is the default, :minor and :major are other options
    Pkg.publish()               # generates the PR for METADATA and other magical things

... but the PR failed:

    julia> Pkg.update()
    INFO: Updating METADATA...
    INFO: Updating IJulia...
    INFO: Computing changes...
    INFO: No packages to install, update or remove

    julia> Pkg.tag("GR", :patch)
    INFO: Tagging GR v0.9.9
    INFO: Committing METADATA for GR

    julia> Pkg.publish()
    INFO: Validating METADATA
    INFO: Pushing GR permanent tags: v0.9.9
    The authenticity of host 'github.com (192.30.252.131)' can't be established.
    RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
    Are you sure you want to continue connecting (yes/no)? yes
    Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

### CODE REVIEW

**Comment by milktrader** [comment]
What happens if you run `Pkg.publish()` again?

**Comment by jheinen** [comment]
... same error:

    ERROR: failed process: Process(`git --work-tree=/usr/local/lib/julia/v0.3/GR --git-dir=/usr/local/lib/julia/v0.3/GR/.git push -q origin refs/tags/v0.9.9:refs/tags/v0.9.9`, ProcessExited(128)) [128]
     in wait at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib (repeats 2 times)
     in wait at task.jl:48
     in sync_end at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
     in publish at pkg/entry.jl:319
     in anonymous at pkg/dir.jl:28
     in cd at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
     in __cd#229__ at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
     in publish at pkg.jl:57

**Comment by milktrader** [comment]
Yeah, that was a long shot. Are you logged in as a different user maybe?

**Comment by jheinen** [comment]
I added my public ssh keys to github, but I still get an error;

    julia> Pkg.publish()
    INFO: Validating METADATA
    INFO: Pushing GR permanent tags: v0.9.9
    INFO: Submitting METADATA changes
    INFO: Forking JuliaLang/METADATA.jl to jheinen
    Enter host password for user 'jheinen':
    ERROR: key not found: "token"
     in getindex at dict.jl:617
     in token at pkg/github.jl:53
     in req at pkg/github.jl:61
     in POST at pkg/github.jl:74
     in fork at pkg/github.jl:87
     in pull_request at pkg/entry.jl:292
     in publish at pkg/entry.jl:359
     in anonymous at pkg/dir.jl:28
     in cd at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
     in __cd#229__ at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
     in publish at pkg.jl:57

**Comment by wildart** [comment]
@jheinen Try to remove file `~/.julia/v0.3/.github/token`, to regenerate GitHub token. I believe there is a reference about it in documentation.

**Comment by jheinen** [comment]
... hmm. Long story:

    julia> Pkg.publish()
    INFO: Validating METADATA
    INFO: Pushing GR permanent tags: v0.9.9
    INFO: Submitting METADATA changes
    INFO: Forking JuliaLang/METADATA.jl to jheinen
    INFO: Pushing changes as branch pull-request/37c49532
    LSOpenURLsWithRole() failed with error -10810 for the URL https://github.com/jheinen/METADATA.jl/compare/pull-request/37c49532.
    ERROR: failed process: Process(`open https://github.com/jheinen/METADATA.jl/compare/pull-request/37c49532`, ProcessExited(1)) [1]
     in error at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
     in pipeline_error at process.jl:502
     in pull_request at pkg/entry.jl:298
     in publish at pkg/entry.jl:359
     in anonymous at pkg/dir.jl:28
     in cd at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
     in __cd#229__ at /usr/local/Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
     in publish at pkg.jl:57

**Comment by wildart** [comment]
Do not worry, it worked. :+1:. Last error is from OSX specific behavior when package manager tries to open PR url in browser (see in line 7 of your error dump: https://github.com/jheinen/METADATA.jl/compare/pull-request/37c49532) using `open` command. This behavior definitely should be removed in next versions.

**Comment by tkelman** [comment]
This can be closed, right?

**Pull request closed without merging**
