### PR TITLE
Register PowerModelsAnnex 

### PR DESCRIPTION
**Pull request by ccoffrin**
https://github.com/lanl-ansi/PowerModelsAnnex.jl.git: v0.0.1

This is a PowerModels extension package with a broader scope and lower quality control.  Additional details can be found in the repo's README.

### CODE REVIEW

**Comment by tkelman** [comment]
Need to push the git tag

**Comment by ccoffrin** [comment]
My bad.  Should be fixed now.

**Comment by ccoffrin** [comment]
@tkelman is this good to go?

**Comment by ccoffrin** [comment]
thanks!

**Pull request merged**
