### PR TITLE
Tag ParticleFilters.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPOMDP/ParticleFilters.jl](https://github.com/JuliaPOMDP/ParticleFilters.jl)
Release: [v0.3.0](https://github.com/JuliaPOMDP/ParticleFilters.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPOMDP/ParticleFilters.jl/builds/448661677)
Diff: [vs v0.2.0](https://github.com/JuliaPOMDP/ParticleFilters.jl/compare/c6fedcdacfd1a31543356939a734bd025eb58679...7ddf17d2abf679e4b27445551761f25c21d2a5d5)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.3.0/requires
@@ -1,4 +1,4 @@
-julia 0.6
+julia 0.7
 StatsBase
 POMDPs 0.6
 POMDPModelTools
```
cc: @zsunberg

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by zsunberg** [comment]
Seems like the failure in the JuliaCIBot tests is because imagemagick is missing. Is that ok, or is there a workaround to make it skip those tests somehow? It does pass on Travis: https://travis-ci.org/JuliaPOMDP/ParticleFilters.jl/builds/448661677

**Comment by andreasnoack** [comment]
It looks like it is a regression from the previous version. Any idea why this would happen?

**Comment by zsunberg** [comment]
The new tests include a tutorial that produces a gif using imagemagick through Reel.jl. The old tests didn't include this tutorial.

I'd like to keep the tutorial in the tests if possible. I guess ideally Reel.jl would make sure imagemagick is provided. Is there any way to have certain tests run on Travis, but not on JuliaCI?

**Comment by andreasnoack** [comment]
It looks like that test is simply skipped on Travis, see https://travis-ci.org/JuliaPOMDP/ParticleFilters.jl/jobs/448661679#L1591. There are quite a few errors on Travis but for some reason, they don't seem to be fatal.

If theory, you'd be able to skip some of the tests with something `if !(get("ENV", "TRAVIS_CI", "false") == "true") && (get(ENV, "CI", "false") == "true")` but I think it would be better to figure out if we can get this working first. Maybe adding ImageMagick.jl as test dependency is an option.

**Comment by zsunberg** [comment]
@andreasnoack thanks for the feedback. I share your desire for it to work, but I think the solution is to get Reel.jl fixed to make sure imagemagick is available https://github.com/shashi/Reel.jl/issues/15.

So for now I just disabled running those notebook tutorials on Julia CI

**Comment by zsunberg** [comment]
oh, I see you merged it, thanks!

**Pull request merged**
