### PR TITLE
Pull request/5ae7e9c2

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
I just recently saw the new packaging guidelines in the documentation. It seems to me that my package falls squarely into category 4 there, which says that non-descriptive names are ok. If that is so, I'd actually like to keep IAMF as the package name and register it. Any objections? I would still create a new pull request to avoid my merge mess, but wanted to get your feedback first.

**Comment by tkelman** [comment]
I think the implication behind "less systematic name" was more non-technical, whimsical, or distinctive proper name for the package. The acronym guideline still holds. Is this wrapping a pre-existing library called IAMF, or is it a from-scratch new implementation?

**Comment by davidanthoff** [comment]
Well, IAMF is a whimsical name. I certainly don't want to give the package a generic name because it is one of VERY many possible approaches to the topic it covers. This is a new from-scratch implementation.

**Comment by StefanKarpinski** [comment]
I'm not sure `IAMF` qualifies as whimsical. To me a whimsical name is something cute, memorable and irrelevant to what the package does – or related but only in a punny, clever way. `IAMF` seems like it's an acronym for something that I should look up and then won't remember. I'm intentionally not looking at the package so that my reaction has the purity of total ignorance.

**Comment by milktrader** [comment]
Searching the IAMF acronym I found these:

International Advanced Mobility Forum (cars; Switzerland)
International Association for Mediterranean Forests (est. 1996)
Innovation in Agribusiness Management Fund (Canada)
Institute of American Music Foundation (Provo, UT)
Inter-Agency Monitoring Form (UK)
It's All My Fault

I like the last one, wasn't expecting that to pop up.

An example of a whimsical name would be `RainForest`. When I think of rain forest, I think of lots of exotic flaura and fauna, but also I think of cattle farmers razing them and creating a mess, sort of a mixed trigger for science and policy. I'm not suggesting this name, just defining some fuzzy boundaries for creative names.

**Comment by StefanKarpinski** [comment]
You could call it `MeaCulpa` which refers to `It's All My Fault` which refers to `IAMF`. Whimsical!

**Comment by davidanthoff** [comment]
@StefanKarpinski, hehe :) I'll just not register it for now.

**Pull request closed without merging**
