### PR TITLE
Register new package DirichletMixtureModels.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [krylea/DirichletMixtureModels.jl](https://github.com/krylea/DirichletMixtureModels.jl)
Release: [v0.0.1](https://github.com/krylea/DirichletMixtureModels.jl/releases/tag/v0.0.1)
cc: @krylea

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@krylea This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please enable Travis testing for your package.

**Comment by krylea** [comment]
Enabled testing and wrote some simple tests.  Do I need to make a new release? Or can I update this one somehow?

**Comment by krylea** [comment]
I'll just delete this release and make a new one.

**Comment by andreasnoack** [comment]
It worked.

**Comment by krylea** [comment]
Hmm, this looks to me like it is still using the old boilerplate test file that fails even though I updated it on the repository before the new release. Is there anything else I need to do to fix the tests?

**Comment by krylea** [comment]
There is still some weird stuff going on with the testing, so I think I am going to try to redo the package registration from scratch.

**Comment by andreasnoack** [comment]
It looks like there is an issue outside your package. More specifically in https://github.com/JuliaStats/ConjugatePriors.jl/blob/5e281ea798d82b4b0a23f240dbe6612c35b9b6f8/src/normalwishart.jl#L43 since `isApproxSymmetric` doesn't seem to be defined anywhere. It's a bit of a detour but the best solution might be to fix and test `ConjugatePriors` first. I'd just try to use `issymmetric` instead and demand the users supply an exactly symmetric matrix.

**Comment by andreasnoack** [comment]
Closing because of no activity for a month.

**Pull request closed without merging**
