### PR TITLE
Tag Distributions.jl v0.12.4

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/Distributions.jl](https://github.com/JuliaStats/Distributions.jl)
Release: [v0.12.4](https://github.com/JuliaStats/Distributions.jl/releases/tag/v0.12.4)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/Distributions.jl/builds/221991496)
Diff: [vs v0.12.3](https://github.com/JuliaStats/Distributions.jl/compare/2540fe7f36996e474e05930bccd11d816566b3f7...7c399b6fca70112298d712d23f717a507382c28b)
`requires` vs v0.12.3: no changes
cc: @ararslan

### CODE REVIEW

**Comment by tkelman** [comment]
This caused a failure in Mads.jl, cc @montyvesselinov https://github.com/JuliaCI/pkg.julialang.org/blob/fc319be22f3dba1b2b2ed7f3f2e03fed959335b5/logs/Mads_0.5.log

**Comment by montyvesselinov** [comment]
https://github.com/JuliaStats/Distributions.jl/issues/595

**Comment by montyvesselinov** [comment]
@tkelman how to pin 0.12.3 version of Distributions in the REQUIRE file?

**Comment by tkelman** [comment]
You can add an upper bound, though if this is going to get fixed with a later release then an upper bound would no longer be necessary.

**Comment by ararslan** [comment]
Yes, we're actively working on fixing this.

**Comment by montyvesselinov** [comment]
How to impose an upper bound for a package in the REQUIRE file? Just curious.

**Comment by ararslan** [comment]
The syntax is
```
SomePackage 0.1.2 0.3.4
```
which would declare a dependency on SomePackage where the version is greater than _or equal to_ 0.1.2, and _strictly less than_ 0.3.4. That is, the lower bound is inclusive while the upper bound is exclusive.

**Comment by montyvesselinov** [comment]
Thank you very much! This worked! Maybe needs to be better explained in the
manual.

-monty

**Pull request merged**
