### PR TITLE
Tighten FixedEffectModels bound on DataFrames further

### PR DESCRIPTION
**Pull request by tkelman**
0.7.8 didn't fix the issue with reducing over an empty collection
and FixedEffectModels 0.3.0 is Julia-0.5-only
ref http://pkg.julialang.org/detail/FixedEffectModels.html

#6244 wasn't tight enough, cc @matthieugomez @ararslan and ref https://github.com/JuliaStats/DataFrames.jl/pull/1017#issuecomment-243803777

If one of the more recent DataFrames tags has fixed the issue, then we can instead loosen or remove the upper bounds, let me know.

### CODE REVIEW

**Comment by ararslan** [comment]
Shound be fixed as of DataFrames 0.8.1. The fix was introduced in https://github.com/JuliaStats/DataFrames.jl/pull/1038. However, it also includes an explicit error for a case that FixedEffectModels may be relying on working, not sure on that.

**Comment by matthieugomez** [comment]
There is a test in fixedeffectmodels checking that in a particular case, an
empty vector is returned . Since Dataframes throws an error in this case
after #1038, the function now throws an error, instead of returning an
empty vector. Therefore only a dataframes version before #1038 can pass
this test.

**Comment by ararslan** [comment]
@matthieugomez If having an empty vector is important for a use case in FixedEffectModels, you could simply wrap it in a `try`/`catch` block and handle the empty case in `catch`.

**Comment by matthieugomez** [comment]
The current version of fixedeffectmodels works around this. I think were
talking about the previously tagged version (right?)

**Comment by ararslan** [comment]
Oh sorry, my mistake.

**Comment by tkelman** [comment]
This doesn't touch FixedEffectModels 0.3.0, but since that is Julia-0.5-only, the package is still failing on Julia 0.4.

**Comment by ararslan** [comment]
Does tightening to DataFrames 0.7.7 fix it on Julia 0.4?

**Comment by tkelman** [comment]
I can't remember if I tested this earlier, but just did on this METADATA branch and it passed with DataFrames 0.7.6.

**Comment by ararslan** [comment]
Nice. Looks good to me, then.

**Comment by tkelman** [comment]
This may downgrade DataFrames further for people who have FixedEffectModels installed, so @matthieugomez if it's at all possible to backport some of the fixes and release an 0.4-compatible 0.2.3 version from a branch that could work with the latest DataFrames versions, that would be useful.

**Pull request merged**
