### PR TITLE
GeoEfficiency tag v0.7.8

### PR DESCRIPTION
**Pull request by DrKrar**
better looking and coherent documentation

### CODE REVIEW

**Comment by tkelman** [comment]
could you rebase out the merge commit?

**Comment by DrKrar** [comment]
sorry for the inconvenient,
I had tried 
git rebase --onto metadata-v2
but I can not see any change happen here.
so I thnk i need a little help with rebasing.

**Comment by tkelman** [comment]
Check with `git remote -v` that the `origin` remote is JuliaLang, then do `git fetch --all`, and when you rebase it should be relative to `origin/metadata-v2`

**Comment by DrKrar** [comment]
Great, thanks for your help.

**Comment by tkelman** [comment]
You've added more merge commits here. You probably needed to force push to this branch after rebasing.

**Comment by DrKrar** [comment]
I did not make it.
I think i should remove this PR and make anther one with a fresh METADATA file.should I?

**Comment by tkelman** [comment]
That might be easiest. For future pull requests, it's recommended to create a new branch and make your changes there.

**Comment by DrKrar** [comment]
Ok, Thanks for your help....

**Pull request closed without merging**
