### PR TITLE
Tag EEG v0.2.1 [https://github.com/codles/EEG.jl]

### PR DESCRIPTION
**Pull request by rob-luke**
Diff vs v0.2.0: https://github.com/codles/EEG.jl/compare/49aeb6759e3c0ea822a2515279f5d7395e1d79ee...49aeb6759e3c0ea822a2515279f5d7395e1d79ee

### CODE REVIEW

**Comment by andreasnoack** [comment]
From the log
```julia
ERROR: LoadError: METADATA/EEG/versions/0.2.1/requires: oldest allowed julia version 0.5.0- too old (>= 0.6.0 needed)
```
Remember that you'll need to bump the minor version when changing the Julia requirement.

It looks like tests are failing and there are many deprecation warnings in the test output.

Also, please consider using https://github.com/attobot/attobot for releases.

**Comment by codles** [comment]
Hi @andreasnoack ,

Thanks for the advice. I will use atoobot from now on.

I wanted to release a final version that I know works with 0.5 and then commit the next version which is for >= 0.6 (in a day or two). I would like to have a final version for 0.5 as I have released papers using this version and would like to be able to go back and reproduce the results easily.

**Comment by codles** [comment]
Also the tests fail due to METADATA git error. Which I believe is reported here https://github.com/JuliaLang/METADATA.jl/issues/10873

**Comment by andreasnoack** [comment]
It is no longer possible to tag releases for 0.5. There is more information in https://discourse.julialang.org/t/errors-for-git-pkg/9351. In short, with Julia 0.5 on Linux, people won't be able to install any packages from GitHub anyway so it wouldn't help much to make a final release for 0.5.

**Pull request closed without merging**
