### PR TITLE
Tag FourierFlows.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [FourierFlows/FourierFlows.jl](https://github.com/FourierFlows/FourierFlows.jl)
Release: [v0.1.1](https://github.com/FourierFlows/FourierFlows.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/FourierFlows/FourierFlows.jl/builds/398519595)
Diff: [vs v0.1.0](https://github.com/FourierFlows/FourierFlows.jl/compare/dfc1060b99ead59e09d45f26df89b303c2c85462...06d3348229123e12e6b48575256f918a6a99ae66)
`requires` vs v0.1.0: no changes
cc: @navidcy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by navidcy** [comment]
@andreasnoack: 
- The CI passed all the tests.
- Some of the required packages could be OK with lower versions. Should I just leave out the version numbers?

**Comment by andreasnoack** [comment]
I think it is fine as is but the tests stalled so I restarted them. When they pass, it should be fine to merge.

**Comment by navidcy** [comment]
Still JuliaCIBot is pending after 2hrs...
Did I do something wrong perhaps?

**Comment by andreasnoack** [comment]
No. I just think the bot has had an off day.

**Pull request merged**
