### PR TITLE
Register new package QuadGK.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMath/QuadGK.jl](https://github.com/JuliaMath/QuadGK.jl)
Release: [v0.0.1](https://github.com/JuliaMath/QuadGK.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMath/QuadGK.jl/builds/186242761)
cc: @ararslan

### CODE REVIEW

**Comment by ararslan** [comment]
cc @stevengj

**Comment by stevengj** [comment]
Seems like it needs a better README?  Also, seems like the whole body of the module should be executed only if `!isdefined(Base, QuadGK)`, so that it just uses the Base function in Julia 0.5?

**Comment by stevengj** [comment]
Seems like it should just do:
```
if !isdefined(Base, :QuadGK)
    export quadgk, gauss, kronrod
end
```
so that on Julia 0.5 it doesn't `import`, it just defines its own module-local `quadgk` function.

**Comment by ararslan** [comment]
I've removed the 0.0.1 release and made some edits to the repo per your suggestions. Could you close this PR and add any further concerns you may have in issues there? Then once it's ready I can tag a new release.

**Comment by ararslan** [comment]
Uh, hey @attobot. How do I open this as a new PR? The SHA here hasn't been updated.

**Comment by simonbyrne** [comment]
Don't close PRs that you're going to update, github sees it as a force push and won't let you reopen it. 

I can fix it, but I need to be at my computer, so it may take a while

**Comment by tkelman** [comment]
or if you use a different version number it should come from a new branch, right?

**Comment by ararslan** [comment]
I'll try that. Sorry for the confusion.

**Comment by ararslan** [comment]
Looks like tagging as v0.1.0 did the trick. Don't worry about changing anything for now, @simonbyrne; this particular situation has been resolved.

**Pull request closed without merging**
