### PR TITLE
Tag LineSearches.jl v4.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/LineSearches.jl](https://github.com/JuliaNLSolvers/LineSearches.jl)
Release: [v4.0.0](https://github.com/JuliaNLSolvers/LineSearches.jl/releases/tag/v4.0.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaNLSolvers/LineSearches.jl/builds/360562668)
Diff: [vs v3.2.5](https://github.com/JuliaNLSolvers/LineSearches.jl/compare/6873fa5a2264a40f6e5b9fa2df2681a2847eec72...b58f286a484a83f7963d7e017cecbd2bf6951519)
`requires` vs v3.2.5: no changes
cc: @pkofod

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by pkofod** [comment]
I will make a PR to add upper bounds.

**Comment by pkofod** [comment]
Can this be re-triggered?

**Comment by andreasnoack** [comment]
I've been told that it should now be the case

**Comment by pkofod** [comment]
Hope that did it :)

**Comment by andreasnoack** [comment]
It did

**Pull request merged**
