### PR TITLE
Tag Bio.jl v0.4.4

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BioJulia/Bio.jl](https://github.com/BioJulia/Bio.jl)
Release: [v0.4.4](https://github.com/BioJulia/Bio.jl/releases/tag/v0.4.4)
Travis: [Travis Build Status](https://travis-ci.org/BioJulia/Bio.jl/builds/184791394)
Diff: [vs v0.4.3](https://github.com/BioJulia/Bio.jl/compare/9bae2aac4542b05db0fdc000a020d8a713874fd5...159b3d92dd6ac2001a5831f5cb0758a89ecb533c)
`requires` vs v0.4.3: 
```diff
--- 0.4.3/requires
+++ 0.4.4/requires
@@ -2,12 +2,13 @@
 BGZFStreams 0.1
 BufferedStreams 0.2
 Colors
+Combinatorics
 Distributions
+EzXML 0.2
 IndexableBitVectors 0.1.1
 IntervalTrees 0.1
 Iterators
 Libz 0.2
 LightGraphs
-LightXML
 Roots
-Combinatorics
+URIParser
```
cc: @Ward9250

### CODE REVIEW

**Comment by tkelman** [comment]
7000 loc added in a patch release?

**Comment by bicycle1885** [comment]
@Ward9250 Did you tag it to the master branch? We should backport patches to the `release-0.4` branch and then tag a patch release to it.

**Comment by Ward9250** [comment]
The changes I've added to this are new methods for Phylo.Dating and docs, I don't know whether that constitutes a patch or not.

**Comment by bicycle1885** [comment]
A commit you attached the v0.4.4 tag at is https://github.com/BioJulia/Bio.jl/commit/159b3d92dd6ac2001a5831f5cb0758a89ecb533c, which is on the master branch and includes some new feature additions like the GFF3 parser. You should make a pull request including commits you want to backport against the release-0.4 branch, merge it, and tag a new patch release to release-0.4. [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) is useful for this purpose.

**Comment by Ward9250** [comment]
Yeah I read up on git cherry-pick last night to see how to do that. Do you think though, since there's GFF as well, should we go to 0.5 rather than just increment a patch number? I can get rid of the 0.4.4 tag and tag a 0.5 on master?

**Comment by bicycle1885** [comment]
That's an option. But I'd like to merge some features & bug fixes before before releasing v0.5, so it would be better to cherry-pick some commits you need if you'd like to release a patch release immediately. I'll be very busy next few days so I cannot work on them. Can we wait for it by the next weekend?

**Comment by Ward9250** [comment]
Yeah I think we can do that :+1:

**Comment by kmsquire** [comment]
Close this, given that the tagging is going to be updated?

**Comment by Ward9250** [comment]
@kmsquire Yes please :+1:

**Comment by simonbyrne** [comment]
Don't close the PR if you're going to update the same version number

**Comment by ViralBShah** [comment]
Maybe close this and use a higher version number in the new tag?

**Comment by bicycle1885** [comment]
I made a mistake. Please do not merge yet.

**Comment by bicycle1885** [comment]
I'm sorry. This is ready to be merged.

**Pull request merged**
