### PR TITLE
Pull request/b24236cf

### PR DESCRIPTION
**Pull request by montyvesselinov**
Mads update.

Now Mads includes a new module called RobustPmap.

RobustPmap is performing a pmap but testing about the type of the returned values.

### CODE REVIEW

**Comment by tkelman** [comment]
I take it this subsumes #4590? I had a question there -

> Would the tests pass if you enabled travis ci? This [RobustPmap] is a very tiny package right now, is there a plan to expand on its functionality instead of putting these two functions in a slightly larger utility package?

**Comment by montyvesselinov** [comment]
Yes. All the tests will be passed by RobustPmap and Mads. We plan to add
more functions in RobustPmap. However, this will be a small package. If
this is unacceptable, we can create a new package MadsTools that will
include more packages in the future. Please advise.

-monty

**Comment by tkelman** [comment]
It's fine as is, I'm mostly just curious whether or not it's always going to be on the order of ~15 real lines of code. It doesn't seem worth managing as a separate package if it's always going to stay that small. We can merge this once travis is finished.

**Comment by montyvesselinov** [comment]
Thank you very much!
On Tue, Feb 23, 2016 at 7:03 PM Tony Kelman <notifications@github.com>
wrote:

> Merged #4642 <https://github.com/JuliaLang/METADATA.jl/pull/4642>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/METADATA.jl/pull/4642#event-562781571>.
>
-- 
-monty

**Pull request merged**
