### PR TITLE
Tag GeoStatsDevTools.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/GeoStatsDevTools.jl](https://github.com/juliohm/GeoStatsDevTools.jl)
Release: [v0.1.1](https://github.com/juliohm/GeoStatsDevTools.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/juliohm/GeoStatsDevTools.jl/builds/361491058)
Diff: [vs v0.1.0](https://github.com/juliohm/GeoStatsDevTools.jl/compare/d82068ec0fe62d1afeb18b861be711666dcdd8a2...89f63dcb287e58b17b6d805f675125ad53cd1ec3)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.1.1/requires
@@ -1,5 +1,5 @@
 julia 0.6
-GeoStatsBase 0.0.5
+GeoStatsBase 0.0.10
 Distances 0.5.0
 Distributions 0.15.0
 DataFrames 0.11.0
```
cc: @juliohm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by juliohm** [comment]
@andreasnoack this one is passing now after the merge of GeoStatsBase.jl

**Comment by andreasnoack** [comment]
It looks like it is breaking some other packages.

**Comment by juliohm** [comment]
It seems that the error in JuliaCIBot is unrelated, and caused by ImageMagick.jl installation issues.

I've just tested the packages locally and they are all passing. These are all solver packages that should be unaffected by the latest changes in this collection of PRs.

**Comment by andreasnoack** [comment]
What about
```julia
ERROR: LoadError: LoadError: LoadError: UndefVarError: AbstractVariogram not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /home/jrun/InverseDistanceWeighting/.julia/v0.6/GeoStats/src/estimators/simple_kriging.jl, in expression starting on line 521
while loading /home/jrun/InverseDistanceWeighting/.julia/v0.6/GeoStats/src/estimators.jl, in expression starting on line 139
while loading /home/jrun/InverseDistanceWeighting/.julia/v0.6/GeoStats/src/GeoStats.jl, in expression starting on line 29
```
in http://juliarun-ci.s3.amazonaws.com/390a1fa0131485bcca1086977187790e8696c17e/InverseDistanceWeighting_with_pull_request_of_GeoStatsDevTools_on_julia_0_6.log?

**Comment by juliohm** [comment]
Thanks for catching it. All the variogram types were moved to `Variography.jl`, that is why the build is successful locally but fails on Travis. Variography.jl was not registered yet #14088

**Comment by juliohm** [comment]
I also just noticed that DataFrames.jl updated again with more `Union` type issues. I will submit a new commit to this PR, thank you for waiting.

**Pull request merged**
