### PR TITLE
Tag FastGaussQuadrature v0.0.3

### PR DESCRIPTION
**Pull request by dlfivefifty**
Fixes gausslegendre and gaussjacobi.

### CODE REVIEW

**Comment by tkelman** [comment]
Would be good to enable Travis CI.

**Comment by dlfivefifty** [comment]
I’m not the owner of the repos, so I can’t enable it.  I’ve CCed the repos owner Alex Townsend.

**Comment by dlfivefifty** [comment]
Since there is some core functionality broken in the currently tagged version, can we merge this request for now and I'll make sure Travis is enabled before making a future pull request?

**Comment by tkelman** [comment]
Sure, once the METADATA Travis check passes. There's a bit of a backlog on JuliaLang's Travis from a large number of active PR's in the last couple days.

**Pull request merged**
