### PR TITLE
Tag BioMedQuery.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bcbi/BioMedQuery.jl](https://github.com/bcbi/BioMedQuery.jl)
Release: [v0.6.0](https://github.com/bcbi/BioMedQuery.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/bcbi/BioMedQuery.jl/builds/422221782)
Diff: [vs v0.5.0](https://github.com/bcbi/BioMedQuery.jl/compare/2203dcef6662eb485ac964f4a1e1539407b7933d...bde4b1bbd51847063d4968aec53b93f78f569d3d)
`requires` vs v0.5.0: 
```diff
--- 0.5.0/requires
+++ 0.6.0/requires
@@ -1,13 +1,14 @@
-julia 0.6
+julia 0.7
 BioServices 0.1.2
-CSV
 DataFrames
 DataStreams
+Dates
 FTPClient
 HTTP
 LightXML
 Missings
 MySQL
 SQLite
+Test
 XMLDict
 ZipFile
```
cc: @mcmcgrath13

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please remove the stdlib from your REQUIRE file

**Comment by mcmcgrath13** [comment]
@andreasnoack updated the REQUIRE file

**Comment by andreasnoack** [comment]
Please add an upper bound on Julia if version 1 isn't supported

**Comment by andreasnoack** [comment]
No activity for more than a month so closing.

**Pull request closed without merging**
