### PR TITLE
Register new package PhotoOrganizer.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [GlenHertz/PhotoOrganizer.jl](https://github.com/GlenHertz/PhotoOrganizer.jl)
Release: [v0.1.0](https://github.com/GlenHertz/PhotoOrganizer.jl/releases/tag/v0.1.0)
cc: @GlenHertz

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@GlenHertz This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please enable Travis testing.

**Comment by GlenHertz** [comment]
I added permissions for Travis to see the repository and enabled it (have the .travis.yml) but it doesn't seem to test it...I'm not sure what is wrong.

**Comment by andreasnoack** [comment]
Having `.travis.yml` and enabling Travis is not the same thing. You'd have to go enable it at https://travis-ci.org/GlenHertz/

**Comment by andreasnoack** [comment]
Since CIBot ran successfully I'll merge, but please enable travis and add some real tests before next release.

**Pull request merged**
