### PR TITLE
Tag Rmath v0.1.1 [git://github.com/JuliaStats/Rmath.jl.git]

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by tkelman** [comment]
the git tag https://github.com/JuliaStats/Rmath.jl/tree/v0.1.1 is not the right sha, please fix

**Comment by andreasnoack** [comment]
Should be fixed now.

**Comment by tkelman** [comment]
I don't get why Travis triggered a push build here when this came from your fork...

**Comment by andreasnoack** [comment]
My fault. I accidentally pushed to origin first but deleted the branch immediately after and thought that I'd avoided the push build.

**Comment by tkelman** [comment]
huh. when you open the pr it should only come from one of the remotes I would think, either julialang or your personal fork, not both?

**Pull request merged**
