### PR TITLE
Tag RingBuffers.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaAudio/RingBuffers.jl](https://github.com/JuliaAudio/RingBuffers.jl)
Release: [v1.0.0](https://github.com/JuliaAudio/RingBuffers.jl/releases/tag/v1.0.0)
Diff: [vs v0.1.1](https://github.com/JuliaAudio/RingBuffers.jl/compare/3ff0c268df2dff8ba31507a0e0d09e4d33f94abf...68d37135a55bbea041ff6141eb097ba352ff554a)
`requires` vs v0.1.1: 
```diff
--- 0.1.1/requires
+++ 1.0.0/requires
@@ -1,2 +1 @@
-julia 0.4
-Compat 0.8.8
+julia 0.6-
```
cc: @ssfrr

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by ssfrr** [comment]
I guess what the JuliaCIBot is saying is that this update breaks PortAudio.jl? (which is dependent on this package). I've got a new PortAudio tag queued up waiting for this to merge, so that issue should be resolved shortly.

**Comment by tkelman** [comment]
to be on the safe side we could upper bound the existing PortAudio tags' dependencies on RingBuffers so this won't upgrade if that package is installed, until the new compatible PortAudio tag is ready?

**Comment by ssfrr** [comment]
done in #9342

**Comment by ssfrr** [comment]
closing this in favor of #9376

**Pull request closed without merging**
