### PR TITLE
Register new package PolyJuMP.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaOpt/PolyJuMP.jl](https://github.com/JuliaOpt/PolyJuMP.jl)
Release: [v0.0.1](https://github.com/JuliaOpt/PolyJuMP.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaOpt/PolyJuMP.jl/builds/209786657)
cc: @blegat

### CODE REVIEW

**Comment by blegat** [comment]
CC @joehuchette @rdeits @chriscoey @ameliaperry

**Comment by tkelman** [comment]
Simulating conditional dependencies with a try-catch isn't going to interact well with precompilation here.

**Comment by blegat** [comment]
I have removed this feature :)

**Comment by tkelman** [comment]
Is it possible to test anything without depending on an unregistered package?

**Comment by blegat** [comment]
It is difficult since `@polyvariable` requires a polymodule. As soon as PolyJuMP is registered, I will register SumOfSquares and then I will be able to reenable the tests

**Comment by blegat** [comment]
I can try something out tomorrow

**Comment by blegat** [comment]
@tkelman Done :)

**Pull request merged**
