### PR TITLE
Register & Tag FTPServer v0.1.0 [https://github.com/invenia/FTPServer.jl]

### PR DESCRIPTION
**Pull request by rofinn**

### CODE REVIEW

**Comment by andreasnoack** [comment]
Why not use Attobot?

**Comment by rofinn** [comment]
I wasn't sure if attobot would work for registering a package, so this seemed like the safer and less magical choice.

**Comment by andreasnoack** [comment]
It easier for us, though, since PRs from Attobot will be automatically merged when tests pass.

**Comment by rofinn** [comment]
Interesting, I didn't realize that.

**Comment by andreasnoack** [comment]
@omus New package registrations are supposed to stay open for three days such that people have a chance to comment.

**Comment by omus** [comment]
Sorry about that.

**Pull request merged**
