### PR TITLE
Tag Pardiso v0.1.0 [https://github.com/KristofferC/Pardiso.jl]

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by tkelman** [comment]
Push the git tag so it shows up at https://github.com/JuliaSparse/Pardiso.jl/releases?

I think someone had been experimenting with installing and testing against MKL on Travis, but dunno where that left off.

**Comment by KristofferC** [comment]
Done.

I could mail the Pardiso people and ask if it is ok If C.I downloads the library and then I have my license as a hidden environment variable that I then create my license file from. You think that is reasonable?

**Comment by tkelman** [comment]
Ah that would be another interesting option. Yeah probably safer to ask for permission before trying that.

**Comment by KristofferC** [comment]
One problem is that Paridso licenses are tied to the userid of the logged in user..

**Pull request merged**
