### PR TITLE
Tag TaylorModels.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIntervals/TaylorModels.jl](https://github.com/JuliaIntervals/TaylorModels.jl)
Release: [v0.1.0](https://github.com/JuliaIntervals/TaylorModels.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIntervals/TaylorModels.jl/builds/512316245)
Diff: [vs v0.0.1](https://github.com/JuliaIntervals/TaylorModels.jl/compare/5b78ea6343f9468c7c60139aef9c5b0dcbdcb178...3b32d43d8b629ac83d21ce05184089110e670d3a)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.1.0/requires
@@ -1,5 +1,6 @@
 julia 0.7
 Reexport v0.2.0
 TaylorSeries v0.8.1
-IntervalArithmetic v0.15.0
+IntervalArithmetic v0.15.1
+TaylorIntegration v0.4.0
 RecipesBase
```
cc: @dpsanders

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dpsanders** [comment]
cc @lbenet

**Comment by dpsanders** [comment]
Is there a reason that this didn't get automatically merged?

**Comment by mforets** [comment]
Bump.

**Comment by lbenet** [comment]
Thanks a lot!

**Comment by schillic** [comment]
> Is there a reason that this didn't get automatically merged?

Automatic merging only kicks in if there is *no* comment. So you screwed it up :wink:

**Pull request merged**
