### PR TITLE
Tag FEMBase.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaFEM/FEMBase.jl](https://github.com/JuliaFEM/FEMBase.jl)
Release: [v0.2.0](https://github.com/JuliaFEM/FEMBase.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaFEM/FEMBase.jl/builds/418813976)
Diff: [vs v0.1.9](https://github.com/JuliaFEM/FEMBase.jl/compare/0730f6495116eeab3977094e0f4978044aa00a01...5201c70c23eee966406c86548ff25ff8e5a35dd8)
`requires` vs v0.1.9: 
```diff
--- 0.1.9/requires
+++ 0.2.0/requires
@@ -1,4 +1,4 @@
-julia 0.6
+julia 0.7
 FEMBasis
 FEMQuad
 TimerOutputs
```
cc: @ahojukka5

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider adding an upper bound on Julia at 0.7 if the package doesn't support Julia 0.7.

**Comment by ahojukka5** [comment]
`FEMBase.jl` should be Julia v1.0 compatible now. Maybe I should set upper bound to all packages that are using FEMBase to 0.1 because they are not updated yet?

**Comment by andreasnoack** [comment]
I was looking at the results from CIBot, https://s3.ap-south-1.amazonaws.com/juliarun-ci/84daa7a9884e40941d6a505e167df7ceed0efcd0/FEMBase_reverse_dependency_tests.html, but apparently, there are still some issues with the bot. Let me take a look.

**Comment by andreasnoack** [comment]
This is actually a real issue. This package depends on `FEMQuad` which again depends on `Logging` which is upper bound at Julia 0.7-. Hence you should first make a new release of `FEMQuad` without the `Logging` dependency and then update `FEMBase` to require the new version of `FEMQuad`.

**Comment by ahojukka5** [comment]
This should now be working after merging PR #17201.

**Comment by andreasnoack** [comment]
It looks like this breaks FEMBeam and HeatTransfer on 0.7

**Comment by ahojukka5** [comment]
- Julia v0.7 compatible FEMBeam tagged (see PR #17386)
- Julia v0.7 compatible HeatTransfer tagged (see PR #17402)

**Pull request merged**
