### PR TITLE
Tag ApproxFun v0.0.7

### PR DESCRIPTION
**Pull request by dlfivefifty**
Restores 0.4 compatibility

### CODE REVIEW

**Comment by tkelman** [comment]
Please wait until Travis has passed before merging your own pull requests.

You should add a REQUIRE file listing `julia 0.3` as the minimum supported version, assuming you aren't testing with anything earlier any more.

**Comment by dlfivefifty** [comment]
Hi Tony,

	Sorry about that, I will do so next time.

Cheers,
Sheehan

**Comment by dlfivefifty** [comment]
If I want to add the REQUIRE and redo the tag on github, do I need to do something to update METADATA?

**Comment by tkelman** [comment]
Generally tags shouldn't be touched after they get pushed, you can add a new separate tag, or modify just the metadata content here of an existing tag

**Pull request merged**
