### PR TITLE
Tag IterableTables.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidanthoff/IterableTables.jl](https://github.com/davidanthoff/IterableTables.jl)
Release: [v0.1.0](https://github.com/davidanthoff/IterableTables.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/davidanthoff/IterableTables.jl/builds/235792037)
Diff: [vs v0.0.2](https://github.com/davidanthoff/IterableTables.jl/compare/9caf2f17373cbd69d7fbb3f3e02434769f020f73...bda44d34cde2e0025e28a4a204854bdcda99f4e4)
`requires` vs v0.0.2: 
```diff
--- 0.0.2/requires
+++ 0.1.0/requires
@@ -1,3 +1,4 @@
-julia 0.5
-NamedTuples 2.0.0
-Requires 0.3.0
+julia 0.6.0-rc1
+NamedTuples 3.0.2
+Requires 0.4.3
+DataValues 0.0.3
```
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Please merge #9491 first.

**Comment by tkelman** [comment]
what was the first version of GLM where `lm(StatsModels.@formula(a~b), source_df)` would work?

**Comment by davidanthoff** [comment]
I have no idea. But we can't do much about that in any case, right? GLM is only in the test REQUIRE, where I would prefer an unversioned line, and then there is no support for minimum versions in Requires.jl, which essentially handles the non-test case.

**Comment by tkelman** [comment]
> where I would prefer an unversioned line

What? Not including minimum versions is saying your code works with every version that's ever been released of the other package. That's clearly incorrect here.

**Comment by davidanthoff** [comment]
I don't have the time to figure out minimum versions in the test REQUIRE file. I also don't see what minimum versions in the *test* REQUIRE file would buy us. I am maintaining the minimum versions in the package REQUIRE file, which seems like the important thing from a user point of view.

**Comment by tkelman** [comment]
Same reason as any other minimum version bound - tests would fail if anyone had your test-dependency package pinned or upper-bounded to anything too old for the feature you're using. GLM has had few enough releases that it wasn't too hard to figure out where that happened, via https://github.com/JuliaStats/GLM.jl/releases and https://github.com/JuliaStats/GLM.jl/compare/v0.6.1...v0.7.0#files_bucket. The `@formula` macro was actually implemented in DataFrames 0.9.0 (https://github.com/JuliaStats/DataFrames.jl/compare/v0.8.4...v0.9.0#files_bucket) so you should lower-bound that in your `test/REQUIRE`.

**Comment by davidanthoff** [comment]
Bump, this can be merged now, right?

**Pull request merged**
