### PR TITLE
Tag CovarianceMatrices.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [gragusa/CovarianceMatrices.jl](https://github.com/gragusa/CovarianceMatrices.jl)
Release: [v0.3.0](https://github.com/gragusa/CovarianceMatrices.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/gragusa/CovarianceMatrices.jl/builds/235849272)
Diff: [vs v0.2.1](https://github.com/gragusa/CovarianceMatrices.jl/compare/d13d20a255615a8b43e3850fb37b6b8af9a75e90...10524c0bd0662461e8b506040f921b1245e3dd3f)
`requires` vs v0.2.1: 
```diff
--- 0.2.1/requires
+++ 0.3.0/requires
@@ -1,4 +1,4 @@
-julia 0.5
+julia 0.6-
 StatsBase 
 GLM 0.6
 DataFrames
```
cc: @gragusa

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
Compat is missing from REQUIRE

**Comment by gragusa** [comment]
Yeap. How did it pass tests on travis? 

Please, could you close this PR? I will remove @compat macros (unnecessaries since this is a v0.6 only release) e re-request a PR.

**Comment by tkelman** [comment]
One of your dependencies happened to depend on Compat, but since that's not guaranteed to always be the case, it's better to list all the dependencies you use directly.

If you use the same version number, deleting and replacing the release will cause attobot to update the PR in place. Closing it would cause attobot to open a new PR. Either way works.

**Comment by tkelman** [comment]
I see you used a new version number for https://github.com/JuliaLang/METADATA.jl/pull/9502, no problem

**Pull request closed without merging**
