### PR TITLE
Pull request/4d0e5e7c

### PR DESCRIPTION
**Pull request by mauro3**
To add https://github.com/mauro3/Parameters.jl

### CODE REVIEW

**Comment by tkelman** [comment]
Should this add a `julia 0.3` requirement?

**Comment by mauro3** [comment]
Done.  Should I be more specific about the versions of other requirements as well?

**Comment by tkelman** [comment]
Cool, will also need to add to https://github.com/mauro3/Parameters.jl/blob/master/REQUIRE before tagging the next version to avoid having to do it manually next time.

If you happen to know which versions of your deps added the features you need then it's nice to add, but not strictly necessary.

**Comment by mauro3** [comment]
I added `julia 0.3` to REQUIRE, thanks. And no, I don't know which package versions.  So I'll leave it like this for now. Thanks.

**Pull request merged**
