### PR TITLE
Register new package LDL.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaSmoothOptimizers/LDL.jl](https://github.com/JuliaSmoothOptimizers/LDL.jl)
Release: [v0.1.0](https://github.com/JuliaSmoothOptimizers/LDL.jl/releases/tag/v0.1.0)
cc: @abelsiqueira

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@abelsiqueira This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
@dpo

**Comment by andreasnoack** [comment]
Same naming problem hereas in #17907. Maybe LDLFactorization?

**Comment by dpo** [comment]
The original C package is named LDL, so it seems natural to name the Julia translation similarly since some people will already be familiar with the name. According to the naming guidelines, if I simply write a Julia interface to the C LDL library, then I should call it LDL. But if I translate it to Julia, the name must change?! That seems a bit inconsistent?!

Would LDLFactorization and LimitedLDLFactorization work?

**Comment by andreasnoack** [comment]
In any case, I think that something more descriptive like `LDLFactorization` is better.

**Comment by abelsiqueira** [comment]
Renamed: https://github.com/JuliaLang/METADATA.jl/pull/17950

**Pull request closed without merging**
