### PR TITLE
Register SolarSystemLib

### PR DESCRIPTION
**Pull request by moisespsena**

### CODE REVIEW

**Comment by tkelman** [comment]
You'll need to tag a version.

**Comment by moisespsena** [comment]
I tagged it now.

**Comment by tkelman** [comment]
In the PkgDev.tag sense here, not just the git tag. Or see https://github.com/attobot/attobot to avoid needing to use PkgDev.

**Comment by moisespsena** [comment]
I made the correction. How to apply again?

**Comment by tkelman** [comment]
now that you've enabled attobot, https://github.com/JuliaLang/METADATA.jl/pull/8786 has this covered

**Pull request closed without merging**
