### PR TITLE
register package qwtwplot.jl

### PR DESCRIPTION
**Pull request by ig-or**
New beautiful 2D plot package for Julia; very convenient for data analysis.

### CODE REVIEW

**Comment by ig-or** [comment]
Now it should work for Windows and Linux platforms; Julia 0.4 and 0.5 rc3 supported.

Related thread in Julia-users community    https://groups.google.com/forum/#!topic/julia-users/by8YlsmRnHg

Best regards, Igor

**Comment by tkelman** [comment]
Note that we currently only have one package, and it's deprecated, that doesn't start with an upper-case letter.

**Comment by ig-or** [comment]
OK, thanks!  Is it OK if I change package name and open another pull request with it?

**Comment by tkelman** [comment]
You can either open a new PR, or force push over this branch.

**Comment by ig-or** [comment]
OK! new PR created.

**Pull request closed without merging**
