### PR TITLE
Tag DataArrays v0.3.6

### PR DESCRIPTION
**Pull request by ararslan**
The one and only @tkelman has bestowed upon us a fix for DataArrays which should solve all of our OneTo woes.

### CODE REVIEW

**Comment by tkelman** [comment]
I'm going to use my administrator powers and merge this without waiting for travis so it gets into tonight's pkgeval run

**Comment by ararslan** [comment]
Cool. Fingers crossed that stats packages are no longer on fire and broken tomorrow.

**Comment by tkelman** [comment]
With the premature rmath deletion they probably will be, but for new reasons. Never a dull day.

**Comment by ararslan** [comment]
Could we temporarily revert the base rmath deletion until packages can catch up?

**Pull request merged**
