### PR TITLE
Tag DataArrays.jl v0.7.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/DataArrays.jl](https://github.com/JuliaStats/DataArrays.jl)
Release: [v0.7.0](https://github.com/JuliaStats/DataArrays.jl/releases/tag/v0.7.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/DataArrays.jl/builds/306869920)
Diff: [vs v0.6.2](https://github.com/JuliaStats/DataArrays.jl/compare/78327d1e6a8cd27c44d9afbaec419caf6a98893c...e8fe4f25727dad1f7155c784621bbc50737bb064)
`requires` vs v0.6.2: 
```diff
--- 0.6.2/requires
+++ 0.7.0/requires
@@ -1,4 +1,5 @@
 julia 0.6
+Missings 0.2.1
 StatsBase 0.15.0
 Reexport
 SpecialFunctions
```
cc: @nalimilan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
These bounds are incomplete, this can result in downgrading to old versions of DataFrames (or others here) that didn't depend on DataArrays

**Comment by nalimilan** [comment]
What do you mean by "incomplete"? AFAICT all dependencies have an upper bound on 0.7.0. I must be missing something.

**Comment by tkelman** [comment]
This missed the fact that several of these packages only depend on DataArrays for a subset of their versions. Having bounded dependencies on only a subset of versions can result in strange things happening to avoid the bounds, like downgrading to a very old version that didn't depend on DataArrays.

**Comment by nalimilan** [comment]
Ah, good catch. I'm glad we still have you around! See https://github.com/JuliaLang/METADATA.jl/pull/12220.

**Pull request merged**
