### PR TITLE
Register new package GraphGLRM.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [mihirparadkar/GraphGLRM.jl](https://github.com/mihirparadkar/GraphGLRM.jl)
Release: [v0.2.0](https://github.com/mihirparadkar/GraphGLRM.jl/releases/tag/v0.2.0)
cc: @mihirparadkar

### CODE REVIEW

**Comment by tkelman** [comment]
If you enabled Travis CI, would your tests pass there?

**Comment by tkelman** [comment]
Since you also use DataFrames and StatsBase, need to list them in REQUIRE

**Comment by mihirparadkar** [comment]
I have those listed in REQUIRE now, but does Travis need to be enabled to merge? I don't think I have any tests configured to run with Travis.

**Comment by tkelman** [comment]
It's very highly recommended. The default .travis.yml should be good enough, mostly just need to click one button at https://travis-ci.org/mihirparadkar/GraphGLRM.jl.

Need to re tag for the REQUIRE changes to be accounted for here

**Comment by tkelman** [comment]
closing in favor of #7914

**Pull request closed without merging**
