### PR TITLE
Register new package JWTs.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [tanmaykm/JWTs.jl](https://github.com/tanmaykm/JWTs.jl)
Release: [v0.1.0](https://github.com/tanmaykm/JWTs.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/tanmaykm/JWTs.jl/builds/477693346)
cc: @tanmaykm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@tanmaykm This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use abbreviations in package names.

**Comment by tanmaykm** [comment]
JSONWebTokens is already taken, and I believe the approach taken in JWTs.jl is different and useful too. And JSON Web Tokens are more often called just JWT.

I am unable to come up with a different suitable name. But suggesions are welcome!

**Comment by tanmaykm** [comment]
Just checking whether the current name is acceptable as I have reasoned, or if I need to do anything more here.

**Comment by EricForgy** [comment]
> I am unable to come up with a different suitable name. But suggesions are welcome!

In a similar case, someone wanted to develop `JSON.jl`, but the name was already taken so they registered [JSON2.jl](https://github.com/quinnj/JSON2.jl). Then, yet a third person wanted a lazy implementation of JSON so they registered [LazyJSON.jl](https://github.com/samoconnor/LazyJSON.jl).

Is there something unique about this implementation?

Suggestions:
* JSONWebTokens2.jl
* LazyJSONWebTokens.jl (or something other adjective besides "Lazy")

At the end of the day, it is your package and you should be able to name it whatever you want, but I do think it is better to avoid acronyms (especially TLAs) because they often have different meaning depending on context.

**Comment by tanmaykm** [comment]
Will JSONWebToken.jl be acceptable?

**Comment by EricForgy** [comment]
Hi @tanmaykm 👋 

I'm in the same boat as you. Watching anxiously for my package to be merged, so I noticed your PR 😊 

From my experience, those interested will provide feedback on you PR and remind you of guidelines / best practices, etc, but at the end of the day, the package is your baby and I think you can name it whatever you want, including `JWTs.jl`, but acronyms for package names are potentially confusing. No one likes TLA (three-letter acronym) overload 😅 

For what it's worth, if it was between JWTs.jl or JSONWebToken.jl (the singular version of an existing registered package), I'd lean to JWTs.jl. I was a little surprised that Googling "JWT" didn't give a wider variety of results. Most everything that came back for "JWT" was for JSON web tokens so you might be ok on this one 🤷‍♂️

**Comment by tanmaykm** [comment]
Thanks @EricForgy. Those were exactly my thoughts too.

- JSONWebToken will be easily confused with the existing JSONWebTokens
- This package also manages keys used to sign/verify JWTs, but names like JSONWebTokensAndKeys or JSONWebTokenManagement seem too long and distracting
- JSONWebToken2 seems like implementing version 2 of something, which it is not
- JWT is a very commonly used term for JSON Web Tokens, and does not seem to be confusing with anything else

So I would like to retain the name JWTs.jl

**Comment by tanmaykm** [comment]
@dpsanders @andreasnoack would like to know if this addresses your concerns?

**Comment by andreasnoack** [comment]
Yes. It does. While I don't think three-letter abbreviations are good names, there is currently no better name candidate.

**Pull request merged**
