### PR TITLE
Tag NFFT v0.1.2

### PR DESCRIPTION
**Pull request by robertdj**

### CODE REVIEW

**Comment by tkelman** [comment]
It looks like this broke your GeneralizedSampling.jl package? http://pkg.julialang.org/detail/GeneralizedSampling.html

**Comment by robertdj** [comment]
I didn't know that packages depending on NFFT where being retested?

**Comment by tkelman** [comment]
PackageEvaluator tests all registered packages nightly. http://pkg.julialang.org/pulse.html

**Comment by robertdj** [comment]
Good to know. I'll tag a new version for GeneralizedSampling soon where the NFFT dependency is fixed.

**Pull request merged**
