### PR TITLE
WIP: Updates to Temporal and Indicators

### PR DESCRIPTION
**Pull request by dysonance**
**Temporal:**
- Added JSON dependency
- More documentation to I/O functions
- Other bugfixes that arose while trying to transition to Julia 0.6

**Indicators:**
- Added Julia 0.5 requirement
- Type annotations for function outputs
- Improved documentation
- ZLEMA (zero-lag exponential moving average) function added

### CODE REVIEW

**Comment by tkelman** [comment]
Indicators doesn't rely on any of the methods being removed from Temporal here?

**Comment by dysonance** [comment]
@tkelman Not to my knowledge no, the functionality should remain intact.

**Comment by tkelman** [comment]
marking WIP because you've described in a conversation in the repo that you plan on making some modifications

**Comment by dysonance** [comment]
@tkelman Hey man, after a brutally unsuccessful hour and a half of trying like hell to find even one thorough and well-documented explanation of how to update a pull request, I'm going to just close this and re-open. I think I *might* have figured out how to use Attobot and there are some new PR's open for each of these packages. Although, I'm still not sure if Attobot will *udpate* these PR's if I make edits later on.

Honestly, it is just amazing how difficult figuring out this simple thing is proving. I almost put my fist through my terminal window there for a second...

**Comment by tkelman** [comment]
You can make changes to an existing branch of an open pull request, but yeah attobot will work too. There's a section https://github.com/attobot/attobot#updatingdeleting-a-release on how attobot would update things for you if needed, but things look fine so that probably won't be necessary. Feel free to ask for help if you get stuck next time.

**Comment by dysonance** [comment]
Haha I'm still trying to figure it out. I'm wondering if the problem is that my remote url in git config is JuliaLang repo, which might make sense given the error message was that I didn't have push access permissions.

**Comment by tkelman** [comment]
Yes that would be a problem, you'd need to add your fork as a separate remote, `git remote add dysonance https://github.com/dysonance/METADATA.jl` (or `ssh://` if you prefer that)

**Comment by dysonance** [comment]
@tkelman I did read that attobot section and went through the steps, but it didn't update this PR, so I was confused. But maybe it just has to be a PR that attobot opened?

Also I just changed the (push)url of the git config file in my local METADATA repo and it seems like it has push rights now. So I did a `git push origin pull-request/fbbe21de --force` and given what I read expected the commits to get updated here, but it doesn't look like they did. Is that because it's already closed?

**Comment by tkelman** [comment]
> But maybe it just has to be a PR that attobot opened?

Correct.

> it doesn't look like they did. Is that because it's already closed?

Likely. If you force push to the branch of a closed PR, github does strange things and I think prevents you from reopening the PR for whatever reason. Opening multiple PR's isn't too much of an issue if it's the easiest thing for you to do.

**Comment by dysonance** [comment]
Okay, I *think* I may finally have a handle on this. Got the extra remotes added, understand how Attobot works now.

You, sir, are a kind and patient man. Thanks for taking the time to explain things to me.

**Pull request closed without merging**
