### PR TITLE
Tag CxxWrap v0.1.3

### PR DESCRIPTION
**Pull request by barche**
* Smart pointer support
* Better array support
* Trigger CMake on build

### CODE REVIEW

**Comment by barche** [comment]
I think most  issues are fixed, depending on if the unexplained appveyor failure is acceptable. Should I move the 0.1.3 tag in my repo to the latest commit or tag a new version?

**Comment by tkelman** [comment]
I usually favor making new tags to modifying existing ones

**Comment by barche** [comment]
OK, I think the code is ready for release now. Shall I close this pull request and tag the latest commit as 0.1.4?

**Comment by tkelman** [comment]
You could push the 0.1.4 tag into this PR if you'd like

**Comment by barche** [comment]
OK, done, thanks for the thorough review!

**Pull request merged**
