### PR TITLE
add planout package

### PR DESCRIPTION
**Pull request by rawls238**
@tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
Cool. I check these any way, any specific reason to ping me?

Would be good to add an explicit license file in addition to the readme note but otherwise lgtm.

**Comment by rawls238** [comment]
ah sorry, sometimes it's needed to get people to actually respond to it :). Won't do it on this repo in the future.

**Comment by rawls238** [comment]
I added the license file

**Comment by tkelman** [comment]
Ah, missing a level of folder name for the actual version number - 0.1.0?

**Comment by rawls238** [comment]
added that -nice catch

**Pull request merged**
