### PR TITLE
Tag GLFW.jl v2.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGL/GLFW.jl](https://github.com/JuliaGL/GLFW.jl)
Release: [v2.0.0](https://github.com/JuliaGL/GLFW.jl/releases/tag/v2.0.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGL/GLFW.jl/builds/383323451)
Diff: [vs v1.5.0](https://github.com/JuliaGL/GLFW.jl/compare/6d1e509cea73402d4f6b37314ab0fe97d934c837...899df53c787935fe3de39c6254187f775cb05985)
`requires` vs v1.5.0: 
```diff
--- 1.5.0/requires
+++ 2.0.0/requires
@@ -1,3 +1,3 @@
-julia 0.5
+julia 0.6
 BinDeps
 @osx Homebrew
```
cc: @SimonDanisch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by jayschwa** [comment]
I will probably make more (slight) breaking changes, so a pre-release tag might have been more appropriate. It's not a big deal though. You're the main consumer of the package, and I know you want some of the new stuff on master.

I will probably have another go at it once Julia 0.7 is out and might bump the major version again, if necessary.

**Comment by jayschwa** [comment]
Also, do you know if there's a way to see all the consumers of the package? https://pkg.julialang.org/ says there are 7 for GLFW, but I cannot see anything specific.

**Comment by andreasnoack** [comment]
Please let us know if/when you'd like this one to be merged

**Comment by jayschwa** [comment]
Please close this PR. I retagged with `v2.0.0-alpha`, which is a better reflection of the stability guarantee. attobot appears to have not pulled in the changes for the release, so I'll start a new PR. Thanks!

**Pull request closed without merging**
