### PR TITLE
Tag TimeSeries v0.5.4

### PR DESCRIPTION
**Pull request by milktrader**
Going to wait to see what travis does first, see if I can figure out why these PRs are failing METADATA tests.

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like travis is just killing the process after 10 minutes of no output. Probably worth trying a progress meter.

**Comment by milktrader** [comment]
Yep,

````bash
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
````
Just restarted it

**Comment by milktrader** [comment]
At least this present error is different from the previous ones

````bash
3.18s$ git fetch origin +refs/pull/2218/merge:
fatal: Couldn't find remote ref refs/pull/2218/merge
The command "eval git fetch origin +refs/pull/2218/merge:" failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/2218/merge
The command "eval git fetch origin +refs/pull/2218/merge:" failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/2218/merge
The command "eval git fetch origin +refs/pull/2218/merge:" failed 3 times.
The command "git fetch origin +refs/pull/2218/merge:" failed and exited with 128 during .
Your build has been stopped.
````

**Comment by milktrader** [comment]
Yay!

@jiahao I think many of my previous merges failed on travis because of a *quick trigger finger* where I was merging before the tests could complete. I won't do that anymore.

Also, it appears a new problem has emerged about timing out, which I'm unclear about.

**Comment by jiahao** [comment]
I did add more tests, which probably contributes to the probability that the tests would time out.

**Pull request merged**
