### PR TITLE
Tag TimeZones.jl v0.4.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaTime/TimeZones.jl](https://github.com/JuliaTime/TimeZones.jl)
Release: [v0.4.2](https://github.com/JuliaTime/TimeZones.jl/releases/tag/v0.4.2)
Diff: [vs v0.4.1](https://github.com/JuliaTime/TimeZones.jl/compare/fa63d7b3af63c106eb2c4d92981af637ca3b771f...b8a8cbd279f4f4147de00699089521fa346f34d8)
`requires` vs v0.4.1: 
```diff
--- 0.4.1/requires
+++ 0.4.2/requires
@@ -1,4 +1,4 @@
 julia 0.4
 Compat 0.25
 Mocking 0.2
-@windows LightXML
+@windows LightXML 0.2
```
cc: @omus

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
What's causing the undefreferror here?

Does this still need to support julia 0.4?

**Comment by omus** [comment]
> Does this still need to support julia 0.4?

This is the final release of TimeZones.jl which will support Julia 0.4 and 0.5. I'm mostly just releasing this tag so those versions can have these last couple of bugfixes.

> What's causing the undefreferror here?

I'm not sure where that is coming from. Will investigate.

**Comment by omus** [comment]
Looks like one of my Linux tests assumes that you have the "Etc/GMT-9" file installed in your zoneinfo directory. (typically "/usr/share/zoneinfo/Etc/GMT-9"). @tkelman can you confirm that this file doesn't exist?

**Comment by omus** [comment]
The `UndefRefError` was from attempting to show a partially constructed `SystemError`: https://github.com/JuliaTime/TimeZones.jl/pull/89

**Comment by tkelman** [comment]
It runs in a fairly minimal docker container as I understand it, not sure of the exact image though.

**Comment by omus** [comment]
Ok, no problem. I've reworked test so it is no longer required.

**Pull request merged**
