### PR TITLE
LightGraphs: Add 0.9.0 as an upper bound on StatsBase requirement

### PR DESCRIPTION
**Pull request by ararslan**
0.9.0 introduces breaking changes.

Ref https://github.com/JuliaGraphs/LightGraphs.jl/pull/383#issuecomment-233534888

### CODE REVIEW

**Comment by tkelman** [comment]
Cool. What about 0.1.11 - 0.1.14 ?

**Comment by ararslan** [comment]
No dependency on StatsBase. Should I add a fake one?

**Comment by tkelman** [comment]
yeah I think so, how odd that it was removed then came back?

**Comment by ararslan** [comment]
Yeah, pretty weird. I'll set the lower bound as whatever the last lower bound was before the dependency mysteriously disappeared.

**Pull request merged**
