### PR TITLE
Register new package HurdleDMR.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [AsafManela/HurdleDMR.jl](https://github.com/AsafManela/HurdleDMR.jl)
Release: [v0.2.0](https://github.com/AsafManela/HurdleDMR.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/AsafManela/HurdleDMR.jl/builds/433019134)
cc: @AsafManela

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@AsafManela This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by AsafManela** [comment]
Please merge this one. The JuliaCIBot tests fail because I rely on a Lasso.jl fork as the registered package is not maintained. The README in this package provides instructions for installing this fork first. Thanks!

**Comment by andreasnoack** [comment]
I've merged your PR to Lasso and made a release, https://github.com/JuliaLang/METADATA.jl/pull/19039, so maybe update this package to use the registered version and update the tag? See https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by AsafManela** [comment]
Thanks! Any chance you could also release a preceding version of Lasso, say v0.1.5 at this [commit](https://github.com/JuliaStats/Lasso.jl/commit/b7083ea099fdf217ab8dd1a015dbf54bd84945cc)?
That was the last reliable one before bumping the julia version to 0.7. I and perhaps others who have older code that uses Lasso.jl would benefit greatly from having such a tagged version.
My plan then is to update the HurdleDMR release as you suggested, and then release a newer version that supports julia 0.7 and above. I have that one ready but, again, wanted to have a julia 0.6 release first.

**Comment by andreasnoack** [comment]
Done! See https://github.com/JuliaLang/METADATA.jl/pull/19109.

**Comment by AsafManela** [comment]
Updated. Thank you for all your help!

**Comment by andreasnoack** [comment]
You are welcome. It would be great if you could add an upper bound on Julia if 0.7/1.0 isn't supported yet.

**Pull request merged**
