### PR TITLE
Tag BoundaryValueDiffEq.jl v2.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/BoundaryValueDiffEq.jl](https://github.com/JuliaDiffEq/BoundaryValueDiffEq.jl)
Release: [v2.2.0](https://github.com/JuliaDiffEq/BoundaryValueDiffEq.jl/releases/tag/v2.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/BoundaryValueDiffEq.jl/builds/415045155)
Diff: [vs v2.1.0](https://github.com/JuliaDiffEq/BoundaryValueDiffEq.jl/compare/d8e1d1b0b1f37898677e27042f07fc83b93582e1...279b77d349a3bf435a7c7b30a44712457b679551)
`requires` vs v2.1.0: 
```diff
--- 2.1.0/requires
+++ 2.2.0/requires
@@ -1,4 +1,4 @@
-julia 0.7-beta2
+julia 1.0
 DiffEqBase
 Reexport
 NLsolve 0.14.0
```
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like there are issues with the dependencies

**Comment by ChrisRackauckas** [comment]
Yes it's just ForwardDiff's deprecation and now bringing back of those constructors.

**Comment by andreasnoack** [comment]
Looks like there is also a problem with `RandomNumbers`
```julia
┌ Error: Error building `RandomNumbers`: 
│ ERROR: LoadError: LoadError: UndefVarError: is_bsd not defined
│ Stacktrace:
│  [1] build() at /home/travis/.julia/packages/RandomNumbers/5tfiq/deps/Random123/build.jl:16
│  [2] top-level scope at /home/travis/.julia/packages/RandomNumbers/5tfiq/deps/Random123/build.jl:40
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:388
│  [7] top-level scope at none:0
│  [8] include at ./boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at ./loading.jl:1038
│  [10] include(::Module, ::String) at ./sysimg.jl:29
│  [11] include(::String) at ./client.jl:388
│  [12] top-level scope at none:0
│ in expression starting at /home/travis/.julia/packages/RandomNumbers/5tfiq/deps/Random123/build.jl:39
│ in expression starting at /home/travis/.julia/packages/RandomNumbers/5tfiq/deps/build.jl:1
```

**Comment by ChrisRackauckas** [comment]
Yes and that's https://github.com/sunoru/RandomNumbers.jl/pull/42 . I really wish that package was in JuliaMath so it could be better maintained on time...

**Pull request merged**
