### PR TITLE
AWSCore fixes for Linux CI

### PR DESCRIPTION
**Pull request by samoconnor**
Travis found problems with Linux/EC2:
 - https://github.com/samoconnor/AWSCore.jl/commit/a6992c639b731c0c71340b3102d912363e3fc666

- https://github.com/samoconnor/AWSCore.jl/commit/7efa84cf5013ec296c1d242bf5c449f6fac2ded8

Also disable "nightly" in travis.yml for now.

### CODE REVIEW

**Comment by samoconnor** [comment]
CI for the AWS* subpackage is failing because AWSCore/AWSCredentials.jl was trying to get instance credentials from the virtual machine used by Travis (instead of using the ENV vars from .travis.yml)

**Comment by tkelman** [comment]
don't really need to re-tag the packages where you only changed .travis.yml, that isn't user visible

**Comment by samoconnor** [comment]
Yeah, but I'd rather have my local copies in sync with the released versions as much as possible.
I have a script that shows me which local repos are ahead of the tagged version, and I'd rather have it run cleanly than constantly nag me about trivial changes.

**Comment by tkelman** [comment]
fair enough

**Comment by samoconnor** [comment]
stand by, I'll give the allowed failure thing a try...

**Comment by samoconnor** [comment]
Ok, looks like the allowed failure setting is working now: https://travis-ci.org/samoconnor/AWSCore.jl

**Pull request merged**
