### PR TITLE
Tag GMT.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [GenericMappingTools/GMT.jl](https://github.com/GenericMappingTools/GMT.jl)
Release: [v0.2.1](https://github.com/GenericMappingTools/GMT.jl/releases/tag/v0.2.1)
Diff: [vs v0.2.0](https://github.com/GenericMappingTools/GMT.jl/compare/afc3a155f7adf58fc263424d26ae13fc6bb8c9c6...5ec77c1b2b4013a4f26fee307ce343f1bedff9c0)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.2.1/requires
@@ -1 +1 @@
-julia 0.5
+julia 0.6
```
cc: @joa-quim

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by joa-quim** [comment]
If the hold with this PR regards the CIBot failure, I have to say that the failure, which fails because it says previous version (v0.2.0) required Julia 0.5 is Wrong! v0.2.0 of this package already required Julia 0.6, as can easily be verified.

**Comment by KristofferC** [comment]
> ERROR: LoadError: New tag 0.2.1 of package GMT requires julia 0.6.0, but version 0.2.0 of GMT requires julia 0.5.0. Use a new minor package version when support for an old version of Julia is dropped. Re-tag the package as 0.3.0 using `PkgDev.tag("GMT", :minor)`.

**Comment by joa-quim** [comment]
That is what I referred in my previous comment. The statement that GMT 0.2.0 required Julia 0.5 is wrong. 0.2.0 already required 0.6 as can be verified. 
I think I know where the error comes from. I made one first attempt to tag 0.2.0 that required 0.5 but it errored for some compat issue and I deleted that attempt and did a new 0.2.0 already with 0.6 which the still current one. 

Sent from my iDedo

No dia 11/11/2017, às 08:45, Kristoffer Carlsson <notifications@github.com> escreveu:

**Comment by KristofferC** [comment]
0.2.0 is already registered in METADATA and it does contain julia 0.5: https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/GMT/versions/0.2.0/requires

**Comment by joa-quim** [comment]
OK, I did retag to 0.3.0 but I'm not dreaming.This is PR for 0.2.0 where I was requested to drop julia 0.5
https://github.com/JuliaLang/METADATA.jl/pull/11851

**Comment by hayd** [comment]
closed/superseded by #11973

**Pull request closed without merging**
