### PR TITLE
Tag GeoStats v0.0.5 [https://github.com/juliohm/GeoStats.jl]

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by juliohm** [comment]
So, if I drop support to a Julia release, I am now enforced to tag a minor release for my package?

**Comment by tkelman** [comment]
Yes. That's always been recommended and it's been enforced for most of the year.

**Comment by juliohm** [comment]
@tkelman what is the most straightforward way to update a PR like this? I have tagged my package with PkgDev.tag(), pushed the tag to GitHub with `git push origin tag` from the package folder, pushed METADATA to my fork on GitHub and finally opened the PR. Undoing these steps is always trick for me and I end up erasing everything and cloning repos again.

**Comment by juliohm** [comment]
@tkelman do you have suggestions about this?

Also, do you think it is a good idea to enforce release schemes on users? I just decided to drop support to Julia v0.4 because it doens't support test sets. So, no actual change to the package code that deserves a minor release.

**Comment by tkelman** [comment]
You could use BaseTestNext to restore 0.4 support. Otherwise dropping support for an existing version of julia is a breaking change. And you need to leave versioning space for the possibility of needing to make a backport bug fix release that does support 0.4.

Otherwise you can do PkgDev tag("GeoStats", :minor) like the error says, and either add that commit to this branch, or make a new branch. You should always create a new branch for any pull request, don't use metadata-v2 of your fork.

**Comment by juliohm** [comment]
Thank you, I will do it later today when I find some time.

**Comment by juliohm** [comment]
@tkelman when you say create a new branch, you mean push the commit obtained with `PkgDev.tag` to a custom branch in my fork of METADATA correct?

The issue I always have is that whenever a mistake like this occur, I have to uninstall METADATA locally and reinstall it again, basically reinstall all the packages because metadata-v2 becomes "corrputed"

**Comment by tkelman** [comment]
What makes you think you have to do that? If you have local commits on your metadata-v2 branch you would like to get rid of, you can either do git rebase or git reset.

**Comment by juliohm** [comment]
Thank you @tkelman, I just submitted a new PR with the corrections. I will also keep in mind the reset and rebase on METADATA.

**Pull request closed without merging**
