### PR TITLE
Register SparseGrids

### PR DESCRIPTION
**Pull request by robertdj**
Generate sparse grids for numerical quadrature.

### CODE REVIEW

**Comment by tkelman** [comment]
Please see the package registration policies at https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/README.md

In particular, you need a `REQUIRE` file listing [your package's dependencies](https://github.com/robertdj/SparseGrids.jl/blob/e55a14fe66bf3c959fc7e67ac6556273501e055e/src/SparseGrids.jl#L3-L4), including the minimum version of Julia that it supports.

**Comment by robertdj** [comment]
I'll check that out! 

Sorry about the trouble -- it's my first attempt at registering a package. 
Would happen to know how to look into the travis problem? The testing works fine on my local machine.

**Comment by tkelman** [comment]
The Travis failure here is because the package doesn't have any tagged versions, but if you tagged any versions in the current state it would fail due to the lack of a REQUIRE file.

You should go to travis-ci.org and enable Travis for the repository itself, so you can see a status indicator on master at https://github.com/robertdj/SparseGrids.jl/branches - a few more changes to get that passing on the self-contained Travis VM's from a clean install (including dependency packages), then it'll be ready to tag a version and finish registering. We're happy to walk you through any steps where you need help.

**Comment by robertdj** [comment]
I'm done with most of the guidelines, but I have problems with `Pkg.publish()` that throws the error `ERROR: KeyError: SparseGrids not found`.

Before running `Pkg.publish` Julia instructed me to update packages. This gave the error

	WARNING: julia is fixed at 0.4.0-rc1 conflicting with requirement for SparseGrids: [0.4.0,∞)

(The package *is* located in `~/.julia/v0.4/SparseGrids`.)

Obviously the `rc` version is not considered to be greater than 0.4, but how do I specify that that 0.4.0-rc1 is a valid version?

I didn't know about `Pkg.tag` before reading the guide and I added an arbitrary version (0.1) to make Travis succeed. Should I remove this tag?

Thanks for your help!

**Comment by tkelman** [comment]
You may need to use the 0.4.0 release, or change the require to 0.4.0-rc1

You haven't pushed any tags to any branches that are visible in this pull request yet, but yes if you added tags manually to your local metadata copy (not from Pkg.tag) you should probably get rid of them.

**Comment by robertdj** [comment]
I'm still having some problems...

Registering seems to work fine:

	julia> Pkg.register("SparseGrids", "https://github.com/robertdj/SparseGrids.jl")
	INFO: Registering SparseGrids at https://github.com/robertdj/SparseGrids.jl
	INFO: Tagging SparseGrids v0.1.0
	INFO: Committing METADATA for SparseGrids

But publishing fails:

	julia> Pkg.publish()
	INFO: Validating METADATA
	INFO: Pushing SparseGrids permanent tags: v0.1.0
	INFO: Submitting METADATA changes
	INFO: Forking JuliaLang/METADATA.jl to robertdj
	INFO: Could not authenticate with existing token. Deleting token and trying again.
	Enter host password for user 'robertdj':
	INFO: Retrieving existing GitHub token. (You may have to re-enter your password.)
	Enter host password for user 'robertdj':
	ERROR: forking JuliaLang/METADATA.jl failed: Bad credentials
	in error at ./error.jl:21
	in fork at pkg/github.jl:144
	in pull_request at pkg/entry.jl:327
	in publish at pkg/entry.jl:394
	in anonymous at pkg/dir.jl:31
	in cd at file.jl:22
	in cd at pkg/dir.jl:31
	in publish at pkg.jl:61

**Comment by tkelman** [comment]
Hm, what version of Julia did you try to run that from? You could try manually pushing the local commits to your fork.

**Comment by robertdj** [comment]
julia> versioninfo()
	Julia Version 0.4.0-rc1
	Commit e5c6964 (2015-09-09 16:07 UTC)
	Platform Info:
	System: Darwin (x86_64-apple-darwin14.5.0)
	CPU: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz
	WORD_SIZE: 64
	BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
	LAPACK: libopenblas
	LIBM: libopenlibm
	LLVM: libLLVM-3.3

**Comment by robertdj** [comment]
Sorry about my long absence. I've pushed changes to my local version of METADATA as you suggested.
I still get Travis errors in this pull request, although the package repository works fine.

**Comment by tkelman** [comment]
Yes. You have a bunch of unrelated commuts in this pull request now, so it needs to be rebased and force pushed. You can modify the url in a new commit.

**Comment by robertdj** [comment]
I've rebased and force pushed, but I don't know what I should modify: As mentioned, my `.travis.yml` file looks correct and succeeds as seen on [Travis](https://travis-ci.org/robertdj/SparseGrids.jl).

I'm sorry about the trouble I'm causing. (And my long response times; I've just started on paternity leave and only have limited time for non-baby issues)

**Comment by tkelman** [comment]
It's no trouble at all, happy to walk you through the steps here at whatever pace you have time for. You should be able to just edit https://github.com/robertdj/METADATA.jl/blob/metadata-v2/SparseGrids/url to add a `.git` suffix.

**Comment by robertdj** [comment]
It finally seems to have passed :-) Should I close this now?

**Comment by tkelman** [comment]
Almost, very close here. Your "Resolving conflict" commit was a merge. I suspect what happened is you tried a non-force push, that failed and said you needed to merge with the remote branch, which brought in unrelated changes that we don't want. Try the rebase again and check that you only have one copy of your commits here, then do a `git push --force` to your fork.

**Comment by robertdj** [comment]
That sounds about right. I'm having some problems merging my GitHub METADATA with my local METADATA. Let me see if I can fix it.

**Comment by tkelman** [comment]
Avoid merging, force pushing will resolve the conflicts just fine. If anything goes wrong there are ways to recover it all.

**Comment by robertdj** [comment]
Should I force push even when my Git history looks like this (the gh/metadata-v2 is the one on my GitHub):

screen shot 2015-10-20 at 23 02 50

This is **after** a `git rebase`.

**Comment by tkelman** [comment]
Not quite, you have some duplicates there. Do another rebase and only pick one copy of each of your commits.

**Comment by tkelman** [comment]
Sorry I think I misread that. The red line looks good.

**Comment by robertdj** [comment]
It did take some time to compile last time... But hopefully the rebase/pushing is working out.

**Comment by tkelman** [comment]
This time looks great. Thanks for sticking with it, git can be frustrating to work with. +1 to merge when Travis gives the green light.

**Comment by robertdj** [comment]
Thanks a lot for all your help! I would really be lost on my own. 
Next time I'll stick closely to the package registration policy from the beginning :-)

**Pull request merged**
