### PR TITLE
Tag BoundingBoxes v0.1.0

### PR DESCRIPTION
**Pull request by sjkelly**
Fixes issues in my prior commit.

### CODE REVIEW

**Comment by IainNZ** [comment]
Looks like Travis timed out due to no output - maybe it should print something?

**Comment by sjkelly** [comment]
The remote changed for this package. How should I update it?

**Comment by garborg** [comment]
I believe I've always just changed it [here](https://github.com/JuliaLang/METADATA.jl/blob/7ba318dd1131afa01ed750f995ad737d616b39e0/BoundingBoxes/url) the next tag after the remote changed.

**Comment by sjkelly** [comment]
I tried it here: https://github.com/JuliaLang/METADATA.jl/pull/2352

**Comment by garborg** [comment]
Missed that -- then I'd guess the timeout there isn't the fault of your PR.

**Pull request merged**
