### PR TITLE
Tag DocStringExtensions.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDocs/DocStringExtensions.jl](https://github.com/JuliaDocs/DocStringExtensions.jl)
Release: [v0.6.0](https://github.com/JuliaDocs/DocStringExtensions.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDocs/DocStringExtensions.jl/builds/456342364)
Diff: [vs v0.5.0](https://github.com/JuliaDocs/DocStringExtensions.jl/compare/8e9da56adf4b6b5b6380d05c28f43e8b2d922f0c...1668567d66be799e5f94a577bf6d8bc564ca8c7d)
`requires` vs v0.5.0: no changes
cc: @fredrikekre

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by fredrikekre** [comment]
I can't make any sense of the failures, the logs are cut off?

**Comment by andreasnoack** [comment]
The log file here is merged together from several logs. Did you look at the error messages in the top of the log file (before the output from the registry update)?

**Comment by fredrikekre** [comment]
Yea, e.g. here: https://juliarun-ci.s3.amazonaws.com/a7cee073d59659377ee40c5858a710c20c8729ea/DocumenterTools_with_pull_request_of_DocStringExtensions_on_julia_1_0.log says that `DocumenterTools` passed its tests.

**Comment by fredrikekre** [comment]
And same with the Documenter one AFAICT.

**Comment by andreasnoack** [comment]
I was thinking of the DocStringExtensions tests here https://juliarun-ci.s3.amazonaws.com/a7cee073d59659377ee40c5858a710c20c8729ea/pull_request_of_DocStringExtensions_on_julia_1_0.log

**Comment by fredrikekre** [comment]
Ah, thanks. Looks like we need to modify tests since packages are not git repos anymore.

**Pull request merged**
