### PR TITLE
Register RleVectors

### PR DESCRIPTION
**Pull request by phaverty**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
This is really cool.

Any chance you would consider calling it RLEVectors? We usually keep caps within acronyms (cf. GLMNet.jl).

**Comment by phaverty** [comment]
Thanks, I'm glad you like it.

I'm open to the change. I think I have a bit of manual reading to do in
order to effect the change on GitHub, unless there is a "rename repository"
button. I can probably have a go at it in the morning.

Best,

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by phaverty** [comment]
I guess there actually was a "rename repository" button. Done. I'll do some
s/RleVectors/RLEVectors/g on the documentation in the morning.

Thanks again,

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by tkelman** [comment]
Don't forget the filename either, changing a file name only in the case can confuse some file systems

**Comment by phaverty** [comment]
OK, I have changed the repository name and changed the name of the
RleVector type to RLEVector throughout the code and documentation. All
tests pass. I think I'm good to go.



Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by phaverty** [comment]
Thanks, I have changed src/RleVectors.jl to src/RLEVectors.jl.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by IainNZ** [comment]
Great! What I'll do is merge this pull request, then manually change the capitalization myself. You'll need to "tag" a version though before people can Pkg.add it, of course.
@dcjones this is BioJulia-ish, something to maybe include there long-term?

**Comment by IainNZ** [comment]
https://github.com/JuliaLang/METADATA.jl/commit/c36b2980d4bfd2804bf30b34d896ab7fcc3e9cb4

very handy SO question/answer: http://stackoverflow.com/questions/3011625/git-mv-and-only-change-case-of-directory

**Comment by phaverty** [comment]
Yes, very helpful, thanks. I have renamed src/RLEVectors.jl using this
trick. I've tagged RLEVectors as 0.0.1.  I think I'm good to go.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by IainNZ** [comment]
Ah when I say tagged, I mean tagged in METADATA using the `Pkg.tag` then `Pkg.publish`

**Comment by phaverty** [comment]
Oops thanks for the correction! I left out the Pkg.publish part.  Done.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by tkelman** [comment]
(incidentally, `Pkg.publish` will get much faster in 0.3.9, binaries of which should be ready shortly)

**Pull request merged**
