### PR TITLE
Tag Query.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidanthoff/Query.jl](https://github.com/davidanthoff/Query.jl)
Release: [v0.8.0](https://github.com/davidanthoff/Query.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/davidanthoff/Query.jl/builds/304817175)
Diff: [vs v0.7.2](https://github.com/davidanthoff/Query.jl/compare/ca1b176326840c9e4c622fb3e068294fbdf88e27...a86e728b83c2f5af6805c4f511b8619b0676e48e)
`requires` vs v0.7.2: 
```diff
--- 0.7.2/requires
+++ 0.8.0/requires
@@ -1,9 +1,9 @@
 julia 0.6.0
 TableTraits 0.0.1
 NamedTuples 3.0.2
-DataStructures 0.4.5
 Requires 0.4.3
 Documenter 0.9.0
 IterableTables 0.5.0
 DataValues 0.0.2
 MacroTools 0.3.7
+QueryOperators 0.0.1
```
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by davidanthoff** [comment]
JuliaCIBot error will be fixed by https://github.com/JuliaLang/METADATA.jl/pull/12097.

**Comment by kshyatt** [comment]
Closing and reopening to try to get CI to start again?

**Comment by davidanthoff** [comment]
Hm, I think the JuliaCIBot message is a false positive. The log seems to indicate that it is trying to run LazyQuery v0.1.3 with Query v0.8.0, but that should not happen, given that https://github.com/JuliaLang/METADATA.jl/pull/12097/ was merged. Looks to me as if JuliaCIBot might actually not honor those upper bounds in its testing routine. I would just merge it.

**Comment by kshyatt** [comment]
Can I get a yea/nay on merging from @simonbyrne or someone more familiar with JuliaCIBot?

**Comment by davidanthoff** [comment]
@aviks Do you know what is going on here?

**Comment by aviks** [comment]
Yeah, JuliaCIBot has issues with recently specified upper bounds. We made some changes, but clearly not enough. Will investigate. 

cc: @nkottary

**Comment by davidanthoff** [comment]
Alright, can we then just merge this?

**Comment by kshyatt** [comment]
Not until CIBot/Travis passes, I think. Sorry :(

**Comment by aviks** [comment]
Just waiting for Travis to finish. The travis queue is backed up. While JuliaCIBot is currently optional, Travis is required.

**Comment by davidanthoff** [comment]
Great, thanks!

**Pull request merged**
