### PR TITLE
Register new package LibCSFML.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMultimedia/LibCSFML.jl](https://github.com/JuliaMultimedia/LibCSFML.jl)
Release: [v0.1.0](https://github.com/JuliaMultimedia/LibCSFML.jl/releases/tag/v0.1.0)
cc: @Gnimuc

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@Gnimuc This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by wookay** [comment]
at the ci logs https://travis-ci.org/JuliaLang/METADATA.jl/jobs/486887095#L511
> To fix this error, change the UUID to be "fa3694d3-b849-58b5-b76d-e00022040519" and retag.

you should change the uuid https://github.com/JuliaMultimedia/LibCSFML.jl/blob/master/Project.toml#L2

**Comment by Gnimuc** [comment]
thanks for pointing that out! I've retagged the release.

**Comment by Gnimuc** [comment]
bump, ready to merge?

**Comment by Gnimuc** [comment]
hi @andreasnoack, sorry for pinging you here, but it looks like this package was missed in the PR list.

**Comment by andreasnoack** [comment]
Please see https://discourse.julialang.org/t/the-current-metadata-release-process/16672 for to avoid delays when releasing a package.

Are you sure that you want the `Lib` part of the name and not just call it `CSFML`. That is the most common way of naming wrapper packages.

**Comment by Gnimuc** [comment]
aha, I totally missed that discourse post. Thanks for pointing that out! I think `Lib`-prefixed packages somewhat imply they're one-to-one mapped to the original API without any abstraction and these packages are often auto-generated using Clang.jl, e.g. [LibCURL](https://github.com/JuliaWeb/LibCURL.jl).

**Comment by Gnimuc** [comment]
IIUC, what I need to do is just retagging the release and leave no further comments?

**Comment by andreasnoack** [comment]
> I think `Lib`-prefixed packages somewhat imply they're one-to-one mapped to the original API without any abstraction and these packages are often auto-generated using Clang.jl, e.g. [LibCURL](https://github.com/JuliaWeb/LibCURL.jl).

I'm not sure that is the case (but I might be wrong). In the `LibCURL.jl` case, though, the name of the wrapped library is `libcurl` whereas the name of the library you are wrapping is `CSFML`.

> IIUC, what I need to do is just retagging the release and leave no further comments?

Yes. That should be sufficient once you made a decision wrt the name.

**Comment by Gnimuc** [comment]
I changed the package name to `CSFML`, which triggers autobot to open a new PR, so this can be closed.

**Pull request closed without merging**
