### PR TITLE
Register Bukdu

### PR DESCRIPTION
**Pull request by wookay**
Hello,
Bukdu is a web development framework.
It's influenced by Phoenix framework.

It can be running on Heroku something like
https://bukdu.herokuapp.com/

thanks!

### CODE REVIEW

**Comment by tkelman** [comment]
Neat! Just curious, does the name mean anything? That's a fun word to say.

**Comment by wookay** [comment]
It's from the name of Korean constellation "The Big Dipper".
https://ko.wikipedia.org/wiki/북두칠성

The Big Dipper (US) or Plough (UK) is an asterism consisting of the seven brightest stars of the constellation Ursa Major.
https://en.wikipedia.org/wiki/Big_Dipper

**Comment by tkelman** [comment]
That's great, today I learned.

Reminds me, I wonder whether everything would work correctly if someone tried to generate and register a package with a unicode name. I guess we should be prepared for that eventuality.

**Comment by wookay** [comment]
thank you!

**Comment by KristofferC** [comment]
In Sweden we consider it a wagon :)

**Pull request merged**
