### PR TITLE
Tag TextAnalysis v0.0.2

### PR DESCRIPTION
**Pull request by aviks**
@johnmyleswhite is this OK?

### CODE REVIEW

**Comment by jiahao** [comment]
Could use a `julia 0.3` entry in REQUIRE

**Comment by IainNZ** [comment]
Better than nothing

**Comment by aviks** [comment]
Thanks @IainNZ . 

I was mainly waiting for John's comment since I thought it would be bad form to tag a package without the maintainer's knowledge.

**Comment by johnmyleswhite** [comment]
Sorry, I'm too busy with work these days to keep up with most e-mails with anything less than a several week delay.

**Pull request merged**
