### PR TITLE
Tag TSne.jl v1.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lejon/TSne.jl](https://github.com/lejon/TSne.jl)
Release: [v1.1.0](https://github.com/lejon/TSne.jl/releases/tag/v1.1.0)
Travis: [Travis Build Status](https://travis-ci.org/lejon/TSne.jl/builds/328801641)
Diff: [vs v1.0.0](https://github.com/lejon/TSne.jl/compare/ded85efa5d47cc8d9dbb5d58b773ed58f4e414df...a88ed686734a8acd9531fd3fd8d41127d7054233)
`requires` vs v1.0.0: 
```diff
--- 1.0.0/requires
+++ 1.1.0/requires
@@ -1,2 +1,3 @@
 julia 0.6
+Distances
 ProgressMeter
```
cc: @alyst

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by alyst** [comment]
Travis failure looks strange
```
ERROR: LoadError: LoadError: Do not modify existing published tag sha1 files (policy 8).
Ask for an exception if absolutely necessary, but tag commits
should be immutable once published for reproducibility.
Stacktrace:
 [1] macro expansion at /home/travis/build/JuliaLang/METADATA.jl/.test/check-pr.jl:75 [inlined]
 [2] anonymous at ./<missing>:?
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
while loading /home/travis/build/JuliaLang/METADATA.jl/.test/check-pr.jl, in expression starting on line 72
while loading /home/travis/build/JuliaLang/METADATA.jl/.test/METADATA.jl, in expression starting on line 237
```

**Comment by alyst** [comment]
Same travis error

**Comment by alyst** [comment]
Unfortunately, I don't have permissions to open/close the issue myself to check whether the SHA problem is gone.

**Comment by aviks** [comment]
Travis is really really slow now unfortunately. Will restart this once it stabilises.

**Pull request merged**
