### PR TITLE
Tag ODBC v0.3.11

### PR DESCRIPTION
**Pull request by nkottary**
Tag ODBC v0.3.11

### CODE REVIEW

**Comment by ViralBShah** [comment]
cc @quinnj

**Comment by tkelman** [comment]
Do not merge, this is broken on 0.3: https://github.com/JuliaDB/ODBC.jl/pull/110

**Comment by tkelman** [comment]
If you want to drop 0.3 support to avoid breaking existing users on 0.3, then you can change the package's `REQUIRE` file to say `julia 0.4` as a minimum and tag the package as 0.4.0 via `Pkg.tag("ODBC", :minor)`

**Comment by quinnj** [comment]
I'd rather we still support 0.3 for this tag. My overhaul branch is almost done that will be 0.4 only. I'll try to take a look into what we need to do for 0.3 this weekend.

**Comment by ViralBShah** [comment]
Closing this one for now.

**Pull request closed without merging**
