### PR TITLE
Pull request/0d62b566

### PR DESCRIPTION
**Pull request by dehann**
After several requests, the plotting functions for [KernelDensityEstimate.jl](https://github.com/dehann/KernelDensityEstimate.jl) is being separated out into a stand-alone plotting repo:

[KernelDensityEstimatePlotting.jl](https://github.com/dehann/KernelDensityEstimatePlotting.jl)
[v0.0.1](https://github.com/dehann/KernelDensityEstimatePlotting.jl/releases/tag/v0.0.1)
[Build Status](https://travis-ci.org/dehann/KernelDensityEstimatePlotting.jl)

I will follow up this PR with an update to KernelDensityEstimate.jl, and update downstream packages such as [RoME](http://www.github.com/dehann/RoME) accordingly.

### CODE REVIEW

**Comment by aviks** [comment]
Tests fail with

```
ERROR: LoadError: LoadError: UndefVarError: VectorRange not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
while loading /mnt/pkgevalempty/0d62b566e066a1506c69df24af22b48961369139/.julia/v0.6/KernelDensityEstimatePlotting/src/KernelDensityEstimatePlotting.jl, in expression starting on line 208
while loading /mnt/pkgevalempty/0d62b566e066a1506c69df24af22b48961369139/.julia/v0.6/KernelDensityEstimatePlotting/test/runtests.jl, in expression starting on line 2
```

**Comment by dehann** [comment]
Fixed `VectorRange` issue and adding KernelDensityEstimate.jl update to this PR:

[KernelDensityEstimate.jl](https://github.com/dehann/KernelDensityEstimate.jl)
[v0.3.0](https://github.com/dehann/KernelDensityEstimate.jl/releases/tag/v0.3.0)
[Build Status](https://travis-ci.org/dehann/KernelDensityEstimate.jl)
[Diff v0.2.6 -> v0.3.0](https://github.com/dehann/KernelDensityEstimate.jl/compare/85fb606...bf999459)

**Comment by dehann** [comment]
Please restart the tests, I forgot to push the new tags to their upstream repos. Both `KernelDensityEstimate.jl v0.3.0`, and `KernelDensityEstimatePlotting.jl v0.0.1`

**Comment by dehann** [comment]
I think it is still showing the same issue on `VectorRange`. Will get back to you...

**Comment by dehann** [comment]
Okay, I have the issue. JuliaCIBot is pulling in:

`INFO: Installing KernelDensityEstimate v0.2.6`

but the issue is fixed in the new tag `v0.3.0`. Please see the reference comment I included above. According to me this merge should be good to go.

Thanks!

**Comment by dehann** [comment]
Or directly here: [export VectorRange](https://github.com/dehann/KernelDensityEstimate.jl/commit/bf999459c928c4c9bb3089043c836b48fa1ad8df#diff-f1f23c1bff2356b279e27fb7c8ed1dffR50)

**Comment by aviks** [comment]
Yeah, JuliaCIBot cannot handle two packages being updated in one PR :(

**Pull request merged**
