### PR TITLE
Tag FileIO v0.1.3 [https://github.com/JuliaIO/FileIO.jl]

### PR DESCRIPTION
**Pull request by timholy**
Changes:
- add missing BigTIFF magic bytes (@romainFr)
- prevent StackOverflow if `load`/`save` is not defined by a module (@timholy)

### CODE REVIEW

**Comment by tkelman** [comment]
@alyst looks like RData is having trouble with this? e.g. http://pkg.julialang.org/logs/FreqTables_0.4.log

**Comment by tkelman** [comment]
ImagineFormat too http://pkg.julialang.org/logs/ImagineFormat_0.4.log

**Comment by alyst** [comment]
It seems like the problem is that `RData` exports `load`, and then the new 0.1.3 `FileIO` check fails, because `RData.load == FileIO.load`.
I'm not sure how to properly fix that. I would like to preserve the current behaviour: `using RData` makes `FileIO.load(filename::String)` available for the user. Maybe `FileIO` check could be a little bit more elaborated and look for the existence of the specific signature?

**Comment by timholy** [comment]
This might be fixed by https://github.com/JuliaIO/FileIO.jl/pull/84. There are some downsides to this approach, unfortunately---this is getting to be quite a hack. What are the odds of forcing users to say `using FileIO`? I recognize that may not be ideal, either.

Cleanest would be to get https://github.com/JuliaLang/julia/issues/14472.

**Pull request merged**
