### PR TITLE
Register new package OpenBCI_WiFi.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [wherrera10/OpenBCI_WiFi.jl](https://github.com/wherrera10/OpenBCI_WiFi.jl)
Release: [v0.0.1](https://github.com/wherrera10/OpenBCI_WiFi.jl/releases/tag/v0.0.1)
cc: @wherrera10

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@wherrera10 This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Package names should not contain underscores. "WiFi" seems redundant in the package name in any case.

**Comment by wherrera10** [comment]
Underslashes as well as hyphens? I can remove the _ and re-release as a new
version, and just did :-) .
There is a version of the EEG hardware that uses BlueTooth, not Wifi, so
this lets the user know what hardware type is required for the software.

**Comment by dpsanders** [comment]
But you presumably wouldn't make a new package for the Bluetooth version?
Rather a single package could handle either.

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
