### PR TITLE
Release RDatasets version 0.5.0

### PR DESCRIPTION
**Pull request by andreasnoack**
Apparently, Attobot isn't enabled for the repo and the owner isn't active so I'm releasing this manually while we are waiting for a proper solution.

### CODE REVIEW

**Comment by andreasnoack** [comment]
CIbot fails because of a project file in Nullables. See https://github.com/JuliaAttic/Nullables.jl/pull/18

**Comment by andreasnoack** [comment]
CIBot now fails because of the project file in Mocking so let's ask @omus if he'd be okay with deleting the file for the time being until CIBot has been updated to the new package manager.

**Comment by omus** [comment]
It should be fine to delete (although it seems a bit silly). Can I just delete it on `master` or do I need a new tag?

**Comment by andreasnoack** [comment]
Thanks. It would have to be a new release. I agree that this isn't optimal but I think reverse dependency testing is important and we don't know yet when CIBot will work with the new package manager.

**Comment by omus** [comment]
Should be addressed by: https://github.com/JuliaLang/METADATA.jl/pull/17490

**Pull request merged**
