### PR TITLE
Tag FortranFiles.jl v0.4.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [traktofon/FortranFiles.jl](https://github.com/traktofon/FortranFiles.jl)
Release: [v0.4.2](https://github.com/traktofon/FortranFiles.jl/releases/tag/v0.4.2)
Travis: [Travis Build Status](https://travis-ci.org/traktofon/FortranFiles.jl/builds/414831874)
Diff: [vs v0.4.1](https://github.com/traktofon/FortranFiles.jl/compare/c926fe87c4a4c0d8e9d3a78ed8cf8c7986ac7b59...181f45a2a5ac3fece3af88f5be260725903b6bc1)
`requires` vs v0.4.1: 
```diff
--- 0.4.1/requires
+++ 0.4.2/requires
@@ -1,2 +1,2 @@
 julia 0.6
-Compat 0.59
+Compat 0.66
```
cc: @traktofon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by traktofon** [comment]
Hmm it says waiting for author. Ok, I'm here now. What should I do? AFAICT my package passes Travis CI on Julia 0.6/0.7/1.0 but the Metadata didn't? I'm afraid I don't know how to correct it.

**Comment by andreasnoack** [comment]
Please read the error log for the failing Travis tests here.

**Comment by traktofon** [comment]
I'm lost. The Travis log I can see says that the build was cancelled.

I'm giving up on this for now. I have deleted this release and tag in my repository. Please close this PR. I will revisit this some time in the future.

**Comment by andreasnoack** [comment]
That is my fault. I'm also trying to fix some issues with our CI. Please try to tag this again later today and we can look into why it is failing.

**Comment by traktofon** [comment]
Thanks for your reply. I'll be away for some days and will try again afterwards.
Good luck with the CI and thank you for your hard work!

**Pull request closed without merging**
