### PR TITLE
Pull request/a5f115df

### PR DESCRIPTION
**Pull request by latticetower**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I'm excited to have a miniKanren implementation in Julia!

**Comment by latticetower** [comment]
And I'm excited to hear such feedback from you =)

me being glad like Katya Managan

**Comment by StefanKarpinski** [comment]
Now there's a chance I could get @webyrd to do some Julia hacking ;-)

**Comment by webyrd** [comment]
Yay!  :)

**Pull request merged**
