### PR TITLE
Register Maker: v0.2.1

### PR DESCRIPTION
**Pull request by tshort**
This package is a make-like system for data analysis. It's geared more towards data analysis than Makefile-style building. To support code and data dependencies, the package includes a way to save some state between sessions.

https://github.com/tshort/Maker.jl

### CODE REVIEW

**Comment by tkelman** [comment]
Could you do a rebase to get rid of the merge commit that touches 119 files?

**Comment by tshort** [comment]
Sure, but rebasing for me usually means "start over":( 

I just used what `Pkg.register/publish()` produced. I guess I didn't realize the disruption because the pull request only shows 7 files changed.

**Comment by tkelman** [comment]
Or just checkout e807583c65ffa4e6d8d054b466f4e46e35d0b127 to its own branch and open a pull request from that point, a rebase isn't strictly necessary. I wouldn't think `Pkg.publish` would do a merge commit, but I'll have to check.

**Comment by tshort** [comment]
You're probably right. `Pkg.publish` didn't finish, so I probably did that
damage.

**Comment by tshort** [comment]
Does that look okay @tkelman? 

I checked out https://github.com/JuliaLang/METADATA.jl/commit/e807583c65ffa4e6d8d054b466f4e46e35d0b127 and force-pushed it to my METADATA.jl.

**Comment by tkelman** [comment]
Looks perfect, thanks!

**Comment by tshort** [comment]
Thanks @tkelman. I appreciate your help here, and I appreciate all the work you do to keep the wheels turning by keeping Pkg commits going and by reviewing code!

**Pull request merged**
