### PR TITLE
Tag LuxurySparse.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [QuantumBFS/LuxurySparse.jl](https://github.com/QuantumBFS/LuxurySparse.jl)
Release: [v0.2.0](https://github.com/QuantumBFS/LuxurySparse.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/QuantumBFS/LuxurySparse.jl/builds/424014110)
Diff: [vs v0.1.2](https://github.com/QuantumBFS/LuxurySparse.jl/compare/e9d48b9434936d57604ce7b12bce3eb1b1f213c5...26824e318d1691d7665d8578288e155ea85c5f1d)
`requires` vs v0.1.2: no changes
cc: @Roger-luo

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
CIBot fails because of the project file. Since the project file isn't needed, I'd recommend that you delete it because it will make it much easier to verify that the package works.

**Comment by Roger-luo** [comment]
Okay, so we should just delete Project.toml and wait for auto-generation?

**Comment by andreasnoack** [comment]
It is your decision but I'd recommend that you do it since it makes the release process easier and less error-prone for the time being.

**Comment by Roger-luo** [comment]
Alright, pls close this PR for me and I'll delete the Project.toml for now

**Comment by andreasnoack** [comment]
You can just delete and reapply the 0.2.0 tag on GitHub. That will automatically update this PR.

**Pull request merged**
