### PR TITLE
Register MultidimensionalTables: v0.0.1

### PR DESCRIPTION
**Pull request by c-s**
Hi,

I would like to register a new package "MultidimensionalTables", which provides a framework to handle multidimensional tables as generalized arrays.

Thanks.

C. S. Park

### CODE REVIEW

**Comment by tkelman** [comment]
If you only need RDatasets and FactCheck to run your tests, it may be preferable to list them ib `test/REQUIRE` instead of `REQUIRE`.

**Comment by c-s** [comment]
I removed RDatasets and FactCheck in REQUIRE and moved them in test/REQUIRE. I didn't know I could add a test specific requirement file.
I haven't published a new package before, so I have 2 questions:
    * I committed a new change in MultidimensionalTables.jl. Do I need to tag and publish again?
    * Do I need to update METADATA.jl/MultidimensionalTables/versions/0.0.1/requires ?

Thanks!

**Comment by tkelman** [comment]
You can either edit the requires and sha1 contents of the 0.0.1 tag at https://github.com/c-s/METADATA.jl/tree/pull-request/9bf6b063/MultidimensionalTables/versions/0.0.1 (updating the same branch of this pr will show up here) to be consistent with your latest commit, or you can make a new 0.0.2 tag. Either work since this hasn't been merged yet, it's up to you.

**Comment by tkelman** [comment]
closing in favor of https://github.com/JuliaLang/METADATA.jl/pull/4261 which has both 0.0.1 and 0.0.2 tags

**Pull request closed without merging**
