### PR TITLE
Register new package FieldMetadata.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rafaqz/FieldMetadata.jl](https://github.com/rafaqz/FieldMetadata.jl)
Release: [v0.0.1](https://github.com/rafaqz/FieldMetadata.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/rafaqz/FieldMetadata.jl/builds/432774899)
cc: @rafaqz

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@rafaqz This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks for all the name feedback, I think this is the most descriptive...

**Comment by rafaqz** [comment]
D'oh delete this. Just lost all the stars in the name change that makes no sense

**Comment by rafaqz** [comment]
Or maybe this will just work with the original repo that now has the same name? Attobot doesn't seem to be making a pull request from that release anyway, so I guess this is ok after all.

**Comment by andreasnoack** [comment]
Could you please remove and add the tag again. That will trigger a comment from Attobot. If the latest comment is from Attobot then the PR will be merged automatically after three days.

**Pull request merged**
