### PR TITLE
Register RawArray [https://github.com/davidssmith/RawArray.jl.git]

### PR DESCRIPTION
**Pull request by davidssmith**
Provides RawArray (RA) file format for simple, robust, and user-friendly N-dimensional array storage.

### CODE REVIEW

**Comment by tkelman** [comment]
Your .travis.yml is using an obsolete configuration. And it's not enabled.

**Comment by davidssmith** [comment]
Sorry it's been so long I forgot about all of that. Is it fixed now?

**Comment by tkelman** [comment]
should push the git tag so it shows up under https://github.com/davidssmith/RawArray.jl/releases

**Comment by davidssmith** [comment]
Done.

**Pull request merged**
