### PR TITLE
Update OEIS to v0.0.2

### PR DESCRIPTION
**Pull request by MurrayT**

### CODE REVIEW

**Comment by tkelman** [comment]
It's recommended to put `julia 0.3` in your REQUIRE file, assuming you are not testing your package with Julia 0.2 or earlier.

**Comment by MurrayT** [comment]
I'm having some issues with doing this any chance you could give me some help? I can't seem to work on the pr branch without ending up in detached head, so I can't commit and push any new changes successfully.

**Comment by tkelman** [comment]
If you've checkout out `pull-request/8404953f` from your fork and ended up in detached head, try `git checkout -b pull-request/8404953f` to create a corresponding local branch.

**Comment by MurrayT** [comment]
Thanks that seems to have worked

**Comment by tkelman** [comment]
Yep. Be sure to add it to https://github.com/MurrayT/OEIS.jl/blob/master/REQUIRE as well before your next tag.

**Pull request merged**
