### PR TITLE
Tag LegacyStrings.jl v0.2.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArchive/LegacyStrings.jl](https://github.com/JuliaArchive/LegacyStrings.jl)
Release: [v0.2.3](https://github.com/JuliaArchive/LegacyStrings.jl/releases/tag/v0.2.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArchive/LegacyStrings.jl/builds/304385357)
Diff: [vs v0.2.2](https://github.com/JuliaArchive/LegacyStrings.jl/compare/111de114d99d052928ab980955717cccabe58a2e...c19101a1009bf88f16582c8971cbc1968187ca2d)
`requires` vs v0.2.2: no changes
cc: @nalimilan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
Metadata is frozen for 0.4.

**Comment by nalimilan** [comment]
Ah, too bad. Though that policy is kind of weird since in the present case it involves more work than just keeping the support for that release. See https://github.com/JuliaArchive/LegacyStrings.jl/pull/26.

**Comment by kmsquire** [comment]
@nalimilan, I think it's okay to ask for an exception here...

**Comment by nalimilan** [comment]
Thanks @kmsquire, but I've dropped support for 0.4 so the work is done now. See https://github.com/JuliaLang/METADATA.jl/pull/12153.

**Pull request closed without merging**
