### PR TITLE
Tag FastRounding.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/FastRounding.jl](https://github.com/JeffreySarnoff/FastRounding.jl)
Release: [v0.2.0](https://github.com/JeffreySarnoff/FastRounding.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JeffreySarnoff/FastRounding.jl/builds/418019959)
Diff: [vs v0.1.2](https://github.com/JeffreySarnoff/FastRounding.jl/compare/122d308ca31bc035d255d32b5544caac30ed1413...69be31d18a831c2b8a0ccadeeb7465899ce552ff)
`requires` vs v0.1.2: no changes
cc: @JeffreySarnoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dpsanders** [comment]
This version does not work on Julia 0.6, which was not tested by Travis. What is the best path forward here?

**Comment by JeffreySarnoff** [comment]
as an oversight, I had left `julia v0.6` in the REQUIRE file -- although not testing v0.6 was intentional
The change that moved this repo's v0.1.x to v0.2.0 is the introduction and export of unicode infix ops that alias the already exported functional forms.

**Comment by JeffreySarnoff** [comment]
I have no objection to retroactively change the Julia version on release 0.2 to 0.7.
I am tagging and PRing for release v0.2.1 which has that change .
If substituting that for v0.2.0 works -- fine by me.  If your better solution does not need v0.2.1 just close the PR without merging and I will delete the tag and proposed release version on my end.

**Comment by rdeits** [comment]
I believe it would be advisable to modify the requirements for *this* tag, rather than just releasing v0.2.1. 

If the required Julia version for v0.2.0 is not fixed, then having a v0.2.1 will not resolve the problem, as the package manager will still try to install the (incompatible) v0.2.0 in Julia v0.6.

**Comment by JeffreySarnoff** [comment]
sounds right . Dear admin .. please ^

**Pull request merged**
