### PR TITLE
Register Metrics

### PR DESCRIPTION
**Pull request by paulhendricks**

### CODE REVIEW

**Comment by tkelman** [comment]
Needs a tagged version, otherwise it can't be added by `Pkg.add` yet

**Comment by paulhendricks** [comment]
Sounds good, I'll tag it and resubmit.

**Comment by lobingera** [comment]
@paulhendricks, Have you thought about a more specific name? Metrics is a broad term.

**Comment by paulhendricks** [comment]
I have considered that Metrics is a broad term. If it's not too long and verbose, MachineLearningMetrics would be a more specific name.

@lobingera What do you think of that?

**Comment by ssfrr** [comment]
perhaps ModelMetrics?

**Comment by lobingera** [comment]
from my perspective both MachineLearningMetrics and ModelMetrics are good choices. I just related to 
> Package names should be sensible to most Julia users, even to those who are not domain experts.

**Comment by paulhendricks** [comment]
Sounds good. I would prefer MachineLearningMetrics.jl to ModelMetrics.jl.

I'll edit the package as needed. Would you prefer I close this pull request and re-submit a new one or is there a better process? I'm unfamiliar with best practices for publishing to JuliaLang/METADATA.jl....

**Comment by lobingera** [comment]
@paulhendricks i'm not an expert
@tkelman guided me through my first registration

**Comment by kmsquire** [comment]
Either way works. The main thing we look for us a clean git history (e.g., no merge commits, no commits adding something removed in the following commit, etc).  So be sure to squash and/or start from a pristine metadata repo. Ask if you have questions.

**Comment by paulhendricks** [comment]
@kmsquire Thanks Kevin!

**Comment by lobingera** [comment]
@paulhendricks I hope i didn't stop your progress with asking for a clearer name ...

**Comment by paulhendricks** [comment]
@lobingera Not at all! I was actually working on it today. I am having some troubles registering it and tagging it but I'm confident I can create a new pull request today or tomorrow.

**Comment by paulhendricks** [comment]
Please see https://github.com/JuliaLang/METADATA.jl/pull/4920.

**Comment by tkelman** [comment]
This one should be closed then?

**Comment by paulhendricks** [comment]
Yes.

**Pull request closed without merging**
