### PR TITLE
Tag HDF5.jl v0.9.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIO/HDF5.jl](https://github.com/JuliaIO/HDF5.jl)
Release: [v0.9.0](https://github.com/JuliaIO/HDF5.jl/releases/tag/v0.9.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIO/HDF5.jl/builds/375008034)
Diff: [vs v0.8.8](https://github.com/JuliaIO/HDF5.jl/compare/29ac03e758fb1e5f9e799a81eef2e8c243a5d5cd...e51e2795fface3f413857d1ce24b722da1523ce9)
`requires` vs v0.8.8: 
```diff
--- 0.8.8/requires
+++ 0.9.0/requires
@@ -1,6 +1,6 @@
-julia 0.5
+julia 0.6
 BinDeps 0.6.0
 Blosc
-Compat 0.32.0
+Compat 0.61.0
 @osx Homebrew 0.3.1
 @windows WinRPM
```
cc: @musm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like tests are failing http://juliarun-ci.s3.amazonaws.com/bb7d9c8dafb0a96fa9f4dd2289dc64b550ca8c02/pull_request_of_HDF5_on_julia_0_6.log

**Comment by musm** [comment]
Looks like a homebrew failure ? https://travis-ci.org/JuliaIO/HDF5.jl/jobs/375941238#L360

**Comment by andreasnoack** [comment]
The link above has this error
```julia
plain: Error During Test
  Got an exception of type UndefVarError outside of a @test
  UndefVarError: h5do_write_chunk not defined
  Stacktrace:
   [1] do_write_chunk(::HDF5.HDF5Dataset, ::Tuple{UInt64,UInt64}, ::Array{UInt8,1}, ::UInt32) at /home/jrun/HDF5/.julia/v0.6/HDF5/src/HDF5.jl:1853
   [2] (::##17#35)(::HDF5.HDF5File) at /home/jrun/HDF5/.julia/v0.6/HDF5/test/plain.jl:370
   [3] #h5open#5(::Bool, ::Function, ::##17#35, ::String, ::Vararg{String,N} where N) at /home/jrun/HDF5/.julia/v0.6/HDF5/src/HDF5.jl:694
   [4] h5open(::Function, ::String, ::String) at /home/jrun/HDF5/.julia/v0.6/HDF5/src/HDF5.jl:692
   [5] macro expansion at /home/jrun/HDF5/.julia/v0.6/HDF5/test/plain.jl:367 [inlined]
   [6] macro expansion at ./test.jl:860 [inlined]
   [7] anonymous at ./<missing>:?
   [8] include_from_node1(::String) at ./loading.jl:576
   [9] include(::String) at ./sysimg.jl:14
   [10] include_from_node1(::String) at ./loading.jl:576
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
```
which doesn't look Homebrew related.

**Comment by musm** [comment]
Yeah, it's just that I haven't seen this error on Linux on Travis in the main repo.

Do I delete the tag and retag if I want to trigger another run on the travis in Metadata.jl?

**Comment by andreasnoack** [comment]
> Do I delete the tag and retag if I want to trigger another run on the Travis in Metadata.jl?

I just did it.

**Comment by andreasnoack** [comment]
I think the problem is https://github.com/JuliaIO/HDF5.jl/pull/456/files#r186633766

**Comment by musm** [comment]
updated https://github.com/JuliaLang/METADATA.jl/pull/14576 hopefully will fix it

please close this

**Comment by andreasnoack** [comment]
I can do that. Another time, you can just delete the old tag and add it again to the new commit. This is fine as long as the tag hasn't been registered in METADATA. The PR will be updated automatically.

**Pull request closed without merging**
