### PR TITLE
Register new package AcceleratedArrays.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [andyferris/AcceleratedArrays.jl](https://github.com/andyferris/AcceleratedArrays.jl)
Release: [v0.1.0](https://github.com/andyferris/AcceleratedArrays.jl/releases/tag/v0.1.0)
cc: @andyferris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@andyferris This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andyferris** [comment]
Not sure what the CI bot is complaining about? It didn't seem to install Indexing.jl (which is a dependency of a dependency) for whatever reason.

**Comment by andreasnoack** [comment]
It's because of the project file in SplitApplyCombine. CIBot isn't able to handle them yet but we are working on it. In the meantime, I'd recommend not using project files since it allows for reverse dependency testing but it is your decision.

**Comment by andyferris** [comment]
Unless there is something obvious that I’ve missed, project files seem to be the only sane way of dealing with multiple interdependent unregistered packages, so in general I’d prefer to keep them...

Couldn’t the CI bot just delete them (locally)?

**Comment by andreasnoack** [comment]
> Couldn’t the CI bot just delete them (locally)?

Ha. That is a pretty obvious solution. Let's try this out here.

**Comment by andreasnoack** [comment]
I'll continue these experiments in a test repo

**Comment by andreasnoack** [comment]
Sorry. This should actually not have been merged yet. Got carried away.

**Pull request merged**
