### PR TITLE
Register new package ImageTransformations.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaImages/ImageTransformations.jl](https://github.com/JuliaImages/ImageTransformations.jl)
Release: [v0.0.1](https://github.com/JuliaImages/ImageTransformations.jl/releases/tag/v0.0.1)
cc: @timholy

### CODE REVIEW

**Comment by tkelman** [comment]
enable CI?

**Comment by tkelman** [comment]
`test/REQUIRE` should have a minimum FixedPointNumbers 0.3.0 requirement since it's using the new names, right?

**Comment by Evizero** [comment]
I'll try and track down version requirements

**Comment by tkelman** [comment]
should be updated to include https://github.com/JuliaImages/ImageTransformations.jl/pull/6?

**Comment by Evizero** [comment]
Yes that is the plan. Will do as soon as time allows ~next couple days

**Pull request merged**
