### PR TITLE
Register OnlineStats: v0.1.0

### PR DESCRIPTION
**Pull request by joshday**

### CODE REVIEW

**Comment by quinnj** [comment]
woot. been waiting for this guy to land!

**Comment by IainNZ** [comment]
That is a wild set of dependencies, wow. Convex and SCS.
I shouldn't have merged though, just realized there isn't an explicit Julia version dependency - might be good to add for the next release?

**Comment by IainNZ** [comment]
Also, the code doesn't actually seem to use Convex and SCS, it looks commented out?

**Comment by joshday** [comment]
I will add a patch today removing those dependencies.  They were for a very experimental feature that is far from release.

**Comment by IainNZ** [comment]
:+1:

**Comment by milktrader** [comment]
Looking forward to this package. Nice.

**Pull request merged**
