### PR TITLE
Tag HDF5 v0.6.0

### PR DESCRIPTION
**Pull request by timholy**
Features:
- better Windows installation (@joa-quim)
- support file access properties when opening files (@eschnett)
- collect coverage statistics (@eschnett)
- install: allow building HDF5 from source (@eschnett)
- support HDF5 1.10 (@eschnett)
- fix various internal types (@eschnett)
- julia-0.5 suppport: delete duplicated methods, tests from reshape change (@eschnett, @timholy)

### CODE REVIEW

**Comment by joa-quim** [comment]
Hi,
I just want to warn about HDF5.10. Files created with it (and netCDF4 files fall in that category) cannot be read with previous HDF versions. This is a pretty big annoyance.

Joaquim

**Comment by timholy** [comment]
It goes both ways: https://github.com/JuliaLang/HDF5.jl/issues/298

For reference, which `libhdf5` versions are you comparing? Try this:
```jl
julia> HDF5._libversion
(1,8,11)
```
Presumably you can change the format like this: https://github.com/JuliaLang/HDF5.jl/issues/170#issuecomment-209399736. And it's quite possible (I keep hoping that someone affected by it will eventually test and report back...) that it solves the frequently-reported https://github.com/JuliaLang/HDF5.jl/issues/170. If so, it's powerful incentive to use the newer format by default.

@eschnett, you've followed this more closely than me, any thoughts?

**Comment by joa-quim** [comment]
Actually my remark was not based on a Julia usage but instead from another soft that indirectly uses HDF through ndtcDF. [Here ](http://gmt.soest.hawaii.edu/boards/1/topics/3495?r=3528#message-3528)we found that a mysterious failure to read a nc file was in fact due to the compatibility break introduced by HDF5.10

**Comment by timholy** [comment]
I would be possible to set it up so that the user can configure HDF5.jl to use a specific format. I don't have time to tackle this right now, though.

**Comment by eschnett** [comment]
When creating a file, one can choose whether to use the newest file format or not via properties (`H5F_LIBVER_EARLIEST`, `H5F_LIBVER_LATEST`). I thought the default was to be compatible, but I might be wrong -- the default might be to go for the improved performance.

One alternative is to run `h5format_convert` on the generated HDF5 file. This will convert the file in place, and is generally a very fast operation. Obviously the file remains readable by HDF5 1.10. This is what I usually do. `h5format_convert` is a utility that comes with HDF5 1.10.

Another compatibility hurdle is the `Blosc` compression filter that Julia uses; this can make datasets unreadable outside Julia.

**Pull request merged**
