### PR TITLE
Tag AbstractAlgebra.jl v0.0.9

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Nemocas/AbstractAlgebra.jl](https://github.com/Nemocas/AbstractAlgebra.jl)
Release: [v0.0.9](https://github.com/Nemocas/AbstractAlgebra.jl/releases/tag/v0.0.9)
Travis: [Travis Build Status](https://travis-ci.org/Nemocas/AbstractAlgebra.jl/builds/407033922)
Diff: [vs v0.0.8](https://github.com/Nemocas/AbstractAlgebra.jl/compare/a32a67d3cab13baf8f7589c1150c576423d1704b...cebd6b44f33b7020a924d02cd808984baba6436c)
`requires` vs v0.0.8: no changes
cc: @thofma

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by thofma** [comment]
Not sure why JuliaCIBot gives me a "Tests failed". All tests are passing.

**Comment by quinnj** [comment]
Closing & re-opening to have CI another run.

**Comment by thofma** [comment]
Something is wrong with the display of the test results. They all passed.

**Comment by thofma** [comment]
Can this be merged?

**Comment by thofma** [comment]
Bump.

**Pull request closed without merging**
