### PR TITLE
Register new package Nord.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [kylecarbon/Nord.jl](https://github.com/kylecarbon/Nord.jl)
Release: [v0.1.0](https://github.com/kylecarbon/Nord.jl/releases/tag/v0.1.0)
cc: @kylecarbon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@kylecarbon This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please be aware that you trigger CI runs each time you retag so it would be great to limit the number of times you retag.

**Comment by kylecarbon** [comment]
Ah, sorry! Will keep that in mind.

**Comment by kylecarbon** [comment]
Hmm, not sure why CI failed. It doesn't look like 0.7 has a log. and 1.0 tests passed for `Nord` but CIBot says it failed. Sorry for eating up CI resources...but should I re-tag the release and try again?

**Comment by andreasnoack** [comment]
Restarting the tests in a case like this is fine. I'll do it.

**Comment by kylecarbon** [comment]
@andreasnoack any chance of merging this? I'm not sure if there are certain qualifications a package must meet to be merged into `METADATA` but it'd be a (small) quality-of-life enhancement for me personally...

**Comment by andreasnoack** [comment]
Yes. It's ready to go.

**Comment by kylecarbon** [comment]
Thanks very much!

**Pull request merged**
