### PR TITLE
Tag LearnBase.jl v0.1.6

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaML/LearnBase.jl](https://github.com/JuliaML/LearnBase.jl)
Release: [v0.1.6](https://github.com/JuliaML/LearnBase.jl/releases/tag/v0.1.6)
Travis: [Travis Build Status](https://travis-ci.org/JuliaML/LearnBase.jl/builds/249914315)
Diff: [vs v0.1.5](https://github.com/JuliaML/LearnBase.jl/compare/984724e975e0b468e8b11a4f4c76b30a004ea1fe...9171d003eb8bc5d8eb01e947494fc0122c20ff21)
`requires` vs v0.1.5: 
```diff
--- 0.1.5/requires
+++ 0.1.6/requires
@@ -1,4 +1,3 @@
 julia 0.5
-StatsBase 0.8.0
+StatsBase 0.17.0
 Compat 0.18
-Distributions
```
cc: @Evizero

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
this caused a test failure in OnlineStats, cc @joshday https://pkg.julialang.org/logs/OnlineStats_0.6.log

**Comment by joshday** [comment]
The test failure is from 3 days ago.  I think it failed because something in the chain of
- add `params` to StatsBase
- make Distributions import `StatsBase.params`
- LearnBase removes Distributions dependency
- Make new releases for StatsBase, Distributions, and LearnBase

wasn't merged then.

**Comment by tkelman** [comment]
that ran on the latest releases of everything yesterday

**Comment by joshday** [comment]
I see.  I think Distributions needs a new release.  I've made the temporary fix in OnlineStats.  I'll make a new release when the travis builds finish.

**Pull request merged**
