### PR TITLE
Registering Pastebin.jl

### PR DESCRIPTION
**Pull request by molnarmark**
Got the package ready for using. Tests and documentation to be added soon.

Pastebin.jl is a wrapper around the official Pastebin REST API.

### CODE REVIEW

**Comment by tkelman** [comment]
This is missing Requests in REQUIRE

**Comment by molnarmark** [comment]
https://github.com/molnarmark/Pastebin.jl/blob/master/REQUIRE

Its there, if you meant that.

**Comment by tkelman** [comment]
not at the sha that was tagged here

**Comment by molnarmark** [comment]
Opening a new pull request would fix that, right? Sorry, bit new to contributing to open source.

**Comment by tkelman** [comment]
yes, a new tag of latest master should fix things

**Pull request merged**
