### PR TITLE
Minor version bumps of Tk, Winston, and ImageView

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
Is this error due to this PR, or a bug in `METADATA/.test/check-pr.jl`?

**Comment by tkelman** [comment]
bug, @ararslan how were you testing that? it needs to run in travis on real pr's to a fork of metadata to be representative.

**Comment by ararslan** [comment]
I was testing it on a local clone of METADATA, and I committed changes to the clone to simulate differences from `origin`. This particular error was an oversight on my part. I sincerely apologize for the disruptions.

**Comment by timholy** [comment]
No prob, just curious.

**Pull request merged**
