### PR TITLE
Register RigidBodyDynamics 0.0.1

### PR DESCRIPTION
**Pull request by tkoolen**
`RigidBodyDynamics` is a basic rigid body dynamics package implemented completely in Julia. See https://github.com/tkoolen/RigidBodyDynamics.jl/blob/master/examples/Mechanism.ipynb for some usage examples.

### CODE REVIEW

**Comment by tkelman** [comment]
You're using Compat at https://github.com/tkoolen/RigidBodyDynamics.jl/blob/v0.0.1/test/runtests.jl#L7, so should declare the dependency (with a minimum version requirement that implements the features you need) in either `REQUIRE` or `test/REQUIRE`

**Comment by tkoolen** [comment]
Good call. I don't actually need anything from Compat anymore, so I'll just get rid of the using statement.

**Comment by tkelman** [comment]
can tag that as an 0.0.2 then

**Comment by tkoolen** [comment]
Sounds good, thank you!

**Pull request merged**
