### PR TITLE
Register SMSSVD [https://github.com/rasmushenningsson/SMSSVD.jl.git]:… 

### PR DESCRIPTION
**Pull request by rasmushenningsson**
… v0.0.1

### CODE REVIEW

**Comment by andreasnoack** [comment]
We usually recommend that acronyms are avoided, see https://docs.julialang.org/en/stable/manual/packages/#Guidelines-for-naming-a-package-1.

Please also consider using https://github.com/attobot/attobot

**Comment by rasmushenningsson** [comment]
The name refers to a method presented in the paper "SMSSVD - SubMatrix Selection Singular Value Decomposition" (https://arxiv.org/abs/1710.08144).
Everyone I have discussed with refers to it as SMSSVD, and that's why I choose that name.
I could change it to SubMatrixSelectionSVD - do you think that is better?

**Comment by andreasnoack** [comment]
> Everyone I have discussed with refers to it as SMSSVD

The reason we have the guideline is to help people who are *not* familiar with the acronym. Hence, I think that `SubMatrixSelectionSVD` is a better name.

**Comment by rasmushenningsson** [comment]
That makes sense. I'll remove this one and create a new pull request.

**Pull request closed without merging**
