### PR TITLE
Register Qwt.jl

### PR DESCRIPTION
**Pull request by tbreloff**

### CODE REVIEW

**Comment by kshyatt** [comment]
Do you want `julia 0.4-` in `REQUIRE`, rather than `julia 0.4`?

**Comment by tbreloff** [comment]
I'm not sure. Would that imply that I support versions pre-AbstractFloat,
etc?

**Comment by kshyatt** [comment]
Well, you have `0.4-` now, which includes prereleases. But `0.4` release is out. My understanding was that `0.4` is preferred assuming the package works with the release (and not just the prereleases?).

**Comment by tbreloff** [comment]
I see... I had it backwards... Thought you were suggesting 0.4-.  Should I
tag 0.0.2 with the new REQUIRE?

**Comment by kshyatt** [comment]
You might be able to just modify the current tag and reopen? Sorry, it was my poor wording that's at fault here.

**Comment by tbreloff** [comment]
I force pushed a new require file with 0.4... please let me know if that looks ok.  Thanks!

**Comment by kshyatt** [comment]
This LGTM - anyone else have thoughts?

**Comment by milktrader** [comment]
:+1:

**Comment by tbreloff** [comment]
Thanks!

**Pull request merged**
