### PR TITLE
Register new package LEB128.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidssmith/LEB128.jl](https://github.com/davidssmith/LEB128.jl)
Release: [v0.0.2](https://github.com/davidssmith/LEB128.jl/releases/tag/v0.0.2)
cc: @davidssmith

### CODE REVIEW

**Comment by davidssmith** [comment]
The JuliaCIBot tests actually all passed, if you look at the log. There must be a problem with the bot.

**Comment by tkelman** [comment]
The package naming guidelines discourage using acronyms, spelling things out a bit makes it more obvious what the package is for.

**Comment by davidssmith** [comment]
LittleEndianBase128 seems awfully long.

**Comment by davidssmith** [comment]
OK I'm changing the name. This PR can be closed.

**Pull request closed without merging**
