### PR TITLE
Tag Compat.jl v0.30.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaLang/Compat.jl](https://github.com/JuliaLang/Compat.jl)
Release: [v0.30.0](https://github.com/JuliaLang/Compat.jl/releases/tag/v0.30.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaLang/Compat.jl/builds/262782812)
Diff: [vs v0.29.0](https://github.com/JuliaLang/Compat.jl/compare/b56640999f12d6d4a7f89e5deb72708f7c922fdf...5883a74bcd743bbee356c335df3d4afff1532556)
`requires` vs v0.29.0: no changes
cc: @ararslan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
Note that this deletes a function that Lint.jl had been using, so that will probably need upper bounds. cc @TotalVerb

**Comment by TotalVerb** [comment]
Which function has Lint been using? Lint tests pass (with lots of depwarns) with Compat master for me.

**Comment by tkelman** [comment]
rewrite_dict, guess the way it's used in a test isn't sensitive to it being deleted?

**Comment by TotalVerb** [comment]
Yeah, I don't think this particular kind of getfield is linted properly in the current version. Would be good to change anyway.

**Pull request merged**
