### PR TITLE
Register COBRA.jl - [PR/f3f0464f]

### PR DESCRIPTION
**Pull request by laurentheirendt**

### CODE REVIEW

**Comment by tkelman** [comment]
You should be listing test requirements in `test/REQUIRE`, instead of adding them only on CI.

**Comment by tkelman** [comment]
CC BY-NC-ND is also a fairly restrictive license, and not OSI approved: https://opensource.org/licenses/alphabetical

**Comment by rmtfleming** [comment]
Is Attribution-NonCommercial-ShareAlike 4.0 International acceptable? It is not on the OSI list, but the OSI list is not compatible with valorisation of research investment, which is a key criteria for our research funding.

**Comment by laurentheirendt** [comment]
Thanks @tkelman. Test requirements are now listed in `test/REQUIRE`.

**Comment by tkelman** [comment]
NC-SA is better than NC-ND, but restricting commercial use is unfortunate.

**Comment by johnmyleswhite** [comment]
To add to Tony's concerns, I think there's a reasonable argument that the Julia package manager should not make it easy to install software that they cannot use without violating laws. If we allow the package manager to distribute software that generally prohibits commercial use, we may want to default to prohibiting installation of that category of software until users explicitly opt in.

**Comment by laurentheirendt** [comment]
Thank you for your comments, @tkelman and @johnmyleswhite.

The license has been changed to GPL v3.

**Pull request merged**
