### PR TITLE
Tag Plots v0.9.5 [https://github.com/tbreloff/Plots.jl]

### PR DESCRIPTION
**Pull request by tbreloff**

### CODE REVIEW

**Comment by tbreloff** [comment]
Since this wasn't merged yet, I'm adding a fix for an issue with PlotThemes gradient names.

**Comment by tkelman** [comment]
These are both failing tests on Travis

**Comment by tbreloff** [comment]
PlotThemes tests pass on master (one tiny change to a test... no change to the package).  I don't think the Plots tests will pass until PlotThemes is tagged, but they pass locally.

**Comment by tkelman** [comment]
Best to re-tag or make a new PlotThemes tag that includes the test fix then

**Comment by tbreloff** [comment]
Or... you could just merge this and I'll restart travis.

**Comment by tkelman** [comment]
restarting travis on plotthemes won't make a difference, the version you tagged here fails its tests - it only has one dependency

**Comment by tbreloff** [comment]
I'm not tagging again anytime soon, so send people to the gitter if they have trouble

**Comment by tkelman** [comment]
I don't understand what the problem was here. If you already fixed the issue, just adjust the sha and the git tag, or add a new one.

**Pull request closed without merging**
