### PR TITLE
Tag WebSockets.jl v0.3.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaWeb/WebSockets.jl](https://github.com/JuliaWeb/WebSockets.jl)
Release: [v0.3.3](https://github.com/JuliaWeb/WebSockets.jl/releases/tag/v0.3.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaWeb/WebSockets.jl/builds/307047883)
Diff: [vs v0.3.0](https://github.com/JuliaWeb/WebSockets.jl/compare/78987bdcc58950b2a314ffff9e93da9f041e1bc8...9570932ba379a8c0756ba98f7f5e777c6d581816)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.3.3/requires
@@ -1,6 +1,6 @@
-julia 0.4
-Compat 0.9.5
-HttpCommon 0.0.3
-HttpServer 0.0.4
+julia 0.5
+Compat 0.28.0
+HttpCommon
+HttpServer
 Codecs
 MbedTLS
```
cc: @hustf

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
> LoadError: New tag 0.3.3 of package WebSockets requires julia 0.5.0, but version 0.3.0 of WebSockets requires julia 0.4.0. Use a new minor package version when support for an old version of Julia is dropped. Re-tag the package as 0.4.0 using `PkgDev.tag("WebSockets", :minor)`.

**Comment by hustf** [comment]
My bad. 
I normally use git directly from git bash.  My  cygwin terminal isn't fully set up with credentials , so that may be the explanation for the message below. From Julia 0.6.1 in Cygwin:
```
julia> PkgDev.tag("WebSockets", :minor)
INFO: Tagging WebSockets v0.4.0




WARNING: cat(repo::GitRepo, T, spec) is deprecated, use content(T(repo, spec))
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] cat(::Base.LibGit2.GitRepo, ::Type{Base.LibGit2.GitBlob}, ::String) at .\deprecated.jl:1160
 [3] with(::PkgDev.Entry.##14#17{String}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:608
 [4] write_tag_metadata(::Base.LibGit2.GitRepo, ::String, ::VersionNumber, ::String, ::Bool) at C:\U   sers\F\.julia\v0.6\PkgDev\src\entry.jl:126
 [5] (::PkgDev.Entry.##43#52{String,Bool})(::Base.LibGit2.GitRepo) at C:\Users\F\.julia\v0.6\PkgDev\   src\entry.jl:269
 [6] transact(::PkgDev.Entry.##43#52{String,Bool}, ::Base.LibGit2.GitRepo) at .\libgit2\libgit2.jl:8   82
 [7] (::PkgDev.Entry.##37#46{String,Bool,String})(::Base.LibGit2.GitRepo) at C:\Users\F\.julia\v0.6\   PkgDev\src\entry.jl:268
 [8] with(::PkgDev.Entry.##37#46{String,Bool,String}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:   608
 [9] tag(::String, ::Symbol, ::Bool, ::String) at C:\Users\F\.julia\v0.6\PkgDev\src\entry.jl:227
 [10] (::Base.Pkg.Dir.##4#7{Array{Any,1},PkgDev.Entry.#tag,Tuple{String,Symbol}})() at .\pkg\dir.jl:   36
 [11] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},PkgDev.Entry.#tag,Tuple{String,Symbol}}, ::String) at .\f   ile.jl:59
 [12] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N} where N) at .\pkg\dir.   jl:36
 [13] tag(::String, ::Symbol) at C:\Users\F\.julia\v0.6\PkgDev\src\PkgDev.jl:52
 [14] eval(::Module, ::Any) at .\boot.jl:235
 [15] eval_user_input(::Any, ::Base.REPL.REPLBackend) at .\REPL.jl:66
 [16] macro expansion at .\REPL.jl:97 [inlined]
 [17] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:73
while loading no file, in expression starting on line 0
INFO: Committing METADATA for WebSockets

```

**Comment by hustf** [comment]
Now this is embarassing, I accidentaly did this again. The depwarns above can be overlooked of course.  I did not intend to tag 0.5.

**Comment by aviks** [comment]
Sorry, I don't understand... Should this PR be closed?

**Comment by hustf** [comment]
The correct number is v0.4. I just did that change manually on the repoisitory without any new commit. It seems to me that attobot has not posted a new pr.

**Comment by hustf** [comment]
I believe you can trigger a new test run by closing, then opening this PR. Or by going to travis. If you have sufficient access, there is a 'refresh' or 'rebuild' button somewhere. I can do neither.

Also, this PR should perhaps be renamed.

**Comment by aviks** [comment]
This PR is still trying to tag 0.3.3. Are you sure you have tagged 0.4 on the repo?

**Comment by hustf** [comment]
Thanks again for the effort, Avik.

I'll call the next update something 0.01 higher than what metadata call it
at the time of release.

The github repo is on v0.4. But Pkg.update() just pushed v0.5, probably due
to my unfortunate tinkering with PkgDev (see above). I have no idea how you
could override the system, if that's desirable. If I do change the repo to
v0.5 using Github, I suppose attobot is just going to post yet another PR?
Anyway, I'm not touching anything right now. v0.3.3, v0.4 and v0.5 refer to
the same commit anyway.

**Pull request closed without merging**
