### PR TITLE
Pull request/ee725c83 Brimjl, new version

### PR DESCRIPTION
**Pull request by tpoisot**
Brim.jl

### CODE REVIEW

**Comment by tkelman** [comment]
Why are you deleting the 1.1.1 and 1.1.2 tags?

**Comment by tpoisot** [comment]
Mistake with the version of Julia in REQUIRE. 1.1.0 is last to support 0.3, 1.2.1 is first to support 0.4

**Comment by tkelman** [comment]
Are 1.1.1 and 1.1.2 invalid, or should they just be changed from `julia 0.3` to `julia 0.4` ?

**Comment by tpoisot** [comment]
They are definitely invalid.

**Pull request merged**
