### PR TITLE
Allow only dev prerelease Julia versions

### PR DESCRIPTION
**Pull request by jiahao**
This PR institutes a requirement that tagged Julia versions for new package version records must be one of:
1. A released version (e.g. "0.3.1") that is at least `minjuliaver` or newer, or
2. A pre-release of a development version (currently "0.5.0-*"), or
3. A pre-release of a released version whose patch number is higher than zero
(e.g. "0.3.2-"). This case is occasionally needed to tag a version before the
fix is released in a new patch version.

In particular, this requirement is designed to raise an error for packages still tagging `julia 0.4-`.

The list of grandfathered packages has also been updated.

### CODE REVIEW

**Comment by tkelman** [comment]
I think this is a little premature. We can encourage this, but enforcing it via travis failure is a bit too soon. I suspect there are package authors out there who are pinning on a prerelease or dev version of 0.4 and may still need to do active package development in that state.

**Comment by tkelman** [comment]
I think it's been long enough since 0.4.0 that we can do this now. I updated the list of packages, anyone have objections to merging this if it passes?

**Comment by timholy** [comment]
Seems fine to me. It would definitely reduce the load on you, @tkelman.

**Comment by mlubin** [comment]
No objections here

**Comment by jiahao** [comment]
Is it also time to bump `minjuliaver = v"0.3.0"`, or just keep at 0.3?

**Comment by jiahao** [comment]
Rebased without changing `minjuliaver`

**Comment by tkelman** [comment]
There's zero functional difference between 0.3 and 0.3.0.

**Comment by jiahao** [comment]
I meant if it should be bumped to v0.4

**Comment by tkelman** [comment]
Ah. No, don't think so, as long as people are testing against it.

**Pull request merged**
