### PR TITLE
Register SALSA.jl package

### PR DESCRIPTION
**Pull request by jumutc**

### CODE REVIEW

**Comment by kshyatt** [comment]
In your `REQUIRE` you don't list a Julia version - does this work with `0.3` or `0.4-` (or both!)?

**Comment by jumutc** [comment]
Sorry, I forgot to include this. Now ``REQUIRE`` is updated.

**Comment by kshyatt** [comment]
Great! This LGTM - anyone else?

**Comment by kmsquire** [comment]
Might want to tag a version, so that people can use Pkg.add("SALSA").

**Comment by jumutc** [comment]
Version is added.

**Comment by tkelman** [comment]
Okay we'll merge this now and the `-` will be gone for the next tag.

**Pull request merged**
