### PR TITLE
Revert "Tag JuliennedArrays.jl v0.1.0"

### PR DESCRIPTION
**Pull request by KristofferC**
Reverts JuliaLang/METADATA.jl#17012

This release has been deleted from the repo and is causing problems https://discourse.julialang.org/t/install-package-dependence-from-specific-repository/20930

### CODE REVIEW

**Comment by KristofferC** [comment]
And 0.0.3 apparently bumped julia version but this was hidden due to the existence of this 0.1.0. So now this fails. Great.

**Comment by ferrolho** [comment]
I think merging this may have caused following PR and merges to fail, according to Travis

**Comment by KristofferC** [comment]
Yeah, that is possible. We should probably revert this and instead make the 0.1.0 release the same commit as the 0.3.0 release.

**Comment by ferrolho** [comment]
Yup, this seems to have fixed it: [JuliaLang/METADATA.jl/builds/500404291](https://travis-ci.org/JuliaLang/METADATA.jl/builds/500404291)

I tried re-submitting my PR but I still get an error related to this, I suppose:
```
ERROR: LoadError: New tag 0.0.3 of package JuliennedArrays requires julia 1.0.0, but version 0.0.1 of JuliennedArrays requires julia 0.6.0. Use a new minor package version when support for an old version of Julia is dropped.
```

**Pull request merged**
