### PR TITLE
Register AstroLib

### PR DESCRIPTION
**Pull request by giordano**
I started writing a bundle of astronomical functions, based on [IDL Astronomy User's Library](http://idlastro.gsfc.nasa.gov/homepage.html).

### CODE REVIEW

**Comment by mlubin** [comment]
You should push a tag to the PR as well.

**Comment by tkelman** [comment]
What is the license status of the code this was derived from?

**Comment by giordano** [comment]
The license of IDL AstroLib is BSD-2-Clause, see http://idlastro.gsfc.nasa.gov/idlfaq.html#A14

**Comment by giordano** [comment]
For the record, Python AstroLib [claims](http://www.hs.uni-hamburg.de/DE/Ins/Per/Czesla/PyA/PyA/pyaslDoc/pyasl.html#license-note) that original IDL AstroLib is in the public domain, but I don't know where they drawn this conclusion from.

For the time being, the few functions present in the AstroLib.jl share only the name with IDL AstroLib's procedures, not the algorithm, but in the future the same algorithm for some functions will be likely used.

**Pull request merged**
