### PR TITLE
Register Rsvg and Tag

### PR DESCRIPTION
**Pull request by lobingera**
should now contain the necessary actions in single commit.

### CODE REVIEW

**Comment by tkelman** [comment]
would be good to push the git tag so it shows up at https://github.com/lobingera/Rsvg.jl/releases

**Comment by lobingera** [comment]
@tkelman, as Pkg.publish() didn't work, i did some steps manually. You mean Rsvg.jl should contain a releases file in the top level directory? (and it contains what?)

**Comment by tkelman** [comment]
No, you should have some tags listed when you do `git tag`, but they haven't been pushed. `git push --tags` will do so.

**Comment by lobingera** [comment]
i did, but how do i see this on github?

**Comment by tkelman** [comment]
https://github.com/lobingera/Rsvg.jl/releases is nonempty now, so looks right

**Pull request merged**
