### PR TITLE
Upper bounds on Parameters.jl in DiffEq

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Avoiding 0.7.0 due to escaping issues. See https://discourse.julialang.org/t/nested-macros-bypass-package-dependencies/2683/4

### CODE REVIEW

**Comment by tkelman** [comment]
Since early versions of DiffEqBase did not depend on Parameters, this could result in downgrading to very old DiffEqBase to get the latest Parameters. Could add an artificial bounded dependency to avoid this.

**Comment by ChrisRackauckas** [comment]
You mean, remove the latest Parameters.jl tag? I think that's a good idea too. Let me know if you want me to do that.

**Comment by tkelman** [comment]
No, I mean supercede it with a tag that works.

**Comment by tkelman** [comment]
should be made unnecessary by https://github.com/JuliaLang/METADATA.jl/pull/8348

**Pull request closed without merging**
