### PR TITLE
Register new package VegaDatasets.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidanthoff/VegaDatasets.jl](https://github.com/davidanthoff/VegaDatasets.jl)
Release: [v0.0.1](https://github.com/davidanthoff/VegaDatasets.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/davidanthoff/VegaDatasets.jl/builds/348505293)
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@davidanthoff This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by davidanthoff** [comment]
CC @fredo-dedup and @randyzwitch

**Comment by quinnj** [comment]
I'm worried about confusion in namespacing here; RDatasets.jl exports `dataset(dir::String, file::String)` and this package would export `dataset(::String)`. It's not clear that either package should be able to claim `dataset`, and IMO, it's a pretty generic term that could apply to any number of "dataset"-loading packages. In short, using `dataset` as the functional interface isn't going to scale well. Potential options:
* don't export, then usage would be `using VegaDatasets; VegaDatasets.dataset(...)`, or `import VegaDatasets.dataset; dataset(...)`; not terrible, more clear, no conflicts, but a little ugly/verbose
* find another function name that's less likely to conflict, maybe `vegaload`, or `vegadataset`, or `vdataset`
* don't worry about it; are people realistically going to have multiple dataset-loading packages loaded at once to actually see a conflict?

**Comment by randyzwitch** [comment]
My vote is: 

don't worry about it; are people realistically going to have multiple dataset-loading packages loaded at once to actually see a conflict?

**Comment by davidanthoff** [comment]
Yeah, I wouldn't worry about it. First, I don't think many folks will load multiple example data sets at once, and second, if they do, they are just automatically back in the world where they have to write ``VegaDatasets.dataset(...)`` and ``RDatasets.dataset()``, which seems fine. But why make the case where they only load one of these packages more complicated?

**Comment by andreasnoack** [comment]
We can revisit the exports if this shows up to be a real concern.

**Pull request merged**
