### PR TITLE
Tag FEMBase.jl v0.0.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaFEM/FEMBase.jl](https://github.com/JuliaFEM/FEMBase.jl)
Release: [v0.0.3](https://github.com/JuliaFEM/FEMBase.jl/releases/tag/v0.0.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaFEM/FEMBase.jl/builds/312878715)
Diff: [vs v0.0.1](https://github.com/JuliaFEM/FEMBase.jl/compare/110acde568e5906fe3e051a16b8087016107aa30...3a0f9f1a80a99d28fb56609740387f17603c7dcd)
`requires` vs v0.0.1: no changes
cc: @ahojukka5

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
`JuliaFEM` tests failed with 
```
JuliaFEM.jl: Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: LoadError: UndefVarError: Discrete not defined
  Stacktrace:
   [1] include_from_node1(::String) at ./loading.jl:569
   [2] eval(::Module, ::Any) at ./boot.jl:235
   [3] _require(::Symbol) at ./loading.jl:483
   [4] require(::Symbol) at ./loading.jl:398
   [5] include_from_node1(::String) at ./loading.jl:569
   [6] include(::String) at ./sysimg.jl:14
   [7] timeit(::##1#2, ::TimerOutputs.TimerOutput, ::String) at /mnt/pkgevalempty/1edcbc9815127efdd1837e9de5aaa62b8b821749/JuliaFEM/.julia/v0.6/TimerOutputs/src/TimerOutput.jl:203
   [8] macro expansion at /mnt/pkgevalempty/1edcbc9815127efdd1837e9de5aaa62b8b821749/JuliaFEM/.julia/v0.6/JuliaFEM/test/runtests.jl:18 [inlined]
   [9] macro expansion at ./test.jl:860 [inlined]
   [10] anonymous at ./<missing>:?
   [11] include_from_node1(::String) at ./loading.jl:569
   [12] include(::String) at ./sysimg.jl:14
   [13] process_options(::Base.JLOptions) at ./client.jl:305
   [14] _start() at ./client.jl:371
  while loading /mnt/pkgevalempty/1edcbc9815127efdd1837e9de5aaa62b8b821749/JuliaFEM/.julia/v0.6/JuliaFEM/src/JuliaFEM.jl, in expression starting on line 12
  while loading /mnt/pkgevalempty/1edcbc9815127efdd1837e9de5aaa62b8b821749/JuliaFEM/.julia/v0.6/JuliaFEM/test/test_add_elements.jl, in expression starting on line 4
```

**Comment by ahojukka5** [comment]
I need a little help on fixing this. FEMBase.jl does not require JuliaFEM.jl but vice versa. What modifications are proposed now? I looks that going from version 0.0.1 to 0.0.2 breaks backward compatibility because JuliaFEM.jl tests are now failing. So should I change version numbering to 0.1.0 and require JuliaFEM.jl to use 0.0.x versions until I fix the code in JuliaFEM.jl to support 0.1.x ?

**Comment by ahojukka5** [comment]
This can be closed.

**Comment by ahojukka5** [comment]
This can be closed.

**Pull request closed without merging**
