### PR TITLE
Register new package AIControl.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [hiranumn/AIControl.jl](https://github.com/hiranumn/AIControl.jl)
Release: [v0.0.1](https://github.com/hiranumn/AIControl.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/hiranumn/AIControl.jl/builds/476311261)
cc: @hiranumn

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@hiranumn This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use abbreviations in package names.

**Comment by dpsanders** [comment]
Ah I see that that is the name of the method.

**Comment by hiranumn** [comment]
Hi David!

Yes. It is the name of the method that this package implements. It is currently under review for a journal. 
It would really help me if I can push this to central registry so let me know if there is anything unclear!

Nao

**Comment by hiranumn** [comment]
Hi just checking back if there was any progress on this or if there are anything I have to do!

**Comment by andreasnoack** [comment]
> It is currently under review for a journal.

GitHub will redirect so that shouldn't be a concern. Let us know if you want to keep or change the current name.

**Comment by hiranumn** [comment]
I'd like to keep the name as it is a method name for my paper!

**Pull request merged**
