### PR TITLE
Register new package Remotes.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bramtayl/Remotes.jl](https://github.com/bramtayl/Remotes.jl)
Release: [v0.0.1](https://github.com/bramtayl/Remotes.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/bramtayl/Remotes.jl/builds/319871770)
cc: @bramtayl

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@bramtayl This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by aviks** [comment]
Maybe GitRemotes might be a better name? It took me a while to figure out what the package does.

**Comment by bramtayl** [comment]
I'm open to renaming but I don't think that GitRemote fits. This package also interacts with Travis and Appveyor

**Comment by bramtayl** [comment]
What about `OnlinePackage`?

**Comment by bramtayl** [comment]
Replaced by https://github.com/JuliaLang/METADATA.jl/pull/13154

**Pull request closed without merging**
