### PR TITLE
Tag Pipe.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [oxinabox/Pipe.jl](https://github.com/oxinabox/Pipe.jl)
Release: [v1.0.0](https://github.com/oxinabox/Pipe.jl/releases/tag/v1.0.0)
Travis: [Travis Build Status](https://travis-ci.org/oxinabox/Pipe.jl/builds/239840099)
Diff: [vs v0.0.3](https://github.com/oxinabox/Pipe.jl/compare/a69a1cef18be8ab799681623fa53c1be2f471294...145b85f0e19f2cb9eda5cb7d447002ff4a0acc0c)
`requires` vs v0.0.3: 
```diff
--- 0.0.3/requires
+++ 1.0.0/requires
@@ -1,2 +1 @@
 julia 0.3
-Compat
```
cc: @oxinabox

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by oxinabox** [comment]
I am specifically still maintaining 0.3 compatibility, and testing it.

See: https://travis-ci.org/oxinabox/Pipe.jl/builds/239840099
Everything is passing in 0.3, 0.4, 0.5, 0.6.
Linux 0.7 is fine, Mac 0.7 seems to have an unrelated error.

**Comment by tkelman** [comment]
metadata is frozen for new package versions that support 0.3

**Comment by oxinabox** [comment]
I thought there as a case-by-case exception for if the authors are specifically still testing on 0.3?

**Comment by oxinabox** [comment]
Thanks.

**Pull request merged**
