### PR TITLE
Register new package SVMs.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [mpastell/SVMs.jl](https://github.com/mpastell/SVMs.jl)
Release: [v0.1.0](https://github.com/mpastell/SVMs.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/mpastell/SVMs.jl/builds/220109141)
cc: @mpastell

### CODE REVIEW

**Comment by mpastell** [comment]
This is a Julia interface for LIBSVM based on code forked from LIBSVM.jl. The motivation is support the features that are missing from LIBSVM.jl and to provide an up to date release. 

Features:
* Supports all LIBSVM models: classification C-SVC, nu-SVC, regression: epsilon-SVR, nu-SVR and distribution estimation: one-class SVM
* Model objects are represented by Julia type SVM which gives you easy access to model features and can be saved e.g. as JLD file

I have done my best to attribute @simonster 's work with LIBSVM.jl. Let me know if I have not done it  correctly.

The interface aims to be "Julian", whereas SVR.jl is more low level.

**Comment by tkelman** [comment]
LIBSVM hasn't had a release in 3 years, wouldn't it be better to take over maintenance in place?

**Comment by simonster** [comment]
@mpastell If you'd like to maintain LIBSVM.jl, I'm happy to give you access or to transfer the package to your account.

**Comment by mpastell** [comment]
@simonster @tkelman That would clearly be a better solution, if you don't plan to work on it I'd like to transfer it to my account. 

I have changed the API a bit on current master, are you OK with that? That's mainly because I'm in the process of adding a Scikilearn compatible API on top and it keeps the code cleaner..

**Comment by mpastell** [comment]
Or would it be better to put package under JuliaML?

**Comment by mpastell** [comment]
@simonster I've deleted my fork of LIBSVM.jl, it would be great if you could transfer the package to my account.

**Comment by mpastell** [comment]
This pull request can now be closed, I've taken over maintenance of LIBSVM instead as suggested. Thanks @tkelman .

**Pull request closed without merging**
