### PR TITLE
Tag Mamba v0.7.1

### PR DESCRIPTION
**Pull request by brian-j-smith**

### CODE REVIEW

**Comment by kshyatt** [comment]
Hello,

Does Mamba need those very specific versions of the packages in its `REQUIRE`? Or will the package work with newer/older versions too?

**Comment by brian-j-smith** [comment]
Hi @kshyatt,

A single number next to a package in the REQUIRE file represents the minimum version requirement.  Thus, Mamba will install with any versions at or later than the ones specified.  The numbers that I did specified are the required package versions at which this release of Mamba was developed and tested.

Feel free to let me know if there are other questions.

**Comment by kshyatt** [comment]
Ok, sounds good. Sometimes people put numbers next to the packages in `REQUIRE` because they think it's required, but it sounds like you know what's up :). It might be nice to test against older versions at some point but this lgtm.

**Comment by brian-j-smith** [comment]
Thanks.  That's a good suggestion to accommodate earlier versions of required packages.  I'll make more of an effort to do that in the future.  Best.

**Comment by kshyatt** [comment]
No worries! Like I said, it would be nice, but it's not super necessary, especially if the package versions you've listed are the first ones that work with 0.4 or something.

**Pull request merged**
