### PR TITLE
Tag HttpCommon.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaWeb/HttpCommon.jl](https://github.com/JuliaWeb/HttpCommon.jl)
Release: [v0.4.0](https://github.com/JuliaWeb/HttpCommon.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaWeb/HttpCommon.jl/builds/331100411)
Diff: [vs v0.3.0](https://github.com/JuliaWeb/HttpCommon.jl/compare/e546dc2cdc58ca2647674bda08fd5ef557c4f151...51c55f1a838e255ba649df5b6e10974c260d1939)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -1,2 +1,3 @@
-julia 0.5
+julia 0.6
 URIParser
+Compat 0.37.0
```
cc: @ararslan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ararslan** [comment]
cc @kshyatt

**Comment by aviks** [comment]
This fails Budku tests. The tests pass for `HttpCommon v0.3.0` but not for `0.4.0`

cc:  @wookay

**Comment by wookay** [comment]
just updated on Bukdu.jl master, thanks to report it.

**Comment by aviks** [comment]
Will you tag a new version of Budku soon? Once this is merged, your users might break.

**Comment by ararslan** [comment]
Before this is merged I'd like to get https://github.com/JuliaWeb/HttpCommon.jl/pull/50 merged then retag.

**Pull request merged**
