### PR TITLE
Register new package NanoTimes.jl v0.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/NanoTimes.jl](https://github.com/JeffreySarnoff/NanoTimes.jl)
Release: [v0.0.0](https://github.com/JeffreySarnoff/NanoTimes.jl/releases/tag/v0.0.0)
Travis: [Travis Build Status](https://travis-ci.org/JeffreySarnoff/NanoTimes.jl/builds/291914219)
cc: @JeffreySarnoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@JeffreySarnoff This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by fredrikekre** [comment]
`ERROR: LoadError: NanoTimes: version 0.0.0 no longer allowed (>= 0.0.1 needed)`

**Comment by JeffreySarnoff** [comment]
thanks for the heads up

**Comment by andreasnoack** [comment]
No activity in three months so closing

**Comment by JeffreySarnoff** [comment]
good move

**Pull request closed without merging**
