### PR TITLE
Tag Symata.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jlapeyre/Symata.jl](https://github.com/jlapeyre/Symata.jl)
Release: [v0.4.0](https://github.com/jlapeyre/Symata.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/jlapeyre/Symata.jl/builds/402790902)
Diff: [vs v0.3.0](https://github.com/jlapeyre/Symata.jl/compare/67c99e3e2b54fba682c1c9597e8a9f41d351d7d9...5ec530e395e4c831ea84460117dae97926101a3c)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -1,6 +1,6 @@
-julia 0.6
-Compat 0.9.5
+julia 0.7-beta
 PyCall 1.7.0
+Compat
 Combinatorics 0.2.1
 Primes 0.1.1
 DataStructures
@@ -8,3 +8,6 @@
 Polynomials
 Roots
 QuadGK
+MacroTools
+LambertW
+SpecialFunctions
```
cc: @jlapeyre

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like the Travis tests are all failing

**Comment by jlapeyre** [comment]
Looks like two things.

1.  `Symata` depends on `SpecialFunctions`, which is failing to build (IIUC) with
```
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/kvjJ/deps/build.log`
WARNING: Base.Pkg is deprecated, run `using Pkg` instead
 in module Main
ERROR: MethodError: no method matching haskey(::Nothing, ::String)
```
At the moment, it looks like this is what stopped the OSX build. I can't see which version of `SpecialFunctions` travis is trying to install. It is not versioned in my `REQUIRE`. I should do this.

2. `Symata` depends on `LambertW` (this is a new dependency). I did not version this in my `REQUIRE`. Travis is trying to install a two year old version, and it is failing.

I will add version numbers to the entries in `REQUIRE` and try again.

**Comment by jlapeyre** [comment]
I added minimum versions for all dependencies. Will make a new release when all dependencies are released.

**Comment by andreasnoack** [comment]
> I added minimum versions for all dependencies. Will make a new release when all dependencies are released.

It indeed looks like `LambertW` is the root cause here. You can just delete the 0.4 release and tag and reapply it to the commit that includes the bounds.

**Comment by jlapeyre** [comment]
I see that `LambertW` tag 0.4 has been committed. But, dealing with the new `Pkg` and dependencies has been an odyssey. I spent a day on it. Don't want to spend more time. I'll wait until things settle down.

`LambertW`  had one source file, and I am the author. I just copied it to the `Symata` repo. I will remove it when everyone has more experience with the new system.

`SpecialFunctions` was also causing trouble yesterday. An old version was downloaded and installed, even though I specified a later version.

**Comment by andreasnoack** [comment]
From the log
```julia
ERROR: LoadError: LoadError: The following tags for Symata have not been pushed to upstream repository: 0.4.0.
```
Did you remember to delete both the release **and** the tag?

**Comment by andreasnoack** [comment]
Oh. Never mind. I see that is is triggered by my restart and that you haven't updated the tag yet so just disregard that last comment.

**Comment by goedman** [comment]
Hi John, if that helps, I do have a Pkg(3)-ready fork of Symata.jl that passes CI (at https://github.com/goedman/Symata.jl with https://travis-ci.org/goedman/Symata.jl and https://ci.appveyor.com/project/goedman/symata-jl - a few Appveyor branches still going)

If that helps, I can make a PR.

appveyor.yml can be streamlined a bit further. For now it pulls in LambertW.jl v0.4.0 (I specified #master). I could make LambertW.jl Pkg(3) ready as well if that would help.

In Project.toml I have specified a version 0.4.1 (but that could easily be changed, as well as some of the other fields).

I added Manifest.toml to .gitignore as this is a package.

**Comment by jlapeyre** [comment]
Hi Rob. Thanks for the help. 

* Yes, a PR would be very helpful. Are you thinking of just the Pkg3 and CI files ?  I have pushed some commits today. I think one step at time would be best. I mean removing LambertW from the dependencies and it in a separate commit.
* I read in the docs that if your project has a Project.toml, then all dependencies must have them too. But, even in the example in the docs, this was not the case.
* Making `LambertW` `Pkg3` ready. Yes! I'd appreciate that.
* `LambertW` is one source file, so I just copied it to Symata . If I can get it to work on machine, maybe with your Project.toml, I'll remove it again.
* My latest commits pushed to github pass tests and work with CI.

**Comment by goedman** [comment]
Out on my bike right now but will pull in your updates and make a PR. I‘ll  remove the LambertW file in Symata and test it with the LambertW package before making the PR. Should be done this afternoon (CO time).

**Comment by goedman** [comment]
Testing takes some time, but it seems that (all in the forked version of Symata and LambertW):

1. Symata with import LambertW.jl#master works fine
2. Made a Pkg(3) version of LambertW.jl (version 0.4.1 in Project.jl)
3. Reverting back to just Pkg(3) stuff and CI testing that right now.

4. Then I'll make a PR for LambertW.jl
5. A PR for Symata with `@inc("LambertW.jl")` enabled, `import LambertW` disabled (once CI testing is completed, later this afternoon)
6. A PR for Symata with `@inc("LambertW.jl")` disabled and `import LambertW` denabled (I'll retest CI, so this PR will be later today or tomorrow am, well half-time soccer :-)

Pkg(3) with non-registered packages is a bit more difficult as `(v0.7)pkg > activate LambertW` won't generate a testable setup (yet). But I'm assuming it is your intention to register LambertW.jl.

**Comment by jlapeyre** [comment]
That's a lot of stuff! This sounds good. LambertW is already registered. That was causing a problem. Until v0.4 was merged in METADATA, the highest registered version was 0.2, which does not work. I tried everything I could think of  to prevent Pkg(3) from pulling in that version, short of renaming the package. But had no luck.
Now that v0.4 is registered, and you have Project.toml working in any case, this problem is likely solved.

**Comment by goedman** [comment]
I believe this would have been an example where Pkg(3) would have been helpful if the Manifest file is stored in the repo. I'll check later today if indeed `test` is now working after `activate LambertW` in the Pkg(3) REPL.

**Comment by jlapeyre** [comment]
I don't have experience with `activate`, so I don't know what's going on. I used `develop` on the registered repo. I'll look into it.

**Comment by jlapeyre** [comment]
The build log https://travis-ci.org/JuliaLang/METADATA.jl/builds/403440835#L469 seem to show that Julia v0.6.4 is being used first. But Symata master is not compatible with v0.6

EDIT: oops thats my build log from a day ago.

**Comment by goedman** [comment]
When you say ‘develop on the registered repo’, did you do ‘dev LambertW’ or ‘dev https://github.../LambertW.jl’? In fact, given that it is registered, ‘add LambertW’ should suffice for Symata. I’ll play around some more when back home later today.

I use ‘activate Symata’ to add dependencies to the Symata package Project.toml file.

I tested that as well on LambertW, hence the dependency on Compat that I should have removed.

**Comment by jlapeyre** [comment]
Just  `dev LambertW` because it is registered.

 `I use ‘activate Symata’ to add dependencies to the Symata package Project.toml file.`

Ah good. I've only added `Project.toml` files to projects with no dependencies.

**Comment by andreasnoack** [comment]
Looks like things are in good shape now. Is this one ready? Also, please consider using the #pkg-usage channel on Slack or Discourse if you're having problems with the new package manager.

**Comment by jlapeyre** [comment]
Yes, this is ready to merge.
> Also, please consider using the #pkg-usage channel on Slack or Discourse

Agreed.

**Pull request merged**
