### PR TITLE
Tag StatPlots.jl v0.8.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPlots/StatPlots.jl](https://github.com/JuliaPlots/StatPlots.jl)
Release: [v0.8.2](https://github.com/JuliaPlots/StatPlots.jl/releases/tag/v0.8.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPlots/StatPlots.jl/builds/455208943)
Diff: [vs v0.8.1](https://github.com/JuliaPlots/StatPlots.jl/compare/05c7cc3c1f88de334c0eac0e7cf9f57ea082fa3f...51b23123fef0bd84a8d6a957bee5238d1830c72b)
`requires` vs v0.8.1: no changes
cc: @mkborregaard

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by mkborregaard** [comment]
The reason StatPlots merge PRs are getting rejected from MetaData is due to a test in ForestBiometrics:
```

ERROR: LoadError: LoadError: UndefVarError: datavaluerows not defined
Stacktrace:
 [1] getiterator(::DataFrames.DataFrame) at /home/jrun/ForestBiometrics/.julia/packages/DataFrames/1PqZ3/src/other/tables.jl:40
 [2] extract_columns_from_iterabletable(::DataFrames.DataFrame, ::Symbol, ::Vararg{Symbol,N} where N) at /home/jrun/ForestBiometrics/.julia/packages/StatPlots/22UPl/src/df.jl:153
 [3] (::getfield(ForestBiometrics, Symbol("##1#9")))(::DataFrames.DataFrame) at ./none:0
 [4] gingrich_chart(::Int64, ::Int64) at /home/jrun/ForestBiometrics/.julia/packages/ForestBiometrics/lHi08/src/GingrichStocking_chart.jl:95
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include at ./sysimg.jl:29 [inlined]
 [9] include(::String) at /home/jrun/ForestBiometrics/.julia/packages/ForestBiometrics/lHi08/src/ForestBiometrics.jl:3
 [10] top-level scope at none:0
 [11] include at ./boot.jl:317 [inlined]
 [12] include_relative(::Module, ::String) at ./loading.jl:1038
 [13] include(::Module, ::String) at ./sysimg.jl:29
 [14] top-level scope at none:2
 [15] eval at ./boot.jl:319 [inlined]
 [16] eval(::Expr) at ./client.jl:399
 [17] top-level scope at ./none:3
in expression starting at /home/jrun/ForestBiometrics/.julia/packages/ForestBiometrics/lHi08/src/GingrichStocking_chart.jl:132
in expression starting at /home/jrun/ForestBiometrics/.julia/packages/ForestBiometrics/lHi08/src/ForestBiometrics.jl:64
```
Any idea what's going on, @Crghilardi @piever ?

**Comment by andreasnoack** [comment]
This error is subtle. It's not obvious if anything in `StatPlots` is causing this. It might be related to `Requires`. The problem is this call to `datavaluerows` in https://github.com/JuliaData/DataFrames.jl/blob/a0d44f6f4905d70b69d61654b2687de3197c5ce9/src/other/tables.jl#L40. This function is behind a `@require` and therefore only defined if `DataValues` is loaded as can be seen from https://github.com/JuliaData/Tables.jl/blob/c3a206252d1f596b532aa9b30ad2b6b5c6211595/src/Tables.jl#L8. However, `DataValues` should be loaded via `StatPlots` -> `TableTraitsUtils` -> `DataValues` so I'm not sure what is going on here. A bug in `Requires`?

I noticed that `ForestBiometrics` is a little odd in that it calls the `gingrich_chart` function from the module, see https://github.com/Crghilardi/ForestBiometrics.jl/blob/v0.1.1/src/GingrichStocking_chart.jl#L132, so this is executed during precompilation. I don't know if that confuses `Requires`. Maybe the better solution for now is to add an upper bound on `StatPlots` in `ForestBiometrics` here in METADATA.

cc: @quinnj @davidanthoff

**Comment by piever** [comment]
Maybe turning on pre-compilation in StatPlots created this issue? The issue seems unrelated to StatPlots, so I would also be in favour of adding an upper-bound on StatPlots in ForestBiometrics for the time being.

I'm curious how the package managed to keep precompilation enabled while depending on StatPlots that disabled it until this release.

**Comment by mkborregaard** [comment]
Essentially the canonical way of implementing the code in ForestBiometrics.jl is to use recipes rather than depending on StatPlots and calling `plot` on a DataFrame. Is the onus on us to PR recipes to that package or how do we deal with this?

**Comment by mkborregaard** [comment]
https://github.com/Crghilardi/ForestBiometrics.jl/pull/13

**Comment by arnavs** [comment]
If this is the only bottleneck, would it be possible to merge this and then have the `ForestBiometrics.jl` maintainer(s) merge in the version cap? 

Asking because this PR is the bottleneck on tagging a new version of TOML in https://github.com/quantecon/quanteconlecturepackages, https://github.com/quantecon/quanteconlectureallpackages, and a Docker image which depends on those.

**Comment by mkborregaard** [comment]
The capping of StatPlots in ForestBiometrics have been merged - is that enough or dowe need a new release of that to merge this?

**Comment by andreasnoack** [comment]
The upper bound needs to be applied here in METADATA to all the released versions of ForestBiometrics. Then we can restart the tests to confirm the that issue has been fixed.

**Comment by mkborregaard** [comment]
OK, so what do I have to do? I already updated it by PR to the package...

**Comment by arnavs** [comment]
I get that we want to isolate the problem but I'm reminded of what @andreasnoack wrote in https://github.com/JuliaLang/METADATA.jl/pull/19282#issuecomment-436173079: 

> We should give people a fair amount of time to resolve any issues before merging but downstream failures shouldn't hold back a release indefinitely. We have given time here so I've merged this.

StatPlots is an important package and this release fixes a big issue (the precompilation). By comparison, this looks like an edge-case error in a package that hasn't been maintained for the last 5-10 months and not one that's even necessarily (or probably?) associated with the new tag...

**Comment by andreasnoack** [comment]
The thing to do is to prepare a PR like https://github.com/JuliaLang/METADATA.jl/pull/19565.

**Comment by mkborregaard** [comment]
Will that happen automatically if there's a new release of the package?

**Comment by piever** [comment]
> Will that happen automatically if there's a new release of the package?

No, as we need to alter past releases as well. Otherwise the resolver could try to install old releases of ForestBiometrics with latest StatPlots, which would also not work: I'll make a PR to change METADATA directly.

EDIT: PR at #19570, after that is merged we can re-trigger CI here and see if everything's fixed.

**Comment by andreasnoack** [comment]
As mentioned on Slack, we are currently unable to receive the requests from GitHub. Hence CIBot isn't getting triggered. Hopefully, the issue will be resolved soon.

**Comment by arnavs** [comment]
@andreasnoack JuliaCI bot is now happy with this PR.

**Comment by Crghilardi** [comment]
Hi, author of ForestBiometrics here. Sorry everyone for holding up everything, just tagged a new release. Hopefully this alleviates the issues. I havn't looked at the repo in a while, was planning to pick it back up at some point in the future. Please proceed without me if need be and let the package break, I am the only user of my package.

**Pull request merged**
