### PR TITLE
Tag Vega v0.7.0

### PR DESCRIPTION
**Pull request by randyzwitch**
Update to 0.5 compatibility, before moving to 0.6 compatibility

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like you removed Compat from REQUIRE but not src/Vega.jl?

**Comment by randyzwitch** [comment]
Can I get away with this change, just modifying the SHA1? Removing it was my intention, so I just pushed the fix to the main Vega.jl library.

**Comment by tkelman** [comment]
That should have failed Travis, unless you also update the git tag in the repo to match

**Comment by randyzwitch** [comment]
I'll just close it and do it the right way then.

**Pull request closed without merging**
