### PR TITLE
Tag FixedPolynomials.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaAlgebra/FixedPolynomials.jl](https://github.com/JuliaAlgebra/FixedPolynomials.jl)
Release: [v0.3.0](https://github.com/JuliaAlgebra/FixedPolynomials.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaAlgebra/FixedPolynomials.jl/builds/376792311)
Diff: [vs v0.2.2](https://github.com/JuliaAlgebra/FixedPolynomials.jl/compare/fbcd5d4536f06c8f70f5491ea01d862f8e93eafa...c8e5913f4d1c7ecf25307a7ac7e66b91c8071af6)
`requires` vs v0.2.2: no changes
cc: @saschatimme

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like this breaks `Homotopies`.

**Comment by saschatimme** [comment]
Already saw this, is it fine if I add an upper bound to Homotopies (I am one of the maintainers of it) here in METADATA.jl via a new PR?

**Comment by andreasnoack** [comment]
Yes that would be great. Remember that you'll have to add upper bounds to all previous versions of the package to avoid that the package manager just downgrades to a previous version of `Homotopies`

**Comment by saschatimme** [comment]
Just opened #14601 to get this done :)

**Pull request merged**
