### PR TITLE
Tag MonteCarloMarkovKernels.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [awllee/MonteCarloMarkovKernels.jl](https://github.com/awllee/MonteCarloMarkovKernels.jl)
Release: [v0.6.0](https://github.com/awllee/MonteCarloMarkovKernels.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/awllee/MonteCarloMarkovKernels.jl/builds/414017241)
Diff: [vs v0.0.1](https://github.com/awllee/MonteCarloMarkovKernels.jl/compare/02e09672aa357ea90128bea253729244c8155378...72895240493d5cd69c2ae056c18e4b2a58fc2fc5)
`requires` vs v0.0.1: no changes
cc: @awllee

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like there are some tests failures on Travis

**Comment by awllee** [comment]
Do you mean the errors on Julia v0.7? These are due to the dependency KernelDensity.jl not being compatible with Julia v0.7 yet.

This tag is the last release for Julia v0.6, so I though this wouldn't be an issue.

**Comment by andreasnoack** [comment]
> This tag is the last release for Julia v0.6, so I though this wouldn't be an issue.

It isn't but it's hard to know that it was the case so it is a good idea to leave a comment with such information. You might also want to consider adding upper bounds on the released versions if you know that they don't work with Julia 0.7/1.0

**Comment by awllee** [comment]
Sorry about that. To be honest, I haven't been sure what information would be helpful.

In fact, the code should also work with Julia 0.7/1.0 as soon as KernelDensity.jl is updated. I am looking forward to learning how to make more precise requirements with the new Pkg.

**Pull request merged**
