### PR TITLE
Register EGM96 [https://github.com/peterjdolan/EGM96.jl]

### PR DESCRIPTION
**Pull request by peterjdolan**
Register and tag EGM96

### CODE REVIEW

**Comment by tkelman** [comment]
If you have the source code from some other author directly checked in, then you should acknowledge its license.

**Comment by peterjdolan** [comment]
Done.

**Comment by tkelman** [comment]
May want to spell out the EGM acronym in the short package description, as that'll appear in the listing at http://pkg.julialang.org tomorrow

**Comment by peterjdolan** [comment]
Thanks, done.

**Pull request merged**
