### PR TITLE
Tag ChaosTools.jl v0.8.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDynamics/ChaosTools.jl](https://github.com/JuliaDynamics/ChaosTools.jl)
Release: [v0.8.2](https://github.com/JuliaDynamics/ChaosTools.jl/releases/tag/v0.8.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDynamics/ChaosTools.jl/builds/360863408)
Diff: [vs v0.8.1](https://github.com/JuliaDynamics/ChaosTools.jl/compare/3b95f8fd9ef42875bd8df6786a7883e15e424ef7...cca836688b26079f84348337d1635764ec663e07)
`requires` vs v0.8.1: no changes
cc: @Datseris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like tests are failing

**Comment by Datseris** [comment]
Hi @andreasnoack thanks for letting me know!

The Travis tests pass. When I clicked on the failing JuliaCI tests, the only thing that was written was:

```
----------Julia and Package versions----------
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
----------STDOUT----------
----------STDERR----------
```
seems like the tests did not even start?

It does not make much sense that the JuliaCI tests won't pass if Travis tests pass, since `ChaosTools` has no packages depending on it.

of course, just to be sure, I run all tests again locally and they seem ok.

**Comment by andreasnoack** [comment]
We've seen that issue with CIBot occasionally so since the Travis tests pass I'll go ahead and merge.

**Comment by Datseris** [comment]
Thank you for your trust!

**Pull request merged**
