### PR TITLE
Register new package PtFEM.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [PtFEM/PtFEM.jl](https://github.com/PtFEM/PtFEM.jl)
Release: [v0.0.1](https://github.com/PtFEM/PtFEM.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/PtFEM/PtFEM.jl/builds/236775250)
cc: @goedman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@goedman This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
Is this superseded by #9566?

**Comment by goedman** [comment]
Yes, I was hoping that by deleting the release it would also remove the PR on METADATA and the tag number.

**Comment by tkelman** [comment]
It will update a PR in place if you replace an existing release number. Though that should only be done before a release gets published to metadata.

**Comment by tkelman** [comment]
See also https://github.com/attobot/attobot/issues/30

**Pull request closed without merging**
