### PR TITLE
Tag SVMLightLoader v0.3.1

### PR DESCRIPTION
**Pull request by IshitaTakeshi**

### CODE REVIEW

**Comment by tkelman** [comment]
Would your tests pass on Travis CI if you enabled it?

**Comment by IshitaTakeshi** [comment]
I think so 

```
$julia -e 'Pkg.build("SVMLightLoader"); Pkg.test("SVMLightLoader"; coverage=true)'
INFO: Building LibCURL
INFO: Testing SVMLightLoader
Testing isnumeric
Testing line_to_data
WARNING: could not attach metadata for @simd loop.
WARNING: could not attach metadata for @simd loop.
WARNING: could not attach metadata for @simd loop.
WARNING: could not attach metadata for @simd loop.
Testing load_svmlight_file
Testing iteration of SVMLightFile
WARNING: could not attach metadata for @simd loop.
Testing length(s::SVMLightFile)
Testing List Comprehensions
INFO: SVMLightLoader tests passed
```

Should I enable it?

**Comment by tkelman** [comment]
> Should I enable it?

No reason not to?

**Comment by IshitaTakeshi** [comment]
Ok I'll create a new pull request after enabling it.

**Comment by tkelman** [comment]
Just changing Travis doesn't really require making a new PR

**Comment by IshitaTakeshi** [comment]
Sorry I've already created another one. 

https://github.com/JuliaLang/METADATA.jl/pull/4858

**Comment by IshitaTakeshi** [comment]
How should I've done? Should I have overwritten this request?

**Comment by tkelman** [comment]
It's alright, what you did is fine.

**Pull request closed without merging**
