### PR TITLE
Julia v0.4 compatibility fixes for CUDNN and CUBLAS.

### PR DESCRIPTION
**Pull request by denizyuret**

### CODE REVIEW

**Comment by jakebolewski** [comment]
@denizyuret a minimum Julia version be added to the REQUIRE file for both packages it seems like

**Comment by denizyuret** [comment]
Thanks, I added the REQUIRE lines, and hopefully I didn't mess up the tags in the meantime.

**Comment by tkelman** [comment]
could you squash the commits?

**Comment by denizyuret** [comment]
I squashed the commits.

**Pull request merged**
