### PR TITLE
Tag BinaryBuilder.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPackaging/BinaryBuilder.jl](https://github.com/JuliaPackaging/BinaryBuilder.jl)
Release: [v0.0.2](https://github.com/JuliaPackaging/BinaryBuilder.jl/releases/tag/v0.0.2)
Diff: [vs v0.0.1](https://github.com/JuliaPackaging/BinaryBuilder.jl/compare/43a532ea895a4894e25e780b2c63bcedab4d594b...819b085e57e405b7f845f4d81e68e771f3382cb9)
`requires` vs v0.0.1: 
```diff
--- 0.0.1/requires
+++ 0.0.2/requires
@@ -1,12 +1,13 @@
 julia 0.6
-BinaryProvider
+BinaryProvider 0.2.0
 ObjectFile
-Compat 0.27.0
+Compat 0.55.0
 Reexport
 TerminalMenus
 MbedTLS
 GitHub
 PkgDev
 JSON
-HTTP
+HTTP 0.6.0
 ProgressMeter
+Nullables
```
cc: @staticfloat

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by staticfloat** [comment]
Looks like `JuliaCIBot` isn't configured properly for unprivileged containers, so it tries to use privileged containers and fails on the `sudo`.  That is fine.  :)

**Comment by aviks** [comment]
JuliaCIBot is running on a docker container, using an Ubuntu image. What kind of magic incantation do we need, @staticfloat ?

**Comment by staticfloat** [comment]
So this will work if you disable the `seccomp` profile docker uses to prevent the usage of certain syscalls.  [Read more here](https://docs.docker.com/engine/security/security/#other-kernel-security-features).  Here's my test environment in a `Dockerfile`:

```
FROM staticfloat/julia:v0.6-x64

RUN julia -e 'Pkg.add("BinaryBuilder"); using BinaryBuilder; BinaryBuilder.update_rootfs(["x86_64-linux-gnu"])'
```

When I run it, we need to provide the `CAP_SYS_ADMIN` capability mask:
```
$ docker run --cap-add=SYS_ADMIN -ti bb_test julia --color=yes -e 'using BinaryBuilder; BinaryBuilder.versioninfo()'
WARNING: PkgDev.jl is not configured. Please, run `PkgDev.config()` before performing any operations.
Info: Julia versioninfo():
Julia Version 0.6.1
Commit 0d7248e2ff (2017-10-24 22:15 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1230 v6 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Info: BinaryBuilder.jl version: 819b085e57e405b7f845f4d81e68e771f3382cb9
Info: Kernel version: 4.15.7-1-ARCH
Info: Preferred runner: BinaryBuilder.UserNSRunner
Info: Relevant envionment variables:
Info: Trying to run `echo hello julia` within a Linux x86_64 environment...
Info: Destination file /root/.julia/v0.6/BinaryBuilder/deps/downloads/rootfs-base.tar.gz already exists, verifying...
Info: Hash cache is consistent, returning true
Info: Destination directory /root/.julia/v0.6/BinaryBuilder/deps/root/ already exists, returning
Info: Destination file /root/.julia/v0.6/BinaryBuilder/deps/downloads/rootfs-x86_64-linux-gnu.tar.gz already exists, verifying...
Info: Hash cache is consistent, returning true
Info: Destination directory /root/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-linux-gnu already exists, returning
Info: Destination directory /root/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-linux-gnu already exists, returning
verbose sandbox enabled (running in privileged container mode)
Parsed --rootfs as "/root/.julia/v0.6/BinaryBuilder/deps/root"
Parsed --workspace as "/"
Parsed --cd as "/workspace/"
Parsed --map as "/root/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-linux-gnu" -> "/opt/x86_64-linux-gnu"
--> Creating overlay workdir at /proc
--> Mounting overlay of /root/.julia/v0.6/BinaryBuilder/deps/root at /root/.julia/v0.6/BinaryBuilder/deps/root (modifications in /proc/upper/rootfs)
--> Mapping /root/.julia/v0.6/BinaryBuilder/deps/shards/x86_64-linux-gnu to /root/.julia/v0.6/BinaryBuilder/deps/root/opt/x86_64-linux-gnu
--> Mounting overlay of /root/.julia/v0.6/BinaryBuilder/deps/root/opt/x86_64-linux-gnu at /root/.julia/v0.6/BinaryBuilder/deps/root/opt/x86_64-linux-gnu (modifications in /proc/upper/x86_64-linux-gnu)
--> Mounting procfs at /root/.julia/v0.6/BinaryBuilder/deps/root/proc
--> Mounting /dev/null at /root/.julia/v0.6/BinaryBuilder/deps/root/dev/null
--> Mounting procfs at /proc
Child Process PID is 32
--> Mapping 0:0 to root:root within container namespace
About to run `/bin/bash` `-c` `echo hello julia`
hello julia
Child Process exited, exit code 0
```

Does that work for you?

**Comment by staticfloat** [comment]
Oh, important note: this locked up two 4.4 kernels for me, it only worked well on my `4.15` Arch box; so there are probably some kernel bugs that have been fixed between 4.4 and 4.15.

**Pull request merged**
