### PR TITLE
Register GitLab

### PR DESCRIPTION
**Pull request by mdpradeep**

### CODE REVIEW

**Comment by tkelman** [comment]
can you push the git tag so it shows up under https://github.com/JuliaComputing/GitLab.jl/releases ?

**Comment by tkelman** [comment]
I think JLD should still be listed in `test/REQUIRE`, not commented out? https://github.com/JuliaComputing/GitLab.jl/blob/60354dec877ab64ae06310c807490736952ca667/test/event_tests.jl

**Comment by mdpradeep** [comment]
Updated the test dependency - https://github.com/JuliaComputing/GitLab.jl/blob/master/test/REQUIRE

**Comment by tkelman** [comment]
That would need a new tag to get released. That can be done separately.

**Pull request merged**
