### PR TITLE
Register new package MOpt.jl v1.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [floswald/MOpt.jl](https://github.com/floswald/MOpt.jl)
Release: [v1.3.0](https://github.com/floswald/MOpt.jl/releases/tag/v1.3.0)
Travis: [Travis Build Status](https://travis-ci.org/floswald/MOpt.jl/builds/215858281)
cc: @floswald

### CODE REVIEW

**Comment by tkelman** [comment]
Would be a bit more descriptive and clearer to call this something like MomentOpt, wouldn't it?

**Comment by floswald** [comment]
yes, you are probably right. am i still in time to change the name?

**Comment by tkelman** [comment]
yeah, we leave new package registration pr's open for at least 24 hrs for this kind of thing. attobot will replace this with a new pr if you re-tag, we can just close this one if you'd like to do that

**Comment by floswald** [comment]
ok that makes sense. yes can you please close this one and I fix those
things first. thanks!

**Pull request closed without merging**
