### PR TITLE
Tag Graphics.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphics/Graphics.jl](https://github.com/JuliaGraphics/Graphics.jl)
Release: [v0.2.0](https://github.com/JuliaGraphics/Graphics.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphics/Graphics.jl/builds/214943124)
Diff: [vs v0.1.5](https://github.com/JuliaGraphics/Graphics.jl/compare/2993c7b9a8a777fa4973d920807f8a74a45e60ee...7b23e2eb67bc1e90ac38f394d6000e407c581e78)
`requires` vs v0.1.5: no changes
cc: @timholy

### CODE REVIEW

**Comment by tkelman** [comment]
If deprecating things, probably best to also drop 0.4 support at the same time? Many downstream packages won't be updating for 0.4.

**Comment by tkelman** [comment]
[GtkUtilities](http://pkg.julialang.org/logs/GtkUtilities_0.5.log) and [ImageView](http://pkg.julialang.org/logs/ImageView_0.5.log) are apparently having issues with this - or possibly the new AxisArrays or ImageAxes, not sure which is causing the trouble.

**Comment by timholy** [comment]
I guess C callbacks don't like julia issuing depwarns in the middle of the callback.

https://github.com/timholy/GtkUtilities.jl/pull/22
https://github.com/timholy/ImageView.jl/pull/113

**Comment by tkelman** [comment]
Thanks! Is that a bug?

**Comment by timholy** [comment]
Yes. Could be hard to fix, though. I can prevent it from borking GtkUtilities with the following diff against the old one:
```diff
diff --git a/test/pan_zoom.jl b/test/pan_zoom.jl
index d2f7c46..43ac48a 100644
--- a/test/pan_zoom.jl
+++ b/test/pan_zoom.jl
@@ -6,7 +6,7 @@ win = Window(c, "PanZoomCanvas")
 showall(win)
 panzoom(c, (0,1), (0,1))
 
-draw(c) do widget
+@guarded draw(c) do widget
     xview, yview = guidata[widget, :xview], guidata[widget, :yview]
     ctx = getgc(widget)
     set_coords(ctx, xview, yview)
diff --git a/test/runtests.jl b/test/runtests.jl
index 41eaa9e..cd302e4 100644
--- a/test/runtests.jl
+++ b/test/runtests.jl
@@ -5,6 +5,6 @@ include("utils.jl")
 include("gui_data.jl")
 include("link.jl")
 include("rubber_band.jl")
-sleep(0.5)
+sleep(5)
 include("pan_zoom.jl")
 sleep(0.5)
```
but that would be irritating to have such a long sleep.

**Pull request merged**
