### PR TITLE
Tag NLOptControl.jl v0.2.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMPC/NLOptControl.jl](https://github.com/JuliaMPC/NLOptControl.jl)
Release: [v0.2.2](https://github.com/JuliaMPC/NLOptControl.jl/releases/tag/v0.2.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMPC/NLOptControl.jl/builds/456256484)
Diff: [vs v0.1.6](https://github.com/JuliaMPC/NLOptControl.jl/compare/0269a566dc7b4c0e108dbb185d061a3ca99fea0d...6d8eafc52ccdc7a5841eb2d5909b67c07e9196b0)
`requires` vs v0.1.6: 
```diff
--- 0.1.6/requires
+++ 0.2.2/requires
@@ -1,11 +1,15 @@
-julia 0.6
-FastGaussQuadrature
-JuMP
+julia 0.6-
+FastGaussQuadrature 0.3.2
+JuMP 0.18.4
 DataFrames 0.11
-Ipopt
-KNITRO
-Interpolations
-MathProgBase
+Ipopt 0.4.3
+KNITRO 0.4
+Interpolations 0.8.0
+MathProgBase 0.7.7
 CSV 0.2.4
-OrdinaryDiffEq
-DiffEqBase
+OrdinaryDiffEq 3.21.0
+DiffEqBase 3.13.3
+Colors 0.8.2
+Plots 0.17.4
+GR 0.35
+Hiccup 0.1.1
```
cc: @huckl3b3rry87

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please just update #19563

**Comment by huckl3b3rry87** [comment]
I do not know how to do this with autobot. It there a tutorial somewhere?

**Comment by huckl3b3rry87** [comment]
thanks

**Comment by andreasnoack** [comment]
Yes, there is documentation on Attobot github page, https://github.com/attobot/attobot#updatingdeleting-a-release.

**Pull request closed without merging**
