### PR TITLE
Tag ImageTransformations.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaImages/ImageTransformations.jl](https://github.com/JuliaImages/ImageTransformations.jl)
Release: [v0.3.0](https://github.com/JuliaImages/ImageTransformations.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaImages/ImageTransformations.jl/builds/232830652)
Diff: [vs v0.2.2](https://github.com/JuliaImages/ImageTransformations.jl/compare/984146c3ccf2b4c57c0f85c4a481d5396ac1f1b9...d1388171ba37616d62240664fcd1f4a858defc26)
`requires` vs v0.2.2: 
```diff
--- 0.2.2/requires
+++ 0.3.0/requires
@@ -5,7 +5,9 @@
 AxisAlgorithms
 OffsetArrays
 StaticArrays
+IdentityRanges
 Colors 0.7.0
 ColorVectorSpace 0.2
 FixedPointNumbers 0.3
-Compat 0.18
+ShowItLikeYouBuildIt
+Compat 0.19
```
cc: @Evizero

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by Evizero** [comment]
I am pretty sure these JuliaCIBot errors under "new" come from Julia not being started with `--color=yes`, which our CI scripts do. At least that were the kind of errors I have observed before adding that flag.

**Comment by tkelman** [comment]
should the tests perhaps check have_color in order to be a bit more flexible?

**Comment by Evizero** [comment]
maybe. I need to think on this. Is skipping tests really that much better? I guess one would at least see if the other tests pass. Yet on first thought I'd rather require color enabled for the tests. Either way a more informative error message would be a good idea

**Comment by Evizero** [comment]
This isn't merge-blocking, is it? Both AppVeyor and Travis pass on the repository itself

**Comment by tkelman** [comment]
not merge blocking, but worth thinking about if it's a new requirement, since a lot of programmatic calls to Pkg.test won't necessarily have color enabled

**Comment by Evizero** [comment]
understood

**Pull request merged**
