### PR TITLE
Tag NLsolve.jl v0.10.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/NLsolve.jl](https://github.com/JuliaNLSolvers/NLsolve.jl)
Release: [v0.10.1](https://github.com/JuliaNLSolvers/NLsolve.jl/releases/tag/v0.10.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaNLSolvers/NLsolve.jl/builds/237417450)
Diff: [vs v0.10.0](https://github.com/JuliaNLSolvers/NLsolve.jl/compare/4cb7d75b975637a6f0fe23862225a2bcc4b1d5a0...21c079d994f32b0982367c9c6f54164cc7f19a43)
`requires` vs v0.10.0: 
```diff
--- 0.10.0/requires
+++ 0.10.1/requires
@@ -1,7 +1,7 @@
 julia 0.6.0-pre
-Optim
 Calculus
 Distances
 ForwardDiff 0.5.0
 LineSearches
 DiffBase
+NLSolversBase 2.1.0
```
cc: @KristofferC

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by KristofferC** [comment]
@pkofod

**Comment by pkofod** [comment]
Disentangles (finally) Optim and NLsolve, so we avoid a lot of the conflicts we've had in the past as well. Allows https://github.com/JuliaLang/METADATA.jl/pull/9585 to move forward.

**Comment by pkofod** [comment]
JuliaCIBot fails due to Complimentary.jl hitting the ForwardDiff issue

**Comment by tkelman** [comment]
I think it should actually be fine, the problem is because JuliaCIBot checks out the package-being-tagged, rather than letting Pkg resolution respect bounds. There's no tagged version of JuMP that's compatible with ForwardDiff 0.5.0 yet, so having NLsolve checked out means JuMP can't be installed at the same time. If you just do `Pkg.add.(["JuMP", "NLsolve"])`, it'll install an older version of NLsolve that's compatible with older ForwardDiff, everything should be fine.

**Comment by KristofferC** [comment]
Thanks for the explanation. It seems that checking out the package being tagged is sort of a bug since it is not how a user would do?

**Comment by tkelman** [comment]
Yeah, we should fix JuliaCIBot to do normal Pkg.add (with metadata based on the merge commit of the pr) instead of checkout.

**Comment by pkofod** [comment]
(going slightly off topic, so I'll put it in secret parentheses, but disregarding checkout vs add, that bot is a super nice addition to the METADATA workflow!)

**Pull request merged**
