### PR TITLE
RecursiveArrayTools bounds

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
For the type piracy elimination

### CODE REVIEW

**Comment by tkelman** [comment]
Almost like you've done this before. 
```
$ git grep -l RecursiveArrayTools | xargs dirname | xargs dirname | xargs dirname | sort -u
.
DelayDiffEq
DiffEqBase
DiffEqDevTools
DiffEqJump
DiffEqParamEstim
MultiScaleArrays
OrdinaryDiffEq
StochasticDiffEq
```

So will DelayDiffEq, DiffEqJump, DiffEqParamEstim, MultiScaleArrays, Ordinary- and StochasticDiffEq notice this? (That doesn't count test-dependencies)

**Comment by ChrisRackauckas** [comment]
The only usage of the extended mean is inDiffEqBase and DiffEqDevTools. The other stuff in the updated RecursiveArrayTools is just new.

**Comment by ChrisRackauckas** [comment]
>Almost like you've done this before.

Not on RecursiveArrayTools. But yes, these last few weeks have been tidying up the Base libraries for a 2.0.0 release, and that means cleaning up a lot of mistakes made really early on that are used in all of the testing and basic type constructions. Hopefully this is the last of it, which is why it's the 2.0.0 release.

**Comment by tkelman** [comment]
Was mostly in response to the artificial dependency on the 0.0.1 tags, which I know we've gone through elsewhere.

**Pull request merged**
