### PR TITLE
Register new package OmniSci.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [omnisci/OmniSci.jl](https://github.com/omnisci/OmniSci.jl)
Release: [v0.1.0](https://github.com/omnisci/OmniSci.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/omnisci/OmniSci.jl/builds/448466114)
cc: @randyzwitch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@randyzwitch This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by randyzwitch** [comment]
This fails because I listed `julia 1.0.1` as my requirement. How should I resolve this?

**Comment by andreasnoack** [comment]
> This fails because I listed julia 1.0.1 as my requirement.

Why do you think that? The error is
```julia
ERROR: LoadError: IOError: connect: connection refused (ECONNREFUSED)
Stacktrace:
 [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
 [2] wait() at ./event.jl:255
 [3] wait(::Condition) at ./event.jl:46
 [4] stream_wait(::Sockets.TCPSocket, ::Condition) at ./stream.jl:47
 [5] wait_connected(::Sockets.TCPSocket) at ./stream.jl:263
 [6] connect at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Sockets/src/Sockets.jl:444 [inlined]
 [7] connect(::String, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Sockets/src/Sockets.jl:427
 [8] connect(::String, ::Int64, ::String, ::String, ::String) at /home/jrun/OmniSci.jl/src/misc.jl:19
 [9] top-level scope at none:0
 [10] include at ./boot.jl:317 [inlined]
 [11] include_relative(::Module, ::String) at ./loading.jl:1038
 [12] include(::Module, ::String) at ./sysimg.jl:29
 [13] include(::String) at ./client.jl:388
 [14] top-level scope at none:0
in expression starting at /home/jrun/OmniSci.jl/test/runtests.jl:13
```

**Comment by randyzwitch** [comment]
@andreasnoack I was referring to this:

`┌ Warning: julia version requirement for package OmniSci not satisfied`, misread it as the failure instead of a warning

**Comment by randyzwitch** [comment]
I think this error is because I expect to be able to connect to a Docker image, which happens as part of my Travis build but I presume not during JuliaCIBot. Is there a way to work around this?

**Comment by andreasnoack** [comment]
That is probably currently a limitation in CIBot and I'm not sure when we'll be able to handle such a case. For the time being we can add the package to a list of untestable packages.

**Comment by randyzwitch** [comment]
Adding it to the untestable packages is fine, I will be maintaining a robust test suite for my own purposes anyway

**Comment by andreasnoack** [comment]
CIBot testing is also more critical for packages with many reverse dependencies and it might take a while before this new packages will be in that situation. I'll add it to the list.

**Comment by randyzwitch** [comment]
Yeah, there likely won't be any reverse dependencies (or, they will be written by me or my co-workers!)

**Pull request merged**
