### PR TITLE
Tag ForwardDiff v0.1.4

### PR DESCRIPTION
**Pull request by KristofferC**
Most important fixes are:

- https://github.com/JuliaDiff/ForwardDiff.jl/pull/82
- https://github.com/JuliaDiff/ForwardDiff.jl/commit/f9d1e44d47fecfa43fc8d397f8e8ab49cad28d0c

cc @mlubin @jrevels

### CODE REVIEW

**Comment by mlubin** [comment]
:+1: thanks!

**Comment by KristofferC** [comment]
Green = go?

**Comment by jrevels** [comment]
:100:

**Comment by gragusa** [comment]
👏🏼

**Pull request merged**
