### PR TITLE
Pull request/91524065

### PR DESCRIPTION
**Pull request by kzahedi**

### CODE REVIEW

**Comment by tkelman** [comment]
Could you remove the files for 0.3.1 and 0.3.2? You can push additional commits to this same branch instead of having to open a new PR.

**Comment by kmsquire** [comment]
Bump

**Comment by aviks** [comment]
Hi @kzahedi is this still relevant?

**Comment by MikeInnes** [comment]
Closing this as we haven't heard from you in a while. Do let me know if you want to re-open.

**Pull request closed without merging**
