### PR TITLE
Pull request/c88d363f

### PR DESCRIPTION
**Pull request by magerton**
Fixes REQUIRE to (hopefully) get Julia CIBot happy...

### CODE REVIEW

**Comment by tkelman** [comment]
It would probably be best to delete the METADATA sha and requires files for the tags before 0.0.5 that were missing the Distributions dependency from the PR branch of your METADATA fork here: https://github.com/magerton/METADATA.jl/tree/pull-request/c88d363f/MarkovTransitionMatrices/versions

Otherwise looks okay, could use a bit of content in the readme.

**Comment by magerton** [comment]
Thanks, @tkelman . I added a readme and deleted the old tags since they were mistakes (I was just figuring out how the `PkgDev.tag()` worked). 

Everything has been squashed into one commit now, but I'm afraid I've broken something by doing that. Should I close this & start over w/ a new PR? Apologies for the back & forth!

**Comment by tkelman** [comment]
I restarted Travis, we'll see if it's happy now. No problem with back and forth. As I said attobot may make your life easier next time instead of using PkgDev.

**Comment by magerton** [comment]
Thanks-attobot looks much easier.

Looks like the checks passed, but I did see that [Travis](https://travis-ci.org/JuliaLang/METADATA.jl/builds/263565883?utm_source=github_status&utm_medium=notification) lists `Tag MarkovTransitionMatrices v0.0.3` when the tag should be v0.0.1. Not sure if this is a problem or not.

Thanks again!

**Comment by tkelman** [comment]
That's from your commit message. Not an issue, not worth modifying.

**Comment by magerton** [comment]
Ah, ok. Thanks.

**Pull request merged**
