### PR TITLE
Register / tag LightGraphsExtras.jl

### PR DESCRIPTION
**Pull request by sbromberger**
Extra functionality for LightGraphs that has heavy external dependencies.

See [LightGraphsExtras.jl](https://github.com/JuliaGraphs/LightGraphsExtras.jl) for more info.

### CODE REVIEW

**Comment by sbromberger** [comment]
Just an FYI - as soon as this is merged I can go ahead and merge/publish a new version of LightGraphs that removes the JuMP dependency.

**Comment by ihnorton** [comment]
@sbromberger looks like this may be pointing a commit that isn't in the repo? (did you rebase and force push?)

**Comment by sbromberger** [comment]
@ihnorton probably. How do I fix that?

**Comment by ihnorton** [comment]
change the sha in this PR to the current head in your repo.

**Comment by sbromberger** [comment]
Ok, I think I've done it :)

**Comment by sbromberger** [comment]
Thank you!!

**Pull request merged**
