### PR TITLE
Tag Compat.jl v1.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaLang/Compat.jl](https://github.com/JuliaLang/Compat.jl)
Release: [v1.4.0](https://github.com/JuliaLang/Compat.jl/releases/tag/v1.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaLang/Compat.jl/builds/455734921)
Diff: [vs v1.3.0](https://github.com/JuliaLang/Compat.jl/compare/052636a58dcffc3c810d48bc3818293dde924902...26852f74f97f61102a1b77b4a2636ab51a29f827)
`requires` vs v1.3.0: no changes
cc: @ararslan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like JuliaCIBot reported QuickTypes on 0.6 as a failure, but looking at the log the tests actually passed: https://s3.ap-south-1.amazonaws.com/juliarun-ci/96f8fd142c9c44904c60f0eb33c1069663b0b1b6/Compat_reverse_dependency_tests.html. Same seems to be true for Compat itself on 0.6, 0.7, and 1.0.

**Comment by ararslan** [comment]
@andreasnoack, any idea what's up with that?

**Comment by andreasnoack** [comment]
It sometimes happens. We don't understand why.

**Comment by ararslan** [comment]
Computers are weird

**Pull request merged**
