### PR TITLE
Tag WinRPM.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPackaging/WinRPM.jl](https://github.com/JuliaPackaging/WinRPM.jl)
Release: [v0.3.0](https://github.com/JuliaPackaging/WinRPM.jl/releases/tag/v0.3.0)
Diff: [vs v0.2.5](https://github.com/JuliaPackaging/WinRPM.jl/compare/8b606a793ef519687cf4bbda029a1bb2c4744ee2...046300a042afca8c6e08aa4c485273e0074e38d0)
`requires` vs v0.2.5: 
```diff
--- 0.2.5/requires
+++ 0.3.0/requires
@@ -1,8 +1,8 @@
-julia 0.4
-Compat 0.10.0
+julia 0.6
+Compat 0.30.0
 URIParser 0.0.3
 @unix HTTPClient 0.0.0
-LibExpat 0.0.3
+LibExpat 0.2.8
 Libz
 BinDeps 0.3
 SHA
```
cc: @ararslan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
@ararslan Is it expected that this one fails CIBot?

**Comment by ararslan** [comment]
I'm not entirely sure, since there's no CI set up on this package, but I imagine that it would fail since WinRPM is intended for use on Windows and JuliaCIBot runs Linux.

**Comment by andreasnoack** [comment]
So good to go?

**Comment by ararslan** [comment]
¯\\\_(ツ)\_/¯ I guess so

**Pull request merged**
