### PR TITLE
Tag ErrorfreeArithmetic.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/ErrorfreeArithmetic.jl](https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl)
Release: [v0.1.0](https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JeffreySarnoff/ErrorfreeArithmetic.jl/builds/402100780)
Diff: [vs v0.0.3](https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl/compare/47ea7652e4d4149f2c5a5779745249967e6984f6...7226a5f1fe39c8680f7c29217c0e8ddba7221bd1)
`requires` vs v0.0.3: 
```diff
--- 0.0.3/requires
+++ 0.1.0/requires
@@ -1 +1 @@
-julia 0.5.0
+julia 0.7.0
```
cc: @JeffreySarnoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
You probably want to make this `julia 0.7-beta` since `0.7` isn't out yet.

**Comment by JeffreySarnoff** [comment]
corrected

**Comment by andreasnoack** [comment]
You'll need to remove and reapply the tag before the PR will be updated.

**Comment by JeffreySarnoff** [comment]
thanks

**Pull request merged**
