### PR TITLE
Register new package Hamiltonian.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Quantum-Many-Body/Hamiltonian.jl](https://github.com/Quantum-Many-Body/Hamiltonian.jl)
Release: [v0.0.1](https://github.com/Quantum-Many-Body/Hamiltonian.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/Quantum-Many-Body/Hamiltonian.jl/builds/449368550)
cc: @waltergu

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@waltergu This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Seems like QuantumLatticeHamiltonians.jl would be a more precise name. The current name seems far too generic.

**Comment by GiggleLiu** [comment]
After `Boltzmann.jl`, `Shannon.jl`, `Turing.jl` and `Laplacians.jl`, we are going to have `Hamltonian.jl` now?

Maybe `QuantumLatticeHamiltonians.jl` is a bit too long :smile: , the author won't take it. Could you please explain why it is too generic? @dpsanders

**Comment by dpsanders** [comment]
One main reason is because the name Hamiltonian is used in many different fields to refer to different things.

**Comment by dpsanders** [comment]
The proposed name is not too long - there are many packages with explicit, long names.

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
