### PR TITLE
Tag IntervalSets.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMath/IntervalSets.jl](https://github.com/JuliaMath/IntervalSets.jl)
Release: [v0.3.0](https://github.com/JuliaMath/IntervalSets.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMath/IntervalSets.jl/builds/424440196)
Diff: [vs v0.2.1](https://github.com/JuliaMath/IntervalSets.jl/compare/3128af543cf4e9c04d08e0cc46fac76bd5ad829a...90576a7f8759a3a68769bc109a473807476c4979)
`requires` vs v0.2.1: 
```diff
--- 0.2.1/requires
+++ 0.3.0/requires
@@ -1,2 +1,2 @@
 julia 0.6
-Compat 0.49
+Compat 1.0
```
cc: @timholy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like this breaks `Poltergeist`

**Comment by timholy** [comment]
Sorry for the delay here. Since the breakage is because ApproxFun also exports `Interval`, perhaps @dlfivefifty can weigh in here about the best course of action?

**Comment by dlfivefifty** [comment]
Just put upper bounds for IntervalSets in ApproxFun and Poltergeist. I can do this PR if you want.

I'm in the midst of updating ApproxFun to use the new IntervalSets.jl, by splitting out the domains to https://github.com/JuliaApproximation/Domains.jl, in conjunction with @daanhb.

**Comment by timholy** [comment]
Thanks @dlfivefifty, see #17934.

**Pull request merged**
