### PR TITLE
Tag MIPVerify.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [vtjeng/MIPVerify.jl](https://github.com/vtjeng/MIPVerify.jl)
Release: [v0.1.0](https://github.com/vtjeng/MIPVerify.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/vtjeng/MIPVerify.jl/builds/424133605)
Diff: [vs v0.0.8](https://github.com/vtjeng/MIPVerify.jl/compare/23d02cdb6eab0a963f402fd8adf8b6b6e39cab15...015891c20e4de1a9f89aaab03d14609b0d247060)
`requires` vs v0.0.8: 
```diff
--- 0.0.8/requires
+++ 0.1.0/requires
@@ -1,7 +1,7 @@
 julia 0.6
-JuMP 0.17
-ConditionalJuMP 0.0.3
-Memento 0.5.0
+JuMP 0.18.1
+ConditionalJuMP 0.0.5
+Memento 0.8.0
 AutoHashEquals 0.1.2
 MAT 0.4.0
 MathProgBase 0.6
```
cc: @vtjeng

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider adding upper bounds on Julia if the package doesn't work with 0.7/10 yet

**Comment by vtjeng** [comment]
Modifying the `requires` file to reflect that; will update PR --- please don't merge till then.

**Comment by vtjeng** [comment]
@andreasnoack, is there a guide for specifying compatibility in the new package manager? Right now I'm writing the depedency as `julia 0.6 0.7`, but I'm not sure if that's standard.

**Comment by andreasnoack** [comment]
`julia 0.6 0.7` in the REQUIRE file would still be the right way of doing it. Once, the new registry system is fully implemented this will change but for now, we still use the REQUIRE file.

**Pull request merged**
