### PR TITLE
Register new package SPH.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rkat/SPH.jl](https://github.com/rkat/SPH.jl)
Release: [v0.0.1](https://github.com/rkat/SPH.jl/releases/tag/v0.0.1)
cc: @rkat

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@rkat This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Maybe the name could be a bit more explicit -- I was excited that this might be about Smooth Particle Hydrodynamics. E.g. SphereFiles.jl

**Comment by rkat** [comment]
Was trying to keep consistency with other file format packages e.g. WAV, FLAC, JSON. It’s a bit of work to change the name of the repository but I’m happy to if you have a strong opinion.

**Comment by andreasnoack** [comment]
I think we now have established a precedence of allowing acronyms that match file extensions supported by the package.

**Comment by dpsanders** [comment]
Sure, but personally I would prefer those to be `FLACFiles.jl`, `WAVFiles.jl` etc. or similar; or I guess now they can just be part of a `FileFormats` depot.

**Pull request merged**
