### PR TITLE
Tag TensorFlow v0.4.0 [https://github.com/malmaud/TensorFlow.jl]

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by tkelman** [comment]
let these get reviewed please?

**Comment by malmaud** [comment]
Oh sorry, I thought we had a policy that green METADATA commits to your own package were g2g

**Comment by tkelman** [comment]
quoting your roommate,
> write access to METADATA is like permission to push code to every Julia user's computer

so best for at least one other person to at least check that nothing malicious is going on

**Comment by malmaud** [comment]
Noted

**Comment by tkelman** [comment]
I'll be adding a quick-comparison link to the PkgDev generated commit message to make that diff-skimming easier to get to

**Comment by tkelman** [comment]
and one of the most urgent needs for Pkg3 will be formalizing the https://github.com/JuliaLang/METADATA.jl/issues/2800 issue of curation for the default registry, separated from anything-goes opt-in user registries

**Pull request merged**
