### PR TITLE
Register new package Quante.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jarvist/Quante.jl](https://github.com/jarvist/Quante.jl)
Release: [v0.0.1](https://github.com/jarvist/Quante.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/jarvist/Quante.jl/builds/418794788)
cc: @jarvist

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@jarvist This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by jarvist** [comment]
The JuliaCIBot failed with what looks like configuration / missing API key errors.
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
0615d00fa606b0cccb323f090404836ba15c7d69/PolaronMobility_julia_0_6.log
</Key>
<RequestId>E5D8E1B90DD555C1</RequestId>
<HostId>
ykm2a52mhsvCkxgvXUowkPklvZCQME65xLbXDkB8MoDs+VxH/VJZvaPowQhUpivmHZ3DCTuXL54=
</HostId>
</Error>
```

**Comment by andreasnoack** [comment]
It looks like Travis tests are failing. Please, also upper bound Julia in the REQUIRE file if Julia 0.7 isn't supported. It would probably be better to make the package work for Julia 1.0 though since it is now the official release version.

**Comment by jarvist** [comment]
OK, patched REQUIRE + re-released making it explicit that 0.6-0.7 is supported. 
The failing CI is due to 1 of ~120 tests failing, for comparison to a literature value. 
This will be the last (only) release on 0.6, before moving wholly to 1.0+ .

**Comment by jarvist** [comment]
@andreasnoack a gentle bump.

**Pull request merged**
