### PR TITLE
Tag IntervalArithmetic.jl v0.10.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIntervals/IntervalArithmetic.jl](https://github.com/JuliaIntervals/IntervalArithmetic.jl)
Release: [v0.10.0](https://github.com/JuliaIntervals/IntervalArithmetic.jl/releases/tag/v0.10.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIntervals/IntervalArithmetic.jl/builds/244333171)
Diff: [vs v0.9.1](https://github.com/JuliaIntervals/IntervalArithmetic.jl/compare/64f72c729b6a4243cfdbcf8da9b5e126d116cd12...e867be4e3796635b4037f7580996d374a46bd888)
`requires` vs v0.9.1: 
```diff
--- 0.9.1/requires
+++ 0.10.0/requires
@@ -1,4 +1,6 @@
 julia 0.5
 CRlibm 0.5
 StaticArrays 0.3
+FastRounding 0.0.4
+AdjacentFloats 0.0.4
 RecipesBase
```
cc: @dpsanders

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by dpsanders** [comment]
cc @lbenet

**Comment by tkelman** [comment]
Should the renames have deprecations put in?

**Comment by dpsanders** [comment]
Good point, thanks.

I have done that on the `deprecate_inf_sup` branch. So should I retag with that commit?

**Comment by tkelman** [comment]
reverse CI is broken right now (cc @nkottary, please respond with an ETA on getting that working again) so we won't see what would be broken otherwise

**Comment by dpsanders** [comment]
Deprecations added; this is ready to merge.

**Comment by tkelman** [comment]
Looks like IntervalRootFinding is now hitting a tolerance issue due to this https://github.com/JuliaCI/pkg.julialang.org/blob/6066c6af620f543dc6351c42ff8c3b332a9c7bbe/logs/IntervalRootFinding_0.5.log

**Pull request merged**
