### PR TITLE
Tag CUTEst v0.2.0 [https://github.com/JuliaSmoothOptimizers/CUTEst.jl]

### PR DESCRIPTION
**Pull request by abelsiqueira**
Diff vs v0.1.0: https://github.com/JuliaSmoothOptimizers/CUTEst.jl/compare/484f045156cea4ef4f1571297f10cec525e4e3d4...d3803953c278fdb1d9e5e5a6e6d65bd96932af83

### CODE REVIEW

**Comment by tkelman** [comment]
You still have a `using Compat` in `deps/build.jl`

**Comment by abelsiqueira** [comment]
Thanks. Did I update correctly?

**Comment by tkelman** [comment]
missing the git tag

**Comment by abelsiqueira** [comment]
Done

**Pull request merged**
