### PR TITLE
Register new package REDCap.jl v1.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bcbi/REDCap.jl](https://github.com/bcbi/REDCap.jl)
Release: [v1.0.1](https://github.com/bcbi/REDCap.jl/releases/tag/v1.0.1)
Travis: [Travis Build Status](https://travis-ci.org/bcbi/REDCap.jl/builds/421725600)
cc: @FLCN17

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@FLCN17 This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by FLCN17** [comment]
This replaces PR #17385

**Comment by andreasnoack** [comment]
Next time, please just update the existing release instead of making a new one.

**Comment by andreasnoack** [comment]
CIBot fails because you have a project file checked in. Please consider deleting it for the time being since it isn't needed yet.

**Comment by FLCN17** [comment]
This doesn't support Julia 0.6

**Comment by andreasnoack** [comment]
Package registration is still based on REQUIRE and not project files.

**Comment by FLCN17** [comment]
Updated, but just to be clear, is the project.toml file is causing an issue? If I remove it now, will I have to re-add it in the future?

**Comment by andreasnoack** [comment]
> is the project.toml file is causing an issue?

Yes, that is the issue here.

> If I remove it now, will I have to re-add it in the future?

Yes, we are currently in a transition phase. Eventually, your package will need a project file but it's unclear when it is needed.

**Comment by FLCN17** [comment]
The JuliaCI is running my tests, but due to the nature of my package involving a private API I cannot run them outside of the users configured environment. How can I disable testing for the JuliaCI?

**Comment by andreasnoack** [comment]
How come that tests then pass on Travis?

**Comment by FLCN17** [comment]
They are disabled on travis by checking the current environment.

**Comment by andreasnoack** [comment]
I see. Eventually, we can add the package to a list of exempt packages but for now, we can just ignore the test errors.

**Comment by FLCN17** [comment]
Is there anything you need on my end for that?

**Comment by andreasnoack** [comment]
Thanks for pinging us here. I had forgotten to remove the label so I thought we were still waiting for a reply.

**Pull request merged**
