### PR TITLE
Pull request/8de3940f

### PR DESCRIPTION
**Pull request by baggepinnen**
@tkelman 
Thanks for your feedback. I hope I have done the necessary changes!

I'm a bit unsure on the naming from Robotlib to Robotlib.jl. I changed the name on the github-repo, but the old name seems to still hang around.

### CODE REVIEW

**Comment by tkelman** [comment]
You need to adjust the url for the file here too. Please add additional commits to this same branch, the new commits will show up in the same pull request instead of having to open a new pull request for each change.

**Comment by baggepinnen** [comment]
The url has been adjusted in what I hope is the correct branch!

**Comment by tkelman** [comment]
Yep, looks good now. Would your tests pass if you enabled Travis CI?

**Comment by baggepinnen** [comment]
It does not pass a travis build due to a module making use of PyPlot, which requires matplotlib and the build failed upon import or installation of matplotlib.

I'm not sure if this is an error in my usage of the PyPlot package, my REQUIRE file or maybe something else?

**Comment by tkelman** [comment]
I think there's an environment variable you can set to force PyPlot to use Conda.jl to download matplotlib, or you can use the travis apt-get addon to install matplotlib when it's running on linux.

**Comment by baggepinnen** [comment]
Build now passes for release, not for nightly

**Comment by baggepinnen** [comment]
Build now passes for release, not for nightly, with the environment set in the travis.yml file instead of the source file

**Comment by baggepinnen** [comment]
Great! Thanks for your help and patience!

**Pull request merged**
