### PR TITLE
Tag NamedTuples.jl v5.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaData/NamedTuples.jl](https://github.com/JuliaData/NamedTuples.jl)
Release: [v5.0.0](https://github.com/JuliaData/NamedTuples.jl/releases/tag/v5.0.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaData/NamedTuples.jl/builds/425425335)
Diff: [vs v4.0.2](https://github.com/JuliaData/NamedTuples.jl/compare/4d03148530531cc1f455179db2ff1a401e283f7c...e688c56b2e74bd521dee4271c2c28bb5020d3711)
`requires` vs v4.0.2: 
```diff
--- 4.0.2/requires
+++ 5.0.0/requires
@@ -1 +1 @@
-julia 0.6 0.7
+julia 0.7
```
cc: @omus

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by omus** [comment]
Even though NamedTuples.jl isn't needed any more as of Julia 0.7 this release allows packages like LibPQ to at least include NamedTuples in their REQUIRE file which allows them to use a single version which run on Julia 0.6 - 1.0.

**Comment by andreasnoack** [comment]
It looks like some bounds are needed here.

**Comment by GunnarFarneback** [comment]
I don't understand these Travis results. How does the introduction of a new Julia 0.7+ version of NamedTuples make anything worse for IterableTables v0.0.1, which has a [2.0.0 3.0.0) bound on NamedTuples?

I would understand if it had complained about #17104, but not this one.

**Comment by ararslan** [comment]
The conflicts identified by Travis seem to only be with IterableTables and Query, so cc @davidanthoff

**Comment by andreasnoack** [comment]
The resolver sometimes seems to have some issues but the easy fix here is to just put upper bounds on the old versions of IterableTables and Query.

**Comment by GunnarFarneback** [comment]
Well, it's exactly the ones which do have upper bounds on NamedTuples that get the complaints. And they are already broken on 0.7 and up.
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-linux-gnu

(v0.7) pkg> activate /tmp/emptyenvironment

(emptyenvironment) pkg> st
    Status `/tmp/emptyenvironment/Project.toml`

(emptyenvironment) pkg> add IterableTables@0.2.0
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package NamedTuples [73a701b4]:
 NamedTuples [73a701b4] log:
 ├─possible versions are: [0.0.1-0.0.3, 0.1.0, 1.0.0, 2.0.0, 2.1.0, 3.0.0-3.0.3, 4.0.0-4.0.2] or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with IterableTables [1c8ee90f] to versions: 3.0.2-3.0.3 — no versions left
   └─IterableTables [1c8ee90f] log:
     ├─possible versions are: [0.0.1-0.0.2, 0.1.0, 0.2.0, 0.3.0, 0.4.0-0.4.2, 0.5.0-0.5.2, 0.6.0-0.6.1, 0.7.0-0.7.3, 0.8.0-0.8.3] or uninstalled
     └─restricted to versions 0.2.0 by an explicit requirement, leaving only versions 0.2.0
```

**Comment by GunnarFarneback** [comment]
Ah, do you mean upper bounds on the Julia version rather than on NamedTuples?

**Comment by ararslan** [comment]
An upper bound on NamedTuples 5.0.0 has been added to versions of IterableTables and Query which currently depend on NamedTuples but don't already set an upper bound: https://github.com/JuliaLang/METADATA.jl/pull/17970

**Comment by davidanthoff** [comment]
I don’t really understand what is going on here, but the bounds seem good to me.

**Comment by ararslan** [comment]
Hm, same issue with the version resolution. :/

**Comment by GunnarFarneback** [comment]
Of course you can't solve breakage for a couple of versions of Query and IterableTables that already had NamedTuples bounds by introducing bounds on all other versions.

I suspect what's needed is to revert #17970 and #17104 and accept this PR.

**Comment by andreasnoack** [comment]
The fix is to add bounds on *Julia* in Query and IteratbleTables. See https://github.com/JuliaLang/METADATA.jl/pull/17979

**Comment by andreasnoack** [comment]
The tests here hang because the `LazyQuery` repo has been deleted which is an error case we haven't thought of. See https://github.com/JuliaLang/METADATA.jl/pull/17981

**Comment by ararslan** [comment]
Thanks for taking care of this, Andreas.

**Comment by davidanthoff** [comment]
Thanks everyone for sorting this out!

**Pull request merged**
