### PR TITLE
Register QuantumBayesian [https://github.com/justindressel/QuantumBay…

### PR DESCRIPTION
**Pull request by justindressel**
…esian.jl.git]: v0.1.0

### CODE REVIEW

**Comment by justindressel** [comment]
It seems to be complaining that the release tag v0.1.0 is possibly malformed. Please advise.

**Comment by simonbyrne** [comment]
Seems to run okay locally: it might be a stale cache from the earlier use of attobot, i'll retrigger it.

**Comment by tkelman** [comment]
superceded by https://github.com/JuliaLang/METADATA.jl/pull/7329 ?

**Comment by justindressel** [comment]
Yes, at the suggestion of Simon I retriggered the bot,.  (Thanks Simon)

**Pull request closed without merging**
