### PR TITLE
Register new package Microeconometrics.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lbittarello/Microeconometrics.jl](https://github.com/lbittarello/Microeconometrics.jl)
Release: [v0.1.0](https://github.com/lbittarello/Microeconometrics.jl/releases/tag/v0.1.0)
cc: @lbittarello

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@lbittarello This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
Would Travis CI pass if you enabled it at https://travis-ci.org/lbittarello/Microeconometrics.jl ?

**Comment by tkelman** [comment]
Since you use RDatasets in your tests, it should be added to a `test/REQUIRE` file

**Comment by lbittarello** [comment]
I added a `test/REQUIRE` file. I also enabled Travis CI. It does pass, but only for Julia 0.6, because `Optim` failed under the nightly build.

**Comment by tkelman** [comment]
Would need to update the tag for the `test/REQUIRE` change. Allowing failures on nightly is fine.

**Pull request merged**
