### PR TITLE
Tag TextParse v0.3.0, and JuliaDB v0.3.0 upperbound old releases

### PR DESCRIPTION
**Pull request by shashi**
cc @davidanthoff this is the DataValues switch.

Also requires #11306

### CODE REVIEW

**Comment by davidanthoff** [comment]
Great, thanks! I'll do a CSVFiles.jl release asap that uses the new TextParse.

**Comment by davidanthoff** [comment]
Actually, wait one moment with this one. We might not even need bounds on CSVFiles, I think it might just work with the new TextParse out of the box. I'll double check now.

**Comment by davidanthoff** [comment]
I don't think we need the bounds on CSVFiles.jl. I just tested things locally with ``master`` of TextParse.jl, and everything just works.

And it works because [here](https://github.com/davidanthoff/TableTraitsUtils.jl/blob/master/src/TableTraitsUtils.jl#L18) we have to special case any missing value representation that is not ``DataValue``, but now that TextParse.jl returns ``DataValueArray``, we don't need to convert anything and the default code path just works.

**Comment by davidanthoff** [comment]
Wait, this PR has lots of upper bounds on TextParse in the CSVFiles REQUIRE file that shouldn't be there, as far as I can tell.

**Comment by shashi** [comment]
@davidanthoff #11359

**Pull request merged**
