### PR TITLE
Register new package Lists.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ChrisRackauckas/Lists.jl](https://github.com/ChrisRackauckas/Lists.jl)
Release: [v0.0.1](https://github.com/ChrisRackauckas/Lists.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/ChrisRackauckas/Lists.jl/builds/259533714)
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ChrisRackauckas This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by aviks** [comment]
That seems to be a very generic name, no? My concern is that with a name like that, it gives the impression of being the first AND last port of call for any user who wants a _list_ of any form. Is that true? What do you think?

**Comment by ChrisRackauckas** [comment]
Yeah, that's probably true. LinkedLists.jl?

**Comment by aviks** [comment]
Yeah, that works, if you're happy with it.

**Comment by ChrisRackauckas** [comment]
Feel free to close this.

**Pull request closed without merging**
