### PR TITLE
Pull request/a9b047e4

### PR DESCRIPTION
**Pull request by dehann**
* Major upgrade to use functors for residual function definition
* Revamp of all major graph constraint types
* Several bug fixes
* interdependent change on RoME

### CODE REVIEW

**Comment by tkelman** [comment]
Do the new package registration and the tags of existing packages need to be in the same PR here?

**Comment by dehann** [comment]
Hi @tkelman, unfortunately for the most part yes... The reason for new package is that IncrementalInference is growing pretty quickly and had way too many bits of different functionality packed together.

I am moving code out of IncrementalInference into the the new package, which in turn required an upgrade which affected RoME. I'm trying to keep the PRs as isolated as possible. Hopefully this is the last of the mixed registration and tagging PRs. I know its not ideal.

You may also notice that the tests for RoME are failing in this PR, but will pass once this PR is merged. Due to a change affecting all three packages.

Happy new year!

**Comment by tkelman** [comment]
> the tests for RoME are failing in this PR, but will pass once this PR is merged. Due to a change affecting all three packages.

You should add minimum version bounds for situations like this.

**Comment by tkelman** [comment]
Caesar is using MeshIO without listing it in REQUIRE, hence failing on Travis

**Comment by dehann** [comment]
@tkelman, I think you are looking at the latest master branch for Caesar.jl. It's like a week since the PR was created, and the MeshIO is a new requirement for code under development. If you look at the Travis tests for METADATA on this PR page you will see it is actually passing. MeshIO is not required for this PR.

> You should add minimum version bounds for situations like this.

Oh, okay I was not aware I could place a minimum requirement on tags which have not been merged to METADATA yet. That is precisely why I am doing the PR together, so that all changes can come at once. I will add minimum version requirements of un-merged package tags for similar cases in the future.

I still think this pull request is good to go please.

**Comment by tkelman** [comment]
> Travis tests for METADATA on this PR page

Those don't indicate anything about the package's own tests. If you used the https://github.com/attobot/attobot package-tagging bot then there would be a link to your package's travis status badge here, and things would be a little faster to review.

**Comment by dehann** [comment]
I will look at attobot thanks.

**Comment by dehann** [comment]
The new master branch tests (fixes for MeshIO) are running for Caesar.jl now. I should be working on a topic branch for development on Caesar.jl, but the MeshIO bug made it through to master yesterday.

**Comment by dehann** [comment]
@tkelman alright thanks, Attobot looks cool. I have been getting a few METADATA branch divergences on my side since using PkgDev. I have a bi of time pressure till last week in January and will look into using attobot then, thanks for the pointer.

**Pull request merged**
