### PR TITLE
ParallelAccelerator from IntelLabs

### PR DESCRIPTION
**Pull request by ehsantn**
ParallelAccelerator is a compiler written in Julia. It performs additional analysis and optimization on top of the Julia compiler and tries automatically parallelize programs.

### CODE REVIEW

**Comment by kshyatt** [comment]
You don't have a minimum version of Julia specified in `REQUIRE`, and that's why CI is failing. The first line of `REQUIRE` should be `julia 0.3` or `julia 0.4` or similar.

**Comment by ehsantn** [comment]
The wrong commit was tagged. It's fixed now.

**Comment by kshyatt** [comment]
Great! LGTM when CI passes.

**Comment by ehsantn** [comment]
Thanks.

**Pull request merged**
