### PR TITLE
Register new package PowerDynamics.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaEnergy/PowerDynamics.jl](https://github.com/JuliaEnergy/PowerDynamics.jl)
Release: [v0.2.0](https://github.com/JuliaEnergy/PowerDynamics.jl/releases/tag/v0.2.0)
cc: @timkittel

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@timkittel This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by timziebart** [comment]
It will need #18735 to be merged first.

**Comment by dpsanders** [comment]
I cannot find any info about what this package does.

**Comment by timziebart** [comment]
Absolutely, I am currently fighting with Travis to get the docs online (:

So I added a short note in the README. It is a the main package that bundles everything we publish on modeling and simulating the dynamics of power grids (currently [PowerDynBase](https://github.com/JuliaEnergy/PowerDynBase.jl) and [PowerDynSolve](https://github.com/JuliaEnergy/PowerDynSolve.jl)). In particuarly, it provides the docs as well.

**Comment by timziebart** [comment]
Managed to win the fight, the docs are here now https://juliaenergy.github.io/PowerDynamics.jl/latest/ 

As soon as #18735 is merged, I will redo the release to trigger a new attobot comment here.

**Pull request merged**
