### PR TITLE
Tag Elly v0.0.5

### PR DESCRIPTION
**Pull request by tanmaykm**
- Julia v0.5 compatibility
- Locks to allow multiple tasks communicating over same node connection

### CODE REVIEW

**Comment by tkelman** [comment]
Just curious, what's in 0.4.3 that you need that wasn't in 0.4.0?

**Comment by tanmaykm** [comment]
Only because this is not being tested with 0.4.0-2 any more.

**Comment by ViralBShah** [comment]
Would the network performance issue affect Elly.jl? If so, that is a good reason to require 0.4.3.

**Comment by tanmaykm** [comment]
Yes, good point. It would.

**Pull request merged**
