### PR TITLE
Tag Nemo version 0.6.0

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by tkelman** [comment]
You should be using specific sha or tag versions of all the repositories that you're cloning in `deps/build.jl`, otherwise external changes can break previously-working versions of your package.

**Comment by thofma** [comment]
We are maintaining the upstream repositories and we make sure not to break anything.

**Comment by tkelman** [comment]
That helps, but doesn't change the fact that what you install with Nemo version X shouldn't depend on when you install it.

**Comment by thofma** [comment]
We have fixed upstream versions.

**Comment by thofma** [comment]
Is there something else to address?

**Comment by StefanKarpinski** [comment]
Can we reopen this and get it merged? @tkelman: please do what's needed to move this forward.

**Comment by thofma** [comment]
Waiting for one more PR in Nemo. Then I will tag it.

**Pull request closed without merging**
