### PR TITLE
Tag DetectionTheory.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [sam81/DetectionTheory.jl](https://github.com/sam81/DetectionTheory.jl)
Release: [v0.1.1](https://github.com/sam81/DetectionTheory.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/sam81/DetectionTheory.jl/builds/245076082)
Diff: [vs v0.1.0](https://github.com/sam81/DetectionTheory.jl/compare/df4a96f7a7447d5f3b4569b54903dd9305c078fb...784d35401f8ea8f862d066a9657649d73b9e71b4)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.1.1/requires
@@ -1,4 +1,4 @@
-julia 0.6-
+julia 0.6
 Distributions
 DocStringExtensions
 HDF5
```
cc: @sam81

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
If this is the only change, note that this doesn't accomplish much. Tightening bounds needs to be done in place. The previous version that claimed to support 0.6-pre is still available for Pkg to possibly use. Since I don't think it's hurting anything, probably better to wait until there are actually code changes to worry about.

**Comment by sam81** [comment]
OK I agree, there are indeed no other code changes.

**Comment by tkelman** [comment]
Looks like you deleted the git tag, should this be closed?

**Comment by sam81** [comment]
yes it can be closed, thanks

**Pull request closed without merging**
