### PR TITLE
Tag PatternDispatch v0.1.0

### PR DESCRIPTION
**Pull request by toivoh**
Should hopefully work with Julia 0.3. Going to try for 0.4 next.

### CODE REVIEW

**Comment by tkelman** [comment]
would travis pass if you turned it on?

**Comment by toivoh** [comment]
Not if it's running Julia 0.4, but the tests pass locally for me with Julia 0.3 so if I can get Travis to use that then it should.

But how do I actually turn on Travis for an old package like this? If I tag the next version with Julia 0.4 support soon, maybe it would be easier to turn on Travis by then?

**Comment by tkelman** [comment]
Doesn't really matter how old the package is, just add the yml, go to travis-ci.org and enable it in the settings, see if it works. I'll fire across a PR with the template yml to start with.

**Comment by toivoh** [comment]
Thanks!

**Pull request merged**
