### PR TITLE
Pull request/a840ec2e

### PR DESCRIPTION
**Pull request by njwilson23**
This adds a package that wraps the TEOS-10 routines for the Gibbs Sea Water equation of state. So far, now the package "works" and passes the GSW test suite.

### CODE REVIEW

**Comment by milktrader** [comment]
Cool, how about tagging a version so it can be added with `Pkg.add`.

**Comment by milktrader** [comment]
I missed that you had the versions already.

**Comment by njwilson23** [comment]
I tried this in #2442 - I'm not sure that's quite right.

**Comment by milktrader** [comment]
Yep, works

**Pull request closed without merging**
