### PR TITLE
Tag DictFiles/ExtemelyRandomizedTrees/Shapemodels/InformedDE/LaTeX

### PR DESCRIPTION
**Pull request by rened**

### CODE REVIEW

**Comment by aviks** [comment]
Could you possibly squash the two Latex commits? Not sure if they might cause issues with case sensitive file systems.

**Comment by rened** [comment]
Sure! You mean like this?

**Comment by aviks** [comment]
Yes, that is what I meant, thanks!

But looking at the commit I now understand what you are doing, and I am wondering, if someone on a Mac already has `Latex.jl` installed, and now runs a `Pkg.update()` will that cause problems? I'm wary because we've had issues in the past with case-renames on the mac. 

On the other hand, this is clearly the right thing to do, so maybe we should just do this and handle any support issues as and when they come in?

@IainNZ @jiahao  any thoughts?

**Comment by jiahao** [comment]
I don't remember what had to be done in the past...

**Comment by IainNZ** [comment]
Yeah something might break... but I think its probably best to just do it anyway.

**Comment by kmsquire** [comment]
I think any existing users on case insensitive filesystems will have to remove the package entirely, and then reinstall. 

If true, I wonder if this will happen often enough that we should try to detect this situation and do that for the user...?

**Comment by jiahao** [comment]
Looks like we should merge this and deal with the fallout.

**Comment by jiahao** [comment]
Ref #2064

**Pull request merged**
