### PR TITLE
Tag Rotations.jl v0.9.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [FugroRoames/Rotations.jl](https://github.com/FugroRoames/Rotations.jl)
Release: [v0.9.0](https://github.com/FugroRoames/Rotations.jl/releases/tag/v0.9.0)
Travis: [Travis Build Status](https://travis-ci.org/FugroRoames/Rotations.jl/builds/428458414)
Diff: [vs v0.8.0](https://github.com/FugroRoames/Rotations.jl/compare/8f6890a6e41a74b0177b1862b0f1a8d07cf3db06...d080990517f89b56c37962ad53a7fd24bd94b9f7)
`requires` vs v0.8.0: no changes
cc: @tkoolen

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like it breaks RigidBodyDynamics

**Comment by tkoolen** [comment]
Yep, that'll be worked around in a PR that's already open and properly fixed soon.

**Comment by andreasnoack** [comment]
Do you want to wait for the fix before this is merged?

**Comment by tkoolen** [comment]
No, this can be merged now. The test needs to be adapted, the production code is fine.

**Pull request merged**
