### PR TITLE
Gadfly + Compose + Patchwork "conditional modules" and Escher 0.3.0

### PR DESCRIPTION
**Pull request by shashi**
moves Patchwork functionality into ComposeDiff and GadflyDiff packages

fixes https://github.com/dcjones/Gadfly.jl/issues/778 and https://github.com/dcjones/Gadfly.jl/issues/759

cc @timholy

### CODE REVIEW

**Comment by shashi** [comment]
Don't merge yet. I'm making more changes in light of fixes required in Escher.

**Comment by shashi** [comment]
Ready to merge now.

**Comment by shashi** [comment]
@tkelman could you take a look at this once?

**Comment by tkelman** [comment]
Is it possible to test Escher and the new *Diff packages on Travis?

**Comment by shashi** [comment]
I can write some tests for ComposeDiff, some parts of Escher can be tested on Travis (i.e. Pkg.test should work)

**Comment by shashi** [comment]
I can make a new release with the tests, I will do so this week. However, these changes are immediately required for people using Escher and Interact and it will be great if this PR can get in.

**Pull request merged**
