### PR TITLE
Tag JuliaWebAPI.jl v0.4.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaWeb/JuliaWebAPI.jl](https://github.com/JuliaWeb/JuliaWebAPI.jl)
Release: [v0.4.2](https://github.com/JuliaWeb/JuliaWebAPI.jl/releases/tag/v0.4.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaWeb/JuliaWebAPI.jl/builds/424418991)
Diff: [vs v0.4.1](https://github.com/JuliaWeb/JuliaWebAPI.jl/compare/e61c2c831d7d79fc2e0c5bae3039ebdb3804256e...550f4b11464fc8e6dc308108bd05368d1efd7f46)
`requires` vs v0.4.1: no changes
cc: @tanmaykm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tanmaykm** [comment]
JuliaCIBot tests seem to have passed for 0.6.4, but status is still marked as failed? Also tests did seem to have run at all on 0.7 and 1.0.

**Comment by tanmaykm** [comment]
ref: https://github.com/JuliaAttic/OldPkg.jl/issues/1

**Comment by andreasnoack** [comment]
The old package `Logging` has been deprecated and now there is a stdlib called `Logging`. Hence the solution is either to stop using `Logging` all together or to bump the versions requirement to Julia 0.7 and remove Logging from REQUIRE since it is a stdlib.

**Comment by tanmaykm** [comment]
Thanks. Will do that and re-release.

**Comment by andreasnoack** [comment]
Closing here since you'd have to make it v0.5.0 when changing the Julia requirement.

**Pull request closed without merging**
