### PR TITLE
Tag PiecewiseLinearOpt v0.0.2

### PR DESCRIPTION
**Pull request by joehuchette**
https://github.com/joehuchette/PiecewiseLinearOpt.jl

### CODE REVIEW

**Comment by tkelman** [comment]
just checking, is

> 2,479 changed files with 121,133 additions and 29 deletions.

intentional?

**Comment by joehuchette** [comment]
Yep, I added a bunch of test instances. Any reason it might cause problems?

**Comment by tkelman** [comment]
git doesn't handle large numbers of small files very well, if you don't expect to ever change the data it might be simpler to put them all in an hdf5 file

**Comment by joehuchette** [comment]
OK, I'll look into doing that in the future.

**Comment by mlubin** [comment]
The package doesn't load without JuMP 0.16 (https://github.com/joehuchette/PiecewiseLinearOpt.jl/issues/5), may want to update requires and wait for JuMP 0.16 to be released before merging.

**Pull request closed without merging**
