### PR TITLE
Tag HDF5.jl v0.10.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIO/HDF5.jl](https://github.com/JuliaIO/HDF5.jl)
Release: [v0.10.3](https://github.com/JuliaIO/HDF5.jl/releases/tag/v0.10.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIO/HDF5.jl/builds/456030832)
Diff: [vs v0.10.2](https://github.com/JuliaIO/HDF5.jl/compare/ad5f958dc6f892d3f59934352a6244e90e418a8d...2ce2abfee57d897c1a27ce338d8a7b3f2eb21bc2)
`requires` vs v0.10.2: no changes
cc: @musm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by oxinabox** [comment]
Any idea what is going wrong here?
According to JuliaCIBot this broke a lot of packages

**Comment by musm** [comment]
Hmm, biggest change is https://github.com/JuliaIO/HDF5.jl/pull/520

**Comment by musm** [comment]
most of the failures look like they're missing to add hdf5 under the travis config. I submitted PRs to several of the failing packages to fix this.

**Comment by musm** [comment]
We can merge after CI. A couple of packages have yet to merge my PRs to fix their travis configuration and tag their respective packages. But all the regressions are actually due to travis configuration with homebrew on osx.

**Comment by musm** [comment]
@oxinabox do you have permissions to merge or do we need to ping someone else?

**Comment by oxinabox** [comment]
I do not have permission to merge on METADATA.jl

**Comment by musm** [comment]
what I don't understand from the CIBot is the HDF5 failure?  The HDF5 package passes all tests in the repo's CI.

**Comment by andreasnoack** [comment]
Would you like to notify the maintainers of the packages the break because of this before merging?

**Comment by oxinabox** [comment]
This isn't a breaking change in the package.
It is the fact that Homebrew.jl is really unreliable, right?

**Comment by andreasnoack** [comment]
I see. I misunderstood. The test failure for HFD5 is spurious.

**Pull request merged**
