### PR TITLE
Register new package Expokit.jl

### PR DESCRIPTION
**Pull request by acroy**
This package provides Julia implementations of some routines contained in EXPOKIT. Those routines allow an efficient calculation of the action of matrix exponentials on vectors for large sparse matrices.

cc @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I reviewed this earlier. This is good to go once the CI passes.

**Comment by mforets** [comment]
> LoadError: METADATA/Expokit/versions/0.0.1/requires: oldest allowed julia version 0.4.0 too old (>= 0.5.0 needed)

😮

**Comment by ChrisRackauckas** [comment]
Oh yes, v0.4 METADATA is frozen. You should increase the minimum version to v0.5.

**Comment by ChrisRackauckas** [comment]
Instead of modifying

**Comment by acroy** [comment]
Sorry for the mess. I retagged the package and now it should be fine.

**Pull request merged**
