### PR TITLE
Update Codecs to v1.0

### PR DESCRIPTION
**Pull request by randyzwitch**

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider using Attobot. It makes it much easier for me to check e.g. the Travis status. Actually, I can't find the current Travis tests and it looks like the CIBot tests are failing.

**Comment by randyzwitch** [comment]
Sure thing, I’ll contact Daniel and see if he can add me to the repo to add Attobot and Travis

**Comment by randyzwitch** [comment]
@andreasnoack 

Please see: https://twitter.com/danielcjones/status/1028450402704879616

Do we have a good home for this? I'd take it, but I don't have any special background in Codecs.jl to actually maintain/improve. I was just willing to do PR reviews/merging to help @dcjones

**Comment by andreasnoack** [comment]
Do we have a good home for this? I'll ask around and get back soon.

**Comment by TransGirlCodes** [comment]
@randyzwitch @andreasnoack I'd offer BioJulia as a home as we need YAML (and so the Codecs dependency) to be released for julia 0.7 and 1.0 to continue upgrading all the BioJulia packages. But it might be better in a place like JuliaIO?

**Comment by TransGirlCodes** [comment]
May I ask what is needed for this to merge? We need YAML and Codecs releases for julia 1.0 quite urgently, in order to upgrade some of our bigger and most used packages in BioJulia.

**Comment by andreasnoack** [comment]
Sorry. I promised to get back soon. Any organization that is willing to take up the task of maintaining the package should be fine. That you have packages that depend on it seems like an advantage. I didn't merge this because I couldn't find the Travis test status. If you believe this release is ready then let me know and I'll merge. Then we can sort out the migration later.

**Comment by TransGirlCodes** [comment]
@andreasnoack 

I struggle to find Travis page, but it works for my julia 1.0 install (I'm on OSX).

```julia
N82106:Codecs.jl bward$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.0 (2018-08-08)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

(v1.0) pkg> add Codecs#v0.5.0
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `https://github.com/dcjones/Codecs.jl.git`
  Updating git-repo `https://github.com/dcjones/Codecs.jl.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [19ecbf4d] ↑ Codecs v0.4.0 ⇒ v0.4.0+ #5d692bd (https://github.com/dcjones/Codecs.jl.git)
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [19ecbf4d] ↑ Codecs v0.4.0 ⇒ v0.4.0+ #5d692bd (https://github.com/dcjones/Codecs.jl.git)

(v1.0) pkg> test Codecs
   Testing Codecs
    Status `/var/folders/h0/fmczc7390c7f_ddk7yxc47h801tjlx/T/tmpBA2cTj/Manifest.toml`
  [19ecbf4d] Codecs v0.4.0+ #5d692bd (https://github.com/dcjones/Codecs.jl.git)
  [2a0f44e3] Base64  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Base64`]
  [8ba89e20] Distributed  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Distributed`]
  [b77e0a4c] InteractiveUtils  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/InteractiveUtils`]
  [8f399da3] Libdl  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Libdl`]
  [37e2e46d] LinearAlgebra  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/LinearAlgebra`]
  [56ddb016] Logging  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Logging`]
  [d6f4376e] Markdown  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Markdown`]
  [9a3f8284] Random  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Random`]
  [9e88b42a] Serialization  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Serialization`]
  [6462fe0b] Sockets  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Sockets`]
  [8dfed614] Test  [`~/github/julia/usr/bin/../share/julia/stdlib/v1.0/Test`]
   Testing Codecs tests passed 
```

**Comment by randyzwitch** [comment]
I'm fine with merging it, both on @BenJWard showing no issues and having reviewed the PR. All the changes are minor syntax/Femtocleaner type changes

**Comment by andreasnoack** [comment]
Just tried on Linux and they pass there as well so I'll merge. Would be great if you could finalize the migration before next release.

**Comment by randyzwitch** [comment]
Sure thing, I just contacted Daniel, so we’ll get it straightened out

**Comment by TransGirlCodes** [comment]
Thanks everyone, sorry to be a pain :)

**Comment by dcjones** [comment]
I've transferred Codecs.jl and YAML.jl to BioJulia so we can better manage admin privileges. @BenJWard can make the necessary changes now (or give me or @randyzwitch admin privileges on those repos to do so).

**Pull request merged**
