### PR TITLE
Tag Luxor.jl v0.12.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphics/Luxor.jl](https://github.com/JuliaGraphics/Luxor.jl)
Release: [v0.12.0](https://github.com/JuliaGraphics/Luxor.jl/releases/tag/v0.12.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphics/Luxor.jl/builds/414902418)
Diff: [vs v0.11.2](https://github.com/JuliaGraphics/Luxor.jl/compare/3c9c448130697b1ca1a14a645265e68b9dd634f2...095948d8e109f07a3e89a7dc94015a18a6b83589)
`requires` vs v0.11.2: 
```diff
--- 0.11.2/requires
+++ 0.12.0/requires
@@ -1,9 +1,8 @@
 julia 0.7
 Cairo
+Juno
 Colors
 Dates
 FileIO
-Hiccup
-Juno
 @linux ImageMagick
 @mac QuartzImageIO
```
cc: @cormullion

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like Travis tests are failing

**Comment by cormullion** [comment]
@andreasnoack Sadly yes; I'm doing as much as I can without Cairo and Homebrew locally, but it's not easy to run things on Travis without Cairo ... :)

**Comment by andreasnoack** [comment]
What is the current Travis+Cairo situation?

**Comment by cormullion** [comment]
I think everyone's given up... :)  It can be made to work (https://github.com/JuliaGraphics/Cairo.jl/issues/230) and I can run on macOS v0.7 locally. It passes on Travis on v0.7 Linux. But Cairo doesn't compile on v1.0 anywhere.

On Linux v1.0

 ```
Building Cairo ───────────→ `~/.julia/packages/Cairo/NBtbd/deps/build.log` ┌
Error: Error building `Cairo`: │ ERROR: LoadError: syntax: misplaced assignment
statement in "[libpng = library_dependency("png", aliases = ["libpng",
"libpng-1.5.14", "libpng15", "libpng12.so.0", "libpng12"], runtime = false,
group = group); pixman = library_dependency("pixman", aliases = ["libpixman",
"libpixman-1", "libpixman-1-0", "libpixman-1.0"], depends = [libpng], runtime =
false, group = group); libffi = library_dependency("ffi", aliases = ["libffi"],
runtime = false, group = group); gettext = library_dependency("gettext",
aliases = ["libintl", "preloadable_libintl", "libgettextpo"], os = :Unix, group
= group); gobject = library_dependency("gobject", aliases =
["libgobject-2.0-0", "libgobject-2.0", "libgobject-2_0-0",
"libgobject-2.0.so.0"], depends = [libffi, gettext], group = group); freetype =
library_dependency("freetype", aliases = ["libfreetype"], runtime = false,
group = group); fontconfig = library_dependency("fontconfig", aliases =
["libfontconfig-1", "libfontconfig", "libfontconfig.so.1"], depends =
[freetype], runtime = false, group = group); cairo =
library_dependency("cairo", aliases = ["libcairo-2", "libcairo",
"libcairo.so.2", "libcairo2"], depends = [gobject, fontconfig, libpng], group =
group, validate = validate_cairo_version); pango = library_dependency("pango",
aliases = ["libpango-1.0-0", "libpango-1.0", "libpango-1.0.so.0",
"libpango-1_0-0"], group = group); pangocairo =
library_dependency("pangocairo", aliases = ["libpangocairo-1.0-0",
"libpangocairo-1.0", "libpangocairo-1.0.so.0"], depends = [cairo], group =
group); zlib = library_dependency("zlib", aliases = ["libzlib", "zlib1"], os =
:Windows, group = group)]" │ Stacktrace: │  [1] include at ./boot.jl:317
[inlined] │  [2] include_relative(::Module, ::String) at ./loading.jl:1038 │
[3] include(::Module, ::String) at ./sysimg.jl:29 │  [4] include(::String) at
./client.jl:388 │  [5] top-level scope at none:0 │ in expression starting at
/home/travis/.julia/packages/Cairo/NBtbd/deps/build.jl:19 └ @ Pkg.Operations
/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

```

**Comment by cormullion** [comment]
You can delete this PR. I'll revisit it soon.

**Pull request closed without merging**
