### PR TITLE
Tag FastRounding.jl v0.0.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/FastRounding.jl](https://github.com/JeffreySarnoff/FastRounding.jl)
Release: [v0.0.3](https://github.com/JeffreySarnoff/FastRounding.jl/releases/tag/v0.0.3)
Travis: [Travis Build Status](https://travis-ci.org/JeffreySarnoff/FastRounding.jl/builds/223003671)
Diff: [vs v0.0.2](https://github.com/JeffreySarnoff/FastRounding.jl/compare/2b7b3c02928c5e9dee294e3f78ad974b9a3efc5e...d07e0eb3d6700b7997b9e65e6d9ad739c95db07d)
`requires` vs v0.0.2: 
```diff
--- 0.0.2/requires
+++ 0.0.3/requires
@@ -1,3 +1,3 @@
 julia 0.5.0
 AdjacentFloats 0.0.2
-ErrorfreeArithmetic 0.0.1
+ErrorfreeArithmetic 0.0.3
```
cc: @JeffreySarnoff

### CODE REVIEW

**Comment by tkelman** [comment]
Does this minimum actually apply to the previous tag? If you haven't made any code changes, the previous tag of FastRounding is still available for the resolver to use with a looser bound. Tightening bounds needs to be done in-place.

**Comment by JeffreySarnoff** [comment]
No, the previous tag needed a bugfix.

**Comment by tkelman** [comment]
The only change between FastRounding v0.0.2 and FastRounding v0.0.3 is in the REQUIRE file though

**Comment by JeffreySarnoff** [comment]
true -- because the change to ErrorfreeArithmetic was a bugfix and I want this file to require the fixed version of that.

**Comment by tkelman** [comment]
Does FastRounding work at all with ErrorFreeArithmetic prior to 0.0.3? If so, then the bound isn't necessary, Pkg will usually upgrade to the newest versions possible. If not, then since FastRounding 0.0.2 is the exact same code as FastRounding 0.0.3, it would be more useful to modify the METADATA/FastRounding/versions/0.0.2/requires file with this change.

**Comment by JeffreySarnoff** [comment]
yes this works with all other versions -- I understand.  you can close this -- I will delete the version

**Pull request closed without merging**
