### PR TITLE
Register new package Makie.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPlots/Makie.jl](https://github.com/JuliaPlots/Makie.jl)
Release: [v0.0.1](https://github.com/JuliaPlots/Makie.jl/releases/tag/v0.0.1)
cc: @SimonDanisch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@SimonDanisch This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Do you have any testing infrastructure set up that can verify that a version works? Would be great with a badge.

**Comment by SimonDanisch** [comment]
I have for the next version! I finally got gitlab with opengl thanks to @maleadt!
This is just a release for the legacy version, so that I can finally merge the final refactor - but still have the first version available for people who started relying on it!

**Comment by SimonDanisch** [comment]
I could try to backport the ci for the legacy version, but it would take some time and wouldn't give me much of a benefit... I did take the time though to try it out on 2 other computers and installed it from scratch ;)

**Comment by andreasnoack** [comment]
With such a long list of dependencies, I think it is necessary to have CI running to make sure that things actually work for users. Currently, the installation fails on Mac from a clean package repo because of `Fontconfig`.

**Comment by SimonDanisch** [comment]
Oh i see, is homebrew broken? Actually, I'm just about to get rid of fontconfig right now... so maybe I should backport that!

**Comment by andreasnoack** [comment]
I think that fontconfig has often been problematic on Mac so it will probably be useful if you can avoid it.

**Comment by SimonDanisch** [comment]
ok! removed fontconfig and even activated the new opengl gitlab ci :)
https://gitlab.com/JuliaGPU/Makie.jl/pipelines/24328396

**Pull request merged**
