### PR TITLE
Register TrainingImages

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by kmsquire** [comment]
Since these are for geostastical simulation, perhaps it would be good to choose a more specific name.  Maybe GeoTrainingImages.jl or GeoStatImages.jl?

**Comment by juliohm** [comment]
@kmsquire , I was trying to come up with a more specific name, but none sounded right to me at the time. `GeoStatsImages.jl` seems like a good one. Is there any way to change the name of the repository on Github without major impacts? I see this option under Settings in the project where I can rename the repo, have you ever tried it before?

**Comment by kmsquire** [comment]
Yep, the rename option under Settings should work fine--in fact, the old repo will redirect to the new one. I would rename it there, re-clone, and rename `src/TrainingImages.jl` to `src/GeoStatsImages.jl`.  I think that'll be all you need.

**Comment by juliohm** [comment]
Will do, thanks.

**Pull request closed without merging**
