### PR TITLE
Registering RobustShortestPath v0.0.1 and TrafficAssignment v0.0.2

### PR DESCRIPTION
**Pull request by chkwon**

### CODE REVIEW

**Comment by chkwon** [comment]
@jiahao Yes it was previously called RSP. By the way, I don't see RSP in the url file. Which file should I edit? Thanks for your help!

I mean, this file here 
https://github.com/chkwon/METADATA.jl/blob/pull-request/73a6db17/RobustShortestPath/url
contains 
git://github.com/chkwon/RobustShortestPath.jl.git

**Comment by jiahao** [comment]
I see; this was changed in d4a1155

**Comment by chkwon** [comment]
@jiahao  Great. So is this ready to go online?

**Comment by jiahao** [comment]
Yes, thanks for the reminder

**Pull request merged**
