### PR TITLE
Tag Compat.jl v0.11.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaLang/Compat.jl](https://github.com/JuliaLang/Compat.jl)
Release: [v0.11.0](https://github.com/JuliaLang/Compat.jl/releases/tag/v0.11.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaLang/Compat.jl/builds/190066153)
Diff: [vs v0.10.0](https://github.com/JuliaLang/Compat.jl/compare/8c6b04c747279e1cd9479a14bad32af739f76d3f...8e198e977db5cadd173d9111da2a1fa1013c898c)
`requires` vs v0.10.0: no changes
cc: @TotalVerb

### CODE REVIEW

**Comment by tkelman** [comment]
Actually since the added exports here do break several packages that were locally defining these, we should set upper bounds so those packages hold Compat back until they have tagged a version that won't collide. Didn't think that would happen with Compat, but here it did.

**Comment by TotalVerb** [comment]
What's a quick way to find what registered packages are locally defining `∘`? (Local definitions of `!` probably do not exact and should not matter anyway.)

**Comment by tkelman** [comment]
likely some false alarms in this list, but:
```
tkelman@nanosoldier4:~/Julia/cloneallpackages$ grep -l ∘ --include='*\.jl' -R .
./Cliffords/src/Paulis.jl
./Cliffords/src/Cliffords.jl
./Cliffords/test/testpaulis.jl
./Cliffords/test/perf.jl
./ArgParse/test/argparse_test8.jl
./UnicodeFun/src/symbols.jl
./JuliaParser/src/lexer.jl
./Tokenize/src/token_kinds.jl
./Convex/src/expressions.jl
./CoordinateTransformations/src/perspective.jl
./CoordinateTransformations/src/core.jl
./CoordinateTransformations/src/CoordinateTransformations.jl
./CoordinateTransformations/test/perspective.jl
./CoordinateTransformations/test/core.jl
./CoordinateTransformations/test/coordinatesystems.jl
./CoordinateTransformations/test/affine.jl
./Caesar/examples/rov/LRBE90degrees.jl
./Caesar/examples/animateSonarSim.jl
./Caesar/examples/visualizeDidson.jl
./Caesar/src/ModelVisualizationUtils.jl
./Caesar/src/VisualizationUtils.jl
./Typeclass/test/runtests.jl
./JuliaFEM/test/test_heat.jl
./Geodesy/src/transformations.jl
./Geodesy/src/Geodesy.jl
./Geodesy/test/transformations.jl
./Geodesy/test/datum_transformations.jl
./MLKernels/test/functions/compositefunction.jl
./MLKernels/misc/gettingstarted.jl
./Jewel/src/parse/scope.jl
./Compat/src/Compat.jl
./Compat/test/runtests.jl
./FastTransforms/src/toeplitzhankel.jl
./Measures/test/runtests.jl
./JuLIP/src/pairpotentials.jl
./IntervalConstraintProgramming/src/reverse_mode.jl
```

**Comment by TotalVerb** [comment]
Great, thanks! I'll have a look at these later today.

**Comment by TotalVerb** [comment]
No action is needed for ArgParse, UnicodeFun, JuliaParser, Tokenize, Convex, Caesar, JuliaFEM, Jewel, FastTransforms, Measures, JuLIP, and IntervalConstraintProgramming because they do not define their own compose operator. (Phew! It turns out many packages just use this as a placeholder for some operator in documentation.)

No action is needed for Typeclass because this package is very old and does not depend on Compat.

No action is needed for MLKernels because this package has never depended on Compat.

For the rest, see #7517.

**Pull request merged**
