### PR TITLE
Register + tag AppConf

### PR DESCRIPTION
**Pull request by tmlbl**

### CODE REVIEW

**Comment by tkelman** [comment]
I don't think we support registered packages on gitlab at this time. Can you publish the repository on github?

**Comment by tkelman** [comment]
Oh, it's there - https://github.com/tmlbl/AppConf.jl

Best to change the url to match that.

**Comment by tmlbl** [comment]
My mistake, thought I switched remote before Pkg.register

**Comment by tmlbl** [comment]
Sorry. Should be good now.

**Comment by tkelman** [comment]
Yeah, looks better now. I see you added a require file at https://github.com/tmlbl/AppConf.jl/blob/master/REQUIRE, great. That won't be reflected until the next tag though.

Looks like a quite small package right now, but could potentially grow over time? Any objections to the name from anyone? AppConf seems reasonable to me, pretty understandable what it's for.

**Comment by tmlbl** [comment]
Yes it is a small part of a larger app framework I am working on privately. Since I found it useful for other projects I figured it was worth breaking out to cut my teeth on maintaining a real Julia package. Thank you for your guidance here.

**Pull request merged**
