### PR TITLE
ROC: Receiver Operating Characteristics calculations

### PR DESCRIPTION
**Pull request by davidavdav**
This is a package for computing the data for ROC curves, and also contain plotting routines. 

There is a wealth of information in ROC curves, and ROC analysis can be used to evaluate probabilistic binary classifiers for their ability to produce calibrated probabilistic predictions.  Popularly speaking, if the classifier says it is 90% sure, it should, on average, actually be 90% of the times correct, and not 91% or 89%.  This packages contains several tools: metrics (Cllr, minCllr, EER convex hull) and graphs (Normalized Bayes Error rate, Applied Probability of Error, Log-Likelihood Ratio, Detection Error Trade-off, traditional Receiver Operating Characteristics). 

There are other efforts for ROC packages, as the package documentation acknowledges, but I believe this implementation outperforms the others in working wil very large data sets (~10^7 data points) while being very robust in the very scarce data region, using the ROC convex hull interpretation.  

One can debate about the short name, but I believe ROC is known in many different disciplines as such. 

This packages is my first with fairly complete in-line documentation.  

It is currently compatible with julia 0.3 and 0.4.

### CODE REVIEW

**Comment by tkelman** [comment]
> I believe ROC is known in many different disciplines as such.

I disagree, that doesn't seem like an unambiguous acronym to me, at least not in isolation. Spelling out the name of the package in a longer form would greatly assist in identifying what it's for. `RocCurves` might work though?

**Comment by StefanKarpinski** [comment]
Maybe `ROCCurves`?

**Comment by quinnj** [comment]
+1 to `ROCCurves`

**Comment by davidavdav** [comment]
I would think `ROCAnalysis` would be better, the plotting is a relatively small part of the package.

**Comment by tkelman** [comment]
That could work, but going by a google search for "ROC analysis," every single result on the first page contains "curve," only 2 contain "analysis." Also interesting: https://books.google.com/ngrams/graph?content=roc+curve%2Croc+analysis&case_insensitive=on&year_start=1960&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Croc%20curve%3B%2Cc0%3B%2Cs0%3B%3BROC%20curve%3B%2Cc0%3B%3BROC%20Curve%3B%2Cc0%3B.t4%3B%2Croc%20analysis%3B%2Cc0%3B%2Cs0%3B%3BROC%20analysis%3B%2Cc0%3B%3BROC%20Analysis%3B%2Cc0

**Comment by diegozea** [comment]
I like **ROCAnalysis** +1

**Comment by davidavdav** [comment]
My colleagues in the field also prefer ROCAnalysis, despite the fact that "Curves" may get more gits on google.  

I'll open another PR under this name, and close this one.

**Comment by diegozea** [comment]
You can add the curve word on the description of the package. An example of
curve/plot in the README would be great also ;)

**Comment by davidavdav** [comment]
Yeah, well, I am not experienced in including graphs in a `.md`, but I was thinking of making a jupiter workbook and link it from the README.   I'll have to study that, though---I'm a REPL guy.

**Comment by diegozea** [comment]
You need to have your graph in some place accessible in the web (Drive,
Dropbox, etc...). The code in markdown is:

 `` some text ``

;)

2015-09-16 12:24 GMT-03:00 David van Leeuwen <notifications@github.com>:

> Yeah, well, I am not experienced in including graphs in a .md, but I was
> thinking of making a jupiter workbook and link it from the README. I'll
> have to study that, though---I'm a REPL guy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/METADATA.jl/pull/3384#issuecomment-140775604>
> .
>



-- 
Diego Javier Zea

Departamento de Ciencia y Tecnología
Universidad Nacional de Quilmes
Roque Saenz Pena 182
1876 Bernal
Argentina
Phone:+541143657100 ext 4135

**Comment by diegozea** [comment]
`` some text ``

**Comment by davidavdav** [comment]
Ehm, yes, of course! Just like the badges.   Ah, well, I am working on a jupyter workbook right now.

**Pull request closed without merging**
