### PR TITLE
Tag IntervalWavelets v0.0.3

### PR DESCRIPTION
**Pull request by robertdj**

### CODE REVIEW

**Comment by robertdj** [comment]
I hope I haven't messed the process up by impatiently making another tag & publish: 
https://github.com/JuliaLang/METADATA.jl/compare/metadata-v2...robertdj:pull-request/f75086f7
that contains this commit as well as another.
Should I wait before making a pull request?

**Comment by tkelman** [comment]
It is best to tag one package at a time usually. You have several options:

1. Open a new pull request that does both, and close this one since it'll be included in the new one
2. Make a new branch of your metadata fork and cherry-pick only the new commit that isn't included here for the other package, make a separate PR from that new branch
3. Rebases or similar other git methods of achieving the same result as 2

**Comment by robertdj** [comment]
Sorry about that -- I'll keep this in mind. How about closing this one and skip the other. Then I can also fix the travis/REQUIRE mess you just commented on?

**Comment by tkelman** [comment]
I think this one's fine as is, issues that only need changes in `.travis.yml` aren't visible to users so don't really need re-tagging

**Comment by robertdj** [comment]
Okay. So I can close this one and turn
https://github.com/JuliaLang/METADATA.jl/compare/metadata-v2...robertdj:pull-request/f75086f7
into a pull request for both packages?

**Comment by tkelman** [comment]
Sure, that should work. I assume @tknopp approves of your recent changes in the NFFT package?

**Comment by robertdj** [comment]
We discussed it in an issue, so I would think so:
https://github.com/tknopp/NFFT.jl/issues/15

**Comment by tknopp** [comment]
@tkelman: Yes! @robertdj co-maintains the package, that is mainly feature complete.

**Comment by tkelman** [comment]
great, good to know, thought as much but figured I'd check.

**Comment by robertdj** [comment]
Another practical question: Should I delete this branch once the other pull request is accepted?
https://github.com/JuliaLang/METADATA.jl/pull/5596

**Comment by tkelman** [comment]
You can if you want to clean it up. It's your fork.

**Pull request closed without merging**
