### PR TITLE
Register new package TransferEntropy.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [kahaaga/TransferEntropy.jl](https://github.com/kahaaga/TransferEntropy.jl)
Release: [v0.1.0](https://github.com/kahaaga/TransferEntropy.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/kahaaga/TransferEntropy.jl/builds/450292261)
cc: @kahaaga

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@kahaaga This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by kahaaga** [comment]
The Travis build is successful, but JuliaCIBot fails and no error messages are available. Is there something I need to fix here?

**Comment by andreasnoack** [comment]
There is an error message. It's
```julia
ERROR: LoadError: ArgumentError: Module PerronFrobenius not found in current path.
Run `Pkg.add("PerronFrobenius")` to install the PerronFrobenius package.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:435
 [2] require(::Symbol) at ./loading.jl:405
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/jrun/.julia/v0.6/TransferEntropy/src/TransferEntropy.jl, in expression starting on line 6
```
Please don't add packages in your `.travis.yml` file.

**Comment by kahaaga** [comment]
Ok, thanks! 

Installing the PerronFrobenius package (which was unregistered) in the .travis.yml file was a workaround for things to work on Travis CI until all dependencies got registered on METADATA. 

I now added PerronFrobenius.jl to REQUIRE instead.  The PerronFrobenius package is submitted in #19294, so the tests for this package should pass once #19294 is merged.

**Comment by andreasnoack** [comment]
Great. Please update this PR as described in https://github.com/attobot/attobot once #19294 has been merged.

**Comment by kahaaga** [comment]
I have now updated the PR by updating the release. This is ready to be merged from my side.

**Comment by andreasnoack** [comment]
Great. Small comment: please avoid commenting on PRs where everything is fine. For some details see https://discourse.julialang.org/t/the-current-metadata-release-process/16672.

**Pull request merged**
