### PR TITLE
Tag AWSCore.jl

### PR DESCRIPTION
**Pull request by samoconnor**
Add arn validation and parsing functions: https://github.com/samoconnor/AWSCore.jl/commit/238e44c5721d1b569177d066012229f88a631c24

### CODE REVIEW

**Comment by tkelman** [comment]
doesn't look like `.|>` works on julia 0.5

**Comment by samoconnor** [comment]
ok, thx

**Comment by samoconnor** [comment]
fixed 
https://github.com/samoconnor/AWSCore.jl/commit/df1216674082eeecd2a511599820c924f5c7ca3d

Tag v0.2.2 moved to latest commit.

**Comment by samoconnor** [comment]
thankyou!

**Pull request merged**
