### PR TITLE
Tag PlotlyJS v0.1.2

### PR DESCRIPTION
**Pull request by spencerlyon2**
Adds the `attr` function and fixes a display error in IJulia notebooks caused by require.js

### CODE REVIEW

**Comment by tkelman** [comment]
Some of your tests are failing.

**Comment by spencerlyon2** [comment]
Last I checked it was because the Web stack failed to install.

Everything works for me locally.

// Spencer

**Comment by spencerlyon2** [comment]
Ahh that's why the Linux ones failed, but there is something else for osx. Will resolveand update. Good catch.

**Comment by spencerlyon2** [comment]
Ok I have amended the tests and tags have been updated.

**Pull request merged**
