### PR TITLE
Tag CUDAnative.jl v0.8.10

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGPU/CUDAnative.jl](https://github.com/JuliaGPU/CUDAnative.jl)
Release: [v0.8.10](https://github.com/JuliaGPU/CUDAnative.jl/releases/tag/v0.8.10)
Diff: [vs v0.8.9](https://github.com/JuliaGPU/CUDAnative.jl/compare/93c10a5b2adb9416a4c1a1ec812e0f9b7adf5259...6bc9e8d543bdb73c3fb9325744f2f513415166e4)
`requires` vs v0.8.9: no changes
cc: @maleadt

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by maleadt** [comment]
Take three, after https://github.com/JuliaLang/METADATA.jl/pull/17474 and https://github.com/JuliaLang/METADATA.jl/pull/17894.

**Comment by andreasnoack** [comment]
Is
```julia
ERROR: LoadError: LoadError: UndefVarError: colon not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include at ./sysimg.jl:29 [inlined]
 [6] include(::String) at /home/jrun/CUDAnativelib/.julia/v1.0/CUDAapi/src/CUDAapi.jl:3
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/jrun/CUDAnativelib/.julia/v1.0/CUDAapi/src/compatibility.jl:20
in expression starting at /home/jrun/CUDAnativelib/.julia/v1.0/CUDAapi/src/CUDAapi.jl:9
```
something to be worried about?

**Comment by maleadt** [comment]
Yes, this should have been removed from CUDAapi and is part of the 0.5 release: https://github.com/JuliaGPU/CUDAapi.jl/commit/0574aacf041fbd154e5eaa949398673d063bb84b
How did this error happen?

EDIT: or even https://github.com/JuliaGPU/CUDAapi.jl/commit/cf5e8a7e8c188eb34de01977929c74f7a99efcd5

**Comment by andreasnoack** [comment]
It happened during the CIBot tests. I thought it was in the `CUDAnative` tests but it was actually in the reverse dependency test of `CUDAnativelib` which looks like it hasn't been touched in a while so there is probably nothing to worry about here.

**Pull request merged**
