### PR TITLE
Register PLS [https://github.com/lalvim/PLS.jl.git]

### PR DESCRIPTION
**Pull request by lalvim**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I don't know about the name because the acronym is not well known.

**Comment by lalvim** [comment]
Hi cris. There are packages in https://github.com/JuliaStats, such as NMF.jl, that used this naming convention. PLS is a well know naming for Partial Least Squares regressor. How can we proceed?

**Comment by ChrisRackauckas** [comment]
This isn't my domain so I'll let someone else make the call.

**Comment by aviks** [comment]
We very much prefer packages not to have acronyms. Would you be wiling to change it?

**Comment by lalvim** [comment]
@aviks , maybe PartialFit or PLSFit. 
Both are ok?

**Comment by aviks** [comment]
Either is good, I think.

**Pull request closed without merging**
