### PR TITLE
Bump NLopt, CPLEX, Gurobi

### PR DESCRIPTION
**Pull request by mlubin**
More updates for the MathProgBase transition.
CC @IainNZ @joehuchette @stevengj

### CODE REVIEW

**Comment by IainNZ** [comment]
:+1:

**Comment by mlubin** [comment]
CC @tkelman

**Comment by tkelman** [comment]
fix https://github.com/JuliaLang/METADATA.jl/commit/2e73754fcea4afb113ee496915a689f6b67401d1#commitcomment-14696017 retroactively on the SCS 0.2.0 tag while at it?

**Comment by mlubin** [comment]
Done

**Pull request merged**
