### PR TITLE
Register new package InstantiateFromURL.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [QuantEcon/InstantiateFromURL.jl](https://github.com/QuantEcon/InstantiateFromURL.jl)
Release: [v0.1.0](https://github.com/QuantEcon/InstantiateFromURL.jl/releases/tag/v0.1.0)
cc: @arnavs

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@arnavs This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by arnavs** [comment]
@KristofferC This is the Jupyter thing we talked about (the failure comes from requiring `Pkg`, should I just take that out?)

**Comment by KristofferC** [comment]
Yes, take Pkg and Test out of REQUIRE.

**Comment by arnavs** [comment]
@KristofferC Done.

**Comment by andreasnoack** [comment]
Please avoid commenting on PRs with passing tests since it breaks the automatic merging mechanism.

**Comment by arnavs** [comment]
Got it, thanks.

And cc @jlperla.

**Pull request merged**
