### PR TITLE
Remove Multirate

### PR DESCRIPTION
**Pull request by JayKickliter**
The code base for Multirate as been absorbed by DSP.

### CODE REVIEW

**Comment by tkelman** [comment]
Does anything depend on it? I think the right way to do this is set an upper Julia version bound so it won't be installable by future Julia versions.

**Comment by JayKickliter** [comment]
As far as I can tell, no other packages depend on it. I don't even think anyone has used it besides me.

**Comment by tkelman** [comment]
See https://github.com/JuliaLang/METADATA.jl/issues/347 for some discussion, I'll let the usual suspects of "stewards of metadata" chime in

**Comment by JayKickliter** [comment]
Ok, thanks. I’ll just limit it to a maximum Julia version of 0.3.

**Pull request closed without merging**
