### PR TITLE
Tag StrPack.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [pao/StrPack.jl](https://github.com/pao/StrPack.jl)
Release: [v0.2.0](https://github.com/pao/StrPack.jl/releases/tag/v0.2.0)
Diff: [vs v0.1.0](https://github.com/pao/StrPack.jl/compare/f98eeb3bc1522ae1837841e62429258dc3c8495f...6b8e65a12aca8a5d89d2e4edfbd343bba55c7044)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,2 +1 @@
-julia 0.5
-Compat 0.4.5
+julia 0.6
```
cc: @aviks

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
You can still keep the `@struct` macro

```
julia> @eval macro $(Symbol("struct"))()
       :(print("Hello"))
       end
@struct (macro with 1 method)

julia> @struct
Hello
```

**Comment by aviks** [comment]
Ah, thanks for the trick. fixed.

**Comment by KristofferC** [comment]
Don't you need to update the README and the rest?

**Comment by aviks** [comment]
Yeah, doing that right now. the tests are changed.

**Comment by KristofferC** [comment]
Shouldn't you have retagged this?

**Comment by aviks** [comment]
yeah, probably, but everyone reads the documentation online.

**Pull request merged**
