### PR TITLE
Tag OffsetArrays.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArrays/OffsetArrays.jl](https://github.com/JuliaArrays/OffsetArrays.jl)
Release: [v0.6.0](https://github.com/JuliaArrays/OffsetArrays.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArrays/OffsetArrays.jl/builds/397410318)
Diff: [vs v0.5.0](https://github.com/JuliaArrays/OffsetArrays.jl/compare/a29db304bf9f0b0104619623f543eeccd30cb4ee...64cebbf868b4725d65052f1a69dda95311c7f801)
`requires` vs v0.5.0: no changes
cc: @mbauman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by mbauman** [comment]
We might want to hold off on actually tagging this until we've tried upgrading a few of the dependent packages.  This new release would introduce a bifurcation in its behaviors between Julia 0.6 and 0.7; it's not a pain in the OffsetArrays repo, but perhaps we should get a sense of what that's like to support in the dependents before tagging this.

CC @ararslan, @timholy

**Comment by mbauman** [comment]
That'll be a bit of a challenge but I'll see what I can do.

**Comment by ararslan** [comment]
You can check out the commit prior to your breaking one, create a branch off of that, then create a release based on that branch.

**Comment by mbauman** [comment]
Yes, that's not the difficult part.  The hard part is coping with the changes in `Base` that expect offset axes.  I'm not sure it's possible to do in a coherent manner. :-\

**Comment by ararslan** [comment]
Ah, I see. Is there anything I can help with to get this rolled out as-is then? I'm working on LibPQ, which uses OffsetArrays.

**Comment by mbauman** [comment]
Try it and report back!  Also: what would you think about upper-bounding dependents?

**Comment by mbauman** [comment]
Turns out this is also broken on Julia v0.6.  I'm going to go back to the drawing board for this tag.

**Pull request closed without merging**
