### PR TITLE
Add package ColorSchemes

### PR DESCRIPTION
**Pull request by cormullion**

### CODE REVIEW

**Comment by tkelman** [comment]
Repository name should end in .jl. How does this compare to existing *Color* packages?

**Comment by cormullion** [comment]
>How does this compare to existing *Color* packages?

It's complementary to [ColorBrewer.jl](https://github.com/timothyrenner/ColorBrewer.jl) and [NoveltyColors.jl](https://github.com/randyzwitch/NoveltyColors.jl).

**Comment by cormullion** [comment]
Well, I don't understand the ".jl" problem - it appears to be named correctly everywhere else. Perhaps it's because I did:

   Pkg.register("ColorSchemes")

Never mind.

**Comment by tkelman** [comment]
The `url` file here is missing the .jl. Not sure why.

**Comment by cormullion** [comment]
I suppose I could edit it manually? If not, I could work through the instructions again to see where it went wrong.

**Comment by cormullion** [comment]
@tkelman thanks Tony, that's one of my New Years Resolutions ("contribute to Julia") completed...! :)

**Comment by tkelman** [comment]
Cheers, happy new year :tada:

**Pull request merged**
