### PR TITLE
Tag PoissonRandom.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/PoissonRandom.jl](https://github.com/JuliaDiffEq/PoissonRandom.jl)
Release: [v0.3.0](https://github.com/JuliaDiffEq/PoissonRandom.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/PoissonRandom.jl/builds/414870761)
Diff: [vs v0.2.0](https://github.com/JuliaDiffEq/PoissonRandom.jl/compare/ef7b9fd415ea9d1382d1153b1951fcac1baf5fe3...7f07101f58f6fe9fed87f67daca349230ea630b8)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.3.0/requires
@@ -1 +1 @@
-julia 0.7-beta2
+julia 1.0
```
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Why is this a package and not just contributed to Distributions?

**Comment by ChrisRackauckas** [comment]
We don't want Distributions and its binaries. It breaks our nightlies too much on tests that should be much more lightweight. Someone can take the time to upstream this to Distributions but it's not something that's a priority to me right now.

**Comment by andreasnoack** [comment]
How does it break your tests? Network issues?

**Comment by ChrisRackauckas** [comment]
There are times when Rmath doesn't build.

**Comment by andreasnoack** [comment]
Please be more specific. If this happens regularly it should be fixed. Distributions is a pretty important package. Did you notice this while Rmath was shipped with BinDeps or have you experienced this under BinaryBuilder?

**Comment by ChrisRackauckas** [comment]
This was all awhile ago. I don't know how Distributions is now since I made sure this was isolated. Since it's faster and lighter to keep this I don't have a reason to change it back anyways.

**Comment by andreasnoack** [comment]
I think it is generally a good thing for the community to avoid fragmentation and to report issues.

**Pull request merged**
