### PR TITLE
Add upper bound for MarketData and TimeSeriesResampler at TimeSeries

### PR DESCRIPTION
**Pull request by iblislin**
To fix JuliaCIBot failure at https://github.com/JuliaLang/METADATA.jl/pull/19071
cc @femtotrader

### CODE REVIEW

**Comment by iblislin** [comment]
TimeSeries v0.14.0 contains breaking changes https://github.com/JuliaLang/METADATA.jl/pull/19071
So I set the upper bound to v0.14.0.

**Comment by iblislin** [comment]
Thank @andreasnoack for patient guiding!

**Comment by andreasnoack** [comment]
Shouldn't there have been a bound on version 0.10.0 as well?

**Comment by iblislin** [comment]
@andreasnoack you are right.
(I'm not ware that there is 0.10.0 under `ls` :man_facepalming:

**Pull request merged**
