### PR TITLE
Register new package FinancialToolbox.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rcalxrc08/FinancialToolbox.jl](https://github.com/rcalxrc08/FinancialToolbox.jl)
Release: [v0.1.0](https://github.com/rcalxrc08/FinancialToolbox.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/rcalxrc08/FinancialToolbox.jl/builds/268906342)
cc: @rcalxrc08

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@rcalxrc08 This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
You should not be calling `Pkg.checkout` in your tests here https://github.com/rcalxrc08/FinancialToolbox.jl/blob/fc66102e94af21b5a1bd41dbaee73ccd90b96e41/test/testHyperDualNumbers.jl#L38 - that results in anyone who runs `Pkg.test("FinancialToolbox")` then using the master version of HyperDualNumbers which will update unpredictably and not participate in version resolution. Better to request that the HyperDualNumbers author make a new release.

**Comment by rcalxrc08** [comment]
Ok you are right.
I was waiting for him, i'll wait more time.

**Comment by MikeInnes** [comment]
Will merge this for now – I'm sure you can fix the test issue in an update.

Thanks for the new package! You might consider announcing it on [Julia's forum](https://discourse.julialang.org/).

**Comment by tkelman** [comment]
This will break version resolution of the downstream package for anyone who runs the tests here. Pkg operations should never be done in deps/build.jl, src, or tests. If you need them temporarily, you can do them in your CI yml files.

**Pull request merged**
