### PR TITLE
Tag Interpolations.jl v0.6.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMath/Interpolations.jl](https://github.com/JuliaMath/Interpolations.jl)
Release: [v0.6.2](https://github.com/JuliaMath/Interpolations.jl/releases/tag/v0.6.2)
Diff: [vs v0.6.1](https://github.com/JuliaMath/Interpolations.jl/compare/70e41285473804cc5867c619682b81aeec5ca08e...e7a96c5ac80c06d44104a3cadefdcad9b8bca4fc)
`requires` vs v0.6.1: no changes
cc: @timholy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
The RigidBodyTreeInspector issue on JuliaCIBot looks real -
`MethodError: no method matching zero(::Type{RigidBodyTreeInspector.InterpolatableArray{Array{Float64,1}}})`

**Comment by tkelman** [comment]
Right, it's reverse-dependency CI. There are still some kinks to work out, and we will hopefully be able to make the source code public once we've reviewed that there aren't any sensitive credentials etc in the repo.

**Comment by tkelman** [comment]
> There are still some kinks to work out

Such as: it chose a different set of 5 reverse-dependencies to test the second time, and left some out including the original case where it flagged a problem. I tested RigidBodyTreeInspector against this latest version of Interpolations locally and it worked.

**Comment by timholy** [comment]
One might even consider weighting the choices by the number of non-intersecting dependents that *those* packages have. For example, when testing ColorTypes (24 direct dependents) it would be really nice to test Colors (55 direct dependents).

**Pull request merged**
