### PR TITLE
Bump DataStreams

### PR DESCRIPTION
**Pull request by quinnj**
Note this depends on https://github.com/JuliaLang/METADATA.jl/pull/6352 being merged first. Tested locally on OSX for julia 0.5-rc4/0.4.6.

I also have tags for CSV, SQLite, and Feather ready to push as soon as this is merged to prevent weird transition states.

### CODE REVIEW

**Comment by quinnj** [comment]
Alrighty, proper CategoricalArrays upper bounds in place and travis seems happy.

**Comment by tkelman** [comment]
Since not all past versions of these depend on CategoricalArrays, this won't do what you expect. It will likely downgrade to a past version that doesn't depend on CategoricalArrays to try to upgrade that package.

**Comment by quinnj** [comment]
I don't think I understand. What would be the solution here then? it seems to work fine for me in a few local testing runs I've done (0.4, 0.5, etc.)

**Comment by tkelman** [comment]
upper bounds are only effective when applied to all past tags. otherwise the resolver can downgrade your package to something very old instead of holding back your dependency

**Comment by quinnj** [comment]
So I should add fake dependencies on CatArrays to all past versions of DataStreams/Feather? That's not what I did last time (with CSV/SQLite and upper bounds on DataStreams), and that seemed to work out fine.

I have all the other tags ready to go, so I'd rather just make the bump and then re-tag the rest and then everyone can safely upgrade to the current releases that all support both 0.4/0.5.

**Comment by tkelman** [comment]
Fake dependencies would get the resolver to do the right thing. Which was the last time, did you merge that before I looked at it or did I check it first?

Simple tests won't show potential strange resolution solutions.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/6291#issuecomment-245765717 had a different solution because the julia minimums were different. here they're all 0.4, right?

**Comment by quinnj** [comment]
You checked and merged. https://github.com/JuliaLang/METADATA.jl/pull/6291

**Comment by quinnj** [comment]
Why does that make a difference?

**Comment by tkelman** [comment]
julia upper bounds remove those versions as feasible solutions the resolver can return. trying to add fake dependencies when the new one doesn't support the same set of julia versions would make that version infeasible on the old julia version it formerly supported.

**Comment by quinnj** [comment]
Ok, so I'll add fake dependencies to all past versions.

**Comment by quinnj** [comment]
Ok, should be good to go here.

**Pull request merged**
