### PR TITLE
Register CBOR.jl

### PR DESCRIPTION
**Pull request by saurvs**

### CODE REVIEW

**Comment by tkelman** [comment]
why are you squashing the release into a single commit instead of tagging a specific commit fron master? seems unusual, and it will make tracking incremental changes between releases more complicated.

**Comment by saurvs** [comment]
Hmm, so `Pkg.generate` created a new git repo. I then added the files from the most recent commit from my local copy of CBOR.jl that I've been working on, into the new repo, and then committed it as "Version 0.0.1" and tagged that. Should I drag `.git` from my working repo into the `.julia/v0.4/CBOR` as well and tag it then?

**Comment by tkelman** [comment]
Did your "working repo" start from Pkg.generate? I guess you could try with copying the .git,
or making a symbolic link, or doing Pkg.clone(localpath).

**Comment by saurvs** [comment]
No I didn't. I read the package development section after I finished the coding.

**Pull request closed without merging**
