### PR TITLE
Register RandomFerns

### PR DESCRIPTION
**Pull request by rened**

### CODE REVIEW

**Comment by rened** [comment]
thanks, good point - done

**Comment by milktrader** [comment]
Ok, thanks! Working on expanding the package docs to explain this better.

**Comment by tkelman** [comment]
Oh, and if you use `Pkg.publish`, then your git tags will get pushed to the package repository too, so users can easily see them under github's releases tab.

**Comment by rened** [comment]
Thanks, will to that in the future. Old habit of doing things manually.


Am 22.06.2015 um 01:32 schrieb Tony Kelman <notifications@github.com>:

**Comment by tkelman** [comment]
`Pkg.publish` used to be annoyingly slow, it isn't any more

**Pull request merged**
