### PR TITLE
Register new package Tqdm.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [cloud-oak/Tqdm.jl](https://github.com/cloud-oak/Tqdm.jl)
Release: [v0.1.1](https://github.com/cloud-oak/Tqdm.jl/releases/tag/v0.1.1)
cc: @cloud-oak

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@cloud-oak This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Although it is usual to keep the same name when wrapping another package, this package name seems so completely undiscoverable that maybe a different name would be better?

**Comment by xgdgsc** [comment]
This name is quite discoverable for python users switching to julia for performance. This is how I searched and found this package. Consider the popularity of https://github.com/noamraph/tqdm .

**Comment by dpsanders** [comment]
That does not help people who are not coming from python to discover the package and what it is useful for.

**Comment by tpapp** [comment]
> This name is quite discoverable for python users switching to julia for performance.

Packages are potentially used by the whole Julia community. It is better to use names which are easy to understand and discover for everyone. 

I can't find this section in the current manual, but see
https://docs.julialang.org/en/v0.6/manual/packages/#Guidelines-for-naming-a-package-1

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
