### PR TITLE
Register new package Notifier.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [goropikari/Notifier.jl](https://github.com/goropikari/Notifier.jl)
Release: [v0.0.1](https://github.com/goropikari/Notifier.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/goropikari/Notifier.jl/builds/344446947)
cc: @goropikari

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@goropikari This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Would it be possible to enable Travis testing on Linux?

**Comment by goropikari** [comment]
This package uses GUI. So the test on Linux always fails.

**Comment by goropikari** [comment]
When we run this package's function on Linux without gui, we get the  following error.
```julia
julia> using Notifier
julia> notify("foo")
(notify-send:158740): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
```
Is there any way to avoid above error?

**Comment by goropikari** [comment]
Sorry. I misunderstand travis testing. I will fix the test on Linux.

**Comment by goropikari** [comment]
I added the test on Linux.

**Pull request merged**
