### PR TITLE
Tag Images.jl v0.11.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaImages/Images.jl](https://github.com/JuliaImages/Images.jl)
Release: [v0.11.0](https://github.com/JuliaImages/Images.jl/releases/tag/v0.11.0)
Diff: [vs v0.10.1](https://github.com/JuliaImages/Images.jl/compare/aa04e63487d46f0e41041e4ca65365ea3aa240ba...2f78e6b9674b39bcad16d7711ac3e3071fe0d755)
`requires` vs v0.10.1: 
```diff
--- 0.10.1/requires
+++ 0.11.0/requires
@@ -16,3 +16,4 @@
 FileIO
 Compat 0.19
 StatsBase   # for histrange
+Requires
```
cc: @timholy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
planning on re-tagging this as 0.6-only?

**Comment by timholy** [comment]
Yes. Don't merge.

**Comment by tkelman** [comment]
Looks like Pyramids.jl needs an upper bound

**Comment by timholy** [comment]
#10261

**Comment by tkelman** [comment]
Downside of JuliaCIBot only doing 5 (random) reverse deps at a time, it isn't going to catch everything. Looks like FaceDatasets needs the same, I can open a PR for that. (cc @dfdx)

**Comment by dfdx** [comment]
Thanks for notifying me. Any recommendations how to migrate to newer versions of Images.jl?

**Comment by timholy** [comment]
Just check out a current version of Images. There are *copious* deprecation warnings that should tell you how to migrate your code. See also:
- https://github.com/JuliaImages/Images.jl/blob/master/NEWS.md
- https://github.com/JuliaImages/Images.jl/blob/master/upgrading_tips.md
- https://github.com/JuliaMath/FixedPointNumbers.jl/blob/master/contrib/deprecation_UFixed.sh (if you're still using old names for fixed-point types).
- http://juliaimages.github.io/latest/

Is that enough? :smile:

**Comment by timholy** [comment]
> Downside of JuliaCIBot only doing 5 (random) reverse deps at a time, it isn't going to catch everything. 

Yep. Need more PkgDev tools, silly to have to do this stuff manually.

**Comment by aviks** [comment]
We should increase the limit in JuliaCI bot... it was set low for the initial rollout.

**Comment by tkelman** [comment]
Well PkgEval will probably catch more in a day or so.

**Comment by timholy** [comment]
True.

BTW, @dfdx, I should have clarified that "current version of Images" should mean currently *tagged* version of Images (not master). The change occurred in release 0.6, the reason you're getting this message now is that the deprecations are being removed. So use something in the 0.6-0.10 range.

**Comment by dfdx** [comment]
Got it! Thanks for a detailed migration plan!

**Comment by tkelman** [comment]
At least out of the packages that had been passing tests on 0.6 on pkgeval (about 60% of them), looks like the only other failure from this was ImageProjectiveGeometry, bounds added in #10282

**Pull request merged**
