### PR TITLE
Tag Playground.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rofinn/Playground.jl](https://github.com/rofinn/Playground.jl)
Release: [v0.3.0](https://github.com/rofinn/Playground.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/rofinn/Playground.jl/builds/256697963)
Diff: [vs v0.2.0](https://github.com/rofinn/Playground.jl/compare/d4ea10dccdeefeb1572cddb6acac25734cb1b114...c08a8fbf1e7477a9362b8c7270ceeee354cb984c)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.3.0/requires
@@ -1,5 +1,7 @@
-julia 0.4
+julia 0.5
 ArgParse
 YAML
+FilePaths 0.2.0
 Mocking
-Compat
+Compat 0.17.0
+Memento
```
cc: @rofinn

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by rofinn** [comment]
The JuliaCIBot log messages aren't very helpful.

**Comment by tkelman** [comment]
Me either.

**Comment by rofinn** [comment]
Thanks. Are there any existing methods for running the bot locally... even just instructions I can use to setup a VM or docker image?

**Comment by tkelman** [comment]
Ubuntu I assume, but I'll have to double check that. The repo with the code that runs it isn't public yet but hopefully can be soon.

PkgEval wasn't very happy with this either: https://github.com/JuliaCI/pkg.julialang.org/blob/b6f5e76f1d5072a5726c2296073d53c11695914a/logs/Playground_0.6.log

**Comment by rofinn** [comment]
Oh, I see. Playground has slightly more complicated build steps (e.g., setting a `PLAYGROUND_INSTALL` environment variable if you'd like to install a new config and executable to `~/.playground/`). I suppose I should double check that the tests don't depend on the installation process.

**Comment by tkelman** [comment]
Yeah would be nice if there was some dumb default not-totally-broken thing it could do on a didn't-RTFM `Pkg.add("Playground"); Pkg.test("Playground")`

**Comment by rofinn** [comment]
> dumb default not-totally-broken thing it could do on a didn't-RTFM

Lol

**Pull request merged**
