### PR TITLE
Tag Rsvg v0.0.2

### PR DESCRIPTION
**Pull request by lobingera**

### CODE REVIEW

**Comment by tkelman** [comment]
You should add `@windows WinRPM` to your `REQUIRE` since it's used in your build.jl script

**Comment by lobingera** [comment]
@tkelman Can i add to 0.0.2 or do i need to close this and re-start?

**Comment by tkelman** [comment]
It's okay to just modify the requires file of the existing tag in this branch of your metadata fork.

**Comment by lobingera** [comment]
I'll restart as i plan also changes on testing.

**Pull request closed without merging**
