### PR TITLE
Bump DataStreams and cap existing DataStream packages

### PR DESCRIPTION
**Pull request by quinnj**
CC @tkelman: I think I have the upper-bounds correct here, but I'd appreciate a look; essentially, the current tagged versions of CSV/SQLite/Feather should only ever be allowed to use v0.0.12 of DataStreams. New tags for those packages will follow this merge.

### CODE REVIEW

**Comment by tkelman** [comment]
upper bounds will not be effective unless you apply them to all past tags of the packages in question

**Comment by tkelman** [comment]
Are there early tags of Feather or SQlite that didn't depend on DataStreams? The resolver may choose to downgrade those in order to get the latest DataStreams. There are a few different things we could do about that.

**Comment by quinnj** [comment]
Just one other older version of SQLite, all versions that had DataStreams as a dependency should now be capped.

**Comment by tkelman** [comment]
the issue is the old versions that didn't have DataStreams as a dependency

**Comment by quinnj** [comment]
ah, what's the best solution then? not worry about capping?

**Comment by tkelman** [comment]
can add an artificial datastreams dependency on the older versions. though for the versions that support older julia versions than datastreams' minimum, better to upper bound julia

**Comment by quinnj** [comment]
Alright, I put julia upper bounds on all the old SQLite verions.

**Pull request merged**
