### PR TITLE
Bump CSV version

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by tkelman** [comment]
This fails its tests on Travis, something is missing a dependency. Can you please check that your packages at least pass tests before submitting a tag?

**Comment by quinnj** [comment]
I definitely check that things pass before submitting.

**Comment by tkelman** [comment]
https://travis-ci.org/JuliaDB/CSV.jl/builds/139109189 ?

**Comment by quinnj** [comment]
Travis is now happy.

**Pull request merged**
