### PR TITLE
Tag DocumentFormat.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ZacLN/DocumentFormat.jl](https://github.com/ZacLN/DocumentFormat.jl)
Release: [v0.2.1](https://github.com/ZacLN/DocumentFormat.jl/releases/tag/v0.2.1)
Travis: [Travis Build Status](https://travis-ci.org/ZacLN/DocumentFormat.jl/builds/474565744)
Diff: [vs v0.2.0](https://github.com/ZacLN/DocumentFormat.jl/compare/52c6853746c5b40209ed71089d65ca8bc7bc1c8e...248bc75a0aaff70ed696c85222a92812fe7340a5)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.2.1/requires
@@ -1,3 +1,3 @@
 julia 0.7
-CSTParser 0.4.1 0.5.0
+CSTParser 0.5.0
 Tokenize 0.5.2
```
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by davidanthoff** [comment]
The failure here is that we declare that it works on julia 0.7, but it doesn't.

We're about to fix that on master. BUT, could we still merge this PR here? Version 0.2.1 is what shipped with the VS Code extension and we can't take that back, and it would be good if the tagged version always matches what we shipped via the VS Code marketplace.

I think one of the admins here would have to do that, though?

**Comment by davidanthoff** [comment]
Bump, @andreasnoack is that something you could do?

**Comment by andreasnoack** [comment]
Unfortunately, I don't think we can do that. You'd have to fix the release. Otherwise, the METADATA tests will keep failing because of this package.

**Comment by davidanthoff** [comment]
Ok, then this tag will just not be in METADATA.

**Pull request closed without merging**
