### PR TITLE
Tag AmplNLReader.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaSmoothOptimizers/AmplNLReader.jl](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl)
Release: [v0.2.1](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/releases/tag/v0.2.1)
Diff: [vs v0.2.0](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/compare/5af4c4d1550ec496f02bb09e25b3ee74468537a3...84f5d31794b3a4d4fcb70b3b1f7d0e87112d2179)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.2.1/requires
@@ -1,4 +1,3 @@
-julia 0.6 0.7
+julia 0.7 2.0
 BinDeps
-@osx Homebrew 0.4.0
-NLPModels 0.0.1 0.5.0
+NLPModels 0.5.0
```
cc: @dpo

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dpo** [comment]
I updated the release tag, but it's not reflected here. How does one change the tag and update the PR?

**Comment by dpo** [comment]
Please close this PR.

**Comment by abelsiqueira** [comment]
> I updated the release tag, but it's not reflected here. How does one change the tag and update the PR?

You remove the release and the tag, then re-release.

**Comment by andreasnoack** [comment]
https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by dpo** [comment]
Thank you, done. This PR is no longer needed.

**Pull request closed without merging**
