### PR TITLE
Tag MixedModels v0.4.5

### PR DESCRIPTION
**Pull request by dmbates**

### CODE REVIEW

**Comment by tkelman** [comment]
don't forget to push the git tag so it shows up at https://github.com/dmbates/MixedModels.jl/releases

**Comment by dmbates** [comment]
@tkelman How would I go about pushing the git tag? 

Sorry to need to ask but I still end up in hand-to-hand combat with git every time I try to do release a new version of a package.  `Pkg.tag` and `Pkg.release` only work for me about 10% of the time.  On the other occasions I end up wasting several hours trying to extricate myself from a git mess.

**Comment by dmbates** [comment]
I meant `Pkg.publish()`, not `Pkg.release()`.

**Comment by nalimilan** [comment]
Try `git push origin v0.4.5`. But AFAICK you can also create a release on GitHub, and it will create the tag automatically (though make sure it points to the same commit).

**Comment by dmbates** [comment]
```
$ git push origin v0.4.5
error: src refspec v0.4.5 does not match any.
error: failed to push some refs to 'git@github.com:dmbates/MixedModels.jl.git'
```

**Comment by dmbates** [comment]
It is possible that I tagged the release on my laptop.  Unfortunately in the process of upgrading to Ubuntu 16.04 this weekend I borked my laptop and lost all the information on it.  It wasn't a great weekend.

**Comment by nalimilan** [comment]
Hmm, what's even more annoying is that I can't find commit 6eda39ccd39126f4b813b8f83178708c981179ce in the git log. Maybe you hadn't pushed this commit from your laptop before it broke? In that case, tag a new release on GitHub, and then edit manually the commit SHA1 at `MixedModels/versions/0.4.5/sha1`.

**Comment by dmbates** [comment]
Thanks for the suggestion, @nalimilan, but I am under a deadline and don't have my laptop anymore so I simply don't have the time to wrestle with git on this.

@tkelman If you want to remove MixedModels from the METADATA repository then go ahead.

**Comment by tkelman** [comment]
We should probably just revert this tag for now since the commit sha does not look like it was pushed to github.

**Comment by nalimilan** [comment]
@dmbates Would it be OK if to tag the latest commit that appears on GitHub as 0.4.5? I can do that for you if you want.

**Comment by dmbates** [comment]
@tkelman Reverting the tag is okay by me.

Is there any way I can reset my local copy of the package's repository and my copy of  the METADATA repository so I don't get tied up in knots when trying to release a new version of the package?  I have some changes in the MixedModels package that I want to commit but after that I am willing to remove the package locally and add the package again to get a clean copy.  I'm even willing to remove my package directory entirely and add all the packages back, if that will clean up the METADATA.

Unfortunately my experience is that once I make a mistake git never forgets it and the package is screwed up forever.  It is true for this package and for the FLAC package.

If necessary I will just avoid registering packages and just ask people to use Pkg.clone()

**Comment by dmbates** [comment]
@nalimilan I'll wait to see what @tkelman says.

As I said I am under a deadline so, if necessary, I will just remove all my packages from METADATA and worry about trying to register the packages again later.

**Comment by tkelman** [comment]
Removing packages entirely is not okay, that would cause major downstream problems with anyone using your packages. I'm not on a proper keyboard right now, but you can always save your local state to a backup branch and replace your metadata-v2 branch with the upstream version.

**Comment by dmbates** [comment]
@nalimilan I was going to say that I would add you as a collaborator on the MixedModels repository then discovered that I had already done so.  Please feel free to tag v0.4.5 as you described,

**Comment by nalimilan** [comment]
Yes, that's why I proposed to do it. I've just tagged a new release pointing to the latest commit. PR https://github.com/JuliaLang/METADATA.jl/pull/5037 updates the git SHA1.

Regarding the ways of fixing messed up repositories, you can always move the directories out of the way and start again with fresh clones. It's always possible to work from the original directories, even after moving them, so no changes should be lost.

**Comment by nalimilan** [comment]
Wait, the situation was totally confusing. MixedModels 0.4.5 was already tagged in my PR https://github.com/JuliaLang/METADATA.jl/pull/4701, a long time ago. The commit in the present PR is dated from March 1st, i.e. one day before my PR. And indeed, it points to a commit from March 1st (which is why I missed it). So the current state is correct. I've now tagged 0.4.5 to point to that commit instead of current git master.

So, @dmbates, you can just wait until you have more time to make a new release. Or if you really want to get some recent fixes published, I can mark 0.4.6 for you.

**Comment by dmbates** [comment]
Thanks, @nalimilan.  I am working on a clean copy of `MixedModels` and `METADATA` now so I hope I will be able to tag and publish myself.

Sorry for all the drama.

**Pull request merged**
