### PR TITLE
Tag DeferredFutures.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [invenia/DeferredFutures.jl](https://github.com/invenia/DeferredFutures.jl)
Release: [v0.5.0](https://github.com/invenia/DeferredFutures.jl/releases/tag/v0.5.0)
Diff: [vs v0.4.0](https://github.com/invenia/DeferredFutures.jl/compare/d2bbd45ffe59191abbc3ded5fdc74c0f2ea80c1d...881f6358acc1a86ac6677b6260bf361829589d2c)
`requires` vs v0.4.0: 
```diff
--- 0.4.0/requires
+++ 0.5.0/requires
@@ -1,2 +1,3 @@
 julia 0.5
 AutoHashEquals
+Compat 0.17.0
```
cc: @rofinn

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
Hm, looks like JuliaCIBot is freezing on Dispatcher's tests. There's no great way of getting notified about this at the moment, but PkgEval has also been freezing on Dispatcher's tests ever since June 30th, which is when DeferredFutures 0.4.0 was tagged. https://github.com/JuliaCI/pkg.julialang.org/blob/gh-pages/logs/Dispatcher_0.5.log

cc @iamed2

**Comment by iamed2** [comment]
@tkelman Where is the freeze? I see it end with:

```
Test Summary: | Pass  Total
  Dispatcher  |  276    276
INFO: Dispatcher tests passed
INFO: No packages to install, update or remove

>>> End of log
```

**Comment by tkelman** [comment]
See the commit date, and the dates here: https://pkg.julialang.org/detail/Dispatcher.html - it's supposed to run daily

**Comment by iamed2** [comment]
It would be helpful to see the logs up until it freezes; do you have any of those?

**Comment by tkelman** [comment]
It looks like it may have been the problem that this fixes, it was only freezing on the runs against the existing version 0.4.0 of DeferredFutures. https://gist.github.com/ff06ef43575ee5ea525adfaa0df75f5b

**Pull request merged**
