### PR TITLE
Tag OhMyREPL.jl v0.2.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [KristofferC/OhMyREPL.jl](https://github.com/KristofferC/OhMyREPL.jl)
Release: [v0.2.3](https://github.com/KristofferC/OhMyREPL.jl/releases/tag/v0.2.3)
Travis: [Travis Build Status](https://travis-ci.org/KristofferC/OhMyREPL.jl/builds/254102266)
Diff: [vs v0.2.2](https://github.com/KristofferC/OhMyREPL.jl/compare/502a07d2d41029117dee39836b72ba55b3a58195...52aa257967531612213a229a0958e033a017cdf0)
`requires` vs v0.2.2: no changes
cc: @KristofferC

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
This looks broken on appveyor https://ci.appveyor.com/project/KristofferC/ohmyrepl-jl/build/1.0.91, seems it was passing at the last release?

**Comment by KristofferC** [comment]
Perhaps the new terminal tests should only be run on linux (at least PTY only seems defined there)? @keno

**Comment by Keno** [comment]
Oh yeah, sry about that. Should be `@unix_only`, since windows doesn't really have a pty (libuv emulates it there).

**Comment by KristofferC** [comment]
Ok, I'll fix it.

**Pull request merged**
