### PR TITLE
Tag StatisticalRethinking.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [StanJulia/StatisticalRethinking.jl](https://github.com/StanJulia/StatisticalRethinking.jl)
Release: [v0.2.0](https://github.com/StanJulia/StatisticalRethinking.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/StanJulia/StatisticalRethinking.jl/builds/467532304)
Diff: [vs v0.1.0](https://github.com/StanJulia/StatisticalRethinking.jl/compare/01226f8472224a301a737041ceacfa6d8b67771a...72a12281c5413085226797708080684ff87c14bf)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -11,3 +11,9 @@
 CSV
 Turing
 Optim
+JLD
+CmdStan
+StanMCMCChain
+Mamba
+Distributed
+Gadfly
```
cc: @goedman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
`Distributed` is a stdlib so shouldn't go into the REQUIRE file.

**Comment by goedman** [comment]
Thanks Andreas. I had removed all dependencies on Distributed in the 2nd attempt. But the real problem might turn out to be that using --project=docs with Literate required pretty much all dependencies in this case. Or maybe we just can't use Literate, CmdStan, Turing & Mamba in a single package yet.

**Comment by andreasnoack** [comment]
Why isn't `Literate` in the REQUIRE file?

**Comment by goedman** [comment]
Thanks again Andreas, clearly needed!

**Pull request merged**
