### PR TITLE
Register new package LibSpatialIndex.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGeo/LibSpatialIndex.jl](https://github.com/JuliaGeo/LibSpatialIndex.jl)
Release: [v0.1.0](https://github.com/JuliaGeo/LibSpatialIndex.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGeo/LibSpatialIndex.jl/builds/465665025)
cc: @yeesian

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@yeesian This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please add to the readme something about the gosl of the package. What is "lib" for in the package name?

**Comment by yeesian** [comment]
> If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

In response to 

>> Please add to the readme something about the gosl of the package. What is "lib" for in the package name?

I am not making these changes. The "Lib" in the package name is to indicate this is a wrapper around the C library [libspatialindex](https://github.com/libspatialindex/libspatialindex). I imagine a name like `SpatialIndex.jl` might be better suited for a pure julia implementation. (See for e.g. `SpatialIndexing.jl` in [this discourse post](https://discourse.julialang.org/t/implementations-of-spatial-indices/7638/8).)

**Comment by dpsanders** [comment]
I see - that wasn't clear to me from the docs. (The purpose of the package wasn't clear to me actually).

**Comment by yeesian** [comment]
It can definitely be improved: feel free to open an issue or submit a PR for it.

**Comment by yeesian** [comment]
(Attobot did say feedback is optional.) I'm okay with bikeshedding the name of the package, but let's not confuse the goals of a METADATA PR with the push for registered packages to be more polished.

**Comment by andreasnoack** [comment]
>  let's not confuse the goals of a METADATA PR with the push for registered packages to be more polished.

The delay here is because you didn't reply to the comment. The comment was to help you improve the name and was based on the available information in the repo. It could probably have been avoided if it had been clear from the README that the package was a wrapper around libspatialindex. I don't consider that polish.

**Comment by yeesian** [comment]
The delay here was because of an error which got fixed in https://github.com/JuliaGeo/LibSpatialIndex.jl/pull/5.

> The comment was to help you improve the name and was based on the available information in the repo. It could probably have been avoided if it had been clear from the README that the package was a wrapper around libspatialindex.

Ah okay, I misunderstood the situation, thanks for the clarification. Again, I agree that the README should be made clearer. Just wanted to check that it is not a requirement for a METADATA PR.

**Pull request merged**
