### PR TITLE
Pull request/7fb53b84

### PR DESCRIPTION
**Pull request by Stivanification**
This is the third pull request for the same package. Sorry if I'm spamming, I dont know how to do it better.

### CODE REVIEW

**Comment by tkelman** [comment]
Would your tests pass if you enabled travis CI? You can push additional commits to the same branch and they will show up in the same PR rather than creating new PR's. But if the only thing you change is travis related then it might not be necessary to retag.

**Comment by Stivanification** [comment]
Well I'm getting a green checkmark here saying "All checks have passed" and the details say "The Travis CI build passed" so I figured that means that the Travis build works out fine, is there anything else I should do?

**Comment by tkelman** [comment]
Travis CI runs per repository. This is METADATA's tests, not your package's tests. I'm suggesting you enable Travis CI for your package repository.

**Comment by Stivanification** [comment]
I have enabled travis and the package passes the tests. [Travis build status](https://travis-ci.org/Stivanification/DriftDiffusionPoissonSystems.jl)

**Pull request merged**
