### PR TITLE
Tag NIDAQ v0.2.0 [https://github.com/JaneliaSciComp/NIDAQ.jl]

### PR DESCRIPTION
**Pull request by bjarthur**
* updates NIDAQ.jl to julia v0.5
* adds support for NIDAQmx 16.0
* users must no longer specify number of samples to read
* adds more tests and examples

### CODE REVIEW

**Comment by bjarthur** [comment]
can someone give me a clue as to why the checks are failing?  thanks.

**Comment by bjarthur** [comment]
ahah, my bad.  works now.

**Comment by tkelman** [comment]
Does the NI license allow redistributing the headers?

**Comment by bjarthur** [comment]
doesn't sound like it.  good catch.  removed in the latest commit.  thanks.

"Under the copyright laws, this publication may not be reproduced or transmitted in any form, electronic or mechanical, including photocopying, recording, storing in an information retrieval system, or translating, in whole or in part, without the prior written consent of National Instruments Corporation."

**Comment by tkelman** [comment]
I wonder about that "translating" part...

**Comment by aviks** [comment]
What's the consensus on this?

**Comment by bjarthur** [comment]
NI is still thinking about it.  they're aware of [PyDAQmx](https://pythonhosted.org/PyDAQmx/) and have no problems with it.  they even recommend it to customers.  but i have not received official word that they approve of these julia wrappers.

**Comment by ViralBShah** [comment]
If we are following what PyDAQmx does, can we note it in the README, and base our stuff off that package? We can always remove this if an issue is raised in the future.

**Comment by bjarthur** [comment]
PyDAQmx link added to README.  https://github.com/JaneliaSciComp/NIDAQ.jl/commit/5c69df8e90b853229061a04285ae645434ee026b

**Pull request merged**
