### PR TITLE
Tag Diversity.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [richardreeve/Diversity.jl](https://github.com/richardreeve/Diversity.jl)
Release: [v0.4.0](https://github.com/richardreeve/Diversity.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/richardreeve/Diversity.jl/builds/319682066)
Diff: [vs v0.3.1](https://github.com/richardreeve/Diversity.jl/compare/f0a356e135055b008cb6ffaf978997f1d471511c...8ccd5c140ec4c782fb916731d7764836e4958a80)
`requires` vs v0.3.1: 
```diff
--- 0.3.1/requires
+++ 0.4.0/requires
@@ -1,4 +1,3 @@
-julia 0.5
-Compat 0.18.0
-DataFrames 0.9.0 0.11.0
-
+julia 0.6
+DataFrames 0.9.0
+Phylo 0.2.0
```
cc: @richardreeve

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by richardreeve** [comment]
I don't know what the JuliaCIBot is doing, but it fails on my tests for this package when it tries to install R for cross-validation, whereas the [package](https://github.com/richardreeve/Diversity.jl) tests succeed on [MacOS, linux](https://travis-ci.org/richardreeve/Diversity.jl?branch=master) and [Windows](https://ci.appveyor.com/project/richardreeve/diversity-jl/branch/master) for Julia v0.6. I'll happily disable the R tests for JuliaCIBot if someone can tell me how to do it? Or can you just ignore the CI failure since it's wrong?

PS @aviks - I hope you're the right person to ping about this at the moment?

**Comment by aviks** [comment]
OK, so,, is  R is only needed for the tests?  How does the package  decide to install  it? We'll take a look as to why cibot does not like this.

**Comment by aviks** [comment]
Cc @nkottary

**Comment by richardreeve** [comment]
Yes, R is only used for the tests - we do some cross-validation against a package written by our group on CRAN. The [.travis.yml](https://github.com/richardreeve/Diversity.jl/blob/master/.travis.yml) file downloads R, but looking at the CI log, the problem seems to crop up when it fails to install some necessary R packages... I don't know why that would be different between the package's own checks (which pass) and the CI checks.

**Pull request merged**
