### PR TITLE
Tag NLsolve.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/NLsolve.jl](https://github.com/JuliaNLSolvers/NLsolve.jl)
Release: [v1.0.0](https://github.com/JuliaNLSolvers/NLsolve.jl/releases/tag/v1.0.0)
Diff: [vs v0.14.1](https://github.com/JuliaNLSolvers/NLsolve.jl/compare/d5761332fdbb65c01c5c6c054d1a27a24f18df05...deed60a6bb655fb73e7b29a4c3759c696fa8827d)
`requires` vs v0.14.1: no changes
cc: @pkofod

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by pkofod** [comment]
did you reset it because of complementarity? Isn't this once again because NLsolve is upper bounded in METADATA, but it checks out master of NLsolve when running Complementarity?

**Comment by ChrisRackauckas** [comment]
It won't be upper bounded anymore though. Did you PR an upper bound to their repo?

**Comment by pkofod** [comment]
This is a pr for nlsolve, not complementarity, why should the bounds change ?

**Comment by pkofod** [comment]
But yes I did, it just hasn't been responded to yet

**Comment by ChrisRackauckas** [comment]
Oh wait, yes. I confused myself.

**Pull request merged**
