### PR TITLE
METADATA Test: Success

### PR DESCRIPTION
**Pull request by omus**
Testing changes in #8548

### CODE REVIEW

**Comment by tkelman** [comment]
This should have failed due to the minimum Julia version being too low, but it's in the grandfathered list. Different package maybe.

**Comment by omus** [comment]
@tkelman you want me to test with another package?

**Comment by tkelman** [comment]
yeah, which error path were you trying to trigger here?

**Comment by omus** [comment]
I was actually trying to validate that checks could still pass.

**Pull request closed without merging**
