### PR TITLE
Register new package HomotopyContinuation.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaHomotopyContinuation/HomotopyContinuation.jl](https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl)
Release: [v0.1.0](https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl/releases/tag/v0.1.0)
cc: @saschatimme

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@saschatimme This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by saschatimme** [comment]
This depends on the new [registered package `Homotopies.jl`](https://github.com/JuliaLang/METADATA.jl/pull/12125).

**Comment by saschatimme** [comment]
We just found some bug, I will update the PR if it is fixed. cc @PB12345

**Comment by saschatimme** [comment]
This depends on #12125 .

**Comment by saschatimme** [comment]
I do not really understand the CI failure. I deleted the old v0.1.0 tag and created a new one. Did this mess something up? Should I just publish version 0.1.1 instead?

**Comment by saschatimme** [comment]
The CI Bot seems to fail because of Julia 0.6.0, the repository travis-ci uses 0.6.1. Shall I update the require file to reflect that or is it fine anyways? (The problem seems only to be type instability)

**Comment by aviks** [comment]
I see you just changed your REQUIRE file. I'd suggest re-tagging with that, since your code does not seem work on 0.6.0. 

In general, I'd suggest not having any code that depends on type inference. However, only you will be able to judge if the current behaviour makes sense in your case.

**Comment by saschatimme** [comment]
The JuliaCIBot still fails since its julia version is fixed at 0.6.0.
Unfortunately it is currently not avoidable to rely on type inference, but everything seems to be stable under 0.6.1. But I will keep this in mind for future version.
But I hope this can now get merged and sorry for the troubles.

**Comment by aviks** [comment]
OK. Note that type inference is not guaranteed to be stable, and thus you're signing up for testing this on `v0.6.2` when it come out.

**Pull request merged**
