### PR TITLE
Register Polyglot: v0.0.1

### PR DESCRIPTION
**Pull request by wavexx**
See #2642 for old request.

- Renamed package from "Bond" to "Polyglot".
- "experimental" nature toned down (package is fully functional)
- Update prefix to r* (for generic "remote"), resulting in reval, rcall, etc.
- Renamed make_bond to bond!
- Better docs.

### CODE REVIEW

**Comment by IainNZ** [comment]
Neat!

**Comment by milktrader** [comment]
:+1:

**Comment by wavexx** [comment]
What do you think if I did an announce into julia-users?
I'm looking for feedback.

**Comment by milktrader** [comment]
Either that or julia-dev (but not both). The reason for julia-dev is maybe toss around the idea of the package being central to other-language packages.

**Pull request merged**
