### PR TITLE
Tag MarketData v0.3.5

### PR DESCRIPTION
**Pull request by milktrader**
Adding DELL time series

### CODE REVIEW

**Comment by tkelman** [comment]
looks like you've got a test failure? https://travis-ci.org/JuliaQuant/MarketData.jl/builds/116163995

**Comment by milktrader** [comment]
Fixed the test (it was an OBO error on object length). What's the plan? Merge this or tag a new version?

**Comment by milktrader** [comment]
This one slipped through the cracks because I needed to do a manual merge of a PR and didn't have the automated testing interface in front of me on github.

**Comment by tkelman** [comment]
should probably make a new tag with the test fixes

**Comment by milktrader** [comment]
New dataset coming soon and will include test fix

**Pull request merged**
