### PR TITLE
Tag RDatasets v0.2.0

### PR DESCRIPTION
**Pull request by randyzwitch**
Fixes RData deprecation errors, which cascaded into several other packages

### CODE REVIEW

**Comment by ararslan** [comment]
Since the 0.1.4 tag has been removed from the repo, you should rebase out that commit here and just leave the one for the 0.2.0 tag.

**Comment by tkelman** [comment]
if you do `using FileIO` then you should explicitly depend on FileIO in REQUIRE.

**Comment by tlnagy** [comment]
`RData` depends on `FileIO`, but if `RDatasets` does an explicit `FileIO` call then it should be in `REQUIRE`

**Comment by tkelman** [comment]
@randyzwitch can you please add the require changes here?

**Comment by randyzwitch** [comment]
Yeah, doing it right now.

Do I have to do rebase? I feel like I’m going to mangle that if I try.

**Comment by tkelman** [comment]
not needed. you can modify the files in place in this branch of your fork. you did a rename so the previous tag won't end up in the registration, and I'll squash on merge when ready.

**Pull request merged**
