### PR TITLE
Register new package ApplicationBuilder.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [NHDaly/ApplicationBuilder.jl](https://github.com/NHDaly/ApplicationBuilder.jl)
Release: [v0.2.1](https://github.com/NHDaly/ApplicationBuilder.jl/releases/tag/v0.2.1)
Travis: [Travis Build Status](https://travis-ci.org/NHDaly/ApplicationBuilder.jl/builds/416374525)
cc: @NHDaly

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@NHDaly This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by NHDaly** [comment]
Build passes for 0.6 and 0.7,  except for the "fully-self-contained" section which still fails due to an upstream problem in MacroTools.

I'm happy to have this merged in! :)

**Comment by NHDaly** [comment]
If you're waiting for a successful travis build, I can just remove the test or mark it `@test_broken`. The package is working, it's just that one of the unit tests is testing packaging up `Blink`, which depends on MacroTools, and that's not working due to this small problem: https://github.com/MikeInnes/MacroTools.jl/pull/85

**Comment by NHDaly** [comment]
Is that something I should try to do?

**Comment by andreasnoack** [comment]
We had to make some adjustments to our CI which was the reason why I closed and opened this a couple of times. It can be merged now.

**Pull request merged**
