### PR TITLE
Tag DataDeps.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [oxinabox/DataDeps.jl](https://github.com/oxinabox/DataDeps.jl)
Release: [v0.4.0](https://github.com/oxinabox/DataDeps.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/oxinabox/DataDeps.jl/builds/405606437)
Diff: [vs v0.3.5](https://github.com/oxinabox/DataDeps.jl/compare/32426c97807afb0ff575692f4077e88777c7261d...a30005b059f2b771d540f6c2c8e501fe175ea863)
`requires` vs v0.3.5: no changes
cc: @oxinabox

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by oxinabox** [comment]
Is There a reason this hasn't been merged?

 it is causing issues for other work

https://github.com/oxinabox/PyDrive.jl/issues/1#issuecomment-407269863


And further I'd rather have this merged
 before I tag the 0.5.0, to bring in 0.7.0 support.

**Comment by martinholters** [comment]
Is CIBot feeling better?

**Comment by oxinabox** [comment]
> Is CIBot feeling better?

Nope, looks like it is having some networkish problems.
like it is dropping connection partway though a download or otherwise corrupting some of the files I use in tests

**Comment by oxinabox** [comment]
Can this be poked again?
It is passing locally, and it passed when I merged the PR.
It seems just JuliaCIBot is flaking out

**Comment by oxinabox** [comment]
Close this in favor of 
https://github.com/JuliaLang/METADATA.jl/pull/16243
which doesn't have the flaky test

**Pull request closed without merging**
