### PR TITLE
Tag StatsModels.jl v0.2.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/StatsModels.jl](https://github.com/JuliaStats/StatsModels.jl)
Release: [v0.2.5](https://github.com/JuliaStats/StatsModels.jl/releases/tag/v0.2.5)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/StatsModels.jl/builds/381782770)
Diff: [vs v0.2.4](https://github.com/JuliaStats/StatsModels.jl/compare/5905ab57d9c76dc6bc247dcef2343836b55c729e...d4ae81540e7c70b737ed63c316b4993d4e3e453e)
`requires` vs v0.2.4: 
```diff
--- 0.2.4/requires
+++ 0.2.5/requires
@@ -1,4 +1,4 @@
 julia 0.6
 DataFrames 0.11.5
-StatsBase 0.20.1
+StatsBase 0.22.0
 Compat 0.63
```
cc: @kleinschmidt

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by kleinschmidt** [comment]
FixedEffectModels is upper-bounded to v0.2.4 of this package (#14429) so failure there shouldn't be an issue.

**Comment by andreasnoack** [comment]
It looks like `FixedEffectModels` actually has been using `StatsModels` in previous versions without it being reflected by the `REQUIRE` file so more upper bounds would have to be applied to the previous versions of the package to avoid breaking it.

**Comment by kleinschmidt** [comment]
Okay, should I close this PR and open a new one with those additional upper bounds then?

**Comment by andreasnoack** [comment]
I prefer to have the upper bounds in a separate PR. Then we just trigger the tests here when the upper bounds are in place.

**Comment by matthieugomez** [comment]
I am not sure I understand the importance of upper bounds very well, but a new version of FixedEffectModels is tagged now that should not break with this update, so maybe that's enough?

**Pull request merged**
