### PR TITLE
Bump NullableArrays

### PR DESCRIPTION
**Pull request by quinnj**
cc: @davidagold @johnmyleswhite @nalimilan 

This is a quick bump for 0.4.

### CODE REVIEW

**Comment by tkelman** [comment]
push the tag to https://github.com/JuliaStats/NullableArrays.jl/releases

also generally preferable to make metadata pr's from your fork rather than branches within JuliaLang

**Comment by nalimilan** [comment]
Ah, I wished you had included https://github.com/JuliaStats/NullableArrays.jl/pull/117. Nevermind, I'll tag a new release.

**Comment by quinnj** [comment]
Yeah, I wasn't sure if that was ready to go yet; anyway, this was more of a 0.4 update release. That PR still didn't get all of 0.5 working, right?

**Comment by nalimilan** [comment]
> That PR still didn't get all of 0.5 working, right?

No, but it fixes some essential features (only `broadcast` doesn't work now AFAIK).

**Pull request merged**
