### PR TITLE
Register new package Context.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bramtayl/Context.jl](https://github.com/bramtayl/Context.jl)
Release: [v0.0.1](https://github.com/bramtayl/Context.jl/releases/tag/v0.0.1)
cc: @bramtayl

### CODE REVIEW

**Comment by ViralBShah** [comment]
I couldn't quite tell what this package is about from the name. Would be nice to have a more descriptive name, but ok not too if you prefer to keep as is.

**Comment by bramtayl** [comment]
Sure! What do you think I should call it?

**Comment by bramtayl** [comment]
Maybe LazyContext?

**Comment by bramtayl** [comment]
Superseded by #9181

**Pull request closed without merging**
