### PR TITLE
Tag GR v0.9.8

### PR DESCRIPTION
**Pull request by jheinen**

### CODE REVIEW

**Comment by tkelman** [comment]
Should probably add `julia 0.3` to a REQUIRE file if you aren't testing with any earlier julia versions

**Comment by milktrader** [comment]
The package has a REQUIRE but the tag does not. Odd.

**Comment by tkelman** [comment]
Oh, that is very strange. @jheinen are you using `Pkg.publish`, or making these metadata commits manually?

**Comment by jheinen** [comment]
I didn't know about ``Pkg.publish``. - I make metadata commits manually. If I'm doing something wrong, pls let me know ...

**Comment by milktrader** [comment]
I'm not sure off-hand how `Pkg.publish` handles it, but somehow it generates a `requires` file that is stored in the version directory, along with the `sha1`. Presumably it reads the REQUIRE file in your package for this. This `requires` file is used to define the floor (and ceiling) of Julia versions and the packages in that file, which is useful information for users when they invoke a `Pkg.update()`

**Comment by wildart** [comment]
To get a correct METADATA commit (which includes `requires` file), you need to run `Pkg.tag` before publishing manually or through `Pkg.publish`.

**Comment by milktrader** [comment]
Yeah, probably the best way going forward is to run this ...

````julia
Pkg.update()                #get latest METADATA
Pkg.tag("GR", :patch)  # :patch is the default, :minor and :major are other options
Pkg.publish()                # generates the PR for METADATA and other magical things
````

**Pull request merged**
