### PR TITLE
Tag Permutations.jl v0.2.7

### PR DESCRIPTION
**Pull request by attobot**
Repository: [scheinerman/Permutations.jl](https://github.com/scheinerman/Permutations.jl)
Release: [v0.2.7](https://github.com/scheinerman/Permutations.jl/releases/tag/v0.2.7)
Travis: [Travis Build Status](https://travis-ci.org/scheinerman/Permutations.jl/builds/415162854)
Diff: [vs v0.2.6](https://github.com/scheinerman/Permutations.jl/compare/d5f4ee9dd8386ef926bc33e69c601f3cb7d7443d...98d04f40bcc2400399081b17d3d90d6595bb6468)
`requires` vs v0.2.6: no changes
cc: @scheinerman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like tests are failing across the board

**Comment by scheinerman** [comment]
I started the long slog of adapting my code to the new Julia. I gotta say: This has been really frustrating. I'll give it another go soon. The language and package management changes are causing me no end of grief.

**Comment by scheinerman** [comment]
Looking at the error. It says:

`* LinearAlgebra (not found in project, manifest or registry)`

Shouldn't this be a standard Julia package?

**Comment by andreasnoack** [comment]
Are you still having problems with the upgrade? Please provide a little more context for the issue. Otherwise, it is difficult to help. Sometimes running the `resolve` command in the package manager will help.

**Comment by scheinerman** [comment]
Hi. I'm having lots of problems. Frankly, the transition from 0.6 to 0.7 has been horrible for me. I don't understand the new package manager, lots of stuff has gotten moved or renamed, syntax has changed, and from my perspective there is no value add. I'm not a computer scientist or software engineer, but just a regular schlub who wants to use Julia for calculations and simulations. It feels like users like me are forgotten. I also have a full time job, so working on this is evenings and weekends. 

I'll try to get back at this and let you know if I can ask more specific questions.

**Comment by scheinerman** [comment]
My version 0.3.0 has passed all tests. Anything left i need to do?

**Comment by andreasnoack** [comment]
No. Since 0.3 has been released, I guess this can be closed.

**Pull request closed without merging**
