### PR TITLE
Tag WCS.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaAstro/WCS.jl](https://github.com/JuliaAstro/WCS.jl)
Release: [v0.3.0](https://github.com/JuliaAstro/WCS.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaAstro/WCS.jl/builds/424959215)
Diff: [vs v0.2.0](https://github.com/JuliaAstro/WCS.jl/compare/9c740fc35adc90937e0c88718d1119201d77302a...8b459cd90838967117421f5dfb351f1fb088ae66)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.3.0/requires
@@ -1,2 +1,2 @@
-julia 0.5
-BinDeps 0.4.1
+julia 0.6
+BinaryProvider 0.3.0
```
cc: @giordano

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like there are only a few deprecations left to fix before this would work Julia 1. Are you sure that you don't want to fix them before the release? If not, please consider adding an upper bound on Julia.

**Comment by giordano** [comment]
There is already new PR with fixes for julia 1.0: https://github.com/JuliaAstro/WCS.jl/pull/21  Next version of the package will come with changes incompatible with Julia 0.6

**Comment by andreasnoack** [comment]
Okay. Then it would be great if you could add the upper bound.

**Comment by giordano** [comment]
Done!

**Pull request merged**
