### PR TITLE
Tag AutoHashEquals v0.0.11

### PR DESCRIPTION
**Pull request by andrewcooke**
contains pull request to support latest 0.6
https://github.com/andrewcooke/AutoHashEquals.jl/pull/7

### CODE REVIEW

**Comment by tkelman** [comment]
Since this drops support for Julia 0.4, it needs to use a new package minor version

**Comment by tkelman** [comment]
You could enable https://github.com/attobot/attobot#usage on your repository, then it would just be a single click to make a new v0.1.0 release from your current master.

Otherwise we could do it manually, it would be creating and pushing a git tag to the package, then renaming these files in your metadata fork to reflect the new tag name.

**Comment by tkelman** [comment]
merged #7822, closing this

**Comment by andrewcooke** [comment]
so that worked?  thanks.  will use that in future.

**Pull request closed without merging**
