### PR TITLE
Tag BinDeps.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaLang/BinDeps.jl](https://github.com/JuliaLang/BinDeps.jl)
Release: [v0.8.0](https://github.com/JuliaLang/BinDeps.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaLang/BinDeps.jl/builds/298208801)
Diff: [vs v0.7.0](https://github.com/JuliaLang/BinDeps.jl/compare/e2553e57468d5692f7e13f45ddc888670bcbbfda...e691a120fb982f646512de9378f34d408fa9da96)
`requires` vs v0.7.0: 
```diff
--- 0.7.0/requires
+++ 0.8.0/requires
@@ -1,5 +1,4 @@
-julia 0.5
-@linux julia 0.7.0-DEV.1287
+julia 0.6
 URIParser
 SHA
-Compat 0.17.0
+Compat 0.27.0
```
cc: @ararslan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
Hold up, BinDeps master should not be tagged, it will freeze on julia 0.6.0

**Comment by ararslan** [comment]
What causes freezing on 0.6.0, do you know?

**Comment by tkelman** [comment]
See the PR I opened last month. If you want to fix nightly-only depwarns in it, go ahead.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/BinDeps.jl/pull/333 is also necessary before it's safe to tag.

**Comment by ararslan** [comment]
Ah, good points. Thanks, I'll get that in and retag.

**Comment by ararslan** [comment]
Ideally I'd also kind of like to get #334 into this next tag as well, but I'm not sure how feasible that is.

**Comment by tkelman** [comment]
That's a new feature, not a major regression relative to the last release

**Comment by ararslan** [comment]
Right, I just mean I'd like it to be in the tag. :)

**Comment by aviks** [comment]
Closing this for safety, please reopen if required.

**Pull request closed without merging**
