### PR TITLE
Tag PyAMG v0.0.3

### PR DESCRIPTION
**Pull request by cortner**
0.0.3 update to PyAMG

### CODE REVIEW

**Comment by tkelman** [comment]
Note that test-only dependencies should be listed in `test/REQUIRE`, not just `.travis.yml`. You can also make nightly an allowed failure so it will run but not make the status red. Using Conda.jl may be worth looking at to automate the Python-side dependency installation.

**Comment by cortner** [comment]
After I fix this so I tag a new version and create a new pull request or do I update the current one?

**Comment by tkelman** [comment]
It's a little less noise here to update the existing PR with a new tag, if you can get the tag commit made and pushed to the same branch of your metadata fork.

**Comment by cortner** [comment]
Ok, happy to do try, but you will need to help with this. I've already spent more time on this than I have available.

**QUESTION ONE:** here is my new travis file, but it still reports a failure. As far as I can tell, I followed instructions on the travis website, the julian-website doesn't give any instructions on this.

```
language: julia
os:
  - linux
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - nightly
sudo:
  - required
notifications:
  email: false
```

**Comment by cortner** [comment]
**QUESTION TWO:** `Conda.jl` isn't exactly brimming with documentation either.  Are you suggesting that I add Conda.jl to `test/REQUIRE` and then install scipy, etc within `runtests.jl`?

**Comment by tkelman** [comment]
the allow_failures has to specify which key is allowed to be "nightly" and fail. namely, the "julia" key under allow_failures then nightly under julia.

not test/REQUIRE for Conda, REQUIRE and deps/build.jl then .travis.yml should not need to do anything other than Pkg.build("PyAMG"). Conda could use some links to examples of packages that do this to manage python deps smoothly.

**Comment by cortner** [comment]
not test/REQUIRE for Conda, REQUIRE and deps/build.jl then .travis.yml should not 
     need to do anything other than Pkg.build("PyAMG"). Conda could use some links to
     examples of packages that do this to manage python deps smoothly.

After playing with this for some time, I decided to not go ahead with it until I understand better what `Conda.jl` does. it seems it actually installs its own miniconda distribution and doesn't use the existing Python environment.

**Comment by cortner** [comment]
this should now satisfy your requirements. The `Conda.jl` usage I will look at more closely when I have more time.

**Comment by tkelman** [comment]
these are just suggestions not absolute requirements, sorry for not making that clear. Conda.jl uses its own environment to install things, and most packages invoke it in a way that they use the existing system python environment if they can find it and the right package is present there, and fall back to a new Conda install otherwise. It may be worth opening an issue there to discuss getting good examples and detailed descriptions into the docs there.

Your merge commit here pulled in several unrelated commits, it's preferred to rebase relative to the upstream branch to keep the pr just touching your own package's files.

**Comment by cortner** [comment]
Your merge commit here pulled in several unrelated commits, it's preferred to rebase
    relative to the upstream branch to keep the pr just touching your own package's files.

I'm afraid I have no idea what this means. In the absence of clear instructions of what I need to do, would it be best if I just delete all tags, delete all METADATA and start over?

**Comment by tkelman** [comment]
We can give you clear instructions for how to fix it without needing to delete anything, as long as you have command line git available. Wait a few minutes for me to type it up, I'm on a phone.

**Comment by cortner** [comment]
no problem and thank you. I will eventually get to grips with this whole mechanism.

**Comment by tkelman** [comment]
- first, `cd` to the location that `Pkg.dir("METADATA")` returns
- check `git branch`, it should say `pull-request/0d48ffb5`
- check `git remote -v`, it will probably say `origin git://github.com/JuliaLang/METADATA.jl (fetch)` and a similar one for `(push)`
- run `git remote add cortner https://cortner@github.com/cortner/METADATA.jl`
- run `git fetch --all`
- check `git log -1`, it should start with `797950358d7ae816b767c7f0499e2d93a293af10`
- run `git rebase -i origin/metadata-v2`
- it should show a list of just your commits
- you can choose to squash a few of them together but we can now do that through github, so not required
- once rebase is done, check `git log` and it should show only your commits in order, on top of the most recent thing merged to the upstream metadata-v2 branch
- run `git push --force cortner pull-request/0d48ffb5`
- refresh this page, it should have just your commits

if anything isn't what I expected it to be, let me know what it actually is

**Comment by cortner** [comment]
`git log` shows the following:

```
commit c2dc07a2871271e8d4627bdf550baf116d4cedd3
Author: Christoph Ortner <c.ortner@warwick.ac.uk>
Date:   Sat May 21 19:38:43 2016 +0100

    Tag PyAMG v0.0.3

commit 935666ef96c80ed7757fae469d6207c1add45ec2
Author: Christoph Ortner <c.ortner@warwick.ac.uk>
Date:   Sat May 21 19:38:29 2016 +0100

    removed 0.0.3 tag

commit 7dc21ae453d7810c979a02661b9537c5d3142e7c
Author: Christoph Ortner <c.ortner@warwick.ac.uk>
Date:   Fri May 20 22:29:15 2016 +0100

    Tag PyAMG v0.0.3

commit c9ab58bd5c12761d8d44e650da35513dffbcc4ed
Author: Christoph Ortner <c.ortner@warwick.ac.uk>
Date:   Thu May 19 23:07:17 2016 +0100

    Tag PyAMG v0.0.2

commit c609aff715031ce1735485ab2f468d028e1a0376
Author: Christoph Ortner <c.ortner@warwick.ac.uk>
Date:   Thu May 19 20:14:04 2016 +0100

    Register PyAMG: v0.0.1

commit 63338b834a131a9216e6308a400df2d981150e82
Author: Andreas Noack <andreasnoackjensen@gmail.com>
Date:   Sat May 21 15:25:41 2016 -0400

    Tag Distributions v0.9.0 (#5239)

commit e80d89a043ee88a7e6baa7c42984a6f41eae160e
Author: Andreas Noack <andreasnoackjensen@gmail.com>
Date:   Sat May 21 11:21:58 2016 -0400

    Tag FactCheck v0.4.3 (#5238)

commit 134d83207fa440aba5f18d05b06a85343e070ae8
Author: Juan Ignacio Polanco <jipolanc@gmail.com>
```

Then
```
git push cortner pull-request/0d48ffb5
Username for 'https://github.com': cortner
Password for 'https://cortner@github.com':
Everything up-to-date
```

**Comment by tkelman** [comment]
That log looks right, but you likely needed to push with `--force`. And are you sure the `git branch` you just rebased on was `pull-request/0d48ffb5` ? This PR should have updated with the changes but that push-without-force didn't upload anything.

**Comment by cortner** [comment]
I actually did so --force, I then did it again without because I was surprised there were no other messages

**Comment by tkelman** [comment]
Very strange, I don't see a log that looks like that at https://github.com/cortner/METADATA.jl/commits/pull-request/0d48ffb5. Maybe try `git checkout -b pyamg-new && git push cortner pyamg-new` and see if that is more visible?

**Comment by cortner** [comment]
Yeah - I think I am done with this. Unless there is a quick fix now, I will close this tomorrow.

**Comment by cortner** [comment]
For the future: this has to become easier, if this is the kind of nonsense I have to deal with overtime I submit something, then I simply won't register packages anymore. And will all due respect to how many of these requests you have to deal with, when it is pretty clear from the beginning that you are now dealing with somebody who is well-versed with git, then you can't have them jump through all of these hoops, when there is the simple option of just submitting a new pull-request, which we ended up doing in the end again anyhow.

**Comment by tkelman** [comment]
> when it is pretty clear from the beginning that you are now dealing with somebody who is well-versed with git

I can't keep track of everyone's level of familiarity with git, sorry.

I said:

> It's a little less noise here to update the existing PR with a new tag, if you can get the tag commit made and pushed to the same branch of your metadata fork.

I didn't think you'd push a merge commit here. That's where this went wrong. If you had just pushed the new tag commit and only the new tag commit it would have been fine. Doesn't really matter.

**Comment by cortner** [comment]
see, the problem is I still don't know what you are talking about. Maybe all it needs are clear and detailed instructions in the documentation that you can point to when there is a problem.

**Comment by tkelman** [comment]
The commit that says "Merge branch 'pull-request/0d48ffb5' of https://github.com/cortner/METADATA.jl into metadata-v2". Part of the problem is when git hits a conflict or a non-fast-forward, it defaults to telling you to merge, which then pulls in unrelated changes into PR's. But yes, this does happen often enough that it's worth writing down so we can refer to it in a standard place.

**Comment by cortner** [comment]
thanks - that would be really great - I am sure I won't remember in the future. And sorry for the outburst earlier.

**Comment by ViralBShah** [comment]
While it would be nice to automate all the python build dependencies eventually, I think we do not need to do so in the early days of a package.

**Comment by cortner** [comment]
I started playing with pyimport_conda

**Pull request closed without merging**
