### PR TITLE
Tag Nemo.jl v0.7.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Nemocas/Nemo.jl](https://github.com/Nemocas/Nemo.jl)
Release: [v0.7.0](https://github.com/Nemocas/Nemo.jl/releases/tag/v0.7.0)
Travis: [Travis Build Status](https://travis-ci.org/Nemocas/Nemo.jl/builds/312847225)
Diff: [vs v0.6.3](https://github.com/Nemocas/Nemo.jl/compare/58e80e13410c968f12caa8f0771d19da9e5ff645...46da26e02e45394b66d04b712150fca5a9b7b3f9)
`requires` vs v0.6.3: 
```diff
--- 0.6.3/requires
+++ 0.7.0/requires
@@ -1,2 +1 @@
-julia 0.5
-
+julia 0.6
```
cc: @thofma

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by thofma** [comment]
Can this be merged soonish? We have an upcoming presentation where we would like to have this new tagged version available.

**Comment by thofma** [comment]
Thanks!

**Comment by aviks** [comment]
Note that the `Hecke` test failed with the new Nemo version. It seems it failed to download `mpfr`, so could just be a temporary glitch. But might be worth a quick check.. logs here: 

http://juliarun-ci.s3.amazonaws.com/a7f1236a0efec67ce43e3835ffba4673e56fab9e/Hecke_with_pull_request_of_Nemo_on_julia_0_6.log

**Comment by thofma** [comment]
Thanks. I have to tag a new Hecke version soonish. Should I upper bound the old/current one?

**Pull request merged**
