### PR TITLE
Tag PkgBenchmark.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaCI/PkgBenchmark.jl](https://github.com/JuliaCI/PkgBenchmark.jl)
Release: [v0.1.0](https://github.com/JuliaCI/PkgBenchmark.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaCI/PkgBenchmark.jl/builds/342707802)
Diff: [vs v0.0.2](https://github.com/JuliaCI/PkgBenchmark.jl/compare/15d12e6133ceded59f521dd9dffa1a0c467b2317...0ee84db5e32f7ac6be6656044a50bcc7c1526e03)
`requires` vs v0.0.2: 
```diff
--- 0.0.2/requires
+++ 0.1.0/requires
@@ -1,4 +1,4 @@
-julia 0.5
-FileIO
-JLD
+julia 0.6
+JSON
 BenchmarkTools
+ProgressMeter
```
cc: @KristofferC

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
@KristofferC Do you know what it going on here?

**Comment by KristofferC** [comment]
With what? JuliaCIBot?

**Comment by andreasnoack** [comment]
> With what? JuliaCIBot?

Yes

**Comment by KristofferC** [comment]
Yes, it is a bug in the package :) Will fix.

**Comment by KristofferC** [comment]
Let's see now.

**Pull request merged**
