### PR TITLE
Register new package CmdStan.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [StanJulia/CmdStan.jl](https://github.com/StanJulia/CmdStan.jl)
Release: [v1.0.0](https://github.com/StanJulia/CmdStan.jl/releases/tag/v1.0.0)
Travis: [Travis Build Status](https://travis-ci.org/StanJulia/CmdStan.jl/builds/397453480)
cc: @goedman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@goedman This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by goedman** [comment]
Thank you!

**Comment by vchuravy** [comment]
This broke master due to the inclusion of the `DelimitedFiles` and `Unicode`.
@goedman this is not your fault and CI should have caught this, but I will revert this PR for now.
Please remove the stdlibs from your REQUIRE file and resubmit this PR.

**Comment by goedman** [comment]
Maybe CI should have caught it, but this is the 2nd time I made the same mistake. My apologies.

**Comment by vchuravy** [comment]
No worries! It is fixed now.

**Comment by goedman** [comment]
Cool, thank you guys for all the great work! Just 3 more Julia 0.7 + Pkg(3) package conversions to do and then back to the real work!

**Pull request merged**
