### PR TITLE
Tag RationalFunctions

### PR DESCRIPTION
**Pull request by aytekinar**
### Description

Tagging [`RationalFunctions 0.0.2`](https://github.com/aytekinar/RationalFunctions.jl/releases).

### Changelog

Added
- [x] Unit tests,
- [x] Function fitting (`funcfit`),
- [x] Plotting support (`plot` through `RecipesBase`), and,
- [x] Documentation (`?command`).

Sample plots for common platforms (as artifacts from unit tests) are also provided.

**Note.** Requires `Polynomials 0.1.2` (latest version as of now) due to the bugfix Keno/Polynomials.jl@b8a6bf4e.

### CODE REVIEW

**Comment by tkelman** [comment]
It's maybe a bit questionable to be defining `/(p1::Poly, p2::Poly)` here, since there might be other comparable packages that would want to do the same and they'd have to fight with your package about it. Any two packages that tried to do that same method extension but returning different result types could never both be used in a way that relied on that functionality at the same time.

**Comment by aytekinar** [comment]
@tkelman, I had thought about it. still, I thought any person who would like to use `/(p1:Poly, p2:Poly)` would not be `using RationalFunctions` and `using XYZ` at the same time. Do you think I would drop that constructor in the next version?

**Comment by tkelman** [comment]
It's not just a single package issue though. If some set of packages decide to start depending on RationalFunctions and some other set of packages starts depending on XYZ, then any time you wanted to use packages from both those sets in the same Julia session, that method would behave unpredictably (would depend on loading order) and likely in a way that half the packages won't expect.

**Comment by aytekinar** [comment]
I wish you had just requested a revision, then. Since no package is depending on `RationalFunctions` now, I will just drop support and tag it `v0.0.3` today.

**Comment by tkelman** [comment]
It's mostly a long term concern. We should write a linter that checks type signatures for this automatically. I don't think Lint.jl has features for this yet, but I could be wrong.

**Pull request merged**
