### PR TITLE
METADATA Tests: Modify tag revision

### PR DESCRIPTION
**Pull request by omus**
Used 0.4.0 tag revision for 0.4.1

Testing changes in #8548

### CODE REVIEW

**Comment by omus** [comment]
> ERROR: LoadError: LoadError: Do not modify existing published tag sha1 files (policy 8)

**Comment by omus** [comment]
> ... (policy 8)

@tkelman is there a list of these policies somewhere?

**Comment by tkelman** [comment]
the readme, which github doesn't show any more because there are too many top-level folders

**Comment by omus** [comment]
Call me crazy. This repo doesn't have a README.

**Comment by tkelman** [comment]
.md https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/README.md

**Pull request closed without merging**
