### PR TITLE
Tag RNGTest v0.0.4

### PR DESCRIPTION
**Pull request by andreasnoack**
Some minor updates maunly to avoid warnings.

### CODE REVIEW

**Comment by tkelman** [comment]
Are you still testing this on prereleases of julia 0.2?

**Comment by andreasnoack** [comment]
Of course I am :smile: . Actually, I don't think there is anything in the package that requires more a recent Julia.

**Comment by tkelman** [comment]
It should at least drop the `-`. That sets a really counterintuitive example and we should get rid of it everywhere it isn't actually needed.

**Comment by andreasnoack** [comment]
I've opened a new with updated version requirement

**Comment by tkelman** [comment]
thanks

**Pull request closed without merging**
