### PR TITLE
Register new package MultivariateFunctions.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [s-baumann/MultivariateFunctions.jl](https://github.com/s-baumann/MultivariateFunctions.jl)
Release: [v0.1.0](https://github.com/s-baumann/MultivariateFunctions.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/s-baumann/MultivariateFunctions.jl/builds/462263130)
cc: @s-baumann

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@s-baumann This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
The name of this package seems rather generic. What is the scope?

**Comment by s-baumann** [comment]
The scope is that you can perfectly represent any function which is composed of polynomial or exponential terms. Any function can be piecewise. In many dimensions this is done by seperating the space in hypercubes each of which has its own funciton. If you have a function that can be represented in this way you can construct it directly. If you wanted to make an approximation function from data then there are a few approximation schemes implemented for one dimensional functions implemented including constant and linear interpolation, schumaker shape preserving spline, Chebyshev polynomials, OLS. For higher dimensional functions you can make an approximation function from Chebyshev polynomials or OLS. I am working on implementing MARS splines but this is not done yet.

There are algebra functions (overloading +, -, /, *, ^) and analytical differentiation and integration implemented. In addition there is a basic Newtonian root-finder and optimiser that use the analytical Jacobians and Hessians.

The main usecase I guess would be approximation. The idea is that by having one framework that can approximate lots of functions then you can do alot of stuff analytically and simply. For instance you could approximate f(x) with a schumaker spline and add it to g(x,y) that you approximated with Chebyshev polynomials. Then square the sum of these two functions and take the integral of this square. This can all be done analytically. For a more concrete application in one dimension see StochasticIntegrals.jl which finds the covariance of two Ito integrals by multiplying their two integrands (represented as functions) and then integrating.

It is a generalisation of UnivariateFunctions.jl to arbitrarily many dimensions. It is a superset of UnivariateFunctions.jl's functionality and will replace it for all intensive purposes.

**Comment by andreasnoack** [comment]
Sounds similar to https://github.com/JuliaApproximation/ApproxFun.jl

**Comment by s-baumann** [comment]
yeah it is quite similar to ApproxFun.jl. To be honest I did not know of that package. From a quick look I do a few things differently but there is a fair amount of overlap.

**Pull request merged**
