### PR TITLE
Tag WriteVTK v0.4.4 [https://github.com/jipolanco/WriteVTK.jl]

### PR DESCRIPTION
**Pull request by jipolanco**

### CODE REVIEW

**Comment by tkelman** [comment]
Is the test failure on 0.4 expected here?

**Comment by jipolanco** [comment]
Not really, sorry I didn't notice that. I'll take a look at it.

Regarding the failure on 0.6, it is related to an upstream issue that has already been fixed (https://github.com/BioJulia/Libz.jl/commit/1838a247a1402b01d9987a729e609b942e7b7120), and I'm waiting for them to tag a new version.

**Comment by jipolanco** [comment]
I just fixed the issue and pushed a new commit to WriteVTK.jl, which is now tagged as v0.4.4. The updated sha1 file points to this new commit.

**Comment by jipolanco** [comment]
I just re-tagged v0.4.4 including the latest changes.

**Pull request merged**
