### PR TITLE
Tag StatsBase v0.8.0

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by nalimilan** [comment]
+1

**Comment by tkelman** [comment]
Do any existig tags of othet packages need upper bounds to avoid potential problems?

**Comment by nalimilan** [comment]
What kind of problems do you have in mind? FWIW, I don't think the newly added functions conflict with existing packages (at least not with GLM.jl and MixedModels.jl).

**Comment by nalimilan** [comment]
Ah, wait, I didn't know @dmbates had defined `AIC` and `BIC` in MixedModels.jl. See PR https://github.com/dmbates/MixedModels.jl/pull/41

OTOH, GLM.jl tests work fine. Any other related packages?

**Comment by andreasnoack** [comment]
Do you want to have `AIC` and `BIC` in `StatsBase` before we tag?

**Comment by andreasnoack** [comment]
@nalimilan What was your conclusion on `AIC` and `BIC`? Can we merge here or would you prefer a retagging of `StatsBase`?

**Comment by nalimilan** [comment]
@andreasnoack AIC and BIC already are in StatsBase 0.8.0. The problem was that MixedModels.jl also exported it (https://github.com/JuliaLang/METADATA.jl/pull/4701). We should be able to merge both PRs at the same time for a smooth transition now. Maybe merge this one, rerun the checks on the other one (which depends on this one) to be certain, and merge it. Good to go?

**Pull request merged**
