### PR TITLE
Tag QuartzImageIO.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIO/QuartzImageIO.jl](https://github.com/JuliaIO/QuartzImageIO.jl)
Release: [v0.3.1](https://github.com/JuliaIO/QuartzImageIO.jl/releases/tag/v0.3.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIO/QuartzImageIO.jl/builds/243315241)
Diff: [vs v0.3.0](https://github.com/JuliaIO/QuartzImageIO.jl/compare/efb89816fe1a99fbcf413b94a5fc6710108eddb0...c4c51c6afe703fb987c87baea392dca4e56ea927)
`requires` vs v0.3.0: no changes
cc: @rsrock

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
Is the package travis failure expected? Looks like it passed at the last tag?

**Comment by rsrock** [comment]
Yeah, I just noticed that.  I have no idea what is going on here.  Tests pass locally.  The only thing I can think of is that the Travis macOS image is rather old (10.9?-- have to translate the Darwin vers. no.). So perhaps something is different about the Quartz API from back then?

**Comment by tkelman** [comment]
I don't think the default is that old any more https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

**Comment by rsrock** [comment]
Right.  I think this might have to do with changes in Images.jl, or some dependent packages.  I can see some similar issues locally if I start from a clean package dir.

Hopefully the new Images tag will fix it all.

**Comment by tkelman** [comment]
I restarted a build at https://travis-ci.org/JuliaIO/QuartzImageIO.jl/jobs/242120433, still errors with Images 0.10.1

**Comment by timholy** [comment]
This does fix Images (see https://github.com/JuliaImages/Images.jl/pull/648#issuecomment-309361860). I wish it were different, but I'm not sure if Images has anything to do with the `_TIFFVSetField` error.

**Comment by tkelman** [comment]
Should be possible to ask for temporary ssh access to a travis build worker for debugging if you contact travis' support address

**Comment by rsrock** [comment]
Ok, that's good to know.

Looks like several things broke in this package recently. I think I can reproduce at least some of them.  I'll let you know once I've sorted it all out.

**Comment by timholy** [comment]
Bump

**Comment by tkelman** [comment]
Did you mean to include https://github.com/JuliaIO/QuartzImageIO.jl/commit/0c62dbbad9a2b261a83c3d7ef607af74c43c788 ? Looks like that may have fixed the problem on Travis?

**Comment by rsrock** [comment]
Indeed I did.  I must have goofed up Attobot in some way.
Ah, I see, I need to delete the tag too.  Makes sense.  Hang tight here...

**Comment by rsrock** [comment]
That looks better

**Pull request merged**
