### PR TITLE
Tag Lora v0.3.2

### PR DESCRIPTION
**Pull request by scidom**

### CODE REVIEW

**Comment by IainNZ** [comment]
Nice! Now should just have to do the same on `master` of your package for the `Julia 0.4` version.

**Comment by scidom** [comment]
Yeap, I am trying, haha, got an error though... ok, I am just deleting my ~/.julia/v0.4 and if I still get the same error after this second attempt, I will post the error message here :)

**Comment by scidom** [comment]
It seems a bit messed up right now, I must have done sth silly. So at the beginning I was getting an error that I did not have the right code and my credentials were not recognized. Then I delete ~/.julia altogether and tried the following:

```
Pkg.update()
Pkg.add("Lora")
Pkg.checkout("Lora")
Pkg.tag("Lora", v"0.4.2")
Pkg.publish()
```

and here is the error I get this time (different than before):

```
julia> Pkg.tag("Lora", v"0.4.2")
INFO: Tagging Lora v0.4.2
fatal: tag 'v0.4.2' already exists
ERROR: failed process: Process(`git --work-tree=/home/theodore/.julia/v0.4/Lora --git-dir=/home/theodore/.julia/v0.4/Lora/.git tag --annotate --message 'Lora v0.4.2 [0ba03c50ef]' v0.4.2 0ba03c50ef3f0d942271b0bc0e9bbb8bf31f8bc4`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:517
 in run at process.jl:493
 in tag at pkg/entry.jl:603
 in tag at pkg/entry.jl:559
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31

julia> Pkg.publish()
ERROR: There are no METADATA changes to publish
 in publish at pkg/entry.jl:348
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61
```

**Comment by scidom** [comment]
Ok, I fixed the above error by using git:

```
git tag -d v0.4.2
git push origin :refs/tags/v0.4.2
```

Now I get the following new error (which may relate to change of my credentials in metadata - have the credentials being revoked in the meantime?):

```
INFO: Could not authenticate with existing token. Deleting token and trying again.
Enter host password for user 'scidom':
INFO: Retrieving existing GitHub token. (You may have to re-enter your password.)
Enter host password for user 'scidom':
ERROR: forking JuliaLang/METADATA.jl failed: Bad credentials
 in error at ./error.jl:21
 in fork at pkg/github.jl:144
 in pull_request at pkg/entry.jl:327
 in publish at pkg/entry.jl:394
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61
```

I couldn't fix this, so I will leave it with you to sort it out as I am sure you know better than me.

**Comment by IainNZ** [comment]
Hah, no you can sort it out, almost there.
Go to https://github.com/settings/tokens and delete the Julia Package Manager token. Hopefully that should fix it.

**Comment by scidom** [comment]
No way...! That's some serious hacking... ok, will try it straight away!

**Comment by scidom** [comment]
Ok, job done, PR submitted! Thanks for this tip, I learnt a couple of new git/github tricks.

**Pull request merged**
