### PR TITLE
Tag LightGraphs 0.7.1

### PR DESCRIPTION
**Pull request by sbromberger**
Kruskal's algorithm, tweaks to euclidean, various bugfixes.

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like you need to push the tag to the package repo. See https://travis-ci.org/JuliaLang/METADATA.jl/builds/163480774#L182.

**Comment by sbromberger** [comment]
Nice catch. I'm having to do this manually since PkgDev.publish() has been broken ever since I upgraded to 0.5.

**Comment by sbromberger** [comment]
Tag pushed to the repo.

**Comment by ararslan** [comment]
Great, thanks! Can you close and reopen the PR to retrigger the Travis build?

**Comment by sbromberger** [comment]
@ararslan all good?

**Pull request merged**
