### PR TITLE
Tag MixedModels.jl v0.13.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [dmbates/MixedModels.jl](https://github.com/dmbates/MixedModels.jl)
Release: [v0.13.0](https://github.com/dmbates/MixedModels.jl/releases/tag/v0.13.0)
Diff: [vs v0.12.0](https://github.com/dmbates/MixedModels.jl/compare/40b3a6d42bf2771d46e059710ff80adf67f85c6b...6d99ac613fd84364fcd8f79a47fd611413e0ffa9)
`requires` vs v0.12.0: 
```diff
--- 0.12.0/requires
+++ 0.13.0/requires
@@ -8,5 +8,6 @@
 NamedArrays
 NLopt 0.3
 Showoff
+StaticArrays 0.6
 StatsBase 0.11
 StatsFuns 0.3
```
cc: @dmbates

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
The CIBot indicates that tests fail on 0.6 with this tag. http://juliarun-ci.s3.amazonaws.com/ff8637b99e187af698182fc3ba177f6c7106266d/pull_request_of_MixedModels_on_julia_0_6.log Do you want to look into that?

**Comment by dmbates** [comment]
I don't have that problem

julia> versioninfo()
Julia Version 0.6.1
Commit 0d7248e2ff (2017-10-24 22:15 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

I hadn't tested on v0.6.0.  Would it be best to install v0.6.0 to test
there or should I just try increasing the lower bound on julia in REQUIRE?

**Comment by dmbates** [comment]
The `MixedModels` package was caught in the transition to `DataFrames v0.11.0`.  Between the time that this PR was submitted and it was merged v0.11.0 and v0.11.1 of `DataFrames` were released.  This version of `MixedModels` fails with `DataFrames 0.11.0` and later because `Formula`, etc. were moved to the `StatsModels` package.  Advice on how to proceed would be appreciated.

**Comment by aviks** [comment]
So I suppose the fix is to add an upper bound to the DataFrames dependencies for MixedModels. Milan had done this for all DF dependants, but, as you say, this got caught in the transition. I've submitted a PR at #12250

**Comment by dmbates** [comment]
Thank you.

**Pull request merged**
