### PR TITLE
Register new package Authorization.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JockLawrie/Authorization.jl](https://github.com/JockLawrie/Authorization.jl)
Release: [v0.1.0](https://github.com/JockLawrie/Authorization.jl/releases/tag/v0.1.0)
cc: @JockLawrie

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@JockLawrie This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
I would say that the name of this package seems too generic. Maybe you could change it to something more specific?

**Comment by dpsanders** [comment]
I would say that the name of this package seems too generic. Maybe you could change it to something more specific?

**Comment by JockLawrie** [comment]
Sure. Any ideas? Tricky to name because it's a pretty abstract package on its own, but has some concrete applications which are unrelated to each other (e.g., data storage, web sessions). `Permissions.jl`?

**Comment by andreasnoack** [comment]
Personally, I think it's okay unless somebody can come up with something better.

**Pull request merged**
