### PR TITLE
Tag TranscodingStreams.jl v0.7.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bicycle1885/TranscodingStreams.jl](https://github.com/bicycle1885/TranscodingStreams.jl)
Release: [v0.7.0](https://github.com/bicycle1885/TranscodingStreams.jl/releases/tag/v0.7.0)
Travis: [Travis Build Status](https://travis-ci.org/bicycle1885/TranscodingStreams.jl/builds/414834636)
Diff: [vs v0.6.1](https://github.com/bicycle1885/TranscodingStreams.jl/compare/4f1e1996b2d5bfa2e3875f48a818a2a6c34c624c...b87d348f36eb3b803231447f90f4e0032b504306)
`requires` vs v0.6.1: no changes
cc: @bicycle1885

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like tests are failing on 1.0 (nightly). Please enable explicit testing on 1.0.

**Comment by bicycle1885** [comment]
I know that (https://github.com/bicycle1885/TranscodingStreams.jl/pull/58) but the CI failure on Julia 1.0 is due to LibCURL.jl (see https://travis-ci.org/bicycle1885/TranscodingStreams.jl/jobs/414415536#L509).

**Comment by bicycle1885** [comment]
Can you merge this? I'm not sure what you are waiting for...

**Comment by andreasnoack** [comment]
Most people are updating for 1.0 so I thought you might wanted the dependencies fixed before tagging.

**Pull request merged**
