### PR TITLE
Register new package Combine.jl v0.9.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ppalmes/Combine.jl](https://github.com/ppalmes/Combine.jl)
Release: [v0.9.2](https://github.com/ppalmes/Combine.jl/releases/tag/v0.9.2)
cc: @ppalmes

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@ppalmes This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
This seems like a very generic name, which gives no information about what the package is about. Maybe something could be added to the name to specify that?

**Comment by ppalmes** [comment]
One option is CombineML. 

Its main feature is to have seamless ensembling of different machine learning models from different libraries such as scikit-learn from python, caret from R and julia native. However, to make this possible, the package create wrappers for common interfaces and workflow. I think once the user is familiar with its function, Combine name should become obvious. Also, it does not only support ensembling but general workflow of modeling.

**Comment by ppalmes** [comment]
I'll rename the package to CombineML to be more specific and retag.

**Comment by ppalmes** [comment]
I renamed the package into CombineML and bumped the release version. This PR can now be closed because there is a new PR for the new name.

**Pull request closed without merging**
