### PR TITLE
Register CVXOPT [https://github.com/cvxopt/CVXOPT.jl.git]: v0.1.0

### PR DESCRIPTION
**Pull request by martinandersen**

### CODE REVIEW

**Comment by mlubin** [comment]
Awesome!!

**Comment by mlubin** [comment]
CC @madeleineudell @blegat @joehuchette @chriscoey

**Comment by dpsanders** [comment]
Is there any particular reason for using the GPL license? This is uncommon in the Julia ecosystem, and will probably restrict the reach of the package.

**Comment by mlubin** [comment]
@dpsanders, it's a wrapper for a python package which is already GPL

**Pull request merged**
