### PR TITLE
Register LinearEquations [https://github.com/KeitaNakamura/LinearEqua…

### PR DESCRIPTION
**Pull request by KeitaNakamura**

### CODE REVIEW

**Comment by tkelman** [comment]
If you enabled Travis CI, would your tests pass?

**Comment by KeitaNakamura** [comment]
Sorry, I have never used Travis CI. What I need to do is add files for Travis CI (.travis.yml, appveyor.yml and .codecov.yml) generated by `PkgDev.generate("LinearEquations")`? My tests will pass when I do `Pkg.test("LinearEquations")`. Thank you in advance.

**Comment by tkelman** [comment]
Right, something like
```yml
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
email: false
```

appveyor and codecov are optional, but you can add them if you want windows testing and coverage reporting

**Comment by KeitaNakamura** [comment]
Okey. I will close this PR first, and submit again.

**Pull request closed without merging**
