### PR TITLE
Register new package NextGenSeqUtils.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [MurrellGroup/NextGenSeqUtils.jl](https://github.com/MurrellGroup/NextGenSeqUtils.jl)
Release: [v0.1.1](https://github.com/MurrellGroup/NextGenSeqUtils.jl/releases/tag/v0.1.1)
cc: @nbavafa

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@nbavafa This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by quinnj** [comment]
Same as other package; please enable travis testing on 0.7 and ensure tests pass.

**Comment by nbavafa** [comment]
We have quite a few dependancies that are not Julia 0.7 and Julia 1.0 compatible. We would like to release a Julia 0.6 version as is and update to Julia 0.7/1.0 once our dependancies are updated. 

Because of a paper submission, we would like our packages out as soon as possible, even if they only support Julia 0.6.

**Comment by andreasnoack** [comment]
If the package doesn't support 0.7 then please add an upper bound Julia in your REQUIRE file and update this PR as described in https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by nbavafa** [comment]
This has been now updated with automated travis testing and the proper Julia version require.

**Comment by andreasnoack** [comment]
It doesn't look like the PR has been updated. Please follow the steps from the link in https://github.com/JuliaLang/METADATA.jl/pull/17009#issuecomment-416177746

**Comment by andreasnoack** [comment]
It looks like there is still no upper bound. See https://github.com/MurrellGroup/NextGenSeqUtils.jl/blob/v0.1.1/REQUIRE

**Comment by nbavafa** [comment]
The package and tag have both been updated to reflect this requirement.

**Pull request merged**
