### PR TITLE
Tag ArbFloats.jl v0.1.13

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ArbFloats.jl](https://github.com/JuliaArbTypes/ArbFloats.jl)
Release: [v0.1.13](https://github.com/JuliaArbTypes/ArbFloats.jl/releases/tag/v0.1.13)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArbTypes/ArbFloats.jl/builds/184176546)
Diff: [vs v0.1.11](https://github.com/JuliaArbTypes/ArbFloats.jl/compare/3e49ec3ed2be9de9bb7410513435400b9bd6c49a...4655010eb6da712507280c823095473bf80f5fec)
`requires` vs v0.1.11: 
```diff
--- 0.1.11/requires
+++ 0.1.13/requires
@@ -1,3 +1,4 @@
-julia 0.5.0
-BinDeps 0.4.5
-Compat 0.9.5
+julia 0.5
+BinDeps 0.4
+Compat 0.9
+Nemo 0.5
```
cc: @JeffreySarnoff

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
@tkelman Is this ok?

**Comment by tkelman** [comment]
sure. would be good to add a travis badge to your readme, but that doesn't need tagging

**Comment by JeffreySarnoff** [comment]
I don't know how to add a travis badge to the readme.

**Comment by tkelman** [comment]
https://docs.travis-ci.com/user/status-images/

**Pull request merged**
