### PR TITLE
Tag TransformUtils v0.0.4 [https://github.com/dehann/TransformUtils.jl]

### PR DESCRIPTION
**Pull request by dehann**
Adding features and in-place memory speedups

### CODE REVIEW

**Comment by KristofferC** [comment]
Consider adding a Travis badge and maybe extend the README a bit. Currently, I think it would be difficult for a user to fully user your package.

**Comment by dpsanders** [comment]
The name of the package also seems to be rather generic and gives no information about the content of the package.

**Comment by KristofferC** [comment]
This is the travis badge code for your package
```
[![Build Status](https://travis-ci.org/dehann/TransformUtils.jl.svg?branch=master)](https://travis-ci.org/dehann/TransformUtils.jl)
```

which gives [Build Status](https://travis-ci.org/dehann/TransformUtils.jl)

**Comment by dehann** [comment]
@KristofferC thanks, I had assumed this badge is related to a build.jl script, is this true? Or is this script only related to my existing .travis.yml file and travis-ci.org output? I noticed the badge in your comment is showing 'build failing'. Would that be something I fix in my repo or via some setting on the Travis-CI web interface?

**Comment by dehann** [comment]
I did add badge [here](https://github.com/dehann/TransformUtils.jl/commit/f4d2b97300e32cc34e1386b885eb92d440574ccc) -- just not sure how to clear the 'build falling' issue. Do I need a build.jl? Thanks!

**Comment by dehann** [comment]
Ah, looks like I got it on Travis interface, thanks!

**Pull request merged**
