### PR TITLE
Tag Cairo.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphics/Cairo.jl](https://github.com/JuliaGraphics/Cairo.jl)
Release: [v0.4.0](https://github.com/JuliaGraphics/Cairo.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphics/Cairo.jl/builds/312243994)
Diff: [vs v0.3.1](https://github.com/JuliaGraphics/Cairo.jl/compare/0fa5949fb347fbc0fdd39344ab0c67900b81a04c...10913a18895481fd49ec661ff6c7a5730814e962)
`requires` vs v0.3.1: 
```diff
--- 0.3.1/requires
+++ 0.4.0/requires
@@ -1,5 +1,5 @@
-julia 0.4
-Compat 0.9.5
+julia 0.5
+Compat 0.39.0
 Colors
 BinDeps 0.3.21
 Graphics 0.1
```
cc: @lobingera

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by lobingera** [comment]
@aviks Is there a reason, why this isn't merged?

**Comment by aviks** [comment]
METADATA tests had failed on Travis. I restarted the tests a few minutes ago, and they have now passed, seems like a glitch on travis. Merging now.

**Comment by lobingera** [comment]
I see.

**Comment by aviks** [comment]
@cormullion Luxor tests seem to be failing for juila `v0.5.2`. See here: http://juliarun-ci.s3.amazonaws.com/c640fd401ee23e4f931d64a2214265b2f53a7d67/Luxor_with_pull_request_of_Cairo_on_julia_0_5.log

**Comment by cormullion** [comment]
@aviks Aargh. 😤 But Luxor doesn’t support Julia v0.5, only 0.6, so I’ll have to investigate older versions... Thanks for message...

**Pull request merged**
