### PR TITLE
Register new package LogDensityProblems.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [tpapp/LogDensityProblems.jl](https://github.com/tpapp/LogDensityProblems.jl)
Release: [v0.1.0](https://github.com/tpapp/LogDensityProblems.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/tpapp/LogDensityProblems.jl/builds/432469849)
cc: @tpapp

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@tpapp This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tpapp** [comment]
Please kindly merge #18321 before this as that is a dependency.

**Comment by andreasnoack** [comment]
Please update this PR once #18321 has been merged.

**Comment by tpapp** [comment]
Will do. Can you please merge #18321, and possibly also #18289?

**Comment by andreasnoack** [comment]
They'll get merged after three days.

**Comment by tpapp** [comment]
@andreasnoack: can you please close/open to trigger CI again, now that the dependency is registered?

**Comment by andreasnoack** [comment]
You can trigger a rebuild by removing and reapplying the tag.

fre. 28. sep. 2018 kl. 07.51 skrev Tamas K. Papp <notifications@github.com>:

**Comment by tpapp** [comment]
Closing in favor of #18567.

**Comment by andreasnoack** [comment]
In the future, please just update a single PR instead of opening new ones. It makes it harder to keep track of things.

**Pull request closed without merging**
