### PR TITLE
Tag DifferentialEquations v0.1.3

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
All of the ODE and SDE solvers allow for in-place functions. The ODE and SDE solvers have been overhauled to become as close to optimal as possible, sacrificing some code cleanliness to get little to no unnecessary allocations from the solver. A new tutorial is included on using in-place functions in a problem definition.  New tests were added for this, and other examples were fixed up.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Is there something wrong with the commit? Is there a reason v0.1.2 is showing up there?

**Comment by ChrisRackauckas** [comment]
I checked and it's the same sha1 tag on v0.1.2 as the recently merged one. Do I need to fix this or will it merge automatically? And what do you think caused this?

**Comment by dpsanders** [comment]
Probably a silly question, but did you do Pkg.update() before
Pkg.publish()?

**Comment by KristofferC** [comment]
`git rebase origin/metadata-v2` maybe and then force push to this branch

**Comment by ChrisRackauckas** [comment]
Yeah I did. There was an error so I pulled from METADATA manually too.

**Comment by ChrisRackauckas** [comment]
I just rebased and force pushed and it's still there?

**Comment by KristofferC** [comment]
```
git checkout metadata-v2 # make sure this is the same as origin has
git checkout -b tag/diffeq
git cherry-pick 18fefd8ce0af53fc90d12c03605c34cf0042607a
```

and then force push here should fix it then...

**Comment by ChrisRackauckas** [comment]
The rebase seemed to fix metadata-v2, but this was on a special pull-request branch that for some reason I couldn't checkout / couldn't push to. So I just opened a new pull-request from my metadata-v2 and it looks like that worked.

**Pull request closed without merging**
