### PR TITLE
Tag HttpParser v0.1.2

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by tkelman** [comment]
Did you ever build new windows binaries? Are you running appveyor, have you tested this on windows since https://github.com/JuliaWeb/HttpParser.jl/pull/36#issuecomment-195599392?

**Comment by malmaud** [comment]
Mmm no. I didn't build the Windows binaries for this the first time - do you know if there is already an automated build for it?

**Comment by tkelman** [comment]
I don't think so. This needs to be reverted for now though.
```
INFO: Testing HttpParser
ERROR: LoadError: test error in expression: HttpParser.version() >= @v_str("2.6")
ccall: could not find function http_parser_version in library C:\Users\Tony\.julia\v0.4\HttpParser\deps\usr\lib\libhttp_parser64.DLL
 in version at C:\Users\Tony\.julia\v0.4\HttpParser\src\HttpParser.jl:99
 in version at C:\Users\Tony\.julia\v0.4\HttpParser\src\HttpParser.jl:99
while loading C:\Users\Tony\.julia\v0.4\HttpParser\test\runtests.jl, in expression starting on line 212
=================================================[ ERROR: HttpParser ]==================================================

failed process: Process(`'E:\code\Julia-0.4.5-win64\bin\julia' --check-bounds=yes --code-coverage=none --color=yes 'C:\Users\Tony\.julia\v0.4\HttpParser\test\runtests.jl'`, ProcessExited(1)) [1]

========================================================================================================================
ERROR: HttpParser had test errors
 in error at error.jl:21
```

**Comment by malmaud** [comment]
OK, sorry about that.

**Comment by malmaud** [comment]
Actually, that same error will be thrown even for non-Windows users who
already have a previous HttpParser version.

**Comment by tkelman** [comment]
Should use a BinDeps validation hook then if the API changes require the latest version.

**Pull request merged**
