### PR TITLE
Tag TaylorSeries.jl v0.7.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiff/TaylorSeries.jl](https://github.com/JuliaDiff/TaylorSeries.jl)
Release: [v0.7.0](https://github.com/JuliaDiff/TaylorSeries.jl/releases/tag/v0.7.0)
Diff: [vs v0.6.0](https://github.com/JuliaDiff/TaylorSeries.jl/compare/d2eedd7565a8ca97e42bb4dd2915dab8d7d5e60c...5d9794fedf32b9d67a9f44ce1f4a367e6f453df0)
`requires` vs v0.6.0: no changes
cc: @lbenet

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Tests failed for `TailorSeries`. Is it just too tight  a bound? The failure for `TailorIntegration` seems more concerning.

**Comment by lbenet** [comment]
Thanks @aviks for taking a look on this. We have noticed that occasionally such failure in the tests happens (maybe the random matrices considered include too large and near zero entries). Is there a way that JuliaCIBot can be restarted? Do I have to delete this tag and restart a new one so things can be again tested?

The failures in TaylorIntegration.jl and related to some changes in TaylorSeries.jl (some indices now start at zero, which is naturally in this case), and a PR is already awainting for v0.7.0 to be ready.

**Comment by lbenet** [comment]
Good trick! Thanks!

**Comment by lbenet** [comment]
@aviks Would it be possible to merge this, despite of the failure in TaylorIntegration? As I comment, changes in TaylorSeries are currently breaking TaylorIntegration, but this has already been addressed; see [this](https://github.com/PerezHz/TaylorIntegration.jl/pull/43).

**Comment by aviks** [comment]
Yes, so long as you know what is happening.

**Comment by lbenet** [comment]
Thanks a lot!

**Pull request merged**
