### PR TITLE
Tag ForwardDiff.jl v0.9.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiff/ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl)
Release: [v0.9.0](https://github.com/JuliaDiff/ForwardDiff.jl/releases/tag/v0.9.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiff/ForwardDiff.jl/builds/422353967)
Diff: [vs v0.8.5](https://github.com/JuliaDiff/ForwardDiff.jl/compare/ae9c4f7edd5368a8c8f2a22a9fc0db2e2f13e462...f21d4d5d0b56152aa0d072383fef683a061b5589)
`requires` vs v0.8.5: 
```diff
--- 0.8.5/requires
+++ 0.9.0/requires
@@ -1,4 +1,4 @@
-julia 0.7-rc3
+julia 0.7
 StaticArrays 0.8.3
 DiffResults 0.0.1
 DiffRules 0.0.4
```
cc: @jrevels

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by jrevels** [comment]
I'm going to make a follow-up PR to this one placing a Julia v1.0 upperbound on previous ForwardDiff releases. ref https://github.com/JuliaDiff/ForwardDiff.jl/issues/352

**Comment by mlubin** [comment]
I don't see any breaking changes in the diff. Is there a reason this was tagged as 0.9? Is it forced by METADATA rules?

**Comment by jrevels** [comment]
Yeah, this release isn't "normal". 

The reasons for the minor version bump are a) we bumped the minimum Julia version number in ForwardDiff's REQUIRE and b) the intention is to put a Julia v1.0 upperbound on most previous ForwardDiff versions.

This is basically my attempt at fixing a Pkg resolution issue where many users are apparently being given old ForwardDiff versions when using Julia v1.0 (i.e. one that doesn't even support 1.0, e.g. ForwardDiff v0.7). ref #17516

**Comment by jrevels** [comment]
Actually, nobody merge this yet - I'm going to add Julia v2.0 upperbound first to avoid us getting into this situation again :p

**Comment by jrevels** [comment]
Okay, now it should be fine to merge once CI passes.

**Comment by jrevels** [comment]
Argh. 

Looks like DiffEqPhysics is hitting a failure due to https://github.com/JuliaDiff/ForwardDiff.jl/commit/19003af62af38a110fa6ec12d3b52cd3451e4a03#diff-60599227d871d54fb6e88cbadac97271R78.

Giving that commit a second look, the slicing there could actually be problematic anyway because it could introduce allocations...

**Comment by maleadt** [comment]
Ah yes, didn't notice that because CuArray slicing is broken:

```julia
julia> for T in (Array,CuArray)
       a = T{Int}(zeros(5))
       b = a[2:4]
       b .= 1
       @show a
       end
a = [0, 0, 0, 0, 0]
a = [0, 1, 1, 1, 0]
```

I'll have a look.

**Comment by jrevels** [comment]
Okay, reverted the change that seemed to cause downstream failures. Fingers crossed...

**Pull request merged**
