### PR TITLE
Split JLD from HDF5; update Images and Options

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by jiahao** [comment]
That's a lot of JLD versions :)

**Comment by jiahao** [comment]
Also, shouldn't JLD 0.5.0 require HDF5 0.5.0?

**Comment by mbauman** [comment]
:tada:!  Do you mean to tag 0.5 as the `teh/split_jld` branch?  Or have you just not pushed your local master (with that branch merged) yet?

**Comment by timholy** [comment]
Oh, crap. Yes, I messed this up big time.

It occurs to me that since I'm going to be traveling for the next ~18hrs, maybe I should just wait to do this until I can deal with the fallout.

**Pull request closed without merging**
