### PR TITLE
Tag ParallelDataTransfer.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ChrisRackauckas/ParallelDataTransfer.jl](https://github.com/ChrisRackauckas/ParallelDataTransfer.jl)
Release: [v0.2.0](https://github.com/ChrisRackauckas/ParallelDataTransfer.jl/releases/tag/v0.2.0)
Diff: [vs v0.1.1](https://github.com/ChrisRackauckas/ParallelDataTransfer.jl/compare/09f8838c3c391582825ee2299cf6304c9f49dd11...24faa0355a1c96790205f6c707d38b5917c0d835)
`requires` vs v0.1.1: no changes
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by tkelman** [comment]
Is the test failure on win32 expected? https://ci.appveyor.com/project/ChrisRackauckas/paralleldatatransfer-jl/build/1.0.39/job/dk7qau86caal073j

**Comment by ChrisRackauckas** [comment]
No. Don't merge.

**Comment by ChrisRackauckas** [comment]
Oh wait, that's v0.6? I hadn't tried for v0.6 compatibility here yet. I was just asked to tag for a previous v0.5 change. Is that okay? I'm not sure what v0.6 compatibility will need.

**Comment by tkelman** [comment]
Yeah nevermind, I misread the ordering of jobs there

**Comment by tkelman** [comment]
Was thrown off since Travis goes Linux release, Linux nightly, Mac release, then Mac nightly, but Appveyor is win32 release, win64 release, win32 nightly, win64 release.

**Pull request merged**
