### PR TITLE
Register new package BracedErrors.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [stakaz/BracedErrors.jl](https://github.com/stakaz/BracedErrors.jl)
Release: [v0.1.0](https://github.com/stakaz/BracedErrors.jl/releases/tag/v0.1.0)
cc: @stakaz

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@stakaz This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please enable Travis testing and put the Travis status badge in your README

**Comment by stakaz** [comment]
Could you give me a hint on what exactly I need to do? It is my first package.

**Comment by andreasnoack** [comment]
Sure. You'd have to go set up your account at https://travis-ci.org/. You'll just link it to your GitHub account. Once you've done that, it should be possible to enable Travis for your GitHub repos. Then you'll have to add a `.travis.yml` file to the repo you'd like to test. See e.g. https://github.com/bicycle1885/TranscodingStreams.jl/blob/master/.travis.yml. Now your package will be tested each time a new commit is registered. Finally, you'd like to put a badge with the test status in your README. It's explained in https://docs.travis-ci.com/user/status-images/ and you can also see example in other packages.

**Comment by stakaz** [comment]
Thanks. I have added anything and will update my release.

**Pull request merged**
