### PR TITLE
Tag MIDI.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMusic/MIDI.jl](https://github.com/JuliaMusic/MIDI.jl)
Release: [v0.6.0](https://github.com/JuliaMusic/MIDI.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMusic/MIDI.jl/builds/401213357)
Diff: [vs v0.5.1](https://github.com/JuliaMusic/MIDI.jl/compare/8b51a44509ce205eafbdb8470e4c1642b11cda1b...19d4693e67f56c2ad0c25d0bd94e5f8302f3032c)
`requires` vs v0.5.1: 
```diff
--- 0.5.1/requires
+++ 0.6.0/requires
@@ -1 +1 @@
-julia 0.6
+julia 0.7
```
cc: @Datseris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
Should be `julia 0.7-alpha` I think? To support pre-releases of julia.

**Comment by Datseris** [comment]
Well I don't really know if it works on 0.7-alpha, I used the beta and there have been things that changed between alpha and beta.

**Comment by andreasnoack** [comment]
Then you probably need `0.7-beta` instead of just `0.7`.

**Comment by Datseris** [comment]
Sorry @andreasdominik , I did not realize my mistake of not writing `-beta` in the REQUIRE. (which is why I may sounded confused).

I fixed it now.

**Pull request merged**
