### PR TITLE
Tag JLD.jl v0.6.10

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIO/JLD.jl](https://github.com/JuliaIO/JLD.jl)
Release: [v0.6.10](https://github.com/JuliaIO/JLD.jl/releases/tag/v0.6.10)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIO/JLD.jl/builds/214737745)
Diff: [vs v0.6.9](https://github.com/JuliaIO/JLD.jl/compare/b8ba932074746809b07aee08978943264c75d0ef...1adf77183ece207d0040eb0d95ee1996b45d1fc4)
`requires` vs v0.6.9: no changes
cc: @ararslan

### CODE REVIEW

**Comment by ararslan** [comment]
cc @tkelman @jrevels @StefanKarpinski

**Comment by musm** [comment]
as @tkelman  pointed out the only troublesome PR is https://github.com/JuliaIO/JLD.jl/pull/124, so why revert all the way to 0.69 only to  backport  #142

**Comment by ararslan** [comment]
Because that's what we discussed doing in #8461.

**Comment by aviks** [comment]
Given that 0.6.9 is the last release version, this is a strict improvement, I suppose.

**Pull request merged**
