### PR TITLE
Tag Reactive 0.3.0 and Interact 0.3.0

### PR DESCRIPTION
**Pull request by shashi**

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like this is the first 0.4 only Interact tag?

**Comment by shashi** [comment]
Yes, because it depends on a Reactive that depends on 0.4. Should I bump minor version instead?

**Comment by tkelman** [comment]
That leaves open the possibility of any future 0.3 bugfix releases if necessary, so I do think it's worth separating.

**Comment by shashi** [comment]
Good idea. Will do soon.

**Comment by shashi** [comment]
Done.

**Comment by shashi** [comment]
ping @SimonDanisch

**Comment by SimonDanisch** [comment]
nice! :+1:

**Pull request merged**
