### PR TITLE
Tag Compat.jl v0.36.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaLang/Compat.jl](https://github.com/JuliaLang/Compat.jl)
Release: [v0.36.0](https://github.com/JuliaLang/Compat.jl/releases/tag/v0.36.0)
Diff: [vs v0.35.0](https://github.com/JuliaLang/Compat.jl/compare/fbd9cb245a89af2c6d3eea0f1622729a14709163...a419b7cc58363613f282382a8cd06e4bcc04d7c9)
`requires` vs v0.35.0: no changes
cc: @nalimilan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Mind retagging with https://github.com/JuliaLang/Compat.jl/pull/412 merged?

**Comment by nalimilan** [comment]
Sure, done!

**Comment by martinholters** [comment]
Closing and reopening to retrigger JuliaCIBot. Or is there a known issue and it's not worth waiting for it?

**Comment by KristofferC** [comment]
The CIBot said the tests passed but returned a failure anyway.

**Pull request merged**
