### PR TITLE
Register KDTrees

### PR DESCRIPTION
**Pull request by KristofferC**
Pkg.publish() is not working for me.

image

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Is this a bug report or a pull request? Both?

**Comment by KristofferC** [comment]
95% pull request, 5% bug report. For a real bug report I would use a better place.

**Comment by ViralBShah** [comment]
PR looks good to merge. Any reason not to?

**Comment by aviks** [comment]
There are quite a few versions being tagged in one go. Only the last one is useful.

**Pull request merged**
