### PR TITLE
Register & Tag mmtf.jl v0.0.1

### PR DESCRIPTION
**Pull request by joels94**

### CODE REVIEW

**Comment by kmsquire** [comment]
Hi, @joels94, thanks for submitting this package. Generally, registered Julia packages follow certain naming conventions.  See this link:

https://docs.julialang.org/en/stable/manual/packages/#Guidelines-for-naming-a-package-1

**Comment by joels94** [comment]
Hi @kmsquire, thanks for the suggestion. How about MMTF.jl? MMTF stands for MacroMolecular Transmission Format. Its a file format used to store data in binary format. I have written a package to parse and write MMTF file format. So, like other file format packages (BSON.jl, JSON.jl, CSV.jl, etc), can we have it as MMTF.jl?

**Comment by bicycle1885** [comment]
I think MMTF.jl is much better.

**Comment by bicycle1885** [comment]
But, why are you going to register it as a separated package? I think it can be a submodule of BioStructures.jl.

**Comment by joels94** [comment]
Thanks, @bicycle1885 for the suggestion! In that case, let me close this pull request and create a new PR once I have renamed the package.

**Comment by joels94** [comment]
@bicycle1885 I was having a discussion with Joe Greener about having it as a separate package similar to other MMTF libraries such as [mmtf-python](https://github.com/rcsb/mmtf-python), [mmtf-javascript](https://github.com/rcsb/mmtf-javascript), etc. Maybe we can further discuss it in an issue in our repo https://github.com/BioJulia/mmtf.jl.

**Comment by jgreener64** [comment]
I feel it makes more sense as its own package in line with similar packages from other languages. BioStructures.jl can then import and extend the decoding/encoding functionality.

**Pull request closed without merging**
