### PR TITLE
Pull request/fdd7bec5

### PR DESCRIPTION
**Pull request by sbromberger**
testing and a bugfix that would trigger on specifically-defined, rare occasions.

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Seems like something went wrong here.

**Comment by sbromberger** [comment]
Yeah. Pkg.tag("IPNets") followed by Pkg.update followed by Pkg.publish. Any ideas on what to do?

**Comment by johnmyleswhite** [comment]
I always do everything manually.

**Comment by sbromberger** [comment]
Let's try again, this time tagging AFTER update.

**Comment by sbromberger** [comment]
Nope, that didn't work either. I don't know how to publish manually.

**Comment by johnmyleswhite** [comment]
http://docs.julialang.org/en/latest/manual/packages/#man-manual-publish

**Pull request closed without merging**
