### PR TITLE
Register AbstractTables [https://github.com/davidagold/AbstractTable…

### PR DESCRIPTION
**Pull request by davidagold**
…s.jl.git]: v0.0.1

### CODE REVIEW

**Comment by tkelman** [comment]
turn travis on?

**Comment by davidagold** [comment]
Done.

**Comment by davidagold** [comment]
There was an error in my REQUIRE, hence the revised commit. We will need to merge https://github.com/JuliaLang/METADATA.jl/pull/6561 in order to satisfy the new requirements.

**Comment by davidagold** [comment]
I can't tell if the failure is my fault or not.

**Pull request merged**
