### PR TITLE
New package OpenFOAM.jl (updated)

### PR DESCRIPTION
**Pull request by andyreagan**

### CODE REVIEW

**Comment by andyreagan** [comment]
This is a continuation of the merge #4493

**Comment by tkelman** [comment]
This looks like the exact same tagged commit for your package, 588c99589c56b30c4ca1f7d6587f44308a2eaac4, but with a merge commit that touches 94 other files. Better to adjust #4493. I can help you do that, but what commit of your package would you like the tag to contain?

**Comment by andyreagan** [comment]
Should I make a new tag for my package? I was trying initially to start with the very beginning tag 0.0.1. I had to merge the metadata-v2 branch.

I want the tag 0.0.1 to contain the contain the master branch of my OpenFOAM.jl package at 7fd64855c2f0193cb9bfb17a8da2306b027179fc.

**Comment by tkelman** [comment]
Okay. Easiest to do this through github's web interface. Go to https://github.com/andyreagan/METADATA.jl/blob/pull-request/d3988eee/OpenFOAM/versions/0.0.1/sha1, click the little pencil "edit" icon, then change the sha to 7fd64855c2f0193cb9bfb17a8da2306b027179fc

Then go to #4493 and refresh your browser, and it should be right.

**Pull request closed without merging**
