### PR TITLE
Register new package EnhancedGJK.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rdeits/EnhancedGJK.jl](https://github.com/rdeits/EnhancedGJK.jl)
Release: [v0.0.1](https://github.com/rdeits/EnhancedGJK.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/rdeits/EnhancedGJK.jl/builds/203676219)
cc: @rdeits

### CODE REVIEW

**Comment by tkelman** [comment]
Would be a good idea to fill in the repository description, that'll show up on pkg.julialang.org. GJK is signed distance, right?

**Comment by rdeits** [comment]
Good point. Done!

**Comment by tkelman** [comment]
You're missing FileIO in `test/REQUIRE`

**Comment by rdeits** [comment]
thanks, fixed!

**Pull request merged**
