### PR TITLE
Upper-bound Unitful version for ImagineFormat

### PR DESCRIPTION
**Pull request by ajkeller34**
This PR is prep work for a version of Unitful with breaking changes (https://github.com/JuliaLang/METADATA.jl/pull/19557). I will make individual PRs for the [very few] packages that the breaking changes affect.

### CODE REVIEW

**Comment by andreasnoack** [comment]
What about the previous versions of ImagineFormat?

**Comment by ajkeller34** [comment]
Since the previous versions had no bounds on Unitful, is it fair to give the first Unitful release as the lower bound? Or do I need to go back and see whether each version of ImagineFormat actually works with the oldest versions of Unitful?

**Comment by andreasnoack** [comment]
You can just use `0.0` since that is what an empty entry means.

**Comment by timholy** [comment]
Depending on the number of releases (I honestly can't remember), [`propagate_upperbounds`](https://github.com/JuliaLang/PkgDev.jl/pull/94) can sometimes be useful. Requires julia-0.6 and checking out that branch.

**Comment by ajkeller34** [comment]
Okay, sorry for the noise and thanks for the help. I've used 0.0 as the lower bound and 0.13- as the upper bound for all versions using Unitful, since none of them had bounds previously.

**Pull request merged**
