### PR TITLE
Tag Mads.jl v0.4.8

### PR DESCRIPTION
**Pull request by attobot**
Repository: [madsjulia/Mads.jl](https://github.com/madsjulia/Mads.jl)
Release: [v0.4.8](https://github.com/madsjulia/Mads.jl/releases/tag/v0.4.8)
Travis: [Travis Build Status](https://travis-ci.org/madsjulia/Mads.jl/builds/233312586)
Diff: [vs v0.4.6](https://github.com/madsjulia/Mads.jl/compare/7ec7356b1c709891eb36c15fa82c91f8d8a6ec21...2299349e183594e916ced53e2e6f72e26cad09ad)
`requires` vs v0.4.6: 
```diff
--- 0.4.6/requires
+++ 0.4.8/requires
@@ -8,6 +8,7 @@
 ReusableFunctions
 RobustPmap
 SVR
+DocumentFunction
 Conda 0.4
 PyCall 1.8
 PyPlot 2.2
```
cc: @montyvesselinov

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by montyvesselinov** [comment]
Please let me know if there issues?! 0.4.7 has not been merged yet?!

**Comment by tkelman** [comment]
You asked for the 0.4.7 PR to be closed.

**Comment by montyvesselinov** [comment]
Yes, I closed the old 0.4.7 which had the bad Gadfly limits in REQUIRE. I added new 0.4.7 which has a code checking for a good Gadfly.

**Comment by tkelman** [comment]
There was only https://github.com/JuliaLang/METADATA.jl/pull/9159, where you said "this can be closed"

**Comment by montyvesselinov** [comment]
cool! Sorry! I will make a new one for 0.4.7 as well.

**Pull request merged**
