### PR TITLE
ProbabilisticNetwork package

### PR DESCRIPTION
**Pull request by tpoisot**
(first PR on METADATA, so I feel like pre-emptive apologies are needed)

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Since there's going to be some name-bikeshedding, maybe throw in a reference to ecology? I would have assumed this was a general purpose DAG library.

**Comment by tpoisot** [comment]
@johnmyleswhite Good call. I worry that `ProbabilisticEcologicalNetworks` is a bit too long. Let me think of something and I'll come back with a better name.

**Comment by IainNZ** [comment]
I'd say its not too long, but thats your call. Could shorten to `Eco`, or `Prob`, or even `Nets`? Cool package, regardless.

**Comment by joehuchette** [comment]
``ProbabilisticEcoNets``?

**Pull request closed without merging**
