### PR TITLE
Tag MeCab v0.1.4

### PR DESCRIPTION
**Pull request by chezou**
I fixed for v0.4.0-rc2
Cloud you merge it?

### CODE REVIEW

**Comment by tkelman** [comment]
package needs a minimum julia version in `REQUIRE`

**Comment by chezou** [comment]
@tkelman fixed on 04230f9 . Is it OK?

**Comment by tkelman** [comment]
not quite, the dash refers to prereleases so for 0.3 it should just be `julia 0.3`

also be sure to update the file in the package too so the next tag gets it automatically

**Comment by chezou** [comment]
I want to support both 0.3 and 0.4. If I'll write `julia 0.3` in require, is it also supports 0.4?

**Comment by tkelman** [comment]
Yes. The first number is a lower bound. If you provide a second number, it's an (exclusive) upper bound. http://docs.julialang.org/en/latest/manual/packages/#man-package-requirements

**Comment by chezou** [comment]
I understand and fix it 5053fff

**Comment by tkelman** [comment]
Looks good. I'll submit a PR to add the same to https://github.com/chezou/MeCab.jl/blob/master/REQUIRE.

**Comment by chezou** [comment]
Thanks! I recreate v0.1.4 tag on MeCab.jl and update commit hash e2d5783

**Comment by chezou** [comment]
Thanks! :raised_hands:

**Pull request merged**
