### PR TITLE
Release 0.0.6

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by KristofferC** [comment]
Please see the test failures: `The commit SHA for Xtensor 0.0.6 does not match between METADATA and the upstream package repository.`

**Comment by SylvainCorlay** [comment]
It seems to correspond: https://github.com/QuantStack/Xtensor.jl/commit/56c9808fe7a239a4bc2986f22a361d579852ee75

**Comment by SylvainCorlay** [comment]
Is it possible to restart the build ?

**Comment by KristofferC** [comment]
I restarted it.

**Comment by SylvainCorlay** [comment]
OK, this is ready!

**Pull request merged**
