### PR TITLE
Tag OrdinaryDiffEq.jl v2.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/OrdinaryDiffEq.jl](https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl)
Release: [v2.6.0](https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/releases/tag/v2.6.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/OrdinaryDiffEq.jl/builds/240036408)
Diff: [vs v2.5.0](https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/compare/3b4510e51379f91d95d498b21765dfcd428390c2...5468e199d6c2d8a2845613f09429a26419ced2de)
`requires` vs v2.5.0: 
```diff
--- 2.5.0/requires
+++ 2.6.0/requires
@@ -1,5 +1,5 @@
 julia 0.6.0-pre
-DiffEqBase 1.5.0
+DiffEqBase 1.10.0
 Parameters 0.5.0
 ForwardDiff 0.5.0
 GenericSVD 0.0.2
@@ -10,4 +10,3 @@
 Roots 0.2.1
 DataStructures 0.4.6
 Compat 0.18.0
-StaticArrays
```
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I deleted this tag awhile ago because regressions were found. I guess attobot did not close this PR?

**Comment by tkelman** [comment]
No, please put the git tag back for now. Leave a comment when you do that, please.

**Comment by tkelman** [comment]
https://github.com/attobot/attobot/issues/30

**Comment by ChrisRackauckas** [comment]
Sorry, I thought it would close the PR.

**Pull request merged**
