### PR TITLE
Tag ArbFloats.jl v0.1.12

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ArbFloats.jl](https://github.com/JuliaArbTypes/ArbFloats.jl)
Release: [v0.1.12](https://github.com/JuliaArbTypes/ArbFloats.jl/releases/tag/v0.1.12)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArbTypes/ArbFloats.jl/builds/184165683)
Diff: [vs v0.1.11](https://github.com/JuliaArbTypes/ArbFloats.jl/compare/3e49ec3ed2be9de9bb7410513435400b9bd6c49a...0e36073f3d44dffcf94e6d69368315e9a41df530)
`requires` vs v0.1.11: 
```diff
--- 0.1.11/requires
+++ 0.1.12/requires
@@ -1,3 +1,4 @@
 julia 0.5.0
-BinDeps 0.4.5
-Compat 0.9.5
+BinDeps 0.4.4
+Compat 0.9.4
+Nemo 0.5.0
```
cc: @JeffreySarnoff

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
closing to incorporate @tkelman's merge and advice

**Comment by simonbyrne** [comment]
In future, you can just delete the release and create a new one with the same version: the PR will then automatically be updated.

**Comment by JeffreySarnoff** [comment]
close this

**Comment by JeffreySarnoff** [comment]
@simonbyrne  Oh, that is helpful.

**Comment by JeffreySarnoff** [comment]
I did get [pull request for v0.1.13](https://github.com/JuliaLang/METADATA.jl/pull/7313) to build, before understanding that there was an easy way to fold the changes into this PR.  Can we close this one and use the one that now works? Otherwise tell me to delete both releases and create a new one with v0.1.12?

**Pull request closed without merging**
