### PR TITLE
Pull request/53c9c467

### PR DESCRIPTION
**Pull request by dehann**
Plotting functions originally held in IncrementalInference.jl and RoME.jl are now separated into this package.

[RoMEPlotting.jl](https://github.com/dehann/RoMEPlotting.jl)
[v0.0.1](https://github.com/dehann/RoMEPlotting.jl/releases/tag/v0.0.1)
[Build Status](https://travis-ci.org/dehann/RoMEPlotting.jl)

### CODE REVIEW

**Comment by dehann** [comment]
Hi, maybe I can ask for help in understanding this Travis error message please?
```julia
ERROR: LoadError: LoadError: Do not modify existing published tag sha1 files (policy 8).
Ask for an exception if absolutely necessary, but tag commits
should be immutable once published for reproducibility.
 in macro expansion; at /home/travis/build/JuliaLang/METADATA.jl/.test/check-pr.jl:75 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /home/travis/build/JuliaLang/METADATA.jl/.test/check-pr.jl, in expression starting on line 72
while loading /home/travis/build/JuliaLang/METADATA.jl/.test/METADATA.jl, in expression starting on line 237
```
I did redo the packages first tag v0.0.1 local to my repo only (before publishing), and the diff shows that I am just adding the required files to METADATA.jl. I'm not quite sure what Travis is unhappy about?

**Comment by aviks** [comment]
Could you possibly rebase your PR on top of the latest METADATA head? The tree was unfortunately broken at the time you made the PR, sorry.

**Comment by dehann** [comment]
got it thanks, will do.

**Comment by dehann** [comment]
Merged into `dehann/METADATA.jl/metadata-v2` from current `JuliaLang/METADATA.jl/metadata-v2` via [Github PR](http://github.com/dehann/METADATA.jl/pull/1). Then locally:
```
git clone https://github.com/dehann/METADATA.jl.git 
cd METADATA.jl; git fetch
git checkout pull-request/53c9c467
git rebase metadata-v2
git push --force
```
That automatically updated this PR here, so if you are happy with this I think we should be good --thanks.

**Pull request merged**
