### PR TITLE
Register new package DiffEqNoiseProcess.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DiffEqNoiseProcess.jl](https://github.com/JuliaDiffEq/DiffEqNoiseProcess.jl)
Release: [v0.0.1](https://github.com/JuliaDiffEq/DiffEqNoiseProcess.jl/releases/tag/v0.0.1)
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Hey @tkelman, just letting you know this will be part of a big ecosystem 2.0 release. The packages involved are:

```
DiffEqBase
OrdinaryDiffEq
StochasticDiffEq
RecursiveArrayTools
Sundials
ODE
ODEInterfaceDiffEq
LSODA
DiffEqMonteCarlo
DiffEqParamEstim
SteadyStateDiffEq
DiffEqNoiseProcess
DASKR
DASSL
DiffEqDevTools
DifferentialEquations
```

I believe this is the only "cross dependency" (this will require DiffEqBase 1.0.0, but DiffEqBase 1.0.0's tests will need this registered). All of the others should just get a minimum version bound for DiffEqBase and RecursiveArrayTools. Max version PR will come before the DiffEqBase update since that is breaking.

**Comment by tkelman** [comment]
RecursiveArrayTools is missing from REQUIRE

**Comment by ChrisRackauckas** [comment]
No valid versions exist because of the DiffEqBase 1.0.0 requirement

**Comment by ChrisRackauckas** [comment]
Is this another resolver issue or because it needs DiffEqBase 1.0.0 which won't be registered till after these 3 for testing purposes?

**Comment by tkelman** [comment]
DiffEqBase 1.0.0 needs to be registered before you can depend on it, otherwise these aren't installable

**Pull request merged**
