### PR TITLE
Tag ImageQuilting.jl v0.5.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/ImageQuilting.jl](https://github.com/juliohm/ImageQuilting.jl)
Release: [v0.5.2](https://github.com/juliohm/ImageQuilting.jl/releases/tag/v0.5.2)
Travis: [Travis Build Status](https://travis-ci.org/juliohm/ImageQuilting.jl/builds/251228254)
Diff: [vs v0.5.1](https://github.com/juliohm/ImageQuilting.jl/compare/44d70140e0b8652b31cc4775e6d86767a921322a...51f7054822c12705f3fb8b6c9f1beb8cc65e8fd8)
`requires` vs v0.5.1: no changes
cc: @juliohm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by juliohm** [comment]
It seems that the Gtk build is failing on JuliaCIBot, is this bot reproducing the environment from PackageEvaluator.jl?

**Comment by tkelman** [comment]
No, it's different. Looks like the environment variable USER doesn't always exist, which can make your tests error

**Comment by juliohm** [comment]
:disappointed:

What would be a wise fix for this?

**Comment by juliohm** [comment]
I will just check if the variable USER is defined then, but it seems that the error there is related to Gtk no?

**Comment by juliohm** [comment]
Can you please close this issue? I will submit a new one in a few minutes.

**Comment by tkelman** [comment]
if you delete and reuse the same version number attobot will update the pr, we can leave it open in "don't merge yet" state until then unless you want to use a new version

**Comment by juliohm** [comment]
@tkelman this should be ready to merge, thank you again.

**Pull request merged**
