### PR TITLE
Tag PiCraft.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaBerry/PiCraft.jl](https://github.com/JuliaBerry/PiCraft.jl)
Release: [v0.2.0](https://github.com/JuliaBerry/PiCraft.jl/releases/tag/v0.2.0)
Diff: [vs v0.1.0](https://github.com/JuliaBerry/PiCraft.jl/compare/39849d753c04a0546bb9f9469930f544dd8c65c1...fc1bdaef6fdea112f62291bb4919bd70cdd4c1a5)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1 +1 @@
-julia 0.5
+julia 0.6
```
cc: @aviks

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
You'd have to move the tag to a commit with `GZip` in `REQUIRE`.

**Comment by Ellipse0934** [comment]
@aviks can you retag and try again ? Also, please push the docs.

**Comment by andreasnoack** [comment]
https://github.com/JuliaBerry/PiCraft.jl/blob/master/test/runtests.jl#L2 needs to be changed. Might be a good idea to update `.travis.yml` to test on the supported versions of Julia.

**Comment by andreasnoack** [comment]
No activity for a month so closing

**Pull request closed without merging**
