### PR TITLE
Register QuantumTomography [https://github.com/BBN-Q/QuantumTomography.jl.git] 

### PR DESCRIPTION
**Pull request by marcusps**

### CODE REVIEW

**Comment by tkelman** [comment]
Needs a minimum Julia version requirement (only 0.4 or higher is being accepted in METADATA now). It would also be preferred if you could separate the commits to one PR per package, if possible (there's a bug we haven't fixed yet to make Pkg.publish do the right thing automatically)

**Comment by marcusps** [comment]
I separated the packages, but `QuantumInfo` is a dependency, so the the build will fail until  `QuantumInfo` is merged (#6362).

**Comment by tkelman** [comment]
Yep, we'll restart CI here when that happens. Thanks!

**Comment by tkelman** [comment]
You're doing `using SchattenNorms` in here, is that a separate package not yet registered?

**Comment by marcusps** [comment]
Ah, I missed that. Yeah, I'll be registering that right away as well, and
will make sure it is in the dependencies.

**Comment by blakejohnson** [comment]
LGTM

**Comment by tkelman** [comment]
Could you restart Travis in the package to see if it passes now? Same with the other recently-merged one.

**Comment by blakejohnson** [comment]
@tkelman both packages are now passing their tests.

**Pull request merged**
