### PR TITLE
Tag Sparklines v0.1.1

### PR DESCRIPTION
**Pull request by mbauman**
Fixes the deprecation warning for floating point indexing.

### CODE REVIEW

**Comment by tkelman** [comment]
Needs a Julia version requirement. What did 0.1.0 require?

**Comment by tkelman** [comment]
@mbauman ping?

**Comment by mbauman** [comment]
Right, sorry!  0.1.0 worked on 0.2.0, but I'll tag it starting with 0.3.

**Comment by mbauman** [comment]
Superseded by #5817

**Pull request closed without merging**
