### PR TITLE
Register new package Web3.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lambda-mechanics/Web3.jl](https://github.com/lambda-mechanics/Web3.jl)
Release: [v0.2.0](https://github.com/lambda-mechanics/Web3.jl/releases/tag/v0.2.0)
cc: @zot

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@zot This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Could the package name be changed to something more self explanatory?

**Comment by zot** [comment]
This is basically a Julia version of [web3.js](https://web3js.readthedocs.io/en/1.0/web3.html), which is the standard tool people use to connect DAPPS (Ethereum's decentralized applications) to the blockchain. I'll add that to the description.

I think any Ethereum programmer who wants to use Julia to interact with the blockchain will search for web3 first -- that's what I did.

**Comment by dpsanders** [comment]
OK thanks. But to anybody from outside that world, the name is mysterious.

**Comment by zot** [comment]
Yeah, it was a bad name choice for them but we're stuck with it -- the Ethereum project and a lot of people in the blockchain world see blockchain technology as forming the basis of a new, decentralized Web 3.0 and they reflected that in the (audacious) web3.js package name.

I'm pretty sure the people who need this package will look for it under this name :-/

**Comment by zot** [comment]
OK, I failed to follow directions and made another pull request instead of properly updating this one: #21205 so this one can be closed.

**Pull request closed without merging**
