### PR TITLE
Register new package LibCUDA.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [hshindo/LibCUDA.jl](https://github.com/hshindo/LibCUDA.jl)
Release: [v0.0.1](https://github.com/hshindo/LibCUDA.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/hshindo/LibCUDA.jl/builds/366272613)
cc: @hshindo

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@hshindo This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like this package is very similar to https://github.com/JuliaGPU/CuArrays.jl. Any reason to prefer a separate package?

**Comment by hshindo** [comment]
yes, it can run on windows.

**Comment by maleadt** [comment]
> yes, it can run on windows.

As does CuArrays.

**Comment by hshindo** [comment]
No, but I recognize CUDAnative, CUDAdrv, etc.
Eventually I'm happy to contribute to CuArrays.jl, but currently I need multi-threaded and custom memory management implementation for deep learning (and subarray support).

> As does CuArrays.

Thanks, I didn't know that.

**Comment by andreasnoack** [comment]
Closing because of no activity for a month.

**Pull request closed without merging**
