### PR TITLE
Bump Homebrew

### PR DESCRIPTION
**Pull request by jiahao**
Fix deprecation warning on 0.4

### CODE REVIEW

**Comment by tkelman** [comment]
Homebrew needs a Compat version requirement for pipe support

**Comment by jiahao** [comment]
Is there a way to look up which version of Compat is needed other than manually trawling the git history?

**Comment by tkelman** [comment]
https://github.com/JuliaLang/Compat.jl/commit/671c8326f3d6bc33a6148cf116efd2bc02a5ae92 has a handy view of which tags it's included in, looks like 0.3.0 is the oldest

**Comment by jiahao** [comment]
@tkelman Do you want to go ahead with your PR, fix the Compat versioning and retag? I'll close this.

**Pull request closed without merging**
