### PR TITLE
Tag CxxWrap.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaInterop/CxxWrap.jl](https://github.com/JuliaInterop/CxxWrap.jl)
Release: [v0.4.0](https://github.com/JuliaInterop/CxxWrap.jl/releases/tag/v0.4.0)
Diff: [vs v0.3.1](https://github.com/JuliaInterop/CxxWrap.jl/compare/3dc95c42b003ff62229eeb445d11f289e2afa2f2...41bc238c58e8638dabb0696f0c3618bc3aa97227)
`requires` vs v0.3.1: no changes
cc: @barche

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like this would break LCIO.jl? cc @jstrube, we could apply upper bounds for now until the downstream package can update

**Comment by SylvainCorlay** [comment]
@tkelman this is indeed a backward incompatible release (also, following semver).

**Comment by jstrube** [comment]
Thanks for pinging me. `REQUIRE` in LCIO.jl lists `CxxWrap 0.3 0.4-`, so I should be OK.

**Comment by tkelman** [comment]
whoops, forgot about that, you're right

**Pull request merged**
