### PR TITLE
Tag StructuredQueries v0.0.3 [https://github.com/davidagold/Structure…

### PR DESCRIPTION
**Pull request by davidagold**
…dQueries.jl]

### CODE REVIEW

**Comment by davidagold** [comment]
@tkelman Can this be merged now that we've made those additions to Compat? Or should it just wait for the next release of Compat? If the latter, when will that be?

**Comment by tkelman** [comment]
I'll tag Compat now.

**Comment by davidagold** [comment]
Much appreciated :)

**Comment by tkelman** [comment]
You're aware this broke your TablesDemo.jl, right? http://pkg.julialang.org/logs/TablesDemo_0.6.log

**Comment by davidagold** [comment]
✔️ thank you

**Pull request merged**
