### PR TITLE
Bump Interpolations and OffsetArrays

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by tkelman** [comment]
> `Base.fill(x, inds::Tuple{UnitRange,Vararg{UnitRange}})`

that method really shouldn't be extending `Base.fill` - would be fine as `OffsetArrays.fill` though

**Comment by tkelman** [comment]
If you're going to use DualNumbers in Interpolations, it should be in REQUIRE

**Comment by timholy** [comment]
Thanks. Hold off on this, looks like we weren't running Travis tests on 0.4, and it's not working.

> that method really shouldn't be extending Base.fill - would be fine as OffsetArrays.fill though

It's complicated. Methods are designed to dispatch by `indices` type. Base arrays handle `OneTo`, and packages handle non-1 arrays. OffsetArrays is the one package designed to work with `UnitRange` indices, all others specialize for their own internal indices. Since `UnitRange` is the fallback for `AbstractUnitRange` indices, it seems necessary to have a fallback corresponding array type available.

**Comment by timholy** [comment]
OK, I think this is fixed.

**Pull request merged**
