### PR TITLE
Provisional test tag of new NullableArray-backed DataFrames

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by tkelman** [comment]
this is explicitly do-not-merge-yet, right? I just meant the branch and commit, not the metadata pr if it isn't ready yet

**Comment by ararslan** [comment]
Correct. Do **not** merge yet.

**Comment by nalimilan** [comment]
What are you testing here exactly?

**Comment by quinnj** [comment]
This is just a dummy "release" pointed at current DataFrames master. Based on the discussion [here](https://github.com/JuliaStats/DataFrames.jl/issues/1092), this should allow Tony to run PkgEval as if DataFrames were tagged after the NA/CA overhaul.

**Comment by kmsquire** [comment]
This was set up and tested a while ago.  Should it be closed?  Cc: @quinnj

**Comment by ararslan** [comment]
> Should it be closed?

I assume we'll want to run PkgEval again at some point before the DataFrames release, in which case we could just update this PR rather than opening a new one.

**Pull request closed without merging**
