### PR TITLE
Tag ReadableNumbers.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArbTypes/ReadableNumbers.jl](https://github.com/JuliaArbTypes/ReadableNumbers.jl)
Release: [v0.1.0](https://github.com/JuliaArbTypes/ReadableNumbers.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArbTypes/ReadableNumbers.jl/builds/259718808)
Diff: [vs v0.0.3](https://github.com/JuliaArbTypes/ReadableNumbers.jl/compare/b89d74c589ffccdba2e757c2922be0e609146c37...76d206d269d858cadcc2535ca929446a0e4453c0)
`requires` vs v0.0.3: 
```diff
--- 0.0.3/requires
+++ 0.1.0/requires
@@ -1 +1 @@
-julia 0.5
+julia 0.6.0
```
cc: @JeffreySarnoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
I do not see the problem.

**Comment by tkelman** [comment]
we merged this tag already, please put the git tag back to its previous value and make a new tag

**Comment by JeffreySarnoff** [comment]
I posted v0.1.1 -- so do whatever is right with this

**Comment by tkelman** [comment]
metadata thinks the 0.1.0 tag is at f8e65d9f6d88ed71b84e0065772f701473d5edc2 so it would be good to put the git tag for 0.1.0 back to that for consistency

**Comment by tkelman** [comment]
same way you've been amending the v0.1.0 tag, just paste that commit for it instead of latest master

**Comment by tkelman** [comment]
perfect thanks

**Pull request merged**
