### PR TITLE
Tag AmplNLReader.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaSmoothOptimizers/AmplNLReader.jl](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl)
Release: [v0.2.0](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/releases/tag/v0.2.0)
Diff: [vs v0.1.0](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/compare/ec4c1f77562193e5b917218d45ac8e1f097bbe2a...5af4c4d1550ec496f02bb09e25b3ee74468537a3)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,5 +1,4 @@
-julia 0.4
+julia 0.6 0.7
 BinDeps
-Compat 0.7.15
 @osx Homebrew 0.4.0
 NLPModels 0.0.1 0.5.0
```
cc: @abelsiqueira

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Related: https://github.com/JuliaLang/METADATA.jl/pull/18099

**Comment by andreasnoack** [comment]
Just to confirm, you are okay with going from passing to failing on 0.6?

**Comment by abelsiqueira** [comment]
Yes

**Comment by abelsiqueira** [comment]
Thanks

**Pull request merged**
