### PR TITLE
Tag TimeSeries v0.5.2

### PR DESCRIPTION
**Pull request by milktrader**

### CODE REVIEW

**Comment by jiahao** [comment]
I don't understand why Travis has consistently [complained about @milktrader's recent pull requests](https://travis-ci.org/JuliaLang/METADATA.jl/pull_requests) (and @mlubin's is the only other one who gets complaints). There appears to be nothing wrong with the actual tag data.

**Comment by milktrader** [comment]
Good question. @IainNZ noticed I'm deleting the branch too quickly, but in this case it's still there.

**Comment by milktrader** [comment]
Here is the log where the error happens:

````bash
[0K$ git fetch origin +refs/pull/2183/merge:
fatal: Couldn't find remote ref refs/pull/2183/merge

[31;1mThe command "eval git fetch origin +refs/pull/2183/merge:" failed. Retrying, 2 of 3.[0m

fatal: Couldn't find remote ref refs/pull/2183/merge

[31;1mThe command "eval git fetch origin +refs/pull/2183/merge:" failed. Retrying, 3 of 3.[0m

fatal: Couldn't find remote ref refs/pull/2183/merge

[31;1mThe command "eval git fetch origin +refs/pull/2183/merge:" failed 3 times.[0m

travis_time:end:1317d196:start=1424493109359575130,finish=1424493112571599930,duration=3212024800
[0K
[31;1mThe command "git fetch origin +refs/pull/2183/merge:" failed and exited with 128 during .[0m

Your build has been stopped.
````

Also, I restarted 4956 to maybe it passes the second time?

**Comment by milktrader** [comment]
Also (this might be relevant), I'm not doing anything manually but instead the following


````julia
Pkg.update()
Pkg.tag("TimeSeries", :patch)
Pkg.publish()
````

**Pull request merged**
