### PR TITLE
Update requires

### PR DESCRIPTION
**Pull request by montyvesselinov**
0.5 added in require

### CODE REVIEW

**Comment by tkelman** [comment]
I suspect you'll also need to change https://github.com/montyvesselinov/METADATA.jl/edit/patch-1/ReusableFunctions/versions/0.2.0/requires in this same branch for the travis version check to pass here.

**Comment by montyvesselinov** [comment]
this was fixed

**Comment by tkelman** [comment]
No it wasn't. Not in this branch, or you didn't open a PR for it.

**Comment by montyvesselinov** [comment]
Maybe i did not do PR. what should I do?

-monty

**Comment by tkelman** [comment]
nevermind, as long as https://github.com/JuliaLang/METADATA.jl/pull/8384/commits/9c9eb940592ae848124480c363978260b82d1f64 is what you were going for, I handled it

**Comment by montyvesselinov** [comment]
Thank you very much!

**Pull request merged**
