### PR TITLE
Tag GridInterpolations.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [sisl/GridInterpolations.jl](https://github.com/sisl/GridInterpolations.jl)
Release: [v0.1.0](https://github.com/sisl/GridInterpolations.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/sisl/GridInterpolations.jl/builds/254632314)
Diff: [vs v0.0.2](https://github.com/sisl/GridInterpolations.jl/compare/c1ce4c039ab6ce455b5b6297617da7281ad9d54d...652a3f788a5a8439aa18f2b127c05cdf353afa37)
`requires` vs v0.0.2: 
```diff
--- 0.0.2/requires
+++ 0.1.0/requires
@@ -1,2 +1 @@
-julia 0.4
-Grid
+julia 0.6
```
cc: @MaximeBouton

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by MaximeBouton** [comment]
Hey,
we are not sure why the build is failing. It seems to be tag related, do you have any hint on what is going on?
Thanks

**Comment by aviks** [comment]
can you verify the tag using the git command line? For example, can you checkout your repository at the tag `v0.1.0`?

**Comment by MaximeBouton** [comment]
Yes I can checkout the tag v0.1.0 , there is actually another tag v0.1 that we made by mistake. Can this be the cause? 
I will delete the v0.1 and keep the v0.1.0.

**Comment by tkelman** [comment]
Yes, deleting the non-semver 0.1 tag would be the fastest solution

**Comment by MaximeBouton** [comment]
Thank you, I deleted it, should we re-submit the PR or can we restart the build?

**Pull request merged**
