### PR TITLE
Tag Planets.jl v0.4.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [dcarrera/Planets.jl](https://github.com/dcarrera/Planets.jl)
Release: [v0.4.1](https://github.com/dcarrera/Planets.jl/releases/tag/v0.4.1)
Diff: [vs v0.2.0](https://github.com/dcarrera/Planets.jl/compare/2f29426688374b96708a7b734123abb0944fa756...dcf981a3dae736171239ab27d0d262b31d0ce11d)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.4.1/requires
@@ -1,4 +1,4 @@
-julia 0.7
+julia 1.0
 DataFrames
 Missings
-CSV
+CSV 0.4.2
```
cc: @dcarrera

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dcarrera** [comment]
Something's wrong. Even after 9 hours, when I type `] add Planets` or `] update Planets` in Julia 1.0, I still get only the old version 0.2.0. The packaging system is ignoring the new version.

**Comment by andreasnoack** [comment]
I can confirm this. However, the new version is registered in https://github.com/JuliaRegistries/General/blob/master/P/Planets/Versions.toml. We are looking into the issue.

**Comment by andreasnoack** [comment]
I had a local issue which prevented my local registry from being updated. What do you get from `] add Planets@v0.4.1`?

**Comment by dcarrera** [comment]
```
(v1.0) pkg> add Planets@v0.4.1
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Planets [e3f94f68]:
 Planets [e3f94f68] log:
 ├─possible versions are: [0.2.0, 0.4.1] or uninstalled
 ├─restricted to versions 0.4.1 by an explicit requirement, leaving only versions 0.4.1
 └─restricted by compatibility requirements with CSV [336ed68f] to versions: 0.2.0 or uninstalled — no versions left
   └─CSV [336ed68f] log:
     ├─possible versions are: 0.4.1 or uninstalled
     └─CSV [336ed68f] is fixed to version 0.4.1
```

I think I know what's happening. A few months ago I hit a bug in CSV 0.4.1 so I changed `Project.toml` file to require version 0.4.2:

```
[compat]
CSV = "0.4.2"
```

For some reason it looks like my CSV installation is fixed at 0.4.1 so that would not meet the requirements for `Planets.jl`. I can't figure out why CSV is fixed at 0.4.1 though.

**Comment by andreasnoack** [comment]
Try `] free CSV` and if that doesn't help then try `up CSV` and see what is reported.

**Comment by dcarrera** [comment]
That worked!

```
(v1.0) pkg> free CSV
 Resolving package versions...
 Installed CSV ─ v0.4.3
  Updating `~/.julia/environments/v1.0/Project.toml`
  [336ed68f] ↑ CSV v0.4.1 #master (git@github.com:JuliaData/CSV.jl.git) ⇒ v0.4.3
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [336ed68f] ↑ CSV v0.4.1 #master (git@github.com:JuliaData/CSV.jl.git) ⇒ v0.4.3
  [9abbd945] + Profile 

(v1.0) pkg> add Planets@v0.4.1
 Resolving package versions...
 Installed Planets ─ v0.4.1
  Updating `~/.julia/environments/v1.0/Project.toml`
  [e3f94f68] ↑ Planets v0.2.0 ⇒ v0.4.1
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [e3f94f68] ↑ Planets v0.2.0 ⇒ v0.4.1
```

Can you explain what happened? Is this going to be a problem for other people? Thanks!

**Pull request merged**
