### PR TITLE
Tag Fontconfig v0.0.3

### PR DESCRIPTION
**Pull request by tlnagy**
This adds:

- basic testing support
- installation and linking of the libfontconfig binary across platforms
- various bug fixes for v0.5
- drops 0.3 support

Thanks @tkelman and @ararslan for the help!

### CODE REVIEW

**Comment by ararslan** [comment]
Since you're bumping the required Julia version, you'll have to tag this as a minor release rather than a patch. That's why Travis is failing.

**Comment by tlnagy** [comment]
Ah. So should I delete the tag and re-tag it?

**Comment by ararslan** [comment]
Yep

**Comment by tlnagy** [comment]
I'm running into this now: https://github.com/JuliaLang/PkgDev.jl/issues/81

**Pull request closed without merging**
