### PR TITLE
Tag CLBlast.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGPU/CLBlast.jl](https://github.com/JuliaGPU/CLBlast.jl)
Release: [v0.2.0](https://github.com/JuliaGPU/CLBlast.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGPU/CLBlast.jl/builds/423939413)
Diff: [vs v0.1.0](https://github.com/JuliaGPU/CLBlast.jl/compare/f741e630dc0200a4ef429104f2e1c8a47828d139...e05232eee30c8c9d92d38b08165c8b929e0d23e1)
`requires` vs v0.1.0: no changes
cc: @ranocha

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Are all the test errors expected?

**Comment by ranocha** [comment]
I don't know much about JuliaCIBot. It seems it is running Julia on Linux. Due to some binary incompatibility between Julia and the published binaries of CLBlast (where CLBlast.jl is built on), we have to build CLBlast on Linux using clang, which does not seem to be installed for the tests of JuliaCIBot. Can we install clang additionally?

We have tests on gitlab (https://gitlab.com/JuliaGPU/CLBlast.jl/pipelines/29286903) and AppVeyor (https://ci.appveyor.com/project/ranocha/clblast-jl/build/63). These pass for Julia `v0.6` and `v0.7`. On Julia `v0.7`, they fail since OpenCL.jl is not updated yet. The tests on Travis fail sometimes due to some strange OpenCL errors that do not seem to be reproducible everytime.

**Comment by andreasnoack** [comment]
Thanks for the clarification. I was referring to the errors in https://travis-ci.org/JuliaGPU/CLBlast.jl/builds/423939413.

**Comment by ranocha** [comment]
Thanks for asking and merging!

**Pull request merged**
