### PR TITLE
Tag Weave.jl v0.6.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [mpastell/Weave.jl](https://github.com/mpastell/Weave.jl)
Release: [v0.6.2](https://github.com/mpastell/Weave.jl/releases/tag/v0.6.2)
Travis: [Travis Build Status](https://travis-ci.org/mpastell/Weave.jl/builds/419495540)
Diff: [vs v0.6.1](https://github.com/mpastell/Weave.jl/compare/aa4ba7ed52ad571411f3d1b79c4521669f97925b...bf57bf8a0717b035afeb030799beb763113a2c2f)
`requires` vs v0.6.1: no changes
cc: @mpastell

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider removing the Project.toml file from your package since it is not yet needed and it currently causes issues for our reverse dependency testing.

**Comment by mpastell** [comment]
Could you merge this if I remove project.toml from the next release?

**Comment by andreasnoack** [comment]
Unless you have special reasons to keep it for this release, I'd suggest that you remove it now and retag this release, i.e. delete and reapply the same release tag. That will automatically update this PR.

**Comment by andreasnoack** [comment]
We should now be able to handle project files

**Pull request merged**
