### PR TITLE
Register IDRs:v0.1

### PR DESCRIPTION
**Pull request by mschauer**

### CODE REVIEW

**Comment by milktrader** [comment]
Any tests planned? Also wondering if we could avoid an acronym name here.

**Comment by tkelman** [comment]
`julia 0.4` won't work until it gets released. Would also strongly prefer a longer name here.

**Comment by mschauer** [comment]
InducedDimensionReduction would be possible. Is it still such a pain to rename a package?

**Comment by milktrader** [comment]
I think renaming is more of a cumbersome task once the package is in METADATA, but renaming the actual repo (and package) is fairly straight-forward with github.

**Comment by mschauer** [comment]
See #2919.

**Pull request closed without merging**
