### PR TITLE
Tag DataDeps.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [oxinabox/DataDeps.jl](https://github.com/oxinabox/DataDeps.jl)
Release: [v0.2.0](https://github.com/oxinabox/DataDeps.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/oxinabox/DataDeps.jl/builds/329561454)
Diff: [vs v0.1.0](https://github.com/oxinabox/DataDeps.jl/compare/ad36413e42939adc37f9b1d5dcd1a79ccf6fc97f...1d419bc7c799278a030f1e2f102dc7cf915743fc)
`requires` vs v0.1.0: no changes
cc: @oxinabox

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Tests seem to fail for the new tag?

**Comment by oxinabox** [comment]
hmm the 0.7 fails I was expecting.
The Mac fail I was not (travis mac has been really bad lately).

It could be a legit failure, it is on the code added in 
https://github.com/oxinabox/DataDeps.jl/pull/22
which was a giant hack.

I may have to add a HTTP dependency an do that right.  I also may have to go run julia on a Mac...

**Comment by oxinabox** [comment]
It isn't actually a legit failure.
Problem is that Travis CI only has a small number of mac build servers.
And that test hits the GitHub API.
which has a rate limit, that I guess someone other than me has exceeded.

I'm going to change that test to point at some other site.

**Comment by oxinabox** [comment]
Test changed,
might as well skip this release,
or merge it and them immediately merge 0.2.1 in #13140 

They are different, but API wise they are basically identical (0.2.1 works in a few places this 0.2.0 crashes and burns)

**Comment by martinholters** [comment]
IIUC correctly, this can be closed as #13140 has been merged? (Please report back if I misunderstood.)

**Pull request closed without merging**
