### PR TITLE
Register new package Boot.jl v0.0.1

### PR DESCRIPTION
**Pull request by djsegal**
Repository: [djsegal/Boot.jl](https://github.com/djsegal/Boot.jl)
Release: [v0.0.1](https://github.com/djsegal/Boot.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/djsegal/Boot.jl)
cc: @djsegal

-----

notes:

+ tool for loading subdirectories within packages
+ related to: [Discourse #7652 (Packages, modules, and files)](https://discourse.julialang.org/t/packages-modules-and-files/7652/3)

### CODE REVIEW

**Comment by KristofferC** [comment]
If you copy code written by other authors you need to comply with the license that code is under. 

It is also not advisable to include files programmatically because it prevents any sort of static analysis. Deleting methods are also not supported by Julia so this can corrupt the method cache. 

We already have a standard method of loading packages. Changing this break assumptions tools have so I don't think it is in the community's interest to have this registered.

**Comment by djsegal** [comment]
> If you copy code written by other authors you need to comply with the license that code is under.

What does this mean? What license did I break? (The delete_method is the only copied thing)

-----

> Deleting methods are also not supported by Julia so this can corrupt the method cache.

Then why does Revise.jl do it?

-----

> I don't think it is in the community's interest to have this registered.

Why does your opinion on sharp knives seem to always dictate everything in the community?

-----

Excerpt from the [Rails Doctrine](http://rubyonrails.org/doctrine#provide-sharp-knives) about Sharp Knives:

+ >Because it’s always about other programmers when the value of sharp knives is contested. I’ve yet to hear a single programmer put up their hand and say “I can’t trust myself with this power, please take it away from me!”. It’s always “I think other programmers would abuse this”. That line of paternalism has never appealed to me.

**Comment by KristofferC** [comment]
> What does this mean? What license did I break? (The delete_method is the only copied thing)

What license is the code you copied under? 

> Then why does Revise.jl do it? 

Revise.jl does not support deleting methods.

> Why does your opinion on sharp knives seem to always dictate everything in the community?

I am sorry you feel that way. If you feel you are being treated unjustly, I would recommend getting in touch with the community stewards (https://julialang.org/community/stewards/).

**Comment by timholy** [comment]
> Then why does Revise.jl do it?

Revise doesn't do it. The code you copied is on an unmerged branch. The branch wasn't merged because it doesn't work properly.

**Comment by djsegal** [comment]
Ok. Closing this sounds like the appropriate move for now then.

Bootloading is a feature that people will continue to ask for though. And it should be seen as more of a necessity than a nicety

**Pull request closed without merging**
