### PR TITLE
Tag ProteinEnsembles.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jgreener64/ProteinEnsembles.jl](https://github.com/jgreener64/ProteinEnsembles.jl)
Release: [v0.2.0](https://github.com/jgreener64/ProteinEnsembles.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/jgreener64/ProteinEnsembles.jl/builds/445040510)
Diff: [vs v0.1.1](https://github.com/jgreener64/ProteinEnsembles.jl/compare/1caf42ad0c29a0937f9f4c9996a9b50e07cab507...34063f8ff72635e4f4a3b9013c0b073e6c3eaca0)
`requires` vs v0.1.1: 
```diff
--- 0.1.1/requires
+++ 0.2.0/requires
@@ -1,6 +1,6 @@
-julia 0.5
+julia 0.7
 ArgParse
 ProgressMeter
-Gadfly 0.6
+Gadfly
 Colors
 Cairo
```
cc: @jgreener64

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by jgreener64** [comment]
Anything in particular stopping this from being merged? Thanks.

**Comment by andreasnoack** [comment]
Yes. The tests are failing. Please take a the logs and identify why they are failing.

**Comment by jgreener64** [comment]
I think this is because I do some custom setup before running the tests on travis: https://github.com/jgreener64/ProteinEnsembles.jl/blob/master/.travis.yml

Is there any way to do this custom setup on JuliaCIBot, or otherwise to exclude the package from being tested?

**Comment by andreasnoack** [comment]
Why don't you install TMScore with a `build.jl` file as you normally would do with a binary dependency?

**Comment by jgreener64** [comment]
So the tests now pass on Julia 1.0 but there seems to be a problem on 0.7. The link to the 0.7 build log seems to not exist though? So I don't know what's wrong.

**Comment by jgreener64** [comment]
Thanks for the help with this.

**Pull request merged**
