### PR TITLE
Tag Turing v0.2.0 [https://github.com/yebai/Turing.jl]

### PR DESCRIPTION
**Pull request by xukai92**

### CODE REVIEW

**Comment by yebai** [comment]
The list of PRs that we created in this release

https://github.com/yebai/Turing.jl/milestone/2?closed=1

Well done!

**Comment by tkelman** [comment]
Any code that has been copied from other projects (e.g. ASCIIPlots) needs to follow the terms of those projects' licenses.

**Comment by xukai92** [comment]
@tkelman How can I make update? Should tag the new one and create a new PR or something?

**Comment by tkelman** [comment]
You can modify the PR branch of your metadata fork in place. Or I recommend using https://github.com/attobot/attobot

**Comment by tkelman** [comment]
replaced by https://github.com/JuliaLang/METADATA.jl/pull/8945

**Pull request closed without merging**
