### PR TITLE
InspectDR: Efficient/interactive Julia/Gtk plots

### PR DESCRIPTION
**Pull request by ma-laforge**
Yes... another plot tool.

I tried using other plot tools for as long as I could hold out, but I need more interactivity & better overall response from the GUI.

InspectDR is not very polished yet, but I think it is still a good Julia package - even in its current state.

MA

### CODE REVIEW

**Comment by ma-laforge** [comment]
I think something might have gone wrong with how this PR was constructed.

Before registering InspectDR, I tried updating my Github fork of METADATA using:
`git pull origin metadata_v2 #succeeded`
`git push ma-laforge metadata_v2 #failed`

But this failed.  Apparently my github fork changed when I initiated the pull request because git could not "fast forward" to match my local copy.

To circumvent this, I then did:
`git pull ma-laforge metadata_v2`

which I proceeded to commit, followed by a:
`git push ma-laforge metadata_v2 #Succeeded`

...Now it looks like the current PR includes last month's PR...

If you can tell me what I did wrong, I will try to fix it.

MA

**Comment by tkelman** [comment]
You would have to rebase out the unrelated commits.

**Comment by tbreloff** [comment]
I think you could also cherry pick the good one(s).  Checkout
origin/metadata-v2 and then "git cherry-pick <commit_sha>" of the good
commit, then push to your fork. I did this for my recent tags and it seemed
to work ok.

**Comment by ma-laforge** [comment]
@tkelman 
The rebase operation cleaned up my local repo - no problem.
...But I still could not push to to my github repo:

```
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
@tbreloff: I could not figure out hot to get things done with cherry-pick.

I think the solution would be to have merged/rebased on JuliaLang/METADATA directly from my github page (don't know how to do this).

...So I instead deleted the non-compliant metadata-v2 branch from the github page, then re-pushed from my local repo.  This seems to have worked (though thoroughly ugly).

I hope nothing broke... Will make a new PR soon...

**Comment by tkelman** [comment]
Just need `--force` when you push over the branch. Don't do that over any remote branch you care about, but it's fine for overwriting a branch you don't want any more as long as you've checked that your local state looks good.

**Comment by ma-laforge** [comment]
Thanks for that.  I am a bit scared of using --force.  I don't fully understand when it is safe to use.

**Comment by tkelman** [comment]
It's not safe to use if you want to keep the existing remote content of the branch that you're pushing to. If you're worried, you can make a backup copy of the existing branch under a new name first, then force push over the old name.

**Comment by ma-laforge** [comment]
Oh, so.. it basically similar to overwriting a file that you might want to keep...

Except that people might be working off that file/pointing to it, and will have to re-start all their merging process manually after a force push... (really wish I could find a lightsaber emoji).

Hmmm.

**Pull request closed without merging**
