### PR TITLE
Tag POMDPModels.jl v0.3.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPOMDP/POMDPModels.jl](https://github.com/JuliaPOMDP/POMDPModels.jl)
Release: [v0.3.2](https://github.com/JuliaPOMDP/POMDPModels.jl/releases/tag/v0.3.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPOMDP/POMDPModels.jl/builds/428905395)
Diff: [vs v0.3.1](https://github.com/JuliaPOMDP/POMDPModels.jl/compare/63e4e2e6c51ffad7298fc747df99a49ff3440e70...855c671f47ab5ce7d87df50693c720d3669b75e1)
`requires` vs v0.3.1: no changes
cc: @zsunberg

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like this breaks ReinforcementLearningEnvironmentDiscrete

**Comment by zsunberg** [comment]
ReinforcementLearningEnvironmentDiscrete is fixed with this commit: https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironmentDiscrete.jl/commit/6f777494e2d95e851a0402acdb2a2058ab76186a

They just haven't tagged a new version yet.

cc: @jbrea

**Comment by andreasnoack** [comment]
Would you like this to be merged or would you allow them some more time to prepare a release?

**Comment by zsunberg** [comment]
We'd rather merge it, please!

**Comment by jbrea** [comment]
Sorry, I wasn't aware that I held back this PR.
I tagged a new version now (see #18074).

**Comment by zsunberg** [comment]
@jbrea No worries! Thank you!

**Pull request merged**
