### PR TITLE
Tag ZMQ.jl v1.0.0 — don't merge without IJulia update

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaInterop/ZMQ.jl](https://github.com/JuliaInterop/ZMQ.jl)
Release: [v1.0.0](https://github.com/JuliaInterop/ZMQ.jl/releases/tag/v1.0.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaInterop/ZMQ.jl/builds/424146829)
Diff: [vs v0.6.4](https://github.com/JuliaInterop/ZMQ.jl/compare/304f2970c52d6d5642cc37b30c23d74f4c2a9168...360f80ce603477308c52878869579476e6e74316)
`requires` vs v0.6.4: 
```diff
--- 0.6.4/requires
+++ 1.0.0/requires
@@ -1,3 +1,2 @@
-julia 0.6
-Compat 0.68.0
+julia 0.7
 BinaryProvider 0.3.0
```
cc: @stevengj

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by stevengj** [comment]
Please don't merge this without also merging a new IJulia tag with JuliaLang/IJulia.jl#729 in order to support the new API.

**Comment by stevengj** [comment]
In particular, merge this one only when you are ready to merge #17670.

**Comment by stevengj** [comment]
CI seemed stuck again.  Merging this and the IJulia update in order to give people a (hopefully) working version to use on Windows.

**Comment by andreasnoack** [comment]
Yes. For some reason, the reverse dependency testing seemed to get stuck when testing https://github.com/JuliaWeb/JuliaWebAPI.jl so it might be a good idea to verify that it still works. cc @tanmaykm

**Comment by stevengj** [comment]
I get a JuliaWebAPI test failure locally (JuliaWeb/JuliaWebAPI.jl#68), but it also occurs for ZMQ 0.6 so I think it is unrelated.  (It runs a bunch of other tests first, which pass.)

(I looked through the JuliaWebAPI usage of ZMQ and it seemed fine, not even any deprecated usages, although they might want to switch to the new low-overhead API if their messages are small enough that a copy is okay.  IJulia ran into trouble because it used an undocumented internal field of `ZMQ.Socket`.)

**Pull request merged**
