### PR TITLE
Update to latest changes in DataFrames

### PR DESCRIPTION
**Pull request by andreasnoack**
With version 0.11.4 of `DataFrames` this version of `RDatasets` works again

### CODE REVIEW

**Comment by nalimilan** [comment]
Funny, I've just pushed a branch to do the same thing. I think you can drop the DataArrays dependency altogether since it's not used at all in RDatasets. Also, I wouldn't add an upper bound on DataFrames 1.0: if we do that, we should apply that change to all packages. Doing this only for one package can only create confusion.

**Comment by nalimilan** [comment]
Cc: @randyzwitch

**Comment by andreasnoack** [comment]
I think we should start to add upper bounds on major versions generally such that we don't need to do it retrospectively in METADATA.

**Comment by nalimilan** [comment]
> I think we should start to add upper bounds on major versions generally such that we don't need to do it retrospectively in METADATA.

I think Pkg3 has a mechanism to handle this (e.g. https://github.com/JuliaLang/Juleps/issues/3). In the meantime, better only apply minimal changes.

**Comment by randyzwitch** [comment]
Thanks for pinging me on this. This change makes the tests for the current RDatasets work, without needing the CSV fixes? Or is this PR https://github.com/johnmyleswhite/RDatasets.jl/pull/48 separately needed?

**Comment by nalimilan** [comment]
The tests already work with DataFrames 0.11.4, this PR just allows the package manager to upgrade DataFrames to 0.11.4 when RDatasets is installed. johnmyleswhite/RDatasets.jl#48 will still be needed to silence the deprecation warnings (and to ensure the package will work once deprecations are removed from DataFrames).

**Comment by randyzwitch** [comment]
So do I need to tag a new version of RDatasets with REQUIRES DataFrames 0.11, to override the current METADATA cap of 0.10?

**Comment by nalimilan** [comment]
It would make sense to update REQUIRE in the RDatasets repo to match the one in this PR, but no need to tag a new release.

**Comment by randyzwitch** [comment]
Sorry, I didn't look at what this PR was actually doing. Now I see that it's fixing RDatasets versioning on METADATA, not changing DataFrames.jl. Got it now.

**Comment by andreasnoack** [comment]
> So do I need to tag a new version of RDatasets with REQUIRES DataFrames 0.11, to override the current METADATA cap of 0.10?

@randyzwitch No, it shouldn't be necessary to tag `RDatasets` now. You can just wait until https://github.com/johnmyleswhite/RDatasets.jl/pull/48 has been merged. However, Before tagging a new version you should add `DataFrames 0.11.4 1.0.0` to the `REQUIRE` file.

@nalimilan The current approach where the person who happens to tag a package which other depends on has to add (possibly unnecessary) upper bounds on all the dependent packages or check all the packages one-by-one is so broken that anything else is better than that. There is almost zero chance that this `1.0.0` upper bound will have an effect though.

**Comment by nalimilan** [comment]
> @nalimilan The current approach where the person who happens to tag a package which other depends on has to add (possibly unnecessary) upper bounds on all the dependent packages or check all the packages one-by-one is so broken that anything else is better than that. There is almost zero chance that this 1.0.0 upper bound will have an effect though.

I agree on the goal, but please apply this to all DataFrames dependency, or to none. Having spent a full afternoon on adding these bounds, I'm aware the current system is far from ideal, but let's not make it even less consistent.

**Comment by nalimilan** [comment]
@andreasnoack I've pushed changes, is that OK with you?

**Comment by randyzwitch** [comment]
Thanks everyone

**Pull request merged**
