### PR TITLE
Tag AmplNLReader.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaSmoothOptimizers/AmplNLReader.jl](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl)
Release: [v0.2.1](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/releases/tag/v0.2.1)
Diff: [vs v0.1.0](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/compare/ec4c1f77562193e5b917218d45ac8e1f097bbe2a...5af4c4d1550ec496f02bb09e25b3ee74468537a3)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.1/requires
@@ -1,5 +1,4 @@
-julia 0.4
+julia 0.6 0.7
 BinDeps
-Compat 0.7.15
 @osx Homebrew 0.4.0
-NLPModels 0.0.1
+NLPModels 0.0.1 0.5.0
```
cc: @abelsiqueira

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dpo** [comment]
Not sure why the JuliaCIBot is testing Julia ≥ 0.6 if we have set an upper bound?!

**Comment by abelsiqueira** [comment]
True, though I think these are allowed fails.
However, it is running 0.6 on Linux, and thus is failing for 'new'. But we don't intend to support Linux 0.6 anymore. Any way to mark that?

**Comment by andreasnoack** [comment]
This was not what I meant in https://github.com/JuliaLang/METADATA.jl/pull/17800#issuecomment-422081556. Please check the PR that I linked to. You should just add an upper bound on NLPModels in https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/AmplNLReader/versions/0.1.0/requires. I'll close this PR. Please delete the tag 0.2.1 tag in the ApmlNLReader repo.

**Comment by dpo** [comment]
AmplNLReader is only failing because of NLPModels for anecdotal reasons. The C interface breaks on certain Linux machines with Julia 0.6 (and not 0.7) but we haven't been able to determine the cause. Tag 0.2.1 removes support for the Linux / Julia 0.6 combination. Linux support will return together with Julia 0.7 support.

**Comment by andreasnoack** [comment]
Okay. Please remove and reapply the tag if you still want to release this version. (Btw why 0.2.1 when the previous version was 0.1.0?)

**Comment by abelsiqueira** [comment]
v0.2.0: https://github.com/JuliaLang/METADATA.jl/pull/16242

We could delete both and re-release 0.2.0. @dpo is that ok?

**Comment by andreasnoack** [comment]
Yes. It usually preferred to update tags that haven't been released to METADATA.

**Comment by dpo** [comment]
Sure, that sounds good. Thanks both.

**Pull request closed without merging**
