### PR TITLE
Tag NumericIO v0.2.1 [https://github.com/ma-laforge/NumericIO.jl]

### PR DESCRIPTION
**Pull request by ma-laforge**
Finalize compatibility with v0.6.0.

Diff vs v0.2.0: https://github.com/ma-laforge/NumericIO.jl/compare/e2a051ccac7786972060209b71d88d416aa5ab4c...a36b0b4131316d7b60aa410122d60d86fc88d60d

### CODE REVIEW

**Comment by ma-laforge** [comment]
Questions:

 - Why are Travis tests still pending if the tests have passed??
 - JuliaCIBot indicates that one of the dependencies of `NumericIO` (InspectDR) is failing due to `Gtk.jl` not being able open a display.  Is there a new step to getting a green checkmark with packages that depend on Gtk?

Thanks.

**Comment by andreasnoack** [comment]
Not sure why. I've restarted the tests.

**Comment by ma-laforge** [comment]
Thanks.  That worked.

I suppose I will have to figure out what is keeping the InspectDR package from being tested (Issue with Travis opening a display) once this PR gets merged.

**Comment by andreasnoack** [comment]
Please consider using Attobot in the future

**Pull request merged**
