### PR TITLE
Tag SCIP.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [SCIP-Interfaces/SCIP.jl](https://github.com/SCIP-Interfaces/SCIP.jl)
Release: [v0.4.0](https://github.com/SCIP-Interfaces/SCIP.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/SCIP-Interfaces/SCIP.jl/builds/263030629)
Diff: [vs v0.3.0](https://github.com/SCIP-Interfaces/SCIP.jl/compare/f04b314a293511a441e3792d2cf0210d582c0189...7311b2bc868866036759d75d11fb9eb5a3afdd37)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -1,4 +1,4 @@
-julia 0.5
+julia 0.6
 BinDeps
 MathProgBase 0.5 0.7
 Compat 0.8.6
```
cc: @leethargo

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by leethargo** [comment]
We require that `SCIP` is downloaded and built before `SCIP.jl` is installed/built. This is part of the config for TravisCI, but how can I tell JuliaCIBot about it?

**Comment by tkelman** [comment]
What was the reason deps/build.jl doesn't download and build scip itself?

**Comment by leethargo** [comment]
It's a licensing issue: [ZIB academic license](http://scip.zib.de/academic.txt). Basically, when automatically installing SCIP, we would be distributing it, and that requires keeping track of downloads.

**Comment by tkelman** [comment]
It looks like you re-tagged the same 7311b2bc868866036759d75d11fb9eb5a3afdd37 commit a second time, was that intentional? Note that you have to delete both the github release and the git tag, two separate steps, before replacing it for attobot to update to a newer commit.

**Comment by leethargo** [comment]
Hm, I forgot to delete the git tag when I wanted to add the last commit. Let me do it over.

**Comment by leethargo** [comment]
Thanks!

**Pull request merged**
