### PR TITLE
Tag ArgCheck.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jw3126/ArgCheck.jl](https://github.com/jw3126/ArgCheck.jl)
Release: [v0.5.0](https://github.com/jw3126/ArgCheck.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/jw3126/ArgCheck.jl/builds/339765059)
Diff: [vs v0.4.2](https://github.com/jw3126/ArgCheck.jl/compare/08ec44ee368a762fce86f3ec2c72ca2de3268488...b7b42c3aaece8ddc8f50f11239fc9411463d5537)
`requires` vs v0.4.2: no changes
cc: @jw3126

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like there is an issue with the remote tags

**Comment by jw3126** [comment]
I think I have fixed it, can you rerun CI?

**Comment by andreasnoack** [comment]
Errors seem to be an issue with JuliaCIBot

**Comment by jw3126** [comment]
Thanks!

**Pull request merged**
