### PR TITLE
Tag BackpropNeuralNet v0.1.0

### PR DESCRIPTION
**Pull request by compressed**

### CODE REVIEW

**Comment by tkelman** [comment]
If the previous tags supported julia 0.3, then this tag should use a new minor version number 0.1.0

**Comment by compressed** [comment]
@tkelman agreed!

I've rebased this now.

**Comment by tkelman** [comment]
the package itself should really add a top level REQUIRE file

**Comment by compressed** [comment]
Oh good point, let me take care of that. Thanks.

**Pull request merged**
