### PR TITLE
Tag CSTParser.jl v0.3.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ZacLN/CSTParser.jl](https://github.com/ZacLN/CSTParser.jl)
Release: [v0.3.5](https://github.com/ZacLN/CSTParser.jl/releases/tag/v0.3.5)
Travis: [Travis Build Status](https://travis-ci.org/ZacLN/CSTParser.jl/builds/328662399)
Diff: [vs v0.3.4](https://github.com/ZacLN/CSTParser.jl/compare/f7098037108f831af3d73075381a3e95132267e4...57a60fbb7cfe2dd049c914929d4dbc0d58c81d35)
`requires` vs v0.3.4: no changes
cc: @ZacLN

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
This breaks LanguageServer?

**Comment by ZacLN** [comment]
I'll add required upper bounds to relevant versions

**Comment by ZacLN** [comment]
restarted CIBot should pass now

**Comment by davidanthoff** [comment]
I just opened a PR that adds the required upper bounds to LanguageServer, see #12890. The JuliaCIBot tests here should work once that is merged.

**Comment by KristofferC** [comment]
Doesn't seem like JuliaCI reran but I confirmed locally that LanguageServer upper bounds are working.

**Pull request merged**
