### PR TITLE
Register Rotations: v0.0.1, v0.1.0

### PR DESCRIPTION
**Pull request by awbsmith**
Pull request to add a rotations package for handling 3D rotation parametrizations and conversions between them.

Parametrizations included are:
rotation matrices
quaternions
angle axis representations
stereographic quaternion projections (a 3 parameter representation of a unit quaternion)
Euler angles (Tait-Bryan ordering e.g. XYZ)
proper Euler angles (proper euler ordering e.g. XYX)

### CODE REVIEW

**Comment by timholy** [comment]
See also
https://github.com/timholy/AffineTransforms.jl
https://github.com/JuliaGeometry/Quaternions.jl

Any chance to combine efforts?

**Comment by awbsmith** [comment]
I'm always happy to combine efforts. If the Julia Geometry people like the
package I'd be happy to move / transfer ownership or whatever works.

The Quaternions used in this package are imported from Quaternions.jl (for
better or for worse)

On AffineTransforms, there will be an issue where I'm using
FixedSizeArrays.Mat{3,3,T} for rotation matrices which is a bit scary and
consistent with the rest of AffineTransforms.  Do you think the author of
AffineTransforms would be interested in integrating them?

**Comment by tkelman** [comment]
If you enabled Travis CI, would your tests pass there?

**Comment by awbsmith** [comment]
Yes for release Julia, no for nightly Julia

**Comment by awbsmith** [comment]
A note that a dependency (FixedSizeArrays.jl) isn't passing nighties

**Comment by tkelman** [comment]
You can set nightly as an allowed failure in the meantime. That way it'll run so you can see the results, but it won't make the status red.

**Comment by awbsmith** [comment]
Thats great thanks.  I added the build image to the readme while I was at it

**Comment by awbsmith** [comment]
Thanks

**Comment by timholy** [comment]
Ah, just noticed this, sorry for not responding earlier.

> Do you think the author of AffineTransforms would be interested in integrating them?

As the author of AffineTransforms, I can answer that question! I think integrating would be good. AffineTransforms was written before FixedSizeArrays existed, so it used other tricks. Assuming the two can be combined, I'd rather use FixedSizeArrays.

**Pull request merged**
