### PR TITLE
Viridis

### PR DESCRIPTION
**Pull request by tpoisot**
Viridis, Inferno, Plasma, and Magma colorscales for Gadfly

### CODE REVIEW

**Comment by KristofferC** [comment]
What advantage does having Viridis as its own package as opposed to just a PR to Gadfly?

**Comment by tpoisot** [comment]
@KristofferC modularity? Less burden of the Gadfly maintainer to maintain additional code?

**Comment by KristofferC** [comment]
Having it in Gadfly would mean it would be tested continuously together with Gadfly instead of being liable to breaking / not working with the latest Gadfly version. For a small piece of code that is as tightly coupled to a package like this, my personal view is that it would be much better to live with the package that it actually enhances.

**Comment by tpoisot** [comment]
I disagree -- the endgoal is to support other packages than gadfly.

**Comment by lobingera** [comment]
I agree withTimothée that we need a modular solution for importing named colormaps (and the data).
(btw: that was the reason i started https://github.com/lobingera/ColorMaps.jl, which includes this data)

I disagree with Kristoffer that this is Gadfly/Compose centric and needs to be included there.

**Comment by tkelman** [comment]
Should acknowledge the source and license of the data in your top-level license file in addition to in the code itself. Would also be good to write some actual tests and enable Travis CI.

**Comment by tpoisot** [comment]
@tkelman is there a way to cleanly untag, or should I make a new tag with the tests?

**Comment by tkelman** [comment]
A new tag would be fine

**Pull request closed without merging**
