### PR TITLE
Register IDRsSolver:v0.1.1

### PR DESCRIPTION
**Pull request by mschauer**
Redo of #2911 .

### CODE REVIEW

**Comment by mschauer** [comment]
At the end, I found IDRsSolver.jl  better than InducedDimensionReduction.jl because the former gives information about what the package does and keeps the naming closer to ``idrs.mat`` and ``idrs.py`` from the website.

**Comment by tkelman** [comment]
Still doesn't help anyone know what the package does at a glance.

**Comment by mschauer** [comment]
Come on...

**Comment by tkelman** [comment]
We can register it with this name anyway if you really don't want to spell out the acronym, but the whole point of disliking acronym package names isn't that they are too short, it's that they are opaque and incomprehensible.

**Comment by mschauer** [comment]
Thanks.

**Comment by tkelman** [comment]
Did you get the original authors' permission to distribute a derived work under the MIT license? The original Matlab code doesn't looks like it has a clear license, just a copyright.

**Comment by mschauer** [comment]
Yes, via @astudillor. PS: do you have a preferred name?

**Comment by tkelman** [comment]
Would be good to write that down explicitly somewhere in the documentation.

If this is just a Krylov method, would it be possible to incorporate into https://github.com/JuliaLang/IterativeSolvers.jl instead of having to be its own tiny package?

**Comment by mschauer** [comment]
I think that would be possible, but I like that the interface allows for abstract linear operators and abstract vectors (as long as ``vec``, ``dot`` and ``axpy!`` are defined).

**Comment by mschauer** [comment]
To clarify, the tiny package will do, until this is figured out.

**Pull request merged**
