### PR TITLE
Tag TensorOperations.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Jutho/TensorOperations.jl](https://github.com/Jutho/TensorOperations.jl)
Release: [v1.0.0](https://github.com/Jutho/TensorOperations.jl/releases/tag/v1.0.0)
Travis: [Travis Build Status](https://travis-ci.org/Jutho/TensorOperations.jl/builds/468254878)
Diff: [vs v0.7.1](https://github.com/Jutho/TensorOperations.jl/compare/8e57134d6c7911ed464b501d667bb0b570563860...aa028d2bbf4d95a9c1bd283c4b0de533923f9a66)
`requires` vs v0.7.1: 
```diff
--- 0.7.1/requires
+++ 1.0.0/requires
@@ -1 +1,3 @@
 julia 0.7
+TupleTools v1.0.0
+Strided v0.2.2
```
cc: @Jutho

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by Jutho** [comment]
Hold off with merging this; I might have to fix some final issue.

**Comment by Jutho** [comment]
Ok fixed, so if I remember correctly, I can just remove the tag, and then tag a release again with the same version number, and everything should work correctly.

**Comment by Jutho** [comment]
I think this is ready now

**Comment by Jutho** [comment]
Bump.

**Comment by andreasnoack** [comment]
Please remember that you disable the automatic merging of PRs when you comment after the most recent Attobot comment.

**Comment by Jutho** [comment]
Oh, my apologies. I did not realize that automatic attobot merging would kick in again. Thanks for merging.

**Pull request merged**
