### PR TITLE
Register new package FinancialToolbox.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rcalxrc08/FinancialToolbox.jl](https://github.com/rcalxrc08/FinancialToolbox.jl)
Release: [v0.0.1](https://github.com/rcalxrc08/FinancialToolbox.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/rcalxrc08/FinancialToolbox.jl/builds/268694008)
cc: @rcalxrc08

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@rcalxrc08 This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by rcalxrc08** [comment]
v0.0.1 supports julia 0.5 and higher
v0.0.2 supports julia 0.6 and higher

**Comment by tkelman** [comment]
The METADATA policy is that different Julia versions should be supported via different package minor versions. Otherwise there's no way for you to make any future bug fix releases for the julia 0.5-supporting version.

**Comment by rcalxrc08** [comment]
ok thank you for the answer!

**Comment by rcalxrc08** [comment]
please close the two old pull request, i just made a release of v0.1.0 that supports julia 0.5.* and higher

**Pull request closed without merging**
