### PR TITLE
Tag Einsum.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ahwillia/Einsum.jl](https://github.com/ahwillia/Einsum.jl)
Release: [v0.4.0](https://github.com/ahwillia/Einsum.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/ahwillia/Einsum.jl/builds/487370128)
Diff: [vs v0.2.0](https://github.com/ahwillia/Einsum.jl/compare/902e4b205ac7bae9f1e2171527759e49a2d05d07...6c69ecfbf0d6527f82fb8c3880d781395cab3640)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.4.0/requires
@@ -1 +1,3 @@
 julia 0.6
+
+Compat
```
cc: @phipsgabler

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by mcabbott** [comment]
This can be closed, superseded by #21045

**Comment by andreasnoack** [comment]
Next time, please just update the existing PR.

**Comment by mcabbott** [comment]
Will do, sorry about the hassle.

**Comment by andreasnoack** [comment]
You are welcome and thanks for letting us know when a PR can be closed.

**Pull request closed without merging**
