### PR TITLE
Tag GLAbstraction.jl v0.2.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGL/GLAbstraction.jl](https://github.com/JuliaGL/GLAbstraction.jl)
Release: [v0.2.2](https://github.com/JuliaGL/GLAbstraction.jl/releases/tag/v0.2.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGL/GLAbstraction.jl/builds/193832344)
Diff: [vs v0.2.1](https://github.com/JuliaGL/GLAbstraction.jl/compare/a88532d45c41c8b47e83a8bdf2ba2975a2aa56b2...644b432d196ccc2702e15ea7008af306843ba46f)
`requires` vs v0.2.1: 
```diff
--- 0.2.1/requires
+++ 0.2.2/requires
@@ -1,4 +1,5 @@
 julia 0.4
+
 Quaternions
 FixedSizeArrays
 GeometryTypes
```
cc: @SimonDanisch

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Needs also these to be merged:
https://github.com/JuliaLang/METADATA.jl/pull/7624
https://github.com/JuliaLang/METADATA.jl/pull/7625
https://github.com/JuliaLang/METADATA.jl/pull/7623
https://github.com/JuliaLang/METADATA.jl/pull/7626

**Comment by tkelman** [comment]
Same question here (and #7625 and #7626), are these still tested on 0.4?

**Comment by tkelman** [comment]
replaced by #7675 ?

**Comment by SimonDanisch** [comment]
Yup! Sorry I got interrupted in the middle of retagging the GL-packages! Will update soon!

**Pull request closed without merging**
