### PR TITLE
Tag Mads v0.4.20 [https://github.com/madsjulia/Mads.jl]

### PR DESCRIPTION
**Pull request by montyvesselinov**
Diff vs v0.4.19: https://github.com/madsjulia/Mads.jl/compare/b78bed5941ca35b9a1f6df7c149712b005a5574b...31f0460929e3b234ed7f8b8a1ba71a8e4921c944

### CODE REVIEW

**Comment by montyvesselinov** [comment]
I am not sure how to read JuliaCIBot log

```
===============================[ ERROR: Mads ]=================================

failed process: Process(`/opt/julia-0.5.2/bin/julia -Cx86-64 -J/opt/julia-0.5.2/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=user --inline=no --color=no --compilecache=yes /mnt/pkgevalempty/2706415b86b92eb03fd99b3ff5589701325ae787/Mads/.julia/v0.5/Mads/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: LoadError: Mads had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:748
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in (::Base.Pkg.#kw##test)(::Array{Any,1}, ::Base.Pkg.#test, ::String, ::Vararg{String,N}) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /mnt/pkgeval/cijm1056105mads/run.jl, in expression starting on line 1
```

**Comment by montyvesselinov** [comment]
Still Travis CI works; so hope it is all ok.

**Comment by tkelman** [comment]
It might be timing out, or just exiting silently, not sure. The log has stdout and stderr separated which we should fix, have things recorded in the order they get output.

There was an error on PackageEvaluator, where this had been passing before: https://github.com/JuliaCI/pkg.julialang.org/blob/09b938da085c16417609c82b8832d6ec26e888f6/logs/Mads_0.6.log. Not sure if it's intermittent, we'll see.

**Comment by tkelman** [comment]
There was also a failure on Julia 0.5 yesterday - https://github.com/JuliaCI/pkg.julialang.org/blob/571f639647b1d31cbf6b54a713a2ff057ec8fccc/logs/Mads_0.5.log

There were updates to HDF5.jl, Polynomials.jl, and Rmath.jl, so it may be related to one of those? Or just random.

**Pull request merged**
