### PR TITLE
New package OpenFOAM.jl

### PR DESCRIPTION
**Pull request by andyreagan**
Wrapper of the OpenFOAM library for Computation Fluid Dynamics (CFD).

### CODE REVIEW

**Comment by tkelman** [comment]
Does `Pkg.test("OpenFOAM")` pass on both Julia 0.3 and 0.4? If so, could it be made to pass on Travis CI?

**Comment by andyreagan** [comment]
I'll double check on the Pkg.test(), locally.

I've never worked with Travis CI before, if it passes locally then it
should pass there, right?

--
Andy Reagan
Department of Mathematics and Statistics
The University of Vermont
16 Colchester Ave.
Burlington, VT 05405
andy@andyreagan.com

**Comment by andyreagan** [comment]
It looks like the Travis CI build passed above, but the tests didn't work locally (were in `test.jl`, not `runtests.jl`).
I moved them and `Pkg.test("OpenFOAM")` works.

Do I need to publish it again?

**Comment by tkelman** [comment]
The tagged commit here will not actually be loadable as a julia package since the src file at https://github.com/andyreagan/OpenFOAM.jl/tree/master/src does not match the package name.

**Comment by andyreagan** [comment]
Oops I forgot to push the latest commit. Should be good to go now.

**Comment by tkelman** [comment]
Good, you'll need to adjust the commit that's tagged here. And the Travis CI check here is just for consistency of Metadata itself. When I was referring to Travis CI earlier, I meant if you enable it for the package repository to test the package itself.

**Comment by andyreagan** [comment]
Got it. Can you just close this one and I'll make a new commit?

**Comment by tkelman** [comment]
You can add new commits to the same branch and they will show up here. That would be preferred and cleaner.

**Comment by andyreagan** [comment]
I tried pushing up the newest commit, and I though that github would figure it out and add it to this pull request, but it didn't.

So now it's over here: https://github.com/JuliaLang/METADATA.jl/pull/4511

**Comment by andyreagan** [comment]
Okay I'm back here. I've cloned my fork of METADATA and now I'm trying to adjust the pull request commit.

**Comment by andyreagan** [comment]
Okay, I think I've pushed a new commit to this branch.

**Comment by tkelman** [comment]
Sorry, it should be replacing the existing sha, not appending to it. If you delete the first line we should be okay.

**Comment by andyreagan** [comment]
Ooops! I thought I did replace it. It's correct now.

Thanks for the help!

**Comment by andyreagan** [comment]
Woohoo!

**Pull request merged**
