### PR TITLE
Tag JavaCall.jl v0.4.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaInterop/JavaCall.jl](https://github.com/JuliaInterop/JavaCall.jl)
Release: [v0.4.3](https://github.com/JuliaInterop/JavaCall.jl/releases/tag/v0.4.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaInterop/JavaCall.jl/builds/221561005)
Diff: [vs v0.4.2](https://github.com/JuliaInterop/JavaCall.jl/compare/5b3dcecd0c14ad29ef2c22789057a71d115d48c4...e2618325d1183a2c15d2a365f043e7c680f215d9)
`requires` vs v0.4.2: no changes
cc: @aviks

### CODE REVIEW

**Comment by tkelman** [comment]
What are the appveyor failures about?

**Comment by aviks** [comment]
0.6, and 32 bit, both are which don't work with this package at present.

**Comment by tkelman** [comment]
Ah I was confused by https://ci.appveyor.com/project/aviks/javacall-jl-6c24s/history which made it look like things were passing a few months ago, which they were because you have 32 bit as an allowed failure and nightly worked at the time.

**Comment by aviks** [comment]
Yes indeed, 32 bit is unlikely to work, but i do want to keep testing with nightly (and see the failure) as a reminder to eventually fix it.

**Pull request merged**
