### PR TITLE
Register new package SimradRaw.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [EchoJulia/SimradRaw.jl](https://github.com/EchoJulia/SimradRaw.jl)
Release: [v0.0.1](https://github.com/EchoJulia/SimradRaw.jl/releases/tag/v0.0.1)
cc: @RobBlackwell

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@RobBlackwell This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like the tests are failing. Please enable testing on Travis.

**Comment by RobBlackwell** [comment]
Thanks - Sorry for my ignorance - this is the first package that I have tried to publish.

The test fails because of a dependency on another, as yet unpublished package. I tried to see if one can REQUIRE an unregistered package, but that doesn't seem to be possible (?)

My aim is to publish a core set of packages from https://github.com/EchoJulia, but there are lots of mutual testing dependencies. Is there a way to get @attobot to push the lot together? Failing that could this package be accepted in the knowledge that once the other packages are published, all the tests will work?

Any advice appreciated please.

**Comment by andreasnoack** [comment]
The solution here is to register dependencies first. Sometimes this process requires some reorganization of your code but that might be a useful process. Please also consider if things are split into too many packages. Sometimes it can be useful to have things in separate packages but it makes it harder to ensure that things work together and you'll end up spending more time on releasing new versions.

**Comment by andreasnoack** [comment]
In short, you'll have to have all your packages merged one at a time but feel free to open all the PRs in one go. We/you can restart the tests as the dependencies get merged.

**Comment by RobBlackwell** [comment]
Thanks, I have made a start with https://github.com/JuliaLang/METADATA.jl/pull/15796 which is passing its tests. I'll build up from there.

**Comment by andreasnoack** [comment]
I've merged https://github.com/JuliaLang/METADATA.jl/pull/15796 but you'll need to add it to the `REQUIRE` files of the packages that depend on it instead of installing it in `.travis.yml`. Once you've added it to a `REQUIRE` file, you can delete the release and tag and reapply the tag on the commit that includes the updated `REQUIRE` file. That will automatically update this PR. This method can also generally be used for restarting the tests.

**Comment by RobBlackwell** [comment]
Okay, thank you for your patience, I think I'm finally getting the hang of this.

**Pull request merged**
