### PR TITLE
Update QuantumOptics.jl to version v0.4.0 and change github url

### PR DESCRIPTION
**Pull request by bastikr**

### CODE REVIEW

**Comment by tkelman** [comment]
You need to have `Compat 0.17` in your require file to use `@compat abstract type`

**Comment by bastikr** [comment]
Thank you! I changed the pull request accordingly.

**Comment by tkelman** [comment]
be sure to also make the corresponding change in https://github.com/qojulia/QuantumOptics.jl/blob/master/REQUIRE

**Comment by bastikr** [comment]
I made a pull request, thanks again!

**Comment by bastikr** [comment]
Since there was this copy bug you reported, it's probably not a good idea to use this release. Is it okay to move the 0.4.0 tag to a commit that fixes this problem or is it cleaner to just release 0.4.1?

**Comment by tkelman** [comment]
you can do either, whichever you prefer

**Comment by bastikr** [comment]
I moved the v0.4.0 tag to the latest commit and changed the sha1 key in METADATA accordingly.

**Pull request merged**
