### PR TITLE
Tag Dolo.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [EconForge/Dolo.jl](https://github.com/EconForge/Dolo.jl)
Release: [v0.2.1](https://github.com/EconForge/Dolo.jl/releases/tag/v0.2.1)
Diff: [vs v0.2.0](https://github.com/EconForge/Dolo.jl/compare/7ef705b432ad037fdb9c0db9c8755c0023026443...81a5c6976c8f6ff34482d353af27ca2568380437)
`requires` vs v0.2.0: no changes
cc: @sglyon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Tests fail for 0.5. Is that meant to work?

**Comment by sglyon** [comment]
No, we no longer support 0.5. I will update the REQUIRE file. Good catch

**Comment by ararslan** [comment]
Since you're dropping support for 0.5 in this release, it will need to be a minor version bump rather than a patch version.

**Comment by sglyon** [comment]
Good catch.

New Pr here https://github.com/JuliaLang/METADATA.jl/pull/12968

**Comment by ararslan** [comment]
Great, thanks! I'll close this one then.

**Pull request closed without merging**
