### PR TITLE
Register new package TracyWidom.jl v0.0.2

### PR DESCRIPTION
**Pull request by AustenLamacraft**
Package providing the Tracy-Widom distribution from random matrix theory.

### CODE REVIEW

**Comment by nkottary** [comment]
The url is incorrect and so tests are failing. It should be `https://github.com/AustenLamacraft/TracyWidom.jl`

**Comment by andreasnoack** [comment]
Have you considered contributing this to the https://github.com/JuliaMath/RandomMatrices.jl/blob/master/src/densities/TracyWidom.jl package instead?

**Comment by AustenLamacraft** [comment]
Will ask

**Comment by andreasnoack** [comment]
Superseded by https://github.com/JuliaMath/RandomMatrices.jl/pull/44

**Pull request closed without merging**
