### PR TITLE
Tag Docker v0.0.1

### PR DESCRIPTION
**Pull request by raphapr**

### CODE REVIEW

**Comment by tkelman** [comment]
What's the minimum supported Julia version?

**Comment by tkelman** [comment]
Also depends on JSON. And badly needs tests (tsk tsk Keno)

**Comment by aviks** [comment]
Should this be closed? @raphapr

**Comment by raphapr** [comment]
Hi, I just created a PR again. I'm sorry for the late reply.

https://github.com/JuliaLang/METADATA.jl/pull/5760

**Pull request closed without merging**
