### PR TITLE
Tag VoronoiDelaunay.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGeometry/VoronoiDelaunay.jl](https://github.com/JuliaGeometry/VoronoiDelaunay.jl)
Release: [v0.2.0](https://github.com/JuliaGeometry/VoronoiDelaunay.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGeometry/VoronoiDelaunay.jl/builds/256633102)
Diff: [vs v0.1.0](https://github.com/JuliaGeometry/VoronoiDelaunay.jl/compare/e2f860c14aecc7ba60d500c6d35e3aac5b8a4f5f...48b33d39808d1bc13610a90630a90cec95e3fa14)
`requires` vs v0.1.0: 
```diff
--- 0.1.0/requires
+++ 0.2.0/requires
@@ -1,4 +1,3 @@
-julia 0.4
-GeometricalPredicates 0.0.6
-Colors 0.6.9
-Compat 0.8.4
+julia 0.6
+GeometricalPredicates 0.1.0
+Colors 0.7.1
```
cc: @robertdj

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by robertdj** [comment]
@tkelman I am tagging the master branch, but for some reason it doesn't include your commit. Do you know what I'm missing?

**Comment by tkelman** [comment]
did you delete both the release and the git tag before recreating it?

**Comment by robertdj** [comment]
Ooops! That's what I missed. Thanks!

**Comment by tkelman** [comment]
Looks like VoronoiCells might need another test bound change like https://github.com/JuliaGeometry/VoronoiCells.jl/commit/bbe4ad8ab90ae888f5b953979c9d7f98c8b21b42

**Comment by tkelman** [comment]
oh actually that looks like a typo, one of the `put!` was misspelled as `out!`

**Comment by robertdj** [comment]
Looking at that log it looks like the `out!` function is from `StatsBase`..? There is no such function in `VoronoiCells`.

**Comment by tkelman** [comment]
it's a typo here https://github.com/JuliaGeometry/VoronoiDelaunay.jl/compare/e2f860c14aecc7ba60d500c6d35e3aac5b8a4f5f...c67cb38e868d19eac068c414540b29378e31ea39?w=1#diff-e4050cf020d76d900e48ea1d818cd0cfR202

**Comment by robertdj** [comment]
Okay. I'll push a fix and make a new release.

**Pull request merged**
