### PR TITLE
Tag MIToS v1.2.0

### PR DESCRIPTION
**Pull request by diegozea**
This solves https://github.com/diegozea/MIToS.jl/issues/32 and the `swap!` problem with `FixedSizeArrays`

Thanks!

### CODE REVIEW

**Comment by tkelman** [comment]
are you sure you want multiple 20k+ line files checked in under docs?

**Comment by tkelman** [comment]
doesn't need to be fixed right now, but note https://github.com/JuliaLang/julia/issues/12120, you shouldn't usually use `Pkg.dir` to refer to a package's location since it could be installed elsewhere

**Comment by diegozea** [comment]
> are you sure you want multiple 20k+ line files checked in under docs?

Sorry, I didn't understand that.

> doesn't need to be fixed right now, but note JuliaLang/julia#12120, you shouldn't usually use Pkg.dir to refer to a package's location since it could be installed elsewhere

Thanks, I will do it and I will tag a `:patch` tomorrow.

**Comment by tkelman** [comment]
`docs/Information.ipynb` and `docs/compiled/Information.html` are rather large files which may make your git history noticeably larger if you include them in a tagged version.

**Comment by diegozea** [comment]
Thanks for the clarification. Will It help If I move the docs into the `gh_pages` branch?

**Comment by tkelman** [comment]
Good question. I think Pkg currently clones all branches, but it's an outstanding todo item that we need to test whether it works properly with single-branch clones.

**Pull request merged**
