### PR TITLE
Tag IntervalArithmetic.jl v0.13.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIntervals/IntervalArithmetic.jl](https://github.com/JuliaIntervals/IntervalArithmetic.jl)
Release: [v0.13.0](https://github.com/JuliaIntervals/IntervalArithmetic.jl/releases/tag/v0.13.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIntervals/IntervalArithmetic.jl/builds/365429704)
Diff: [vs v0.12.0](https://github.com/JuliaIntervals/IntervalArithmetic.jl/compare/c8695e349988b6f44427e23a9a063387469e21cc...0897d41e0fdec7e77db380b481d8157eb184f358)
`requires` vs v0.12.0: no changes
cc: @dpsanders

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dpsanders** [comment]
cc @lbenet, @tkoolen

**Comment by dpsanders** [comment]
How do I close this?

**Comment by dpsanders** [comment]
Ready for merge once green.

**Comment by dpsanders** [comment]
cc @lbenet, @tkoolen

**Comment by dpsanders** [comment]
Could this please be merged?

**Comment by andreasnoack** [comment]
Looks like it breaks EAGO

**Comment by andreasnoack** [comment]
Looks like `IntervalContractors` is now broken.

**Comment by dpsanders** [comment]
@andreasnoack Thanks, that caught a stupid bug that wasn't tested anywhere else!

**Comment by dpsanders** [comment]
Now ready to merge.

**Comment by dpsanders** [comment]
Please *do not merge* yet.

**Comment by dpsanders** [comment]
Ready to merge once green.

**Pull request merged**
