### PR TITLE
Register Interfaces.jl

### PR DESCRIPTION
**Pull request by Rory-Finnegan**
A simple implementation of interfaces for julia. I'll note that it doesn't currently work on the latest nightlies due to [this](https://github.com/JuliaLang/julia/issues/11052) issue with `methodswith`.

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Why not use Traits.jl instead?

**Comment by Rory-Finnegan** [comment]
Traits.jl seemed overly complicated to use with the `@traitdef` and `@traitfn` and it seemed like it was fighting against the language with the tick to make dispatching work.

**Comment by StefanKarpinski** [comment]
For what it's worth I think further experiments with how to do interfaces in the language are worthwhile, with the understanding that we'll eventually pick one and go with it.

**Comment by Rory-Finnegan** [comment]
Just realized Traits.jl isn't in METADATA. Alternatively, I could withdraw my pull request and just mention it in julia-users.

**Comment by johnmyleswhite** [comment]
I don't think that's necessary. Stefan's point about experimenting with different approaches is good.

**Comment by IainNZ** [comment]
Lets merge?
(PS @Rory-Finnegan, seems like your Github email and your local git config'd email don't match?)

**Comment by Rory-Finnegan** [comment]
Oops, yeah. I'll fix that right away.

**Pull request merged**
