### PR TITLE
Register ParallelSparseMatMul

### PR DESCRIPTION
**Pull request by madeleineudell**

### CODE REVIEW

**Comment by jiahao** [comment]
Amazing that this package hasn't been registered yet? Did you ever figure out the performance regressions from Julia v0.2?

**Comment by ViralBShah** [comment]
How about merging this functionality into DistributedArrays?

**Comment by timholy** [comment]
Since it depends on SharedArrays, not DistributedArrays, I'm not certain that makes sense.

**Comment by ViralBShah** [comment]
I somehow mistakenly remembered from last year that this was distributed memory. Sorry for the noise.

**Pull request merged**
