### PR TITLE
Register FatGraphs [https://github.com/CarloLucibello/FatGraphs.jl.git]

### PR DESCRIPTION
**Pull request by CarloLucibello**
This a derivative of LightGraphs, the main differences being the support to custom graph types (inheriting from an abstract graph type, and defining a basic interface) and many under the hood improvements specified in the changelog.

Bye,
Carlo

### CODE REVIEW

**Comment by dpsanders** [comment]
I don't think the name is appropriate.

**Comment by CarloLucibello** [comment]
>I don't think the name is appropriate.

I agree. Graphs is taken. What about:
- FastGraphs
- Erdos (in honor of the matematician)
- Grafi (the italian for graphs, running out of ideas here)

I think Erdos is growing on me. Any advise against it? some "googlability" problems?

**Comment by CarloLucibello** [comment]
Also, should I tag a version before registration?

**Comment by tkelman** [comment]
> should I tag a version before registration?

At the same time.

So much of the code here is a straight unmodified fork of LightGraphs, would it make any sense to trim this package down to primarily consist of the pieces where it differs?

**Comment by CarloLucibello** [comment]
> So much of the code here is a straight unmodified fork of LightGraphs, would it make any sense to trim this package down to primarily consist of the pieces where it differs?

not really: all methods' signatures of LightGraphs have been relaxed here to accept G<:AGraph, AGraph being an abstract graph type. This is one of the reasons that pushed me to fork LightGraphs a few months ago

**Comment by tkelman** [comment]
replaced by #8085

**Pull request closed without merging**
