### PR TITLE
Register TinySegmenter: v0.0.1

### PR DESCRIPTION
**Pull request by chezou**
I create Julia version of [TinySegmenter](http://chasen.org/~taku/software/TinySegmenter/), which is compact Japanese tokenizer.

### CODE REVIEW

**Comment by jiahao** [comment]
:japanese_castle: :fireworks:

**Comment by stevengj** [comment]
Maybe it would be better to have a generic descriptive name like `TokenizeJapanese`?  You might want to include alternative tokenization algorithms in the future, or modifications to the original TinySegmenter algorithm.  Also, "TinySegmenter" by itself is not a very descriptive name to people outside the field of Japanese language processing, it could just as easily mean image segmentation or something else.

**Comment by chezou** [comment]
Ah, it's a difficult problem. 😓

It is a just porting package and the name "TinySegmenter" is a well known tokenization tool in Japanese NLPer, and I won't add any other algorithms. 
I read the nameing rule of Julian way like wrapping tool is simply use the original tool, like "LibSVM.jl", I think this rule is reasonable in this case.

**Comment by chezou** [comment]
More descriptive document of TinySegmenter in English is as following (written by mhagiwara who is a Japanese translator of Natural Language Proccesing in Python)
http://lilyx.net/tinysegmenter-in-python/

**Comment by chezou** [comment]
Or is it [namespace problem](https://github.com/JuliaLang/METADATA.jl/issues/2417)?
Then I will close this PR until the problem will be solved.

**Comment by tkelman** [comment]
It looks like there are already TinySegmenter ports in Python, Ruby, Perl, Java, all named similarly. You might have to know what you're looking for to find it, but there aren't really any chances to confuse it with anything else if you look into it a bit.

**Comment by stevengj** [comment]
@tkelman, I'm not worried about people who know what they are looking for finding it.  I'm worried about:

* In the future, do we want to have multiple Japenese tokenizer packages, or do we want to encourage people to work on a single package that implements multiple algorithms as needed?  (And if someone enhances the original TinySegmenter algorithm, should they fork to a new package?)   I thought that we tend to encourage unified packages when it makes sense, in which case a more generic name would be appropriate here.

* People who *aren't* looking for a Japanese tokenizer might get confused by this name; a more descriptive name would help people to know that it's not what they want.

**Comment by jiahao** [comment]
I think the name is allowable under the our current naming policy. It is a port of a well known Japanese tokenize and represents one of several possible Japanese tokenization strategies. (It implements one particular trained ML model for tokenization.) Requiring discoverability on the basis of name would have precluded the registration of dozens of packages by now. (Gadfly?)

**Comment by chezou** [comment]
@jiahao Thanks for merging!

This discussion let me know better understanding for package naming in Julia :)

**Pull request merged**
