### PR TITLE
Register Sparrow

### PR DESCRIPTION
**Pull request by rennis250**
This is a Julia interface to the ctioga2 plotting system. I really like the plots that Ctioga2 produces, but I found it frustrating to constantly export Julia data and then write a separate file for plotting. This makes the process much easier and everything can be done within the Julia environment.

### CODE REVIEW

**Comment by tkelman** [comment]
Note the new guidelines at https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/README.md - tag a version and this should be good.

**Comment by rennis250** [comment]
Should I close this request then? Using Pkg.publish() after Pkg.tag() creates a new pull request.

**Comment by tkelman** [comment]
You could force push the tag commit to this branch, or open a new PR, up to you.

**Comment by rennis250** [comment]
I'll do a new PR since it is already there. One second.

**Pull request closed without merging**
