### PR TITLE
Tag CUDAnative.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGPU/CUDAnative.jl](https://github.com/JuliaGPU/CUDAnative.jl)
Release: [v0.4.0](https://github.com/JuliaGPU/CUDAnative.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGPU/CUDAnative.jl/builds/259742743)
Diff: [vs v0.3.1](https://github.com/JuliaGPU/CUDAnative.jl/compare/fe0214e942a347742da415565729a06efadd6595...1da524d321686e3f124bb2555914110c98bce646)
`requires` vs v0.3.1: 
```diff
--- 0.3.1/requires
+++ 0.4.0/requires
@@ -1,3 +1,3 @@
 julia 0.6
-CUDAdrv 0.4.2
-LLVM 0.3.5
+CUDAdrv 0.5.0
+LLVM 0.3.8
```
cc: @maleadt

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by maleadt** [comment]
Merging, as CUDAdrv has already been tagged and the currently released CUDAnative is incompatible with it.

**Comment by tkelman** [comment]
You should add bounds when your packages break existing releases of each other.

**Comment by maleadt** [comment]
How? Wouldn't a released CUDAnative, which doesn't include upper bounds on dependent packages, always break when any of those packages introduces breaking changes? Or do you suggest adding "precautionary" upper bounds for all dependencies?

**Comment by tkelman** [comment]
You can retroactively modify bounds of the METADATA copy of the requires files, they don't have to match the package version - for a tagged release of a registered package, only the METADATA copy matters. You can modify the requires files here in a PR, without touching the sha or the package itself. There was a recent example in https://github.com/JuliaLang/METADATA.jl/pull/10494

**Comment by maleadt** [comment]
Ah, didn't know that. Making a PR now.

**Pull request merged**
