### PR TITLE
Register new package DependencyTrees.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [dellison/DependencyTrees.jl](https://github.com/dellison/DependencyTrees.jl)
Release: [v0.1.1](https://github.com/dellison/DependencyTrees.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/dellison/DependencyTrees.jl/builds/500218876)
cc: @dellison

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@dellison This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dellison** [comment]
This PR should be closed- after installing attobot, it took me a couple iterations to figure out what I was doing. I think I have the hang of it now, and #21858 is my "real" PR. Sorry about the duplicates, and thanks in advance!

**Comment by dellison** [comment]
The title of this PR is out of date: DependencyTrees.jl v0.1.0 was registered earlier this month, and this is an update.

**Comment by dellison** [comment]
Just checking in on this, as it seems like it might have been overlooked. Do these PRs get reviewed?

I've been thinking that I will probably have the same problem as this one (regarding the title of the PR) if I tag v0.1.2 and v0.1.3 of this package- I expect that attobot would force-push to update those out-of-date PRs ([here](https://github.com/JuliaLang/METADATA.jl/pull/21855) and [here](https://github.com/JuliaLang/METADATA.jl/pull/21856)), leaving them with "Register new package" titles for a change that is actually just the release of a new tagged version. I don't have the permission to delete those PRs. Is there any way that I can avoid this issue?

**Comment by dellison** [comment]
Hello?

**Comment by dellison** [comment]
ping

**Comment by dellison** [comment]
Ping?

**Comment by andreasnoack** [comment]
Sorry for the delay here. Please note that we are now switching over to using Registrator for package registrations.

**Comment by dellison** [comment]
@andreasnoack, right, I did see announcement on the Julia Discourse a week or two ago. Thanks for the reminder, and no worries! I haven't gotten around to setting up the Registrator stuff for this package yet, but I'm planning to do it soon :)

**Pull request merged**
