### PR TITLE
Tag Unitful.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ajkeller34/Unitful.jl](https://github.com/ajkeller34/Unitful.jl)
Release: [v0.1.1](https://github.com/ajkeller34/Unitful.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/ajkeller34/Unitful.jl/builds/204732354)
Diff: [vs v0.1.0](https://github.com/ajkeller34/Unitful.jl/compare/f544bc68fad1679ec169afadc13f73fcee5f59db...a742ba2c34c48a3f7d21607ffdd02c5dc87a2932)
`requires` vs v0.1.0: no changes
cc: @ajkeller34

### CODE REVIEW

**Comment by ajkeller34** [comment]
Fix a macro hygiene issue and add tests for expected functionality of the macros that define new units and dimensions.

**Comment by ajkeller34** [comment]
I'm not sure why GitHub shows that the CI build is still in progress, but it has finished and passed.

**Comment by tkelman** [comment]
which one, that package's ci or metadata's ci? travis status reporting has had a few failures to deliver in the last few days, dunno if related

**Comment by ajkeller34** [comment]
Not sure quite what you mean, so I'll describe it the roundabout way: in Travis for the Unitful repository, the CI build that gets triggered when a release is tagged has passed. The last commit before tagging the release also triggered a CI build, which I canceled (why build twice for the same code?). On the badge in my README, it now shows that the build has been cancelled but if you look in the build history, the release build passed after that. So something seems funky. I've recently tried restarting the one I cancelled to see if that helps. Meanwhile, it still says "some checks haven't completed yet" on this page.

**Comment by tkelman** [comment]
If by "this page" you mean https://github.com/JuliaLang/METADATA.jl/pull/8095, the checks that haven't completed yet are METADATA's Travis, aka https://travis-ci.org/JuliaLang/METADATA.jl/builds/204732370, because base Julia is busy and using up the JuliaLang queue.

The badge link generated by attobot is showing "build unknown" but the link it points to https://travis-ci.org/ajkeller34/Unitful.jl/builds/204732354 has passed. It's probably saying "build unknown" because the master push build for the same release commit still has mac jobs pending, the job that has finished was a separate job triggered for the release tag. ref https://travis-ci.org/ajkeller34/Unitful.jl/builds

**Comment by ajkeller34** [comment]
Thank you for the clarification!

**Pull request merged**
