### PR TITLE
Upper bound older versions of AbstractTrees

### PR DESCRIPTION
**Pull request by Keno**
These versions of AbstractTrees don't work with julia 0.6, don't let the user install them

### CODE REVIEW

**Comment by tkelman** [comment]
What doesn't work about them? They all seem to pass their tests on Julia 0.6

**Comment by Keno** [comment]
There's invalid subtyping syntax in the package prior to 0.1.0, I'm surprised that tests would pass.

**Comment by tkelman** [comment]
I spoke a little too soon, 0.0.4 is indeed broken on julia 0.6, but 0.0.1 through 0.0.3 don't seem to be

**Comment by aviks** [comment]
Tests fail with `ERROR: ERROR: LoadError: LoadError: packages with unsatisfiable requirements found:`

Seems risky to merge as is.

**Comment by MikeInnes** [comment]
Closing this as we haven't heard from you in a while. Do let me know if you want to re-open.

**Pull request closed without merging**
