### PR TITLE
Add StreamStats package

### PR DESCRIPTION
**Pull request by johnmyleswhite**
This adds a standardized package for computing statistics on streaming data.

### CODE REVIEW

**Comment by IainNZ** [comment]
Cool!

**Comment by IainNZ** [comment]
Does this "deprecate" HyperLogLog.jl?

**Comment by johnmyleswhite** [comment]
Yes. That package should be deprecated after this gets merged.

**Comment by IainNZ** [comment]
I can handle that on the METADATA side of things. Do you think something like reservoir sampling would go in this package too?

**Comment by johnmyleswhite** [comment]
That would be great. The package's README notes that it's abandoned and I'll change it to point to this repo, which I will maintain since I need it for work.

Definitely think we should have reservoir sampling in this package. I have code for that somewhere, but forgot to include it.

**Comment by IainNZ** [comment]
Neat, I might submit a PR for it just for fun if you don't get to it first

**Comment by johnmyleswhite** [comment]
Found my reservoir sampling code. If you want a fun streaming project, I probably won't get to implementing q-digest soon.

**Comment by johnmyleswhite** [comment]
I just added reservoir sampling, which I'll include with the next release.

**Comment by IainNZ** [comment]
Let merge this for now anyway

**Comment by johnmyleswhite** [comment]
Thanks!

**Pull request merged**
