### PR TITLE
MathProgBase breaking transition

### PR DESCRIPTION
**Pull request by mlubin**
This bumps MathProgBase with some breaking changes (https://github.com/JuliaOpt/MathProgBase.jl/pull/91) with corresponding updates to most of the core JuliaOpt packages.

CI makes it hard to test these out, but everything is passing locally. After this is merged I'll be checking for any breakage, then working on updating the remaining packages.

CC @IainNZ @joehuchette @tkelman @ulfworsoe @madeleineudell @JackDunnNZ @yeesian

### CODE REVIEW

**Comment by IainNZ** [comment]
:+1:

**Comment by mlubin** [comment]
@IainNZ, could we do a package evaluator run tonight?

**Comment by IainNZ** [comment]
Yep, absolutely

**Comment by mlubin** [comment]
Here we go

**Pull request merged**
