### PR TITLE
Tag Polynomials.jl v0.3.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMath/Polynomials.jl](https://github.com/JuliaMath/Polynomials.jl)
Release: [v0.3.3](https://github.com/JuliaMath/Polynomials.jl/releases/tag/v0.3.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMath/Polynomials.jl/builds/398251317)
Diff: [vs v0.3.2](https://github.com/JuliaMath/Polynomials.jl/compare/723fc0701489b338f42af4b7a4177f4f424a3cbb...1c2c79672e7fa18f14bf0ed7f3f77c1602c94ceb)
`requires` vs v0.3.2: no changes
cc: @jverzani

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like this release will break ControlSystems

**Comment by andreasnoack** [comment]
See below. It says "**JuliaCIBot**  — Tests failed" and there is a "Details" link to the right that will show you which downstream packages failed with links to the test logs.

**Comment by jverzani** [comment]
Thx. That looks like a connectivity issue. I’ll double check

**Comment by andreasnoack** [comment]
I've restarted the tests. Let's see how it goes.

**Comment by jverzani** [comment]
This looks like `ControlCore` had an issue though unrelated to the change in `Polynomials`, as far as I can tell. The new error in `PolynomialMatrices` is related to this change. I will send them a PR if this gets merged.

**Comment by KristofferC** [comment]
What is the actionable thing to do here? If this breaks `PolynomialMatrices` then this should perhaps use a minor version bump instead of a patch bump=

**Comment by jverzani** [comment]
I'd close this and bump the minor version, but I can't close. I'll do the latter.

**Pull request closed without merging**
