### PR TITLE
Pull request/159e9b09

### PR DESCRIPTION
**Pull request by andrewcooke**

### CODE REVIEW

**Comment by IainNZ** [comment]
Hey @andrewcooke, METADATA.jl is a finite namespace and a shared community resource. Before you "claim" an extremely common name like "Draw", it'd be good to have a chance for people to discuss that.

**Comment by tkelman** [comment]
Agreed, this is a way too generic name.

**Comment by andrewcooke** [comment]
oh, ok, i'll think of something else.  is Drawing OK?

(there are already 300+ packages.  maybe it would make sense to reserve names you don't want people to use.  calling a drawing package Draw seemed like quite a natural idea to me).

**Comment by andrewcooke** [comment]
or Draw2D?  there's already a Draw3D.  but that implies the two are similar in some way.

**Comment by tkelman** [comment]
The issue here is merging your own PR immediately without allowing the community any time to give review feedback. While that's normally fine for just tagging a new version, registering a new package and reserving a name warrants more scrutiny.

**Comment by andrewcooke** [comment]
https://groups.google.com/forum/#!topic/julia-users/FNKeiepG8Jk

**Comment by tkelman** [comment]
By "public scrutiny" I didn't mean a mailing list post. I meant leaving the pull request open for at least a day or two and asking if anyone has any feedback about the name, rather than merging it yourself immediately. We should probably be more restrictive about commit access to metadata.

The name is really the most important thing about a newly registered package that needs some initial discussion. And with very small yet general-purpose packages like this one, it would likely be worth investigating opportunities for collaboration to make a smaller number of better packages, rather than making the situation in https://github.com/dcjones/Gadfly.jl/issues/658 even worse.

**Comment by timholy** [comment]
Without having first looked at the package, I immediately assumed it was an interactive (i.e., mouse-driven) sketching/painting program written in Julia.

**Comment by lobingera** [comment]
@timholy, looking at the source, i'm rather convinced, it isn't...

> A library for drawing (diagrams, lines, shapes).
>
> In more formal terms - simple, imperative vector graphics. For a declarative approach, see Compose.jl. For more control and complexity, see Cairo.jl.

**Comment by lobingera** [comment]
Why not naming like the purpose: SimpleImperativeGraphics.jl ?

**Comment by andrewcooke** [comment]
i'm happy to change the name.  i am not so happy that other people get to pick it.  it seems completely arbitrary and against the docs that suddenly (after years of development and 300+ packages) there are important names that "shouldn't" be used, and that you're not supposed to merge the request yourself.

this isn't my first julia package. i've never been told before that i needed to wait, or get approval.  it's not in the official julia docs.

if you've got names that you want ot keep, then reserve them in some way.  arbitrarily jumping on someone and inventing new rules and processes that didn't apply before is very frustrating.

**Comment by tkelman** [comment]
Actually, it is in the documentation. http://docs.julialang.org/en/latest/manual/packages/#guidelines-for-naming-a-package

This is not new, we're not jumping on you, we're not reserving names. But as Iain said it's a shared namespace and there's a desire to be more selective and critical of the packages we allow to be registered in metadata as time goes on. Merging your own pull requests defeats the purpose of code review, though I will grant you that appears to not be explicitly written down anywhere.

**Comment by andrewcooke** [comment]
i feel like the implicit thing here is a made some crappy little package just to grab a name. this is a 0.0.1 release.  look at my other packages: 

https://github.com/andrewcooke/ParserCombinator.jl
https://github.com/andrewcooke/IntModN.jl
https://github.com/andrewcooke/CRC.jl

these are all "decent", honest, supported packages.  i'm not trying to screw the system, i was looking forwards to a week of development.  now i feel like the whole thinhg is ome kind of joke.

and what is the point of an "established" process if you deign to "grant" me the fact that it's not  documented anywhere.  this isn't your private fucking club.

**Comment by tkelman** [comment]
Please calm down. This is a community, and part of that means assuming good faith collaboration - http://julialang.org/community/standards/. Packages don't absolutely need to be registered right away either, it can help to do early design work and announce the package in an unregistered state prior to tagging an official version.

**Comment by andrewcooke** [comment]
I've renamed the package to Drawing.jl.  I have no idea how to change the metadata, so please can someone do that.

And please document your process.  For this to appear inclusive, you need a clear, consistent process.

**Comment by cormullion** [comment]
I called my drawing package Luxor.jl ... sort of relating to Cairo (it's just a thin wrapper for Cairo). But I'm not interested in adding it to the main Julia system -- it's not good enough. :)

**Comment by andrewcooke** [comment]
Yeah, that's the kind of thing (Luxor) I am aiming for too.  If you had published your package I would have found it myself before starting this one (I think the idea of scopes using `with` is a good one, and that's what I am trying to explore here).

**Comment by lobingera** [comment]
@cormullion,
>  it's not good enough

i've seen worse.

**Comment by catawbasam** [comment]
svaksha's curated decibans can be useful for finding things like Luxor.jl --
https://github.com/svaksha/Julia.jl/blob/master/Computer-Graphics.md

**Comment by jiahao** [comment]
I've reverted this commit.

@andrewcooke feel free to edit the docs if what is written there isn't clear. We expect that users who are given commit access should err on the side of discretion.

**Comment by andrewcooke** [comment]
how can i edit the docs?  i don't know the rules.  the whole point is that you have a bunch of rules that are not public.  i am not telepathic.  if you have rules that aren't there, you write them down.

**Comment by jiahao** [comment]
And the point of open source is that if you're unhappy with the current situation you can suggest changes.

**Comment by andrewcooke** [comment]
please, read this thread.  it is clear that i don't know what the expected behaviour is.

there's some internal developer culture that i am not part of.  it's even begrudgingly admitted above that these things are not public.

i do submit changes to docs.  the julia manual contains at least one submission of mine. but i cannot magically produce documentation on *your* culture, your "club" when i am nit part of it.  surely that must be obvious?

**Comment by tkelman** [comment]
I never said that things aren't public, just that they aren't written down in as many places as they could be. Understanding the expectations comes from active participation and engagement in code review and collaboration on packages, metadata, and base Julia. Julia's development is remarkably open and public on github, but it's driven by active participation.

We hit a little bit of friction where you ran afoul of something you weren't aware of, and didn't find out about it until after the fact. It's not a big deal, can we move on?

**Comment by andrewcooke** [comment]
was there any point to that comment apart from wanting to get the last word?

**Comment by timholy** [comment]
@andrewcooke, regarding cliques and the like: never blame on malice that which you can explain by stupidity...or more commonly, folks simply being too busy to do due diligence.

There's no question that docs are often inadequate, that there are important details known only to those who receive too many emails a day, etc. That's how there gets to be an "inner" circle---simply in proportion to how much time you invest---and people not having/taking the time to update the docs to disseminate this information properly. The reality is there are not enough hours in the day, and often there's a tension between two good outcomes: doing something that will make julia even better vs documenting those things one has already contributed. When you can't do both, which do you choose?

You've been around a lot (which is great!), and so people may treat you as an insider when perhaps they shouldn't. Don't take it personally, we're all too human in our failings but all :angel:s when it comes to our intentions.

**Comment by andrewcooke** [comment]
thanks, tim.  i'm sorry i got angry.  it's a whole other culture.

**Comment by tpoisot** [comment]
I don't know the extent to which comments (about the name) are still welcome on this PR, but reading the docs, and in particular the sentence ([ref](http://docs.julialang.org/en/latest/manual/packages/#guidelines-for-naming-a-package)):

> A less systematic name may suit a package that implements one of several possible approaches to its domain.

I would consider something else than `Draw.jl`.

@andrewcooke renaming a package is not difficult. I had to do it in a previous PR. Rebase METADATA.jl, re-register the package under the new name, and submit a new PR. It took me about 10, maybe 15 minutes. Having had to change the name of one of my packages, I don't think it's right to see it as others picking names for you. These are reasonable suggestions, and I'm sure that they only aim to make the package ecosystem understandable for people that do not follow the mailing lists, etc, closely.

**Comment by pkofod** [comment]
Maybe AnDraw.jl ? :) (I'm so sorry, I'll take a timeout in the corner)

**Pull request merged**
