### PR TITLE
Registering Klara

### PR DESCRIPTION
**Pull request by scidom**
(renaming Lora to Klara)

### CODE REVIEW

**Comment by tkelman** [comment]
The only one of these tags that will work under its current name is 0.6.0. All other tags should not be registered under this name.

**Comment by scidom** [comment]
What is the best way to handle this? Should I close the PR or there is an easy eay to drop older tags?

**Comment by tkelman** [comment]
you can either delete the files from the `pull-request/768922c9` branch of your metadata fork, or open a new PR that doesn't add them

**Comment by scidom** [comment]
I delted the files from the pull-request/768922c9 branch @tkelman, hopefully this has worked now.

**Comment by scidom** [comment]
@tkelman, if there is no technical holdback, it would be helpful to get this PR merged please so that I can then create the readthedocs new url (in the readthedocs site), and announce publicly the transition from Lora to Klara. Thanks for the help.

**Comment by scidom** [comment]
Thanks @tkelman!

**Pull request merged**
