### PR TITLE
Tag Nemo.jl v0.6.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [Nemocas/Nemo.jl](https://github.com/Nemocas/Nemo.jl)
Release: [v0.6.2](https://github.com/Nemocas/Nemo.jl/releases/tag/v0.6.2)
Travis: [Travis Build Status](https://travis-ci.org/Nemocas/Nemo.jl/builds/236314880)
Diff: [vs v0.6.1](https://github.com/Nemocas/Nemo.jl/compare/c501ab953d0541fe900ffcf800a8a1d712eee50f...6a513db316d9a5471c8133a068d95a046879ed54)
`requires` vs v0.6.1: no changes
cc: @thofma

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by thofma** [comment]
Don't merge yet.

**Comment by thofma** [comment]
OK, now it's ready.

**Comment by thofma** [comment]
These are only bugfixes, but we worked around them in Hecke. Now that they are fixed, Hecke is failing. Should I put some upper bounds on Hecke or just release a new Hecke version?

**Comment by tkelman** [comment]
Probably both.

**Comment by thofma** [comment]
Can we somehow restart JuliaCIBot?

**Comment by tkelman** [comment]
We can close and reopen the PR, but I think it might not respect the upper bounds though and instead check out this package to this specific version. I'd also have to look at the code to see whether it runs directly on the attobot/Nemo/v0.6.2 METADATA branch or will run on the merge-commit branch like Travis does. We should tweak it to fix these things, but we can see what happens now if you'd like.

**Comment by thofma** [comment]
You are right, I think closing and reopening won't help. I will just make a new PR (without attobot).

**Comment by tkelman** [comment]
A new PR might not respect the upper bounds either due to the first problem, but at least the merge issue could be solved with a manual rebase before you open a PR

**Pull request closed without merging**
