### PR TITLE
Tag ApplicationBuilder.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [NHDaly/ApplicationBuilder.jl](https://github.com/NHDaly/ApplicationBuilder.jl)
Release: [v0.3.1](https://github.com/NHDaly/ApplicationBuilder.jl/releases/tag/v0.3.1)
Travis: [Travis Build Status](https://travis-ci.org/NHDaly/ApplicationBuilder.jl/builds/459936728)
Diff: [vs v0.2.1](https://github.com/NHDaly/ApplicationBuilder.jl/compare/8bb5f60b2e408e08674431d5e6461be77e317b1a...77d8cb0f93c613a73121dcf8091fde3f63d7c727)
`requires` vs v0.2.1: 
```diff
--- 0.2.1/requires
+++ 0.3.1/requires
@@ -1,5 +1,4 @@
-julia 0.6
+julia 0.7
 PackageCompiler
 Glob
 ArgParse
-Compat
```
cc: @NHDaly

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Is this package not expected to work on Linux?

**Comment by ChrisRackauckas** [comment]
>ApplicationBuilder supports macOS, Windows, and Linux.

**Comment by andreasnoack** [comment]
See https://github.com/NHDaly/ApplicationBuilder.jl/blob/v0.3.1/.travis.yml#L6, though.

**Comment by NHDaly** [comment]
Ah, sorry. Yes this _maybe_ supports linux, but there's no tests for it. The tests are all written assuming they're on a mac. I'll go ahead and wrap them with `isapple()` so this won't happen again. Thanks Andreas!

**Comment by NHDaly** [comment]
Reported: https://github.com/NHDaly/ApplicationBuilder.jl/issues/39

**Pull request merged**
