### PR TITLE
Tag TensorToolbox.jl v0.0.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lanaperisa/TensorToolbox.jl](https://github.com/lanaperisa/TensorToolbox.jl)
Release: [v0.0.3](https://github.com/lanaperisa/TensorToolbox.jl/releases/tag/v0.0.3)
Travis: [Travis Build Status](https://travis-ci.org/lanaperisa/TensorToolbox.jl/builds/290429839)
Diff: [vs v0.0.2](https://github.com/lanaperisa/TensorToolbox.jl/compare/e5ccce0b50d7cc3f545a365b6e136bc19b2cd5dc...8c23743f541ab2d78750b99bad5fb77897de7b07)
`requires` vs v0.0.2: no changes
cc: @lanaperisa

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
I think this should be retagged so that the tag gets the recent update to the REQUIRE file (dropping julia v0.5 support)?

**Comment by lanaperisa** [comment]
Oh, yes, thanks!

**Comment by KristofferC** [comment]
I still don't think the correct commit is included in the tag.

**Comment by lanaperisa** [comment]
I retaged the version as 0.1.0, this can be closed.

**Pull request closed without merging**
