### PR TITLE
Tag Homebrew v0.3.3

### PR DESCRIPTION
**Pull request by ranjanan**
cc: @ViralBShah @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
it's usually better if someone with commit acces does these, so they can push the git tag to https://github.com/JuliaLang/Homebrew.jl/releases

**Comment by ViralBShah** [comment]
I tagged it on Homebrew.jl.

**Comment by ViralBShah** [comment]
Should we use 0.4 as the minimum dependency here? Did we really use this in the 0.3 days?

**Comment by tkelman** [comment]
yes, staticfloat wanted to keep the rewrite working on 0.3.

**Comment by ranjanan** [comment]
Yes, Homebrew.jl works on v0.3.

**Comment by ViralBShah** [comment]
Merge then?

**Pull request merged**
