### PR TITLE
Register CirruParser

### PR DESCRIPTION
**Pull request by jiyinyiyong**

### CODE REVIEW

**Comment by milktrader** [comment]
I've rebooted travis since it looks like the error was upstream of this package.

@jiyinyiyong for`Pkg.add("CirruParser")` to work, you'll need to do a couple things.

`Pkg.update()`
`Pkg.tag("CirruParser", :patch)`

**Comment by milktrader** [comment]
Well, travis failed again on the Julia build with this
````bash
The command "curl -s -L --retry 7 'https://status.julialang.org/download/linux-x86_64' | tar -C ~/julia -x -z --strip-components=1 -f -" failed and exited with 2 during .
````
ping @staticfloat @tkelman

**Comment by tkelman** [comment]
I restarted it again and it seems to have worked this time. I think the DDOS on GitHub has picked up in intensity over the last day or two, causing all sorts of flaky downloads.

**Comment by jiyinyiyong** [comment]
@milktrader I just ran the commands you mentioned: https://github.com/Cirru/CirruParser.jl/tree/v0.0.2

**Comment by ViralBShah** [comment]
I think you need `Pkg.publish()` as well.

**Comment by jiyinyiyong** [comment]
I just did `git push` to update this PR. `Pkg.publish()` is really slow on my side. Hope it does break things.

**Pull request merged**
