### PR TITLE
Tag PeriodicTable.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rahulkp220/PeriodicTable.jl](https://github.com/rahulkp220/PeriodicTable.jl)
Release: [v0.1.0](https://github.com/rahulkp220/PeriodicTable.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/rahulkp220/PeriodicTable.jl/builds/426115894)
Diff: [vs v0.0.3](https://github.com/rahulkp220/PeriodicTable.jl/compare/3c6e6e41aa03cea6cf92c016dddca98e878fdcef...e0677666c8dc688434c1e695e185034375a88e95)
`requires` vs v0.0.3: no changes
cc: @rahulkp220

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by rahulkp220** [comment]
@crstnbr

**Comment by rahulkp220** [comment]
@andreasnoack How do I make the build successful for Julia 1.0 ? 
I see here, the Travis CI runner was able to run it for METADATA.jl

**Comment by andreasnoack** [comment]
You should delete these two lines, https://github.com/rahulkp220/PeriodicTable.jl/blob/master/.travis.yml#L16-L17,  from your .travis.yml

**Comment by rahulkp220** [comment]
Thank you very much @andreasnoack 👍 💯

**Pull request merged**
