### PR TITLE
Tag MixedModels 0.4.5 and add upper bounds on Stats Base for older releases

### PR DESCRIPTION
**Pull request by nalimilan**
See https://github.com/JuliaLang/METADATA.jl/pull/4695

### CODE REVIEW

**Comment by nalimilan** [comment]
@tkelman Is this correct? I don't really know how to test it.

**Comment by tkelman** [comment]
Yeah, I think a lower bound of just `0` works for major ver

**Comment by dmbates** [comment]
@nalimilan Is there anything I should be doing with respect to the MixedModels package to coordinate with this release of StatsBase?  I thought I had tagged a new version 0.4.5 of MixedModels with the modified REQUIRE file but now I can't find any trace of it.  I'm confused.

**Comment by andreasnoack** [comment]
Did you tag `MixedModels` independently from @nalimilan? Or are you talking about the same tag?

I've just merged a new version of `StatsBase` and restarted the tests there. I also accidentally added an extra merge commit the that I'll remove now. When the tests pass we can merge this.

**Comment by nalimilan** [comment]
@dmbates No, that's fine, your commit is in this PR.

**Comment by dmbates** [comment]
@nalimilan Okay.  Please let me know if there is something I need to do.

@andreasnoack Did the issue with the `Showoff` package for Julia v0.5.0-dev get resolved?  IIRC I can't test `MixedModels` with your PR for replacing the `chksquare` calls on v0.5 until `Showoff` is changed.

**Comment by andreasnoack** [comment]
Unfortunately not. I think that @dcjones might has been busy with something else lately. His github activity has been low the last couple of months.

**Comment by nalimilan** [comment]
The tests pass. Let's merge?

**Pull request merged**
