### PR TITLE
Tag InplaceOps v0.0.5

### PR DESCRIPTION
**Pull request by simonbyrne**
cc @KristofferC

### CODE REVIEW

**Comment by KristofferC** [comment]
Looks like the `REQUIRE` file also needs updating. Should probably be `julia 0.4`.

**Comment by KristofferC** [comment]
:tada:

**Comment by simonbyrne** [comment]
Blegh, that was messy. We need a better way to handle `Pkg` errors.

**Comment by tkelman** [comment]
Given that this is the first 0.4-only tag it should probably use a new minor package version.

**Pull request merged**
