### PR TITLE
Tag PyPlot.jl v2.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPy/PyPlot.jl](https://github.com/JuliaPy/PyPlot.jl)
Release: [v2.4.0](https://github.com/JuliaPy/PyPlot.jl/releases/tag/v2.4.0)
Diff: [vs v2.3.2](https://github.com/JuliaPy/PyPlot.jl/compare/4a5195ad158af5d8be9d97e9a7b792b63bafe56e...2c21a76adc380047538717c1df8c7c47d2501f04)
`requires` vs v2.3.2: 
```diff
--- 2.3.2/requires
+++ 2.4.0/requires
@@ -1,5 +1,5 @@
-julia 0.4
+julia 0.5
 PyCall 1.6.2
 Colors
 LaTeXStrings
-Compat 0.8.0
+Compat 0.32.0
```
cc: @stevengj

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Steven, we seem to failing the test for 2.4.0 of PyPlot, while passing tests with version 2.3.2. Both are using Conda on linux. Any thoughts as to why this would be? 

2.3.2: http://juliarun-ci.s3.amazonaws.com/82a46f755f87b2b0fd123422ef03621e6bd91d16/current_release_of_PyPlot_on_julia_0_6.log

2.4.0: http://juliarun-ci.s3.amazonaws.com/82a46f755f87b2b0fd123422ef03621e6bd91d16/pull_request_of_PyPlot_on_julia_0_6.log

**Comment by stevengj** [comment]
Has the Matplotlib backend changed? Are you using the MKL version of Julia (which might conflict with conda’s MKL, though I’m not sure why that would depend on the PyPlot version).

**Comment by aviks** [comment]
The tests are run at the same time, using the same disk image, once with the previous tag of the package, and once with the current tag. So its always using the same version of the dependencies. There is no MKL, this is a vanilla julialang/julia release.

**Comment by stevengj** [comment]
It looks like it is just a Conda update that is biting us (thanks to a ZLIB library conflict, https://github.com/JuliaPy/PyPlot.jl/issues/151).   You'll notice that the Conda package installation messages have changed significantly between the two logs you linked.  This doesn't seem related to the update of PyPlot.

**Comment by stevengj** [comment]
Again, the failure seems unrelated to the PyPlot update.  It is due to a zlib conflict between matplotlib and Julia on the latest version of Conda for Linux.

**Comment by andreasnoack** [comment]
I think we should go ahead and merge here then. However, we have now dropped 0.5 support so PyPlot would have to drop 0.5 and move the tag before we can merge.

**Comment by jebej** [comment]
Is there any way `travis.yml` can be modified to fix this issue? I'm also hitting this problem.

**Comment by andreasnoack** [comment]
> Is there any way travis.yml can be modified to fix this issue? I'm also hitting this problem.

I'm not sure I understand. PyPlot needs to bump the Julia requirement to 0.6.

**Comment by stevengj** [comment]
Closing this; will tag a new version that drops 0.5.

**Pull request closed without merging**
