### PR TITLE
Tag IntervalArithmetic.jl v0.11.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIntervals/IntervalArithmetic.jl](https://github.com/JuliaIntervals/IntervalArithmetic.jl)
Release: [v0.11.0](https://github.com/JuliaIntervals/IntervalArithmetic.jl/releases/tag/v0.11.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIntervals/IntervalArithmetic.jl/builds/244375367)
Diff: [vs v0.9.1](https://github.com/JuliaIntervals/IntervalArithmetic.jl/compare/64f72c729b6a4243cfdbcf8da9b5e126d116cd12...f4be4b6b831dee83ca3e1f683110d8043dd3ab47)
`requires` vs v0.9.1: 
```diff
--- 0.9.1/requires
+++ 0.11.0/requires
@@ -1,4 +1,7 @@
-julia 0.5
+julia 0.6-pre
 CRlibm 0.5
-StaticArrays 0.3
+StaticArrays 0.5
+FastRounding 0.0.4
+AdjacentFloats 0.0.5
 RecipesBase
+
```
cc: @dpsanders

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by dpsanders** [comment]
cc @lbenet

**Comment by tkelman** [comment]
does this replace https://github.com/JuliaLang/METADATA.jl/pull/9865 ?

**Comment by dpsanders** [comment]
No: #9865 (v0.10) is the last version supporting Julia 0.5; version v0.11 is the same code but with deprecation warnings removed for Julia 0.6.

**Comment by tkelman** [comment]
IntervalConstraintProgramming has a tolerance issue from this https://github.com/JuliaCI/pkg.julialang.org/blob/6066c6af620f543dc6351c42ff8c3b332a9c7bbe/logs/IntervalConstraintProgramming_0.6.log

**Comment by dpsanders** [comment]
Thanks, I think the problem is just that the meaning of a..b has subtley changed, so that the tests are no longer testing the correct thing.

**Pull request merged**
