### PR TITLE
Register Rsvg

### PR DESCRIPTION
**Pull request by lobingera**

### CODE REVIEW

**Comment by tkelman** [comment]
could you rebase and squash this into a single commit?

**Comment by tkelman** [comment]
You should also make the dependency on BinDeps (and Homebrew on osx) explicit instead of assuming they will be present as transitive dependencies.

**Comment by lobingera** [comment]
@tkelman : you mean adding in the REQUIRE of the package, or the require of metadata?

**Comment by tkelman** [comment]
Both. It's fine in metadata for now, if you plan on tagging another version soon then changing it just in the package is fine since it'll get picked up in the next tag.

**Comment by lobingera** [comment]
note to myself, learn more git...

**Pull request closed without merging**
