### PR TITLE
Tag FileIO.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaIO/FileIO.jl](https://github.com/JuliaIO/FileIO.jl)
Release: [v1.0.0](https://github.com/JuliaIO/FileIO.jl/releases/tag/v1.0.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaIO/FileIO.jl/builds/399639351)
Diff: [vs v0.9.1](https://github.com/JuliaIO/FileIO.jl/compare/429b5a7109116fd24b2eda1c7e6837f1ea781fde...fb403010ff0ad42c518150c2aac074ab51e58301)
`requires` vs v0.9.1: 
```diff
--- 0.9.1/requires
+++ 1.0.0/requires
@@ -1,2 +1 @@
-julia 0.6
-Compat 0.28.0
+julia 0.7-alpha
```
cc: @SimonDanisch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
cc: @timholy @fredrikekre @Datseris

**Comment by fredrikekre** [comment]
Perhaps `v.0.10.0`?

**Comment by SimonDanisch** [comment]
Fair point. I was seeing it as a big eyesore, but something that won't actually change the interface of FileIO, so having the fix in 1.1.x seems acceptable to me.

**Comment by fredrikekre** [comment]
But it is pretty broken, I can't even use FileIO to load stuff

**Comment by davidanthoff** [comment]
This version seems good enough for me to update all the file IO story in Queryverse to 0.7, so I'd be in favor of merging this here.

**Comment by SimonDanisch** [comment]
Yeah should be mostly working!

**Comment by davidanthoff** [comment]
So, can someone merge it?

**Pull request merged**
