### PR TITLE
Register new package PiecewiseDeterministicMarkovProcesses.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rveltz/PiecewiseDeterministicMarkovProcesses.jl](https://github.com/rveltz/PiecewiseDeterministicMarkovProcesses.jl)
Release: [v0.0.1](https://github.com/rveltz/PiecewiseDeterministicMarkovProcesses.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/rveltz/PiecewiseDeterministicMarkovProcesses.jl/builds/459963672)
cc: @rveltz

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@rveltz This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by rveltz** [comment]
I don't understand why I have this problem in Coverage. I dont get why my coverage is so low too compared to before

**Comment by andreasnoack** [comment]
It's a general problem. Coverage is currently not reliable.

**Comment by rveltz** [comment]
Does it mean it will be an official package?

**Comment by andreasnoack** [comment]
> Does it mean it will be an official package?

I don't understand the question.

**Comment by rveltz** [comment]
My pull request was accepted? Will I be able to install my package via `] add PiecewiseDeterministicMarkovProcesses`?

**Comment by andreasnoack** [comment]
> Will I be able to install my package via ] add PiecewiseDeterministicMarkovProcesses?

Yes. That should now be possible.

**Comment by rveltz** [comment]
Hi since my release, my package does not build anymore. Could it be related? The build cannot resolve the version

**Comment by andreasnoack** [comment]
Sounds unlikely but hard to tell without the error. Probably better to post the question on Discourse though. More eyes there.

**Pull request merged**
