### PR TITLE
Tag Spectra v0.1.0

### PR DESCRIPTION
**Pull request by charlesll**
Major revision with auto-installation of the Fortran dependency on Linux/OSX, and improved docs.

### CODE REVIEW

**Comment by tkelman** [comment]
Note that auto-installation at `Pkg.add` / `Pkg.build` time requires the build script to be located at `deps/build.jl`, you currently have it named `Dependencies/build.jl` which won't get used automatically.

**Comment by charlesll** [comment]
Thanks, I'm going to update that asap!

**Comment by charlesll** [comment]
It should now work well, I tried installations on Mac OSX and Fedora, with success.

**Comment by tkelman** [comment]
Do you want to make a new tag 0.1.1 for that?

**Comment by charlesll** [comment]
If you're OK with it, it is good with the 0.1.0 tag :)

**Comment by tkelman** [comment]
Having the `build.jl` file in `Dependencies` won't work automatically.

**Comment by charlesll** [comment]
I changed the name of Dependencies to deps as asked before ?

**Comment by tkelman** [comment]
But the 0.1.0 tag was made before that change.

**Comment by charlesll** [comment]
Ah ok sorry, of course I will create a new tag.

**Comment by charlesll** [comment]
Ok so I need to create a new pull request with the new tag I guess ?

**Comment by tkelman** [comment]
Either a new PR, or you can push the new commit to this same `pull-request/df46f2e7` branch of your METADATA fork.

**Comment by charlesll** [comment]
Oki thanks, I created a new pull request.

**Comment by tkelman** [comment]
included in #5497, closing this one

**Pull request closed without merging**
