### PR TITLE
Tag CausalInference.jl v0.3.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [mschauer/CausalInference.jl](https://github.com/mschauer/CausalInference.jl)
Release: [v0.3.1](https://github.com/mschauer/CausalInference.jl/releases/tag/v0.3.1)
Travis: [Travis Build Status](https://travis-ci.org/mschauer/CausalInference.jl/builds/421080554)
Diff: [vs v0.3.0](https://github.com/mschauer/CausalInference.jl/compare/60159cc3e1d54100ea8ebc61f5fdf477454c9073...879d168a2f86a69ecff944fe053b1d117feb9ec4)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.3.1/requires
@@ -1,3 +1,3 @@
-julia 0.6
-LightGraphs 0.9.0
-Combinatorics 0.4.1
+julia 0.7
+LightGraphs 0.13.0
+Combinatorics 0.6.0
```
cc: @mschauer

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
You'd have to make it a minor release when changing the required Julia version

**Comment by mschauer** [comment]
I would disagree, https://semver.org/spec/v2.0.0.html#spec-item-4, but can do.

**Comment by andreasnoack** [comment]
It might not be in accordance with semver but it has long been a formal requirement in METADATA and it was the reason why the tests failed.

**Comment by mschauer** [comment]
Ok, good to know.

**Pull request closed without merging**
