### PR TITLE
Tag Unitful.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ajkeller34/Unitful.jl](https://github.com/ajkeller34/Unitful.jl)
Release: [v0.1.0](https://github.com/ajkeller34/Unitful.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/ajkeller34/Unitful.jl/builds/203692333)
Diff: [vs v0.0.4](https://github.com/ajkeller34/Unitful.jl/compare/35f51c2905bc91e8999319819268062c22c117c2...0762a70a03250f518156335dc2389557fe1ee263)
`requires` vs v0.0.4: 
```diff
--- 0.0.4/requires
+++ 0.1.0/requires
@@ -1 +1,3 @@
 julia 0.5
+Compat 0.18.0
+Ranges
```
cc: @ajkeller34

### CODE REVIEW

**Comment by ajkeller34** [comment]
cc: @timholy

**Comment by tkelman** [comment]
There are quite a few `if VERSION` checks here where it would be preferable to be more specific

**Comment by ajkeller34** [comment]
I'm working on the various version checks but bisecting is taking quite some time. I'll retag once I've found them.

**Comment by timholy** [comment]
I propose that while I think it's OK to be unforgiving with version checks when it comes to Compat.jl, we should be a little more relaxed about this for other packages. It's just not worth spending hours on something for which the right answer is "update your julia-0.6". No one should be using julia-0.6 in production, and it gets better by the day anyway.

**Comment by tkelman** [comment]
Sure. If you know what behavior change you're testing for, then adding the few extra characters makes the package work on a wider range of prerelease versions which is incredibly valuable if the package ever triggers a bug in base that needs bisecting. It's not worth spending hours to bisect, but it is worth thinking about and adding the few extra digits if it doesn't take long to find them.

**Comment by ajkeller34** [comment]
As a good faith effort, I've added specific bounds to version checks in runtests.jl, along with some comments referencing the PR numbers. There's a couple remaining in the code itself but I think it may be more challenging to bisect for those. I've deleted the 0.1.0 release/tag, and will retag once CI is done.

**Comment by ajkeller34** [comment]
Good to merge as far as I'm concerned. Thanks!

**Pull request merged**
