### PR TITLE
Tag ExtremeStats.jl v0.0.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/ExtremeStats.jl](https://github.com/juliohm/ExtremeStats.jl)
Release: [v0.0.3](https://github.com/juliohm/ExtremeStats.jl/releases/tag/v0.0.3)
Diff: [vs v0.0.2](https://github.com/juliohm/ExtremeStats.jl/compare/e0074c1728491f3931ff87a0ae7a9e2cd0a9bbb7...234d290328cecfdec8cbc3336213835f8582d434)
`requires` vs v0.0.2: no changes
cc: @juliohm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by juliohm** [comment]
The build failure in Julia v0.7 is expected. This PR is ready to be merged.

I will be submitting a version with support to Julia v0.7 in the future.

**Comment by juliohm** [comment]
Similar build error after reopening

**Comment by juliohm** [comment]
@andreasnoack would you like to retry the build again or should it be merged?

**Comment by martinholters** [comment]
So is this usable on 0.7 or should it put an upper bound on the Julia version?

**Comment by juliohm** [comment]
Is Julia v0.7 released yet? All my packages don't have upper bounds. I am planning to tag a new version dropping support to v0.6 in the future.

**Comment by juliohm** [comment]
This release has a bug fix that I would like to share with users. I appreciate if someone can merge.

**Comment by juliohm** [comment]
In other words, I don't plan to add support to Julia v0.7 yet. This is something that I will do in the future by dropping support to v0.6 completely.

**Comment by quinnj** [comment]
You can put an upper bounds on 0.7 before dropping support for v0.6; we can merge anyway.

**Pull request merged**
