### PR TITLE
Tag NLSolversBase.jl v2.1.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/NLSolversBase.jl](https://github.com/JuliaNLSolvers/NLSolversBase.jl)
Release: [v2.1.2](https://github.com/JuliaNLSolvers/NLSolversBase.jl/releases/tag/v2.1.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaNLSolvers/NLSolversBase.jl/builds/235139842)
Diff: [vs v2.1.1](https://github.com/JuliaNLSolvers/NLSolversBase.jl/compare/a4dbd0d5b8f13b83773ae2c496778cc254b4aff0...e5ce9180428ce85b97e187f05406f3f5faaa0a36)
`requires` vs v2.1.1: no changes
cc: @pkofod

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by pkofod** [comment]
seems like an initialization problem, will investigate.

**Comment by tkelman** [comment]
this looks CI only. that same error happens o  pkgeval fairly often too http://pkg.julialang.org/detail/NLSolversBase

**Comment by pkofod** [comment]
> the changes since 2.1.1 look CI only, users won't see any difference in the code.

Alright, so you mean merge this as is, and then fix the bug in another patch?

**Comment by tkelman** [comment]
I mean this doesn't strictly need to be tagged as is, but if you want we can publish is anyway. Or hold off until you have an idea on fixing the bug and amend the release to include the user visible changes

**Comment by pkofod** [comment]
Oh, sure. Just close this then!

**Pull request closed without merging**
