### PR TITLE
Pull request/ff49f211

### PR DESCRIPTION
**Pull request by montyvesselinov**

### CODE REVIEW

**Comment by KristofferC** [comment]
`ERROR: LoadError: Repository name Kriging does not end in .jl`, see also https://github.com/JuliaLang/METADATA.jl/issues/9480.

**Comment by montyvesselinov** [comment]
Repo has been renamed.

-monty

**Comment by KristofferC** [comment]
Could you please make a new PR or update this one?

**Comment by montyvesselinov** [comment]
I will submit new one

**Comment by montyvesselinov** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/11430

**Pull request closed without merging**
