### PR TITLE
Register new package PolaronMobility.jl v1.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jarvist/PolaronMobility.jl](https://github.com/jarvist/PolaronMobility.jl)
Release: [v1.0.1](https://github.com/jarvist/PolaronMobility.jl/releases/tag/v1.0.1)
cc: @jarvist

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@jarvist This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by jarvist** [comment]
The JuliaCIBot failed with what looks like configuration / missing API key errors.
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
0615d00fa606b0cccb323f090404836ba15c7d69/PolaronMobility_julia_0_6.log
</Key>
<RequestId>E5D8E1B90DD555C1</RequestId>
<HostId>
ykm2a52mhsvCkxgvXUowkPklvZCQME65xLbXDkB8MoDs+VxH/VJZvaPowQhUpivmHZ3DCTuXL54=
</HostId>
</Error>
```

**Comment by andreasnoack** [comment]
Please, upper bound Julia in the REQUIRE file if Julia 0.7/1.0 isn't supported.

**Comment by jarvist** [comment]
OK @andreasnoack ; hope I got that right. (Edited for correct github username! Apologies.)
I have a separate branch mostly working on 1.0, and will move over to that once a 0.6 working one for people today is available.

**Comment by jarvist** [comment]
@andreasnoack a gentle bump.

**Pull request merged**
