### PR TITLE
Tag BioServices.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BioJulia/BioServices.jl](https://github.com/BioJulia/BioServices.jl)
Release: [v0.2.0](https://github.com/BioJulia/BioServices.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/BioJulia/BioServices.jl/builds/405385177)
Diff: [vs v0.1.3](https://github.com/BioJulia/BioServices.jl/compare/d74a3264794ee00a89f3fc75943868c32749736b...df68418a2c554ef7248d2a5c79a24d542657117d)
`requires` vs v0.1.3: no changes
cc: @bicycle1885

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by TransGirlCodes** [comment]
There's a single line in CHANGELOG.md that needs changing.

`[Unreleased]: https://github.com/BioJulia/BioServices.jl/compare/v0.1.3...HEAD`
should now be
`[Unreleased]: https://github.com/BioJulia/BioServices.jl/compare/v0.2.0...HEAD`

**Comment by bicycle1885** [comment]
I've fixed it.

**Comment by TransGirlCodes** [comment]
Thanks @bicycle1885! This will make the tests pass on the changes I'm prepping on Bio before juliacon :)

**Comment by bicycle1885** [comment]
Oh, I didn't know you'll go. Unfortunately, I cannot this year 😢

**Comment by TransGirlCodes** [comment]
Is there a reason this is held up? The CI passes, and the log of JuliaCIBot for julia 0.6 looks like it completes ok.

**Comment by aviks** [comment]
@nkottary Another one for you -- why do the tests fail here?

**Comment by TransGirlCodes** [comment]
Can this be merged if somethings up with the JuliaCIBot? There's a dependent package I'd like to cut a release of before JuliaCon :)

**Comment by andreasnoack** [comment]
Yes. We have had some issues with CIBot lately but it shouldn't hold this one back any longer.

**Pull request merged**
