### PR TITLE
Tag DataArrays.jl v0.7.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/DataArrays.jl](https://github.com/JuliaStats/DataArrays.jl)
Release: [v0.7.0](https://github.com/JuliaStats/DataArrays.jl/releases/tag/v0.7.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/DataArrays.jl/builds/266596995)
Diff: [vs v0.6.2](https://github.com/JuliaStats/DataArrays.jl/compare/78327d1e6a8cd27c44d9afbaec419caf6a98893c...8b9e89617ca3539440a9a1b2fc75fc44f86ec850)
`requires` vs v0.6.2: no changes
cc: @ararslan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
This seems to have a genuine failure in a dependent project

**Comment by ararslan** [comment]
Yes, we expect this to be breaking.

**Comment by davidanthoff** [comment]
Shouldn't there be a PR to METADATA first that puts an upper bound on the DataArrays line in the REQUIRE files of all the packages (and all their versions) that would otherwise be broken by this? I feel pretty strongly that DataArrays is too embedded in the overall julia ecosystem to just break downstream packages and then fix things later.

Also, which packages is JuliaCIBot testing here? Anything that relies on DataArrays? Why is it not testing DataFrames in that case, which I assume would also be broken by this PR?

**Comment by aviks** [comment]
JuliaCIBot tests a random sample of 5 packages out of all the dependencies. 

Don't have an answer to your other questions, will defer to others who do.

**Comment by davidanthoff** [comment]
Ah, good to know! I think there will be way, way more than 5 packages that will be broken by this, including DataFrames.jl.

So, I think this PR can't be merged until the whole dependency situation is sorted out with PRs against METADATA that add upper bounds on *lots* of packages. I think if this PR here would just get merged without that, all hell would break lose. There would be dozens, if not hundreds, of packages that will stop working on any user system where someone executes ``Pkg.update()``, which seems unacceptable to me.

@tkelman you have a better sense of this, what is your take on this?

**Comment by ararslan** [comment]
I have no idea which packages would be broken by this change, and it would be intractable to install every package that depends on DataArrays, run their tests, and determine whether any failures that arise are related to this particular change. If @tkelman is around, he might be able to do a custom run of PkgEval with this tag; I think he's done that for breaking changes in other packages.

**Comment by davidanthoff** [comment]
I think a full PkgEval run would be good for this PR. But minimally DataFrames should be bounded, we know that it would break with this PR and we know that a lot of stuff depends on that, right?

**Comment by tkelman** [comment]
I'd advise rebasing this branch then doing something like https://github.com/JuliaCI/PackageEvaluator.jl/commit/01a7bfaee2d62a8df00fddcce5d74efd7f186803

**Comment by MikeInnes** [comment]
what's the status on this?

**Comment by ararslan** [comment]
Needs a PkgEval run to determine the extent of the breakage, haven't had a chance to do that yet.

**Comment by nalimilan** [comment]
Closing since we'll tag a release which also ports DataArrays to Nulls. That will avoid breaking dependencies twice in a row.

**Pull request closed without merging**
