### PR TITLE
Docs release for FlatBuffers

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by tkelman** [comment]
hardly worth tagging for 2 commits that don't change any user-visible code? https://github.com/JuliaData/FlatBuffers.jl/compare/v0.1.2...v0.1.3

**Comment by quinnj** [comment]
It's just a docs release so that Documenter will publish a new "stable" set of docs. The previous set somehow got borked in the move from dmbates/FlatBuffers to JuliaData/FlatBuffers

**Comment by tkelman** [comment]
Ah okay, Documenter needs things to be tagged? Didn't realize that.

**Comment by quinnj** [comment]
Yeah, for the "stable" docs, it makes and commits docs from the latest git tag that runs successfully on travis. You can obviously make the docs manually, but in this case, I find it easier to just tag a new release and let it all happen automatically.

**Pull request merged**
