### PR TITLE
Tag Images.jl v0.15.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaImages/Images.jl](https://github.com/JuliaImages/Images.jl)
Release: [v0.15.0](https://github.com/JuliaImages/Images.jl/releases/tag/v0.15.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaImages/Images.jl/builds/419037547)
Diff: [vs v0.14.0](https://github.com/JuliaImages/Images.jl/compare/601f750e4144432551f6e94f362a6a53c49727ee...d39453048842e3be0412fc18d63b20db47ea3502)
`requires` vs v0.14.0: 
```diff
--- 0.14.0/requires
+++ 0.15.0/requires
@@ -1,4 +1,4 @@
-julia 0.6.0
+julia 0.7
 Reexport
 Colors 0.7.0
 ColorVectorSpace 0.2
@@ -17,7 +17,7 @@
 StaticArrays
 Graphics 0.1
 FileIO
-Compat 0.19
 StatsBase 0.14   # for histrange
 Requires
 OffsetArrays
+TiledIteration
```
cc: @Evizero

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by Evizero** [comment]
cc @timholy

**Comment by tknopp** [comment]
yeahhh!!! Thanks so much @Evizero and @timholy and all involved.

**Comment by Evizero** [comment]
A really big part of the hard work was done by @RalphAS ! my involvement was more administrative

**Comment by tknopp** [comment]
Thanks so much @RalphAS!

**Pull request merged**
