### PR TITLE
Tag MXNet.jl v0.0.6

### PR DESCRIPTION
**Pull request by pluskid**
Mostly for fixing a breaking change introduced in the upstream libmxnet. See dmlc/MXNet.jl#42. Other changes:

* Variants of Xaiver initializers (@vchuravy)
* More arithmetic operators on symbolic nodes
* Basic interface for symbolic node attributes (@vchuravy)

### CODE REVIEW

**Comment by kshyatt** [comment]
Is the registration for SimpleStructs supposed to be on this PR?

**Comment by pluskid** [comment]
@kshyatt Oh, no. Sorry, It should not.

**Comment by pluskid** [comment]
Is there a simple or recommended way to get rid of that?

**Comment by kshyatt** [comment]
You could make a new branch from `metadata-v2` and `git cherry-pick` the MXNet commit?

**Comment by pluskid** [comment]
@kshyatt Thanks!

Closing in favor for #4139

**Pull request closed without merging**
