### PR TITLE
Register new package EffectiveWaves.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [arturgower/EffectiveWaves.jl](https://github.com/arturgower/EffectiveWaves.jl)
Release: [v0.1.0](https://github.com/arturgower/EffectiveWaves.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/arturgower/EffectiveWaves.jl/builds/444346883)
cc: @arturgower

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@arturgower This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by arturgower** [comment]
The only tests that are failing are for Julia  version > 0.7. This tag was only set to run on Julia 0.6, where all tests have passed. So can you go ahead and please merge?

**Comment by andreasnoack** [comment]
Please add upper bounds in the REQUIRE file if Julia 0.7 and 1.0 are not support.

**Comment by andreasnoack** [comment]
Please add upper bounds on julia if versions 0.7 and 1.0 are not supported.

**Comment by andreasnoack** [comment]
Please add upper bounds on julia if versions 0.7 and 1.0 are not supported.

**Comment by arturgower** [comment]
I'm going to fix the REQUIRE file and then submit a new register request.

**Comment by arturgower** [comment]
I have submitted a new release with a fixed require file, though I used a different tag and name. Please ignore this one.

**Comment by arturgower** [comment]
I corrected the REQUIRE file, then created a new release with the same tag. 
Now How do I get the JuliaCIBot to redo the tests? They should pass now.

**Comment by andreasnoack** [comment]
Assume you followed the steps in https://github.com/attobot/attobot#updatingdeleting-a-release. GitHub has had some issue today so that might explain why the PR hasn't been updated. Maybe try again in an hour. Once the update is going through then CIBot will automatically run the tests again.

**Comment by fredrikekre** [comment]
> then created a new release with the same tag

You need to remove the tag and the release and then redo it. After that this PR should will be updated automatically, see https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by arturgower** [comment]
Thanks for the help.

I have re-done [all the steps for updating](https://github.com/attobot/attobot#updatingdeleting-a-release) i.e. I deleted the Release, then deleted the tag v0.1.0, then created a new Release with the tag v0.1.0. But it still seems that the checks/test did not restart (the date logged on this Travis test is yesterday).

You can see that my [new, and now only, release](https://github.com/arturgower/EffectiveWaves.jl/releases/tag/v0.1.0) is only a few hours old, but the tests were performed yesterday, and attobot has not sent me any email about this new release. What am I missing??

**Comment by andreasnoack** [comment]
GitHub still hasn't recovered completely so give it some more time and then try to repeat the procedure if Attobot hasn't triggered a new build.

**Comment by arturgower** [comment]
Thank you both @andreasnoack and @fredrikekre. In the end it was just a problem with github.

**Pull request merged**
