### PR TITLE
Register IQSIM

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by jiahao** [comment]
See http://julia.readthedocs.org/en/latest/manual/packages/#guidelines-for-naming-a-package

How about calling it ImageQuilting?

**Comment by juliohm** [comment]
Mainly due to historical reasons. Previous algorithms developed in the
field follow this naming convention: ccsim, sgsim, ...

Also I want to emphasize that this package is for geostatistical
simulation, not only image quilting as in my previous package
ImageQuilting.jl.

**Comment by juliohm** [comment]
Could you please merge the pull request?

**Comment by jiahao** [comment]
I don't think the name 'IQSIM' is sufficiently meaningful to qualify as a package name.

Again, see http://julia.readthedocs.org/en/latest/manual/packages/#guidelines-for-naming-a-package

> Package names should be sensible to most Julia users, even to those who are not domain experts.

**Comment by juliohm** [comment]
Such naming convention rules shouldn't be applied to all packages,
specially those that are meant for domain experts. Probably less than 10
people in the world are interested in this package.

Naming it differently to a more verbose sentence will just make researchers
in the field confused and will also take the new name out of the list of
available names to choose from in the future.

The other package ImageQuilting.jl that I registered months ago is more
useful to the general scientific community and as so deserves a clear name.
This new package unfortunately doesn't have a clear short mnemonic name.

Could you please reconsider it?

**Comment by tkelman** [comment]
> Probably less than 10 people in the world are interested in this package.

Then does it really need to be registered? It can still be easily installed via `Pkg.clone` with the url.

**Comment by juliohm** [comment]
Registration means having versions in this case.

**Comment by juliohm** [comment]
This package won't be merged because of its name? I'm about to present the
code in a conference, please tell me if it won't be merged.

**Comment by Keno** [comment]
Nobody said anything about not merging this package. Since METADATA is a global namespace we have to make sure that names are appropriate and recognizable. That is a normal part of any pull request. I suspect we may end up merging it with the current name, even if it's not descriptive. This has happened for a few other packages, but all of those had discussion.

**Comment by dpsanders** [comment]
> Registration means having versions in this case.

You can still tag versions in your personal repository even if the package is not registered. Is that what you meant by "versions"?

I agree that the name IQSIM is too non-descriptive. Googling "IQSIM" and "IQSIM image quilting" don't seem to throw up anything.

**Comment by StefanKarpinski** [comment]
The description of the package is "3D image quilting simulation"... so it seems pretty specific to image quilting. What's the difference between this package and the other registered ImageQuilting package?

**Comment by juliohm** [comment]
This package is about Geostatistics. It's about generating samples that
reproduce the patterns in an image and honor Q-Q plots, trends, etc. It
fits in the statistics organization.

The previous package is simply a 2D draft on how to paste images together
without loosing texture. It can be considered an image processing algorithm.

**Comment by dpsanders** [comment]
So how about the package name `GeostatisticsIQSIM`?

**Comment by juliohm** [comment]
I don't think the change makes the name clearer.

I have plans to deprecate this package in the future and create a whole set
of geostatistical algorithms in Julia (GeoStats.jl). Don't have the time to
do it now because of other priorities.

Think of this package as an intermediate step to a larger contribution from
the geostats community. I'm trying to bring them to start using Julia.

**Comment by jiahao** [comment]
I don't think it is a good idea to register a package, knowing full well that it will be deprecated in the future. I'm sorry you feel that our rules are annoying, but one of the reasons why we are so strict about package names now is because we don't have a good mechanism for handling deprecations and renaming (#347).

**Comment by juliohm** [comment]
So it won't be merged?

**Comment by jiahao** [comment]
Since you plan to have a more comprehensive package planned, how about registering this package as `GeoStats.jl` and provide IQSIM as a function within that package?

**Comment by juliohm** [comment]
I was trying to avoid this responsibility of maintaining a more
comprehensive package at this moment. I will rename it to GeoStats.jl by
tomorrow if that is the only way to get the code merged.

**Comment by tkelman** [comment]
I wouldn't consider it a whole lot of responsibility to claim a recognizable name for the initial package, as long as you don't disappear completely. If someone else comes along in the future who's interested in geostatistics and wants to see more functionality in the package than what you're able to write by then, then you can add them as a collaborator and figure out how to jointly make the most effective progress. That's what has happened informally with various organizations like JuliaOpt, JuliaStats, JuliaQuantum, JuliaWeb, etc which is the closest thing we've got at the moment to namespacing.

**Comment by StefanKarpinski** [comment]
I don't really get it. This package is only of interest to ten people in the world and is already planned to be deprecated. Why does it make sense to have it in the metadata registry? How is not having it registered preventing you from doing anything?

**Comment by juliohm** [comment]
Hi Stefan, I would like the package to be part of the Julia package
ecosystem and also take advantage of versions.

I'll just rename it to GeoStats.jl

**Comment by ViralBShah** [comment]
Fantastic. Closing this one then.

**Comment by juliohm** [comment]
Reconsidering all the discussion, I'll just release a new version of the previous ImageQuilting.jl package instead of creating a new repository.

**Pull request closed without merging**
