### PR TITLE
Pull request/eda8175d

### PR DESCRIPTION
**Pull request by femtotrader**

### CODE REVIEW

**Comment by tkelman** [comment]
looks like the first two tags in here should be removed, the first one claims to support 0.5 but uses 0.6 syntax

**Comment by femtotrader** [comment]
@tkelman you are right but how can I do this?

I had a look at https://github.com/JuliaLang/PkgDev.jl/issues/39 but it doesn't help

**Comment by femtotrader** [comment]
I did it manually

```bash
git clone https://github.com/femtotrader/METADATA.jl
cd METADATA.jl
git checkout pull-request/eda8175d
git rm TimeFrames/versions/0.0.7/ -r
git rm TimeFrames/versions/0.0.8/ -r
```

it should be ok now (except if you want me to squash commits).
But I can do if you prefer

**Comment by femtotrader** [comment]
Done with https://github.com/JuliaLang/METADATA.jl/pull/10191

**Pull request closed without merging**
