### PR TITLE
Tag Hecke.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [thofma/Hecke.jl](https://github.com/thofma/Hecke.jl)
Release: [v0.2.1](https://github.com/thofma/Hecke.jl/releases/tag/v0.2.1)
Travis: [Travis Build Status](https://travis-ci.org/thofma/Hecke.jl/builds/236747496)
Diff: [vs v0.2.0](https://github.com/thofma/Hecke.jl/compare/a3ac0f678dd9826eadff59425d98df1a0580711b...6319226d4b6a731d82c289809337b57be46ee86a)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.2.1/requires
@@ -1,2 +1,2 @@
 julia 0.5
-Nemo 0.6.0 0.6.2
+Nemo 0.6
```
cc: @thofma

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by thofma** [comment]
By the way, I noticed that while the tests of Hecke passing on 0.6.rc1, they are failing on 0.6.rc2. How should I proceed?

**Comment by tkelman** [comment]
Hm, that's not good. What's the failure, and can you bisect to identify what caused it?

**Comment by thofma** [comment]
If I use the debug build, then he already fails when loading Hecke. I think it is the same failure the JuliaCIBot sees on 0.7.dev.

This is with Hecke v0.2.1 (the tag of this PR here).

```julia
julia> versioninfo()
Julia Version 0.6.0-rc2.0
Commit 68e911b (2017-05-18 02:31 UTC)
DEBUG build
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, nehalem)

julia> using Hecke

Welcome to Nemo version 0.6.0

Nemo comes with absolutely no warranty whatsoever

Welcome to FPlll version 0.1
juliagit: /home/thofmann/julia/julia-git/src/gf.c:1326: jl_method_instance_add_backedge: Assertion `callee->min_world <= caller->min_world && callee->max_world >= caller->max_world' failed.

signal (6): Aborted
while loading no file, in expression starting on line 0
raise at /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56
abort at /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:89
__assert_fail_base at /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:92
__assert_fail at /build/eglibc-oGUzwX/eglibc-2.19/assert/assert.c:101
jl_method_instance_add_backedge at /home/thofmann/julia/julia-git/src/gf.c:1326
jl_insert_backedges at /home/thofmann/julia/julia-git/src/dump.c:2229
_jl_restore_incremental at /home/thofmann/julia/julia-git/src/dump.c:3282
jl_restore_incremental at /home/thofmann/julia/julia-git/src/dump.c:3321
_include_from_serialized at ./loading.jl:157
_require_from_serialized at ./loading.jl:200
unknown function (ip: 0x7fd8b46988f0)
jl_call_fptr_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:337
jl_call_method_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:356
jl_apply_generic at /home/thofmann/julia/julia-git/src/gf.c:1930
_require_search_from_serialized at ./loading.jl:236
unknown function (ip: 0x7fd8b46991a0)
jl_call_fptr_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:337
jl_call_method_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:356
jl_apply_generic at /home/thofmann/julia/julia-git/src/gf.c:1930
_require at ./loading.jl:434
require at ./loading.jl:398
unknown function (ip: 0x7fd8b469b2cb)
jl_call_fptr_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:337
jl_call_method_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:356
jl_apply_generic at /home/thofmann/julia/julia-git/src/gf.c:1930
jl_apply at /home/thofmann/julia/julia-git/src/julia.h:1422
eval_import_path_ at /home/thofmann/julia/julia-git/src/toplevel.c:401
eval_import_path at /home/thofmann/julia/julia-git/src/toplevel.c:428
jl_toplevel_eval_flex at /home/thofmann/julia/julia-git/src/toplevel.c:493
jl_toplevel_eval at /home/thofmann/julia/julia-git/src/toplevel.c:598
jl_toplevel_eval_in at /home/thofmann/julia/julia-git/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7fd8b44f480f)
jl_call_fptr_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:337
jl_call_method_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:356
jl_apply_generic at /home/thofmann/julia/julia-git/src/gf.c:1930
eval_user_input at ./REPL.jl:66
unknown function (ip: 0x7fd8b459ed0f)
jl_call_fptr_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:337
jl_call_method_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:356
jl_apply_generic at /home/thofmann/julia/julia-git/src/gf.c:1930
macro expansion at ./REPL.jl:97 [inlined]
#1 at ./event.jl:73
unknown function (ip: 0x7fd89805a5af)
jl_call_fptr_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:337
jl_call_method_internal at /home/thofmann/julia/julia-git/src/julia_internal.h:356
jl_apply_generic at /home/thofmann/julia/julia-git/src/gf.c:1930
jl_apply at /home/thofmann/julia/julia-git/src/julia.h:1422
start_task at /home/thofmann/julia/julia-git/src/task.c:267
unknown function (ip: 0xffffffffffffffff)
Allocations: 3478379 (Pool: 3476726; Big: 1653); GC: 5
Aborted (core dumped)
```

I can try to bisect today or tomorrow.

**Comment by thofma** [comment]
Ok, found it. It was between pre-beta and rc1: https://github.com/JuliaLang/julia/pull/21307/commits/5e709e46458f8a1cc566d75718b385a63ac9d917
Note that https://github.com/JuliaLang/julia/pull/21307/commits/8d16ddda75cfe26fdf8e1a9fea589d8170fe9585 did not fix it.

It only shows up with precompilation turned on and compiled using `make debug`.

**Comment by tkelman** [comment]
I'm seeing an assertion failure on both release-0.6 and master. Worth reporting an issue, especially if you have a smaller test case that can trigger it.

**Comment by thofma** [comment]
There are two different errors. The precompilation error is now https://github.com/JuliaLang/julia/issues/22158.

**Pull request merged**
