### PR TITLE
Tag TextParse.jl v0.6.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaComputing/TextParse.jl](https://github.com/JuliaComputing/TextParse.jl)
Release: [v0.6.1](https://github.com/JuliaComputing/TextParse.jl/releases/tag/v0.6.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaComputing/TextParse.jl/builds/444143034)
Diff: [vs v0.6.0](https://github.com/JuliaComputing/TextParse.jl/compare/c8c7a27076c3051898535b1c04c1aee8fa62aaa8...73da796e5913d9c45f47a833351ca107a5361b0f)
`requires` vs v0.6.0: 
```diff
--- 0.6.0/requires
+++ 0.6.1/requires
@@ -1,7 +1,7 @@
-julia 0.7-alpha
-Compat 0.17
+julia 0.7
 PooledArrays 0.2.0
 Nullables
 DataStructures
 WeakRefStrings 0.4.4
 CodecZlib
+DoubleFloats
```
cc: @davidanthoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Don't merge this, there seems to be still a bug!

**Comment by davidanthoff** [comment]
Alright, now ready to be merged!

**Comment by andreasnoack** [comment]
Remember not to comment when things are good.

**Comment by davidanthoff** [comment]
> Remember not to comment when things are good.

Ah, I didn't know that! Unless I have missed it, maybe it might be a good idea to have a discourse post that outlines current best practices for this kind of thing?

**Comment by andreasnoack** [comment]
No problem. I've mentioned it to you before where you expressed your satisfaction with things getting automated. The current best practice isn't documented which isn't great but I thought I'd wait until we migrate to a new system with release PRs against the general registry. However, it's uncertain when it will happen so maybe I'll write a discouse post about the current practice anyway.

**Comment by andreasnoack** [comment]
No problem. I've mentioned once before where you expressed your satisfaction with the process being automated. I might write a post on discourse about the current practice but actually planned on waiting for the new system with PRs against the general registry. However, we don't know when that will happen.

**Comment by davidanthoff** [comment]
> I've mentioned once before where you expressed your satisfaction with the process being automated.

Haha, I'm too old to remember things for more than a few days :)

**Comment by andreasnoack** [comment]
See https://discourse.julialang.org/t/the-current-metadata-release-process/16672

**Pull request merged**
