### PR TITLE
Register new package CTPSS.jl v0.1.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [PharmCat/CTPSS.jl](https://github.com/PharmCat/CTPSS.jl)
Release: [v0.1.5](https://github.com/PharmCat/CTPSS.jl/releases/tag/v0.1.5)
cc: @PharmCat

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@PharmCat This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use abbreviations in package names.

**Comment by PharmCat** [comment]
ClinicalTrialPowerAndSampleSize - it is to long name.
ClinicalTrialSampleSize - already used (no developing)
TrialSize - used in R Project library
CT is a common abbreviation for clinicat trial

If CTPSS not recommended, is it possible to use "SampleSize" name or "CTsize"?

**Comment by dpsanders** [comment]
`ClinicalTrialPowerSampleSize.jl` seems good to me.

**Comment by dpsanders** [comment]
Or you could just take over the previous package name if the author agrees.

**Comment by PharmCat** [comment]
I checked name "TrialUtils" - no conflicts I found. Can i use it?

Should i change the module name and names in other files?

**Comment by dpsanders** [comment]
Maybe then `ClinicalTrialUtilities.jl`? `Trial` is too generic a word without specifying the domain.

Yes, you will need to change all the names, then make a new release from the new repository name.

**Comment by PharmCat** [comment]
Ok. ClinicalTrialUtilities.jl - will be done ASAP.

**Pull request closed without merging**
