### PR TITLE
Update EllipticFEM to version v0.0.2.

### PR DESCRIPTION
**Pull request by gerhardtulzer**
I corrected a problem with the folder structure. Now the version should work fine.

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like there's still a test issue? https://travis-ci.org/gerhardtulzer/EllipticFEM.jl/jobs/202271402
```
ERROR: LoadError: LoadError: MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Array{Float64,2}
This may have arisen from a call to the constructor Array{Float64,2}(...),
since type constructors fall back to convert methods.
 in meshDataElementsInitializeNablaFTsVolumesCentroidsAndMeshsizes(::MeshData) at /home/travis/.julia/v0.5/EllipticFEM/test/./Elliptic/../../src/MeshData/./meshDataElementsInitializeNablaFTsVolumesCentroidsAndMeshsizes.jl:31
 in geoDataToMeshData(::GeoData, ::Float64) at /home/travis/.julia/v0.5/EllipticFEM/test/./Elliptic/../../src/EquationData to GeoData to MeshData/geoDataToMeshData.jl:20
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/travis/.julia/v0.5/EllipticFEM/test/./Elliptic/runElliptic.jl, in expression starting on line 43
while loading /home/travis/.julia/v0.5/EllipticFEM/test/runtests.jl, in expression starting on line 6
```

Does `Pkg.test("EllipticFEM")` pass for you locally?

**Comment by gerhardtulzer** [comment]
Yes, locally it passes.

**Comment by tkelman** [comment]
Looks like this broke DriftDiffusionSystems.jl on Julia 0.4 http://pkg.julialang.org/logs/DriftDiffusionPoissonSystems_0.4.log

**Comment by gerhardtulzer** [comment]
Ok, but I don't understand why. As far as I see the last merge of DriftDiffusionPoissonSystems removed the dependence on EllipticFEM?

**Comment by tkelman** [comment]
but only on Julia 0.5 - on Julia 0.4 its latest version still depends on EllipticFEM

**Comment by tkelman** [comment]
It would be worthwhile to add a package description other than "No description, website, or topics provided." That will be populated into the listing at pkg.julialang.org

**Pull request merged**
