### PR TITLE
Tag ScikitLearn.jl v0.5.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [cstjean/ScikitLearn.jl](https://github.com/cstjean/ScikitLearn.jl)
Release: [v0.5.0](https://github.com/cstjean/ScikitLearn.jl/releases/tag/v0.5.0)
Travis: [Travis Build Status](https://travis-ci.org/cstjean/ScikitLearn.jl/builds/421125283)
Diff: [vs v0.4.0](https://github.com/cstjean/ScikitLearn.jl/compare/216bb6e8c02c75c69b37a19ddb3844cf662e4529...92377f3fa3326e1968dbb493a3dbc3ec0f3d71ad)
`requires` vs v0.4.0: 
```diff
--- 0.4.0/requires
+++ 0.5.0/requires
@@ -1,4 +1,4 @@
-julia 0.6
+julia 0.7
 PyCall 1.6.2
 Parameters 0.3.0
 MacroTools 0.3.0
```
cc: @cstjean

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
The CIBot tests currently fail because Mocking includes a project file. Later today there might be a new release of Mocking without a project file so I'll restart the tests once it has been released.

**Comment by andreasnoack** [comment]
Please add an upper bound if Julia 1.0 isn't supported.

**Comment by cstjean** [comment]
I have a new version for 1.0 already (barring a few problems with PyCall and RDatasets not being quite 1.0-compatible). I've just been waiting for this PR to be pulled into metadata to release 0.5.1.

**Comment by cstjean** [comment]
Should I just update the attobot PR? I thought that it would be simpler to review the much smaller diff from the next tag, than to restart the review process.

**Comment by andreasnoack** [comment]
I'd just move (delete and reapply) the tag here instead. I'm not sure what you mean by "restart the review process". The only thing we do here (almost) is to check that tests pass.

**Comment by andreasnoack** [comment]
There still isn't an upper bound on Julia

**Comment by cstjean** [comment]
As I've said above, the remaining tests failures are, to the best of my knowledge, PyCall and RDatasets failures on 1.0. Otherwise the package seems to work perfectly fine on 1.0.

**Comment by andreasnoack** [comment]
I misunderstood. I thought you had a version different from this one for 1.0. RDatasets was release in a 1.0 compatible version a while ago and PyCall for 1.0 was merged earlier today so I'll try to restart tests.

**Comment by cstjean** [comment]
There's still an error, AFAICT because of PyCall/Base. https://github.com/JuliaPy/PyCall.jl/issues/555

I know you're not the only person involved in setting the rules for METADATA, but I find the policy to insist on 100% test success a bit frustrating. I haven't added functionality to this package in forever. I'm just trying to fight code rot, but because I'm "just" fixing 80% of the new test failures, we can't merge into METADATA, even though the new tag is a clear improvement on all fronts. [Last time](https://github.com/JuliaLang/METADATA.jl/pull/13293), I updated ScikitLearn for the new DataFrames release in February, but it took me four months to find the time to deal with 100% of the issues. During those four months, all new users of ScikitLearn saw their DataFrames.jl install downgraded, even though the `master` was perfectly good. It's hardly ideal.

**Comment by andreasnoack** [comment]
Hm. For some reason, CIBot seems to get stuck when trying to process this package so I'll go ahead an merge. Regarding your comment then, generally, I think passing test is a reasonable minimum requirement for a release. Hopefully, things will be more stable now and in the future, it should also be easier to avoid that a single package keeps other packages on lower versions for all projects.

**Comment by cstjean** [comment]
Thanks!

**Pull request merged**
