### PR TITLE
Tag mPulseAPI v1.0.2

### PR DESCRIPTION
**Pull request by bluesmoon**
Updated prerequisites, documentation, and added support for julia DateTime in filters.

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like you still have to push the tag to the project's repo. See https://travis-ci.org/JuliaLang/METADATA.jl/builds/168991631#L209

**Comment by bluesmoon** [comment]
Apologies, I just pushed it.

**Comment by ararslan** [comment]
Okay great. Can you close and reopen the PR to restart the Travis check?

**Comment by ararslan** [comment]
I don't mean open a new one--you can just click "reopen" on this one.

**Comment by bluesmoon** [comment]
I suppose it's too late for that :) the other one completed successfully

**Comment by bluesmoon** [comment]
also it looks like I don't have permission to reopen issues.

**Pull request closed without merging**
