### PR TITLE
Register Taste: v0.0.0

### PR DESCRIPTION
**Pull request by jiahao**
A simple package to support Integrated Demand-driven Instant Olfaction Technology Screens

### CODE REVIEW

**Comment by IainNZ** [comment]
Haha wow

**Comment by kmsquire** [comment]
That's funny, they must have released those at least 3 hours earlier on the US east coast than here on the west coast.

**Comment by dcjones** [comment]
Yep, this checks out.
bananna
jerky

**Comment by timholy** [comment]
Great tests! Can you contribute them to `runtests.jl`, please?

**Comment by ViralBShah** [comment]
What is this stuff? I must say it is the most bizarre julia thing I have seen, and replaces the light sensor theramin for the top spot!

**Comment by jiahao** [comment]
This package exposes undocumented functionality on some notebooks for gustatory input. Older machines have much more primitive sensors, and you may need to apply the sample directly to your screen or other sensor array to get reliable readings.

**Comment by IainNZ** [comment]
:dead:

**Comment by jiahao** [comment]
b2c1a998a4c6536bac5a20cf30495f69

**Pull request closed without merging**
