### PR TITLE
Register new package DistQuads.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [pkofod/DistQuads.jl](https://github.com/pkofod/DistQuads.jl)
Release: [v0.1.0](https://github.com/pkofod/DistQuads.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/pkofod/DistQuads.jl/builds/235136192)
cc: @pkofod

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@pkofod This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by pkofod** [comment]
I believe JuliaCIBot fails because `build.jl` will ask the user to choose a mirror to install statmod.

Currently, this is basically calling out to the R package statmod to generate quadrature points for a small set of distributions, where the distributions are specified using Distributions.jl

**Comment by tkelman** [comment]
Any way to avoid the interactive prompt and pick some default when installed by a script?

**Comment by pkofod** [comment]
> Any way to avoid the interactive prompt and pick some default when installed by a script?

I actually think it should be fixed already https://github.com/pkofod/DistQuads.jl/blob/dc38058ffd8093ff92b0cc2d76ad5e497c77fc26/deps/build.jl#L3 (this is part of the commit in question in this PR).

Travis works https://travis-ci.org/pkofod/DistQuads.jl but that is because I wget and `R install` in `before_install`

**Comment by pkofod** [comment]
I tried googling asking on gitter a few days ago, but couldn't find a package that used an R package like this, but your overview of the packages is much more comprehensive than mine; do you by any chance know of any .jl package that depends on an R package like this? Then maybe I can find inspiration there.

**Comment by tkelman** [comment]
Somewhat surprisingly, this would be the first registered Julia package to depend on RCall. So I guess not? I know almost nothing about R, so I'm the wrong person to ask. Try discourse or an issue on RCall maybe?

**Pull request merged**
