### PR TITLE
Register and tag HarwellRutherfordBoeing

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by tkelman** [comment]
Needs a minimum julia version requirement

**Comment by dpo** [comment]
Done.

**Comment by tkelman** [comment]
also at https://github.com/dpo/METADATA.jl/blob/pull-request/974f324b/HarwellRutherfordBoeing/versions/0.0.1/requires

**Comment by dpo** [comment]
that wasn't obvious.

**Comment by tkelman** [comment]
Sorry about that. `Pkg.tag` takes the current content of your package's `REQUIRE` file and populates the METADATA files accordingly. The METADATA content is what actually gets used for dependency resolution by Pkg. So if you change the package data without subsequently re-tagging, the dependency data is not publicly known yet.

**Comment by dpo** [comment]
Oh yes, sorry. I meant pushing to the `pull-request-xyz` branch on my fork wasn't so obvious. Somehow `Pkg.publish()` managed to push to it without adding my fork as a remote.

**Comment by dpo** [comment]
I'm getting https://travis-ci.org/JuliaSparse/HarwellRutherfordBoeing.jl/jobs/93824999#L25

**Comment by tkelman** [comment]
DNS issues, not your fault. Will be fixed by https://github.com/travis-ci/travis-build/pull/557

Registering this package LGTM, I think it's good to go if no comments otherwise for the next day or so.

**Comment by dpo** [comment]
Thanks!

**Pull request merged**
