### PR TITLE
Tag StaticArrays.jl v0.8.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArrays/StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl)
Release: [v0.8.0](https://github.com/JuliaArrays/StaticArrays.jl/releases/tag/v0.8.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArrays/StaticArrays.jl/builds/398104568)
Diff: [vs v0.7.2](https://github.com/JuliaArrays/StaticArrays.jl/compare/4b1afb6f50682d7ae7df2c7ff948d733673aea64...1b99b91518f5cb471503c18e18ae57e9d7351ba4)
`requires` vs v0.7.2: 
```diff
--- 0.7.2/requires
+++ 0.8.0/requires
@@ -1,2 +1 @@
-julia 0.6.0
-Compat 0.66
+julia 0.7-alpha
```
cc: @andyferris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andyferris** [comment]
Special thanks to @fredrikekre

**Comment by fredrikekre** [comment]
Lets retag once https://github.com/JuliaArrays/StaticArrays.jl/pull/451#discussion_r199063779 is fixed.

**Comment by andyferris** [comment]
Yes, you mean create v0.8.1 once that's functioning?

**Comment by fredrikekre** [comment]
No I meant don't merge this, and re-tag `v0.8.0`

**Pull request closed without merging**
