### PR TITLE
Tag Klara.jl v0.9.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/Klara.jl](https://github.com/JuliaStats/Klara.jl)
Release: [v0.9.1](https://github.com/JuliaStats/Klara.jl/releases/tag/v0.9.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/Klara.jl/builds/282648080)
Diff: [vs v0.9.0](https://github.com/JuliaStats/Klara.jl/compare/d1bfefe8c20881685425dca9796bc8859aa78973...183920315887e7f7e5d7b4aa27ddebfffe824791)
`requires` vs v0.9.0: 
```diff
--- 0.9.0/requires
+++ 0.9.1/requires
@@ -2,6 +2,6 @@
 DiffBase 0.1
 Distributions 0.4.7
 Formatting 0.1.4
-ForwardDiff 0.4
+ForwardDiff 0.4 0.6-
 ReverseDiff 0.1
 StatsBase 0.7.4
```
cc: @scidom

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by KristofferC** [comment]
Why `0.6-` upper bound on ForwardDiff? Upper bounds are exclusive so `0.6` would mean everything that is below 0.6.

**Comment by tkelman** [comment]
Applying an upper bound only on a single version is useless. Pkg can downgrade Klara and upgrade ForwardDiff to 0.6 since the older Klara versions still allow it.

**Comment by scidom** [comment]
Thanks @KristofferC, I fixed the upper bound as per your suggestion. @tkelman, did you make comments of general nature, or did you suggest a specific course of action that eluded me?

**Comment by tkelman** [comment]
If your desired goal is to make Klara use older versions of ForwardDiff, this will not accomplish it. You need to propose a separate PR that adds ForwardDiff upper bounds to the requires files of the metadata tags for all past releases of Klara for that to work.

**Comment by scidom** [comment]
Thanks @tkelman. How can I achieve this? If I understand well, it was proposed in the past not to create manual PRs on METADATA. Is there a way to get the desired result using attobot?

**Comment by tkelman** [comment]
No that's not possible. It's advised against making manual PRs for tags.

**Comment by scidom** [comment]
What is the procedure in this case to propose a separate PR that adds ForwardDiff upper bounds to the REQUIRE files of the METADATA tags for all past releases of Klara, as you suggested?

**Comment by tkelman** [comment]
Make a new local branch that's up-to-date with upstream metadata-v2, open all the files under `Klara/versions/*/requires` and add 0.6 upper bounds to the ForwardDiff requirement (if there isn't an existing lower bound you can add a dummy one at 0.0), commit that, push the branch to your fork, open a new PR.

**Comment by scidom** [comment]
I am following you @tkelman. I will follow the process you suggested later on today.

**Comment by scidom** [comment]
@tkelman I followed your instructions and opened a separate PR:

https://github.com/JuliaLang/METADATA.jl/pull/11468

I guess the current PR will be merged after merging the above PR first.

**Comment by scidom** [comment]
@KristofferC if this is okey by now, it would be great to merge, as it's been open for four days...

**Comment by scidom** [comment]
Thanks @aviks. As you merged the previous PR re older releases, I will now close this one, to make sure that generate a new release pointing to the latest commit in Klara.

**Comment by KristofferC** [comment]
So this should be closed?

**Comment by scidom** [comment]
Hi @KristofferC, this should be (and is ready to) be merged. Initially, I opened a separate PR (which was merged yest), which changes the ForwardDiff upper bound in the requirements of all previous versions of Klara, as @tkelman suggested. The current PR is for the purposes of upgrading to a new minor version of Klara, v0.9.1 (which solves some code generation - world age issues).

**Pull request merged**
