### PR TITLE
Tag KernelDensityEstimate.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaRobotics/KernelDensityEstimate.jl](https://github.com/JuliaRobotics/KernelDensityEstimate.jl)
Release: [v0.4.0](https://github.com/JuliaRobotics/KernelDensityEstimate.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaRobotics/KernelDensityEstimate.jl/builds/432606646)
Diff: [vs v0.3.1](https://github.com/JuliaRobotics/KernelDensityEstimate.jl/compare/6a66742195001cdaead92f03dd2b2a0e099e5ff6...14a2cf541a2d95d54290f2ff367d71a3f5011709)
`requires` vs v0.3.1: 
```diff
--- 0.3.1/requires
+++ 0.4.0/requires
@@ -1,3 +1,3 @@
-julia 0.6
+julia 0.7
 Distributions
-Compat 0.18
+Compat 1.1.0
```
cc: @dehann

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by dehann** [comment]
Hi, I'm not planning to support backward compatibility with Julia 0.6, hence the failures on JuliaCIBot, however, note the important Julia 0.7 tests [**do pass**](https://juliarun-ci.s3.amazonaws.com/8e5b3936a481f1b2546008d1a52975340a4c638d/pull_request_of_KernelDensityEstimate_on_julia_0_7.log).  The following dependent downstream packages will be updated for Julia 0.7 soon too:  `RoME`, `KernelDensityEstimatePlotting`, `IncrementalInference`, `Caesar`, `RoMEPlotting`.  If this is okay Julia, please merge this PR.  Thanks!

**Comment by andreasnoack** [comment]
The critical failure is on Julia 1.0
```julia
ERROR: LoadError: UndefVarError: Void not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:319 [inlined]
 [7] eval(::Expr) at ./client.jl:389
 [8] top-level scope at ./none:3
in expression starting at /home/jrun/KernelDensityEstimate/.julia/packages/KernelDensityEstimate/LylAR/src/KernelDensityEstimate.jl:50
```

**Comment by dehann** [comment]
Hi @andreasnoack , please find tests for Julia 0.7 and 1.0 that pass.  Support for Julia 0.6 has been dropped in 0.4.x and beyond.

**Comment by andreasnoack** [comment]
Thanks for the update. We set up a system where PR's are automatically merged when tests pass unless the PR contains comments after the latest Attobot update so in the future it is better to avoid commenting on PRs where tests pass since it might slow down the process.

**Pull request merged**
