### PR TITLE
Tag DynamicalSystemsBase.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDynamics/DynamicalSystemsBase.jl](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl)
Release: [v0.3.0](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDynamics/DynamicalSystemsBase.jl/builds/325626377)
Diff: [vs v0.2.1](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/compare/06df5220faa72fb1259e3a6947786926b136c99a...c68cbdb1a179ad6461fa555924ac498ba81eabcf)
`requires` vs v0.2.1: no changes
cc: @Datseris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by Datseris** [comment]
Please do not merge yet, I have encountered an unforseen problem!

**Comment by Datseris** [comment]
Okay, tests should pass now and everything should be a-ok.

**Comment by ChrisRackauckas** [comment]
Is the JuliaCIBot failure something that needs to be acted on?

**Comment by Datseris** [comment]
I've read on gitter that JuliaCI bot has failed or something like that so I didn't pay attention... Checking it now.

**Comment by Datseris** [comment]
Yeap, the error is:
```
INFO: Installing ChaosTools v0.3.0
INFO: Installing Combinatorics v0.5.0
INFO: Installing Polynomials v0.2.0
INFO: Package database updated
ERROR: LoadError: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
```
Which means that the install itself has problems. I do not know what to do about this.

**Comment by Datseris** [comment]
My require doesn't have ChaosTools, :S ???
REQUIRE:
```
julia 0.6
OrdinaryDiffEq 2.17.0
ForwardDiff 0.5
Requires 0.4.3
StaticArrays 0.5.0
StatsBase 0.8.2
IterTools
NearestNeighbors
LsqFit
```

**Comment by Datseris** [comment]
Oh wait. I am sorry I have no clue what JuliaCI is supposed to do.

It tries to test ChaosTools.jl . Of course it fails, because ChaosTools cannot work with the current version of DynamicalSystemsBase.jl. Of course, I cannot tag a new version of ChaosTools before the tag of DynamicalSystemsBase is through, because the new tag of chaostools will depend on the new tag of DynamicalSystemsBase!

**Comment by ChrisRackauckas** [comment]
You need to upper bound ChaosTools.jl on all previous versions of DynamicalSystemsBase.jl

**Comment by Datseris** [comment]
Okay, I hope that this: https://github.com/JuliaLang/METADATA.jl/pull/12765 fixes it

**Pull request merged**
