### PR TITLE
Register new package AdjacentFloats.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/AdjacentFloats.jl](https://github.com/JeffreySarnoff/AdjacentFloats.jl)
Release: [v0.0.1](https://github.com/JeffreySarnoff/AdjacentFloats.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/JeffreySarnoff/AdjacentFloats.jl/builds/219617524)
cc: @JeffreySarnoff

### CODE REVIEW

**Comment by dpsanders** [comment]
Do you use Compat?

**Comment by JeffreySarnoff** [comment]
yes

**Comment by JeffreySarnoff** [comment]
@dpsanders while you are here, look at [ErrorfreeArithmetic.jl](https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl) and email any comments, suggestions, requests (getting near release)

**Comment by JeffreySarnoff** [comment]
@dpsanders the REQUIRE for Compat was too high for v0.5.1 -- resubmitting

**Comment by dpsanders** [comment]
Sorry, I wasn't clear - my question was if `Compat` is actually required for the functionality in the package. I don't see where it's used.

**Comment by JeffreySarnoff** [comment]
I put it in for this `const IEEE754 = Union{Float64, Float32, Float16}`

**Comment by JeffreySarnoff** [comment]
@tkelman This and the pkg I just submitted (ErrorfreeArithmetic) are jointly required by another package, FastRounding that @dpsanders needs.  If it does not muck anything, and those two look ok, please let them become add_able over the weekend.  Should this not work out -- that's ok too.  As ever, thank you.

**Comment by tkelman** [comment]
> `const IEEE754 = Union{Float64, Float32, Float16}`

You don't need Compat for that at all. Certainly not 0.21.

**Comment by JeffreySarnoff** [comment]
removed Compat

**Comment by JeffreySarnoff** [comment]
afaik, good
(I had to rename appveyor.yml for this to report itself in a clean state)

**Comment by tkelman** [comment]
You still aren't using Compat though? What was failing on appveyor?

**Comment by JeffreySarnoff** [comment]
I have no idea.  Looking at the pull requests, many were failing.  I saw one that was just posted and got through cleanly.  The only difference I could see was that package did not supply an appveyor file.  So I renamed mine _appveyor_.yml and forced resubmission -- it worked.

**Comment by JeffreySarnoff** [comment]
maybe this
ERROR: LoadError: packages with unsatisfiable requirements found:
BioEnergeticFoodWebs v0.3.0 – no valid versions exist for package ParameterizedFunctions
BioEnergeticFoodWebs v0.3.1 – no valid versions exist for package ParameterizedFunctions
in check_metadata(::Set{String}) at /home/travis/.julia/v0.5/PkgDev/src/entry.jl:301
in check_metadata() at /home/travis/.julia/v0.5/PkgDev/src/entry.jl:288
in include_from_node1(::String) at ./loading.jl:488
in eval(::Module, ::Any) at ./boot.jl:234
in process_options(::Base.JLOptions) at ./client.jl:242
in _start() at ./client.jl:321
while loading /home/travis/build/JuliaLang/METADATA/.test/METADATA.jl, in expression starting on line 248

**Comment by tkelman** [comment]
No, that's unrelated to your package, has nothing to do with whether or not you have an appveyor.yml file. It's a problem with METADATA / Pkg that you didn't cause.

**Comment by JeffreySarnoff** [comment]
good -- will re-engage appveyor

**Comment by JeffreySarnoff** [comment]
fixed

**Pull request merged**
