### PR TITLE
Tag Dopri.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [helgee/Dopri.jl](https://github.com/helgee/Dopri.jl)
Release: [v0.4.0](https://github.com/helgee/Dopri.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/helgee/Dopri.jl/builds/215917559)
Diff: [vs v0.3.0](https://github.com/helgee/Dopri.jl/compare/7584341721f6d5e55a41d9b979554d4ea69745d9...5564ac01b83267684be01d9c4cb19bb6133833d2)
`requires` vs v0.3.0: 
```diff
--- 0.3.0/requires
+++ 0.4.0/requires
@@ -1,3 +1,2 @@
-julia 0.4
-BaseTestNext
-Compat
+julia 0.5
+Compat 0.17.0
```
cc: @helgee

### CODE REVIEW

**Comment by helgee** [comment]
I will compile Windows binaries for the Fortran library and update this PR when it's done.

**Comment by helgee** [comment]
Should be good to go now.

For the record: Compiling Fortran on Windows and figuring out the correct linker settings is no fun at all and one of the reasons why Julia will eat the world...

**Comment by tkelman** [comment]
Is ref.txt intended to be checked in?

**Comment by helgee** [comment]
Yes. The tests compiled and ran a Fortran program before but since the output is always the same I decided to put it in a file instead.

**Pull request merged**
