### PR TITLE
Register CUSPARSE

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by milktrader** [comment]
This looks like a good candidate for the [JuliaGPU](https://github.com/JuliaGPU) group.

@jakebolewski

**Comment by IainNZ** [comment]
Hey @kshyatt, thanks for the PR. You'll need to `Pkg.tag` a version to be able to `Pkg.add` the package - we can merge this now and then you can do that, or you can tag a version and open a new PR. Its not required to have a version, but its usually desirable.

**Comment by timholy** [comment]
Looks awesome, @kshyatt!

**Comment by kshyatt** [comment]
There are a few more tests I wanted to write tonight, and then I will v0.0.1 later tonight. Could you merge now?

**Comment by IainNZ** [comment]
:+1:

**Comment by kshyatt** [comment]
I got a nice round PR number too. Everything's coming up Milhouse today.

**Pull request merged**
