### PR TITLE
Bump Stan.jl to version 1.0.0

### PR DESCRIPTION
**Pull request by goedman**
Upgrade  Stan.jl to Julia v0.5

### CODE REVIEW

**Comment by tkelman** [comment]
Have you investigated enabling Travis CI?

**Comment by goedman** [comment]
Hi Tony,

Thanks for merging.

The problem with Stan.jl (and Jags.jl, which is next on my list) is that to do proper testing the CmdStan and Jags binaries need to be installed. Without these installed the Travis testing is not very telling as the more complicated code deals with running the sampling commands in parallel, processing the combined chain results and using Mamba graphics to display the results.

I did follow your suggestions regarding not using Pkg.dir() and the construct cd(...) do ... end.

Will Pkg.dir go away? I find Pkg.dir("Stan", "Examples", "Bernoulli") a bit clearer than ProjDir = joinpath(dirname(@__FILE__), "..", "Examples", "Bernoulli").

On the cd() do .. end construct, it sure looks nicer. To test the individual methods in say Jagscode.jl, typically by stepping through them using run selection  (^E in my setup of TextMate), I can temporarily go back to the cd(...) and cd(old) bracketing.

Thanks for all your help!

**Comment by tkelman** [comment]
Pkg.dir won't go away, but it's not the right way for a package to refer to its own location, since the code may be loaded from elsewhere.

**Comment by goedman** [comment]
Ah, I see, thank you!

**Pull request merged**
