### PR TITLE
Tag Blosc v0.1.5 [git://github.com/stevengj/Blosc.jl.git]

### PR DESCRIPTION
**Pull request by stevengj**
Closes stevengj/Blosc.jl#13

### CODE REVIEW

**Comment by stevengj** [comment]
Looks like the Windows binaries are broken somehow, hold on...

**Comment by tkelman** [comment]
also good to push the git tag to https://github.com/stevengj/Blosc.jl/releases when ready

**Comment by stevengj** [comment]
Grrr, I don't know what I'm doing wrong with the Windows binaries.  Cross-compiling them always worked before.

**Comment by tkelman** [comment]
What distro are you using? Anything major changed or upgraded since you last built them?

**Comment by stevengj** [comment]
Debian, with MinGW; not sure if there has been an upgrade since last build.

**Comment by tkelman** [comment]
which debian version? the mingw cross compilers may be posix-thread-based now so you might just be missing libwinpthread1.dll or something, have you checked in dependency walker if you have a windows system nearby? dependency walker might work under wine, not positive

**Comment by stevengj** [comment]
Good call, I tried dependency walker and got a couple missing DLLs:
image

**Comment by stevengj** [comment]
Oh, duh, I'm compiling with `-pthread`.

**Comment by tkelman** [comment]
winpthread is probably the only one you actually need to worry about, I think the others are just dependency walker getting confused

**Comment by stevengj** [comment]
Yay, looks like it works.  Will post corrected binaries soon and merge this once AppVeyor is green.

**Comment by stevengj** [comment]
I wish that Julia's `dlopen` gave a more informative error message for this sort of thing, but maybe that is a libuv limitation.

**Pull request merged**
