### PR TITLE
Register new package YaoArrayRegister.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [QuantumBFS/YaoArrayRegister.jl](https://github.com/QuantumBFS/YaoArrayRegister.jl)
Release: [v0.2.0](https://github.com/QuantumBFS/YaoArrayRegister.jl/releases/tag/v0.2.0)
cc: @Roger-luo

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@Roger-luo This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please add motivation and basic usage in the README.

Google does not (seem to) know what a "Yao array". What is the meaning of the package name?

**Comment by Roger-luo** [comment]
It's separated from [Yao.jl](https://github.com/QuantumBFS/YaoArrayRegister.jl) to make it become a meta-package, it's not "Yao array", it's an `Array` register for Yao as README says:

> Simulated Full Amplitude Quantum Register

**Comment by Roger-luo** [comment]
Err, BTW, I can't update this tag, can I? after I add more README.

**Comment by dpsanders** [comment]
You can delete the release and the tag, and then do a new release. Or just update the README and don't worry about the tag.

**Comment by Roger-luo** [comment]
I tried a few hours ago... but seems attobot didn't force push the new tag (I deleted v0.1.0 and re-tag v0.1.0). I'll leave the tag as it is for now, since I need to tag new versions to fix things after I finish all the component package for Yao later...

**Comment by andreasnoack** [comment]
You'd have to delete both the release and the tag before making the release again.

**Comment by Roger-luo** [comment]
Could you just close this? v0.1 was merged. I'll delete this version. Thanks.

**Pull request closed without merging**
