### PR TITLE
Register/tag Gallium/ASTInterpreter

### PR DESCRIPTION
**Pull request by Keno**
Fixes https://github.com/JuliaLang/julia/issues/505.

### CODE REVIEW

**Comment by tkelman** [comment]
Push the git tags. If you're using `PkgDev.publish`, it should be doing that for you if authentication is working.

Is `LoadError: type LambdaInfo has no field slotnames` on AbstractTrees a case of nightlies not being recent enough?

**Comment by Keno** [comment]
`PkgDev.publish` has never worked for me. Yes, the travis error is because of outdated nightlies.

**Comment by kmsquire** [comment]
Bug report?

**Comment by Keno** [comment]
It's a problem with my configuration I believe. Libgit2 isn't picking up some SSL library. I should investigate at some point.

**Comment by tkelman** [comment]
Try with https remotes. I'm looking into the buildbot issue, it's an LLVM unable to allocate section memory problem but setting `JULIA_TEST_MAXRSS_MB` will hopefully help.

**Comment by tkelman** [comment]
Please don't forget to push the git tags. Or I'll do it for you if you give me commit access.

**Comment by Keno** [comment]
All done

**Pull request merged**
