### PR TITLE
Tag QuantEcon.jl v0.15.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [QuantEcon/QuantEcon.jl](https://github.com/QuantEcon/QuantEcon.jl)
Release: [v0.15.0](https://github.com/QuantEcon/QuantEcon.jl/releases/tag/v0.15.0)
Travis: [Travis Build Status](https://travis-ci.org/QuantEcon/QuantEcon.jl/builds/422648363)
Diff: [vs v0.14.3](https://github.com/QuantEcon/QuantEcon.jl/compare/6b6d842aebc76c80fc7f17ce458333c768d29e10...f454d4dfbaf52f550ddd52eff52471e4b8fddb9d)
`requires` vs v0.14.3: 
```diff
--- 0.14.3/requires
+++ 0.15.0/requires
@@ -1,11 +1,8 @@
-julia 0.6
+julia 0.7
 DSP
-Distributions 0.8.9
+Distributions
 LightGraphs
 Primes
-Compat 0.18.0
 StatsBase
-Optim 0.9.0
-NLopt 0.3.4
-Nullables
-Compat 0.48.0
+Optim
+NLopt
```
cc: @sglyon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by sglyon** [comment]
Sorry, I need to fix one more thing. Please do not merge

**Comment by sglyon** [comment]
OK last change in. This is ready for review now!

**Comment by omus** [comment]
JuliaCIBot seems stuck. Re-triggering.

**Comment by andreasnoack** [comment]
CIBot fails because of the project file so please consider deleting it.

**Comment by sglyon** [comment]
Done

**Comment by sglyon** [comment]
OK I think now I'm done.

Green lights from Travis on the repo. 


Hopefully things go well here too 🤞

**Pull request merged**
