### PR TITLE
Tag GeoStats.jl v0.5.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/GeoStats.jl](https://github.com/juliohm/GeoStats.jl)
Release: [v0.5.5](https://github.com/juliohm/GeoStats.jl/releases/tag/v0.5.5)
Travis: [Travis Build Status](https://travis-ci.org/juliohm/GeoStats.jl/builds/361492243)
Diff: [vs v0.5.4](https://github.com/juliohm/GeoStats.jl/compare/82db580645110ab8479a8d988385c3052af1d99a...6beb582f48cd1ada35ed4f006d66e438905f4b1c)
`requires` vs v0.5.4: 
```diff
--- 0.5.4/requires
+++ 0.5.5/requires
@@ -1,11 +1,10 @@
 julia 0.6
-Reexport
-GeoStatsBase 0.0.9
-GeoStatsDevTools 0.1.0
+Reexport 0.1.0
+GeoStatsBase 0.0.10
+GeoStatsDevTools 0.1.1
+Variography 0.0.1
+KrigingEstimators 0.0.1
 Distances 0.5.0
-StatsBase
-Combinatorics 0.5.0
-SpecialFunctions
-Parameters
-NamedTuples
-RecipesBase
+StatsBase 0.20.1
+NamedTuples 4.0.0
+RecipesBase 0.2.3
```
cc: @juliohm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by juliohm** [comment]
Sorry for the long list of changes, but the complexity of the project is reaching another level.

This new release depends on two new packages #14088 and #14084 , and new versions of existing packages #14089 #14090 .

**Comment by andreasnoack** [comment]
No problem Thanks for leaving comments about the dependency of the PRs. They are very useful.

**Comment by juliohm** [comment]
@andreasnoack this and #14088 #14084 #13626 would need to be merged together to avoid errors.

I wonder if Pkg3 has a solution to this multi-package project issue. Looking forward to it.

**Comment by fredrikekre** [comment]
> I wonder if Pkg3 has a solution to this multi-package project issue. Looking forward to it.

If they are this coupled, perhaps they should be one package?

**Comment by juliohm** [comment]
They used to be one package, but their functionality will expand considerably in the future. I also need them as separate packages to use them in different solvers that are coming up.

For Variography.jl there is a lot of tooling that needs to be built. For KrigingEstimators.jl there is a lot of work to be done to expand to problem of co-estimation (estimating more than one variable at a time using covariates).

**Comment by juliohm** [comment]
@andreasnoack the build is failing because GeoStatsDevTools.jl wasn't merged yet. I updated the REQUIRE there to use the latest DataFrames.jl and added fixes for the new Missings interface.

**Comment by andreasnoack** [comment]
> I updated the REQUIRE there to use the latest DataFrames.jl and added fixes for the new Missings interface.

Do you then want to retag this?

**Comment by juliohm** [comment]
Everything is at the latest version, now the tests are passing, thanks for the patience with this migration, hopefully it won't happen again in the future.

**Comment by andreasnoack** [comment]
No problem. Refactorings often cause some hiccups but it looks like we made it through.

**Pull request merged**
