### PR TITLE
Tag NLsolve.jl v1.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/NLsolve.jl](https://github.com/JuliaNLSolvers/NLsolve.jl)
Release: [v1.1.0](https://github.com/JuliaNLSolvers/NLsolve.jl/releases/tag/v1.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaNLSolvers/NLsolve.jl/builds/337023060)
Diff: [vs v1.0.0](https://github.com/JuliaNLSolvers/NLsolve.jl/compare/deed60a6bb655fb73e7b29a4c3759c696fa8827d...deed60a6bb655fb73e7b29a4c3759c696fa8827d)
`requires` vs v1.0.0: no changes
cc: @pkofod

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ararslan** [comment]
This and the tag before it have the same SHA, which I guess means that no changes were made to master between the previous tag and this one. I assume that was not intentional. @pkofod?

**Comment by pkofod** [comment]
Not on purpose!

**Comment by pkofod** [comment]
You can close this... I could have sworn github said 5 changes since master... apparently I already tagged these changes, hence the same aha.

**Comment by ararslan** [comment]
I could have sworn that we had a check here in METADATA at one point that verified that the SHA of the new tag was distinct from previous tags, but I guess not.

**Pull request closed without merging**
