### PR TITLE
Tag BioStructures.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BioJulia/BioStructures.jl](https://github.com/BioJulia/BioStructures.jl)
Release: [v0.3.0](https://github.com/BioJulia/BioStructures.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/BioJulia/BioStructures.jl/builds/421278631)
Diff: [vs v0.2.0](https://github.com/BioJulia/BioStructures.jl/compare/c50a4536c55150775879c809cc29ccba6fb757f5...157ab9560a7671dc7a4a44ef0a8ece1128c878a3)
`requires` vs v0.2.0: 
```diff
--- 0.2.0/requires
+++ 0.3.0/requires
@@ -1,6 +1,6 @@
-julia 0.6
-Libz 0.2
-Formatting
-BioCore 1.3.0
+julia 0.7
+CodecZlib
+Format
+BioCore
 BioSymbols
 BioSequences
```
cc: @jgreener64

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by jgreener64** [comment]
Had to update this to fix the doc build, which is now fixed :+1:.

**Comment by andreasnoack** [comment]
The reverse dependency testing in CIbot breaks because the dependency Format.jl includes a project file. See https://github.com/JuliaString/Format.jl/pull/40.

**Comment by andreasnoack** [comment]
Since no packages depend on this package, I'll merge instead of waiting for the Format PR.

**Comment by jgreener64** [comment]
Thanks.

**Pull request merged**
