### PR TITLE
Package MathToolkit

### PR DESCRIPTION
**Pull request by baruchel**

### CODE REVIEW

**Comment by tkelman** [comment]
Would your tests pass if you enabled Travis CI?

**Comment by kmsquire** [comment]
I'm wondering if the tools in this package are meant to be useful for all
areas of math, or if a more specific name would be appropriate?

**Comment by baruchel** [comment]
@tkelman Hi, could you explain more precisely what you mean; this is my first package for Julia; what should I do for enabling Travis CI?

**Comment by baruchel** [comment]
@kmsquire These tools are much used in the field of experimental mathematics, "concrete" mathematics, etc. Of course a more specific name could fit; do you have any suggestion? Regards.

**Comment by tkelman** [comment]
Log in at https://travis-ci.org/, then click the "+" for Add New Repository to enable this package. The generated template `.travis.yml` file should be good enough to get going.

**Comment by kmsquire** [comment]
I took a slightly closer look, and don't have any better suggestions right now. If no one else has any comments, I think the current name will be fine.

**Comment by baruchel** [comment]
@tkelman OK, I think I did it; however an error occurent for one test (Julia nightly on Apple); however the error message has nothing to do with this package; it looks like the system couldn't even find or launch Julia. What should I do?

**Comment by tkelman** [comment]
That's a known issue, we're looking into it, you're fine. See https://github.com/travis-ci/travis-ci/issues/5740.

**Comment by baruchel** [comment]
@tkelman OK, I noticed that the URL in my METADATA pull request contained https rather than git (like all other packages); this has probably to do with the fact that I encountered issues concerning normalize_url when trying to use PkgDev.register and I did part of the job by hand instead. However I think I am fine now; do I have something more to do?

**Comment by tkelman** [comment]
Both https and git should work currently, we will be gradually migrating more towards https over time but at the moment we aren't enforcing one or the other yet.

**Comment by baruchel** [comment]
@tkelman and @kmsquire It looks like everything is OK now; is there a step more for being accepted as a new package? Regards,.

**Comment by tkelman** [comment]
Generally we like to leave initial registration PR's open for about 24 hours of feedback, the community consists of people in all timezones across the world after all.

**Comment by baruchel** [comment]
That's nice! Thank you for everything. One more question: if I add later some changes and tag them with a new version number; do I need to come here again?

**Comment by tkelman** [comment]
You'll submit a new pull request to METADATA for each new version tag. Generally those don't have to wait 24 hours, as long as it passes the metadata tests and nothing malicious or obviously broken has changed in the package since the last tag, new version PR's are uncontroversial.

**Pull request merged**
