### PR TITLE
Tag LightGraphs v0.7.0

### PR DESCRIPTION
**Pull request by sbromberger**
See https://github.com/JuliaGraphs/LightGraphs.jl/issues/420 and discussion in https://github.com/JuliaLang/METADATA.jl/issues/6155#issuecomment-242997676.

### CODE REVIEW

**Comment by sbromberger** [comment]
Thanks!

**Comment by sbromberger** [comment]
@tkelman one last big favor: can you kick off a pkgstatus check of LightGraphs so that the status for 0.7.0 will show that it's passing on 0.5?

**Comment by tkelman** [comment]
packageevaluator does funny things if you do an official run more than once a day. it's scheduled daily starting at 12:20 am eastern on a cron job, publishing the website updates about 10hrs after that when it's done.

**Comment by sbromberger** [comment]
Oh, wow, ok. For some reason I thought it was once a week. I can certainly wait a day :)

**Comment by tkelman** [comment]
It had been manually triggered by Iain until we moved it over to running on a @nanosoldier node via a cron script in May https://github.com/JuliaCI/pkg.julialang.org/commits/gh-pages

**Pull request merged**
