### PR TITLE
Regular update with minor improvements

### PR DESCRIPTION
**Pull request by cortner**

### CODE REVIEW

**Comment by tkelman** [comment]
be sure to push the git tags to https://github.com/cortner/PyAMG.jl/releases

**Comment by tkelman** [comment]
you've tagged the same commit twice here, but that's harmless

**Comment by cortner** [comment]
yeah, I realised, but didn't want to mess around with the repository. Btw,`PkgDev.publish()` failed:
```
julia> PkgDev.publish()
INFO: Validating METADATA
INFO: Pushing PyAMG permanent tags: v0.0.5, v0.0.6
WARNING: The explicitly provided credentials were incompatible with the server's supported authentication methods
ERROR: GitError(Code:EAUTH, Class:None, No errors)
 in macro expansion at ./libgit2/error.jl:98 [inlined]
 in #push#53(::Bool, ::Base.LibGit2.PushOptions, ::Function, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./libgit2/remote.jl:84
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRemote, ::Array{String,1}) at ./<missing>:0
 in #push#94(::String, ::String, ::Array{String,1}, ::Bool, ::Nullable{Base.LibGit2.UserPasswordCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:179
 in (::Base.LibGit2.#kw##push)(::Array{Any,1}, ::Base.LibGit2.#push, ::Base.LibGit2.GitRepo) at ./<missing>:0
 in (::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}})(::Base.LibGit2.GitRepo) at /Users/ortner/.julia/v0.5/PkgDev/src/entry.jl:101
 in with(::PkgDev.Entry.##6#11{Dict{String,Array{String,1}}}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:645
 in publish(::String, ::String) at /Users/ortner/.julia/v0.5/PkgDev/src/entry.jl:86
 in publish() at /Users/ortner/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```
Any thoughts?

**Comment by tkelman** [comment]
looks like it's getting confused between ssh vs https, see https://github.com/JuliaLang/PkgDev.jl/issues/48#issuecomment-236185630

**Comment by cortner** [comment]
thank you - tags have been pushed.

**Pull request merged**
