### PR TITLE
Register new package MultiJuMP.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [anriseth/MultiJuMP.jl](https://github.com/anriseth/MultiJuMP.jl)
Release: [v0.1.1](https://github.com/anriseth/MultiJuMP.jl/releases/tag/v0.1.1)
cc: @anriseth

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@anriseth This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by KristofferC** [comment]
cc @mlubin for name

**Comment by anriseth** [comment]
Hmm. I wasn't trying to register this package. Is there a way to tell attobot to ignore particular repositories?

**Comment by KristofferC** [comment]
I guess you can choose not to install the bot globally.

**Comment by anriseth** [comment]
I've uninstalled attobot, so this shouldn't happen again.

In terms of registering the package, there seem to be a few people using it so it may be useful on METADATA. 

The package is almost two years old, so the name came about ages ago. If you, or @mlubin, don't find it appropriate, I don't mind having the PR closed.

**Comment by mlubin** [comment]
Yes, I don't have any issue with the name. This package has been around for a long time, surprised it's not already registered.

**Comment by anriseth** [comment]
> Yes, I don't have any issue with the name. This package has been around for a long time, surprised it's not already registered.

Thank you. I was a bit surprised myself.

@KristofferC I have tried to fix the Travis error by removing a spurious tag in the repository.

**Pull request merged**
