### PR TITLE
Register GraphPlot

### PR DESCRIPTION
**Pull request by afternone**
GraphPlot can draw networks easily

### CODE REVIEW

**Comment by hayd** [comment]
cc @sbromberger

**Comment by sbromberger** [comment]
oooh - cool. Can't wait to check this out!

**Comment by hayd** [comment]
What's the difference between this package and GraphLayout?

**Comment by afternone** [comment]
In the actual problem, I want different communities in network have different colors, custom node size, custom edge width and so on. I will add these features to GraphLayout and close this PR.

**Pull request closed without merging**
