### PR TITLE
Tag ModiaMath.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [ModiaSim/ModiaMath.jl](https://github.com/ModiaSim/ModiaMath.jl)
Release: [v0.3.0](https://github.com/ModiaSim/ModiaMath.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/ModiaSim/ModiaMath.jl/builds/462603767)
Diff: [vs v0.2.6](https://github.com/ModiaSim/ModiaMath.jl/compare/4623fdd0d34d87a48f966cbfc278c98e7fd43df5...f018a510cb9dfd9aaefb698fc14d979999597ba5)
`requires` vs v0.2.6: no changes
cc: @MartinOtter

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by MartinOtter** [comment]
CI of ModiaMath (version 0.3.0) is successful, so the new version of ModiaMath should be released.

It is also checked whether Modia and Modia3D work with the newset version of ModiaMath and this fails. It is clear that it fails due to the changes of ModiaMath. My plan was to first release ModiaMath and then adapt Modia and Modia3D. It is not clear to me how I should proceed. The only reasonable way would be to restrict Modia and Modia3D to work only with ModiaMath upto version 0.2.6. However, this is not possible, because they are already released.

Do I need to release a new version of Modia and Modia3D with the "old" version of ModiaMath and restrict the version of ModiaMath to 0.2.6? However, it is not fully clear how I can restrict the version. Is this performed by setting in the REQUIRE file "ModiaMath 0.2.6-"??

Note, in the Manifest file of Modia and Modia3D it is correctly stated that these versions work with ModiaMath 0.2.6.

**Comment by andreasnoack** [comment]
It is possible to add upper bounds to existing releases and I'd recommend doing it in this case. See e.g. https://github.com/JuliaLang/METADATA.jl/pull/19766/files for an example of how to do it.

**Comment by MartinOtter** [comment]
> 
> 
> It is possible to add upper bounds to existing releases and I'd recommend doing it in this case. See e.g. https://github.com/JuliaLang/METADATA.jl/pull/19766/files for an example of how to do it.

Thanks. I did this.

**Comment by andreasnoack** [comment]
> Thanks. I did this.

You are welcome. Please remember not to comment on PRs (after an update through Attobot) when things are working since it breaks the automatic merging. For more info see https://discourse.julialang.org/t/the-current-metadata-release-process/16672.

**Pull request merged**
