### PR TITLE
Pull request/2a157d4b

### PR DESCRIPTION
**Pull request by montyvesselinov**
Array fixes; switching to 0.5.

### CODE REVIEW

**Comment by tkelman** [comment]
Dropping support for Julia 0.4 requires using a new package minor version for AffineInvariantMCMC, Anasol, BIGUQ, and RobustPmap

**Comment by montyvesselinov** [comment]
will do on next update. can you still merge these changes? Thank you very
much!


-monty

**Comment by tkelman** [comment]
No, this fails the metadata travis check.

**Comment by montyvesselinov** [comment]
wow. i see. i did not know travis is checking for this.

-monty

**Pull request closed without merging**
