### PR TITLE
Tag DiffEqBase.jl v1.0.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DiffEqBase.jl](https://github.com/JuliaDiffEq/DiffEqBase.jl)
Release: [v1.0.0](https://github.com/JuliaDiffEq/DiffEqBase.jl/releases/tag/v1.0.0)
Diff: [vs v0.15.0](https://github.com/JuliaDiffEq/DiffEqBase.jl/compare/be480ecd3167104a6524e9222bf1b384622d7724...d3310cb7111452257a930dd872ddfc71870acdd6)
`requires` vs v0.15.0: 
```diff
--- 0.15.0/requires
+++ 1.0.0/requires
@@ -2,6 +2,6 @@
 RecipesBase 0.1.0
 Ranges 0.0.1
 Parameters 0.5.0
-RecursiveArrayTools 0.2.0 0.4.0
+RecursiveArrayTools 0.4.0
 SimpleTraits 0.1.1
 Compat 0.19.0
```
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Needs https://github.com/JuliaLang/METADATA.jl/pull/9033 https://github.com/JuliaLang/METADATA.jl/pull/9014 https://github.com/JuliaLang/METADATA.jl/pull/9034

**Comment by tkelman** [comment]
To pass its tests you mean?

Are all the needed upper bounds in place so this won't be too breaking?

**Comment by ChrisRackauckas** [comment]
>Are all the needed upper bounds in place so this won't be too breaking?

Yes, this shouldn't be used in DifferentialEquations until #9033 #9014 #9034 also go through.

**Comment by ChrisRackauckas** [comment]
Thanks!

**Comment by tkelman** [comment]
StokesDiffEq is failing with an invalid subtyping, it should probably be upper-bounded here https://github.com/JuliaCI/pkg.julialang.org/blob/5b594c5d55cc0ddfd201f21a615dff02ff87de0c/logs/StokesDiffEq_0.5.log

**Pull request merged**
