### PR TITLE
Tag Bootstrap v0.2.0, v0.2.1, v0.2.2

### PR DESCRIPTION
**Pull request by julian-gehring**

### CODE REVIEW

**Comment by julian-gehring** [comment]
@jiahao Thanks for pointing this out, v0.2.2 fixes this.
Since the v0.2.0 and v0.2.1 are already out and used, I would like to publish the tags for them.

**Comment by jiahao** [comment]
No, you want `julia 0.3`. `0.3.0-` still means pre-release. Please look at the syntax for version numbers in the manual if this is still unclear.

**Comment by julian-gehring** [comment]
Thanks for clarifying this, I had not enough coffee this morning... v0.2.3 now requires `julia 0.3`.

**Comment by tkelman** [comment]
> Please look at the syntax for version numbers in the manual if this is still unclear.

The fact that we need to keep reminding people of this means we need better, louder, harder-to-miss docs about this. Perhaps on the readme here, and/or the package registering/tagging docs.

**Comment by milktrader** [comment]
https://github.com/JuliaLang/METADATA.jl/issues/2481

**Pull request closed without merging**
