### PR TITLE
Register new package ApproximateBayesianComputing.jl v0.0.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [eford/ApproximateBayesianComputing.jl](https://github.com/eford/ApproximateBayesianComputing.jl)
Release: [v0.0.2](https://github.com/eford/ApproximateBayesianComputing.jl/releases/tag/v0.0.2)
cc: @eford

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@eford This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
You'd have to remove stdlibs from your REQUIRE, i.e. these three https://github.com/eford/ApproximateBayesianComputing.jl/blob/master/REQUIRE#L10-L12. Stdlibs are special.

**Comment by andreasnoack** [comment]
Once you have done that, you can just delete the tag and reapply it to the new commit. Then this PR will get updated automatically.

**Comment by eford** [comment]
But I only added those to the REQUIRE file because I got error messages when I didn't include them!  

How do I delete a tag and reapply it?   

BTW- I'm totally confused by the new package manager.  Thanks for helping newbies like me individually. 
 I really wish there were a decent tutorial, so we didn't have to try stuff randomly and experts didn't have  to help us individually.

**Comment by eford** [comment]
I found how to delete tags.  And tried your suggestion.  I'll see what happens next.

**Comment by andreasnoack** [comment]
You are welcome. We haven't transitioned completely to the way of doing things which currently makes things a little more complicated than they eventually will be. Once we have transitioned, the documentation will also be better.

The details of the updating process (which is really easy once you tried it once) are in https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by andreasnoack** [comment]
That worked.

**Comment by eford** [comment]
Thanks for your help.   Hopefully, I'll do better on my next package....

**Comment by andreasnoack** [comment]
Sorry for the delay here. For some reason CIBot stalled. I've restarted the tests.

**Comment by andreasnoack** [comment]
It looks like we have an issue with our testing infrastructure so I'll merge.

**Pull request merged**
