### PR TITLE
Register new package SortingNetworks.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JeffreySarnoff/SortingNetworks.jl](https://github.com/JeffreySarnoff/SortingNetworks.jl)
Release: [v0.0.1](https://github.com/JeffreySarnoff/SortingNetworks.jl/releases/tag/v0.0.1)
cc: @JeffreySarnoff

### CODE REVIEW

**Comment by tkelman** [comment]
would travis pass if you enabled it?

**Comment by JeffreySarnoff** [comment]
Enabled; and Yes.

**Comment by tkelman** [comment]
Would it be possible to make this not extend the Base sort, so calling these methods could be done selectively instead of globally modifying methods?

**Comment by JeffreySarnoff** [comment]
Replaced `import Base:sort` with `export swapsort` and updated files accordingly

**Comment by tkelman** [comment]
There's also the `alg` keyword argument that could work for this, and x-ref https://github.com/JuliaCollections/SortingAlgorithms.jl for future possible integration

**Comment by JeffreySarnoff** [comment]
(nice)
I added:
     
    export swapsort, ExchangeSort

    immutable ExchangeSortAlg  <: Algorithm end
    const ExchangeSort  = ExchangeSortAlg()

**Comment by JeffreySarnoff** [comment]
That's good.

**Pull request merged**
