### PR TITLE
Tag Colors.jl v0.9.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphics/Colors.jl](https://github.com/JuliaGraphics/Colors.jl)
Release: [v0.9.1](https://github.com/JuliaGraphics/Colors.jl/releases/tag/v0.9.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphics/Colors.jl/builds/412433331)
Diff: [vs v0.9.0](https://github.com/JuliaGraphics/Colors.jl/compare/6ec22e2b8e8bfa24be580cd23c8108e9ce8d5c23...106abae26b9329add5e7a2b24aa2fd3e301492e7)
`requires` vs v0.9.0: 
```diff
--- 0.9.0/requires
+++ 0.9.1/requires
@@ -1,4 +1,4 @@
-julia 0.7-alpha
+julia 0.7-rc2
 ColorTypes 0.7.0
 FixedPointNumbers 0.5.0
 Reexport
```
cc: @timholy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Are the failures on nightly expected?

**Comment by timholy** [comment]
Sorry, I should have noticed this earlier. It's outdated now. Not sure whether the failure on master was relevant. Better to close?

**Comment by andreasnoack** [comment]
It looks like the issue is in JLD2 which probably is only used in tests. In the meantime, there has been a release of JLD2 so let's restart and see how it goes.

**Comment by andreasnoack** [comment]
Doh. I need more coffee. It's Colors's tests that need to be restarted. Could you either restart the tests for the current tag or maybe delete it and reapply it to a more recent commit? That will automatically update this PR.

**Comment by timholy** [comment]
Well, we have already released 0.9.3 so maybe it's moot?

**Pull request closed without merging**
