### PR TITLE
Tag PDMats.jl v0.7.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/PDMats.jl](https://github.com/JuliaStats/PDMats.jl)
Release: [v0.7.1](https://github.com/JuliaStats/PDMats.jl/releases/tag/v0.7.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaStats/PDMats.jl/builds/290588011)
Diff: [vs v0.7.0](https://github.com/JuliaStats/PDMats.jl/compare/490112262b3670021ca9e40f890189347a3556ce...afb7891204b0dc76076a46f22d2e41d88e135048)
`requires` vs v0.7.0: 
```diff
--- 0.7.0/requires
+++ 0.7.1/requires
@@ -1,2 +1,2 @@
 julia 0.5
-Compat 0.18.0
+Compat 0.33
```
cc: @ararslan

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like CIBot. Is there a way to look into it?

**Comment by ararslan** [comment]
It looks like CIBot what? I don't believe there's a way to investigate CIBot (at least that I know of) other than delegating the work by pinging Avik.

**Comment by andreasnoack** [comment]
Hangs

**Comment by aviks** [comment]
cc: @nkottary

**Comment by aviks** [comment]
We'll probably look at this monday morning.

**Pull request merged**
