### PR TITLE
Register Clockwork

### PR DESCRIPTION
**Pull request by malmaud**
https://github.com/malmaud/Clockwork.jl

### CODE REVIEW

**Comment by jakebolewski** [comment]
You could have been the first 0.5 only package.

**Comment by malmaud** [comment]
It's not :watch: to drop .4 support yet.

**Comment by tkelman** [comment]
PkgDev is 0.5 only.

Since 0.4 final is out, drop the trailing - ?

**Comment by malmaud** [comment]
OK

**Comment by malmaud** [comment]
It's *time* to merge this

**Comment by milktrader** [comment]
Bout time we got a package like this!

**Comment by StefanKarpinski** [comment]
If nothing else, this package shook out a number of issues with generic linear algebra.

**Comment by sjkelly** [comment]
Perfect timing for 0.5.

**Comment by jiahao** [comment]
> You could have been the first 0.5 only package.

It wasn't the first, but it could have been the second.

**Comment by jakebolewski** [comment]
The puns are getting worse over time.

**Pull request merged**
