### PR TITLE
Tag IntervalConstraintProgramming.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Release: https://github.com/dpsanders/IntervalConstraintProgramming.jl/releases/tag/v0.3.0
Diff: [vs v0.2.0](https://github.com/dpsanders/IntervalConstraintProgramming.jl/compare/ee14e1293a8b6242eb80b68e2a2d8c69ef8a2b66...18ff6d9c2819d63201b7cd74e8e4207b42155189)
cc: @dpsanders

### CODE REVIEW

**Comment by tkelman** [comment]
if 0.4 is still supported, it should still be tested on travis

**Comment by dpsanders** [comment]
It is: 
https://travis-ci.org/dpsanders/IntervalConstraintProgramming.jl/jobs/183622138

**Comment by dpsanders** [comment]
The `master` branch is in the middle of a complete rewrite that broke functionality. 
Can I just rename `master` to something else and make this one `master`?

**Comment by simonbyrne** [comment]
Is the branch name a problem?

**Comment by tkelman** [comment]
You could also change the default branch setting on gjthub, that way people will see whichever branch you want them to by default.

**Pull request merged**
