### PR TITLE
Tag PATHSolver v0.0.3  /  Tag Complementarity v0.0.3

### PR DESCRIPTION
**Pull request by chkwon**
Updates in user interfaces of Complementarity.jl

Updates in interfaces between Complementarity.jl and PATHSolver.jl

Bug fixes in Complementarity.jl

### CODE REVIEW

**Comment by chkwon** [comment]
Travis may fail, because the new Complementarity.jl requires the new PATHSolver.jl

**Comment by mlubin** [comment]
Cool stuff!

**Comment by tkelman** [comment]
It's best to add a lower bound version number in REQUIRE when the dependencies are closely coupled.

**Comment by chkwon** [comment]
@mlubin Thanks!

@tkelman Yes, I'll do it in the future. Thanks for the help!

**Pull request merged**
