### PR TITLE
Tag InfrastructureModels.jl v0.0.13

### PR DESCRIPTION
**Pull request by attobot**
Repository: [lanl-ansi/InfrastructureModels.jl](https://github.com/lanl-ansi/InfrastructureModels.jl)
Release: [v0.0.13](https://github.com/lanl-ansi/InfrastructureModels.jl/releases/tag/v0.0.13)
Travis: [Travis Build Status](https://travis-ci.org/lanl-ansi/InfrastructureModels.jl/builds/471079110)
Diff: [vs v0.0.12](https://github.com/lanl-ansi/InfrastructureModels.jl/compare/f411fe0c572cfc53290037332b8f74dd95bc8f20...310b7bc21638e741ae76144fada55b24d5d7f94c)
`requires` vs v0.0.12: no changes
cc: @ccoffrin

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by ccoffrin** [comment]
@andreasnoack, can we get a restart on this one?

**Comment by andreasnoack** [comment]
Please just remove and reapply the tag/release. That will automatically trigger the tests. It will also ensure that the PR is merged if tests pass. The latter won't happen automatically if I trigger the tests.

**Comment by ccoffrin** [comment]
@andreasnoack had a look at the CIBot logs.  Failures seem to be due to an upstream issue in pulling down files to build Ipopt.jl.  Is there anything you would like done to finish this?

**Comment by ccoffrin** [comment]
Note both PowerModels and GasModels are waiting on this tag to make their next releases.  I don't see any clear way to resolve the CIBot issues.

**Comment by andreasnoack** [comment]
Note that this doesn't seem to happen for the current release. Any idea why this release could have such an effect on Ipopt.jl?

**Comment by ccoffrin** [comment]
I reviewed all of the logs for failed cases in detail.  In each case, the reported issue is, 
> www.coin-or.org port 80: Connection timed out 

which is an HTTP request inside of Ipopt.jl's build script.  This an up stream dependency, which is out of my control, and independent of any changes that were made in this release of InfrastructureModels.

I experience this error at random on my travis builds in about 1/3 of case, restarting the build often resolves the issue.  As far as I can tell, the fails we are seeing here are just random luck if the Ipopt build passes or not.  One explanation of why they all occur in the "New" category is that coin-or.org had a short term network issue that only occurred after the "Current" builds were complete.

**Comment by andreasnoack** [comment]
Okay. Sounds plausible. Thanks for looking into the issue.

**Comment by ccoffrin** [comment]
Thanks!

**Pull request merged**
