### PR TITLE
Register new package Libtask.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [TuringLang/Libtask.jl](https://github.com/TuringLang/Libtask.jl)
Release: [v0.1.1](https://github.com/TuringLang/Libtask.jl/releases/tag/v0.1.1)
cc: @yebai

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@yebai This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please enable Travis testing and add the badge to your README.

**Comment by andreasnoack** [comment]
Please make Julia 1.0 the minimum requirement if 0.7 isn't supported.

**Comment by yebai** [comment]
@andreasnoack The package works with both Julia 0.7 and 1.0 (see [here](
https://ci.appveyor.com/project/TuringLang/libtask-jl/branch/master)). Seems something got wrong on JuliaCIBot.

**Comment by andreasnoack** [comment]
These are the tests for this release https://travis-ci.org/TuringLang/Libtask.jl/builds/425216590 where 0.7 isn't tested. I'll try to restart CIBot.

**Comment by yebai** [comment]
I just enabled Travis test on julia 0.7. The error message comes from `BinaryProvider`:

```julia
┌ Error: Error building `Libtask`: 
│ [ Info: Downloading https://github.com/hessammehr/LibtaskBuilder2/releases/download/1.0.1/Libtask.v1.0.0.x86_64-linux-gnu.tar.gz to /home/travis/build/TuringLang/Libtask.jl/deps/usr/downloads/Libtask.v1.0.0.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: LibraryProduct(nothing, ["libtask"], :libtask, "Prefix(/home/travis/build/TuringLang/Libtask.jl/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#134(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/travis/.julia/packages/BinaryProvider/UTYxu/src/Products.jl:409
│  [3] write_deps_file(::String, ::Array{LibraryProduct,1}) at /home/travis/.julia/packages/BinaryProvider/UTYxu/src/Products.jl:396
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1038
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:398
│  [9] top-level scope at none:0
│ in expression starting at /home/travis/build/TuringLang/Libtask.jl/deps/build.jl:39
```

**Comment by andreasnoack** [comment]
Would be great if you could look into why it errors. Alternatively, you could require Julia 1.0.

**Comment by yebai** [comment]
> Would be great if you could look into why it errors. Alternatively, you could require Julia 1.0.

I can't seem to find out why `BinaryProvider` does not work on Travis under Julia 0.7. It works well on appveyor... 

In the meantime, I've made `Libtask` require Julia 1.0. Will revisit this when `BinaryProvider` got a new release.

**Comment by yebai** [comment]
@andreasnoack if we look at the following travis testing result, it seems that `BinaryProvider` has an issue on Julia 0.7 for Linux (OSX works fine).

https://travis-ci.org/TuringLang/Libtask.jl/builds/425655205

**Comment by andreasnoack** [comment]
@staticfloat Is this a known issue?

**Comment by yebai** [comment]
@andreasnoack There is nothing that can be done on Libtask’s side. This is ready for merging when you are happy.

**Pull request merged**
