### PR TITLE
Register new package Ripemd.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [gdkrmr/Ripemd.jl](https://github.com/gdkrmr/Ripemd.jl)
Release: [v0.2.0](https://github.com/gdkrmr/Ripemd.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/gdkrmr/Ripemd.jl/builds/454606585)
cc: @gdkrmr

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@gdkrmr This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
What is the meaning of the name of the package? What does the package actually do? This information needs to be available in the readme.

**Comment by gdkrmr** [comment]
I will update the readme accordingly. This is one of the cases where, if you don't know what it is you almost surely don't need it ;-).
What should I do with the tag? Delete it and place it again or increment the version number?

**Comment by dpsanders** [comment]
You can delete the tag and the release and make a release with the same number. This will update the PR automatically.

**Comment by dpsanders** [comment]
It looks like it should maybe be RIPEMD.jl?

**Comment by gdkrmr** [comment]
Does attobot work with tags that I push from a local git repo?

**Comment by gdkrmr** [comment]
- Updated README.md
- moved the v0.2.0 tag to the tip of current master

**Comment by andreasnoack** [comment]
> Does attobot work with tags that I push from a local git repo?

No. You'll have to you GitHub for this.

**Comment by gdkrmr** [comment]
I seems that attobot worked now. I had to actually delete the release on Github and recreate it after moving the tag on my local machine. The button for deleting a release this is really hard to find.

**Comment by andreasnoack** [comment]
Please avoid commenting on PRs where things are good. See https://discourse.julialang.org/t/the-current-metadata-release-process/16672 for more details.

**Comment by gdkrmr** [comment]
sorry. I also saw that there is a description on how to delete releases.

**Pull request merged**
