### PR TITLE
Register new package UNSflow.jl v0.5.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [KiranUofG/UNSflow.jl](https://github.com/KiranUofG/UNSflow.jl)
Release: [v0.5.1](https://github.com/KiranUofG/UNSflow.jl/releases/tag/v0.5.1)
cc: @KiranUofG

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@KiranUofG This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
Please don't use abbreviations in package names.

**Comment by KiranRamesh-Aero** [comment]
We've modified the package name to UnsteadyFlowSolvers.jl

**Comment by KiranRamesh-Aero** [comment]
We’ve changed the package name based on the feedback, can you please merge?

Thanks,
Kiran



On 31 Dec 2018, at 7:51 pm, David P. Sanders <notifications@github.com<mailto:notifications@github.com>> wrote:


Please don't use abbreviations in package names.

**Comment by dpsanders** [comment]
You will need to register the package again with the new name, which is why this was closed. Just delete the tag and the release and make a new release, then attobot will pick up the new name.

**Pull request closed without merging**
