### PR TITLE
Tag NIRX.jl v0.1.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rob-luke/NIRX.jl](https://github.com/rob-luke/NIRX.jl)
Release: [v0.1.3](https://github.com/rob-luke/NIRX.jl/releases/tag/v0.1.3)
Diff: [vs v0.1.2](https://github.com/rob-luke/NIRX.jl/compare/96454b18675e0d067023429f6a95918b7ea64f64...8daa946d59fdc3fed6e2f6a62486a0408431f814)
`requires` vs v0.1.2: no changes
cc: @rob-luke

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by rob-luke** [comment]
The CI is failing with the following error. However, it passes on the Travis CI for both Linux and OSX.

```bash
ERROR: LoadError: DataDeps.DisabledError("DataDeps download disabled, as we appear to be in a CI environment, and the environment variable `DATADEPS_ALWAYS_ACCEPT` is not set.\nIf this is indeed running in a headless CI environment, then set the `DATADEPS_ALWAYS_ACCEPT` environment variable to `true` to bypass the accept download prompt (if you do wish to always accept.)\nIf not, then either unset the `CI` environment variable from true, or set `DATADEPS_ALWAYS_ACCEPT` to `false` for the normal prompt behaviour.")
```

**Comment by rob-luke** [comment]
For travis I have the env variable set using

```bash
env:
  global:
- DATADEPS_ALWAYS_ACCEPT=true  
```

is there an equivelent way to specify this for JuliaCIBot?

**Comment by andreasnoack** [comment]
cc @oxinabox

**Comment by oxinabox** [comment]
For now, for JuliaCIBot 
add to the top of `runtests.jl`

`ENV["DATADEPS_ALWAYS_ACCEPT"] = "true"`

@andreasnoack  did we have a discussion a while back about making JuliaCIBot read travis config?

**Comment by andreasnoack** [comment]
I might have mentioned it. We are currently parsing the `.travis.yml` but not really doing anything with the info. We'd have to refactor most of CIBot when we leave METADATA so I'll probably not spend time on it before then. The good news is that we'll develop the new version openly, so you might be one to implement the feature.

**Comment by oxinabox** [comment]
mhmm yes, possible.

**Comment by rob-luke** [comment]
Can this please be merged? And for my next commit I will follow the suggestion from oxinabox

**Comment by andreasnoack** [comment]
You can make the change and update the PR. However, since no packages depend on your package, it should be fine just to merge as is.

**Pull request merged**
