### PR TITLE
Tag Blocks v0.1.0

### PR DESCRIPTION
**Pull request by tanmaykm**

### CODE REVIEW

**Comment by tkelman** [comment]
Could this be made 0.1.0 instead? That way we could tag an 0.0.8 or 0.0.9 for 0.3 bugfixes in the future, ref https://github.com/JuliaLang/METADATA.jl/pull/3502#issuecomment-144890283

**Comment by hayd** [comment]
Can't you just release 0.7.1 in that case?

**Comment by tanmaykm** [comment]
Yes. Will change to 0.1.0

**Comment by tkelman** [comment]
Thanks!

**Pull request merged**
