### PR TITLE
Minor version bump for Interpolations

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
I'm pretty surprised that it would take Travis more than 7 hours to get to this. Any ideas about what's up?

**Comment by IainNZ** [comment]
I've just cancelled and restarted all the outstanding Travis builds, we'll see what happens I suppose

**Comment by IainNZ** [comment]
I'm not entirely sure I'm reading https://www.traviscistatus.com/ right, but it seems like maybe they are at capacity?

**Comment by timholy** [comment]
Thanks for pointing that page out, @IainNZ.

**Comment by tkelman** [comment]
We could try adding `sudo: false` to `.travis.yml` to make the builds use docker workers, which should have a quicker queue time.

**Pull request merged**
