### PR TITLE
Register LLVM [https://github.com/maleadt/LLVM.jl.git]: v0.1.0

### PR DESCRIPTION
**Pull request by maleadt**
Had to do this outside of PkgDev, so apologies if I messed something up. Not sure why it used `https://` instead of `git://`.

### CODE REVIEW

**Comment by tkelman** [comment]
Should this be exporting `Module`, considering that name is exported from Core?

**Comment by maleadt** [comment]
Yeah that is a valid critique, given we need to specify `LLVM.Module` anyway because of that conflict (same applies to `Function`).

What is the typical approach here? Have users specify the module for those conflicting names (ie. `LLVM.Module`, as I did here)? Or rename the types to make them safe (eg. `LLVMModule`)?

**Comment by tkelman** [comment]
I think it'll be confusing to keep track in your own code when you're referring to LLVM Module vs Julia Module. If you do use the same name, take it out of exports.

**Comment by maleadt** [comment]
I've kept it as is for now, can always change if it turns out to be too confusing.
Removed the exports and replaced the tags, should be good to go.

**Pull request merged**
