### PR TITLE
Tag BusinessDays.jl v0.9.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [felipenoris/BusinessDays.jl](https://github.com/felipenoris/BusinessDays.jl)
Release: [v0.9.0](https://github.com/felipenoris/BusinessDays.jl/releases/tag/v0.9.0)
Travis: [Travis Build Status](https://travis-ci.org/felipenoris/BusinessDays.jl/builds/415130909)
Diff: [vs v0.8.4](https://github.com/felipenoris/BusinessDays.jl/compare/7581db22ee54ad343159c59b5bb46cbf38f61354...e8b65bb0790a432ef2a58bf89730c3652bc72c1f)
`requires` vs v0.8.4: 
```diff
--- 0.8.4/requires
+++ 0.9.0/requires
@@ -1 +1 @@
-julia 0.6
+julia 0.7
```
cc: @felipenoris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by felipenoris** [comment]
@andreasnoack , I guess there was a problem with the travis build. How can I force a new travis build?

**Comment by andreasnoack** [comment]
I should have noticed that. I'll restart the build.

**Comment by felipenoris** [comment]
JuliaCIBot has a strange error when testing under Julia v1.0 . It tries to load OldPkg and fails.
I should point out that `BusinessDays` tests pass on v1.0 .

**Comment by andreasnoack** [comment]
CIBot is not yet working on Julia 1.0

**Pull request merged**
