### PR TITLE
Tag AbstractAlgebra.jl v0.0.9

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like this breaks Nemo

**Comment by thofma** [comment]
It does not. The last line of the log reads "INFO: Nemo tests passed". The same for Hecke. The display of the test results seems to be bugged.

**Comment by andreasnoack** [comment]
I see. We have had some issues with CIBot lately and are looking into them.

**Comment by thofma** [comment]
I have been waiting for 10 days for this to be merged. I opened this PR here because https://github.com/JuliaLang/METADATA.jl/pull/16009 is stalling for no reason.

**Comment by andreasnoack** [comment]
It's vacation season and we have had some issues with CIBot which has caused some delays. Sorry for the inconvenience. Is #16009 still relevant or should it be closed?

**Comment by thofma** [comment]
#16009 can be closed.

**Pull request merged**
