### PR TITLE
Tag ApproxFun v0.6.0 [https://github.com/JuliaApproximation/ApproxFun…

### PR DESCRIPTION
**Pull request by dlfivefifty**
….jl]

Supports Julia 0.6

### CODE REVIEW

**Comment by tkelman** [comment]
Will SingularIntegralEquations 0.2.2 need an upper bound?

**Comment by dlfivefifty** [comment]
Yes, I was going to add it when I tagged a new version

**Comment by tkelman** [comment]
better to do now, otherwise Pkg.update() will break SingularIntegralEquations for any users

**Comment by dlfivefifty** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8495

**Pull request merged**
