### PR TITLE
Register new package Poltergeist.jl v0.0.4

### PR DESCRIPTION
**Pull request by attobot**
Repository: [wormell/Poltergeist.jl](https://github.com/wormell/Poltergeist.jl)
Release: [v0.0.4](https://github.com/wormell/Poltergeist.jl/releases/tag/v0.0.4)
cc: @wormell

### CODE REVIEW

**Comment by dpsanders** [comment]
This looks like a very nice package! Any particular reason you chose that license? As far as I understand, it's not compatible with MIT, for example (only the 3-clause BSD is?)

**Comment by dpsanders** [comment]
(And very clever, although obscure, package name!)

**Comment by ararslan** [comment]
The BSD 2-clause license is quite similar to MIT, actually. And I don't think any of the BSD licenses are incompatible with MIT (which is itself a BSD-style license). [This](https://opensource.stackexchange.com/a/582) is a good explanation of BSD vs. MIT.

**Comment by dpsanders** [comment]
Ah OK, thanks for the clarification - my mistake.

**Comment by wormell** [comment]
Thanks @dpsanders, glad you like it! Two-clause seems like the default BSD licence in PkgDev for whatever (nefarious?) reason so I went with that

**Comment by ararslan** [comment]
Is that the default? It might just be the first sorted alphanumerically. It's a good, solid license nonetheless though. 🙂

**Comment by dpsanders** [comment]
I don't think there is a default: the license has to specified explicitly?

**Pull request merged**
