### PR TITLE
Tag BioSequences.jl v0.6.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [BioJulia/BioSequences.jl](https://github.com/BioJulia/BioSequences.jl)
Release: [v0.6.2](https://github.com/BioJulia/BioSequences.jl/releases/tag/v0.6.2)
Travis: [Travis Build Status](https://travis-ci.org/BioJulia/BioSequences.jl/builds/250708273)
Diff: [vs v0.6.1](https://github.com/BioJulia/BioSequences.jl/compare/3904c46d6f513dae3cb13c533c46251e09adff5a...f7f4d882f1c8475a06b264fc4a10bf8f14d16c7a)
`requires` vs v0.6.1: 
```diff
--- 0.6.1/requires
+++ 0.6.2/requires
@@ -6,7 +6,7 @@
 Combinatorics
 Compat 0.18
 IndexableBitVectors
-Iterators
+IterTools 0.1
 IntervalTrees
 Twiddle
 DataStructures
```
cc: @Ward9250

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by tkelman** [comment]
this should be a new tag, don't change an existing one. please put the 0.6.2 git tag back to what metadata says it was.

**Comment by Ward9250** [comment]
0.6.2 doesn't exist? I don't know why is would already be in metadata.

**Comment by tkelman** [comment]
see #9941 it was tagged 2 weeks ago but someone deleted it?

**Comment by Ward9250** [comment]
Ohhhh ok now I know what's going on. This morning, the tag 0.6.2 existed, but the associated release was for some reason, in draft state, so I thought it was a hot-fix release I didn't quite hit the go button on, Kenta made some more hot-fixes so I thought, oh well they might as well go in 0.6.2 as well, thinking I hadn't release 0.6.2 yet. I can fix this.

**Pull request closed without merging**
