### PR TITLE
Tag PkgTemplates.jl v0.3.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [invenia/PkgTemplates.jl](https://github.com/invenia/PkgTemplates.jl)
Release: [v0.3.0](https://github.com/invenia/PkgTemplates.jl/releases/tag/v0.3.0)
Travis: [Travis Build Status](https://travis-ci.org/invenia/PkgTemplates.jl/builds/441762412)
Diff: [vs v0.2.3](https://github.com/invenia/PkgTemplates.jl/compare/7e38c924132f70b12eceb2dc01dabafdc3a1fea5...b55dc64ff1e6c149aa7485d53f66e290a8e9be2b)
`requires` vs v0.2.3: 
```diff
--- 0.2.3/requires
+++ 0.3.0/requires
@@ -1,5 +1,4 @@
-julia 0.6
+julia 0.7
 AutoHashEquals
 Mustache
-TerminalMenus
 URIParser
```
cc: @christopher-dG

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by christopher-dG** [comment]
Could anyone help me figure out why JuliaCIBot tests are failing? It seems that it's trying to add PkgTemplates from the General registry where no version for 0.7/1.0 exists yet.

**Comment by andreasnoack** [comment]
The error is
```julia
Interactive package generation: Error During Test at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/test/interactive/interactive.jl:53
  Got exception outside of a @test
  GitError(Code:ENOTFOUND, Class:Config, config value 'user.name' was not found)
  Stacktrace:
   [1] default_signature(::GitRepo) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LibGit2/src/error.jl:101
   [2] LibGit2.Signature(::GitRepo) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LibGit2/src/signature.jl:25
   [3] commit at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LibGit2/src/commit.jl:113 [inlined]
   [4] macro expansion at ./logging.jl:307 [inlined]
   [5] generate(::String, ::Template) at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/src/generate.jl:19
   [6] generate_interactive(::String) at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/src/generate.jl:74
   [7] macro expansion at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/test/interactive/interactive.jl:55 [inlined]
   [8] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [9] top-level scope at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/test/interactive/interactive.jl:54
   [10] include at ./boot.jl:317 [inlined]
   [11] include_relative(::Module, ::String) at ./loading.jl:1038
   [12] include(::Module, ::String) at ./sysimg.jl:29
   [13] include(::String) at ./client.jl:388
   [14] top-level scope at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/test/tests.jl:99 [inlined]
   [15] top-level scope at ./none:0
   [16] include at ./boot.jl:317 [inlined]
   [17] include_relative(::Module, ::String) at ./loading.jl:1038
   [18] include(::Module, ::String) at ./sysimg.jl:29
   [19] include(::String) at ./client.jl:388
   [20] macro expansion at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/test/runtests.jl:16 [inlined]
   [21] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [22] (::getfield(Main, Symbol("##4#6")))() at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/test/runtests.jl:16
   [23] cd(::getfield(Main, Symbol("##4#6")), ::String) at ./file.jl:96
   [24] (::getfield(Main, Symbol("##3#5")))(::String) at /home/jrun/PkgTemplates/.julia/packages/PkgTemplates/uEunH/test/runtests.jl:14
   [25] mktempdir(::getfield(Main, Symbol("##3#5")), ::String) at ./file.jl:576
   [26] mktempdir(::Function) at ./file.jl:574
   [27] top-level scope at none:0
   [28] include at ./boot.jl:317 [inlined]
   [29] include_relative(::Module, ::String) at ./loading.jl:1038
   [30] include(::Module, ::String) at ./sysimg.jl:29
   [31] include(::String) at ./client.jl:388
   [32] top-level scope at none:0
   [33] eval(::Module, ::Any) at ./boot.jl:319
   [34] macro expansion at ./logging.jl:317 [inlined]
   [35] exec_options(::Base.JLOptions) at ./client.jl:219
   [36] _start() at ./client.jl:421
```

**Comment by fredrikekre** [comment]
Probably https://github.com/JuliaLang/METADATA.jl/pull/18601#issuecomment-429843238

**Comment by christopher-dG** [comment]
I believe https://github.com/invenia/PkgTemplates.jl/pull/29 should take care of this. Should I just make a new release when it's merged?

**Comment by fredrikekre** [comment]
You could just update this release.

**Pull request merged**
