### PR TITLE
Tag Xpress.jl v0.9.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaOpt/Xpress.jl](https://github.com/JuliaOpt/Xpress.jl)
Release: [v0.9.1](https://github.com/JuliaOpt/Xpress.jl/releases/tag/v0.9.1)
Diff: [vs v0.9.0](https://github.com/JuliaOpt/Xpress.jl/compare/17e1acd1e43d5ed0e1ce34b6a9ec2f3aeed2d8d7...6d983b36613586f370958eafcb501124ae68250f)
`requires` vs v0.9.0: 
```diff
--- 0.9.0/requires
+++ 0.9.1/requires
@@ -1,4 +1,4 @@
 julia 0.6
 MathProgBase 0.6 0.8
-LinQuadOptInterface 0.4 0.5
+LinQuadOptInterface 0.6 0.7
 Compat 0.59
```
cc: @joaquimg

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by joaquimg** [comment]
Tests are passing locally on 0.6(.4), 0.7 and 1.0 (1.0.3 and 1.1.0rc1)

cc @hellemo , @mlubin

**Comment by mlubin** [comment]
@joaquimg FYI commenting breaks the auto-merge rules for METADATA.

**Comment by joaquimg** [comment]
oops I missed that. Sorry. Better to close and open a new one?

**Comment by andreasnoack** [comment]
Next time, you can just remove and reapply the tag. That will trigger a new attobot comment which will reenable the auto-merging.

**Pull request merged**
