### PR TITLE
Tag Knet.jl v1.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [denizyuret/Knet.jl](https://github.com/denizyuret/Knet.jl)
Release: [v1.0.1](https://github.com/denizyuret/Knet.jl/releases/tag/v1.0.1)
Travis: [Travis Build Status](https://travis-ci.org/denizyuret/Knet.jl/builds/423067991)
Diff: [vs v1.0.0](https://github.com/denizyuret/Knet.jl/compare/249540aef4949ac38e00eb5d9ec8b109bc62ebe8...4342175488d74cd450e653d01716cb38fc4769bf)
`requires` vs v1.0.0: 
```diff
--- 1.0.0/requires
+++ 1.0.1/requires
@@ -1,10 +1,12 @@
 julia 0.7
-AutoGrad 1.0.0
+AutoGrad 1.0.1
 CUDAapi 0.5.0
 SpecialFunctions 0.7.0
+JLD2 0.1.1
+FileIO 1.0.1
 
 # The following are used by the build script if installed.
 # CUDAdrv, Documenter
 
-# We need the following for some examples. They get automatically installed when needed.
+# We need the following for some examples.  They get automatically installed when needed.
 # ArgParse, JLD, JLD2, Images, GZip, MAT, PyCall, JSON, IJulia, BenchmarkTools, Distributions
```
cc: @denizyuret

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please consider removing the project file since it isn't needed and it currently breaks CIBot.

**Comment by denizyuret** [comment]
Hi Andreas, the gitlab ci (which I use for gpu testing) requires it.

**Comment by andreasnoack** [comment]
I see. Then we'll just have to live without reverse dependency testing here until CIBot has been upgraded.

**Comment by denizyuret** [comment]
OK, thanks.

**Pull request merged**
