### PR TITLE
Tag NamedArrays.jl v0.9.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [davidavdav/NamedArrays.jl](https://github.com/davidavdav/NamedArrays.jl)
Release: [v0.9.2](https://github.com/davidavdav/NamedArrays.jl/releases/tag/v0.9.2)
Travis: [Travis Build Status](https://travis-ci.org/davidavdav/NamedArrays.jl/builds/461686001)
Diff: [vs v0.9.1](https://github.com/davidavdav/NamedArrays.jl/compare/162aa3df705ec4bf841ac0a35e66a704f6d934d1...8ab1e80135b64ef96cb5e83a375700b300957d8a)
`requires` vs v0.9.1: no changes
cc: @davidavdav

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by diegozea** [comment]
Is something wrong with JuliaCIBot? I saw the failed report for NamedArrays (new) and it is not failing: "Testing NamedArrays tests passed"

**Comment by davidavdav** [comment]
I don't know, I just continue to not understand what CIbot does, apart from blocking this release.   Maybe there is something wrong with my "Version bounds reflect minimum requirements".

**Comment by diegozea** [comment]
There is something strange going on. You hasn't changed REQUIRE and the message at the begging agrees with that:
```
Diff: vs v0.9.1
requires vs v0.9.1: no changes
```

**Comment by diegozea** [comment]
JuliaCIBot show fail status for the following packages, however `STDERR` shows only `info` and `warn`ings and `STDOUT` shows:

NamedArrays Julia 0.7 New: "Testing NamedArrays tests passed"
NamedArrays Julia 1.0 New: "Testing NamedArrays tests passed"

PairwiseListMatrices Julia 0.7 Current: "Testing PairwiseListMatrices tests passed"
PairwiseListMatrices Julia 1.0 Current: "Testing PairwiseListMatrices tests passed"

Mimi Julia 1.0 Current: JuliaCIBot error, XML message
Mimi Julia 1.0 New: JuliaCIBot error, XML message

Others:

Testing FreqTables tests passed 
Testing FreqTables tests passed 
Testing CmdStan tests passed
Testing MixedModels tests passed

Maybe JuliaCIBot shows failing because of the unrelated Mimi error

**Comment by diegozea** [comment]
I tested `Mimi` with this `NamedArrays` version and tests passed fine:
image

**Comment by diegozea** [comment]
Is not possible for this release to cause that problems. This is the only commit of the new tag: https://github.com/davidavdav/NamedArrays.jl/commit/8ab1e80135b64ef96cb5e83a375700b300957d8a
It only deletes `println` uses for debugging.

**Comment by andreasnoack** [comment]
Unfortunately, CIBot sometimes reports failure even when tests pass. We still don't know why it happens. It looks like all of the failures are spurious.

**Comment by diegozea** [comment]
Thanks @davidavdav & @andreasnoack :)

**Pull request merged**
