### PR TITLE
Tag NormalizeQuantiles.jl v0.3.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [oheil/NormalizeQuantiles.jl](https://github.com/oheil/NormalizeQuantiles.jl)
Release: [v0.3.3](https://github.com/oheil/NormalizeQuantiles.jl/releases/tag/v0.3.3)
Travis: [Travis Build Status](https://travis-ci.org/oheil/NormalizeQuantiles.jl/builds/318592216)
Diff: [vs v0.3.2](https://github.com/oheil/NormalizeQuantiles.jl/compare/603be7e159d37d25e4459343d7e859d9ccaa21f0...6ae5e76b3f81e53914e8f363fc0cea8dfd2c9467)
`requires` vs v0.3.2: 
```diff
--- 0.3.2/requires
+++ 0.3.3/requires
@@ -1 +1 @@
-julia 0.4+julia 0.4 0.6.999
```
cc: @oheil

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by oheil** [comment]
I want to redesign the code quite completely for the 0.7 introduction of "missing" values.

Therefore I thought I could make the current code somehow fix with requirement:
julia 0.4 0.6.999

Future bug fixes could be done in a new branch e.g. "backport 0.6" and will be tagged v0.3.4 and so on.

The master branch with new code based on "missing" will get requirement
julia 0.7
and will be tagged v0.4.0...

The idea is according to 
https://discourse.julialang.org/t/julia-package-different-branches-for-different-julia-versions/4718

Is this a proper way to do it?

Is it possible to still release on the new branch "backport 0.6" with tags v0.3.4... and in parallel on the master branch with tags v0.4.0... ? 
Goal:
  *  julia 0.6 (or 0.5,0.4) users use Pkg.update() and get the latest v0.3 tagged package
  *  julia 0.7 users use Pkg.update() and get the latest v0.4 tagged package

How can I release this version (v.0.3.3) without dropping julia 0.4 support, because it is still supported? (See fail of Travis build)

Thanks a lot for your (all of you) amazing work on julia!

**Comment by oheil** [comment]
removed 0.4 tests from appveyor.yml and .travis.yml

**Comment by oheil** [comment]
removed 0.4 tests from REQUIRE

**Comment by oheil** [comment]
Pull request can be canceled and closed.

**Comment by aviks** [comment]
Hi, @oheil So if you need to still support 0.4, we will need to manually add an exception for you package, after which you can release a 0.3.3 version that supports julia 0.4. We have this check since most users do not test on 0.4, and we do not want unsupported version bounds by default. 

Your other option is to drop julia 0.4 support, and tag your package `v0.4.0`.  Let us know if you want to proceed with either of these options. 

Sorry if you have felt frustrated with this. The rules were made for a reason, but I accept they can feel annoying in certain cases.

**Comment by oheil** [comment]
Hi, @aviks ,
thanks for your understanding.
On the root of the matter it is not so important which version my package has, 0.3 or 0.4 makes no difference for me or for users. So I am fine with the 0.4 merge. For the julia 0.7 development I will start over with 0.5.

All in all it would be much easier and less "frustrating" if there is a point to go to look for the current rules of METADATA pull requests. I would suggest a README.md in JuliaLang/METADATA.jl with some notes for package maintainers. Or is there something somewhere?

Anyways, this pull request can be canceled and closed (I can't do it since attobot is doing the magic).

THANKS A LOT TO YOU ALL FOR YOUR AWESOME WORK ON JULIA!!!!
(I am coming from R and lots of other languages and IMHO julia rocks)

**Pull request closed without merging**
