### PR TITLE
Tag GR.jl v0.34.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jheinen/GR.jl](https://github.com/jheinen/GR.jl)
Release: [v0.34.1](https://github.com/jheinen/GR.jl/releases/tag/v0.34.1)
Travis: [Travis Build Status](https://travis-ci.org/jheinen/GR.jl/builds/425764078)
Diff: [vs v0.33.1](https://github.com/jheinen/GR.jl/compare/ef06aa9933dc75ded25076aa1810029a1fad2497...9c5f03b2421f671b9d3749603d36fa378c9514cc)
`requires` vs v0.33.1: no changes
cc: @jheinen

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Please just update #17824 instead of opening a new PRs. See https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by jheinen** [comment]
I read this too late. Please merge v0.34.1, as there is a change in the `deps/build.jl` script. Sorry for the noise ...

**Comment by andreasnoack** [comment]
I closed this one so please delete and reapply the tag for v0.34.1 and I'll merge as soon as tests pass. But please update a single PR in the future. Having multiple PRs open here is confusing and error prone.

**Comment by jheinen** [comment]
Thanks. I republished the tag for v0.34.1. Sorry for the confusion ...

**Pull request closed without merging**
