### PR TITLE
Register PAINTER: v0.1.0, v0.1.1

### PR DESCRIPTION
**Pull request by andferrari**
``Painter.jl`` is a julia implementation of PAINTER: Polychromatic opticAl INTErferometric Reconstruction algorithm.

### CODE REVIEW

**Comment by IainNZ** [comment]
The package name/code all use Painter, but the MeTADATA is PAINTER. It should be one or the other consistently.

**Comment by andferrari** [comment]
Thank your for the help.
Do I have to register again the package with a new name: Pkg.register("Painter") ?

**Comment by StefanKarpinski** [comment]
I would just edit the METADATA files manually, do a git amend and then push to this branch again.

**Comment by IainNZ** [comment]
I actually preferred the PAINTER version given that its an acronym/name of an algorithm, but Painter is fine too I suppose

**Comment by dpsanders** [comment]
On 29 May 2015 17:53, "Iain Dunning" <notifications@github.com> wrote:
>
> I actually preferred the PAINTER version given that its an acronym/name
of an algorithm,

I agree.

> but Painter is fine too I suppose

I don't think so, since this will lead people to think that the package is
about graphics or even (possibly?) art criticism. At least the capital
letters are a giveaway that the name is not to be taken literally.

**Comment by andferrari** [comment]
Thank you for your comments. I have renames the package PAINTER.

**Comment by IainNZ** [comment]
Closed by #2660

**Pull request closed without merging**
