### PR TITLE
Register new package PrettyPlots.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMPC/PrettyPlots.jl](https://github.com/JuliaMPC/PrettyPlots.jl)
Release: [v0.1.1](https://github.com/JuliaMPC/PrettyPlots.jl/releases/tag/v0.1.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMPC/PrettyPlots.jl/builds/245931705)
cc: @huckl3b3rry87

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@huckl3b3rry87 This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
Colors and NLOptControl are used here so should be listed in REQUIRE

**Comment by diegozea** [comment]
The name of the package makes me think in something related to (more general) graphic/plot aesthetics. Other package with a similar name refers to that: [Python - prettyplotlib](https://github.com/olgabot/prettyplotlib)

**Comment by tkelman** [comment]
Yeah, may want to use a more specific name here.

**Comment by aviks** [comment]
Hi @huckl3b3rry87 Do you want to keep this name, or do you wish to change it? Also some basic documentation about the package would be useful.

**Comment by huckl3b3rry87** [comment]
@aviks I would prefer not changing the name since it will require a bit of work on my end and I am currently pretty busy. But I understand the concern that @diegozea brings up that it may cause confusion, so if the community prefers, I will change the name, but it may take some time for me to get around to it. What does everyone prefer? If it it is to change the name, are there any suggestions? MPCPlots.jl?

**Comment by tkelman** [comment]
MPCPlots would be a bit better, though the acronym isn't universally known. Will need to fix the missing dependencies, so this shouldn't be merged as-is if you want the package to work correctly.

**Comment by huckl3b3rry87** [comment]
@tkelman this pull request was replaced by https://github.com/JuliaLang/METADATA.jl/pull/11053. Thank you!

**Pull request closed without merging**
