### PR TITLE
Pull request/35c7e7f3

### PR DESCRIPTION
**Pull request by andrewcooke**

### CODE REVIEW

**Comment by IainNZ** [comment]
No ParserCombinator**s**.jl?

**Comment by andrewcooke** [comment]
don't people normally say "it's a parser combinator library" rather than "it's a parser combinators library"?  i don't know why - it just seems to be normal use.  i think?

**Comment by IainNZ** [comment]
More just a general trend in Julia pacakges to use plurals for the package name, is all. Not an actual problem :+1:

**Comment by andrewcooke** [comment]
well, it's on it's third name already.  maybe this is good enough.

**Pull request merged**
