### PR TITLE
Tag DataDeps.jl v0.5.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [oxinabox/DataDeps.jl](https://github.com/oxinabox/DataDeps.jl)
Release: [v0.5.2](https://github.com/oxinabox/DataDeps.jl/releases/tag/v0.5.2)
Travis: [Travis Build Status](https://travis-ci.org/oxinabox/DataDeps.jl/builds/425645106)
Diff: [vs v0.5.1](https://github.com/oxinabox/DataDeps.jl/compare/e0e6c155d0a0f461336a36938aa426fe5f984542...c68d718d105986bd7dbe40f2d368cde993bb3d2f)
`requires` vs v0.5.1: 
```diff
--- 0.5.1/requires
+++ 0.5.2/requires
@@ -1,4 +1,3 @@
 julia 0.7-beta
-SHA
 Reexport
 HTTP 0.6
```
cc: @oxinabox

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by oxinabox** [comment]
@andreasnoack  re: https://github.com/JuliaLang/METADATA.jl/pull/17556#issuecomment-418088711

**Comment by andreasnoack** [comment]
I've been able to make a partial fix for the project file issue in CIBot but it doesn't work yet for test dependencies so thanks for disabling the project file for the time being. We are working on fixing the issue completely so hopefully it should soon be fine with project files.

**Comment by andreasnoack** [comment]
This killed CIBot again
```
2.5M	./cijm17818pr07datadepsgenerators
2.6M	./cijm17556pr07tsne
2.6M	./cijm17556pr10tsne
33G	./cijm1782010embeddings
39G	./cijm1782010datadeps
44G	./cijm1782007embeddings
```

**Comment by oxinabox** [comment]
Sorry, I am still debugging that.
I have an open PR against myself

**Pull request merged**
