### PR TITLE
Tag DiffEqSensitivity.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DiffEqSensitivity.jl](https://github.com/JuliaDiffEq/DiffEqSensitivity.jl)
Release: [v0.1.0](https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/DiffEqSensitivity.jl/builds/221429787)
Diff: [vs v0.0.4](https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/compare/89a4d10352336d50fed55fec61ef39fca1c21696...aa4d6e3693128599da8e28f8658c372f703e5731)
`requires` vs v0.0.4: 
```diff
--- 0.0.4/requires
+++ 0.1.0/requires
@@ -1,2 +1,2 @@
 julia 0.5
-DiffEqBase 0.2.0 0.15.0
+DiffEqBase 0.15.0
```
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by tkelman** [comment]
`UndefVarError: numparameters not defined`
where should that be coming from?

**Comment by ChrisRackauckas** [comment]
That was something changed in DiffEqBase to `numargs`. 

I noticed this was actually missing a commit, so I updated the release... but I first misnamed the version to v0.2.0, and now when I update v0.1.0 attobot isn't updating this PR.

**Comment by tkelman** [comment]
Do you want to close this and just skip publishing 0.1.0, or what then?

**Comment by ChrisRackauckas** [comment]
Sure, if that's easier on attobot.

**Comment by tkelman** [comment]
Dunno, though looks like you deleted the 0.2.0 tag so either way one of the tags needs to be replaced. Let's try closing 0.2.0, wait the 20 second delay to be sure attobot deletes the branch, and see if updating 0.1.0 works again.

**Comment by ChrisRackauckas** [comment]
Got it.

**Comment by tkelman** [comment]
replaced by https://github.com/JuliaLang/METADATA.jl/pull/8831

**Pull request closed without merging**
