### PR TITLE
Register new package WeightedOnlineStats.jl v0.1.5

### PR DESCRIPTION
**Pull request by attobot**
Repository: [gdkrmr/WeightedOnlineStats.jl](https://github.com/gdkrmr/WeightedOnlineStats.jl)
Release: [v0.1.5](https://github.com/gdkrmr/WeightedOnlineStats.jl/releases/tag/v0.1.5)
Travis: [Travis Build Status](https://travis-ci.org/gdkrmr/WeightedOnlineStats.jl/builds/461803231)
cc: @gdkrmr

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@gdkrmr This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by mkborregaard** [comment]
There's nothing in the REQUIRE file - that must be a mistake?

**Comment by gdkrmr** [comment]
Has there to be? I thought it was only for older Julia versions and for METADATA.jl.

**Comment by andreasnoack** [comment]
@gdkrmr Please see https://discourse.julialang.org/t/the-current-metadata-release-process/16672

**Comment by gdkrmr** [comment]
ok, sorry for my ignorance, v0.1.6 is here: #19867

**Pull request merged**
