### PR TITLE
Tag AbaqusReader.jl v0.1.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaFEM/AbaqusReader.jl](https://github.com/JuliaFEM/AbaqusReader.jl)
Release: [v0.1.3](https://github.com/JuliaFEM/AbaqusReader.jl/releases/tag/v0.1.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaFEM/AbaqusReader.jl/builds/415410743)
Diff: [vs v0.1.2](https://github.com/JuliaFEM/AbaqusReader.jl/compare/e290262b6a878f93d4f1a03c5c41925fc1331d2c...09b6538108798fbcb92d787969c4e1b87c2885f4)
`requires` vs v0.1.2: no changes
cc: @ahojukka5

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like tests are failing

**Comment by ahojukka5** [comment]
Yes, I noticed that and did fixup. Now it's working, how to proceed?

**Comment by andreasnoack** [comment]
You can delete this tag and reapply it to a commit with the fixes. That will automatically update this PR.

**Comment by ahojukka5** [comment]
Hmm I think I applied tag again but still fails.

**Comment by andreasnoack** [comment]
It doesn't look like the PR has been updated. You'd have to delete both the release and the tag before reapplying.

**Comment by andreasnoack** [comment]
Looks like the PR got updated now.

**Pull request merged**
