### PR TITLE
Register new package LightQuery.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bramtayl/LightQuery.jl](https://github.com/bramtayl/LightQuery.jl)
Release: [v0.0.1](https://github.com/bramtayl/LightQuery.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/bramtayl/LightQuery.jl/builds/431908652)
cc: @bramtayl

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@bramtayl This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by bramtayl** [comment]
Fails on 0.6 but I think thats ok?

**Comment by bramtayl** [comment]
Hello?

**Comment by bramtayl** [comment]
Hmm. Is everyone super busy or are the julia gods angry at me?

**Comment by diegozea** [comment]
> Fails on 0.6 but I think thats ok?

Does this need to support Julia 0.6? If it's intended to be only 0.7/1.0, REQUIRE should be changed.

**Comment by bramtayl** [comment]
Aha! Thanks!

**Comment by bramtayl** [comment]
Hmm... Would people be happier if I made PR to query packages to add LightQuery compatible methods before I release this? I was kinda waiting for it to get released, cause I thought that would add some legitimacy to my PRs, but...

**Comment by bramtayl** [comment]
Or are people mad that I deleted a bunch of my experimental repos? I can't promise I won't do this with LightQuery either but I think there's a lot of promise here.

**Comment by andreasnoack** [comment]
Much of the process for registering packages is now automated so when tests don't pass there is a risk that the merging is delayed. Hence, make sure that tests pass before opening the PR. Deleting repos didn't have anything to do with the delay here.

However, 

> I can't promise I won't do this with `LightQuery`

Please don't deleted repos for registered packages. If you think you might delete the repo then don't register the package. If you decide to delete a repo for a registered package anyway then please at least make it uninstallable first. I've spent quite a bit of time on handling your previously deleted repos.

**Pull request merged**
