### PR TITLE
Tag Julz v0.1.0 [https://github.com/djsegal/Julz.jl]

### PR DESCRIPTION
**Pull request by djsegal**
Diff vs v0.0.2: https://github.com/djsegal/Julz.jl/compare/8cb10b52a6acdea418b42e82fe5acefe3e4e6ebd...9b21100e60ff4e28eb2e40e2ed4052500c6479a6

### CODE REVIEW

**Comment by djsegal** [comment]
Any clue why this is failing?

**Comment by djsegal** [comment]
@tkelman 

How do I find out why this failed?

this is all the logs say:

```julia

INFO: Testing Julz
================================[ ERROR: Julz ]=================================

failed process: Process(`/opt/julia-0.5.2/bin/julia -Cx86-64 -J/opt/julia-0.5.2/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=user --inline=no --color=no --compilecache=yes /mnt/pkgevalempty/82507f5f1126cd6c4035dd8d9f58038164b4347e/Julz/.julia/v0.5/Julz/test/runtests.jl`, ProcessSignaled(6)) [0]

================================================================================
ERROR: Julz had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:748
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in (::Base.Pkg.#kw##test)(::Array{Any,1}, ::Base.Pkg.#test, ::String, ::Vararg{String,N}) at ./<missing>:0
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
```

**Comment by aviks** [comment]
Yes, that is strange, it shouldn't do that. Will investigate.

**Comment by djsegal** [comment]
@aviks, just an fyi, julz is a framework for building and running packages. 

it might be useful to rerun the JuliaCIBot for https://github.com/JuliaLang/METADATA.jl/pull/11778 and check the results

// it was failing before because it needed this julz version

**Pull request merged**
