### PR TITLE
Pull request/a7b44ea7

### PR DESCRIPTION
**Pull request by reworkhow**

### CODE REVIEW

**Comment by reworkhow** [comment]
A tidy PR is created for two packages JWAS and XSim. The related old PR can be found [here](https://github.com/JuliaLang/METADATA.jl/pull/2493). A related paper is published [here](http://www.g3journal.org/content/early/2015/05/07/g3.115.016683.abstract).

**Comment by tkelman** [comment]
Does the updated documentation still need to be clarified further? `julia 0.3-` means you're claiming to support prerelease versions of Julia master from before 0.3.0 was released, which I doubt you're testing with.

**Comment by reworkhow** [comment]
I agree. I'll create a new pull request.

**Comment by tkelman** [comment]
For future reference, note that if you force push to the same branch you can update or replace an existing pull request.

**Pull request closed without merging**
