### PR TITLE
Tag new versions of Gallium and its dependencies

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by kshyatt** [comment]
So what I've learned here is that if I want a package developer to tag a new version, I just need them to give a JuliaCon talk?

**Comment by Keno** [comment]
Yes

**Comment by tkelman** [comment]
JuliaParser is failing its tests. https://travis-ci.org/JuliaLang/JuliaParser.jl/builds/139507218

**Comment by tkelman** [comment]
So is ASTInterpreter. https://travis-ci.org/Keno/ASTInterpreter.jl/jobs/139507170

And Gallium. https://travis-ci.org/Keno/Gallium.jl/jobs/139507210

Tagging these one at a time would give a much better chance of actually making sure they work.

**Comment by tkelman** [comment]
This actually should not have passed at all as COFF is not yet registered.

**Comment by Keno** [comment]
I'll register COFF.

**Comment by tkelman** [comment]
And fix your tests.

**Pull request merged**
