### PR TITLE
Tag Mads.jl v0.4.31

### PR DESCRIPTION
**Pull request by attobot**
Repository: [madsjulia/Mads.jl](https://github.com/madsjulia/Mads.jl)
Release: [v0.4.31](https://github.com/madsjulia/Mads.jl/releases/tag/v0.4.31)
Travis: [Travis Build Status](https://travis-ci.org/madsjulia/Mads.jl/builds/304928001)
Diff: [vs v0.4.30](https://github.com/madsjulia/Mads.jl/compare/9aff5a9b5757090ec4034d2d248293940b948a9c...eb076702c1624964f10ce9981c42bd7b81e691b5)
`requires` vs v0.4.30: no changes
cc: @montyvesselinov

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by montyvesselinov** [comment]
travis is passing:

https://travis-ci.org/madsjulia/Mads.jl

**Comment by montyvesselinov** [comment]
Tests have passed! Can you pull? Thank you!

https://travis-ci.org/madsjulia/Mads.jl

**Comment by montyvesselinov** [comment]
@tkelman I am not sure who is in charge of the pulls?

**Comment by tkelman** [comment]
you're not allowed to change the sha of an existing tag

**Comment by montyvesselinov** [comment]
what should i do? i was told to delete the old tag because it failed for
julia 0.5. should just tag a new version?

-monty

**Comment by montyvesselinov** [comment]
Please close this.

**Pull request closed without merging**
