### PR TITLE
Tag HPAT v0.0.3

### PR DESCRIPTION
**Pull request by ehsantn**

### CODE REVIEW

**Comment by tkelman** [comment]
Any idea why your tests are freezing on travis?

**Comment by ehsantn** [comment]
No idea. It works for all my machines. HPAT itself hasn't changed but the dependencies might have changed. I'll take a look.

**Comment by ehsantn** [comment]
It might be related to the C++11 std::random_device that I added in ParallelAccelerator recently.

**Comment by ehsantn** [comment]
The issue is resolved in ParallelAccelerator. It was about initialization of random number generators.

**Pull request merged**
