### PR TITLE
Tag Dynare v0.1.0.

### PR DESCRIPTION
**Pull request by stepan-a**

### CODE REVIEW

**Comment by KristofferC** [comment]
> ERROR: LoadError: LoadError: The following tags for Dynare have not been pushed to upstream repository: 0.1.0.

And it hasn't: https://github.com/DynareTeam/dynare/tags

**Comment by stepan-a** [comment]
@KristofferC But upstream is 

https://github.com/DynareTeam/Dynare.jl

and not

https://github.com/DynareTeam/dynare

My understanding was that the upstream is set in the `url` file... Am I wrong? I checked that the tags are present in 

https://github.com/DynareTeam/Dynare.jl/tags

**Comment by KristofferC** [comment]
Sorry, my mistake. Hmm, let's try again.

**Comment by KristofferC** [comment]
@tkelman Do you understand the Travis failure here? It does seem like the tag correctly exists in the repo that the url files point to.

**Comment by tkelman** [comment]
it's missing the v prefix

**Comment by KristofferC** [comment]
Thanks!

**Comment by KristofferC** [comment]
@stepan-a Could you rename the tag in the repo to include the `v` prefix?

**Comment by stepan-a** [comment]
Sorry, I was not aware of this requirement. I have just pushed the change to upstream.

**Pull request merged**
