### PR TITLE
Register EscapeString: v0.0.1

### PR DESCRIPTION
**Pull request by JockLawrie**

### CODE REVIEW

**Comment by tkelman** [comment]
missing the httpcommon dependency?

**Comment by JockLawrie** [comment]
Already exists in REQUIRE.
Added to src/EscapeString.jl.
Also simplified the code.

**Comment by tkelman** [comment]
The dependency isn't correctly reflected in the tag here, it should be listed in https://github.com/JockLawrie/METADATA.jl/blob/metadata-v2/EscapeString/versions/0.0.1/requires

**Comment by JockLawrie** [comment]
Delete this PR. Will create another.

**Pull request closed without merging**
