### PR TITLE
Tag RecipesBase.jl v0.6.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPlots/RecipesBase.jl](https://github.com/JuliaPlots/RecipesBase.jl)
Release: [v0.6.0](https://github.com/JuliaPlots/RecipesBase.jl/releases/tag/v0.6.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPlots/RecipesBase.jl/builds/421548624)
Diff: [vs v0.5.0](https://github.com/JuliaPlots/RecipesBase.jl/compare/22ee75c138b150aff06d806fbee3650fe5e26774...2f838ebf4602c024baf35a3d9f47ecf19e2517be)
`requires` vs v0.5.0: no changes
cc: @mkborregaard

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Merge together with https://github.com/JuliaLang/METADATA.jl/pull/17435 (as this will break the current release of Plots)

**Comment by andreasnoack** [comment]
Is it expected that `DimensionalPlotRecipes` breaks?

**Comment by mkborregaard** [comment]
No, let me have a look.

**Comment by mkborregaard** [comment]
@andreasnoack why do you suspect the failure of DimensionalPlotRecipes is due to this release? AFAICS that package has had failing tests for some time. And there's nothing in it that I can see that should be related to the updates I've done here. @ChrisRackauckas , what's your take?

**Comment by ChrisRackauckas** [comment]
DimensionalPlotRecipes.jl's tests are just not so compatible with CI right now. I don't see why that would block a RecipesBase.jl release.

**Comment by andreasnoack** [comment]
Please take a look at the CIBot log https://s3.ap-south-1.amazonaws.com/juliarun-ci/77338c1a3befe732b3b86650fe45df65d94cbdf1/RecipesBase_reverse_dependency_tests.html. Tests pass with the current release but fails with this release. The error is
```julia
ERROR: LoadError: type RecipeData has no field d
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
 [2] _process_userrecipes(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Array{Complex{Float64},2}}) at /home/jrun/DimensionalPlotRecipes/.julia/v1.0/Plots/src/pipeline.jl:83
 [3] macro expansion at ./logging.jl:307 [inlined]
 [4] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Array{Complex{Float64},2}}) at /home/jrun/DimensionalPlotRecipes/.julia/v1.0/Plots/src/plot.jl:171
 [5] #plot#136(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Vararg{Any,N} where N) at /home/jrun/DimensionalPlotRecipes/.julia/v1.0/Plots/src/plot.jl:57
 [6] plot(::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Array{Complex{Float64},2}) at /home/jrun/DimensionalPlotRecipes/.julia/v1.0/Plots/src/plot.jl:51
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] exec_options(::Base.JLOptions) at ./client.jl:229
 [12] _start() at ./client.jl:421
in expression starting at /home/jrun/DimensionalPlotRecipes/.julia/v1.0/DimensionalPlotRecipes/test/runtests.jl:7
```
I guess it could just be that the new version of `Plots` is needed but that was why I asked if the error was expected.

**Comment by mkborregaard** [comment]
Oh yes, that's it exactly. As I wrote above this release of RecipesBase will break the current release of Plots. One disadvantage of tagging releases in a distributed package ecosystem.

**Comment by mkborregaard** [comment]
So this should be good to merge. I should mention that Plots#master is also broken for everyone until this gets merged, because it requires a release of RecipesBase that doesn't exist.

**Pull request merged**
