### PR TITLE
Tag WriteVTK v0.2.3

### PR DESCRIPTION
**Pull request by jipolanco**

### CODE REVIEW

**Comment by tkelman** [comment]
Since this is the first tag to drop support for Julia 0.3, it should really be a new minor version, 0.3.0 of the package.

**Comment by jipolanco** [comment]
Done, I just created a separate PR with version 0.3.0 (#4019).

**Comment by tkelman** [comment]
Great, thank you. If you don't need to support pre-releases of Julia 0.4, it may be good for cleanliness' sake to drop the trailing `-` on the julia version in REQUIRE some time before the 0.3.1 tag.

**Comment by jipolanco** [comment]
RIght! I'll do that.

**Pull request closed without merging**
