### PR TITLE
Register new package GraphIO.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphs/GraphIO.jl](https://github.com/JuliaGraphs/GraphIO.jl)
Release: [v0.0.1](https://github.com/JuliaGraphs/GraphIO.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphs/GraphIO.jl/builds/223763410)
cc: @sbromberger

### CODE REVIEW

**Comment by sbromberger** [comment]
This currently only works with a specific branch of LightGraphs. Once LG v0.9.0 is tagged we will make the necessary changes here and will bump the version.

**Comment by tkelman** [comment]
Would be good to fill in the repo description to something more useful than "No description, website, or topics provided."

**Comment by sbromberger** [comment]
Oops. yes. Will do.

**Comment by tkelman** [comment]
This looks good, pretty nicely factored.

Just so I understand you correctly (and the checkout on travis), against the existing LightGraphs releases this won't work properly? Do you need this to be available and registered first before tagging a version of LightGraphs that it'll work with?

**Comment by sbromberger** [comment]
> Just so I understand you correctly (and the checkout on travis), against the existing LightGraphs releases this won't work properly?

That's right, since the current LG has this functionality included already (via overlapping methods).

> Do you need this to be available and registered first before tagging a version of LightGraphs that it'll work with?

I'd prefer it since we've removed this functionality from the branch that we plan on making LG v0.9.0. If we tag LG v0.9.0 without this then folks will have a version of LG without these graph formats available to them. The plan is to get this registered, then tag LG v0.9.0, then tag v0.1.0 of this with the proper branch in travis.yml and REQUIRE, and then ask you to merge the PRs in metadata.

**Comment by tkelman** [comment]
If this actually requires 0.9 but that just isn't available yet, it'll be more accurate to change the requires bound here once it is available. CI only changes won't need a new tag on their own.

**Comment by sbromberger** [comment]
ok, we can do that. My main goal is to get this registered so I can do full testing on what will become LG v0.9.0.

**Pull request merged**
