### PR TITLE
Tag Memento v0.1.0 [https://github.com/invenia/Memento.jl]

### PR DESCRIPTION
**Pull request by Rory-Finnegan**
Adds support for:

1. Lazy evaluation of log records cause generating stacktraces is expensive
2. Emit levels for log handlers... and arbitrary `Filter`s for loggers and handlers.
3. Benchmark tests and general performance improvements.

### CODE REVIEW

**Comment by Rory-Finnegan** [comment]
Looks like PkgDev didn't push my tag either. Should work now if someone can rerun the build.

**Comment by tkelman** [comment]
Looks like your benchmark test doesn't run by default, but it'd be a good idea to add BenchmarkTools explicitly to test/REQUIRE if it's imported directly

**Comment by Rory-Finnegan** [comment]
@tkelman Is it alright if I just update the v0.1.0 tag in the repo and push another commit to METADATA.jl which replace the reference?

**Comment by tkelman** [comment]
that's fine as long as the tag hasn't been published to metadata yet

**Comment by Rory-Finnegan** [comment]
The v0.1.0 release has been updated with @tkelman's suggestions and this should be ready to go now.

**Comment by Rory-Finnegan** [comment]
Thanks @tkelman !

**Pull request merged**
