### PR TITLE
Register SecureSessions

### PR DESCRIPTION
**Pull request by JockLawrie**

### CODE REVIEW

**Comment by kshyatt** [comment]
Hi @JockLawrie, I see you haven't tagged a version. It would be nice (although not immediately required) to do so, so that people can `Pkg.add("SecureSessions")` rather than having to `Pkg.checkout()`. Otherwise, your README and REQUIRE look nice. LGTM.

**Comment by JockLawrie** [comment]
Fixed. Tagged as v0.0.1. Thanks for the suggestion.

**Comment by kshyatt** [comment]
If you want, you can update this PR to include the tag so that it will be registered and tagged in one fell swoop.

**Comment by JockLawrie** [comment]
Sounds good.
How do I do that?
``git status`` in my local METADATA.jl doesn't show anything to update.

**Comment by kshyatt** [comment]
I think if you try `PkgDev.publish()` or `Pkg.publish()` (if you're on 0.4) it should try to open a new PR for you with both commits.

**Comment by JockLawrie** [comment]
I'm aving trouble with Pkg.publish() so I pushed it manually.
Hopefully the tag now appears.
Please let me know if not.
Thanks again,
Jock

**Comment by kshyatt** [comment]
It does! Anyone else have more feedback?

**Comment by JockLawrie** [comment]
I announced this repo on Julia Users last week but had no feedback unfortunately.
I figured just publish it anyway with a clear warning on the README, then figure out how to get some professional eyes across it.

**Comment by tkelman** [comment]
Note that your Travis CI builds are failing, any idea why? https://travis-ci.org/JockLawrie/SecureSessions.jl/builds/94517405

**Comment by JockLawrie** [comment]
Fixed.
The problem was an upgrade to a dependency, namely Requests.jl.

**Pull request merged**
