### PR TITLE
Tag LoggedDicts v0.0.2

### PR DESCRIPTION
**Pull request by JockLawrie**
Added ability to turn logging off. Handy for session management.

### CODE REVIEW

**Comment by tkelman** [comment]
why did you delete the 0.0.2 tag?

**Comment by JockLawrie** [comment]
I got confused.
I am running tests for another package that depends on this one. The tests pass using LoggedDicts master, but fail with v0.0.1. I ran `Pkg.update()` and got version 0.0.1+ (master), instead of v0.0.2. In my haste I just redid v0.0.2.

**Comment by tkelman** [comment]
Could you re-create the git tag for the sake of https://github.com/JockLawrie/LoggedDicts.jl/releases ?

**Comment by JockLawrie** [comment]
Woops. Forgot to push. Done.

**Pull request merged**
