### PR TITLE
Pull request/47293467

### PR DESCRIPTION
**Pull request by jpfairbanks**
A package for using Arbitrary Graph types for Spectral Graph Algorithms.

### CODE REVIEW

**Comment by tkelman** [comment]
Note that you'll need to tag a version before it's possible to add via `Pkg.add`. Name looks fine to me, anyone else have any feedback?

**Comment by IainNZ** [comment]
Nope, looks cool

**Comment by jpfairbanks** [comment]
@tkelman by tag a version, do you mean a regular `git tag`, or a special julia thing?

**Comment by tkelman** [comment]
`Pkg.update(); Pkg.tag("GraphMatrices"); Pkg.publish()`

If github ssh key authentication is set up and works properly then it will push a corresponding git tag to the repository which matches the special julia metadata tag.

**Comment by tkelman** [comment]
http://docs.julialang.org/en/latest/manual/packages/#tagging-and-publishing-your-package for full docs

**Comment by jpfairbanks** [comment]
@tkelman thanks I just submitted #3083 for version v0.1.0

**Pull request merged**
