### PR TITLE
Tag ImageQuilting.jl v0.5.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [juliohm/ImageQuilting.jl](https://github.com/juliohm/ImageQuilting.jl)
Release: [v0.5.3](https://github.com/juliohm/ImageQuilting.jl/releases/tag/v0.5.3)
Diff: [vs v0.5.2](https://github.com/juliohm/ImageQuilting.jl/compare/3a4af3caa3852527ccc41f486b207227edf309db...272ce68af0775c473c386ffffcaa377c90888ad5)
`requires` vs v0.5.2: 
```diff
--- 0.5.2/requires
+++ 0.5.3/requires
@@ -2,7 +2,8 @@
 Combinatorics
 StatsBase
 Primes
-Images 0.7.0
+ImageFiltering
+ImageMorphology
 LightGraphs 0.6.1
 RecipesBase
 ProgressMeter
```
cc: @juliohm

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by juliohm** [comment]
The build failed because of the dependencies, will the ImageQuilting.jl badge get red after the merge? What can be done to re-trigger the build in the JuliaCIBot?

**Comment by ararslan** [comment]
> will the ImageQuilting.jl badge get red after the merge?

Only if it fails the nightly PkgEval runs.

> What can be done to re-trigger the build in the JuliaCIBot?

Not necessary, but in general CI can be retriggered by closing and reopening a PR. (That applies to any repo with any common CI system.)

**Comment by juliohm** [comment]
I am always confused, so many bots :) So JuliaCIBot is not the bot that runs the tests for the pkg.julialang.org website?

**Comment by ararslan** [comment]
There's definitely a lot of bots, hard to keep them all straight. The one you're talking about is PkgEvaluator, a bot that runs every night that tests all registered packages and populates pkg.julialang.org. JuliaCIBot runs as a CI service on METADATA to check whether a new tag for a package breaks any packages that depend on it.

**Comment by juliohm** [comment]
Very interesting, hard to get things wrong with so many bots helping.

Do you think it is ok to merge the PR then?

**Comment by ararslan** [comment]
Yep, looks good to me. I figured I'd leave it open a little longer in case anyone else had comments on it first.

**Pull request merged**
