### PR TITLE
Register new package LazyArrays.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArrays/LazyArrays.jl](https://github.com/JuliaArrays/LazyArrays.jl)
Release: [v0.0.1](https://github.com/JuliaArrays/LazyArrays.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArrays/LazyArrays.jl/builds/415355831)
cc: @dlfivefifty

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@dlfivefifty This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Anyone know why JuliaCIBot is still pending on this?

**Comment by andreasnoack** [comment]
The CIBot isn't reliable for the time being.

**Comment by andreasnoack** [comment]
It looks like this might need a rebase. Could you please delete and reapply the tag to the same commit? That will rebase the PR.

**Comment by dlfivefifty** [comment]
It passes now.

**Pull request merged**
