### PR TITLE
Tag Mustache.jl v0.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [jverzani/Mustache.jl](https://github.com/jverzani/Mustache.jl)
Release: [v0.4.0](https://github.com/jverzani/Mustache.jl/releases/tag/v0.4.0)
Travis: [Travis Build Status](https://travis-ci.org/jverzani/Mustache.jl/builds/414980858)
Diff: [vs v0.3.3](https://github.com/jverzani/Mustache.jl/compare/35d2dfced10e0c69c85b4dc5a8237649dd3e9fd8...daa6ea9c62c4fd7541ad5a02ce087878d27242e9)
`requires` vs v0.3.3: no changes
cc: @jverzani

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like this still breaks the package on Julia 0.6

**Comment by andreasnoack** [comment]
Is this obsolete now?

**Comment by jverzani** [comment]
Yes. Sorry, I tried closing/updating through Attobot, but to no luck.
Thanks for all your help.

**Comment by andreasnoack** [comment]
No worries.

**Pull request closed without merging**
