### PR TITLE
Tag ValidatedNumerics.jl v0.6.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [dpsanders/ValidatedNumerics.jl](https://github.com/dpsanders/ValidatedNumerics.jl)
Release: [v0.6.1](https://github.com/dpsanders/ValidatedNumerics.jl/releases/tag/v0.6.1)
Travis: [Travis Build Status](https://travis-ci.org/dpsanders/ValidatedNumerics.jl/builds/198671786)
Diff: [vs v0.6.0](https://github.com/dpsanders/ValidatedNumerics.jl/compare/390c5e4bcd5e50762d30192ba7a9ec641b9b7ddc...b85d1550529839f8adb8f960d755e00f3f001dcd)
`requires` vs v0.6.0: 
```diff
--- 0.6.0/requires
+++ 0.6.1/requires
@@ -1,5 +1,5 @@
 julia 0.4
-CRlibm 0.2.2
+CRlibm 0.4
 Compat 0.7.11
 FixedSizeArrays 0.1.2
 ForwardDiff 0.2.0
```
cc: @dpsanders

### CODE REVIEW

**Comment by tkelman** [comment]
It looks like this broke IntervalLinearEquations http://pkg.julialang.org/detail/IntervalLinearEquations.html

**Comment by dpsanders** [comment]
That's why 0.6.2 was tagged reverting the change from 0.6.1.

**Comment by dpsanders** [comment]
But I'm not sure how I can catch this before releasing?

**Comment by tkelman** [comment]
we're going to try to set up some reverse dependency testing that would catch this faster than pkgeval. I would think IntervalLinearEquations should be using 0.6.2 now then?

**Comment by tkelman** [comment]
it's now using 0.6.2 and has an UndefVarError http://pkg.julialang.org/logs/IntervalLinearEquations_0.5.log

**Comment by dpsanders** [comment]
Thanks, this seems to be fixed on VN master, but for some reason this particular usage was not caught by any of our tests. Tracking as https://github.com/dpsanders/ValidatedNumerics.jl/issues/226

**Pull request merged**
