### PR TITLE
Tag SPH.jl v0.2.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [rkat/SPH.jl](https://github.com/rkat/SPH.jl)
Release: [v0.2.1](https://github.com/rkat/SPH.jl/releases/tag/v0.2.1)
Travis: [Travis Build Status](https://travis-ci.org/rkat/SPH.jl/builds/419969415)
Diff: [vs v0.0.1](https://github.com/rkat/SPH.jl/compare/eeb3a883e02c5634513c2bed108ed8fc23dc45a1...7161d1128738880b2260d0d2bee55b6fbbfff5a0)
`requires` vs v0.0.1: no changes
cc: @rkat

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Was this opened on purpose? Is it different from https://github.com/JuliaLang/METADATA.jl/pull/17234?

**Comment by rkat** [comment]
Yes. This is the Julia 0.6/0.7 release. The other request targets Julia 1.

**Comment by andreasnoack** [comment]
Please consider adding an upper bound on julia in the REQUIRE file if this doesn't work on Julia 0.7.

**Comment by rjkat** [comment]
It works on 0.7, just not 1. I incorrectly assumed 1 didn’t care about REQUIRE files.

**Pull request merged**
