### PR TITLE
Tag GeophysicalFlows.jl v0.2.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [FourierFlows/GeophysicalFlows.jl](https://github.com/FourierFlows/GeophysicalFlows.jl)
Release: [v0.2.0](https://github.com/FourierFlows/GeophysicalFlows.jl/releases/tag/v0.2.0)
Travis: [Travis Build Status](https://travis-ci.org/FourierFlows/GeophysicalFlows.jl/builds/473617409)
Diff: [vs v0.1.0](https://github.com/FourierFlows/GeophysicalFlows.jl/compare/10430774c4f6484d80baabff48f909ca5ea1da55...335fa6e42432e0c3f7a365f33b8598c6af098e5b)
`requires` vs v0.1.0: no changes
cc: @navidcy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by navidcy** [comment]
@andreasnoack: this shouldn't be merged since it's breaking
this release of GeophysicalFlows should come **after**FourierFlows v0.3.0, since it depends on it.
Can you undo this merge?

**Comment by andreasnoack** [comment]
Sorry for the mess. As announced on Discourse and Slack, CIBot testing has been disabled because of issues with the testing infrastructure. Wouldn't it be fine just to merge the FourierFlows PR?

**Comment by navidcy** [comment]
I want to retag FourierFlows and resubmit the release after I do a minor fix.
Then GeophysicalFlows would be OK with the only change that it should have minimum requirement FourierFlows v0.3.0 and not v0.2.2 as it has now. But that I can change easy right?

**Comment by andreasnoack** [comment]
Would be possible to update FourierFlows right away?

**Comment by navidcy** [comment]
Let me tag it now and I'll do the fix in a later release.

**Pull request merged**
