### PR TITLE
Register PyAMG: v0.0.1

### PR DESCRIPTION
**Pull request by cortner**
very simple wrapper around PyCall; cf. discussion in IterativeSolvers.jl, Issue #1.

There are tests for the package, but they don't pass on Travis since the package depends on having a `pyamg` installation.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I'm playing around with it. I'll see if I can get it to work.

**Comment by ChrisRackauckas** [comment]
I think you meant to reference julialang/IterativeSolvers#1

**Comment by ChrisRackauckas** [comment]
It looks like it loads scipy, numpy, and pyamg correctly. I put a pull request. The tests still fail.

**Comment by cortner** [comment]
Here are the tests on mine:
```
julia> Pkg.test("PyAMG")
INFO: Testing PyAMG
=================================================
Test 1: Julia `\` vs PyAMG Blackbox `solve` (2D) Laplacian
 \ :   0.329987 seconds (391.80 k allocations: 26.640 MB, 1.08% gc time)
PyAMG-Warmup: /Users/ortner/anaconda/lib/python2.7/site-packages/pyamg/strength.py:533: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if B == 'ones':
  1.351308 seconds (1.41 M allocations: 63.061 MB, 0.76% gc time)
PyAMG:   0.121734 seconds (219 allocations: 939.266 KB)
|x_\ - x_amg|_∞ = 1.2607345722948082e-12
|A x_amg - b|_∞ = 2.7919213607674465e-9
=================================================
Test 2: Julia `\` vs PyAMG Blackbox `solve` (3D)
 \ :   0.559407 seconds (85 allocations: 98.501 MB, 0.62% gc time)
PyAMG-Warmup:   0.693098 seconds (218 allocations: 3.221 MB)
PyAMG:   0.653033 seconds (218 allocations: 3.221 MB)
|x_\ - x_amg|_∞ = 1.9637902415325925e-12
|A x_amg - b|_∞ = 1.5542482856290007e-9
=================================================
Test 3: RugeStubenSolver (3D)
        50 x 50 x 50 grid = 125k dofs
Create solver:   3.255054 seconds (117.66 k allocations: 118.435 MB)
First solve:   2.177973 seconds (90.51 k allocations: 11.399 MB)
Second solve: (tol 1e-9)  3.561778 seconds (9.87 k allocations: 8.090 MB)
Third solve: (tol 1e-6)  2.288713 seconds (145 allocations: 7.635 MB)
|A x_amg - b|_∞ = 4.761118304941192e-6
Testing amg \ b: (PyAMG as a preconditioner)
Cost of amg \ b: (2 runs)
  0.219154 seconds (17.56 k allocations: 8.312 MB)
  0.200677 seconds (138 allocations: 7.635 MB)
INFO: PyAMG tests passed
```

**Comment by cortner** [comment]
I wonder what has gone wrong

**Comment by ChrisRackauckas** [comment]
Yeah, the tests pass on my machine.

**Comment by ChrisRackauckas** [comment]
```
5.81s$ sudo apt-get install -qq python-numpy python-scipy
Selecting previously unselected package libamd2.2.0.
(Reading database ... 124639 files and directories currently installed.)
Unpacking libamd2.2.0 (from .../libamd2.2.0_1%3a3.4.0-2ubuntu3_amd64.deb) ...
Selecting previously unselected package libumfpack5.4.0.
Unpacking libumfpack5.4.0 (from .../libumfpack5.4.0_1%3a3.4.0-2ubuntu3_amd64.deb) ...
Selecting previously unselected package python-imaging.
Unpacking python-imaging (from .../python-imaging_1.1.7-4ubuntu0.12.04.1_amd64.deb) ...
Selecting previously unselected package python-numpy.
Unpacking python-numpy (from .../python-numpy_1%3a1.6.1-6ubuntu1_amd64.deb) ...
Selecting previously unselected package python-scipy.
Unpacking python-scipy (from .../python-scipy_0.9.0+dfsg1-1ubuntu2_amd64.deb) ...
Processing triggers for man-db ...
Setting up libamd2.2.0 (1:3.4.0-2ubuntu3) ...
Setting up libumfpack5.4.0 (1:3.4.0-2ubuntu3) ...
Setting up python-imaging (1.1.7-4ubuntu0.12.04.1) ...
Setting up python-numpy (1:1.6.1-6ubuntu1) ...
Setting up python-scipy (0.9.0+dfsg1-1ubuntu2) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
```

On my machine I have scipy-0.17.1. That may be the issue. I might need to have it update since the Travis default version is pretty behind?

**Comment by ChrisRackauckas** [comment]
Check the pull request. I had to have Travis install miniconda and use that for scipy because I couldn't have it update properly. The tests now pass on Linux. I got rid of the OSX tests because I don't know how I'd do this with OSX.

**Comment by cortner** [comment]
thank you - I would have had no idea how to get this to run. Just to check: should I now close this pull-request, tag a new version and create a new METADATA pull request?

**Comment by ChrisRackauckas** [comment]
That's what I did before. I don't know if it's the best way, but it works.

**Pull request closed without merging**
