### PR TITLE
Tagging [GeometryTypes, FixedSizeArrays, FreeType] 

### PR DESCRIPTION
**Pull request by SimonDanisch**
second try of #6555

### CODE REVIEW

**Comment by tkelman** [comment]
If https://github.com/JuliaGeometry/GeometryTypes.jl/commit/60735fedc8943fa7da12786c00cea0c98ad21958 is MIT-licensed, you still need to follow the full terms of the MIT license.

**Comment by SimonDanisch** [comment]
like this: https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/src/polygons.jl ?

**Comment by tkelman** [comment]
That's better. I'd also mention it in your top-level license file, contains code ported from ...

**Comment by SimonDanisch** [comment]
Done!

**Pull request merged**
