### PR TITLE
Tag SQLite.jl v0.4.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDB/SQLite.jl](https://github.com/JuliaDB/SQLite.jl)
Release: [v0.4.3](https://github.com/JuliaDB/SQLite.jl/releases/tag/v0.4.3)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDB/SQLite.jl/builds/218728597)
Diff: [vs v0.4.2](https://github.com/JuliaDB/SQLite.jl/compare/2610faaaeea7cd92c38c29221101727445f7ab25...ba067882156ef6e44fdbc476733f6983eef8268a)
`requires` vs v0.4.2: 
```diff
--- 0.4.2/requires
+++ 0.4.3/requires
@@ -1,4 +1,4 @@
-julia 0.5
+julia 0.5 0.6
 BinDeps
 @osx Homebrew
 @windows WinRPM
@@ -6,3 +6,4 @@
 DataFrames
 WeakRefStrings 0.1.3
 LegacyStrings
+Compat 0.9.5
```
cc: @quinnj

### CODE REVIEW

**Comment by quinnj** [comment]
We'll need to cap previous SQLite requires as well, right?

**Comment by tkelman** [comment]
What's the goal with the Julia version upper bound? Are you deprecating this package?

**Comment by quinnj** [comment]
SQLite relies on Base `serialize` behavior and so it's not compatible between Julia 0.5/0.6.

**Comment by tkelman** [comment]
Would the existing/current versions work correctly if only ever used from 0.6?

**Comment by quinnj** [comment]
Yes, technically. The package tests won't work on 0.6 however, since it relies on custom 0.5 serialized values. I have a tag incoming for DataStreamsIntegrationTests that adds a 0.6 sqlite database to test from.

**Comment by tkelman** [comment]
If it's only the tests that would fail, then I don't think it's necessary to prevent installation of the existing versions on 0.6? That would also prevent installation of any dependent package, at least until a version that does allow 0.6 gets tagged.

**Comment by quinnj** [comment]
I'm following. Got a new tag incoming, thanks for helping me walk thru this.

**Pull request closed without merging**
