### PR TITLE
Tag Bio v0.4.2 [https://github.com/BioJulia/Bio.jl]

### PR DESCRIPTION
**Pull request by bicycle1885**
* Bug fix
* Require Julia 0.5 (not a development version)

### CODE REVIEW

**Comment by tkelman** [comment]
You seem to have hit a bug in the tag-checking code. I think @ararslan saw it and hopefully has some ideas for a fix. It's supposed to only be checking the tags that a PR is changing.

**Comment by bicycle1885** [comment]
So, should I remove the erroneous tag (0.3.0 was tagged by mistake), or keep it for reproducibility of the bug?

**Comment by tkelman** [comment]
Bug fixed, all is good!

**Comment by ararslan** [comment]
Thanks for your patience, Kenta! I apologize for the inconvenience.

**Comment by bicycle1885** [comment]
Never mind. Thank you for merging.

**Pull request merged**
