### PR TITLE
Tag ReadWriteDlm2.jl v0.6.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [strickek/ReadWriteDlm2.jl](https://github.com/strickek/ReadWriteDlm2.jl)
Release: [v0.6.2](https://github.com/strickek/ReadWriteDlm2.jl/releases/tag/v0.6.2)
Travis: [Travis Build Status](https://travis-ci.org/strickek/ReadWriteDlm2.jl/builds/304986307)
Diff: [vs v0.6.1](https://github.com/strickek/ReadWriteDlm2.jl/compare/f8987beac02d6429b8fd3042dc63cd0d39892233...1f452542ca21298cce31b213eed951c00a827b85)
`requires` vs v0.6.1: no changes
cc: @strickek

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Test failure `METADATA/ReadWriteDlm2/versions/0.6.2/requires: prerelease 0.6.0-pre not allowed (>= 0.6.0 needed)`

**Comment by strickek** [comment]
Have sent a new tag v0.6.3 with changed requires to 0.6.0

**Comment by strickek** [comment]
I need some help: I have deleted v0.6.2  of ReadDlm2 and released v0.6.3 but attobot do not create a new pull request.

**Comment by strickek** [comment]
Should be ok now.

**Pull request merged**
