### PR TITLE
Tag WCS v0.1.2

### PR DESCRIPTION
**Pull request by kbarbary**

### CODE REVIEW

**Comment by tkelman** [comment]
can you push the git tag so it shows up under https://github.com/JuliaAstro/WCS.jl/releases ?

**Comment by kbarbary** [comment]
Done. (I usually wait to push the tag, in case there is a problem with the METADATA PR...)

**Comment by tkelman** [comment]
Oh okay. As a note, these WCS packages almost always time out on PackageEvaluator due to the flaky ftp download. Could we set up a more reliable mirror for them?

**Comment by kbarbary** [comment]
Recommendations? cache.julialang.org? Add tarball to releases on WCS.jl repo?

**Comment by tkelman** [comment]
Yeah we can add it to the whitelist here https://github.com/staticfloat/cache.julialang.org/blob/master/cache.py - though I'm not positive whether that will work perfectly with ftp, may need to try and see.

**Pull request merged**
