### PR TITLE
Tag StaticArrays.jl v0.7.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArrays/StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl)
Release: [v0.7.1](https://github.com/JuliaArrays/StaticArrays.jl/releases/tag/v0.7.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaArrays/StaticArrays.jl/builds/382427659)
Diff: [vs v0.7.0](https://github.com/JuliaArrays/StaticArrays.jl/compare/b454bc9131333da153f49182c7829c385fb2a6f5...96bf39c4b723538f2f92e6ad34ce075623e9e9fb)
`requires` vs v0.7.0: 
```diff
--- 0.7.0/requires
+++ 0.7.1/requires
@@ -1,2 +1,2 @@
 julia 0.6.0
-Compat 0.46
+Compat 0.59
```
cc: @andyferris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Looks like tests are not passing and that it breaks some packages.

**Comment by martinholters** [comment]
Three packages (including StaticArrays itself) change from pass to fail on JuliaCIBot:
* NeighbourLists: `ERROR: GitError(Code:ERROR, Class:Net, curl error: Could not resolve host: github.com)` - unrelated
* SMCExamples: no log available
* StaticArrays: no log available

What does it mean if the log is unavailable? A timeout?

**Comment by andreasnoack** [comment]
cc @nkottary

**Comment by andyferris** [comment]
Hmm... I haven't had much interaction with JuliaCIBot before.

Tests were passing for me, so if they are failing somewhere it would sure be nice to know what's broken :)

As a general rule, I'd guess that if the CIBot results are flakey then we can't justify using the results to hold up tagging a package.

**Comment by nkottary** [comment]
The CIBot has DNS errors sometimes, so it is unable to connect to github.com or upload the logs. I will check with our cloud provider to see what we can do about this.

**Comment by martinholters** [comment]
Closing and re-opening to re-trigger so we can check again...

**Comment by martinholters** [comment]
Ok, so from the second JuliaCIBot run:
* NeighbourLists and StaticArrays now pass.
* SMCExamples wasn't run again.
* ImageFiltering fails and looks related:
```
  MethodError: no method matching getindex(::ColorTypes.Gray{Float64})
  Stacktrace:
   [1] macro expansion at /home/jrun/ImageFiltering/.julia/v0.6/StaticArrays/src/broadcast.jl:178 [inlined]
   [2] _broadcast at /home/jrun/ImageFiltering/.julia/v0.6/StaticArrays/src/broadcast.jl:139 [inlined]
   [3] broadcast_c at /home/jrun/ImageFiltering/.julia/v0.6/StaticArrays/src/broadcast.jl:37 [inlined]
   [4] broadcast at ./broadcast.jl:455 [inlined]
...
```
(http://juliarun-ci.s3.amazonaws.com/6aa057c0ed7abcd623b5ad30e367749b8b6b9ba7/ImageFiltering_with_pull_request_of_StaticArrays_on_julia_0_6.log)

@andyferris can you take a look at the ImageFiltering issue?

**Comment by andyferris** [comment]
I'm not too familiar with that code... I have had a quick look but have more questions than answers so far.

At some point there was a `broadcastable` function that would have made `Gray` into something that we can `getindex` (like a `Ref`). The current `StaticArrays` possibly assumes this (incorrectly?), or perhaps this isn't done right with `Gray`? I'll have to dig in some more. (I'll ping @timholy @mbauman @tkoolen in case they can share any insight?)

**Comment by andreasnoack** [comment]
The easier solution is too upper bounds here and let the package maintainers deal with updating the package when they have time.

**Comment by tkoolen** [comment]
I think this is the culprit: https://github.com/JuliaArrays/StaticArrays.jl/commit/ee7766c1931225552e986acb3bea506ae5d66170, part of https://github.com/JuliaArrays/StaticArrays.jl/pull/393.

**Comment by andyferris** [comment]
Yay! Thanks everyone. I can officially declare that this is our best release *ever*. :slightly_smiling_face:

**Pull request merged**
