### PR TITLE
Register Extern v0.0.1, tag StatsBase v0.8.3

### PR DESCRIPTION
**Pull request by ararslan**
I *finally* got `Pkg.publish()` to work! 🎉 However, it doesn't seem to care that I already have an outstanding PR for Extern (#5563) so I'll close that one in favor of this.

### CODE REVIEW

**Comment by tkelman** [comment]
Better if you could separate the PR's into independent branches.

**Comment by ararslan** [comment]
Not sure how to do that with `Pkg.publish()`. Is that something that I'd have to do manually instead?

**Comment by tkelman** [comment]
Either a rebase, or cherry-pick just the StatsBase commit into a new branch

**Comment by ararslan** [comment]
Okay, separated into #5563 (reopened) and #5570. It took some super serious googling.

**Pull request closed without merging**
