### PR TITLE
Tag DiffEqDevTools.jl v0.7.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DiffEqDevTools.jl](https://github.com/JuliaDiffEq/DiffEqDevTools.jl)
Release: [v0.7.0](https://github.com/JuliaDiffEq/DiffEqDevTools.jl/releases/tag/v0.7.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/DiffEqDevTools.jl/builds/221422834)
Diff: [vs v0.6.0](https://github.com/JuliaDiffEq/DiffEqDevTools.jl/compare/b7de7b660e531e43ed7b43b5e7dd935518e91717...24adfbc9417277970e337db8767907afb7513cca)
`requires` vs v0.6.0: 
```diff
--- 0.6.0/requires
+++ 0.7.0/requires
@@ -1,5 +1,5 @@
 julia 0.5
 RecipesBase 0.1.0
-DiffEqBase 0.5.0 0.15.0
+DiffEqBase 0.15.0
 RecursiveArrayTools 0.1.2
 DiffEqPDEBase
```
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/8769#issuecomment-293639490

**Comment by ChrisRackauckas** [comment]
Travis needs to be restarted here so it can find DiffEqBase v0.15.0. But its own tests will fail until other changes go through. Ignore for now.

**Comment by ChrisRackauckas** [comment]
I might've said that in an unclear way: ignore the tests for now since the tests here since this is the testing tools package, and uses the solvers to test the testing tools, which themselves need an update. So for now, ignore the tests on this, re-run the METADATA Travis so that way this can get through. 

Then, once this and https://github.com/JuliaLang/METADATA.jl/pull/8803 are through, all of the Base and testing suite is updated. This means that the rest of the packages will have proper tests pass before merging.

**Comment by tkelman** [comment]
Been restarted several times, the metadata travis check is still failing.

**Comment by ChrisRackauckas** [comment]
ParameterizedFunctions.jl is only a test dependency (and that's through DiffEqProblemLibrary). It should be able to satisfy all of its dependencies, but not its test dependencies.

**Pull request merged**
