### PR TITLE
Tag LibGEOS v0.0.4

### PR DESCRIPTION
**Pull request by OmriRoames**

### CODE REVIEW

**Comment by tkelman** [comment]
please push the git tag to the package so it shows up at https://github.com/JuliaGeo/LibGEOS.jl/releases

**Comment by yeesian** [comment]
@tkelman he doesn't yet have commit access to the repo. This was upon my request at https://github.com/JuliaGeo/GeoInterface.jl/issues/5#issuecomment-215276164

**Comment by tkelman** [comment]
@yeesian can you push the git tag then? It's cleanest if people with commit access do these.

**Comment by yeesian** [comment]
Done!

**Pull request merged**
