### PR TITLE
Register new package FixedPointDecimals.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaMath/FixedPointDecimals.jl](https://github.com/JuliaMath/FixedPointDecimals.jl)
Release: [v0.0.1](https://github.com/JuliaMath/FixedPointDecimals.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaMath/FixedPointDecimals.jl/builds/233373316)
cc: @omus

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

@omus This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by tkelman** [comment]
A package description and a minimal readme or docs would be good to add.

**Comment by omus** [comment]
I was planning on doing that next. This release is mostly so that the FixedPointDecimals can be removed from Currencies.jl. Would you prefer there be a minimal README before we do the initial tag?

**Comment by tkelman** [comment]
It doesn't have to be included in the tagged sha, but would be good to have something people can see, around the time it's published tomorrow

**Comment by omus** [comment]
Added a simple [README](https://github.com/JuliaMath/FixedPointDecimals.jl/blob/master/README.md) to master.

**Comment by tkelman** [comment]
and something in the "No description, website, or topics provided." for pkg.julialang.org

**Comment by omus** [comment]
Added repo description

**Pull request merged**
