### PR TITLE
Register new package Holidays.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [joshbode/Holidays.jl](https://github.com/joshbode/Holidays.jl)
Release: [v0.0.1](https://github.com/joshbode/Holidays.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/joshbode/Holidays.jl/builds/267066305)
cc: @joshbode

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@joshbode This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by ararslan** [comment]
Neat package! It would be to add tests though; currently it just has `@test 1 == 1`.

**Comment by joshbode** [comment]
:flushed: Hold off on this one - I can surely come up with some better tests than that :)

**Comment by aviks** [comment]
@joshbode Have you seen https://github.com/felipenoris/BusinessDays.jl ? Any chance you could merge your effort with that?

**Comment by MikeInnes** [comment]
Closing this as we haven't heard from you in a while. Do let me know if you want to re-open.

**Pull request closed without merging**
