### PR TITLE
Pull request/6316d280

### PR DESCRIPTION
**Pull request by trappmartin**

### CODE REVIEW

**Comment by trappmartin** [comment]
Hi there,
his package provides basic implementations of the Hilbert-Schmidt Independence Criterion.

Thanks!

**Comment by tkelman** [comment]
Is this a very widely-known acronym? Would spelling it out with a longer package name make it more discoverable for potential users to see what the package does?

**Comment by trappmartin** [comment]
Yes, HSIC is a known acronym for the Hilbert-Schmidt Independence Criterion.

**Comment by tkelman** [comment]
Looks like the package was moved to https://github.com/OFAI/BayesianNonparametrics.jl? That sounds like a clearer name to me! Should this PR be closed or repurposed then?

**Comment by tkelman** [comment]
My mistake, I was looking at a different repo (https://github.com/trappmartin/BNP.jl). Ignore the previous comment. I guess you decided against renaming HSIC?

**Comment by trappmartin** [comment]
Nope, I'll rename the package in the next week. Just couldn't find the time so far.

**Comment by trappmartin** [comment]
Closed for renaming in future..

**Pull request closed without merging**
