### PR TITLE
Tag LazySets.jl v1.4.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaReach/LazySets.jl](https://github.com/JuliaReach/LazySets.jl)
Release: [v1.4.0](https://github.com/JuliaReach/LazySets.jl/releases/tag/v1.4.0)
Diff: [vs v1.3.0](https://github.com/JuliaReach/LazySets.jl/compare/53b2e096d79f9840d94c05078d397b5299bac5e7...67426ec1375627f7c2e28d9767301383b67173ba)
`requires` vs v1.3.0: 
```diff
--- 1.3.0/requires
+++ 1.4.0/requires
@@ -1,13 +1,10 @@
 julia 0.6
-IterTools 0.2.1
-RecipesBase 0.3.1
-Plots 0.17.4
-GR 0.31.0
-Expokit 0.0.1
-MathProgBase 0.7.1
-GLPKMathProgInterface 0.4.2
-Requires 0.4.4
-Polyhedra 0.3.4
-CDDLib 0.3.2
-IntervalArithmetic 0.14.0
-Compat 1.0.0
+Compat 1.0
+Expokit 0.1
+GLPKMathProgInterface 0.4
+GR 0.32
+IntervalArithmetic 0.14
+MathProgBase 0.7
+Plots 0.17
+RecipesBase 0.3
+Requires 0.4
```
cc: @schillic

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by schillic** [comment]
[Our Travis tests](https://travis-ci.org/JuliaReach/LazySets.jl/builds/419700117) pass for v0.7 :confused:

**Comment by schillic** [comment]
The error message is:
`ERROR: LoadError: ArgumentError: Package RecipesBase [3cdcf5f2-1ef4-517c-9805-6587b60abb01] is required but does not seem to be installed:`
``- Run `Pkg.instantiate()` to install all recorded dependencies.``

However, a few lines above:
`[ Info: Installing RecipesBase v0.5.0`

**Comment by schillic** [comment]
A similar problem occurs in https://github.com/JuliaLang/METADATA.jl/pull/17233. It was suggested to remove the `Project.toml` file again. Does the same apply here?

**Comment by andreasnoack** [comment]
Yes. It's because of one or more Project.toml files. We can merge here anyway but it is a shame not to have the reverse dependency testing working.

**Comment by schillic** [comment]
Okay, thanks! We will remove the file for the next release then.

**Pull request merged**
