### PR TITLE
Upper bound Julia version for past ACME versions

### PR DESCRIPTION
**Pull request by martinholters**
ACME 0.1.0 and 0.1.1 were broken by JuliaLang/julia#19595

### CODE REVIEW

**Comment by tkelman** [comment]
Will you have a new version that works soonish, or should this package not be installable at all on nightly?

**Comment by martinholters** [comment]
I already have; you might have missed that some @tkelman merged #7461 :smile:

**Comment by tkelman** [comment]
Ah whoops. They weren't visible at https://github.com/martinholters/METADATA.jl/tree/2ed38f25de7671ea4042905a16690a0237558f53/ACME/versions, this branch must have been created from a parent commit before that.

**Comment by martinholters** [comment]
You're right, and that actually confused me, too, for a second :smile:

**Pull request merged**
