### PR TITLE
Register new package Knockout.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGizmos/Knockout.jl](https://github.com/JuliaGizmos/Knockout.jl)
Release: [v0.1.0](https://github.com/JuliaGizmos/Knockout.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGizmos/Knockout.jl/builds/395573323)
cc: @piever

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@piever This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by piever** [comment]
Not sure what's going on with JuliaCIBot as the tests are passing on Travis.

**Comment by andreasnoack** [comment]
CIBot can't yet handle `xvfb-run`

**Comment by piever** [comment]
I see, can this be merged as is even if CIBot doesn't pass?

**Comment by andreasnoack** [comment]
Yes, but we often let registration PRs stay open for three days (despite the message in the top post)

**Pull request merged**
