### PR TITLE
Register new package ClassImbalance.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [bcbi/ClassImbalance.jl](https://github.com/bcbi/ClassImbalance.jl)
Release: [v0.1.0](https://github.com/bcbi/ClassImbalance.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/bcbi/ClassImbalance.jl/builds/341469276)
cc: @paulstey

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@paulstey This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Tests fail because of missing R package "DMwR". Would it be possible to install the package as part of the test script?

**Comment by dilumaluthge** [comment]
@andreasnoack This is now fixed in master. Do we need to tag a new release?

**Comment by andreasnoack** [comment]
The easiest solution would be to remove and add the tag at https://github.com/bcbi/ClassImbalance.jl/releases. That should automatically update this PR.

**Comment by andreasnoack** [comment]
It looks like the issue is still there. See http://juliarun-ci.s3.amazonaws.com/b1d97c1bc31dd662577005839cf34de0b34724ef/ClassImbalance_julia_0_6.log

**Comment by dilumaluthge** [comment]
Hmmmm... I think I may know what's happening. I'll see if I can get it to work.

**Comment by dilumaluthge** [comment]
Whew okay looks like CI passes now.

**Pull request merged**
