### PR TITLE
Tag FreeTypeAbstraction.jl v0.4.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaGraphics/FreeTypeAbstraction.jl](https://github.com/JuliaGraphics/FreeTypeAbstraction.jl)
Release: [v0.4.1](https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/releases/tag/v0.4.1)
Travis: [Travis Build Status](https://travis-ci.org/JuliaGraphics/FreeTypeAbstraction.jl/builds/419058422)
Diff: [vs v0.4.0](https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/compare/1853af310b961c5113e80a0a414ed514c7236f6e...1963dc6d24bfe9bb59b390336b3f11206f7b7249)
`requires` vs v0.4.0: no changes
cc: @SimonDanisch

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
There are still a zillion deprecation warnings left on 0.7 which causes it to fail on on 1.0. Do you really want to release this before fixing it?

**Comment by SimonDanisch** [comment]
ok, without FreeType tagged, this will still not depwarn free - freetype sadly relies on FreeTypeAbstraction to get some cheap test coverage - so until FreeTypeAbstraction is tagged, FreeType tests won't pass on 1.0.

**Comment by andreasnoack** [comment]
This is probably a situation where joint tagging makes sense but let's just merge for now such that you can make progress.

**Comment by SimonDanisch** [comment]
thanks @andreasnoack  :) We'll need to figure out something smarter for the future! sadly, no one really has time for those packages :(

**Pull request merged**
