### PR TITLE
Tag DynamicalSystemsBase.jl v0.11.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDynamics/DynamicalSystemsBase.jl](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl)
Release: [v0.11.0](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/releases/tag/v0.11.0)
Diff: [vs v0.10.3](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/compare/afb83cd7ac335b8fbca4a070c0f01b66fa7d6412...259bc6013000898c013155fa1dc86ec9d6a36c6b)
`requires` vs v0.10.3: 
```diff
--- 0.10.3/requires
+++ 0.11.0/requires
@@ -1,10 +1,7 @@
-julia 0.6
-OrdinaryDiffEq 3.1
-DiffEqBase 3.5
-ForwardDiff 0.5
-Requires 0.4.3
-StaticArrays 0.5.0
-StatsBase 0.8.2
-IterTools
-NearestNeighbors
-LsqFit 0.3.0
+julia 0.7.0-beta2
+StaticArrays 0.8
+Distances 0.7
+NearestNeighbors 0.4
+DiffEqBase 4.10
+OrdinaryDiffEq 4.5
+ForwardDiff 0.8
```
cc: @Datseris

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by quinnj** [comment]
@aviks @ranjanan, why does JuliaCIBot run the 0.6 tests when the new REQUIRES is 0.7 only?

**Comment by aviks** [comment]
It's only run the 0.6 tests for the old version, you'll see, since that allows 0.6. For the new version, only the 0.7 tests are run.

**Comment by Datseris** [comment]
The tests failed instantly, but I don't understand why.... I've seen the log and still can't understand. The Travis tests pass. Could I have some help finding the problem?

**Comment by aviks** [comment]
As we discussed on Slack this morning, the tests are failing since it cannot find `StaticArrays`. Which is strange, since it exists in your REQUIRE. This could be an artifact of the tests, but I don't know why. 

@Datseris I'll merge if you are confident this pacakge works. It may be worth testing adding  this package in a clean environment.

**Comment by Datseris** [comment]
> It may be worth testing adding this package in a clean environment.

I am on it now!

**Comment by Datseris** [comment]
```
julia> cd()

julia> mkpath("DynBasetest")
"DynBasetest"

julia> cd("DynBasetest")

(v0.7) pkg> activate .

(DynBasetest) pkg> add DynamicalSystemsBase#master
  Updating registry at `C:\Users\datseris\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `https://github.com/JuliaDynamics/DynamicalSystemsBase.jl.git`
  Updating git-repo `https://github.com/JuliaDynamics/DynamicalSystemsBase.jl.git`
┌ Warning: package DynamicalSystemsBase at C:\Users\datseris\AppData\Local\Temp\jl_535D.tmp will need to have a [Julia]Project.toml file in the future
└ @ Pkg.Types C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Types.jl:619
 Resolving package versions...
  Updating `Project.toml`
  [6e36e845] + DynamicalSystemsBase v0.10.3+ #master (https://github.com/JuliaDynamics/DynamicalSystemsBase.jl.git)
  Updating `Manifest.toml`
  [9e28174c] + BinDeps v0.8.8
  [b99e7846] + BinaryProvider v0.3.3
  [49dc2e85] + Calculus v0.4.0
  [bbf7d656] + CommonSubexpressions v0.2.0
  [34da2185] + Compat v1.0.0
  [864edb3b] + DataStructures v0.10.0
  [c5cfe0b6] + DiffBase v0.3.2
  [2b5f629d] + DiffEqBase v4.18.0
  [01453d9d] + DiffEqDiffTools v0.6.0
  [163ba53b] + DiffResults v0.0.3
  [b552c78f] + DiffRules v0.0.6
  [b4f34e82] + Distances v0.7.1
  [6e36e845] + DynamicalSystemsBase v0.10.3+ #master (https://github.com/JuliaDynamics/DynamicalSystemsBase.jl.git)
  [f6369f11] + ForwardDiff v0.8.0
  [01680d73] + GenericSVD v0.2.0
  [82899510] + IteratorInterfaceExtensions v0.1.0
  [d3d80556] + LineSearches v7.0.0
  [1914dd2f] + MacroTools v0.4.2
  [e1d29d7a] + Missings v0.2.10
  [46d2c3a1] + MuladdMacro v0.2.1
  [d41bc354] + NLSolversBase v7.0.3
  [2774e3e8] + NLsolve v2.0.1
  [77ba4419] + NaNMath v0.3.1
  [b8a86587] + NearestNeighbors v0.4.0
  [1dea7af3] + OrdinaryDiffEq v4.6.0
  [d96e819e] + Parameters v0.9.1
  [3cdcf5f2] + RecipesBase v0.4.0
  [731186ca] + RecursiveArrayTools v0.17.0
  [189a3867] + Reexport v0.1.0
  [ae029012] + Requires v0.5.2
  [f2b01f46] + Roots v0.6.0
  [276daf66] + SpecialFunctions v0.6.0
  [90137ffa] + StaticArrays v0.8.2
  [3783bdb8] + TableTraits v0.3.0
  [a2a6695c] + TreeViews v0.3.0
  [30578b45] + URIParser v0.3.1
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode

(DynBasetest) pkg> test DynamicalSystemsBase
   Testing DynamicalSystemsBase

Testing dynamical systems...
Test Summary: | Pass  Total
combination 1 |    9      9
Test Summary: | Pass  Total
combination 2 |    9      9
Test Summary: | Pass  Total
combination 3 |    8      8
Test Summary: | Pass  Total
combination 4 |    8      8
Test Summary: | Pass  Total
combination 5 |    9      9
Test Summary: | Pass  Total
combination 6 |    9      9
Test Summary: | Pass  Total
combination 7 |    9      9
Test Summary: | Pass  Total
combination 8 |    9      9

Testing tangent dynamics...
Test Summary: | Pass  Total
combination 1 |    1      1
Test Summary: | Pass  Total
combination 2 |    1      1
Test Summary: | Pass  Total
combination 3 |    1      1
Test Summary: | Pass  Total
combination 4 |    1      1
Test Summary: | Pass  Total
combination 5 |    1      1
Test Summary: | Pass  Total
combination 6 |    1      1
Test Summary: | Pass  Total
combination 7 |    1      1
Test Summary: | Pass  Total
combination 8 |    1      1

Testing inference...
Test Summary: | Pass  Total
Inference     |   20     20

Testing continuous system evolution...
Test Summary: | Pass  Total
Lorenz System |    4      4
Test Summary: | Pass  Total
Lorenz96      |    4      4
Test Summary:     | Pass  Total
Gissinger Columns |    3      3

Testing discrete system evolution...
Test Summary: | Pass  Total
Logistic Map  |    5      5
Test Summary: | Pass  Total
Henon map     |    5      5
Test Summary:         | Pass  Total
Coupled standard maps |    2      2

Testing Dataset...
Test Summary: | Pass  Total
Dataset       |   13     13

Testing reconstruct
Test Summary: | Pass  Total
reconstruct   |   47     47

Test took total time of:
255.424 seconds or 4.257 minutes
   Testing DynamicalSystemsBase tests passed
```
tests just passed on a fully clean environment.

**Comment by aviks** [comment]
@nkottary @KristofferC We should probably investigate why CIBot does not like this?

**Pull request merged**
