### PR TITLE
Register new package Figures.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [EricForgy/Figures.jl](https://github.com/EricForgy/Figures.jl)
Release: [v0.0.1](https://github.com/EricForgy/Figures.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/EricForgy/Figures.jl/builds/474401083)
cc: @EricForgy

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@EricForgy This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by EricForgy** [comment]
This test is failing due to waiting for https://github.com/JuliaLang/METADATA.jl/pull/20289 (pending more than 5 hours so far 😅)

Edit: Oops. Looking at the travis details, that seems to not be the case 🤔 It is about requiring `Test` 🤔

**Comment by EricForgy** [comment]
PS: The last commit ☝️ incorporates some feedback.

https://github.com/EricForgy/Figures.jl/releases/tag/v0.0.1

**Comment by dpsanders** [comment]
The package name seems too generic. Maybe you could make it more specific?

**Comment by EricForgy** [comment]
Hi @dpsanders,

Thanks for the feedback 👍 

I like the name "Figures" and the name was chosen intentionally. There is literally one purpose for Figures.jl, to make figures 😊 

The name is not so generic that it encompasses different fields of study rendering its meaning ambiguous. I understand the sentiment, but prefer to keep the name Figures if possible 😊🙏 

PS: Note, we had a similar discussion about my other package: Pages.jl 😊 The conclusion was that as long as the name is not misleading or anything sinister, package authors should be able to name packages however they like. I hope that is still the case 🙏

**Comment by tpapp** [comment]
Eg BrowserFigures.jl would be a more descriptive name.

**Comment by EricForgy** [comment]
Figures.jl is not limited to browsers, e.g. it was designed with VS Code in mind. 

I probably will not change the name, so it either gets merged or denied. Being denied my chosen name would suck and I'd probably wonder if I want to be part of this community anymore.

Feedback is noted though.

**Comment by tpapp** [comment]
> Being denied my chosen name would suck and I'd probably wonder if I want to be part of this community anymore.

Please kindly note that giving packages descriptive names benefits others in the Julia language community, which is why there are [guidelines](https://julialang.github.io/Pkg.jl/dev/creating-packages/#Package-naming-guidelines-1) in place to help with naming.

**Comment by EricForgy** [comment]
Noted.

**Comment by andreasnoack** [comment]
> so it either gets merged or denied

We don't deny names. At least I'm not aware of any cases. (Though, I guess it would happen if a name [in English] was considered a violation of the CoC.) We point our potential issues and propose alternatives. The only thing we require is that people reply that they want to keep the current name and you've already done that.

**Comment by EricForgy** [comment]
Thank you 🙏

**Pull request merged**
