### PR TITLE
Register new package Barycentric.jl v0.1.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [dawbarton/Barycentric.jl](https://github.com/dawbarton/Barycentric.jl)
Release: [v0.1.1](https://github.com/dawbarton/Barycentric.jl/releases/tag/v0.1.1)
cc: @dawbarton

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@dawbarton This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
I suggest the name BarycentricInterpolation.jl

**Comment by andreasnoack** [comment]
I think `Barycentric` can work. @dawbarton Is that your preferred name?

**Comment by dpsanders** [comment]
There are too many "barycentric" things for that in my opinion:

https://en.m.wikipedia.org/wiki/Barycentric

**Comment by dawbarton** [comment]
On reflection I have to agree with @dpsanders that barycentric is quite ambiguous, I just didn't have time to alter it over the weekend. I'll change it to BarycentricInterpolation.jl and resubmit when I get a few more minutes.

**Pull request closed without merging**
