### PR TITLE
Tag ApproxFun v0.2.0

### PR DESCRIPTION
**Pull request by dlfivefifty**
Includes many substantial changes, including fractional differential operators and partial 0.5 support.

### CODE REVIEW

**Comment by tkelman** [comment]
It looks like this broke SingularIntegralEquations, cc @MikaelSlevinsky - http://pkg.julialang.org/detail/SingularIntegralEquations.html

Best to add upper bounds to all past tagged versions of that (and any other) dependent packages that this broke.

**Comment by dlfivefifty** [comment]
I tag is in the works, should be done in the next couple weeks or so.

**Comment by dlfivefifty** [comment]
#5526

**Comment by tkelman** [comment]
Adding a new tag makes the latest version of the package work, but all old versions of the packages are broken because they were not accurately upper-bounding their dependencies. You should retroactively add an upper bound on the past tags of SingularIntegralEquations' dependency on ApproxFun in METADATA as well.

**Comment by dlfivefifty** [comment]
I don't know how to do that.

**Comment by tkelman** [comment]
Under the existing tags at https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/SingularIntegralEquations/versions, modify the `requires` files to add an upper bound of `0.2` after the existing lower bound on the ApproxFun dependencies. The upper bound is exclusive.

**Comment by dlfivefifty** [comment]
how do you add an upper bound?

**Comment by tkelman** [comment]
Just a second number, e.g. `ApproxFun 0.0.7 0.2`

**Pull request merged**
