### PR TITLE
Register new package ORCA.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [sglyon/ORCA.jl](https://github.com/sglyon/ORCA.jl)
Release: [v0.1.0](https://github.com/sglyon/ORCA.jl/releases/tag/v0.1.0)
cc: @sglyon

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@sglyon This PR will remain open for three days for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by andreasnoack** [comment]
CIBot fails because of the project file so it would be great if you could delete it since it isn't needed yet and it would make it much easier for us to verify that the package works.

**Comment by sglyon** [comment]
Done

**Comment by sglyon** [comment]
So when I removed the Project file, my CI testing broke. https://travis-ci.org/sglyon/ORCA.jl/builds/424131718

Any suggestions?

**Comment by andreasnoack** [comment]
Might just be a missing `close`. See https://docs.travis-ci.com/user/languages/julia/#default-build-and-test-script

**Comment by andreasnoack** [comment]
I'll merge since tests on Travis pass (but please enable testing on Julia 1.0 as well). Though, it would be good to figure out why CIBot fails with
```
Error During Test at /home/jrun/.julia/v1.0/ORCA/test/runtests.jl:11
  Test threw exception
  Expression: myplot(tempname() * "." * ext) === nothing
  IOError: connect: connection refused (ECONNREFUSED)
  Stacktrace:
   [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
   [2] wait() at ./event.jl:255
   [3] wait(::Condition) at ./event.jl:46
   [4] stream_wait(::Sockets.TCPSocket, ::Condition) at ./stream.jl:47
   [5] wait_connected(::Sockets.TCPSocket) at ./stream.jl:263
   [6] connect at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Sockets/src/Sockets.jl:444 [inlined]
   [7] connect(::Sockets.IPv4, ::UInt64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Sockets/src/Sockets.jl:428
   [8] #getconnection#14(::Bool, ::Int64, ::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol,Symbol},NamedTuple{(:require_ssl_verification, :iofunction, :status_exception),Tuple{Bool,Nothing,Bool}}}, ::Function, ::Type{Sockets.TCPSocket}, ::SubString{String}, ::SubString{String}) at /home/jrun/.julia/v1.0/HTTP/src/ConnectionPool.jl:548
```

**Pull request merged**
