### PR TITLE
Register Lisp: v0.1.0

### PR DESCRIPTION
**Pull request by swadey**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Gerry Sussman will be very pleased.

**Comment by swadey** [comment]
lol

**Comment by StefanKarpinski** [comment]
His main comment on @JeffBezanson's defense was "this is great, but can I have it with Lisp syntax?"

**Comment by swadey** [comment]
that's what unholy macros like this are for...

But seriously, despite its elegance, I can't imagine wanting to do math with lisp syntax.

**Comment by JeffBezanson** [comment]
Nice!

I know I'm way late here but I would reconsider the name of this package. Perhaps something like `LispSyntax` or `SExpressions`.

**Comment by swadey** [comment]
Makes sense.  Will do.

**Pull request merged**
