### PR TITLE
Put upper limit on Optim

### PR DESCRIPTION
**Pull request by pkofod**
xref to fix in DSGE.jl: https://github.com/FRBNY-DSGE/DSGE.jl/pull/6
xref to discussion #5957

### CODE REVIEW

**Comment by tkelman** [comment]
Does 0.1.2 not have the same problem?

**Comment by pkofod** [comment]
Thank you, yes it does. I re-pushed.

**Comment by tkelman** [comment]
Good thing it was an easy fix, thanks for this!

**Comment by pkofod** [comment]
> Good thing it was an easy fix, thanks for this!

Yeah, sorry for the noise.

**Pull request merged**
