### PR TITLE
Tag Optim.jl v0.9.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaNLSolvers/Optim.jl](https://github.com/JuliaNLSolvers/Optim.jl)
Release: [v0.9.0](https://github.com/JuliaNLSolvers/Optim.jl/releases/tag/v0.9.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaNLSolvers/Optim.jl/builds/237492191)
Diff: [vs v0.7.8](https://github.com/JuliaNLSolvers/Optim.jl/compare/250b50ab5f9bb87576c623fa20fdafb981ce40a1...4f3dade6d0e2c4e175784f5765b676a7197001f0)
`requires` vs v0.7.8: 
```diff
--- 0.7.8/requires
+++ 0.9.0/requires
@@ -1,6 +1,7 @@
-julia 0.4
-Calculus
-ForwardDiff 0.3.0 0.5.0
+julia 0.6.0-pre
 PositiveFactorizations
 Compat 0.18.0
-LineSearches 0.1.2 1.0.0-
+LineSearches 2.1.0
+Calculus
+NLSolversBase 2.1.0
+ForwardDiff 0.5.0
```
cc: @pkofod

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds are up to date.

### CODE REVIEW

**Comment by pkofod** [comment]
Let's see if this passes

**Comment by tkelman** [comment]
Looks like DiffEqParamEstim has a method error - should there be deprecations in place for most renamed things?

**Comment by pkofod** [comment]
> Looks like DiffEqParamEstim has a method error - should there be deprecations in place for most renamed things?

Yes, this should be depreacted.

**Comment by pkofod** [comment]
> Yes, this should be depreacted.

Hmm, I don't really see how I can deprecate this. LsqFit needs to merge https://github.com/JuliaNLSolvers/LsqFit.jl/pull/48 but that won't work before this is tagged. Next step would be to move all of this machinery to NLSolversBase.jl

**Comment by pkofod** [comment]
> Hmm, I don't really see how I can deprecate this. LsqFit needs to merge JuliaNLSolvers/LsqFit.jl#48 but that won't work before this is tagged. Next step would be to move all of this machinery to NLSolversBase.jl

We can solve it by copying the type code to NLsolve and tagging NLsolve before tagging this?

**Comment by tkelman** [comment]
DiffEqParamEstim is still showing a regression from this?

**Comment by pkofod** [comment]
Yes, but that is because it ran before lsqfit was merged right ? Lsqfit shows v0.2.0

**Pull request merged**
