### PR TITLE
Register new package ClosedIntervals.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [scheinerman/ClosedIntervals.jl](https://github.com/scheinerman/ClosedIntervals.jl)
Release: [v0.1.0](https://github.com/scheinerman/ClosedIntervals.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/scheinerman/ClosedIntervals.jl/builds/416990732)
cc: @scheinerman

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@scheinerman This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by dpsanders** [comment]
This looks similar to https://github.com/JuliaMath/IntervalSets.jl?

**Comment by scheinerman** [comment]
Yes. The `IntervalSets` is the same idea as my `ClosedIntervals`. I have some added functionality (e.g., comparisons) and a different philosophy on union, but otherwise quite the same.

**Comment by quinnj** [comment]
The REQUIRE says `julia 0.6`, but travis testing is for `0.7` and `1.0`; please update REQUIRE to `julia 0.7` or enable 0.6 testing on travis.

**Comment by scheinerman** [comment]
I updated the REQUIRE

**Comment by andreasnoack** [comment]
Please also update this PR. See https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by timholy** [comment]
To be fair, I think ClosedIntervals was around (unregistered) even before IntervalSets. But we found we couldn't use it for our geometrical needs because of behaviors like
```julia
julia> i = ClosedInterval(2, 1.9)
[1.9,2.0]
```
and the consequent inability to create an empty interval based purely on the values you supply to the constructor (in much the way that `1:0` creates an empty `UnitRange`).

**Comment by scheinerman** [comment]
`CloseIntervals` provides an empty interval, but it's not built by giving endpoints. I understand there are different philosophies on how to do this. I think of `[a,b]` as the convex hull of the two endpoints and that works well for me. Also, we differ on how unions are handled. I'm OK with there being two different approaches.

**Pull request merged**
