### PR TITLE
Tag StatsBase.jl v0.14.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaStats/StatsBase.jl](https://github.com/JuliaStats/StatsBase.jl)
Release: [v0.14.1](https://github.com/JuliaStats/StatsBase.jl/releases/tag/v0.14.1)
Diff: [vs v0.14.0](https://github.com/JuliaStats/StatsBase.jl/compare/38c62a15e2e3b24c732f9b90b7ded1abc83ce6ad...e200a7299a40e1f9d719179b98968542edc19f3c)
`requires` vs v0.14.0: no changes
cc: @ararslan

### CODE REVIEW

**Comment by tkelman** [comment]
will this fix DataArrays, ImageMetadata, and/or ImageTransformations? https://github.com/JuliaLang/METADATA.jl/pull/9083#issuecomment-298817852

**Comment by ararslan** [comment]
Probably not, but it fixes LightGraphs

**Comment by tkelman** [comment]
K. Any idea what's wrong with DataArrays then?

The Image* are showing that StatsBase has some ambiguities. Should probably enable ambiguity testing within StatsBase to avoid that going forward

**Comment by ararslan** [comment]
> Any idea what's wrong with DataArrays then?

Not yet. :/

> Should probably enable ambiguity testing within StatsBase to avoid that going forward

I'm actually not sure how to do that, but it sounds like a good idea.

**Comment by tkelman** [comment]
something like https://github.com/JuliaImages/ImageTransformations.jl/blob/ee9d5267309b2bce35be6c592ee376188120d82d/test/runtests.jl#L4-L7, there are a few variations out there

@timholy may have advice on the latest best-practice version of that

**Comment by ararslan** [comment]
Turns out DataArrays had a weird case that we were testing but it doesn't actually make sense and was broken by a refactor of the weighting code in StatsBase. Our solution is to remove the test case in DataArrays.

**Pull request merged**
