### PR TITLE
Register new package POMDPModelTools.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaPOMDP/POMDPModelTools.jl](https://github.com/JuliaPOMDP/POMDPModelTools.jl)
Release: [v0.1.0](https://github.com/JuliaPOMDP/POMDPModelTools.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaPOMDP/POMDPModelTools.jl/builds/421825520)
cc: @MaximeBouton

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

@MaximeBouton This PR will remain open for 24 hours for feedback (which is optional). If you get feedback, please let us know if you are making changes, and we'll merge once you're done.

### CODE REVIEW

**Comment by MaximeBouton** [comment]
We are not sure why the JuliaCIBot is failing, any ideas?

**Comment by andreasnoack** [comment]
The reason is that CIBot is (unfortunately) still based on the old package manager and it will, therefore, fail when there is a project file checked in. I'd recommend that you delete the project files from your repos for the time being since they aren't needed yet and it will allow the dependency testing to work.

**Comment by MaximeBouton** [comment]
Thanks, what is the easiest way to delete the file, should I delete this release and create a new one?

**Comment by MaximeBouton** [comment]
If I remove the Project.toml, the travis build is failing with: 
```
ERROR: The following package names could not be resolved:
 * POMDPModelTools (not found in project or manifest)
Please specify by known `name=uuid`.
```
https://github.com/JuliaPOMDP/POMDPModelTools.jl

**Comment by andreasnoack** [comment]
Could you try to remove https://github.com/JuliaPOMDP/POMDPModelTools.jl/blob/master/.travis.yml#L10-L12 from the script?

**Comment by MaximeBouton** [comment]
If I comment them out the build passes. Would you suggest restoring the build script and the Project.toml file on the master branch after it is registered?

**Comment by MaximeBouton** [comment]
JuliaCIBot says 
```
ERROR: LoadError: ArgumentError: Package Distributions [31c24e10-a181-5473-b8eb-7969acd0382f] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```

but a few line above I see 
```
[ Info: Installing Distributions v0.16.2
```
any ideas?

**Comment by andreasnoack** [comment]
> Would you suggest restoring the build script and the `Project.toml` file on the master branch after it is registered?

No. It's better to use the default build script and I'd suggest that you wait with adding a project file until it is needed. We'll continue using REQUIRE for a little longer.

**Comment by andreasnoack** [comment]
The reason why the tests fail is that POMDPs.jl also has a project file.

**Comment by MaximeBouton** [comment]
Ok thanks
I removed it from POMDPs.jl 
Can we restart the build once JuliaLang/METADATA.jl#17499 is merged?

**Comment by MaximeBouton** [comment]
Unsure why the travis build is still pending.

**Comment by andreasnoack** [comment]
Looks like a bug since the tests have finished. I'll restart.

**Comment by MaximeBouton** [comment]
Thanks!

**Pull request merged**
