### PR TITLE
Tag Hiccup v0.1.0 [https://github.com/JunoLab/Hiccup.jl]

### PR DESCRIPTION
**Pull request by ranjanan**
Fixes https://github.com/JunoLab/Hiccup.jl/issues/17

cc: @andreasnoack

### CODE REVIEW

**Comment by andreasnoack** [comment]
@ranjanan Thanks. There is a test error that suggests that you should tag a minor version instead of a patch version.

**Comment by tkelman** [comment]
also should adjust travis so it runs on the supported release versions of Julia

**Comment by tkelman** [comment]
looks like this won't work correctly unless MacroTools is tagged first

**Comment by andreasnoack** [comment]
@ranjanan Are you able to tag MacroTools or is @MikeInnes the only person who can do that? It would be great if these things could be resolved fairly fast since this causes everything that depends on `DataFrames` (115 packages) to fail on master.

**Comment by andreasnoack** [comment]
The changes hasn't taken effect here https://github.com/JunoLab/Hiccup.jl/releases. Probably simplest to retag with attobot

**Comment by andreasnoack** [comment]
Superseded by https://github.com/JuliaLang/METADATA.jl/pull/7355

**Pull request closed without merging**
