### PR TITLE
Tag PAINTER v0.2.0

### PR DESCRIPTION
**Pull request by andferrari**

### CODE REVIEW

**Comment by tkelman** [comment]
Needs a Julia version requirement

**Comment by tkelman** [comment]
Also note that using the PPA on Travis is deprecated, `language: julia` will let you more easily test against older and the most recent versions of Julia.

**Comment by andferrari** [comment]
> Le 23 mars 2016 à 10:35, Tony Kelman <notifications@github.com> a écrit :
> 
> Needs a Julia version requirement


thanks, I will add the line.

**Comment by andferrari** [comment]
> Le 23 mars 2016 à 14:43, Tony Kelman <notifications@github.com> a écrit :
> 
> Also note that using the PPA on Travis is deprecated, language: julia will let you more easily test against older and the most recent versions of Julia.

thanks again! 
I have messed up the pull request and submitted a new one.

**Pull request closed without merging**
