### PR TITLE
Register new package ReactiveExtensions.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [yuehhua/ReactiveExtensions.jl](https://github.com/yuehhua/ReactiveExtensions.jl)
Release: [v0.0.1](https://github.com/yuehhua/ReactiveExtensions.jl/releases/tag/v0.0.1)
Travis: [Travis Build Status](https://travis-ci.org/yuehhua/ReactiveExtensions.jl/builds/209760311)
cc: @yuehhua

### CODE REVIEW

**Comment by timholy** [comment]
Overlap with Reactive.jl should be explained.

**Comment by yuehhua** [comment]
They are similar, but not the same.
For reactive programming, I expect the way to chaining things up, and it can be something like the following.

```
foo = from([1,2,3,4,5]).map(x -> x + 1).tolist()
```

But the [Reactive.jl](https://github.com/JuliaGizmos/Reactive.jl) is not in this way.
It separate the steps line by line.
If I follow the way, I will get the code hard to read.
Rather, I think the [RxPY](https://github.com/ReactiveX/RxPY) can provide better readability.

**Comment by tkelman** [comment]
What's the verdict here w.r.t. https://github.com/JuliaGizmos/Reactive.jl/issues/127 then? Do you still want to register and develop this as an independent package, or pursue feature additions to the existing Reactive.jl?

**Comment by yuehhua** [comment]
Oh! I plan to add features to Reactive.jl.
Sorry for delay.
Can you cancel this pull request for me?

**Comment by tkelman** [comment]
No problem.

**Pull request closed without merging**
