### PR TITLE
Tag StackTraces v0.0.3

### PR DESCRIPTION
**Pull request by spurll**

### CODE REVIEW

**Comment by tkelman** [comment]
:+1:

**Comment by jakebolewski** [comment]
I feel like this (limited) functionality should be in `Base`.

**Comment by spurll** [comment]
Can't say as I disagree. Thanks. :smile:

**Comment by jakebolewski** [comment]
Can you open an issue?

**Comment by spurll** [comment]
I'll do it first thing in the morning.

**Comment by spurll** [comment]
Done: https://github.com/JuliaLang/julia/issues/14212

**Pull request merged**
