### PR TITLE
Tag MixedModels v0.4.5

### PR DESCRIPTION
**Pull request by dmbates**
Releasing this version should be coordinated with releasing StatsBase 0.8.0

### CODE REVIEW

**Comment by tkelman** [comment]
Does this need to add upper bounds on the StatsBase dependency for past versions?

**Comment by nalimilan** [comment]
I didn't know we could alter older versions after the fact, that's cool. Indeed, this would prevent some trouble. @dmbates Can you do it, or do you prefer me to push the changes to this branch?

What's the problem with Travis CI?
>     MixedModels v0.4.5 – no valid versions exist for package Showoff

**Comment by tkelman** [comment]
I think the error message is just wrong there. `StatsBase 0.8.0` is not yet tagged.

**Comment by dmbates** [comment]
@nalimilan Could you push the change in the REQUIRES file, please?  I'm waiting at the doctor's office and would probably botch it.

**Comment by dmbates** [comment]
@nalimilan I have added you as a collaborator on the MixedModels.jl repository so you can merge your changes.

**Comment by nalimilan** [comment]
Thanks, but the branch is hosted in your fork of METADATA, not in MixedModels. Anyway, I've made a new PR at https://github.com/JuliaLang/METADATA.jl/pull/4701.

**Pull request closed without merging**
