### PR TITLE
Register new package SwiftObjectStores.jl v0.1.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [oxinabox/SwiftObjectStores.jl](https://github.com/oxinabox/SwiftObjectStores.jl)
Release: [v0.1.0](https://github.com/oxinabox/SwiftObjectStores.jl/releases/tag/v0.1.0)
Travis: [Travis Build Status](https://travis-ci.org/oxinabox/SwiftObjectStores.jl/builds/204471215)
cc: @oxinabox

### CODE REVIEW

**Comment by oxinabox** [comment]
### Proposed name of the package:

```
SwiftObjectStores.jl
```

### One-line description:

```
Interface for storing and retrieving data from OpenStack Swift object stores
```
### Alternative package names:

> Give alternative package names (applicable if your package is not a wrapper of another package).

Swift
ObjectStores
OpenStackSwiftObjectStores.jl

### Documentation:

>  You are required to provide adequate documentation.
>  Confirm whether documentation is provided in README.md or give a link to the separate documentation

In README.md and fairly extensive use of docstrings, for what this is.

### Tests and continuous integration:

> Your package is required to have tests in the test/runtests.jl file,
> and to be linked to a continuous-integration service. Provide the relevant information.

Travis is enabled on the repository. Tests pass on 0.5.

AppVeyor is enabled on the repository.
However, requires some additional configuring to unbreak it, in terms of making sure the enviroment is set up.

Does not pass on the nightly, because PyCall does not currently build

### Related packages in the Julia ecosystem:

> Describe the similarities and differences with related packages.

 https://github.com/jerryzhenleicai/LevelDB.jl
LevelDB.jl is also a package for interactive with a key - value data store. But this is a different data store; based on different technology.

**Comment by tkelman** [comment]
missing Conda from REQUIRE

if you don't need to support 0.5 prereleases, drop the trailing dash

**Comment by dpsanders** [comment]
Thanks @oxinabox for trying out the package registration template. Do you have any comments about it? 

Can we try out requiring it (or similar) for all package registration PRs? It really makes it so much nicer to work out what the package is about and how it fits into the ecosystem.

**Comment by oxinabox** [comment]
@dpsanders I've actually used it before: https://github.com/JuliaLang/METADATA.jl/pull/6890

I really like it.
As a planning tool, and as a retrospective tool.
I think these are the kinds of questions you should be asking yourself when you start making a package,
and also the kinds of things it is good to reflect on when a package is done (at least for done being "registerable")

In #6890 it was also useful (using the other concerns field which is based on something else from the same kinds of issues in JuliaLang/METADATA.jl that connect with templates, to highlight issues that required consulting with others before it was completely clear that it could/should be registered.

**Pull request closed without merging**
