### PR TITLE
Tag DSGE.jl v0.1.3

### PR DESCRIPTION
**Pull request by attobot**
Repository: [FRBNY-DSGE/DSGE.jl](https://github.com/FRBNY-DSGE/DSGE.jl)
Release: [v0.1.3](https://github.com/FRBNY-DSGE/DSGE.jl/releases/tag/v0.1.3)
Diff: [vs v0.1.2](https://github.com/FRBNY-DSGE/DSGE.jl/compare/fff901bfee9c98d7f28289fd794085ff036b5ef5...81475397f0975e1f50c6910943f2d6fc7a0a0535)
`requires` vs v0.1.2: 
```diff
--- 0.1.2/requires
+++ 0.1.3/requires
@@ -2,7 +2,8 @@
 Calculus
 DataStructures
 Distributions
+FredData
 HDF5
-Optim 0.5 0.6
+Optim 0.5
 QuantEcon
 Roots
```
cc: @pearlzli

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by tkelman** [comment]
@pearlzli what's going on here, the v0.1.3 tag was made from b4ab96a39a4b24abc324e36fda79510d2cd1d4de in June 2016 (#5465). Past tags shouldn't be modified, it would be best if you could restore the git tag to the commit that it was previously. Thanks!

**Comment by pearlzli** [comment]
@tkelman Sorry about that - I thought I had just been editing the release notes. I'll work on restoring the git tags.

**Comment by tkelman** [comment]
No problem, I'll close the PR's here where the existing tags got modified. Release notes are useful, but yeah some of github's UI's can do weird unexpected things.

**Comment by pearlzli** [comment]
Thanks!

**Comment by pearlzli** [comment]
@tkelman Sorry, I realize I should have commented again instead of editing my previous comment. Could you delete the other non-v0.3.1 pull requests as well?

**Pull request closed without merging**
