### PR TITLE
Register SoArrays

### PR DESCRIPTION
**Pull request by simonster**

### CODE REVIEW

**Comment by tkelman** [comment]
So... what are SoArrays? Not an immediately obvious name to me.

**Comment by StefanKarpinski** [comment]
Agreed, not immediately obvious. I read it as "So..., Arrays."

**Comment by tkelman** [comment]
`HowBoutThemArrays.jl`

**Comment by johnmyleswhite** [comment]
Maybe better to go with the wordier `StructOfArrays`?

**Comment by StefanKarpinski** [comment]
`StructsOfArrays` to keep with the pluralization thing?

**Comment by johnmyleswhite** [comment]
Oh yeah, that's more correct.

**Comment by simonster** [comment]
Then should I rename the type itself to `StructOfArrays`? Or leave it as `SoArray`?

**Comment by StefanKarpinski** [comment]
That could go either way, but `StructOfArrays` is nice and obvious :-)

**Comment by simonster** [comment]
Registered as StructsOfArrays.

**Pull request closed without merging**
