### PR TITLE
Tag ArbFloats.jl v0.2.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaArbTypes/ArbFloats.jl](https://github.com/JuliaArbTypes/ArbFloats.jl)
Release: [v0.2.2](https://github.com/JuliaArbTypes/ArbFloats.jl/releases/tag/v0.2.2)
Diff: [vs v0.2.1](https://github.com/JuliaArbTypes/ArbFloats.jl/compare/4ea4126fea2038857b4428b8cbcf9cc291603b8b...f8c75f68e8bcee79afa708ac55f3816f1372cb31)
`requires` vs v0.2.1: 
```diff
--- 0.2.1/requires
+++ 0.2.2/requires
@@ -1,4 +1,4 @@
-julia 0.6.0
+julia 0.6.0 0.6.9
 BinDeps 0.4.5
 Compat 0.9.5
 Nemo 0.6.0
```
cc: @JeffreySarnoff

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by aviks** [comment]
Do you need both this and #12371 ?

**Comment by KristofferC** [comment]
This upper bounds is a bit weird. Did you mean to put `0.7`? Remember that upper bounds are exclusive.

**Comment by JeffreySarnoff** [comment]
this should have vanished (it should have been a local tag not a release) 
The intended release is https://github.com/JuliaLang/METADATA.jl/pull/12371

Let me know the right way to specify the Julia version span for REQUIRE:
this (12371) is good for versions 0.6.0 .. 0.6.<any> 
The next release will be a new subversion and works with 0.7.0-Dev .. forward only.

**Comment by JeffreySarnoff** [comment]
deleted tag

**Comment by aviks** [comment]
Closing. Let me know if that's incorrect.

**Comment by JeffreySarnoff** [comment]
Yes --  *closed*.

**Pull request closed without merging**
