### PR TITLE
Tag Chemfiles v0.8.0 [https://github.com/chemfiles/Chemfiles.jl]

### PR DESCRIPTION
**Pull request by Luthaf**
Diff vs v0.7.4: https://github.com/chemfiles/Chemfiles.jl/compare/4c7e430d16bdb672518e6572abfba5188cc6bf63...b9d515145f8c47b5660e1f52df9a7942410e6136

### CODE REVIEW

**Comment by Luthaf** [comment]
JuliaCIBot output is cut in the middle of the log, is this expected ?

**Comment by andreasnoack** [comment]
I've restarted the tests. Let's see if it was just a single bad run.

Please consider using https://github.com/attobot/attobot when making releases.

**Comment by andreasnoack** [comment]
Looks like an issue with CIBot

**Comment by Luthaf** [comment]
> Please consider using https://github.com/attobot/attobot when making releases.

I did not knew this existed! I'll give it a look for the next release.

**Pull request merged**
