### PR TITLE
Register new package DelayDiffEq.jl v0.0.1

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DelayDiffEq.jl](https://github.com/JuliaDiffEq/DelayDiffEq.jl)
Release: [v0.0.1](https://github.com/JuliaDiffEq/DelayDiffEq.jl/releases/tag/v0.0.1)
cc: @ChrisRackauckas

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
>DelayDiffEq v0.0.1 – no valid versions exist for package Combinatorics

This is likely because it was looking for https://github.com/JuliaLang/METADATA.jl/pull/7508 and https://github.com/JuliaLang/METADATA.jl/pull/7508

**Comment by ChrisRackauckas** [comment]
Can someone with commit privileges reset Travis?

**Comment by dpsanders** [comment]
I think you can just close and reopen the PR to reset Travis?

**Comment by dpsanders** [comment]
Oh but maybe you need priviliges to reopen.

**Comment by ChrisRackauckas** [comment]
You can't close a PR opened by attobot.

**Comment by simonbyrne** [comment]
I've kicked the buildbot, see how that goes.

Not sure if there's a way to automate that, but thankfully it doesn't occur too often.

**Comment by tkelman** [comment]
we could do an @attobot comment listener hook maybe?

**Comment by ChrisRackauckas** [comment]
This should be good: all tests are passing. When this is merged, Travis needs to be reset on https://github.com/JuliaLang/METADATA.jl/pull/7542 which completes this round of tags.

**Comment by ChrisRackauckas** [comment]
Thanks!

**Pull request merged**
