### PR TITLE
Register LSODA [http://github.com/rveltz/LSODA.jl]: v0.0.1

### PR DESCRIPTION
**Pull request by sdwfrost**

### CODE REVIEW

**Comment by tkelman** [comment]
You should not download master of an external resource. Use a fixed tag or sha so you don't risk this breaking if the file changes. All downloads should be versioned.

**Comment by sdwfrost** [comment]
I have updated build.jl to pull v0.1.0 of liblsoda. I've deleted the old release, as I want the first to be v0.0.1, and generated a new tag locally using PkgDev. What's the best way to go forward? I haven't used PkgDev.publish(), as this will open up a new PR (will it?).

**Comment by ChrisRackauckas** [comment]
Push the METADATA changes you made to the branch `sdwfrost:pull-request/f1d70cfc` on your METADATA fork.

**Comment by sdwfrost** [comment]
Superceded by [https://github.com/JuliaLang/METADATA.jl/pull/7266](https://github.com/JuliaLang/METADATA.jl/pull/7266).

**Pull request closed without merging**
