### PR TITLE
Tag LinearOperators.jl v0.5.2

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaSmoothOptimizers/LinearOperators.jl](https://github.com/JuliaSmoothOptimizers/LinearOperators.jl)
Release: [v0.5.2](https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/releases/tag/v0.5.2)
Travis: [Travis Build Status](https://travis-ci.org/JuliaSmoothOptimizers/LinearOperators.jl/builds/486720955)
Diff: [vs v0.5.1](https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/compare/c1f35a4ff85891d566e3857ab6dc569d9035fb22...591544b94f9ce132dbe23370a234c18bef45c944)
`requires` vs v0.5.1: no changes
cc: @abelsiqueira

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
@Xx-fractale-xX

**Comment by amontoison** [comment]
Great! Thank you Abel.

**Comment by dpo** [comment]
bump

**Comment by amontoison** [comment]
bump

**Comment by amontoison** [comment]
@andreasnoack 
Could you merge this pull request?
This new version corrects some memory problems. We are waiting it for updating other packages.

**Comment by andreasnoack** [comment]
@abelsiqueira Please avoid commenting on PRs before they are merged. It prevents them from being automatically merged.

**Comment by abelsiqueira** [comment]
Thanks.

**Pull request merged**
