### PR TITLE
Tag ScikitLearnBase and ScikitLearn 0.2.0

### PR DESCRIPTION
**Pull request by cstjean**

### CODE REVIEW

**Comment by cstjean** [comment]
I just realized that my 0.5 changes caused an issue on Julia 0.4, belatedly caught by travis. Hence I closed this PR, reset --hard my METADATA (since it [wouldn't update otherwise](https://github.com/JuliaLang/julia/issues/18113)) and tried to tag 0.2.1, but got `LoadError: 0.2.1 skips over 0.2.0`. Github already has a 0.2.0 tag. I suppose I could delete the tag from there, and retag 0.2.0? Or we could merge this PR with the bug, and I'll immediately tag 0.2.1. Which way sounds better?

**Comment by tkelman** [comment]
you could push an 0.2.1 tag into this same pr branch

**Comment by cstjean** [comment]
This was far from my git comfort zone, but I _think_ it's ok. Let me know if anything looks wrong.

**Comment by tkelman** [comment]
Don't do `Pkg.add` in `.travis.yml`, instead add `RDatasets` to a `test/REQUIRE` file

**Comment by cstjean** [comment]
I tried it and [got](https://travis-ci.org/cstjean/ScikitLearn.jl/jobs/166040495)

```julia
$ julia -e 'using Conda; Conda.add("scikit-learn")'
ERROR: ArgumentError: Module Conda not found in current path.
Run `Pkg.add("Conda")` to install the Conda package.
```

even though [`Conda` is in `test/REQUIRE`](https://github.com/cstjean/ScikitLearn.jl/blob/master/test/REQUIRE)

**Comment by tkelman** [comment]
test/REQUIRE packages get installed during Pkg.test

**Comment by cstjean** [comment]
Fixed it.

**Comment by tkelman** [comment]
Does that need an 0.2.2 tag then?

**Comment by cstjean** [comment]
I don't think so? I didn't change any of the code, just `test/REQUIRE` and `.travis.yml`. Do I need to tag again?

**Comment by tkelman** [comment]
`test/REQUIRE` does need re-tagging, yes

**Comment by cstjean** [comment]
Done.

**Comment by tkelman** [comment]
don't forget to push the git tag

**Comment by cstjean** [comment]
Yes, thank you for the reminder.

**Pull request merged**
