### PR TITLE
Tag DiffEqBase.jl v4.24.0

### PR DESCRIPTION
**Pull request by attobot**
Repository: [JuliaDiffEq/DiffEqBase.jl](https://github.com/JuliaDiffEq/DiffEqBase.jl)
Release: [v4.24.0](https://github.com/JuliaDiffEq/DiffEqBase.jl/releases/tag/v4.24.0)
Travis: [Travis Build Status](https://travis-ci.org/JuliaDiffEq/DiffEqBase.jl/builds/419886153)
Diff: [vs v4.23.4](https://github.com/JuliaDiffEq/DiffEqBase.jl/compare/2b70cf5a515e6b1b9ad6d7163087befdb121ee0c...1b051267804c79d44b0cd7b6c9cc8cddb4dc09c4)
`requires` vs v4.23.4: 
```diff
--- 4.23.4/requires
+++ 4.24.0/requires
@@ -4,5 +4,6 @@
 Compat 0.19.0
 Requires
 IteratorInterfaceExtensions 0.1.0
+StaticArrays 0.8.3
 TableTraits 0.3.0
 TreeViews
```
cc: @ChrisRackauckas

Please make sure that:
- CI passes for supported Julia versions (if applicable).
- Version bounds reflect minimum requirements.

### CODE REVIEW

**Comment by andreasnoack** [comment]
It looks like tests are failing.

**Comment by ChrisRackauckas** [comment]
yup re-tagging soon.

**Comment by andreasnoack** [comment]
CIBot reports this error
```julia
High Level solve Interface: Test Failed at /home/jrun/DiffEqBase/.julia/v1.0/DiffEqBase/test/high_level_solve.jl:17
  Expression: typeof(prob2.u0) == Float64
   Evaluated: Normal{Float64} == Float64
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] include(::String) at ./client.jl:388
 [6] top-level scope at /home/jrun/DiffEqBase/.julia/v1.0/DiffEqBase/test/runtests.jl:6
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] exec_options(::Base.JLOptions) at ./client.jl:229
 [11] _start() at ./client.jl:421
```

**Comment by ChrisRackauckas** [comment]
Is JuliaCIBot known to be incompatible with Requires? The missing method is defined in an __init__() call with `@requires`. Travis, AppVeyor and JuliaCIBot all have the same version of Distributions so since it works on the first two I'd assume it would work on the latter.

**Comment by andreasnoack** [comment]
Yes. CIBot is still based on the old package manager so specifying packages by UUID doesn't work. So no reverse dependency testing for you yet.

**Pull request merged**
